/**
 * 영어 기초 빈도어 리스트 (GSL/NGSL 상위 빈도 기반, 소문자).
 *
 * 용도: 어휘 레벨 진단의 상위 밴드(L4+ 모의고사 단어장)에서 기초 단어 출제 제외.
 * 모고 단어장은 시험 지문에서 추출돼 situation/experience 같은 기본어가 섞여 있는데,
 * 하위 밴드 "교재 표제어" 제외만으로는 못 거른다 (교재에 없는 기본어가 많음) → 이 리스트로 보강.
 *
 * ⚠️ L1~L3(중등 교재 밴드)에는 적용하지 말 것 — 중등 교재 표제어가 곧 기초 단어라 풀이 무너진다.
 * 여기 없는 단어가 출제되는 건 괜찮다(필터는 보수적으로) — 반대로 어려운 단어를 잘못 넣지 말 것.
 */

const WORDS = [
  // ── 대명사·한정사·기능어 (모고 리스트에 간혹 섞임)
  'a', 'an', 'the', 'this', 'that', 'these', 'those', 'some', 'any', 'each', 'every', 'all', 'both',
  'few', 'many', 'much', 'more', 'most', 'other', 'another', 'such', 'same', 'own', 'either', 'neither',
  'something', 'anything', 'nothing', 'everything', 'someone', 'anyone', 'everyone', 'nobody',
  // ── 기본 동사
  'be', 'have', 'do', 'say', 'get', 'make', 'go', 'know', 'take', 'see', 'come', 'think', 'look',
  'want', 'give', 'use', 'find', 'tell', 'ask', 'work', 'seem', 'feel', 'try', 'leave', 'call',
  'need', 'become', 'mean', 'keep', 'let', 'begin', 'start', 'show', 'hear', 'play', 'run', 'move',
  'like', 'live', 'believe', 'hold', 'bring', 'happen', 'write', 'sit', 'stand', 'lose', 'pay',
  'meet', 'include', 'continue', 'set', 'learn', 'change', 'lead', 'understand', 'watch', 'follow',
  'stop', 'create', 'speak', 'read', 'spend', 'grow', 'open', 'close', 'walk', 'win', 'teach',
  'offer', 'remember', 'consider', 'appear', 'buy', 'sell', 'wait', 'serve', 'die', 'send', 'build',
  'stay', 'fall', 'cut', 'reach', 'kill', 'raise', 'pass', 'decide', 'return', 'explain', 'hope',
  'develop', 'carry', 'break', 'receive', 'agree', 'support', 'hit', 'produce', 'eat', 'cover',
  'catch', 'draw', 'choose', 'wear', 'fight', 'throw', 'fill', 'save', 'drop', 'push', 'pull',
  'turn', 'wish', 'drive', 'ride', 'fly', 'swim', 'sing', 'dance', 'jump', 'climb', 'cook', 'clean',
  'wash', 'help', 'visit', 'enjoy', 'love', 'hate', 'prefer', 'want', 'plan', 'study', 'practice',
  'answer', 'question', 'talk', 'listen', 'smile', 'laugh', 'cry', 'sleep', 'wake', 'dream', 'rest',
  'add', 'count', 'check', 'test', 'try', 'share', 'join', 'invite', 'welcome', 'thank', 'forget',
  'remind', 'repeat', 'finish', 'complete', 'end', 'arrive', 'travel', 'stay', 'wait', 'hurry',
  'realize', 'recognize', 'notice', 'imagine', 'guess', 'suppose', 'expect', 'suggest', 'describe',
  'discuss', 'mention', 'report', 'express', 'introduce', 'improve', 'increase', 'decrease', 'reduce',
  'protect', 'prevent', 'prepare', 'provide', 'require', 'allow', 'accept', 'refuse', 'avoid',
  'achieve', 'attend', 'belong', 'borrow', 'lend', 'cause', 'compare', 'collect', 'connect',
  'contain', 'control', 'cost', 'cross', 'deliver', 'depend', 'design', 'destroy', 'disappear',
  'discover', 'divide', 'earn', 'encourage', 'enter', 'exist', 'fail', 'succeed', 'fix', 'repair',
  'happen', 'hide', 'hurt', 'invent', 'judge', 'lay', 'lie', 'manage', 'marry', 'matter', 'measure',
  'miss', 'mix', 'obtain', 'occur', 'order', 'organize', 'perform', 'pick', 'place', 'point',
  'pour', 'press', 'print', 'promise', 'prove', 'record', 'remain', 'remove', 'replace', 'reply',
  'respect', 'respond', 'rise', 'roll', 'rush', 'search', 'seek', 'select', 'shake', 'shape',
  'shoot', 'shout', 'sign', 'solve', 'sound', 'spell', 'spread', 'steal', 'stick', 'suffer',
  'supply', 'surprise', 'survive', 'taste', 'tear', 'touch', 'train', 'treat', 'trust', 'wonder',
  'worry', 'wrap', 'burn', 'beat', 'blow', 'boil', 'bake', 'brush', 'celebrate', 'change', 'charge',
  'chat', 'cheer', 'communicate', 'complain', 'concentrate', 'confuse', 'copy', 'correct', 'crash',
  'date', 'decorate', 'delay', 'dig', 'disagree', 'download', 'dress', 'drink', 'drop', 'exercise',
  'feed', 'float', 'fold', 'freeze', 'fry', 'gather', 'greet', 'hang', 'hug', 'hunt', 'kick',
  'knock', 'lift', 'lock', 'melt', 'nod', 'pack', 'paint', 'park', 'pause', 'phone', 'plant',
  'pollute', 'pray', 'prepare', 'punish', 'recycle', 'relax', 'remember', 'rent', 'ring', 'sail',
  'score', 'scream', 'shine', 'ski', 'slide', 'slip', 'smell', 'sneeze', 'spend', 'stretch',
  'surf', 'sweep', 'swing', 'text', 'tie', 'upload', 'wave', 'weigh', 'whisper', 'yell', 'behave',
  'bother', 'breathe', 'chase', 'crawl', 'disturb', 'escape', 'explore', 'feed', 'flow', 'fold',
  'graduate', 'grab', 'heal', 'ignore', 'lean', 'march', 'obey', 'owe', 'own', 'pat', 'pretend',
  'raise', 'recover', 'regret', 'rub', 'scratch', 'settle', 'sew', 'shut', 'spill', 'spin',
  'split', 'squeeze', 'stare', 'suck', 'swallow', 'trade', 'trick', 'volunteer', 'vote', 'wander',
  'warn', 'waste', 'wipe', 'concern', 'recommend', 'favor', 'attack', 'rapid', 'award', 'wound',
  // ── 기본 명사
  'time', 'year', 'people', 'way', 'day', 'man', 'woman', 'child', 'children', 'world', 'life',
  'hand', 'part', 'eye', 'place', 'week', 'case', 'point', 'group', 'number', 'fact', 'home',
  'water', 'room', 'mother', 'father', 'area', 'money', 'story', 'month', 'book', 'word', 'side',
  'kind', 'head', 'house', 'friend', 'power', 'hour', 'game', 'line', 'city', 'name', 'team',
  'minute', 'idea', 'body', 'face', 'level', 'door', 'health', 'person', 'art', 'war', 'history',
  'result', 'morning', 'reason', 'girl', 'boy', 'food', 'moment', 'air', 'teacher', 'student',
  'school', 'force', 'education', 'foot', 'feet', 'music', 'sound', 'voice', 'light', 'heart',
  'question', 'answer', 'road', 'street', 'car', 'bus', 'train', 'plane', 'ship', 'boat', 'bike',
  'animal', 'dog', 'cat', 'bird', 'fish', 'horse', 'tree', 'flower', 'plant', 'garden', 'park',
  'mountain', 'river', 'sea', 'ocean', 'lake', 'beach', 'island', 'sky', 'sun', 'moon', 'star',
  'rain', 'snow', 'wind', 'cloud', 'weather', 'season', 'spring', 'summer', 'autumn', 'winter',
  'color', 'paper', 'letter', 'news', 'newspaper', 'magazine', 'picture', 'photo', 'movie', 'film',
  'television', 'radio', 'computer', 'phone', 'internet', 'website', 'email', 'message', 'video',
  'family', 'parent', 'brother', 'sister', 'son', 'daughter', 'baby', 'grandmother', 'grandfather',
  'uncle', 'aunt', 'cousin', 'neighbor', 'doctor', 'nurse', 'police', 'officer', 'driver', 'farmer',
  'cook', 'chef', 'singer', 'actor', 'artist', 'writer', 'scientist', 'engineer', 'lawyer', 'job',
  'work', 'office', 'company', 'business', 'store', 'shop', 'market', 'restaurant', 'hotel',
  'hospital', 'library', 'museum', 'church', 'station', 'airport', 'bank', 'post office', 'factory',
  'farm', 'building', 'apartment', 'kitchen', 'bathroom', 'bedroom', 'window', 'wall', 'floor',
  'roof', 'table', 'chair', 'desk', 'bed', 'sofa', 'lamp', 'clock', 'watch', 'mirror', 'key',
  'bag', 'box', 'bottle', 'cup', 'glass', 'plate', 'bowl', 'knife', 'fork', 'spoon', 'dish',
  'breakfast', 'lunch', 'dinner', 'meal', 'snack', 'bread', 'rice', 'meat', 'chicken', 'beef',
  'pork', 'egg', 'milk', 'cheese', 'butter', 'sugar', 'salt', 'pepper', 'oil', 'soup', 'salad',
  'fruit', 'apple', 'banana', 'orange', 'grape', 'strawberry', 'vegetable', 'potato', 'tomato',
  'onion', 'carrot', 'corn', 'bean', 'juice', 'coffee', 'tea', 'cake', 'cookie', 'candy',
  'chocolate', 'ice cream', 'pizza', 'sandwich', 'hamburger', 'noodle', 'clothes', 'shirt',
  'pants', 'skirt', 'dress', 'coat', 'jacket', 'sweater', 'shoes', 'socks', 'hat', 'cap',
  'gloves', 'scarf', 'umbrella', 'pocket', 'button', 'ring', 'glasses', 'money', 'price', 'size',
  'gift', 'present', 'card', 'ticket', 'map', 'plan', 'trip', 'vacation', 'holiday', 'party',
  'birthday', 'wedding', 'festival', 'event', 'concert', 'show', 'stage', 'club', 'member',
  'sport', 'soccer', 'baseball', 'basketball', 'tennis', 'volleyball', 'golf', 'race', 'player',
  'coach', 'ball', 'goal', 'score', 'prize', 'winner', 'match', 'practice', 'exercise', 'gym',
  'health', 'sickness', 'cold', 'fever', 'headache', 'medicine', 'pill', 'accident', 'danger',
  'fire', 'smoke', 'noise', 'problem', 'trouble', 'mistake', 'error', 'chance', 'luck', 'hope',
  'dream', 'wish', 'plan', 'goal', 'purpose', 'choice', 'decision', 'opinion', 'thought', 'mind',
  'memory', 'feeling', 'emotion', 'joy', 'fun', 'pleasure', 'happiness', 'sadness', 'anger',
  'fear', 'surprise', 'interest', 'attention', 'care', 'effort', 'energy', 'strength', 'skill',
  'ability', 'talent', 'habit', 'culture', 'language', 'english', 'math', 'science', 'subject',
  'class', 'lesson', 'homework', 'exam', 'test', 'grade', 'course', 'club', 'uniform', 'rule',
  'law', 'government', 'country', 'nation', 'state', 'president', 'king', 'queen', 'leader',
  'war', 'peace', 'army', 'soldier', 'weapon', 'past', 'present', 'future', 'century', 'age',
  'period', 'date', 'today', 'tomorrow', 'yesterday', 'tonight', 'weekend', 'noon', 'midnight',
  'north', 'south', 'east', 'west', 'top', 'bottom', 'middle', 'center', 'front', 'back',
  'corner', 'edge', 'end', 'beginning', 'distance', 'space', 'earth', 'land', 'ground', 'soil',
  'rock', 'stone', 'sand', 'gold', 'silver', 'iron', 'metal', 'wood', 'leaf', 'branch', 'root',
  'seed', 'grass', 'insect', 'bee', 'butterfly', 'ant', 'spider', 'snake', 'frog', 'rabbit',
  'mouse', 'bear', 'lion', 'tiger', 'elephant', 'monkey', 'sheep', 'cow', 'pig', 'duck', 'wing',
  'tail', 'skin', 'hair', 'nose', 'mouth', 'ear', 'tooth', 'teeth', 'neck', 'shoulder', 'arm',
  'finger', 'leg', 'knee', 'blood', 'bone', 'brain', 'stomach', 'situation', 'experience',
  'information', 'knowledge', 'system', 'service', 'program', 'project', 'activity', 'action',
  'process', 'method', 'model', 'example', 'type', 'form', 'style', 'item', 'list', 'note',
  'page', 'title', 'topic', 'subject', 'detail', 'value', 'quality', 'condition', 'position',
  'direction', 'section', 'material', 'product', 'machine', 'tool', 'device', 'button', 'screen',
  'technology', 'nature', 'environment', 'pollution', 'trash', 'garbage', 'waste', 'society',
  'community', 'public', 'human', 'individual', 'person', 'customer', 'guest', 'visitor',
  'audience', 'crowd', 'partner', 'relationship', 'conversation', 'discussion', 'speech',
  'advice', 'suggestion', 'invitation', 'promise', 'secret', 'truth', 'lie', 'joke', 'story',
  'novel', 'poem', 'sentence', 'phrase', 'meaning', 'symbol', 'sign', 'mark', 'number', 'amount',
  'total', 'half', 'quarter', 'percent', 'shape', 'circle', 'square', 'triangle', 'line', 'row',
  'pair', 'couple', 'piece', 'part', 'whole', 'rest', 'difference', 'change', 'growth', 'step',
  'stage', 'grade', 'speed', 'weight', 'height', 'length', 'temperature', 'degree', 'setting',
  'path', 'trail', 'bridge', 'gate', 'fence', 'sidewalk', 'block', 'town', 'village', 'capital',
  'address', 'guide', 'tour', 'passport', 'luggage', 'departure', 'arrival', 'schedule',
  // ── 기본 형용사·부사
  'good', 'new', 'first', 'last', 'long', 'great', 'little', 'old', 'right', 'big', 'high',
  'different', 'small', 'large', 'next', 'early', 'young', 'important', 'public', 'bad', 'able',
  'best', 'better', 'sure', 'free', 'low', 'late', 'hard', 'easy', 'strong', 'weak', 'true',
  'false', 'real', 'full', 'empty', 'whole', 'clear', 'dark', 'bright', 'light', 'heavy', 'warm',
  'cool', 'hot', 'cold', 'wet', 'dry', 'clean', 'dirty', 'fresh', 'nice', 'fine', 'happy', 'sad',
  'angry', 'afraid', 'scared', 'tired', 'sleepy', 'hungry', 'thirsty', 'sick', 'healthy', 'safe',
  'dangerous', 'careful', 'busy', 'quiet', 'loud', 'noisy', 'fast', 'slow', 'quick', 'ready',
  'famous', 'popular', 'special', 'common', 'normal', 'usual', 'strange', 'funny', 'serious',
  'simple', 'difficult', 'possible', 'impossible', 'necessary', 'useful', 'helpful', 'kind',
  'friendly', 'polite', 'rude', 'honest', 'brave', 'smart', 'clever', 'wise', 'foolish', 'silly',
  'lazy', 'diligent', 'proud', 'shy', 'nervous', 'excited', 'bored', 'boring', 'interesting',
  'exciting', 'amazing', 'wonderful', 'beautiful', 'pretty', 'handsome', 'ugly', 'cute', 'lovely',
  'expensive', 'cheap', 'rich', 'poor', 'main', 'major', 'minor', 'central', 'local', 'national',
  'international', 'foreign', 'global', 'modern', 'ancient', 'traditional', 'recent', 'current',
  'final', 'perfect', 'complete', 'certain', 'similar', 'equal', 'thick', 'thin', 'fat', 'wide',
  'narrow', 'deep', 'shallow', 'tall', 'short', 'round', 'flat', 'sharp', 'smooth', 'rough',
  'soft', 'hard', 'tight', 'loose', 'near', 'close', 'far', 'inside', 'outside', 'upstairs',
  'downstairs', 'everywhere', 'somewhere', 'anywhere', 'nowhere', 'always', 'usually', 'often',
  'sometimes', 'rarely', 'never', 'again', 'once', 'twice', 'already', 'yet', 'still', 'just',
  'even', 'also', 'too', 'very', 'quite', 'really', 'almost', 'enough', 'together', 'alone',
  'early', 'soon', 'later', 'ago', 'now', 'then', 'finally', 'suddenly', 'quickly', 'slowly',
  'carefully', 'easily', 'well', 'badly', 'hardly', 'nearly', 'especially', 'probably', 'maybe',
  'perhaps', 'actually', 'certainly', 'exactly', 'properly', 'ordinary', 'daily', 'weekly',
  'monthly', 'regularly', 'wrong', 'correct', 'delicious', 'tasty', 'sweet', 'sour', 'bitter',
  'salty', 'favorite', 'glad', 'sorry', 'welcome', 'lucky', 'unlucky', 'upset', 'lonely',
  'surprised', 'shocked', 'worried', 'confused', 'disappointed', 'satisfied', 'comfortable',
  'uncomfortable', 'convenient', 'inconvenient', 'terrible', 'horrible', 'awful', 'excellent',
  'fantastic', 'incredible', 'huge', 'giant', 'tiny', 'enormous', 'entire', 'extra', 'general',
  'particular', 'personal', 'private', 'natural', 'physical', 'mental', 'social', 'cultural',
  'economic', 'political', 'scientific', 'medical', 'digital', 'electronic', 'electric',
  // ── 자주 나오는 기본 숙어·구동사 (모고 리스트에 표제어로 등장)
  'a lot of', 'lots of', 'a few', 'a little', 'at first', 'at last', 'at least', 'at once',
  'in fact', 'in front of', 'in the end', 'for example', 'of course', 'right now', 'each other',
  'find out', 'give up', 'get up', 'wake up', 'stand up', 'sit down', 'come back', 'go back',
  'come in', 'go out', 'get out', 'get on', 'get off', 'put on', 'take off', 'take out',
  'take care of', 'look at', 'look for', 'look after', 'look forward to', 'listen to',
  'wait for', 'ask for', 'pay for', 'thanks to', 'because of', 'instead of', 'in addition to',
  'be able to', 'be good at', 'be interested in', 'be famous for', 'be full of', 'be late for',
  'be proud of', 'be different from', 'turn on', 'turn off', 'pick up', 'put off', 'help out',
  // ── 2차 확장 (2026-07-21): 중등 필수~고1 초입 수준 중간 빈도어.
  // 모고 단어장에 섞여 상위 밴드 라운드를 물렁하게 하던 단어들 — L5·L6 변별어는 넣지 말 것.
  'academic', 'accent', 'access', 'account', 'accurate', 'active', 'actual', 'adapt', 'adjust',
  'admire', 'admit', 'adopt', 'adult', 'advance', 'advantage', 'adventure', 'advertise', 'advice',
  'advise', 'affect', 'afford', 'agency', 'agent', 'aid', 'aim', 'alarm', 'alive', 'amazed',
  'ambition', 'amount', 'amuse', 'analyze', 'ancestor', 'announce', 'annual', 'anxious', 'apart',
  'apologize', 'apparent', 'appeal', 'apply', 'appointment', 'appreciate', 'approach', 'appropriate',
  'approve', 'argue', 'argument', 'arrange', 'arrest', 'article', 'ashamed', 'aspect', 'assign',
  'assist', 'assume', 'athlete', 'atmosphere', 'attach', 'attempt', 'attitude', 'attract',
  'attractive', 'author', 'authority', 'available', 'average', 'aware', 'awkward', 'background',
  'balance', 'ban', 'bare', 'bargain', 'barrier', 'base', 'basic', 'basis', 'battle', 'bear',
  'behavior', 'being', 'belief', 'benefit', 'besides', 'bet', 'beyond', 'bias', 'bill', 'bind',
  'biology', 'birth', 'bite', 'blame', 'blank', 'blend', 'bless', 'blind', 'block', 'bloom',
  'blossom', 'bold', 'bomb', 'bond', 'boost', 'border', 'bore', 'bound', 'brand', 'breath',
  'breed', 'brick', 'brief', 'brilliant', 'broad', 'broadcast', 'budget', 'bump', 'burden',
  'burst', 'bury', 'calculate', 'calm', 'campaign', 'cancel', 'cancer', 'capable', 'capacity',
  'capture', 'career', 'caution', 'cell', 'ceremony', 'certificate', 'challenge', 'channel',
  'chapter', 'character', 'characteristic', 'charity', 'charm', 'cheat', 'chemical', 'chemistry',
  'chief', 'childhood', 'chill', 'choir', 'chore', 'circumstance', 'cite', 'citizen', 'civil',
  'claim', 'classic', 'classify', 'client', 'climate', 'clue', 'code', 'collapse', 'colleague',
  'column', 'combine', 'comfort', 'command', 'comment', 'commercial', 'commit', 'committee',
  'compete', 'competition', 'complex', 'compose', 'concept', 'conclude', 'conclusion', 'concrete',
  'conduct', 'conference', 'confidence', 'confident', 'confirm', 'conflict', 'confront', 'congress',
  'conscious', 'consequence', 'conserve', 'consist', 'constant', 'construct', 'consult', 'consume',
  'contact', 'contemporary', 'content', 'contest', 'context', 'continent', 'contract', 'contrast',
  'contribute', 'convention', 'convince', 'cooperate', 'cope', 'core', 'corporation', 'costume',
  'cottage', 'council', 'courage', 'court', 'crack', 'craft', 'creature', 'credit', 'crew',
  'crime', 'crisis', 'criteria', 'critic', 'critical', 'criticize', 'crop', 'crucial', 'cruel',
  'cue', 'cultivate', 'cure', 'curious', 'currency', 'current', 'curriculum', 'custom', 'cycle',
  'dairy', 'debate', 'debt', 'decade', 'deceive', 'declare', 'decline', 'decrease', 'dedicate',
  'defeat', 'defend', 'define', 'definite', 'degree', 'delicate', 'delight', 'demand', 'democracy',
  'demonstrate', 'dense', 'deny', 'department', 'departure', 'depression', 'depth', 'derive',
  'deserve', 'desire', 'desperate', 'despite', 'detail', 'detect', 'determine', 'device', 'devote',
  'differ', 'digest', 'dignity', 'diligent', 'dim', 'diminish', 'diplomat', 'direct', 'disaster',
  'discipline', 'discount', 'discourage', 'disease', 'disgust', 'dismiss', 'display', 'dispose',
  'dispute', 'distance', 'distinct', 'distinguish', 'distract', 'distribute', 'district', 'disturb',
  'diverse', 'document', 'domestic', 'dominate', 'donate', 'dot', 'downtown', 'draft', 'drag',
  'dramatic', 'drift', 'drown', 'drug', 'due', 'dull', 'dump', 'durable', 'duty', 'dynamic',
  'eager', 'ecosystem', 'edge', 'edit', 'educate', 'effect', 'effective', 'efficient', 'elect',
  'element', 'eliminate', 'embarrass', 'embrace', 'emerge', 'emergency', 'emotion', 'emphasize',
  'empire', 'employ', 'enable', 'encounter', 'endure', 'enemy', 'engage', 'enhance', 'enormous',
  'ensure', 'enthusiastic', 'entrance', 'envelope', 'envy', 'equal', 'equipment', 'era', 'erase',
  'essay', 'essential', 'establish', 'estimate', 'ethnic', 'evaluate', 'eventually', 'evidence',
  'evident', 'evil', 'evolve', 'exact', 'examine', 'exchange', 'exclude', 'excuse', 'executive',
  'exhausted', 'exhibit', 'expand', 'expense', 'experiment', 'expert', 'expose', 'extend',
  'extent', 'external', 'extreme', 'facility', 'factor', 'faint', 'faith', 'fake', 'fame',
  'familiar', 'fancy', 'fare', 'fascinate', 'fate', 'fatigue', 'fault', 'feather', 'feature',
  'fee', 'feedback', 'fellow', 'fiction', 'fierce', 'figure', 'financial', 'firm', 'fit',
  'flavor', 'flexible', 'flood', 'fluent', 'focus', 'folk', 'fond', 'forbid', 'forecast',
  'formal', 'former', 'fortune', 'found', 'foundation', 'frame', 'frank', 'frequent', 'frontier',
  'frustrate', 'fuel', 'function', 'fund', 'fundamental', 'funeral', 'furniture', 'furthermore',
  'gain', 'gap', 'gaze', 'gender', 'gene', 'generate', 'generation', 'generous', 'genius',
  'genre', 'genuine', 'gesture', 'glance', 'glare', 'globe', 'glory', 'glow', 'good-looking',
  'govern', 'gradual', 'grain', 'grant', 'grateful', 'grave', 'greedy', 'grief', 'grocery',
  'guarantee', 'guilty', 'handle', 'harbor', 'harm', 'harsh', 'harvest', 'hesitate', 'hire',
  'holy', 'honor', 'horizon', 'horror', 'host', 'household', 'humble', 'humor', 'identify',
  'identity', 'illegal', 'illustrate', 'image', 'imitate', 'immediate', 'immigrant', 'impact',
  'imply', 'import', 'impress', 'incident', 'income', 'independent', 'indicate', 'industry',
  'infant', 'infect', 'influence', 'inform', 'ingredient', 'inherit', 'initial', 'injure',
  'innocent', 'innovation', 'insect', 'insert', 'insist', 'inspire', 'install', 'instance',
  'instant', 'instinct', 'institution', 'instruct', 'instrument', 'insult', 'insurance', 'intend',
  'intense', 'interact', 'interfere', 'internal', 'interpret', 'interrupt', 'interview',
  'intimate', 'invest', 'investigate', 'involve', 'irritate', 'isolate', 'issue', 'jealous',
  'journal', 'journey', 'justice', 'justify', 'keen', 'labor', 'laboratory', 'lack', 'landscape',
  'lately', 'latter', 'launch', 'layer', 'leak', 'leap', 'lecture', 'legal', 'legend', 'leisure',
  'liberty', 'license', 'likewise', 'limit', 'liquid', 'literature', 'load', 'loan', 'logic',
  'loyal', 'luxury', 'maintain', 'majority', 'manner', 'manual', 'manufacture', 'marine',
  'mass', 'master', 'mature', 'maximum', 'means', 'meanwhile', 'medium', 'mend', 'mercy',
  'mere', 'merit', 'mess', 'method', 'military', 'mineral', 'minimum', 'minister', 'minority',
  'miracle', 'miserable', 'mission', 'moderate', 'modest', 'modify', 'moral', 'moreover',
  'motion', 'motivate', 'multiple', 'multiply', 'murder', 'muscle', 'mutual', 'mystery',
  'narrative', 'nasty', 'navigate', 'neat', 'negative', 'neglect', 'negotiate', 'nerve',
  'nevertheless', 'noble', 'nonetheless', 'norm', 'notion', 'numerous', 'nutrition', 'obesity',
  'object', 'objective', 'obligation', 'observe', 'obstacle', 'obtain', 'obvious', 'occasion',
  'occupation', 'occupy', 'odd', 'offend', 'official', 'operate', 'opponent', 'opportunity',
  'oppose', 'opposite', 'optimistic', 'option', 'oral', 'orbit', 'organ', 'origin', 'otherwise',
  'outcome', 'outstanding', 'overall', 'overcome', 'overlook', 'overseas', 'overwhelm', 'owner',
  'oxygen', 'pace', 'panic', 'paradox', 'parallel', 'participate', 'particle', 'passenger',
  'passion', 'passive', 'patient', 'pattern', 'pedestrian', 'perceive', 'perception', 'perform',
  'permanent', 'permit', 'perspective', 'persuade', 'phenomenon', 'philosophy', 'phrase',
  'physician', 'pile', 'pioneer', 'pity', 'plain', 'plenty', 'plot', 'polish', 'political',
  'population', 'portion', 'portrait', 'possess', 'potential', 'pottery', 'poverty', 'practical',
  'praise', 'pray', 'precious', 'precise', 'predict', 'pregnant', 'prejudice', 'preserve',
  'pressure', 'pretend', 'previous', 'priest', 'primary', 'prime', 'principal', 'principle',
  'priority', 'privilege', 'procedure', 'proceed', 'profession', 'professor', 'profit',
  'progress', 'prohibit', 'project', 'prominent', 'promote', 'prompt', 'proof', 'proper',
  'property', 'proportion', 'proposal', 'propose', 'prospect', 'protein', 'protest', 'psychology',
  'publish', 'punctual', 'pupil', 'purchase', 'pure', 'pursue', 'puzzle', 'qualify', 'quantity',
  'quit', 'quote', 'random', 'range', 'rank', 'rate', 'rational', 'raw', 'react', 'reality',
  'reasonable', 'recall', 'recent', 'recipe', 'recognition', 'refer', 'reflect', 'reform',
  'refund', 'region', 'register', 'regular', 'reject', 'relate', 'relative', 'release',
  'relevant', 'relief', 'relieve', 'religion', 'religious', 'rely', 'remark', 'remarkable',
  'remote', 'repair', 'represent', 'reputation', 'request', 'require', 'rescue', 'research',
  'resemble', 'reserve', 'resident', 'resist', 'resolve', 'resource', 'restore', 'restrict',
  'retain', 'retire', 'reveal', 'revenge', 'reverse', 'review', 'revise', 'revolution', 'reward',
  'rid', 'ripe', 'risk', 'ritual', 'rival', 'roast', 'rotate', 'route', 'routine', 'royal',
  'rural', 'sacred', 'sacrifice', 'satellite', 'satisfy', 'scale', 'scarce', 'scatter', 'scene',
  'scenery', 'scheme', 'scholar', 'scold', 'scope', 'section', 'secure', 'seldom', 'sensible',
  'sensitive', 'sequence', 'session', 'severe', 'shade', 'shallow', 'shame', 'shelter', 'shift',
  'shortage', 'sibling', 'significant', 'silence', 'similar', 'sincere', 'site', 'situation',
  'slight', 'soak', 'soar', 'solid', 'solution', 'somewhat', 'sophisticated', 'sorrow', 'source',
  'souvenir', 'span', 'spare', 'species', 'specific', 'spectator', 'spirit', 'splendid', 'spoil',
  'spot', 'stable', 'stack', 'staff', 'standard', 'stapler', 'statistics', 'status', 'steady',
  'steep', 'stem', 'stimulate', 'stir', 'stock', 'strategy', 'stress', 'strict', 'strike',
  'strive', 'structure', 'struggle', 'stubborn', 'stuff', 'subject', 'submit', 'substance',
  'substitute', 'subtle', 'suburb', 'sufficient', 'suicide', 'suit', 'sum', 'summary',
  'superior', 'supervise', 'supreme', 'surface', 'surgery', 'surround', 'survey', 'suspect',
  'suspend', 'sustain', 'swear', 'sweat', 'swell', 'swift', 'sympathy', 'symptom', 'target',
  'task', 'temper', 'temperature', 'temporary', 'tempt', 'tend', 'tender', 'tense', 'term',
  'territory', 'theme', 'theory', 'therefore', 'thorough', 'threat', 'threaten', 'thrill',
  'thus', 'tidy', 'tissue', 'tone', 'tough', 'trace', 'track', 'tradition', 'tragedy',
  'transfer', 'transform', 'translate', 'transport', 'treasure', 'treatment', 'treaty',
  'tremendous', 'trend', 'trial', 'tribe', 'triumph', 'tropical', 'trunk', 'typical',
  'ultimate', 'undergo', 'undertake', 'unify', 'unique', 'unite', 'universal', 'universe',
  'urban', 'urge', 'urgent', 'usage', 'utility', 'vacant', 'vague', 'vain', 'valid', 'valley',
  'valuable', 'vary', 'vast', 'vehicle', 'venture', 'version', 'vertical', 'vessel', 'victim',
  'victory', 'violate', 'violent', 'virtual', 'virtue', 'visible', 'vision', 'vital', 'vivid',
  'vocabulary', 'voluntary', 'voyage', 'wage', 'wealth', 'weapon', 'weed', 'welfare', 'wheat',
  'whereas', 'whisper', 'widespread', 'willing', 'wisdom', 'wit', 'withdraw', 'witness',
  'worship', 'worth', 'wound', 'wreck', 'yield',
] as const;

/** 소문자 Set — 진단 상위 밴드(L4+) 출제 제외용 */
export const BASIC_ENGLISH_WORDS: ReadonlySet<string> = new Set(WORDS);
