-- ============================================================
-- 명사를 꾸며주는 분사 Step 3 — 서술형 60문항
-- template_topic: 명사를 꾸며주는 분사
-- category: problem, mode: interactive
-- Parts: 1(빈칸 분사형태 Q1-10), 2(어색한 부분 고치기 Q11-22),
--        3(두 문장 합치기 Q23-34), 4(관계대명사+be 생략 Q35-42),
--        5(감정분사 Q43-50), 6(조건 영작 Q51-60)
-- ============================================================

DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN

DELETE FROM naesin_templates WHERE title = E'명사를 꾸며주는 분사 Step 3';

-- ── q1: Part 1-2 (Q1–Q22) ──
q1 := jsonb_build_array(
    jsonb_build_object('number',1,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nLook at the ________ dog in the yard. (bark)',
      'type','short_answer',
      'answer',E'barking',
      'acceptedAnswers',jsonb_build_array('barking'),
      'explanation',E'개가 짖고 있는 중(능동/진행) → 현재분사 barking'),
    jsonb_build_object('number',2,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe ________ window needs to be fixed right away. (break)',
      'type','short_answer',
      'answer',E'broken',
      'acceptedAnswers',jsonb_build_array('broken'),
      'explanation',E'창문이 깨진 상태(수동/완료) → 과거분사 broken'),
    jsonb_build_object('number',3,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nI know the woman ________ next to the principal. (stand)',
      'type','short_answer',
      'answer',E'standing',
      'acceptedAnswers',jsonb_build_array('standing'),
      'explanation',E'여자가 서 있는 중(능동/진행) → 현재분사 standing'),
    jsonb_build_object('number',4,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nShe is reading a book ________ by a famous Korean author. (write)',
      'type','short_answer',
      'answer',E'written',
      'acceptedAnswers',jsonb_build_array('written'),
      'explanation',E'책이 쓰여진 것(수동/완료) → 과거분사 written'),
    jsonb_build_object('number',5,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe boy ________ soccer in the playground is my brother. (play)',
      'type','short_answer',
      'answer',E'playing',
      'acceptedAnswers',jsonb_build_array('playing'),
      'explanation',E'소년이 축구를 하고 있는 중(능동/진행) → 현재분사 playing'),
    jsonb_build_object('number',6,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThere were pieces of ________ glass on the kitchen floor. (break)',
      'type','short_answer',
      'answer',E'broken',
      'acceptedAnswers',jsonb_build_array('broken'),
      'explanation',E'유리가 깨진 상태(수동/완료) → 과거분사 broken'),
    jsonb_build_object('number',7,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThis is a bridge ________ the two towns. (connect)',
      'type','short_answer',
      'answer',E'connecting',
      'acceptedAnswers',jsonb_build_array('connecting'),
      'explanation',E'다리가 두 마을을 연결하고 있는 중(능동/진행) → 현재분사 connecting'),
    jsonb_build_object('number',8,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe people ________ to the ceremony all arrived on time. (invite)',
      'type','short_answer',
      'answer',E'invited',
      'acceptedAnswers',jsonb_build_array('invited'),
      'explanation',E'사람들이 초대받은 것(수동/완료) → 과거분사 invited'),
    jsonb_build_object('number',9,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nMy grandfather has a box ________ with old letters and photos. (fill)',
      'type','short_answer',
      'answer',E'filled',
      'acceptedAnswers',jsonb_build_array('filled'),
      'explanation',E'상자가 채워진 상태(수동/완료) → 과거분사 filled'),
    jsonb_build_object('number',10,
      'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nLook at the leaves ________ slowly from the trees in the autumn wind. (fall)',
      'type','short_answer',
      'answer',E'falling',
      'acceptedAnswers',jsonb_build_array('falling'),
      'explanation',E'나뭇잎이 떨어지고 있는 중(능동/진행) → 현재분사 falling'),

    -- ═══════════════════════════════════════════
    -- Part 2: 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오 (Q11-Q22)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe man drove his truck is my neighbor.',
      'type','short_answer',
      'answer',E'drove → driving',
      'acceptedAnswers',jsonb_build_array('drove → driving','drove->driving','driving'),
      'explanation',E'남자가 트럭을 운전하고 있는 중(능동/진행) → 현재분사 driving. drove는 과거시제 동사로 분사가 아님'),
    jsonb_build_object('number',12,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nI read a book writing by O. Henry last night.',
      'type','short_answer',
      'answer',E'writing → written',
      'acceptedAnswers',jsonb_build_array('writing → written','writing->written','written'),
      'explanation',E'책이 쓰여진 것(수동/완료) → 과거분사 written. writing은 능동 의미로 어색함'),
    jsonb_build_object('number',13,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nLook at the girl danced on the stage. She''s amazing!',
      'type','short_answer',
      'answer',E'danced → dancing',
      'acceptedAnswers',jsonb_build_array('danced → dancing','danced->dancing','dancing'),
      'explanation',E'소녀가 춤을 추고 있는 중(능동/진행) → 현재분사 dancing. danced는 과거시제/과거분사로 수동 의미가 되어 어색함'),
    jsonb_build_object('number',14,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe people inviting to the party are all close friends of mine.',
      'type','short_answer',
      'answer',E'inviting → invited',
      'acceptedAnswers',jsonb_build_array('inviting → invited','inviting->invited','invited'),
      'explanation',E'사람들이 초대받은 것(수동/완료) → 과거분사 invited. inviting은 능동 의미로 어색함'),
    jsonb_build_object('number',15,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nCan you fix this breaking bicycle for me?',
      'type','short_answer',
      'answer',E'breaking → broken',
      'acceptedAnswers',jsonb_build_array('breaking → broken','breaking->broken','broken'),
      'explanation',E'자전거가 고장난 상태(수동/완료) → 과거분사 broken. breaking은 능동 의미(부수는 중)로 어색함'),
    jsonb_build_object('number',16,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nShe is the writer loving by all Koreans.',
      'type','short_answer',
      'answer',E'loving → loved',
      'acceptedAnswers',jsonb_build_array('loving → loved','loving->loved','loved'),
      'explanation',E'작가가 사랑받는 것(수동/완료) → 과거분사 loved. loving은 능동 의미로 어색함'),
    jsonb_build_object('number',17,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe language speaking in Brazil is Portuguese.',
      'type','short_answer',
      'answer',E'speaking → spoken',
      'acceptedAnswers',jsonb_build_array('speaking → spoken','speaking->spoken','spoken'),
      'explanation',E'언어가 말해지는 것(수동/완료) → 과거분사 spoken. speaking은 능동 의미로 어색함'),
    jsonb_build_object('number',18,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nI saw a box leaving at the front door this morning.',
      'type','short_answer',
      'answer',E'leaving → left',
      'acceptedAnswers',jsonb_build_array('leaving → left','leaving->left','left'),
      'explanation',E'상자가 놓여진 것(수동/완료) → 과거분사 left. leaving은 능동 의미(떠나는 중)로 어색함'),
    jsonb_build_object('number',19,
      'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe girl is calling my name over there is my best friend.',
      'type','short_answer',
      'answer',E'is calling → calling',
      'acceptedAnswers',jsonb_build_array('is calling → calling','is calling->calling','calling'),
      'explanation',E'소녀가 이름을 부르고 있는 중(능동/진행) → 현재분사 calling. is calling은 진행형 동사구로 분사 수식이 아님'),
    jsonb_build_object('number',20,
      'question',E'다음 글에서 어법상 어색한 두 군데를 찾아 바르게 고쳐 쓰시오.\n\nThe woman sit on the mat is my homeroom teacher, Ms. Kim. I saw her at the park yesterday. She was with her family. The boy drink juice is her son, and the man holding a cup is her husband. They all looked happy.',
      'type','short_answer',
      'answer',E'sit → sitting, drink → drinking',
      'acceptedAnswers',jsonb_build_array('sit → sitting, drink → drinking','sitting, drinking','sit→sitting, drink→drinking'),
      'explanation',E'(1) sit → sitting: 여자가 앉아 있는 중(능동) → 현재분사 / (2) drink → drinking: 소년이 마시고 있는 중(능동) → 현재분사'),
    jsonb_build_object('number',21,
      'question',E'다음 글에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThis is the hospital in my neighborhood. Dr. Chang is taking a crying girl to the X-ray room. Dr. Smith is taking care of a boy hit by a bicycle. Dr. Kim is checking a man biting by a snake. They are all very busy today.',
      'type','short_answer',
      'answer',E'biting → bitten',
      'acceptedAnswers',jsonb_build_array('biting → bitten','bitten','biting->bitten'),
      'explanation',E'남자가 뱀에 물린 것(수동/완료) → 과거분사 bitten. biting은 능동 의미(무는 중)로 어색함'),
    jsonb_build_object('number',22,
      'question',E'다음 글에서 어법상 어색한 두 군데를 찾아 바르게 고쳐 쓰시오.\n\nLast weekend I went to a bookstore near my house. It was crowded with people buy books. I was looking for a book written by Leo Tolstoy. At the corner, a soccer player was signing autographs. Lots of people were waiting in line. A pretty girl wore a pink shirt helped this event.',
      'type','short_answer',
      'answer',E'buy → buying, wore → wearing',
      'acceptedAnswers',jsonb_build_array('buy → buying, wore → wearing','buying, wearing','buy→buying, wore→wearing'),
      'explanation',E'(1) buy → buying: 사람들이 책을 사고 있는 중(능동) → 현재분사 / (2) wore → wearing: 소녀가 셔츠를 입고 있는 중(능동) → 현재분사. wore는 과거시제 동사로 분사가 아님')
);

-- ── q2: Part 3-4 (Q23–Q42) ──
q2 := jsonb_build_array(
-- Partial file: jsonb_build_object lines only (Q23-Q42)

    jsonb_build_object('number',23,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The girl is my classmate.\n• She is singing on the stage.',
      'type','short_answer',
      'answer',E'The girl singing on the stage is my classmate.',
      'acceptedAnswers',jsonb_build_array('The girl singing on the stage is my classmate.','The girl singing on the stage is my classmate'),
      'explanation',E'She is singing → singing(현재분사)으로 줄여서 girl 뒤에 배치'),
    jsonb_build_object('number',24,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• I know the man.\n• He is wearing a black hat.',
      'type','short_answer',
      'answer',E'I know the man wearing a black hat.',
      'acceptedAnswers',jsonb_build_array('I know the man wearing a black hat.','I know the man wearing a black hat'),
      'explanation',E'He is wearing → wearing(현재분사)으로 줄여서 man 뒤에 배치'),
    jsonb_build_object('number',25,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The building was built in 1980.\n• It is still being used today.',
      'type','short_answer',
      'answer',E'The building built in 1980 is still being used today.',
      'acceptedAnswers',jsonb_build_array('The building built in 1980 is still being used today.','The building built in 1980 is still being used today'),
      'explanation',E'was built → built(과거분사)으로 줄여서 building 뒤에 배치'),
    jsonb_build_object('number',26,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• I spoke to the woman.\n• She was sitting next to me on the plane.',
      'type','short_answer',
      'answer',E'I spoke to the woman sitting next to me on the plane.',
      'acceptedAnswers',jsonb_build_array('I spoke to the woman sitting next to me on the plane.','I spoke to the woman sitting next to me on the plane'),
      'explanation',E'She was sitting → sitting(현재분사)으로 줄여서 woman 뒤에 배치'),
    jsonb_build_object('number',27,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• They found a wallet.\n• It was left on the bench in the park.',
      'type','short_answer',
      'answer',E'They found a wallet left on the bench in the park.',
      'acceptedAnswers',jsonb_build_array('They found a wallet left on the bench in the park.','They found a wallet left on the bench in the park'),
      'explanation',E'It was left → left(과거분사)으로 줄여서 wallet 뒤에 배치'),
    jsonb_build_object('number',28,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• She always reads articles.\n• They are published in science magazines.',
      'type','short_answer',
      'answer',E'She always reads articles published in science magazines.',
      'acceptedAnswers',jsonb_build_array('She always reads articles published in science magazines.','She always reads articles published in science magazines'),
      'explanation',E'They are published → published(과거분사)으로 줄여서 articles 뒤에 배치'),
    jsonb_build_object('number',29,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The soldier was taken to the hospital.\n• He was injured in the battle.',
      'type','short_answer',
      'answer',E'The soldier injured in the battle was taken to the hospital.',
      'acceptedAnswers',jsonb_build_array('The soldier injured in the battle was taken to the hospital.','The soldier injured in the battle was taken to the hospital'),
      'explanation',E'He was injured → injured(과거분사)으로 줄여서 soldier 뒤에 배치'),
    jsonb_build_object('number',30,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The novel became a bestseller.\n• It was translated into 30 languages.',
      'type','short_answer',
      'answer',E'The novel translated into 30 languages became a bestseller.',
      'acceptedAnswers',jsonb_build_array('The novel translated into 30 languages became a bestseller.','The novel translated into 30 languages became a bestseller'),
      'explanation',E'It was translated → translated(과거분사)으로 줄여서 novel 뒤에 배치'),
    jsonb_build_object('number',31,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• Do you know the woman?\n• She is standing next to Thomas.',
      'type','short_answer',
      'answer',E'Do you know the woman standing next to Thomas?',
      'acceptedAnswers',jsonb_build_array('Do you know the woman standing next to Thomas?','Do you know the woman standing next to Thomas'),
      'explanation',E'She is standing → standing(현재분사)으로 줄여서 woman 뒤에 배치'),
    jsonb_build_object('number',32,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• There was a coat.\n• It was hanging on the wall.',
      'type','short_answer',
      'answer',E'There was a coat hanging on the wall.',
      'acceptedAnswers',jsonb_build_array('There was a coat hanging on the wall.','There was a coat hanging on the wall'),
      'explanation',E'It was hanging → hanging(현재분사)으로 줄여서 coat 뒤에 배치'),
    jsonb_build_object('number',33,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• She is one of the scientists.\n• They are working on a climate change project.',
      'type','short_answer',
      'answer',E'She is one of the scientists working on a climate change project.',
      'acceptedAnswers',jsonb_build_array('She is one of the scientists working on a climate change project.','She is one of the scientists working on a climate change project'),
      'explanation',E'They are working → working(현재분사)으로 줄여서 scientists 뒤에 배치'),
    jsonb_build_object('number',34,
      'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The man is my Japanese teacher.\n• He is standing in front of the gate.',
      'type','short_answer',
      'answer',E'The man standing in front of the gate is my Japanese teacher.',
      'acceptedAnswers',jsonb_build_array('The man standing in front of the gate is my Japanese teacher.','The man standing in front of the gate is my Japanese teacher'),
      'explanation',E'He is standing → standing(현재분사)으로 줄여서 man 뒤에 배치'),

    -- Part 4: 다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오. (Q35-42)

    jsonb_build_object('number',35,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nThe boy who is standing next to the door is my cousin.',
      'type','short_answer',
      'answer',E'who is / The boy standing next to the door is my cousin.',
      'acceptedAnswers',jsonb_build_array('who is / The boy standing next to the door is my cousin.','who is / The boy standing next to the door is my cousin','The boy standing next to the door is my cousin.','The boy standing next to the door is my cousin'),
      'explanation',E'관계대명사+be동사(who is) 생략 → 현재분사 standing만 남음'),
    jsonb_build_object('number',36,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nI received a letter which was written in English.',
      'type','short_answer',
      'answer',E'which was / I received a letter written in English.',
      'acceptedAnswers',jsonb_build_array('which was / I received a letter written in English.','which was / I received a letter written in English','I received a letter written in English.','I received a letter written in English'),
      'explanation',E'관계대명사+be동사(which was) 생략 → 과거분사 written만 남음'),
    jsonb_build_object('number',37,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nThe woman who is walking her dog talked to the old man.',
      'type','short_answer',
      'answer',E'who is / The woman walking her dog talked to the old man.',
      'acceptedAnswers',jsonb_build_array('who is / The woman walking her dog talked to the old man.','who is / The woman walking her dog talked to the old man','The woman walking her dog talked to the old man.','The woman walking her dog talked to the old man'),
      'explanation',E'관계대명사+be동사(who is) 생략 → 현재분사 walking만 남음'),
    jsonb_build_object('number',38,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nLook at those lions which are sleeping under the tree.',
      'type','short_answer',
      'answer',E'which are / Look at those lions sleeping under the tree.',
      'acceptedAnswers',jsonb_build_array('which are / Look at those lions sleeping under the tree.','which are / Look at those lions sleeping under the tree','Look at those lions sleeping under the tree.','Look at those lions sleeping under the tree'),
      'explanation',E'관계대명사+be동사(which are) 생략 → 현재분사 sleeping만 남음'),
    jsonb_build_object('number',39,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nThe car that was damaged in the accident was mine.',
      'type','short_answer',
      'answer',E'that was / The car damaged in the accident was mine.',
      'acceptedAnswers',jsonb_build_array('that was / The car damaged in the accident was mine.','that was / The car damaged in the accident was mine','The car damaged in the accident was mine.','The car damaged in the accident was mine'),
      'explanation',E'관계대명사+be동사(that was) 생략 → 과거분사 damaged만 남음'),
    jsonb_build_object('number',40,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nTeachers often have nicknames which are known only by their students.',
      'type','short_answer',
      'answer',E'which are / Teachers often have nicknames known only by their students.',
      'acceptedAnswers',jsonb_build_array('which are / Teachers often have nicknames known only by their students.','which are / Teachers often have nicknames known only by their students','Teachers often have nicknames known only by their students.','Teachers often have nicknames known only by their students'),
      'explanation',E'관계대명사+be동사(which are) 생략 → 과거분사 known만 남음'),
    jsonb_build_object('number',41,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nThe girl who is playing the piano over there is my little sister.',
      'type','short_answer',
      'answer',E'who is / The girl playing the piano over there is my little sister.',
      'acceptedAnswers',jsonb_build_array('who is / The girl playing the piano over there is my little sister.','who is / The girl playing the piano over there is my little sister','The girl playing the piano over there is my little sister.','The girl playing the piano over there is my little sister'),
      'explanation',E'관계대명사+be동사(who is) 생략 → 현재분사 playing만 남음'),
    jsonb_build_object('number',42,
      'question',E'다음 문장에서 생략할 수 있는 부분을 쓰고, 줄인 문장으로 다시 쓰시오.\n\nThere is a galaxy which is called the Milky Way.',
      'type','short_answer',
      'answer',E'which is / There is a galaxy called the Milky Way.',
      'acceptedAnswers',jsonb_build_array('which is / There is a galaxy called the Milky Way.','which is / There is a galaxy called the Milky Way','There is a galaxy called the Milky Way.','There is a galaxy called the Milky Way'),
      'explanation',E'관계대명사+be동사(which is) 생략 → 과거분사 called만 남음')
);

-- ── q3: Part 5-6 (Q43–Q60) ──
q3 := jsonb_build_array(
-- Partial file: jsonb_build_object lines only (Q43-Q60)

    -- Part 5: 빈칸에 알맞은 감정분사(-ing 또는 -ed)를 쓰시오. (Q43-50)

    jsonb_build_object('number',43,
      'question',E'빈칸에 알맞은 감정분사(-ing 또는 -ed)를 쓰시오.\n\nThe movie was so ________ that I cried three times. (touch)',
      'type','short_answer',
      'answer',E'touching',
      'acceptedAnswers',jsonb_build_array('touching'),
      'explanation',E'영화가 감동을 유발(사물) → 현재분사 touching'),
    jsonb_build_object('number',44,
      'question',E'빈칸에 알맞은 감정분사(-ing 또는 -ed)를 쓰시오.\n\nShe looked ________ when she heard the bad news. (disappoint)',
      'type','short_answer',
      'answer',E'disappointed',
      'acceptedAnswers',jsonb_build_array('disappointed'),
      'explanation',E'그녀가 실망을 느낌(사람) → 과거분사 disappointed'),
    jsonb_build_object('number',45,
      'question',E'빈칸에 알맞은 감정분사(-ing 또는 -ed)를 쓰시오.\n\nMost children find horror movies ________. (frighten)',
      'type','short_answer',
      'answer',E'frightening',
      'acceptedAnswers',jsonb_build_array('frightening'),
      'explanation',E'공포 영화가 두려움을 유발(사물) → 현재분사 frightening'),
    jsonb_build_object('number',46,
      'question',E'빈칸에 알맞은 감정분사(-ing 또는 -ed)를 쓰시오.\n\nI was completely ________ by the magician''s performance. (amaze)',
      'type','short_answer',
      'answer',E'amazed',
      'acceptedAnswers',jsonb_build_array('amazed'),
      'explanation',E'내가 놀라움을 느낌(사람) → 과거분사 amazed'),
    jsonb_build_object('number',47,
      'question',E'다음 괄호 안의 단어를 알맞은 형태로 바꾸어 빈칸을 완성하시오.\n\n(1) Justin was ________ to hear about the accident. (surprise)\n(2) This book has many ________ stories. (touch)\n(3) I bought a ________ car because I didn''t have much money. (use)',
      'type','short_answer',
      'answer',E'surprised, touching, used',
      'acceptedAnswers',jsonb_build_array('surprised, touching, used','surprised / touching / used','surprised,touching,used'),
      'explanation',E'(1) Justin이 놀람을 느낌(사람) → surprised / (2) 이야기가 감동 유발 → touching / (3) 사용된 차(수동) → used'),
    jsonb_build_object('number',48,
      'question',E'다음 괄호 안의 단어를 알맞은 형태로 바꾸어 빈칸을 완성하시오.\n\n(1) She always talks about the same things. She never says anything ________. She''s really ________. (interest / bore)\n(2) My father works very hard. It''s not ________ that he''s always ________. (surprise / tire)',
      'type','short_answer',
      'answer',E'interesting, boring, surprising, tired',
      'acceptedAnswers',jsonb_build_array('interesting, boring, surprising, tired','interesting / boring / surprising / tired','interesting,boring,surprising,tired'),
      'explanation',E'(1) 말이 흥미를 유발 → interesting, 그녀가 지루함을 유발 → boring / (2) 놀라움을 유발하는 일 → surprising, 아버지가 피곤함을 느낌 → tired'),
    jsonb_build_object('number',49,
      'question',E'다음 대화의 괄호 안의 단어를 알맞은 형태로 바꾸어 쓰시오.\n\nA: What are you reading?\nB: This is a book (A)(write) by a famous Korean artist.\nA: Who is that in the middle of the page?\nB: This is a traditional Korean artist (B)(know) to everyone in Korea.\nA: Hey, look at the dog (C)(run) after the cat. Are they fighting?\nB: Nope! They are good friends.\n\n(A) ________ (B) ________ (C) ________',
      'type','short_answer',
      'answer',E'written, known, running',
      'acceptedAnswers',jsonb_build_array('written, known, running','written / known / running','written,known,running'),
      'explanation',E'(A) 책이 쓰여진(수동) → written / (B) 예술가가 알려진(수동) → known / (C) 개가 쫓고 있는(능동) → running'),
    jsonb_build_object('number',50,
      'question',E'다음 글의 괄호 안의 단어를 알맞은 형태로 바꾸어 쓰시오.\n\nLook at this picture of a man (A)(play) soccer. He''s a famous soccer player (B)(name) David Park. There''s even a movie (C)(make) about him. Hello Paris is a travel book (D)(write) by Bill Jones. He is a young writer (E)(know) for his unique style.\n\n(A) ________ (B) ________ (C) ________ (D) ________ (E) ________',
      'type','short_answer',
      'answer',E'playing, named, made, written, known',
      'acceptedAnswers',jsonb_build_array('playing, named, made, written, known','playing / named / made / written / known','playing,named,made,written,known'),
      'explanation',E'(A) 축구하는 중(능동) → playing / (B) 이름 불리는(수동) → named / (C) 만들어진(수동) → made / (D) 쓰여진(수동) → written / (E) 알려진(수동) → known'),

    -- Part 6: 주어진 조건에 맞게 영작하시오. (Q51-60)

    jsonb_build_object('number',51,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n공원에서 조깅하고 있는 저 남자는 우리 아버지이다.\n\n【조건】 jog, the man 사용 / 8단어',
      'type','short_answer',
      'answer',E'The man jogging in the park is my father.',
      'acceptedAnswers',jsonb_build_array('The man jogging in the park is my father.','The man jogging in the park is my father'),
      'explanation',E'현재분사 jogging이 the man을 후치 수식. 8단어'),
    jsonb_build_object('number',52,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n나는 한국에서 만들어진 자동차를 사고 싶다.\n\n【조건】 make, in Korea 사용 / 9단어',
      'type','short_answer',
      'answer',E'I want to buy a car made in Korea.',
      'acceptedAnswers',jsonb_build_array('I want to buy a car made in Korea.','I want to buy a car made in Korea'),
      'explanation',E'과거분사 made가 a car를 후치 수식. 9단어'),
    jsonb_build_object('number',53,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n그 도서관에서 공부하고 있는 학생들은 다음 주에 시험이 있다.\n\n【조건】 study, have an exam 사용 / 12단어',
      'type','short_answer',
      'answer',E'The students studying in the library have an exam next week.',
      'acceptedAnswers',jsonb_build_array('The students studying in the library have an exam next week.','The students studying in the library have an exam next week'),
      'explanation',E'현재분사 studying이 the students를 후치 수식. 12단어'),
    jsonb_build_object('number',54,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n그 회의에 초대된 사람들은 모두 제시간에 도착했다.\n\n【조건】 invite, the people 사용 / 10단어',
      'type','short_answer',
      'answer',E'The people invited to the meeting all arrived on time.',
      'acceptedAnswers',jsonb_build_array('The people invited to the meeting all arrived on time.','The people invited to the meeting all arrived on time'),
      'explanation',E'과거분사 invited가 the people을 후치 수식. 10단어'),
    jsonb_build_object('number',55,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n바다에서 수영하고 있는 저 여자는 금메달을 땄다.\n\n【조건】 swim, 두 문장을 분사를 이용하여 한 문장으로 / 10단어',
      'type','short_answer',
      'answer',E'That woman swimming in the sea won a gold medal.',
      'acceptedAnswers',jsonb_build_array('That woman swimming in the sea won a gold medal.','That woman swimming in the sea won a gold medal'),
      'explanation',E'현재분사 swimming이 that woman을 후치 수식. 10단어'),
    jsonb_build_object('number',56,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n야구공으로 인해 깨진 창문을 보아라.\n\n【조건】 look, break, by 사용 / 8단어',
      'type','short_answer',
      'answer',E'Look at the window broken by a baseball.',
      'acceptedAnswers',jsonb_build_array('Look at the window broken by a baseball.','Look at the window broken by a baseball'),
      'explanation',E'과거분사 broken이 the window를 후치 수식. 8단어'),
    jsonb_build_object('number',57,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n우리 할머니는 지역 예술가가 만든 목걸이를 항상 하신다.\n\n【조건】 make, a local artist 사용 / 11단어',
      'type','short_answer',
      'answer',E'My grandmother always wears a necklace made by a local artist.',
      'acceptedAnswers',jsonb_build_array('My grandmother always wears a necklace made by a local artist.','My grandmother always wears a necklace made by a local artist'),
      'explanation',E'과거분사 made가 a necklace를 후치 수식. 11단어'),
    jsonb_build_object('number',58,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n기차를 기다리고 있는 2명의 사람들이 있다.\n\n【조건】 people, train, wait 사용 / 8단어',
      'type','short_answer',
      'answer',E'There are two people waiting for a train.',
      'acceptedAnswers',jsonb_build_array('There are two people waiting for a train.','There are two people waiting for a train','There are two people waiting for the train.','There are two people waiting for the train'),
      'explanation',E'현재분사 waiting이 two people을 후치 수식. 8단어'),
    jsonb_build_object('number',59,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n그 화재로 소실된 그림들의 가치는 수십억 원에 달했다.\n\n【조건】 destroy, the paintings 사용 / 11단어',
      'type','short_answer',
      'answer',E'The paintings destroyed in the fire were worth billions of won.',
      'acceptedAnswers',jsonb_build_array('The paintings destroyed in the fire were worth billions of won.','The paintings destroyed in the fire were worth billions of won'),
      'explanation',E'과거분사 destroyed가 the paintings를 후치 수식. 11단어'),
    jsonb_build_object('number',60,
      'question',E'주어진 조건에 맞게 영작하시오.\n\n무대 위에서 바이올린을 연주하고 있는 소녀가 내 여동생이다. (그녀는 올해 겨우 11살이다.)\n\n【조건】 play, the violin, on stage 사용 / 첫 번째 문장만 12단어로 쓸 것',
      'type','short_answer',
      'answer',E'The girl playing the violin on stage is my younger sister.',
      'acceptedAnswers',jsonb_build_array('The girl playing the violin on stage is my younger sister.','The girl playing the violin on stage is my younger sister','The girl playing the violin on the stage is my younger sister.','The girl playing the violin on the stage is my younger sister'),
      'explanation',E'현재분사 playing이 the girl을 후치 수식. 12단어')
);

a := jsonb_build_array();

INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
VALUES (
  E'명사를 꾸며주는 분사 Step 3',
  E'명사를 꾸며주는 분사',
  q1 || q2 || q3,
  a,
  'problem',
  'interactive'
);

END $$;
