DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '사역동사 Step 3';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1: [상황 추론] 상황 묘사와 데이터를 활용한 문장 생성 (Q1~Q10)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 아빠가 고장 난 컴퓨터를 만졌고, 이제 컴퓨터가 정상 작동한다.',
      'answer',E'Dad made the computer work.',
      'acceptedAnswers',jsonb_build_array(E'Dad made the computer work.', E'Dad made the computer work'),
      'explanation',E'make + 목적어 + 동사원형: "작동하게 만들다"'),

    jsonb_build_object('number',2,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 준수가 주디의 노트북을 쓰고 싶어 하지만 주디는 단호하게 거절한다.',
      'answer',E'Judy wouldn''t let Junsu use her laptop.',
      'acceptedAnswers',jsonb_build_array(
        E'Judy wouldn''t let Junsu use her laptop.',
        E'Judy wouldn''t let Junsu use her laptop',
        E'Judy wouldn''t let him use her laptop.',
        E'Judy wouldn''t let him use her laptop',
        E'Judy would not let Junsu use her laptop.',
        E'Judy would not let Junsu use her laptop',
        E'Judy would not let him use her laptop.',
        E'Judy would not let him use her laptop',
        E'Judy won''t let Junsu use her laptop.',
        E'Judy won''t let Junsu use her laptop',
        E'Judy won''t let him use her laptop.',
        E'Judy won''t let him use her laptop',
        E'Judy doesn''t let Junsu use her laptop.',
        E'Judy doesn''t let Junsu use her laptop',
        E'Judy does not let Junsu use her laptop.',
        E'Judy does not let Junsu use her laptop'),
      'explanation',E'let + 목적어 + 동사원형: "~하게 허락하다"의 부정형'),

    jsonb_build_object('number',3,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오. (make 활용)\n\n상황: [스케줄표] 주디는 월요일에 여동생을 돌보기로 되어 있다.',
      'answer',E'Judy''s mom made her take care of her sister on Monday.',
      'acceptedAnswers',jsonb_build_array(
        E'Judy''s mom made her take care of her sister on Monday.',
        E'Judy''s mom made her take care of her sister on Monday',
        E'Judy''s mom made her take care of her sister.',
        E'Judy''s mom made her take care of her sister',
        E'Judy''s mother made her take care of her sister on Monday.',
        E'Judy''s mother made her take care of her sister on Monday',
        E'Judy''s mother made her take care of her sister.',
        E'Judy''s mother made her take care of her sister',
        E'Her mom made her take care of her sister on Monday.',
        E'Her mom made her take care of her sister on Monday',
        E'Her mom made her take care of her sister.',
        E'Her mom made her take care of her sister'),
      'explanation',E'make + 목적어 + 동사원형: 엄마가 시켜서 돌봄'),

    jsonb_build_object('number',4,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 미나가 태수에게 거실이 더럽다고 말하자 태수가 청소기를 돌린다.',
      'answer',E'Mina made Taesu clean the living room.',
      'acceptedAnswers',jsonb_build_array(
        E'Mina made Taesu clean the living room.',
        E'Mina made Taesu clean the living room',
        E'Mina made Taesu vacuum the living room.',
        E'Mina made Taesu vacuum the living room'),
      'explanation',E'make + 목적어 + 동사원형: "청소하게 시키다" (clean/vacuum 모두 허용)'),

    jsonb_build_object('number',5,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 진수가 큰 화분을 옮기려 하자 미나가 옆에서 함께 들어준다.',
      'answer',E'Mina helped Jinsu move the plant.',
      'acceptedAnswers',jsonb_build_array(
        E'Mina helped Jinsu move the plant.',
        E'Mina helped Jinsu move the plant',
        E'Mina helped Jinsu to move the plant.',
        E'Mina helped Jinsu to move the plant',
        E'Mina helped Jinsu move the big plant.',
        E'Mina helped Jinsu move the big plant',
        E'Mina helped Jinsu to move the big plant.',
        E'Mina helped Jinsu to move the big plant',
        E'Mina helped him move the plant.',
        E'Mina helped him move the plant',
        E'Mina helped him to move the plant.',
        E'Mina helped him to move the plant'),
      'explanation',E'help + 목적어 + 동사원형/to부정사: 둘 다 가능'),

    jsonb_build_object('number',6,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 아빠가 팀에게 거실 바닥에 걸레질을 하라고 시켰다.',
      'answer',E'Tim''s dad made him clean the floor.',
      'acceptedAnswers',jsonb_build_array(
        E'Tim''s dad made him clean the floor.',
        E'Tim''s dad made him clean the floor',
        E'Tim''s father made him clean the floor.',
        E'Tim''s father made him clean the floor',
        E'Tim''s dad made him mop the floor.',
        E'Tim''s dad made him mop the floor',
        E'Tim''s father made him mop the floor.',
        E'Tim''s father made him mop the floor',
        E'Tim''s dad made Tim clean the floor.',
        E'Tim''s dad made Tim clean the floor'),
      'explanation',E'make + 목적어 + 동사원형: "걸레질하게 시키다"'),

    jsonb_build_object('number',7,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 엄마가 나가기 전에 반드시 숙제를 끝내라고 말했고, 딸은 알겠다고 답한다.',
      'answer',E'My mom makes me do my homework before I go out.',
      'acceptedAnswers',jsonb_build_array(
        E'My mom makes me do my homework before I go out.',
        E'My mom makes me do my homework before I go out',
        E'My mother makes me do my homework before I go out.',
        E'My mother makes me do my homework before I go out',
        E'Mom makes me do my homework before I go out.',
        E'Mom makes me do my homework before I go out'),
      'explanation',E'make + 목적어 + 동사원형: 현재 습관적 지시'),

    jsonb_build_object('number',8,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: 여자가 소년에게 일찍 잠자리에 들라고 강조한다.',
      'answer',E'The woman made the boy go to bed early.',
      'acceptedAnswers',jsonb_build_array(
        E'The woman made the boy go to bed early.',
        E'The woman made the boy go to bed early',
        E'The woman made him go to bed early.',
        E'The woman made him go to bed early'),
      'explanation',E'make + 목적어 + 동사원형: "일찍 자게 시키다"'),

    jsonb_build_object('number',9,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: [스케줄표] 주디는 화요일 정원에 물을 주는 것이 허락되었다.',
      'answer',E'Judy''s mom let her water flowers in the garden on Tuesday.',
      'acceptedAnswers',jsonb_build_array(
        E'Judy''s mom let her water flowers in the garden on Tuesday.',
        E'Judy''s mom let her water flowers in the garden on Tuesday',
        E'Judy''s mom let her water flowers in the garden.',
        E'Judy''s mom let her water flowers in the garden',
        E'Judy''s mom let her water the flowers in the garden on Tuesday.',
        E'Judy''s mom let her water the flowers in the garden on Tuesday',
        E'Judy''s mom let her water the flowers in the garden.',
        E'Judy''s mom let her water the flowers in the garden',
        E'Judy''s mother let her water flowers in the garden on Tuesday.',
        E'Judy''s mother let her water flowers in the garden on Tuesday',
        E'Judy''s mother let her water flowers in the garden.',
        E'Judy''s mother let her water flowers in the garden',
        E'Judy''s mother let her water the flowers in the garden on Tuesday.',
        E'Judy''s mother let her water the flowers in the garden on Tuesday',
        E'Judy''s mother let her water the flowers in the garden.',
        E'Judy''s mother let her water the flowers in the garden'),
      'explanation',E'let + 목적어 + 동사원형: "허락하다"'),

    jsonb_build_object('number',10,
      'question',E'[Part 1]\n제시된 상황 설명을 읽고 사역동사 구문을 활용하여 영어 문장을 완성하시오.\n\n상황: [스케줄표] 주디는 일요일에 강아지 산책을 설득 끝에 하게 되었다.',
      'answer',E'Judy''s mom got her to walk her pet dog on Sunday.',
      'acceptedAnswers',jsonb_build_array(
        E'Judy''s mom got her to walk her pet dog on Sunday.',
        E'Judy''s mom got her to walk her pet dog on Sunday',
        E'Judy''s mom got her to walk her pet dog.',
        E'Judy''s mom got her to walk her pet dog',
        E'Judy''s mother got her to walk her pet dog on Sunday.',
        E'Judy''s mother got her to walk her pet dog on Sunday',
        E'Judy''s mother got her to walk her pet dog.',
        E'Judy''s mother got her to walk her pet dog',
        E'Judy''s mom got her to walk the dog on Sunday.',
        E'Judy''s mom got her to walk the dog on Sunday',
        E'Judy''s mom got her to walk the dog.',
        E'Judy''s mom got her to walk the dog',
        E'Judy''s mother got her to walk the dog on Sunday.',
        E'Judy''s mother got her to walk the dog on Sunday',
        E'Judy''s mother got her to walk the dog.',
        E'Judy''s mother got her to walk the dog'),
      'explanation',E'get + 목적어 + to부정사: "설득해서 ~하게 하다"'),

    -- ═══════════════════════════════════════════
    -- Part 2: [논리 패러프레이징] 문장 전환 및 고쳐 쓰기 (Q11~Q20)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 주어진 조건에 맞게 영작하시오. (let 활용)\n\nDon''t stop him from doing what he wants.',
      'answer',E'Let him do what he wants.',
      'acceptedAnswers',jsonb_build_array(
        E'Let him do what he wants.',
        E'Let him do what he wants'),
      'explanation',E'"막지 마" → "하게 해 줘" (let + 목적어 + 동사원형)'),

    jsonb_build_object('number',12,
      'question',E'[Part 2]\n다음 빈칸에 알맞은 영어를 쓰시오.\n\nHe looks older when he wears the hat.\n→ The hat _______ him _______ older.',
      'answer',E'makes, look',
      'acceptedAnswers',jsonb_build_array(
        E'makes, look',
        E'makes / look',
        E'makes look',
        E'makes him look older'),
      'explanation',E'make + 목적어 + 동사원형: "~하게 보이게 만들다"'),

    jsonb_build_object('number',13,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 주어진 조건에 맞게 영작하시오. (have 활용)\n\nMom told me to look for her cellphone.',
      'answer',E'Mom had me look for her cellphone.',
      'acceptedAnswers',jsonb_build_array(
        E'Mom had me look for her cellphone.',
        E'Mom had me look for her cellphone',
        E'Mom had me look for her cell phone.',
        E'Mom had me look for her cell phone',
        E'Mom had me look for her phone.',
        E'Mom had me look for her phone',
        E'My mom had me look for her cellphone.',
        E'My mom had me look for her cellphone',
        E'My mom had me look for her cell phone.',
        E'My mom had me look for her cell phone',
        E'My mom had me look for her phone.',
        E'My mom had me look for her phone'),
      'explanation',E'have + 목적어 + 동사원형: "~하게 시키다" (told ≈ had)'),

    jsonb_build_object('number',14,
      'question',E'[Part 2]\n다음 빈칸에 알맞은 영어를 쓰시오.\n\nI am excited because of the World Cup.\n→ The World Cup _______ me _______.',
      'answer',E'makes, excited',
      'acceptedAnswers',jsonb_build_array(
        E'makes, excited',
        E'makes / excited',
        E'makes excited',
        E'makes me excited'),
      'explanation',E'make + 목적어 + 형용사: "~한 기분이 들게 하다"'),

    jsonb_build_object('number',15,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 so that을 활용하여 영작하시오.\n\nI asked for his phone number because I wanted to call him.',
      'answer',E'I asked for his phone number so that I could call him.',
      'acceptedAnswers',jsonb_build_array(
        E'I asked for his phone number so that I could call him.',
        E'I asked for his phone number so that I could call him',
        E'I asked for his telephone number so that I could call him.',
        E'I asked for his telephone number so that I could call him'),
      'explanation',E'"전화하기 위해" → so that + 주어 + could (과거 시제)'),

    jsonb_build_object('number',16,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 so that을 활용하여 영작하시오.\n\nI am doing my homework to have fun this afternoon.',
      'answer',E'I am doing my homework so that I can have fun this afternoon.',
      'acceptedAnswers',jsonb_build_array(
        E'I am doing my homework so that I can have fun this afternoon.',
        E'I am doing my homework so that I can have fun this afternoon',
        E'I''m doing my homework so that I can have fun this afternoon.',
        E'I''m doing my homework so that I can have fun this afternoon'),
      'explanation',E'"놀기 위해" → so that + 주어 + can (현재 시제)'),

    jsonb_build_object('number',17,
      'question',E'[Part 2]\n다음 우리말을 주어진 조건에 맞게 영작하시오. (so that 활용)\n\n나는 영어 시험에 합격하기 위해 열심히 공부했다.',
      'answer',E'I studied hard so that I could pass the English exam.',
      'acceptedAnswers',jsonb_build_array(
        E'I studied hard so that I could pass the English exam.',
        E'I studied hard so that I could pass the English exam',
        E'I studied hard so that I could pass the English test.',
        E'I studied hard so that I could pass the English test',
        E'I studied hard so that I could pass my English exam.',
        E'I studied hard so that I could pass my English exam'),
      'explanation',E'주절이 과거(studied)이므로 so that + could'),

    jsonb_build_object('number',18,
      'question',E'[Part 2]\n다음 빈칸에 알맞은 영어를 쓰시오.\n\nWe study harder because of an exam.\n→ An exam _______ us _______ harder.',
      'answer',E'makes, study',
      'acceptedAnswers',jsonb_build_array(
        E'makes, study',
        E'makes / study',
        E'makes study',
        E'makes us study harder'),
      'explanation',E'make + 목적어 + 동사원형: "더 열심히 공부하게 만들다"'),

    jsonb_build_object('number',19,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 주어진 조건에 맞게 영작하시오. (make 활용)\n\nRed reminds me of the 2002 World Cup.',
      'answer',E'Red makes me think of the 2002 World Cup.',
      'acceptedAnswers',jsonb_build_array(
        E'Red makes me think of the 2002 World Cup.',
        E'Red makes me think of the 2002 World Cup'),
      'explanation',E'"떠올리게 한다" → make + 목적어 + think of'),

    jsonb_build_object('number',20,
      'question',E'[Part 2]\n다음 문장과 같은 뜻이 되도록 in order not to를 활용하여 영작하시오.\n\nI took my umbrella because I didn''t want to get wet.',
      'answer',E'I took my umbrella in order not to get wet.',
      'acceptedAnswers',jsonb_build_array(
        E'I took my umbrella in order not to get wet.',
        E'I took my umbrella in order not to get wet',
        E'I brought my umbrella in order not to get wet.',
        E'I brought my umbrella in order not to get wet'),
      'explanation',E'"젖지 않기 위해" → in order not to + 동사원형'),

    -- ═══════════════════════════════════════════
    -- Part 3: [디테일 교정] 어법 오류 및 어형 변화 (Q21~Q30)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',21,
      'question',E'[Part 3]\n다음 괄호 안의 단어를 어법에 맞게 고쳐 쓰시오.\n\nHis wife got him (quit) smoking.',
      'answer',E'to quit',
      'acceptedAnswers',jsonb_build_array(E'to quit', E'To quit'),
      'explanation',E'get + 목적어 + to부정사: got him to quit'),

    jsonb_build_object('number',22,
      'question',E'[Part 3]\n다음 괄호 안의 단어를 어법에 맞게 고쳐 쓰시오.\n\nI could never get him (admit) his faults.',
      'answer',E'to admit',
      'acceptedAnswers',jsonb_build_array(E'to admit', E'To admit'),
      'explanation',E'get + 목적어 + to부정사: get him to admit'),

    jsonb_build_object('number',23,
      'question',E'[Part 3]\n다음 문장에서 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nThe barking dog made the postman ran away.',
      'answer',E'The barking dog made the postman run away.',
      'acceptedAnswers',jsonb_build_array(E'The barking dog made the postman run away.', E'The barking dog made the postman run away'),
      'explanation',E'make + 목적어 + 동사원형: ran → run'),

    jsonb_build_object('number',24,
      'question',E'[Part 3]\n다음 문장의 의미에 맞게 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nYou should drive slowly so as to have an accident.',
      'answer',E'You should drive slowly so as not to have an accident.',
      'acceptedAnswers',jsonb_build_array(E'You should drive slowly so as not to have an accident.', E'You should drive slowly so as not to have an accident'),
      'explanation',E'"사고를 당하지 않기 위해" → so as not to (not 삽입)'),

    jsonb_build_object('number',25,
      'question',E'[Part 3]\n다음 괄호 안의 단어를 어법에 맞는 형태로 쓰시오.\n\nNancy will have her son (play) the piano.',
      'answer',E'play',
      'acceptedAnswers',jsonb_build_array(E'play', E'Play'),
      'explanation',E'have + 목적어 + 동사원형: have her son play'),

    jsonb_build_object('number',26,
      'question',E'[Part 3]\n다음 문장에서 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nMs. Yun let me to solving a math problem.',
      'answer',E'Ms. Yun let me solve a math problem.',
      'acceptedAnswers',jsonb_build_array(E'Ms. Yun let me solve a math problem.', E'Ms. Yun let me solve a math problem'),
      'explanation',E'let + 목적어 + 동사원형: to solving → solve'),

    jsonb_build_object('number',27,
      'question',E'[Part 3]\n다음 문장에서 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nI helped her choosing her dress.',
      'answer',E'I helped her choose her dress.',
      'acceptedAnswers',jsonb_build_array(E'I helped her choose her dress.', E'I helped her choose her dress', E'I helped her to choose her dress.', E'I helped her to choose her dress'),
      'explanation',E'help + 목적어 + 동사원형/to부정사: choosing → choose/to choose'),

    jsonb_build_object('number',28,
      'question',E'[Part 3]\n다음 문장에서 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nI made my sister cleaned her room.',
      'answer',E'I made my sister clean her room.',
      'acceptedAnswers',jsonb_build_array(E'I made my sister clean her room.', E'I made my sister clean her room'),
      'explanation',E'make + 목적어 + 동사원형: cleaned → clean'),

    jsonb_build_object('number',29,
      'question',E'[Part 3]\n다음 괄호 안의 단어를 어법에 맞는 형태로 쓰시오.\n\nI had my hair (cut) short for summer.',
      'answer',E'cut',
      'acceptedAnswers',jsonb_build_array(E'cut', E'Cut'),
      'explanation',E'have + 사물 목적어 + 과거분사: cut-cut-cut 불규칙 동사'),

    jsonb_build_object('number',30,
      'question',E'[Part 3]\n다음 문장에서 어법상 틀린 부분을 고쳐 완전한 문장으로 다시 쓰시오.\n\nI often stop working so that can take a rest.',
      'answer',E'I often stop working so that I can take a rest.',
      'acceptedAnswers',jsonb_build_array(E'I often stop working so that I can take a rest.', E'I often stop working so that I can take a rest'),
      'explanation',E'so that 뒤에 주어 필수: so that I can'),

    -- ═══════════════════════════════════════════
    -- Part 4: [맥락 완성] 대화와 지문 빈칸 채우기 (Q31~Q41)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',31,
      'question',E'[Part 4]\n다음 대화의 빈칸을 조건에 맞게 완성하시오. (let, go 활용)\n\nA: 오늘 뭐해?\nB: 엄마가 영화관에 ________.',
      'answer',E'won''t let me go',
      'acceptedAnswers',jsonb_build_array(E'won''t let me go', E'will not let me go', E'Won''t let me go', E'Will not let me go'),
      'explanation',E'let + 목적어 + 동사원형 부정: won''t let me go'),

    jsonb_build_object('number',32,
      'question',E'[Part 4]\n다음 대화의 빈칸을 조건에 맞게 완성하시오. (make, study 활용)\n\nA: 왜?\nB: 기말고사가 다가와서 하루 종일 ________.',
      'answer',E'will make me study',
      'acceptedAnswers',jsonb_build_array(E'will make me study', E'Will make me study', E'is going to make me study'),
      'explanation',E'make + 목적어 + 동사원형: will make me study'),

    jsonb_build_object('number',33,
      'question',E'[Part 4]\n다음 글의 빈칸 (1), (2)에 공통으로 들어갈 말을 쓰시오.\n\nSumin wants to talk to foreigners (1)________ she can improve her English. I need to study (2)________ I can speak to foreigners.',
      'answer',E'so that',
      'acceptedAnswers',jsonb_build_array(E'so that', E'So that', E'in order that', E'In order that'),
      'explanation',E'so that + 주어 + 조동사: 목적을 나타내는 접속사'),

    jsonb_build_object('number',34,
      'question',E'[Part 4]\n다음 조건에 맞게 영작하시오.\n사과와 과일의 효능을 설명하시오. [단어: fruits, make, you, healthy]',
      'answer',E'Fruits make you healthy.',
      'acceptedAnswers',jsonb_build_array(E'Fruits make you healthy.', E'Fruits make you healthy', E'Fruit makes you healthy.', E'Fruit makes you healthy'),
      'explanation',E'make + 목적어 + 형용사: "건강하게 만들다"'),

    jsonb_build_object('number',35,
      'question',E'[Part 4]\n다음 조건에 맞게 영작하시오.\n시험 기간의 심리 상태를 설명하시오. [단어: a test, makes, us, feel nervous]',
      'answer',E'A test makes us feel nervous.',
      'acceptedAnswers',jsonb_build_array(E'A test makes us feel nervous.', E'A test makes us feel nervous', E'A test makes us nervous.', E'A test makes us nervous', E'Tests make us feel nervous.', E'Tests make us feel nervous', E'An exam makes us feel nervous.', E'An exam makes us feel nervous'),
      'explanation',E'make + 목적어 + 동사원형(feel) + 형용사'),

    jsonb_build_object('number',36,
      'question',E'[Part 4]\n다음 우리말을 so as not to를 활용하여 영작하시오.\n다른 사람들을 불편하게 하지 않기 위해 앞좌석을 발로 차지 마세요.',
      'answer',E'You should not kick the seat in front of you so as not to make others feel uncomfortable.',
      'acceptedAnswers',jsonb_build_array(
        E'You should not kick the seat in front of you so as not to make others feel uncomfortable.',
        E'You should not kick the seat in front of you so as not to make others feel uncomfortable',
        E'Don''t kick the seat in front of you so as not to make others feel uncomfortable.',
        E'Don''t kick the seat in front of you so as not to make others feel uncomfortable',
        E'Do not kick the seat in front of you so as not to make others feel uncomfortable.',
        E'Do not kick the seat in front of you so as not to make others feel uncomfortable',
        E'Don''t kick the front seat so as not to make others feel uncomfortable.',
        E'Don''t kick the front seat so as not to make others feel uncomfortable',
        E'Don''t kick the front seat so as not to make others uncomfortable.',
        E'Don''t kick the front seat so as not to make others uncomfortable'),
      'explanation',E'so as not to + 동사원형: "~하지 않기 위해"'),

    jsonb_build_object('number',37,
      'question',E'[Part 4]\n다음 우리말을 so as not to를 활용하여 영작하시오.\n극장에서 소음을 내지 않기 위해 폰을 꺼야 합니다. [단어: make a noise]',
      'answer',E'You should turn off your phone so as not to make a noise.',
      'acceptedAnswers',jsonb_build_array(
        E'You should turn off your phone so as not to make a noise.',
        E'You should turn off your phone so as not to make a noise',
        E'You should turn off your phone so as not to make noise.',
        E'You should turn off your phone so as not to make noise',
        E'You must turn off your phone so as not to make a noise.',
        E'You must turn off your phone so as not to make a noise',
        E'Turn off your phone so as not to make a noise.',
        E'Turn off your phone so as not to make a noise'),
      'explanation',E'so as not to + 동사원형: "소음을 내지 않기 위해"'),

    jsonb_build_object('number',38,
      'question',E'[Part 4]\n다음 우리말을 so that을 활용하여 영작하시오.\n나는 기차를 제시간에 타기 위해 정말 빨리 달렸다. [단어: so that, could, on time]',
      'answer',E'I hurried so that I could catch a train on time.',
      'acceptedAnswers',jsonb_build_array(
        E'I hurried so that I could catch a train on time.',
        E'I hurried so that I could catch a train on time',
        E'I hurried so that I could catch the train on time.',
        E'I hurried so that I could catch the train on time',
        E'I hurried so that I could take a train on time.',
        E'I hurried so that I could take a train on time',
        E'I hurried so that I could take the train on time.',
        E'I hurried so that I could take the train on time',
        E'I ran so that I could catch a train on time.',
        E'I ran so that I could catch a train on time'),
      'explanation',E'주절이 과거(hurried)이므로 so that + could'),

    jsonb_build_object('number',39,
      'question',E'[Part 4]\n다음 우리말을 so that을 활용하여 영작하시오.\n세종대왕은 한국인들이 쉽게 읽고 쓸 수 있도록 한글을 발명했다.',
      'answer',E'King Sejong invented Hangeul so that Koreans could read and write easily.',
      'acceptedAnswers',jsonb_build_array(
        E'King Sejong invented Hangeul so that Koreans could read and write easily.',
        E'King Sejong invented Hangeul so that Koreans could read and write easily',
        E'King Sejong invented Hangul so that Koreans could read and write easily.',
        E'King Sejong invented Hangul so that Koreans could read and write easily',
        E'King Sejong the Great invented Hangeul so that Koreans could read and write easily.',
        E'King Sejong the Great invented Hangeul so that Koreans could read and write easily'),
      'explanation',E'주절이 과거(invented)이므로 so that + could'),

    jsonb_build_object('number',40,
      'question',E'[Part 4]\n다음 대화를 읽고 B의 대답을 so as not to를 활용하여 완전한 문장으로 쓰시오.\n\nA: 왜 번호를 적고 있니?\nB: 번호를 잊어버리지 않기 위해서 적고 있어.',
      'answer',E'I''m writing it down so as not to forget the number.',
      'acceptedAnswers',jsonb_build_array(
        E'I''m writing it down so as not to forget the number.',
        E'I''m writing it down so as not to forget the number',
        E'I am writing it down so as not to forget the number.',
        E'I am writing it down so as not to forget the number'),
      'explanation',E'so as not to + 동사원형: "잊지 않기 위해"'),

    jsonb_build_object('number',41,
      'question',E'[Part 4]\n다음 우리말을 so that을 활용하여 영작하시오.\n소윤이는 계란을 떨어뜨리지 않기 위해 걸음걸이에 매우 주의했다. [단어: wouldn''t]',
      'answer',E'Soyun was very careful so that she wouldn''t drop the egg.',
      'acceptedAnswers',jsonb_build_array(
        E'Soyun was very careful so that she wouldn''t drop the egg.',
        E'Soyun was very careful so that she wouldn''t drop the egg',
        E'Soyun was very careful so that she would not drop the egg.',
        E'Soyun was very careful so that she would not drop the egg',
        E'So-yun was very careful so that she wouldn''t drop the egg.',
        E'So-yun was very careful so that she wouldn''t drop the egg',
        E'So-yun was very careful so that she would not drop the egg.',
        E'So-yun was very careful so that she would not drop the egg'),
      'explanation',E'so that + would not: 과거 시제에서의 부정 목적'),

    -- ═══════════════════════════════════════════
    -- Part 5: [실전 통영작] 핵심 구문 기반 영작 (Q42~Q51)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',42,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n나는 수리공으로 하여금 나의 차를 수리하도록 하였다. (have 활용)',
      'answer',E'I had the mechanic fix my car.',
      'acceptedAnswers',jsonb_build_array(E'I had the mechanic fix my car.', E'I had the mechanic fix my car', E'I had a mechanic fix my car.', E'I had a mechanic fix my car', E'I had the mechanic repair my car.', E'I had a mechanic repair my car.'),
      'explanation',E'have + 목적어 + 동사원형: "수리공에게 수리하게 시키다"'),

    jsonb_build_object('number',43,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n내가 너를 사랑하고 있다는 것을 네가 이해하게 어떻게 만들 수 있을까?',
      'answer',E'How can I make you understand that I love you?',
      'acceptedAnswers',jsonb_build_array(E'How can I make you understand that I love you?', E'How can I make you understand that I love you'),
      'explanation',E'make + 목적어 + 동사원형: 의문문에서의 사역동사'),

    jsonb_build_object('number',44,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n컴퓨터는 사람들이 더 빨리 일할 수 있도록 도와준다.',
      'answer',E'Computers help people work faster.',
      'acceptedAnswers',jsonb_build_array(E'Computers help people work faster.', E'Computers help people work faster', E'Computers help people to work faster.', E'Computers help people to work faster', E'A computer helps people work faster.', E'A computer helps people to work faster.'),
      'explanation',E'help + 목적어 + 동사원형/to부정사'),

    jsonb_build_object('number',45,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n도서관에서 아이들을 뛰게 하지 마세요. (make 활용)',
      'answer',E'Don''t make children run in the library.',
      'acceptedAnswers',jsonb_build_array(E'Don''t make children run in the library.', E'Don''t make children run in the library', E'Do not make children run in the library.', E'Do not make children run in the library', E'Don''t make kids run in the library.', E'Don''t make the children run in the library.', E'Do not make the children run in the library.'),
      'explanation',E'make + 목적어 + 동사원형의 부정 명령문'),

    jsonb_build_object('number',46,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n그는 이발사에게 자신의 머리를 짧게 깎도록 시켰다. (had 활용)',
      'answer',E'He had the barber cut his hair short.',
      'acceptedAnswers',jsonb_build_array(E'He had the barber cut his hair short.', E'He had the barber cut his hair short', E'He had a barber cut his hair short.', E'He had a barber cut his hair short'),
      'explanation',E'have + 목적어 + 동사원형: "이발사에게 깎게 시키다"'),

    jsonb_build_object('number',47,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n사막여우의 발은 뜨거운 모래 위에서 걸을 수 있도록 털로 덮여 있다.',
      'answer',E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand.',
      'acceptedAnswers',jsonb_build_array(E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand.', E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand', E'A fennec fox''s feet are covered with fur so that it can walk on the hot sand.', E'The fennec fox''s feet are covered in fur so that it can walk on the hot sand.', E'The fennec fox''s feet are covered with fur so that it can walk on hot sand.'),
      'explanation',E'so that + 주어 + can: 목적을 나타내는 접속사'),

    jsonb_build_object('number',48,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n그 의사는 간호사에게 환자의 체온을 재게 했다. (have 활용)',
      'answer',E'The doctor had the nurse take the patient''s temperature.',
      'acceptedAnswers',jsonb_build_array(E'The doctor had the nurse take the patient''s temperature.', E'The doctor had the nurse take the patient''s temperature', E'The doctor had a nurse take the patient''s temperature.', E'The doctor had a nurse take the patient''s temperature'),
      'explanation',E'have + 목적어 + 동사원형: "간호사에게 체온을 재게 시키다"'),

    jsonb_build_object('number',49,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n그녀는 고등학교에 들어갈 수 있도록 열심히 공부한다. (so that 활용)',
      'answer',E'She studies hard so that she can enter the high school.',
      'acceptedAnswers',jsonb_build_array(E'She studies hard so that she can enter the high school.', E'She studies hard so that she can enter the high school', E'She studies hard so that she can enter high school.', E'She studies hard so that she can enter high school', E'She studies hard so that she can get into high school.', E'She studies hard so that she can get into the high school.'),
      'explanation',E'so that + 주어 + can: 현재 시제에서의 목적'),

    jsonb_build_object('number',50,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n우리는 좋은 자리를 잡을 수 있도록 일찍 도착했다. (so that 활용)',
      'answer',E'We arrived early so that we could get good seats.',
      'acceptedAnswers',jsonb_build_array(E'We arrived early so that we could get good seats.', E'We arrived early so that we could get good seats', E'We got there early so that we could get good seats.', E'We arrived early so that we could get the good seats.'),
      'explanation',E'주절이 과거(arrived)이므로 so that + could'),

    jsonb_build_object('number',51,
      'question',E'[Part 5]\n다음 우리말을 사역동사 또는 so that 구문을 사용하여 영어로 옮기시오.\n\n나는 그가 저녁 식사 전에 페인트칠을 끝낼 수 있도록 아버지를 도왔다. (so that 활용)',
      'answer',E'I helped my father paint the wall so that he could finish painting before dinner.',
      'acceptedAnswers',jsonb_build_array(E'I helped my father paint the wall so that he could finish painting before dinner.', E'I helped my father paint the wall so that he could finish painting before dinner', E'I helped my dad paint the wall so that he could finish painting before dinner.', E'I helped my father to paint the wall so that he could finish painting before dinner.'),
      'explanation',E'help + 목적어 + (to)동사원형 + so that + could')
  );

  a := jsonb_build_array(
    E'Dad made the computer work.',
    E'Judy wouldn''t let Junsu use her laptop.',
    E'Judy''s mom made her take care of her sister on Monday.',
    E'Mina made Taesu clean the living room.',
    E'Mina helped Jinsu move the plant.',
    E'Tim''s dad made him clean the floor.',
    E'My mom makes me do my homework before I go out.',
    E'The woman made the boy go to bed early.',
    E'Judy''s mom let her water flowers in the garden on Tuesday.',
    E'Judy''s mom got her to walk her pet dog on Sunday.',
    E'Let him do what he wants.',
    E'makes, look',
    E'Mom had me look for her cellphone.',
    E'makes, excited',
    E'I asked for his phone number so that I could call him.',
    E'I am doing my homework so that I can have fun this afternoon.',
    E'I studied hard so that I could pass the English exam.',
    E'makes, study',
    E'Red makes me think of the 2002 World Cup.',
    E'I took my umbrella in order not to get wet.',
    E'to quit',
    E'to admit',
    E'The barking dog made the postman run away.',
    E'You should drive slowly so as not to have an accident.',
    E'play',
    E'Ms. Yun let me solve a math problem.',
    E'I helped her choose her dress.',
    E'I made my sister clean her room.',
    E'cut',
    E'I often stop working so that I can take a rest.',
    E'won''t let me go',
    E'will make me study',
    E'so that',
    E'Fruits make you healthy.',
    E'A test makes us feel nervous.',
    E'You should not kick the seat in front of you so as not to make others feel uncomfortable.',
    E'You should turn off your phone so as not to make a noise.',
    E'I hurried so that I could catch a train on time.',
    E'King Sejong invented Hangeul so that Koreans could read and write easily.',
    E'I''m writing it down so as not to forget the number.',
    E'Soyun was very careful so that she wouldn''t drop the egg.',
    E'I had the mechanic fix my car.',
    E'How can I make you understand that I love you?',
    E'Computers help people work faster.',
    E'Don''t make children run in the library.',
    E'He had the barber cut his hair short.',
    E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand.',
    E'The doctor had the nurse take the patient''s temperature.',
    E'She studies hard so that she can enter the high school.',
    E'We arrived early so that we could get good seats.',
    E'I helped my father paint the wall so that he could finish painting before dinner.'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    '사역동사 Step 3',
    '사역동사',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
