DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '간접의문문 Step 1';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════
    -- Part 1: 알맞은 표현 고르기 (Q1-Q10) — MCQ 2지선다
    -- ═══════════════════════════════════════
    jsonb_build_object('number',1,
      'question',E'[Part 1] 괄호 안에서 알맞은 표현을 고르시오.\n\nCan you tell me (where is the library / where the library is)?',
      'options',jsonb_build_array('where is the library','where the library is'),
      'answer','2',
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 where the library is가 올바르다.'),
    jsonb_build_object('number',2,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nI''m not sure (that / whether) she passed the test or not.',
      'options',jsonb_build_array('that','whether'),
      'answer','2',
      'explanation',E'or not과 함께 쓸 때는 that이 아니라 whether를 사용한다.'),
    jsonb_build_object('number',3,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nDo you know (what time does the train leave / what time the train leaves)?',
      'options',jsonb_build_array('what time does the train leave','what time the train leaves'),
      'answer','2',
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 what time the train leaves가 올바르다.'),
    jsonb_build_object('number',4,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\n(Who do you think / Do you think who) that man is?',
      'options',jsonb_build_array('Who do you think','Do you think who'),
      'answer','1',
      'explanation',E'think, believe, suppose 등의 동사에서는 의문사가 문두로 나온다.'),
    jsonb_build_object('number',5,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nI wonder (where did I put my phone / where I put my phone).',
      'options',jsonb_build_array('where did I put my phone','where I put my phone'),
      'answer','2',
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 where I put my phone이 올바르다.'),
    jsonb_build_object('number',6,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nCould you tell me (how long does it take / how long it takes) to get there?',
      'options',jsonb_build_array('how long does it take','how long it takes'),
      'answer','2',
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 how long it takes가 올바르다.'),
    jsonb_build_object('number',7,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nI asked (if / what) he could come to the meeting.',
      'options',jsonb_build_array('if','what'),
      'answer','1',
      'explanation',E'yes/no 의문문을 간접의문문으로 바꿀 때는 if 또는 whether를 사용한다.'),
    jsonb_build_object('number',8,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\n(Do you think who / Who do you think) will win the championship?',
      'options',jsonb_build_array('Do you think who','Who do you think'),
      'answer','2',
      'explanation',E'think류 동사에서는 의문사가 문두로 나온다: Who do you think ~?'),
    jsonb_build_object('number',9,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nHe wants to know (why is she upset / why she is upset).',
      'options',jsonb_build_array('why is she upset','why she is upset'),
      'answer','2',
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 why she is upset이 올바르다.'),
    jsonb_build_object('number',10,
      'question',E'괄호 안에서 알맞은 표현을 고르시오.\n\nWhere do you (think / know) she went after school?',
      'options',jsonb_build_array('think','know'),
      'answer','1',
      'explanation',E'의문사가 문두에 나오려면 think, believe, suppose 등의 동사가 필요하다. know는 해당되지 않는다.'),

    -- ═══════════════════════════════════════
    -- Part 2: 대화 완성하기 (Q11-Q20) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',11,
      'question',E'[Part 2] 대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Can you tell me ___?\nB: Her name is Lisa.',
      'answer',E'what her name is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'이름을 묻는 간접의문문: what her name is (의문사+주어+동사 어순)'),
    jsonb_build_object('number',12,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Do you know ___?\nB: Yes, it opens at 9 a.m.',
      'answer',E'what time it opens',
      'acceptedAnswers',jsonb_build_array('when it opens'),
      'explanation',E'시간을 묻는 간접의문문: what time it opens'),
    jsonb_build_object('number',13,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: I wonder ___.\nB: He is from Canada.',
      'answer',E'where he is from',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'출신지를 묻는 간접의문문: where he is from'),
    jsonb_build_object('number',14,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Do you know ___?\nB: Yes, she has two sisters.',
      'answer',E'if she has any sisters',
      'acceptedAnswers',jsonb_build_array('whether she has any sisters','if she has sisters','whether she has sisters'),
      'explanation',E'yes/no 대답이므로 if/whether를 사용한 간접의문문: if she has any sisters'),
    jsonb_build_object('number',15,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Tell me ___.\nB: I''m studying for the math test.',
      'answer',E'what you are doing',
      'acceptedAnswers',jsonb_build_array(E'what you''re doing'),
      'explanation',E'현재 하고 있는 일을 묻는 간접의문문: what you are doing'),
    jsonb_build_object('number',16,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Can you tell me ___?\nB: Yes, he enjoys playing basketball.',
      'answer',E'if he enjoys playing basketball',
      'acceptedAnswers',jsonb_build_array('whether he enjoys playing basketball'),
      'explanation',E'yes/no 대답이므로 if/whether를 사용: if he enjoys playing basketball'),
    jsonb_build_object('number',17,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: I have no idea ___.\nB: Your bag is on the chair.',
      'answer',E'where my bag is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'장소를 묻는 간접의문문: where my bag is (의문사+주어+동사 어순)'),
    jsonb_build_object('number',18,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Do you know ___?\nB: Yes, he is from Australia.',
      'answer',E'where he is from',
      'acceptedAnswers',jsonb_build_array('if he is from Australia','whether he is from Australia'),
      'explanation',E'출신지를 묻거나 yes/no로 확인하는 간접의문문'),
    jsonb_build_object('number',19,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: I''m not sure ___.\nB: The concert starts at 7 p.m.',
      'answer',E'when the concert starts',
      'acceptedAnswers',jsonb_build_array('what time the concert starts'),
      'explanation',E'시간을 묻는 간접의문문: when the concert starts'),
    jsonb_build_object('number',20,
      'question',E'대화의 빈칸에 알맞은 간접의문문을 쓰시오.\n\nA: Do you know ___?\nB: Yes, she likes Italian food.',
      'answer',E'if she likes Italian food',
      'acceptedAnswers',jsonb_build_array('whether she likes Italian food'),
      'explanation',E'yes/no 대답이므로 if/whether를 사용: if she likes Italian food'),

    -- ═══════════════════════════════════════
    -- Part 3: 직접의문문 → 간접의문문 전환 (Q21-Q35) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',21,
      'question',E'[Part 3] 다음 직접의문문을 주어진 표현으로 시작하는 간접의문문으로 바꿔 쓰시오.\n\nWhat does this word mean?\n→ Do you know ___?',
      'answer',E'what this word means',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'does mean → means로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',22,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nHow can I get to the subway station?\n→ Can you tell me ___?',
      'answer',E'how I can get to the subway station',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'의문사+주어+동사 어순: how I can get to the subway station'),
    jsonb_build_object('number',23,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWho broke the vase?\n→ I don''t know ___.',
      'answer',E'who broke the vase',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'who가 주어인 의문문은 어순 변화 없이 그대로 사용한다.'),
    jsonb_build_object('number',24,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhy did she quit her job?\n→ Please tell me ___.',
      'answer',E'why she quit her job',
      'acceptedAnswers',jsonb_build_array('why she quitted her job'),
      'explanation',E'did quit → quit으로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',25,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhere does he work?\n→ I don''t know ___.',
      'answer',E'where he works',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'does work → works로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',26,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nDoes she speak French?\n→ I wonder ___.',
      'answer',E'if she speaks French',
      'acceptedAnswers',jsonb_build_array('whether she speaks French'),
      'explanation',E'yes/no 의문문은 if/whether를 사용하여 간접의문문으로 전환'),
    jsonb_build_object('number',27,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nHow long will the trip take?\n→ I want to know ___.',
      'answer',E'how long the trip will take',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'의문사+주어+동사 어순: how long the trip will take'),
    jsonb_build_object('number',28,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nDid they win the game?\n→ Do you know ___?',
      'answer',E'if they won the game',
      'acceptedAnswers',jsonb_build_array('whether they won the game'),
      'explanation',E'yes/no 의문문은 if/whether 사용, did win → won으로 전환'),
    jsonb_build_object('number',29,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhat made him so angry?\n→ Can you tell me ___?',
      'answer',E'what made him so angry',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'what이 주어인 의문문은 어순 변화 없이 그대로 사용한다.'),
    jsonb_build_object('number',30,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhen does the pharmacy close?\n→ Please tell me ___.',
      'answer',E'when the pharmacy closes',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'does close → closes로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',31,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nIs it safe to swim here?\n→ I wonder ___.',
      'answer',E'if it is safe to swim here',
      'acceptedAnswers',jsonb_build_array('whether it is safe to swim here'),
      'explanation',E'yes/no 의문문은 if/whether를 사용하여 간접의문문으로 전환'),
    jsonb_build_object('number',32,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhich team does he support?\n→ Do you know ___?',
      'answer',E'which team he supports',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'does support → supports로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',33,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nWhy is she smiling?\n→ I don''t know ___.',
      'answer',E'why she is smiling',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'is she smiling → she is smiling으로 의문사+주어+동사 어순 전환'),
    jsonb_build_object('number',34,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nHow much does this jacket cost?\n→ Can you tell me ___?',
      'answer',E'how much this jacket costs',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'does cost → costs로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',35,
      'question',E'직접의문문을 간접의문문으로 바꿔 쓰시오.\n\nDid he finish his homework?\n→ Do you know ___?',
      'answer',E'if he finished his homework',
      'acceptedAnswers',jsonb_build_array('whether he finished his homework'),
      'explanation',E'yes/no 의문문은 if/whether 사용, did finish → finished로 전환'),

    -- ═══════════════════════════════════════
    -- Part 4: 두 문장 합치기 — 빈칸 채우기 (Q36-Q45) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',36,
      'question',E'[Part 4] 두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nWho fixed this computer? Could you tell me?\n→ Could you tell me ___?',
      'answer',E'who fixed this computer',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'who가 주어인 의문문은 어순 변화 없이 그대로 사용한다.'),
    jsonb_build_object('number',37,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nDoes he enjoy cooking? Do you know?\n→ Do you know ___?',
      'answer',E'if he enjoys cooking',
      'acceptedAnswers',jsonb_build_array('whether he enjoys cooking'),
      'explanation',E'yes/no 의문문은 if/whether를 사용, does enjoy → enjoys로 전환'),
    jsonb_build_object('number',38,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nWhy did she change her mind? I don''t know.\n→ I don''t know ___.',
      'answer',E'why she changed her mind',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'did change → changed로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',39,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nHow far is it to the beach? Do you have any idea?\n→ Do you have any idea ___?',
      'answer',E'how far it is to the beach',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'is it → it is로 의문사+주어+동사 어순 전환'),
    jsonb_build_object('number',40,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nI wonder it. What time does the library open?\n→ I wonder ___.',
      'answer',E'what time the library opens',
      'acceptedAnswers',jsonb_build_array('when the library opens'),
      'explanation',E'does open → opens로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',41,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nWhere did she grow up? Tom asked Jenny.\n→ Tom asked Jenny ___.',
      'answer',E'where she grew up',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'did grow up → grew up으로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',42,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nIs it going to rain tomorrow? Sarah wants to know it.\n→ Sarah wants to know ___.',
      'answer',E'if it is going to rain tomorrow',
      'acceptedAnswers',jsonb_build_array('whether it is going to rain tomorrow'),
      'explanation',E'yes/no 의문문은 if/whether를 사용, is it → it is로 어순 전환'),
    jsonb_build_object('number',43,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nDid you reserve a table? I was wondering it.\n→ I was wondering ___.',
      'answer',E'if you had reserved a table',
      'acceptedAnswers',jsonb_build_array('whether you had reserved a table','if you reserved a table','whether you reserved a table'),
      'explanation',E'과거 시제에서 간접의문문: did reserve → had reserved 또는 reserved로 전환'),
    jsonb_build_object('number',44,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nHow did the accident happen? No one knows.\n→ No one knows ___.',
      'answer',E'how the accident happened',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'did happen → happened로 바꾸고 의문사+주어+동사 어순으로 전환'),
    jsonb_build_object('number',45,
      'question',E'두 문장을 한 문장으로 쓸 때, 빈칸에 알맞은 말을 쓰시오.\n\nIs the new student friendly? I''d like to know.\n→ I''d like to know ___.',
      'answer',E'if the new student is friendly',
      'acceptedAnswers',jsonb_build_array('whether the new student is friendly'),
      'explanation',E'yes/no 의문문은 if/whether를 사용, is the new student → the new student is로 어순 전환')
,
    -- ═══════════════════════════════════════
    -- Part 5: 두 문장 합치기 — 자유 작문 (Q46-Q60)
    -- ═══════════════════════════════════════
    jsonb_build_object('number',46,
      'question',E'[Part 5] 두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you think?\n· What is she cooking?',
      'answer',E'What do you think she is cooking?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사 → 의문사(What)가 문두로 이동'),
    jsonb_build_object('number',47,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you know?\n· Where did he move to?',
      'answer',E'Do you know where he moved to?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'know는 think류가 아니므로 의문사가 절 안에 남고, 간접의문문 어순(의문사+주어+동사)을 따른다.'),
    jsonb_build_object('number',48,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you believe?\n· Who stole the money?',
      'answer',E'Who do you believe stole the money?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'believe는 think류 동사이고, who가 주어 역할이므로 의문사(Who)가 문두로 이동한다.'),
    jsonb_build_object('number',49,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· I wonder.\n· How old is your grandmother?',
      'answer',E'I wonder how old your grandmother is.',
      'acceptedAnswers',jsonb_build_array(E'I wonder how old my grandmother is.'),
      'explanation',E'wonder는 think류가 아니므로 간접의문문 어순(의문사+주어+동사)을 따른다.'),
    jsonb_build_object('number',50,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you think?\n· Which is the easiest way to solve this?',
      'answer',E'Which do you think is the easiest way to solve this?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사이고 which가 주어 역할이므로 의문사(Which)가 문두로 이동한다.'),
    jsonb_build_object('number',51,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· She wants to know.\n· When did he get home?',
      'answer',E'She wants to know when he got home.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)으로 변환하고, did 제거 후 동사를 과거형(got)으로 쓴다.'),
    jsonb_build_object('number',52,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· We can''t predict.\n· The results will be good.',
      'answer',E'We can''t predict whether the results will be good.',
      'acceptedAnswers',jsonb_build_array(E'We can''t predict if the results will be good.'),
      'explanation',E'평서문을 간접의문문으로 바꿀 때 whether 또는 if를 사용한다.'),
    jsonb_build_object('number',53,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· I remember.\n· What did you have for breakfast?',
      'answer',E'I remember what you had for breakfast.',
      'acceptedAnswers',jsonb_build_array(E'I remember what I had for breakfast.'),
      'explanation',E'간접의문문 어순(의문사+주어+동사)으로 변환하고, did 제거 후 동사를 과거형(had)으로 쓴다.'),
    jsonb_build_object('number',54,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Can you tell me?\n· What does Amy want for her birthday?',
      'answer',E'Can you tell me what Amy wants for her birthday?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)으로 변환하고, does 제거 후 동사에 -s를 붙인다(wants).'),
    jsonb_build_object('number',55,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you suppose?\n· Where does he come from?',
      'answer',E'Where do you suppose he comes from?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'suppose는 think류 동사이므로 의문사(Where)가 문두로 이동한다.'),
    jsonb_build_object('number',56,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· I wonder.\n· Is Mr. Kim our new homeroom teacher?',
      'answer',E'I wonder if Mr. Kim is our new homeroom teacher.',
      'acceptedAnswers',jsonb_build_array(E'I wonder whether Mr. Kim is our new homeroom teacher.'),
      'explanation',E'yes/no 의문문이므로 if 또는 whether를 사용하여 간접의문문으로 바꾼다.'),
    jsonb_build_object('number',57,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you think?\n· Why did Daniel leave so early?',
      'answer',E'Why do you think Daniel left so early?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사이므로 의문사(Why)가 문두로 이동하고, did 제거 후 동사를 과거형(left)으로 쓴다.'),
    jsonb_build_object('number',58,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· I don''t know.\n· Does Emma have a younger brother?',
      'answer',E'I don''t know if Emma has a younger brother.',
      'acceptedAnswers',jsonb_build_array(E'I don''t know whether Emma has a younger brother.'),
      'explanation',E'yes/no 의문문이므로 if/whether를 사용하고, does 제거 후 동사에 -s(has)를 붙인다.'),
    jsonb_build_object('number',59,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Do you guess?\n· Who can answer this question?',
      'answer',E'Who do you guess can answer this question?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'guess는 think류 동사이고, who가 주어 역할이므로 의문사(Who)가 문두로 이동한다.'),
    jsonb_build_object('number',60,
      'question',E'두 문장을 하나의 간접의문문 문장으로 합치시오.\n\n· Please tell me.\n· How did you learn to play the guitar?',
      'answer',E'Please tell me how you learned to play the guitar.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)으로 변환하고, did 제거 후 동사를 과거형(learned)으로 쓴다.'),

    -- ═══════════════════════════════════════
    -- Part 6: 오류 찾아 전체 문장 고쳐 쓰기 (Q61-Q75)
    -- ═══════════════════════════════════════
    jsonb_build_object('number',61,
      'question',E'[Part 6] 각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nDo you think what she is doing right now?',
      'answer',E'What do you think she is doing right now?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사 → 의문사(what)가 문두로 이동해야 한다.'),
    jsonb_build_object('number',62,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nI don''t know when does the museum open.',
      'answer',E'I don''t know when the museum opens.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 does를 제거하고 3인칭 단수 현재형(opens)을 쓴다.'),
    jsonb_build_object('number',63,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nCan you tell me how old is your sister?',
      'answer',E'Can you tell me how old your sister is?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 how old your sister is가 올바르다.'),
    jsonb_build_object('number',64,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nPlease tell me who did win the award.',
      'answer',E'Please tell me who won the award.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'who가 주어일 때 do/did 조동사가 불필요하므로 제거하고 동사를 과거형(won)으로 쓴다.'),
    jsonb_build_object('number',65,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nI wonder can they finish the project on time.',
      'answer',E'I wonder if they can finish the project on time.',
      'acceptedAnswers',jsonb_build_array(E'I wonder whether they can finish the project on time.'),
      'explanation',E'yes/no 의문문을 간접의문문으로 바꿀 때 if 또는 whether가 필요하다.'),
    jsonb_build_object('number',66,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nI couldn''t understand why does he act like that.',
      'answer',E'I couldn''t understand why he acts like that.',
      'acceptedAnswers',jsonb_build_array(E'I couldn''t understand why he acted like that.'),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 does를 제거하고, 동사에 3인칭 단수형(-s)을 붙인다.'),
    jsonb_build_object('number',67,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nWho do you know broke the rule?',
      'answer',E'Do you know who broke the rule?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'know는 think류 동사가 아니므로 의문사가 문두로 나갈 수 없다. 의문사(who)는 절 안에 남아야 한다.'),
    jsonb_build_object('number',68,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nI''m not sure if is the information correct.',
      'answer',E'I''m not sure if the information is correct.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'if절 안에서도 「주어+동사」 어순을 따라야 하므로 the information is correct가 올바르다.'),
    jsonb_build_object('number',69,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nDo you remember when did you last see her?',
      'answer',E'Do you remember when you last saw her?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 did를 제거하고, 동사를 과거형(saw)으로 바꾼다.'),
    jsonb_build_object('number',70,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nShe asked me when did the show begin.',
      'answer',E'She asked me when the show began.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 did를 제거하고, 시제를 일치시켜 과거형(began)으로 쓴다.'),
    jsonb_build_object('number',71,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nDo you think who will get the prize?',
      'answer',E'Who do you think will get the prize?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사이므로 의문사(Who)가 문두로 이동해야 한다.'),
    jsonb_build_object('number',72,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nI don''t know where is the nearest hospital.',
      'answer',E'I don''t know where the nearest hospital is.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 where the nearest hospital is가 올바르다.'),
    jsonb_build_object('number',73,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nShe would like to know if Mr. Lee goes to work yesterday.',
      'answer',E'She would like to know if Mr. Lee went to work yesterday.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'yesterday는 과거 시점이므로 동사를 과거시제(went)로 써야 한다.'),
    jsonb_build_object('number',74,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nTell me how tall is he.',
      'answer',E'Tell me how tall he is.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문은 「의문사+주어+동사」 어순이므로 how tall he is가 올바르다.'),
    jsonb_build_object('number',75,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 다시 쓰시오.\n\nDo you know how a dolphin lives long?',
      'answer',E'Do you know how long a dolphin lives?',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'「의문사+형용사」(how long)가 한 덩어리로 앞에 와야 한다.'),

    -- ═══════════════════════════════════════
    -- Part 7: 대화 완성하기 — 보기 참고 (Q76-Q85)
    -- ═══════════════════════════════════════
    jsonb_build_object('number',76,
      'question',E'[Part 7] 보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: Where is your brother?\nB: I don''t know ___.',
      'answer',E'where my brother is',
      'acceptedAnswers',jsonb_build_array(E'where he is'),
      'explanation',E'간접의문문 어순(의문사+주어+동사)으로 바꾸고, your→my로 인칭을 전환한다.'),
    jsonb_build_object('number',77,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: What time is it now?\nB: I''m not sure ___.',
      'answer',E'what time it is now',
      'acceptedAnswers',jsonb_build_array(E'what time it is'),
      'explanation',E'간접의문문 어순(의문사+주어+동사): what time it is now'),
    jsonb_build_object('number',78,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: Who is that tall boy?\nB: I don''t know ___.',
      'answer',E'who that tall boy is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): who that tall boy is'),
    jsonb_build_object('number',79,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: How much is the ticket?\nB: I''m not sure ___.',
      'answer',E'how much the ticket is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): how much the ticket is'),
    jsonb_build_object('number',80,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: When does the next bus come?\nB: I don''t know ___.',
      'answer',E'when the next bus comes',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 does를 제거하고 동사에 -s(comes)를 붙인다.'),
    jsonb_build_object('number',81,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: What sport does she like most?\nB: I don''t know ___.',
      'answer',E'what sport she likes most',
      'acceptedAnswers',jsonb_build_array(E'what sport she likes the most'),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 does를 제거하고 동사에 -s(likes)를 붙인다.'),
    jsonb_build_object('number',82,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: Why is he so tired today?\nB: I have no idea ___.',
      'answer',E'why he is so tired today',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): why he is so tired today'),
    jsonb_build_object('number',83,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: Does she enjoy reading?\nB: I don''t know ___.',
      'answer',E'if she enjoys reading',
      'acceptedAnswers',jsonb_build_array(E'whether she enjoys reading'),
      'explanation',E'yes/no 의문문이므로 if 또는 whether를 사용하고, does를 제거 후 동사에 -s(enjoys)를 붙인다.'),
    jsonb_build_object('number',84,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: Where did you leave your keys?\nB: I can''t remember ___.',
      'answer',E'where I left my keys',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 did를 제거하고 동사를 과거형(left)으로 쓴다. you→I, your→my 인칭 전환.'),
    jsonb_build_object('number',85,
      'question',E'보기와 같이 B의 대답을 완성하시오.\n<보기> A: Where is my umbrella? / B: I don''t know where your umbrella is.\n\nA: What subject does he like most?\nB: I''m sorry, but I don''t know ___.',
      'answer',E'what subject he likes most',
      'acceptedAnswers',jsonb_build_array(E'what subject he likes the most'),
      'explanation',E'간접의문문 어순(의문사+주어+동사)에서 does를 제거하고 동사에 -s(likes)를 붙인다.'),

    -- ═══════════════════════════════════════
    -- Part 8: 단어 배열하기 (Q86-Q95)
    -- ═══════════════════════════════════════
    jsonb_build_object('number',86,
      'question',E'[Part 8] 괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nTell me (I, the door, how, can open).',
      'answer',E'how I can open the door',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): how I can open the door'),
    jsonb_build_object('number',87,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nLet''s find out (leave, when, we, will).',
      'answer',E'when we will leave',
      'acceptedAnswers',jsonb_build_array(E'Let''s find out when we will leave.'),
      'explanation',E'간접의문문 어순(의문사+주어+동사): when we will leave'),
    jsonb_build_object('number',88,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nShe wanted to know (got, Jake, why, nervous).',
      'answer',E'why Jake got nervous',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): why Jake got nervous'),
    jsonb_build_object('number',89,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nI can''t recall (left, my, where, I, wallet).',
      'answer',E'where I left my wallet',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'간접의문문 어순(의문사+주어+동사): where I left my wallet'),
    jsonb_build_object('number',90,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(you, think, what, do) they are arguing about?',
      'answer',E'What do you think',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사이므로 의문사(What)가 문두로 이동한다. 전체 문장: What do you think they are arguing about?'),
    jsonb_build_object('number',91,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(know, when, you, do) your mom will be back?',
      'answer',E'Do you know when',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'know는 think류가 아니므로 의문사(when)가 문두로 나가지 않는다. 전체 문장: Do you know when your mom will be back?'),
    jsonb_build_object('number',92,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nI''m not certain (is, whether, the, shop, open) on holidays.',
      'answer',E'whether the shop is open',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'whether절 안에서 「주어+동사」 어순을 따른다: whether the shop is open'),
    jsonb_build_object('number',93,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nI''m not sure (snow, if, will, it) this weekend.',
      'answer',E'if it will snow',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'if절 안에서 「주어+동사」 어순을 따른다: if it will snow'),
    jsonb_build_object('number',94,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(do, how, think, you) I can improve my English?',
      'answer',E'How do you think',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'think류 동사이므로 의문사(How)가 문두로 이동한다. 전체 문장: How do you think I can improve my English?'),
    jsonb_build_object('number',95,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(believe, you, who, do) broke the class window?',
      'answer',E'Who do you believe',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'believe는 think류 동사이고 who가 주어이므로 의문사(Who)가 문두로 이동한다. 전체 문장: Who do you believe broke the class window?'),

    -- ═══════════════════════════════════════
    -- Part 9: 한→영 영작 (Q96-Q100)
    -- ═══════════════════════════════════════
    jsonb_build_object('number',96,
      'question',E'[Part 9] 주어진 힌트를 활용하여 문장을 영작하시오.\n\n너는 그 가수가 어디 출신인지 아니? (know, where, from)',
      'answer',E'Do you know where the singer is from?',
      'acceptedAnswers',jsonb_build_array(E'Do you know where that singer is from?'),
      'explanation',E'know + 간접의문문 어순(의문사+주어+동사): Do you know where the singer is from?'),
    jsonb_build_object('number',97,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n나는 그녀가 그 파티에 올지 궁금하다. (wonder, if, come)',
      'answer',E'I wonder if she will come to the party.',
      'acceptedAnswers',jsonb_build_array(E'I wonder whether she will come to the party.'),
      'explanation',E'~올지(yes/no)이므로 if 또는 whether를 사용한다: I wonder if she will come to the party.'),
    jsonb_build_object('number',98,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그는 나에게 시험이 언제 시작하는지 물었다. (ask, when, start)',
      'answer',E'He asked me when the exam starts.',
      'acceptedAnswers',jsonb_build_array(E'He asked me when the exam started.',E'He asked me when the test starts.',E'He asked me when the test started.'),
      'explanation',E'ask + 간접의문문 어순(의문사+주어+동사): He asked me when the exam starts.'),
    jsonb_build_object('number',99,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n너는 문제가 뭐라고 생각하니? (think, what, the problem)',
      'answer',E'What do you think the problem is?',
      'acceptedAnswers',jsonb_build_array(E'What do you think is the problem?'),
      'explanation',E'think류 동사이므로 의문사(What)가 문두로 이동한다: What do you think the problem is?'),
    jsonb_build_object('number',100,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n아무도 그가 어디로 갔는지 모른다. (no one, know, go)',
      'answer',E'No one knows where he went.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'No one + 3인칭 단수 동사(knows) + 간접의문문 어순: No one knows where he went.')  );

  a := jsonb_build_array(
    -- Part 1 (Q1-Q10) MCQ answers (1-based index)
    '2','2','2','1','2','2','1','2','2','1',
    -- Part 2 (Q11-Q20)
    E'what her name is',
    E'what time it opens',
    E'where he is from',
    E'if she has any sisters',
    E'what you are doing',
    E'if he enjoys playing basketball',
    E'where my bag is',
    E'where he is from',
    E'when the concert starts',
    E'if she likes Italian food',
    -- Part 3 (Q21-Q35)
    E'what this word means',
    E'how I can get to the subway station',
    E'who broke the vase',
    E'why she quit her job',
    E'where he works',
    E'if she speaks French',
    E'how long the trip will take',
    E'if they won the game',
    E'what made him so angry',
    E'when the pharmacy closes',
    E'if it is safe to swim here',
    E'which team he supports',
    E'why she is smiling',
    E'how much this jacket costs',
    E'if he finished his homework',
    -- Part 4 (Q36-Q45)
    E'who fixed this computer',
    E'if he enjoys cooking',
    E'why she changed her mind',
    E'how far it is to the beach',
    E'what time the library opens',
    E'where she grew up',
    E'if it is going to rain tomorrow',
    E'if you had reserved a table',
    E'how the accident happened',
    E'if the new student is friendly',
    -- Part 5 (Q46-Q60)
    E'What do you think she is cooking?',
    E'Do you know where he moved to?',
    E'Who do you believe stole the money?',
    E'I wonder how old your grandmother is.',
    E'Which do you think is the easiest way to solve this?',
    E'She wants to know when he got home.',
    E'We can''t predict whether the results will be good.',
    E'I remember what you had for breakfast.',
    E'Can you tell me what Amy wants for her birthday?',
    E'Where do you suppose he comes from?',
    E'I wonder if Mr. Kim is our new homeroom teacher.',
    E'Why do you think Daniel left so early?',
    E'I don''t know if Emma has a younger brother.',
    E'Who do you guess can answer this question?',
    E'Please tell me how you learned to play the guitar.',
    -- Part 6 (Q61-Q75)
    E'What do you think she is doing right now?',
    E'I don''t know when the museum opens.',
    E'Can you tell me how old your sister is?',
    E'Please tell me who won the award.',
    E'I wonder if they can finish the project on time.',
    E'I couldn''t understand why he acts like that.',
    E'Do you know who broke the rule?',
    E'I''m not sure if the information is correct.',
    E'Do you remember when you last saw her?',
    E'She asked me when the show began.',
    E'Who do you think will get the prize?',
    E'I don''t know where the nearest hospital is.',
    E'She would like to know if Mr. Lee went to work yesterday.',
    E'Tell me how tall he is.',
    E'Do you know how long a dolphin lives?',
    -- Part 7 (Q76-Q85)
    E'where my brother is',
    E'what time it is now',
    E'who that tall boy is',
    E'how much the ticket is',
    E'when the next bus comes',
    E'what sport she likes most',
    E'why he is so tired today',
    E'if she enjoys reading',
    E'where I left my keys',
    E'what subject he likes most',
    -- Part 8 (Q86-Q95)
    E'how I can open the door',
    E'when we will leave',
    E'why Jake got nervous',
    E'where I left my wallet',
    E'What do you think',
    E'Do you know when',
    E'whether the shop is open',
    E'if it will snow',
    E'How do you think',
    E'Who do you believe',
    -- Part 9 (Q96-Q100)
    E'Do you know where the singer is from?',
    E'I wonder if she will come to the party.',
    E'He asked me when the exam starts.',
    E'What do you think the problem is?',
    E'No one knows where he went.'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    '간접의문문 Step 1',
    '간접의문문',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
