-- 접속사 because Step 1 — 80문항 (서술형)
-- template_topic: 접속사 because
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '접속사 because Step 1';

  q := jsonb_build_array(
jsonb_build_object('number',1,
  'question',E'[Warm-up: 접속사 because 기본 전환] 다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nShe stayed inside. It was snowing heavily.',
  'answer',E'She stayed inside because it was snowing heavily.',
  'similar_answers',jsonb_build_array(E'Because it was snowing heavily, she stayed inside.'),
  'explanation',E'결과 because 원인 / Because 원인, 결과'),
jsonb_build_object('number',2,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nHe missed the bus. He woke up too late.',
  'answer',E'He missed the bus because he woke up too late.',
  'similar_answers',jsonb_build_array(E'Because he woke up too late, he missed the bus.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',3,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nThey canceled the picnic. The weather was terrible.',
  'answer',E'They canceled the picnic because the weather was terrible.',
  'similar_answers',jsonb_build_array(E'Because the weather was terrible, they canceled the picnic.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',4,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nI turned on the heater. The room was freezing cold.',
  'answer',E'I turned on the heater because the room was freezing cold.',
  'similar_answers',jsonb_build_array(E'Because the room was freezing cold, I turned on the heater.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',5,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nThe soccer match was postponed. A heavy storm was approaching.',
  'answer',E'The soccer match was postponed because a heavy storm was approaching.',
  'similar_answers',jsonb_build_array(E'Because a heavy storm was approaching, the soccer match was postponed.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',6,
  'question',E'다음 보기 중 알맞은 것을 골라 빈칸을 완성하시오.\n\n보기: ⓐ had too much homework to finish / ⓑ felt dizzy and could not stand up / ⓒ missed the last train home / ⓓ kept breaking his promises to his friends\n\nSora skipped PE class today because she ___.',
  'answer',E'felt dizzy and could not stand up',
  'similar_answers',jsonb_build_array(E'ⓑ',E'ⓑ felt dizzy and could not stand up'),
  'explanation',E'PE를 빠진 이유 → 어지러워서'),
jsonb_build_object('number',7,
  'question',E'다음 보기 중 알맞은 것을 골라 빈칸을 완성하시오.\n\n보기: ⓐ had too much homework to finish / ⓑ felt dizzy and could not stand up / ⓒ missed the last train home / ⓓ kept breaking his promises to his friends\n\nBecause Junho ___, his friends stopped trusting him.',
  'answer',E'kept breaking his promises to his friends',
  'similar_answers',jsonb_build_array(E'ⓓ',E'ⓓ kept breaking his promises to his friends'),
  'explanation',E'친구들이 신뢰를 잃은 이유 → 약속을 계속 어겨서'),
jsonb_build_object('number',8,
  'question',E'다음 보기 중 알맞은 것을 골라 빈칸을 완성하시오.\n\n보기: ⓐ had too much homework to finish / ⓑ felt dizzy and could not stand up / ⓒ missed the last train home / ⓓ kept breaking his promises to his friends\n\nShe could not hand in her report on time because she ___.',
  'answer',E'had too much homework to finish',
  'similar_answers',jsonb_build_array(E'ⓐ',E'ⓐ had too much homework to finish'),
  'explanation',E'보고서를 못 낸 이유 → 숙제가 너무 많아서'),
jsonb_build_object('number',9,
  'question',E'[Part 1: so → because 전환 + 두 문장 합치기] 다음 문장을 because를 사용하여 다시 쓰시오.\nShe studied hard so she passed the exam.',
  'answer',E'She passed the exam because she studied hard.',
  'similar_answers',jsonb_build_array(E'Because she studied hard, she passed the exam.'),
  'explanation',E'so(결과→원인 순) → because(결과 because 원인)'),
jsonb_build_object('number',10,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nThe baby was crying so my mom couldn''t sleep.',
  'answer',E'My mom couldn''t sleep because the baby was crying.',
  'similar_answers',jsonb_build_array(E'Because the baby was crying, my mom couldn''t sleep.',E'My mom couldn''t sleep because the baby was crying.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',11,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nHe had no money left so he couldn''t buy the jacket.',
  'answer',E'He couldn''t buy the jacket because he had no money left.',
  'similar_answers',jsonb_build_array(E'Because he had no money left, he couldn''t buy the jacket.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',12,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nShe was allergic to cats so she didn''t adopt one.',
  'answer',E'She didn''t adopt a cat because she was allergic to cats.',
  'similar_answers',jsonb_build_array(E'Because she was allergic to cats, she didn''t adopt one.',E'She didn''t adopt one because she was allergic to cats.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',13,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nThe roads were icy so the school bus arrived late.',
  'answer',E'The school bus arrived late because the roads were icy.',
  'similar_answers',jsonb_build_array(E'Because the roads were icy, the school bus arrived late.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',14,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nHe wanted to be a pilot so he took flying lessons every weekend.',
  'answer',E'He took flying lessons every weekend because he wanted to be a pilot.',
  'similar_answers',jsonb_build_array(E'Because he wanted to be a pilot, he took flying lessons every weekend.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',15,
  'question',E'다음 문장을 because를 사용하여 다시 쓰시오.\nHer phone battery died so she couldn''t call for help.',
  'answer',E'She couldn''t call for help because her phone battery died.',
  'similar_answers',jsonb_build_array(E'Because her phone battery died, she couldn''t call for help.'),
  'explanation',E'so→because 전환'),
jsonb_build_object('number',16,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nThe concert was sold out. / Thousands of fans wanted to see the band.',
  'answer',E'The concert was sold out because thousands of fans wanted to see the band.',
  'similar_answers',jsonb_build_array(E'Because thousands of fans wanted to see the band, the concert was sold out.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',17,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nWe had to cancel the camping trip. / The forest fire warning was at its highest level.',
  'answer',E'We had to cancel the camping trip because the forest fire warning was at its highest level.',
  'similar_answers',jsonb_build_array(E'Because the forest fire warning was at its highest level, we had to cancel the camping trip.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',18,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nMany sea animals are losing their homes. / Ocean temperatures are rising rapidly.',
  'answer',E'Many sea animals are losing their homes because ocean temperatures are rising rapidly.',
  'similar_answers',jsonb_build_array(E'Because ocean temperatures are rising rapidly, many sea animals are losing their homes.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',19,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nShe reads English novels every night. / She wants to improve her vocabulary.',
  'answer',E'She reads English novels every night because she wants to improve her vocabulary.',
  'similar_answers',jsonb_build_array(E'Because she wants to improve her vocabulary, she reads English novels every night.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',20,
  'question',E'다음 두 문장을 because를 사용하여 한 문장으로 합치시오.\nThe stray dog was taken to the shelter. / It had been wandering the streets for days.',
  'answer',E'The stray dog was taken to the shelter because it had been wandering the streets for days.',
  'similar_answers',jsonb_build_array(E'Because it had been wandering the streets for days, the stray dog was taken to the shelter.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',21,
  'question',E'[Part 2: because vs because of] 빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nI couldn''t sleep last night ___ the noise from the construction site.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'the noise(명사구) → because of'),
jsonb_build_object('number',22,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nHe had to wear sunglasses ___ the sunlight was too bright.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'the sunlight was(절) → because'),
jsonb_build_object('number',23,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nThe flight was canceled ___ a sudden engine problem.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'a sudden engine problem(명사구) → because of'),
jsonb_build_object('number',24,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nShe felt proud ___ her son won first place in the science contest.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'her son won(절) → because'),
jsonb_build_object('number',25,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nThe mountain trail was closed ___ the heavy snowfall.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'the heavy snowfall(명사구) → because of'),
jsonb_build_object('number',26,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nHe quit the team ___ the coach never gave him a chance to play.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'the coach never gave(절) → because'),
jsonb_build_object('number',27,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nWe had to leave the beach early ___ the jellyfish warning.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'the jellyfish warning(명사구) → because of'),
jsonb_build_object('number',28,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nThe old bridge was torn down ___ it was no longer safe to use.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'it was(절) → because'),
jsonb_build_object('number',29,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nMany students struggled on the test ___ its unexpected difficulty.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'its unexpected difficulty(명사구) → because of'),
jsonb_build_object('number',30,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nShe turned down the job offer ___ the salary was too low.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'the salary was(절) → because'),
jsonb_build_object('number',31,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nThe event had to be moved indoors ___ the sudden change in weather.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'the sudden change(명사구) → because of'),
jsonb_build_object('number',32,
  'question',E'빈칸에 because 또는 because of 중 알맞은 것을 쓰시오.\nHe was disqualified from the race ___ he had started before the signal.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'he had started(절) → because')
,
-- Part 3: because / so / but / and 선택 (Q33-52)
jsonb_build_object('number',33,
  'question',E'[Part 3] 빈칸에 알맞은 접속사를 쓰시오. (because / so / but / and)\n\nShe wanted to go hiking, ___ it was raining, so she stayed home.',
  'answer',E'but',
  'similar_answers',jsonb_build_array(E'But'),
  'explanation',E'원했지만(대조) → but'),
jsonb_build_object('number',34,
  'question',E'I forgot to charge my phone, ___ the battery died during the trip.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'원인→결과 → so'),
jsonb_build_object('number',35,
  'question',E'He wore a thick coat ___ it was extremely cold outside.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',36,
  'question',E'The store was closed, ___ we had to find another one nearby.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'원인→결과 → so'),
jsonb_build_object('number',37,
  'question',E'She is shy ___ her brother is very outgoing.',
  'answer',E'but',
  'similar_answers',jsonb_build_array(E'But'),
  'explanation',E'대조 → but'),
jsonb_build_object('number',38,
  'question',E'I skipped breakfast ___ I was running late for school.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',39,
  'question',E'He likes action movies ___ documentaries.',
  'answer',E'and',
  'similar_answers',jsonb_build_array(E'And'),
  'explanation',E'나열 → and'),
jsonb_build_object('number',40,
  'question',E'The museum was free that day, ___ there were long lines everywhere.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'무료→긴 줄(결과) → so'),
jsonb_build_object('number',41,
  'question',E'She trains six days a week ___ she wants to compete professionally.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',42,
  'question',E'I enjoy cooking ___ I''m not very good at it yet.',
  'answer',E'but',
  'similar_answers',jsonb_build_array(E'But'),
  'explanation',E'대조 → but'),
jsonb_build_object('number',43,
  'question',E'The project deadline was moved up, ___ the team had to work overtime.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'원인→결과 → so'),
jsonb_build_object('number',44,
  'question',E'She couldn''t enter the building ___ she had forgotten her ID card.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',45,
  'question',E'He is good at math ___ science.',
  'answer',E'and',
  'similar_answers',jsonb_build_array(E'And'),
  'explanation',E'나열 → and'),
jsonb_build_object('number',46,
  'question',E'The movie got great reviews, ___ I found it rather boring.',
  'answer',E'but',
  'similar_answers',jsonb_build_array(E'But'),
  'explanation',E'대조 → but'),
jsonb_build_object('number',47,
  'question',E'She lost her wallet on the subway, ___ she had to borrow money from her friend.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'원인→결과 → so'),
jsonb_build_object('number',48,
  'question',E'We couldn''t play outside ___ the fine dust level was dangerously high.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',49,
  'question',E'He is hardworking ___ honest, which is why everyone trusts him.',
  'answer',E'and',
  'similar_answers',jsonb_build_array(E'And'),
  'explanation',E'나열 → and'),
jsonb_build_object('number',50,
  'question',E'I wanted to order pizza, ___ the restaurant only delivered after 6 p.m.',
  'answer',E'but',
  'similar_answers',jsonb_build_array(E'But'),
  'explanation',E'대조 → but'),
jsonb_build_object('number',51,
  'question',E'She had practiced for months, ___ she performed the piece perfectly.',
  'answer',E'so',
  'similar_answers',jsonb_build_array(E'So'),
  'explanation',E'원인→결과 → so'),
jsonb_build_object('number',52,
  'question',E'He didn''t apply for the scholarship ___ he thought he didn''t qualify.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
-- Part 4: 오류 수정 + 대화문 빈칸 (Q53-64)
jsonb_build_object('number',53,
  'question',E'[Part 4] 밑줄 친 부분을 올바르게 고쳐 쓰시오.\n\nFind error: She was exhausted <u>because of</u> she had worked for twelve hours straight.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because',E'because (because of → because)'),
  'explanation',E'뒤에 절(she had worked) → because of가 아니라 because'),
jsonb_build_object('number',54,
  'question',E'Find error: <u>Because</u> the storm, all flights were grounded for the night.',
  'answer',E'Because of',
  'similar_answers',jsonb_build_array(E'because of',E'Because of the storm'),
  'explanation',E'뒤에 명사구(the storm) → Because가 아니라 Because of'),
jsonb_build_object('number',55,
  'question',E'Find error: Because he trained so hard he won the championship.',
  'answer',E'Because he trained so hard, he won the championship.',
  'similar_answers',jsonb_build_array(E'Because he trained so hard, he won the championship'),
  'explanation',E'Because절이 앞에 올 때 콤마 필요 → hard 뒤에 콤마 추가'),
jsonb_build_object('number',56,
  'question',E'Find error: She didn''t come to school <u>because of</u> her leg was badly injured.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because',E'because (because of → because)'),
  'explanation',E'뒤에 절(her leg was) → because'),
jsonb_build_object('number',57,
  'question',E'Find error: He couldn''t sleep <u>because</u> the loud music from the party next door.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of',E'because of the loud music'),
  'explanation',E'뒤에 명사구(the loud music) → because가 아니라 because of'),
jsonb_build_object('number',58,
  'question',E'Find error: <u>Because of</u> she missed the bus, she arrived at the interview thirty minutes late.',
  'answer',E'Because',
  'similar_answers',jsonb_build_array(E'because',E'Because (Because of → Because)'),
  'explanation',E'뒤에 절(she missed) → Because of가 아니라 Because'),
jsonb_build_object('number',59,
  'question',E'빈칸에 알맞은 말을 쓰시오.\n\nA: Why did you leave the party so early?\nB: I left early ___ I had an important exam the next morning.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'이유 → because'),
jsonb_build_object('number',60,
  'question',E'A: You look really tired today.\nB: Yeah, I couldn''t fall asleep ___ the heat. My air conditioner broke last night.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'the heat(명사) → because of'),
jsonb_build_object('number',61,
  'question',E'A: Did you hear the school festival was canceled?\nB: Yes. ___ the weather forecast showed heavy rain all day, the teachers decided to cancel it.',
  'answer',E'Because',
  'similar_answers',jsonb_build_array(E'because'),
  'explanation',E'문장 앞 + 절(the weather forecast showed) → Because'),
jsonb_build_object('number',62,
  'question',E'A: I heard Jiho didn''t make the team.\nB: Right. It was a shame ___ he had trained so hard for months.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'뒤에 절 → because'),
jsonb_build_object('number',63,
  'question',E'A: Why is the gym closed today?\nB: It''s closed ___ a water pipe burst this morning. They need the whole day to fix it.',
  'answer',E'because of',
  'similar_answers',jsonb_build_array(E'Because of'),
  'explanation',E'a water pipe burst(명사구: 수도관 파열) → because of'),
jsonb_build_object('number',64,
  'question',E'A: How come you didn''t answer my calls?\nB: Sorry! My phone was on silent ___ I was in the middle of an important presentation.',
  'answer',E'because',
  'similar_answers',jsonb_build_array(E'Because'),
  'explanation',E'뒤에 절 → because'),
-- Part 5: 어순 배열 (Q65-72)
jsonb_build_object('number',65,
  'question',E'[Part 5] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\n(studied / because / they / hard / so), they finished the project ahead of schedule.',
  'answer',E'Because they studied so hard, they finished the project ahead of schedule.',
  'similar_answers',jsonb_build_array(E'Because they studied so hard, they finished the project ahead of schedule',E'because they studied so hard, they finished the project ahead of schedule.',E'because they studied so hard, they finished the project ahead of schedule'),
  'explanation',E'Because + S + V 어순'),
jsonb_build_object('number',66,
  'question',E'We had to wear masks (of / because / the / dust / fine / levels / high).',
  'answer',E'We had to wear masks because of the high fine dust levels.',
  'similar_answers',jsonb_build_array(E'we had to wear masks because of the high fine dust levels.',E'We had to wear masks because of the high fine dust levels'),
  'explanation',E'because of + 명사구'),
jsonb_build_object('number',67,
  'question',E'(dangerous / the / was / road / because / icy / so), the drivers slowed down.',
  'answer',E'Because the road was so icy and dangerous, the drivers slowed down.',
  'similar_answers',jsonb_build_array(E'Because the dangerous road was so icy, the drivers slowed down.',E'because the road was so icy and dangerous, the drivers slowed down.',E'because the road was so icy and dangerous, the drivers slowed down'),
  'explanation',E'Because + S + V + 형용사'),
jsonb_build_object('number',68,
  'question',E'She had to repeat the year (she / because / too / many / had / missed / classes).',
  'answer',E'She had to repeat the year because she had missed too many classes.',
  'similar_answers',jsonb_build_array(E'she had to repeat the year because she had missed too many classes.',E'She had to repeat the year because she had missed too many classes'),
  'explanation',E'because + S + V'),
jsonb_build_object('number',69,
  'question',E'(of / the / because / power / outage), the entire neighborhood was in the dark for hours.',
  'answer',E'Because of the power outage, the entire neighborhood was in the dark for hours.',
  'similar_answers',jsonb_build_array(E'because of the power outage, the entire neighborhood was in the dark for hours.',E'Because of the power outage, the entire neighborhood was in the dark for hours'),
  'explanation',E'Because of + 명사구'),
jsonb_build_object('number',70,
  'question',E'He could not focus on his work (because / his / noisy / were / neighbors / so).',
  'answer',E'He could not focus on his work because his neighbors were so noisy.',
  'similar_answers',jsonb_build_array(E'he could not focus on his work because his neighbors were so noisy.',E'He could not focus on his work because his neighbors were so noisy'),
  'explanation',E'because + S + V'),
jsonb_build_object('number',71,
  'question',E'(rising / are / because / costs / living / of), many young people cannot afford to rent an apartment.',
  'answer',E'Because of rising living costs, many young people cannot afford to rent an apartment.',
  'similar_answers',jsonb_build_array(E'because of rising living costs, many young people cannot afford to rent an apartment.',E'Because of rising living costs, many young people cannot afford to rent an apartment'),
  'explanation',E'Because of + 명사구'),
jsonb_build_object('number',72,
  'question',E'The baby woke up (was / because / there / loud / a / noise / outside).',
  'answer',E'The baby woke up because there was a loud noise outside.',
  'similar_answers',jsonb_build_array(E'the baby woke up because there was a loud noise outside.',E'The baby woke up because there was a loud noise outside'),
  'explanation',E'because + there was'),
-- Part 6: 조건 영작 (Q73-80)
jsonb_build_object('number',73,
  'question',E'[Part 6] 조건에 맞게 영작하시오.\n\n날씨가 너무 더워서, 우리는 수영장에 갔다. [because절 문장 앞 / 콤마]',
  'answer',E'Because the weather was so hot, we went to the swimming pool.',
  'similar_answers',jsonb_build_array(E'Because it was so hot, we went to the swimming pool.',E'because the weather was so hot, we went to the swimming pool.'),
  'explanation',E'Because + 절, 결과'),
jsonb_build_object('number',74,
  'question',E'교통 체증 때문에 그는 회의에 늦었다. [because of / 7단어]',
  'answer',E'He was late for the meeting because of traffic.',
  'similar_answers',jsonb_build_array(E'He was late because of the traffic.',E'he was late for the meeting because of traffic.'),
  'explanation',E'because of + 명사'),
jsonb_build_object('number',75,
  'question',E'그녀는 영어를 잘하기 때문에 통역사가 될 수 있었다. [because절 문장 뒤]',
  'answer',E'She was able to become an interpreter because she was good at English.',
  'similar_answers',jsonb_build_array(E'She could become an interpreter because she was good at English.',E'she was able to become an interpreter because she was good at English.'),
  'explanation',E'결과 because 원인'),
jsonb_build_object('number',76,
  'question',E'갑작스러운 정전 때문에, 수업이 일찍 끝났다. [Because of로 시작]',
  'answer',E'Because of the sudden power outage, the class ended early.',
  'similar_answers',jsonb_build_array(E'because of the sudden power outage, the class ended early.',E'Because of the sudden power outage, the class ended early'),
  'explanation',E'Because of + 명사구, 결과'),
jsonb_build_object('number',77,
  'question',E'그는 열쇠를 집에 두고 왔기 때문에 문을 잠글 수 없었다. [because / forget, lock 사용]',
  'answer',E'He couldn''t lock the door because he had forgotten his key at home.',
  'similar_answers',jsonb_build_array(E'He could not lock the door because he had forgotten his key at home.',E'He couldn''t lock the door because he forgot his key at home.'),
  'explanation',E'because + 절, forget/lock 사용'),
jsonb_build_object('number',78,
  'question',E'심한 두통 때문에 그녀는 일찍 퇴근했다. [because of / 8단어]',
  'answer',E'She left work early because of a severe headache.',
  'similar_answers',jsonb_build_array(E'she left work early because of a severe headache.',E'She left work early because of a severe headache'),
  'explanation',E'because of + 명사구'),
jsonb_build_object('number',79,
  'question',E'매일 연습했기 때문에, 그는 무대에서 완벽하게 공연했다. [because절 앞 / practice, perform 사용]',
  'answer',E'Because he practiced every day, he performed perfectly on stage.',
  'similar_answers',jsonb_build_array(E'because he practiced every day, he performed perfectly on stage.',E'Because he practiced every day, he performed perfectly on stage'),
  'explanation',E'Because + 절, practice/perform 사용'),
jsonb_build_object('number',80,
  'question',E'그의 뛰어난 리더십 때문에, 팀 전체가 그를 믿었다. [because/because of 올바른 것 선택, 문장 앞]',
  'answer',E'Because of his outstanding leadership, the whole team trusted him.',
  'similar_answers',jsonb_build_array(E'because of his outstanding leadership, the whole team trusted him.',E'Because of his outstanding leadership, the whole team trusted him'),
  'explanation',E'his outstanding leadership(명사구) → because of')
  );

  a := jsonb_build_array(
    jsonb_build_object('number',1,'answer',E'She stayed inside because it was snowing heavily.'),
    jsonb_build_object('number',2,'answer',E'He missed the bus because he woke up too late.'),
    jsonb_build_object('number',3,'answer',E'They canceled the picnic because the weather was terrible.'),
    jsonb_build_object('number',4,'answer',E'I turned on the heater because the room was freezing cold.'),
    jsonb_build_object('number',5,'answer',E'The soccer match was postponed because a heavy storm was approaching.'),
    jsonb_build_object('number',6,'answer',E'felt dizzy and could not stand up'),
    jsonb_build_object('number',7,'answer',E'kept breaking his promises to his friends'),
    jsonb_build_object('number',8,'answer',E'had too much homework to finish'),
    jsonb_build_object('number',9,'answer',E'She passed the exam because she studied hard.'),
    jsonb_build_object('number',10,'answer',E'My mom couldn''t sleep because the baby was crying.'),
    jsonb_build_object('number',11,'answer',E'He couldn''t buy the jacket because he had no money left.'),
    jsonb_build_object('number',12,'answer',E'She didn''t adopt a cat because she was allergic to cats.'),
    jsonb_build_object('number',13,'answer',E'The school bus arrived late because the roads were icy.'),
    jsonb_build_object('number',14,'answer',E'He took flying lessons every weekend because he wanted to be a pilot.'),
    jsonb_build_object('number',15,'answer',E'She couldn''t call for help because her phone battery died.'),
    jsonb_build_object('number',16,'answer',E'The concert was sold out because thousands of fans wanted to see the band.'),
    jsonb_build_object('number',17,'answer',E'We had to cancel the camping trip because the forest fire warning was at its highest level.'),
    jsonb_build_object('number',18,'answer',E'Many sea animals are losing their homes because ocean temperatures are rising rapidly.'),
    jsonb_build_object('number',19,'answer',E'She reads English novels every night because she wants to improve her vocabulary.'),
    jsonb_build_object('number',20,'answer',E'The stray dog was taken to the shelter because it had been wandering the streets for days.'),
    jsonb_build_object('number',21,'answer',E'because of'),
    jsonb_build_object('number',22,'answer',E'because'),
    jsonb_build_object('number',23,'answer',E'because of'),
    jsonb_build_object('number',24,'answer',E'because'),
    jsonb_build_object('number',25,'answer',E'because of'),
    jsonb_build_object('number',26,'answer',E'because'),
    jsonb_build_object('number',27,'answer',E'because of'),
    jsonb_build_object('number',28,'answer',E'because'),
    jsonb_build_object('number',29,'answer',E'because of'),
    jsonb_build_object('number',30,'answer',E'because'),
    jsonb_build_object('number',31,'answer',E'because of'),
    jsonb_build_object('number',32,'answer',E'because'),
    jsonb_build_object('number',33,'answer',E'but'),
    jsonb_build_object('number',34,'answer',E'so'),
    jsonb_build_object('number',35,'answer',E'because'),
    jsonb_build_object('number',36,'answer',E'so'),
    jsonb_build_object('number',37,'answer',E'but'),
    jsonb_build_object('number',38,'answer',E'because'),
    jsonb_build_object('number',39,'answer',E'and'),
    jsonb_build_object('number',40,'answer',E'so'),
    jsonb_build_object('number',41,'answer',E'because'),
    jsonb_build_object('number',42,'answer',E'but'),
    jsonb_build_object('number',43,'answer',E'so'),
    jsonb_build_object('number',44,'answer',E'because'),
    jsonb_build_object('number',45,'answer',E'and'),
    jsonb_build_object('number',46,'answer',E'but'),
    jsonb_build_object('number',47,'answer',E'so'),
    jsonb_build_object('number',48,'answer',E'because'),
    jsonb_build_object('number',49,'answer',E'and'),
    jsonb_build_object('number',50,'answer',E'but'),
    jsonb_build_object('number',51,'answer',E'so'),
    jsonb_build_object('number',52,'answer',E'because'),
    jsonb_build_object('number',53,'answer',E'because'),
    jsonb_build_object('number',54,'answer',E'Because of'),
    jsonb_build_object('number',55,'answer',E'Because he trained so hard, he won the championship.'),
    jsonb_build_object('number',56,'answer',E'because'),
    jsonb_build_object('number',57,'answer',E'because of'),
    jsonb_build_object('number',58,'answer',E'Because'),
    jsonb_build_object('number',59,'answer',E'because'),
    jsonb_build_object('number',60,'answer',E'because of'),
    jsonb_build_object('number',61,'answer',E'Because'),
    jsonb_build_object('number',62,'answer',E'because'),
    jsonb_build_object('number',63,'answer',E'because of'),
    jsonb_build_object('number',64,'answer',E'because'),
    jsonb_build_object('number',65,'answer',E'Because they studied so hard, they finished the project ahead of schedule.'),
    jsonb_build_object('number',66,'answer',E'We had to wear masks because of the high fine dust levels.'),
    jsonb_build_object('number',67,'answer',E'Because the road was so icy and dangerous, the drivers slowed down.'),
    jsonb_build_object('number',68,'answer',E'She had to repeat the year because she had missed too many classes.'),
    jsonb_build_object('number',69,'answer',E'Because of the power outage, the entire neighborhood was in the dark for hours.'),
    jsonb_build_object('number',70,'answer',E'He could not focus on his work because his neighbors were so noisy.'),
    jsonb_build_object('number',71,'answer',E'Because of rising living costs, many young people cannot afford to rent an apartment.'),
    jsonb_build_object('number',72,'answer',E'The baby woke up because there was a loud noise outside.'),
    jsonb_build_object('number',73,'answer',E'Because the weather was so hot, we went to the swimming pool.'),
    jsonb_build_object('number',74,'answer',E'He was late for the meeting because of traffic.'),
    jsonb_build_object('number',75,'answer',E'She was able to become an interpreter because she was good at English.'),
    jsonb_build_object('number',76,'answer',E'Because of the sudden power outage, the class ended early.'),
    jsonb_build_object('number',77,'answer',E'He couldn''t lock the door because he had forgotten his key at home.'),
    jsonb_build_object('number',78,'answer',E'She left work early because of a severe headache.'),
    jsonb_build_object('number',79,'answer',E'Because he practiced every day, he performed perfectly on stage.'),
    jsonb_build_object('number',80,'answer',E'Because of his outstanding leadership, the whole team trusted him.')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('접속사 because Step 1', '접속사 because', q, a, 'problem', 'interactive');
END $$;
