-- ============================================================
-- 접속사 since/though Step 3 — 서술형 60문항
-- template_topic: 접속사 since/though
-- category: problem, mode: interactive
-- Parts: 1(빈칸 접속사 Q1-10), 2(어색한 부분 고치기 Q11-22),
--        3(두 문장 합치기 Q23-32), 4(동의문 전환 Q33-42),
--        5(단어 배열 Q43-50), 6(조건 영작 Q51-60)
-- ============================================================

DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN

DELETE FROM naesin_templates WHERE title = E'접속사 since/though Step 3';

-- ── q1: Part 1-2 (Q1–Q22) ──
q1 := jsonb_build_array(
    jsonb_build_object('number',1,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\n________ it looked very easy at first, it took a long time to solve.',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array(E'Though',E'Although',E'Even though',E'though',E'although',E'even though'),
  'explanation',E'뒤에 역접(쉬워 보였지만 오래 걸림) 관계이므로 양보 접속사 though/although/even though가 알맞다.'),
    jsonb_build_object('number',2,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\nShe gets lost often ________ she is really poor at directions.',
  'answer',E'since',
  'acceptedAnswers',jsonb_build_array(E'since',E'because',E'Since',E'Because'),
  'explanation',E'길치라서 자주 길을 잃는 인과 관계이므로 since/because가 알맞다.'),
    jsonb_build_object('number',3,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\n________ he was good at painting, he could easily learn how to draw cartoons.',
  'answer',E'Since',
  'acceptedAnswers',jsonb_build_array(E'Since',E'Because',E'since',E'because'),
  'explanation',E'그림을 잘 그려서 만화를 쉽게 배울 수 있었다는 인과 관계이므로 since/because가 알맞다.'),
    jsonb_build_object('number',4,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\n________ he has many friends, he often feels lonely.',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array(E'Though',E'Although',E'Even though',E'though',E'although',E'even though'),
  'explanation',E'친구가 많은데도 외로움을 느끼는 양보 관계이므로 though/although/even though가 알맞다.'),
    jsonb_build_object('number',5,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\nI didn''t watch the soccer game ________ I was so busy.',
  'answer',E'since',
  'acceptedAnswers',jsonb_build_array(E'since',E'because',E'Since',E'Because'),
  'explanation',E'너무 바빠서 축구 경기를 못 본 인과 관계이므로 since/because가 알맞다.'),
    jsonb_build_object('number',6,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\nJustin ate ten pieces of chocolate cake ________ he was on a diet.',
  'answer',E'though',
  'acceptedAnswers',jsonb_build_array(E'though',E'although',E'even though',E'Though',E'Although',E'Even though'),
  'explanation',E'다이어트 중인데 케이크를 10조각이나 먹은 양보 관계이므로 though/although/even though가 알맞다.'),
    jsonb_build_object('number',7,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\nThey often die from eating plastic ________ their bodies cannot break it down.',
  'answer',E'since',
  'acceptedAnswers',jsonb_build_array(E'since',E'because',E'Since',E'Because'),
  'explanation',E'몸이 플라스틱을 분해하지 못해서 죽는 인과 관계이므로 since/because가 알맞다.'),
    jsonb_build_object('number',8,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\n________ it is very difficult, I will find some way to solve it.',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array(E'Though',E'Although',E'Even though',E'though',E'although',E'even though'),
  'explanation',E'매우 어렵지만 해결 방법을 찾겠다는 양보 관계이므로 though/although/even though가 알맞다.'),
    jsonb_build_object('number',9,'type','short_answer',
  'question',E'빈칸에 알맞은 접속사를 <보기>에서 골라 쓰시오.\n\n<보기> though / since / although / even though / because\n\nA: Did it rain a lot?\nB: Yes, it did. ________ it rained a lot, I arrived at the festival on time.',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array(E'Though',E'Although',E'Even though',E'though',E'although',E'even though'),
  'explanation',E'비가 많이 왔지만 제시간에 도착한 양보 관계이므로 though/although/even though가 알맞다.'),
    jsonb_build_object('number',10,'type','short_answer',
  'question',E'다음 빈칸 (A), (B)에 알맞은 접속사를 각각 쓰시오.\n\n<보기> though / since / although / even though / because\n\n(A) ________ the shoes were too expensive, Sora couldn''t buy them.\n(B) Minho got healthier ________ he exercised every day.',
  'answer',E'Since, since',
  'acceptedAnswers',jsonb_build_array(E'Since, since',E'Since, because',E'Because, since',E'Because, because',E'Since / since',E'Since / because',E'Because / since',E'Because / because'),
  'explanation',E'(A) 신발이 너무 비싸서 못 산 인과 관계 → since/because\n(B) 매일 운동해서 건강해진 인과 관계 → since/because'),
    jsonb_build_object('number',11,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nWe enjoyed the day at the park though the bad weather.',
  'answer',E'though → despite',
  'acceptedAnswers',jsonb_build_array(E'though → despite',E'though → in spite of',E'though->despite',E'though->in spite of',E'despite',E'in spite of'),
  'explanation',E'though 뒤에는 절(주어+동사)이 와야 하지만 the bad weather는 명사구 → despite/in spite of 사용'),
    jsonb_build_object('number',12,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nDespite the playground was very small, it looked large to the little boy.',
  'answer',E'Despite → Although',
  'acceptedAnswers',jsonb_build_array(E'Despite → Although',E'Despite → Though',E'Despite → Even though',E'Despite->Although',E'Despite->Though',E'Although',E'Though',E'Even though'),
  'explanation',E'despite 뒤에는 명사구가 와야 하지만 the playground was very small은 절 → though/although 사용'),
    jsonb_build_object('number',13,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nAlthough he studied hard, but he failed the exam.',
  'answer',E'but 삭제',
  'acceptedAnswers',jsonb_build_array(E'but 삭제',E'remove but',E'delete but',E'but을 삭제'),
  'explanation',E'although와 but은 중복 사용 불가. 양보 접속사(although)가 있으면 주절에 but 불필요'),
    jsonb_build_object('number',14,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThough began last, he finished first.',
  'answer',E'Though began → Though he began',
  'acceptedAnswers',jsonb_build_array(E'Though began → Though he began',E'Though he began',E'Though began->Though he began'),
  'explanation',E'though절에도 주어+동사가 필요. he 누락'),
    jsonb_build_object('number',15,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nAlthough our efforts, we failed to win the prize.',
  'answer',E'Although → Despite',
  'acceptedAnswers',jsonb_build_array(E'Although → Despite',E'Although → In spite of',E'Although->Despite',E'Although->In spite of',E'Despite',E'In spite of'),
  'explanation',E'our efforts는 명사구 → 전치사 despite/in spite of 사용'),
    jsonb_build_object('number',16,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nI couldn''t sleep although I very tired.',
  'answer',E'I very tired → I was very tired',
  'acceptedAnswers',jsonb_build_array(E'I very tired → I was very tired',E'I was very tired',E'I very tired->I was very tired'),
  'explanation',E'be동사(was) 누락. although절에도 완전한 주어+동사 필요'),
    jsonb_build_object('number',17,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nAlthough our house is small, but it''s big enough for our needs.',
  'answer',E'but 삭제',
  'acceptedAnswers',jsonb_build_array(E'but 삭제',E'remove but',E'delete but',E'but을 삭제'),
  'explanation',E'although와 but 중복 사용 불가'),
    jsonb_build_object('number',18,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nEven though the traffic, I arrived on time.',
  'answer',E'Even though → Despite',
  'acceptedAnswers',jsonb_build_array(E'Even though → Despite',E'Even though → In spite of',E'Even though->Despite',E'Even though->In spite of',E'Despite',E'In spite of'),
  'explanation',E'the traffic은 명사구 → 전치사 despite/in spite of 사용'),
    jsonb_build_object('number',19,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nDespite of the storm, the airplane landed safely.',
  'answer',E'Despite of → Despite',
  'acceptedAnswers',jsonb_build_array(E'Despite of → Despite',E'Despite',E'Despite of->Despite'),
  'explanation',E'despite 뒤에 of 불필요. "in spite of"와 혼동 주의'),
    jsonb_build_object('number',20,'type','short_answer',
  'question',E'어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nShe got up late since she was on time for school.',
  'answer',E'since → though',
  'acceptedAnswers',jsonb_build_array(E'since → though',E'since → although',E'since → even though',E'since->though',E'since->although',E'though',E'although',E'even though'),
  'explanation',E'늦게 일어났는데 제시간에 온 것은 인과가 아닌 양보 관계 → though/although'),
    jsonb_build_object('number',21,'type','short_answer',
  'question',E'다음 글에서 어법상 어색한 두 군데를 찾아 바르게 고쳐 쓰시오.\n\nSince she missed the bus, but she was late for school. Her teacher was angry because she was 30 minutes late. Although the danger signs, we still swam in that area. We should have been more careful.',
  'answer',E'but 삭제, Although → Despite',
  'acceptedAnswers',jsonb_build_array(E'but 삭제, Although → Despite',E'but 삭제, Although → In spite of',E'but 삭제 / Although → Despite',E'but 삭제 / Although → In spite of'),
  'explanation',E'(1) since와 but 중복 → but 삭제 (Since she missed the bus, she was late for school.) / (2) the danger signs는 명사구 → Despite/In spite of'),
    jsonb_build_object('number',22,'type','short_answer',
  'question',E'다음 글에서 어법상 어색한 두 군데를 찾아 바르게 고쳐 쓰시오.\n\nThough began last in the race, Tom finished first and won the gold medal. Everyone was surprised. Despite he was tired after the race, he smiled for the cameras and thanked his coach.',
  'answer',E'Though began → Though he began, Despite he was → Although he was',
  'acceptedAnswers',jsonb_build_array(E'Though began → Though he began, Despite he was → Although he was',E'Though began → Though he began, Despite he was → Though he was',E'Though he began, Although he was',E'Though he began / Although he was',E'Though he began, Though he was'),
  'explanation',E'(1) though절에 주어(he) 누락 / (2) despite 뒤에 절이 옴 → though/although로 교체')
);

-- ── q2: Part 3-4 (Q23–Q42) ──
q2 := jsonb_build_array(
jsonb_build_object('number',23,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• It was already April.\n• The weather was rather cold.',
  'type','short_answer',
  'answer',E'Though it was already April, the weather was rather cold.',
  'acceptedAnswers',jsonb_build_array('Though it was already April, the weather was rather cold.','Though it was already April, the weather was rather cold','Although it was already April, the weather was rather cold.','Although it was already April, the weather was rather cold'),
  'explanation',E'4월인데 날씨가 추운 것은 양보 관계 → though/although 사용'),
jsonb_build_object('number',24,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• She could finish the work early.\n• She worked very hard.',
  'type','short_answer',
  'answer',E'Since she worked very hard, she could finish the work early.',
  'acceptedAnswers',jsonb_build_array('Since she worked very hard, she could finish the work early.','Since she worked very hard, she could finish the work early','Because she worked very hard, she could finish the work early.','Because she worked very hard, she could finish the work early'),
  'explanation',E'열심히 일해서 일찍 끝낼 수 있었다 → 이유/원인 관계 → since/because 사용'),
jsonb_build_object('number',25,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• I couldn''t go out.\n• I caught a bad cold.',
  'type','short_answer',
  'answer',E'Since I caught a bad cold, I couldn''t go out.',
  'acceptedAnswers',jsonb_build_array('Since I caught a bad cold, I couldn''t go out.','Since I caught a bad cold, I couldn''t go out','Because I caught a bad cold, I couldn''t go out.','Because I caught a bad cold, I couldn''t go out'),
  'explanation',E'심한 감기에 걸려서 외출할 수 없었다 → 이유/원인 관계 → since/because 사용'),
jsonb_build_object('number',26,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• He is poor.\n• He always helps other people.',
  'type','short_answer',
  'answer',E'Though he is poor, he always helps other people.',
  'acceptedAnswers',jsonb_build_array('Though he is poor, he always helps other people.','Though he is poor, he always helps other people','Although he is poor, he always helps other people.','Although he is poor, he always helps other people'),
  'explanation',E'가난하지만 항상 다른 사람을 돕는다 → 양보 관계 → though/although 사용'),
jsonb_build_object('number',27,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• They are in the same class.\n• They hardly talk to each other.',
  'type','short_answer',
  'answer',E'Though they are in the same class, they hardly talk to each other.',
  'acceptedAnswers',jsonb_build_array('Though they are in the same class, they hardly talk to each other.','Though they are in the same class, they hardly talk to each other','Although they are in the same class, they hardly talk to each other.','Although they are in the same class, they hardly talk to each other'),
  'explanation',E'같은 반인데 거의 대화하지 않는다 → 양보 관계 → though/although 사용'),
jsonb_build_object('number',28,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• Pinocchio lied.\n• His nose grew longer.',
  'type','short_answer',
  'answer',E'Since Pinocchio lied, his nose grew longer.',
  'acceptedAnswers',jsonb_build_array('Since Pinocchio lied, his nose grew longer.','Since Pinocchio lied, his nose grew longer','Because Pinocchio lied, his nose grew longer.','Because Pinocchio lied, his nose grew longer'),
  'explanation',E'피노키오가 거짓말을 해서 코가 길어졌다 → 이유/원인 관계 → since/because 사용'),
jsonb_build_object('number',29,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• Ms. Wilson enjoys eating kimchi very much.\n• She is not Korean.',
  'type','short_answer',
  'answer',E'Though Ms. Wilson is not Korean, she enjoys eating kimchi very much.',
  'acceptedAnswers',jsonb_build_array('Though Ms. Wilson is not Korean, she enjoys eating kimchi very much.','Though Ms. Wilson is not Korean, she enjoys eating kimchi very much','Although Ms. Wilson is not Korean, she enjoys eating kimchi very much.','Although Ms. Wilson is not Korean, she enjoys eating kimchi very much','Though she is not Korean, Ms. Wilson enjoys eating kimchi very much.','Though she is not Korean, Ms. Wilson enjoys eating kimchi very much','Although she is not Korean, Ms. Wilson enjoys eating kimchi very much.','Although she is not Korean, Ms. Wilson enjoys eating kimchi very much'),
  'explanation',E'한국인이 아닌데 김치를 즐겨 먹는다 → 양보 관계 → though/although 사용'),
jsonb_build_object('number',30,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• He failed several times.\n• He didn''t give up on his dream.',
  'type','short_answer',
  'answer',E'Though he failed several times, he didn''t give up on his dream.',
  'acceptedAnswers',jsonb_build_array('Though he failed several times, he didn''t give up on his dream.','Though he failed several times, he didn''t give up on his dream','Although he failed several times, he didn''t give up on his dream.','Although he failed several times, he didn''t give up on his dream'),
  'explanation',E'여러 번 실패했지만 꿈을 포기하지 않았다 → 양보 관계 → though/although 사용'),
jsonb_build_object('number',31,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• My parents were not home during the weekend.\n• I had to take care of my little brother.',
  'type','short_answer',
  'answer',E'Since my parents were not home during the weekend, I had to take care of my little brother.',
  'acceptedAnswers',jsonb_build_array('Since my parents were not home during the weekend, I had to take care of my little brother.','Since my parents were not home during the weekend, I had to take care of my little brother','Because my parents were not home during the weekend, I had to take care of my little brother.','Because my parents were not home during the weekend, I had to take care of my little brother'),
  'explanation',E'주말에 부모님이 집에 안 계셔서 동생을 돌봐야 했다 → 이유/원인 관계 → since/because 사용'),
jsonb_build_object('number',32,
  'question',E'주어진 두 문장을 since 또는 though를 사용하여 한 문장으로 쓰시오.\n\n• I could still see children playing in the street.\n• It was raining outside.',
  'type','short_answer',
  'answer',E'Though it was raining outside, I could still see children playing in the street.',
  'acceptedAnswers',jsonb_build_array('Though it was raining outside, I could still see children playing in the street.','Though it was raining outside, I could still see children playing in the street','Although it was raining outside, I could still see children playing in the street.','Although it was raining outside, I could still see children playing in the street'),
  'explanation',E'비가 오는데도 아이들이 거리에서 노는 것을 볼 수 있었다 → 양보 관계 → though/although 사용'),
jsonb_build_object('number',33,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nAlthough it was cold, he stood outside all day long.\n→ ________ the cold weather, he stood outside all day long.',
  'type','short_answer',
  'answer',E'Despite',
  'acceptedAnswers',jsonb_build_array('Despite','In spite of','despite','in spite of'),
  'explanation',E'Although + 절 = Despite/In spite of + 명사구. 접속사를 전치사(구)로 전환'),
jsonb_build_object('number',34,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nIn spite of the rain, we played soccer.\n→ ________ it rained, we played soccer.',
  'type','short_answer',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array('Though','Although','Even though','though','although','even though'),
  'explanation',E'In spite of + 명사 = Though/Although/Even though + 절. 전치사(구)를 접속사로 전환'),
jsonb_build_object('number',35,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nAlthough he studied hard, he failed to pass the final exam.\n→ In spite of ________, he couldn''t pass the final exam.',
  'type','short_answer',
  'answer',E'his hard study',
  'acceptedAnswers',jsonb_build_array('his hard study','studying hard','his hard studying','his effort'),
  'explanation',E'Although + 주어 + 동사 → In spite of + 명사구/동명사. "he studied hard"를 명사구로 전환'),
jsonb_build_object('number',36,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nHe wasn''t interested in movies, but he joined the school club.\n→ ________ he wasn''t interested in movies, he joined the school club.',
  'type','short_answer',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array('Though','Although','Even though','though','although','even though'),
  'explanation',E'but(역접) = though/although/even though(양보 접속사)로 전환'),
jsonb_build_object('number',37,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nThough she has four sons, she wants another boy.\n→ ________ having four sons, she wants another boy.',
  'type','short_answer',
  'answer',E'Despite',
  'acceptedAnswers',jsonb_build_array('Despite','In spite of','despite','in spite of'),
  'explanation',E'Though + 절 = Despite/In spite of + 동명사구. 접속사를 전치사(구)로 전환'),
jsonb_build_object('number',38,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nWe had to walk home. Therefore, we had no money.\n→ We had to walk home ________ we had no money.',
  'type','short_answer',
  'answer',E'since',
  'acceptedAnswers',jsonb_build_array('since','because','Since','Because'),
  'explanation',E'Therefore(그러므로, 결과)를 이유 접속사 since/because로 전환. 돈이 없어서 걸어가야 했다'),
jsonb_build_object('number',39,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nHe ate a big lunch, but he is still hungry.\n→ He is still hungry ________ he ate a big lunch.',
  'type','short_answer',
  'answer',E'although',
  'acceptedAnswers',jsonb_build_array('although','though','even though','Although','Though','Even though'),
  'explanation',E'but(역접) = although/though/even though(양보 접속사)로 전환'),
jsonb_build_object('number',40,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nI was very tired. However, I finished all of my homework.\n→ ________ I was very tired, I finished all of my homework.',
  'type','short_answer',
  'answer',E'Though',
  'acceptedAnswers',jsonb_build_array('Though','Although','Even though','though','although','even though'),
  'explanation',E'However(그러나, 역접 부사) = Though/Although/Even though(양보 접속사)로 전환'),
jsonb_build_object('number',41,
  'question',E'두 문장의 의미가 같도록 빈칸에 알맞은 말을 쓰시오.\n\nAlthough my grades were low, I lived a successful life.\n→ ________ ________ my low grades, I lived a successful life.',
  'type','short_answer',
  'answer',E'In spite of',
  'acceptedAnswers',jsonb_build_array('In spite of','Despite','in spite of','despite'),
  'explanation',E'Although + 절 = In spite of/Despite + 명사구. 빈칸이 두 개이므로 In spite of가 가장 적절'),
jsonb_build_object('number',42,
  'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 완성하시오.\n\n(1) Though he was poor, he always helped others.\n→ ________, he always helped others.\n\n(2) Since the book was written in easy French, I could understand it.\n→ ________, I could understand it.',
  'type','short_answer',
  'answer',E'Despite his poverty, The book was written in easy French, so',
  'acceptedAnswers',jsonb_build_array('Despite his poverty, The book was written in easy French, so','In spite of his poverty, The book was written in easy French, so','Despite being poor, The book was written in easy French, so','In spite of being poor, The book was written in easy French, so','Despite his poverty, Because the book was written in easy French','In spite of his poverty, Because the book was written in easy French'),
  'explanation',E'(1) Though + 절 → Despite/In spite of + 명사구: "Though he was poor" → "Despite his poverty"\n(2) Since(이유) + 절 → 결과 접속 전환: "Since ~" → "~, so" 또는 "Because ~"')
);

-- ── q3: Part 5-6 (Q43–Q60) ──
q3 := jsonb_build_array(
jsonb_build_object('number',43,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n비가 내리고 있었지만, 우리는 운동장에서 축구를 했다.\n\n(it / played / though / the / we / soccer / on / was / raining / playground)',
  'type','short_answer',
  'answer',E'Though it was raining, we played soccer on the playground.',
  'acceptedAnswers',jsonb_build_array('Though it was raining, we played soccer on the playground.','Though it was raining, we played soccer on the playground'),
  'explanation',E'though + 주어 + 동사 → 양보 부사절. Though it was raining이 부사절, we played~가 주절'),
jsonb_build_object('number',44,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n그녀는 매우 바쁘지만 매일 일기를 쓴다.\n\n(very / every / she / keeps / busy / a / though / is / diary / she / day)',
  'type','short_answer',
  'answer',E'Though she is very busy, she keeps a diary every day.',
  'acceptedAnswers',jsonb_build_array('Though she is very busy, she keeps a diary every day.','Though she is very busy, she keeps a diary every day'),
  'explanation',E'though + 주어 + 동사 → 양보 부사절. 바쁘지만(양보) 매일 일기를 쓴다(주절)'),
jsonb_build_object('number',45,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n우리는 돈이 없기 때문에, 그 차를 살 수 없다.\n\n(no / since / we / buy / car / can''t / the / have / money / we)',
  'type','short_answer',
  'answer',E'Since we have no money, we can''t buy the car.',
  'acceptedAnswers',jsonb_build_array('Since we have no money, we can''t buy the car.','Since we have no money, we can''t buy the car'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 돈이 없어서(이유) 차를 살 수 없다(결과)'),
jsonb_build_object('number',46,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n비록 서비스는 느렸지만, 웨이터들은 친절했다.\n\n(kind / were / the waiters / the service / slow / was / although)',
  'type','short_answer',
  'answer',E'Although the service was slow, the waiters were kind.',
  'acceptedAnswers',jsonb_build_array('Although the service was slow, the waiters were kind.','Although the service was slow, the waiters were kind'),
  'explanation',E'although + 주어 + 동사 → 양보 부사절. 서비스가 느렸지만(양보) 웨이터들은 친절했다(주절)'),
jsonb_build_object('number',47,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n내 생일이었기 때문에, 난 많은 선물들을 받았다.\n\n(my / received / I / since / it / a lot of / was / birthday / gifts)',
  'type','short_answer',
  'answer',E'Since it was my birthday, I received a lot of gifts.',
  'acceptedAnswers',jsonb_build_array('Since it was my birthday, I received a lot of gifts.','Since it was my birthday, I received a lot of gifts'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 생일이었기 때문에(이유) 선물을 많이 받았다(결과)'),
jsonb_build_object('number',48,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n비록 그 집은 붕괴되었지만, 아무도 다치지 않았다.\n\n(house / the / hurt / was / even / though / one / was / no / destroyed)',
  'type','short_answer',
  'answer',E'Even though the house was destroyed, no one was hurt.',
  'acceptedAnswers',jsonb_build_array('Even though the house was destroyed, no one was hurt.','Even though the house was destroyed, no one was hurt'),
  'explanation',E'even though + 주어 + 동사 → 강한 양보 부사절. 집이 붕괴되었지만(양보) 아무도 다치지 않았다(주절)'),
jsonb_build_object('number',49,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n그는 그림 그리기를 잘했으므로 만화 그리는 법을 쉽게 배울 수 있었다.\n\n(cartoons / since / could / at / was / draw / how / to / good / easily / he / painting / learn / he)',
  'type','short_answer',
  'answer',E'Since he was good at painting, he could easily learn how to draw cartoons.',
  'acceptedAnswers',jsonb_build_array('Since he was good at painting, he could easily learn how to draw cartoons.','Since he was good at painting, he could easily learn how to draw cartoons'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 그림을 잘 그려서(이유) 만화를 쉽게 배울 수 있었다(결과). be good at + 동명사'),
jsonb_build_object('number',50,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오.\n\n부모님이 주말 동안 집에 안 계셨기 때문에, 나는 남동생을 돌봐야만 했다.\n\n(home / little / my / were / since / the / I / my / brother / take / parents / during / to / of / weekend / not / had / care)',
  'type','short_answer',
  'answer',E'Since my parents were not home during the weekend, I had to take care of my little brother.',
  'acceptedAnswers',jsonb_build_array('Since my parents were not home during the weekend, I had to take care of my little brother.','Since my parents were not home during the weekend, I had to take care of my little brother'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 부모님이 안 계셔서(이유) 동생을 돌봐야 했다(결과). take care of = ~을 돌보다'),
jsonb_build_object('number',51,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n비가 오고 있었기 때문에, 우리는 축구를 할 수 없었다.\n\n【조건】 since, play soccer 사용 / 10단어',
  'type','short_answer',
  'answer',E'Since it was raining, we couldn''t play soccer.',
  'acceptedAnswers',jsonb_build_array('Since it was raining, we couldn''t play soccer.','Since it was raining, we couldn''t play soccer','Since it was raining, we could not play soccer.','Since it was raining, we could not play soccer'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 비가 오고 있었으므로(이유) 축구를 할 수 없었다(결과). couldn''t = could not'),
jsonb_build_object('number',52,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n비록 그는 나이가 많지만, 매우 활동적이다.\n\n【조건】 although, active 사용 / 8단어',
  'type','short_answer',
  'answer',E'Although he is old, he is very active.',
  'acceptedAnswers',jsonb_build_array('Although he is old, he is very active.','Although he is old, he is very active'),
  'explanation',E'although + 주어 + 동사 → 양보 부사절. 나이가 많지만(양보) 활동적이다(주절)'),
jsonb_build_object('number',53,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n그녀는 숙제가 있었기 때문에 늦게까지 자지 않고 있었다.\n\n【조건】 since, stay up late 사용 / 10단어',
  'type','short_answer',
  'answer',E'Since she had homework to do, she stayed up late.',
  'acceptedAnswers',jsonb_build_array('Since she had homework to do, she stayed up late.','Since she had homework to do, she stayed up late'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 숙제가 있어서(이유) 늦게까지 깨어 있었다(결과). stay up late = 늦게까지 자지 않다'),
jsonb_build_object('number',54,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n비록 그 집은 작지만, 우리 가족에게는 충분히 크다.\n\n【조건】 although, enough 사용 / 11단어',
  'type','short_answer',
  'answer',E'Although our house is small, it is big enough for our family.',
  'acceptedAnswers',jsonb_build_array('Although our house is small, it is big enough for our family.','Although our house is small, it is big enough for our family','Although the house is small, it is big enough for our family.','Although the house is small, it is big enough for our family'),
  'explanation',E'although + 주어 + 동사 → 양보 부사절. 집이 작지만(양보) 가족에게 충분히 크다(주절). enough는 형용사 뒤에 위치'),
jsonb_build_object('number',55,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n나는 열심히 노력했지만 내 성적은 나아지지 않았다.\n\n【조건】 though, grades, improve 사용 / 11단어',
  'type','short_answer',
  'answer',E'Though I tried hard, my grades didn''t improve.',
  'acceptedAnswers',jsonb_build_array('Though I tried hard, my grades didn''t improve.','Though I tried hard, my grades didn''t improve','Though I tried hard, my grades did not improve.','Though I tried hard, my grades did not improve'),
  'explanation',E'though + 주어 + 동사 → 양보 부사절. 열심히 노력했지만(양보) 성적이 나아지지 않았다(주절)'),
jsonb_build_object('number',56,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n그는 지도가 없었음에도 불구하고 그곳에 쉽게 도착했다.\n\n【조건】 though, map, get there 사용 / 12단어',
  'type','short_answer',
  'answer',E'Though he didn''t have a map, he got there easily.',
  'acceptedAnswers',jsonb_build_array('Though he didn''t have a map, he got there easily.','Though he didn''t have a map, he got there easily','Though he did not have a map, he got there easily.','Though he did not have a map, he got there easily'),
  'explanation',E'though + 주어 + 동사 → 양보 부사절. 지도가 없었지만(양보) 쉽게 도착했다(주절). get there = 그곳에 도착하다'),
jsonb_build_object('number',57,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n비가 내리는데도, 많은 사람들이 밖에서 놀았다.\n\n【조건】 although, rain, people, outside 사용 / 10단어',
  'type','short_answer',
  'answer',E'Although it was raining, many people played outside.',
  'acceptedAnswers',jsonb_build_array('Although it was raining, many people played outside.','Although it was raining, many people played outside'),
  'explanation',E'although + 주어 + 동사 → 양보 부사절. 비가 내리는데도(양보) 많은 사람들이 밖에서 놀았다(주절)'),
jsonb_build_object('number',58,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n나는 쉽게 살이 찌기 때문에 항상 다이어트 중이다.\n\n【조건】 since, gain weight, on a diet 사용 / 11단어',
  'type','short_answer',
  'answer',E'I am always on a diet since I gain weight easily.',
  'acceptedAnswers',jsonb_build_array('I am always on a diet since I gain weight easily.','I am always on a diet since I gain weight easily','Since I gain weight easily, I am always on a diet.','Since I gain weight easily, I am always on a diet'),
  'explanation',E'since + 주어 + 동사 → 이유 부사절. 쉽게 살이 찌기 때문에(이유) 항상 다이어트 중이다(결과). gain weight = 살이 찌다, on a diet = 다이어트 중'),
jsonb_build_object('number',59,
  'question',E'주어진 조건에 맞게 영작하시오.\n\n비록 그는 50년도 더 전에 세상을 떠났지만, 그의 정신은 우리와 함께 영원히 남아 있을 것이다.\n\n【조건】 though, pass away, spirit, remain 사용 / 17단어',
  'type','short_answer',
  'answer',E'Though he passed away more than 50 years ago, his spirit will remain with us forever.',
  'acceptedAnswers',jsonb_build_array('Though he passed away more than 50 years ago, his spirit will remain with us forever.','Though he passed away more than 50 years ago, his spirit will remain with us forever'),
  'explanation',E'though + 주어 + 동사 → 양보 부사절. 세상을 떠났지만(양보) 정신은 영원히 남을 것이다(주절). pass away = 세상을 떠나다, remain = 남아 있다'),
jsonb_build_object('number',60,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n(1) 그녀는 피곤했음에도 불구하고, 열심히 공부하려고 노력했다.\n(2) 그녀는 부유함에도 불구하고, 거의 돈을 쓰지 않는다.\n\n【조건】 though 사용 / (1) tired, try 포함 / (2) rich, spend 포함',
  'type','short_answer',
  'answer',E'Though she was tired, she tried to study hard. / Though she is rich, she hardly spends any money.',
  'acceptedAnswers',jsonb_build_array(
    'Though she was tired, she tried to study hard. / Though she is rich, she hardly spends any money.',
    'Though she was tired, she tried to study hard. Though she is rich, she hardly spends any money.',
    'Though she was tired, she tried to study hard., Though she is rich, she hardly spends any money.'
  ),
  'explanation',E'(1) 양보(피곤했지만 노력) → Though she was tired / (2) 양보(부유하지만 안 씀) → Though she is rich. hardly = 거의 ~않다')
);

a := jsonb_build_array();

INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
VALUES (
  E'접속사 since/though Step 3',
  E'접속사 since/though',
  q1 || q2 || q3,
  a,
  'problem',
  'interactive'
);

END $$;
