DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '사역동사 Step 1';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1: 보어 형태 선택 (Q1~Q27) — 2지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
  'question',E'[Part 1] 알맞은 형태를 고르시오.\n\nThis great joke made me ______.',
  'options',jsonb_build_array('laugh','to laugh'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',2,
  'question',E'Emma got her sister ______ some flowers.',
  'options',jsonb_build_array('buy','to buy'),
  'answer','2',
  'explanation',E'get + 목적어 + to부정사'),
jsonb_build_object('number',3,
  'question',E'The teacher always makes us ______ quiet.',
  'options',jsonb_build_array('be','been'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',4,
  'question',E'Yesterday, mom let me ______ later.',
  'options',jsonb_build_array('stay up','stayed up'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),
jsonb_build_object('number',5,
  'question',E'I had my brother ______ there instead of me.',
  'options',jsonb_build_array('go','to go'),
  'answer','1',
  'explanation',E'have + 목적어 + 동사원형'),
jsonb_build_object('number',6,
  'question',E'Let me ______ you fix the computer.',
  'options',jsonb_build_array('help','to help'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),
jsonb_build_object('number',7,
  'question',E'He helped her ______ a lot of money.',
  'options',jsonb_build_array('raising','to raise'),
  'answer','2',
  'explanation',E'help + 목적어 + to부정사 (raising은 help의 목적격 보어로 불가)'),
jsonb_build_object('number',8,
  'question',E'My mom had me ______ the dishes.',
  'options',jsonb_build_array('do','did'),
  'answer','1',
  'explanation',E'have + 목적어 + 동사원형'),
jsonb_build_object('number',9,
  'question',E'His new clothes make him ______ better.',
  'options',jsonb_build_array('look','looks'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',10,
  'question',E'Eating too much food can make you ______.',
  'options',jsonb_build_array('sick','are sick'),
  'answer','1',
  'explanation',E'make + 목적어 + 형용사 (목적격 보어)'),
jsonb_build_object('number',11,
  'question',E'I had my sister ______ my room.',
  'options',jsonb_build_array('clean','to clean'),
  'answer','1',
  'explanation',E'have + 목적어 + 동사원형'),
jsonb_build_object('number',12,
  'question',E'Mina helped his brother ______ his homework.',
  'options',jsonb_build_array('do','doing'),
  'answer','1',
  'explanation',E'help + 목적어 + 동사원형'),
jsonb_build_object('number',13,
  'question',E'I can''t make her ______ crying.',
  'options',jsonb_build_array('stop','stopped'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',14,
  'question',E'My sister made me ______ out the trash.',
  'options',jsonb_build_array('take','to take'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',15,
  'question',E'I let her ______ my guitar sometimes.',
  'options',jsonb_build_array('play','playing'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),
jsonb_build_object('number',16,
  'question',E'Mom had me ______ home early.',
  'options',jsonb_build_array('come','to come'),
  'answer','1',
  'explanation',E'have + 목적어 + 동사원형'),
jsonb_build_object('number',17,
  'question',E'She let the bird ______ free.',
  'options',jsonb_build_array('go','going'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),
jsonb_build_object('number',18,
  'question',E'He had his hair ______ by his sister.',
  'options',jsonb_build_array('cut','to cut'),
  'answer','1',
  'explanation',E'have + 목적어 + 과거분사 (수동: 머리카락이 잘리는 것)'),
jsonb_build_object('number',19,
  'question',E'I cannot have you ______ such a thing.',
  'options',jsonb_build_array('do','doing'),
  'answer','1',
  'explanation',E'have + 목적어 + 동사원형'),
jsonb_build_object('number',20,
  'question',E'He got his brother ______ his computer.',
  'options',jsonb_build_array('fix','to fix'),
  'answer','2',
  'explanation',E'get + 목적어 + to부정사'),
jsonb_build_object('number',21,
  'question',E'I helped her ______ her cases.',
  'options',jsonb_build_array('to carry','carrying'),
  'answer','1',
  'explanation',E'help + 목적어 + to부정사'),
jsonb_build_object('number',22,
  'question',E'Will your parents let you ______ to the party?',
  'options',jsonb_build_array('go','going'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),
jsonb_build_object('number',23,
  'question',E'She got her husband ______ the pictures.',
  'options',jsonb_build_array('to take','take'),
  'answer','1',
  'explanation',E'get + 목적어 + to부정사'),
jsonb_build_object('number',24,
  'question',E'The wind made the picture ______ on the floor.',
  'options',jsonb_build_array('fall','to fall'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',25,
  'question',E'Reading before bed helps me ______.',
  'options',jsonb_build_array('to relax','relaxing'),
  'answer','1',
  'explanation',E'help + 목적어 + to부정사'),
jsonb_build_object('number',26,
  'question',E'Mr. Park made us ______ a report.',
  'options',jsonb_build_array('write','to write'),
  'answer','1',
  'explanation',E'make + 목적어 + 동사원형'),
jsonb_build_object('number',27,
  'question',E'He will let me ______ early.',
  'options',jsonb_build_array('leave','to leave'),
  'answer','1',
  'explanation',E'let + 목적어 + 동사원형'),

    -- ═══════════════════════════════════════════
    -- Part 2: 문장 전환 + 영작 (Q28~Q48) — 서술형
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',28,
  'question',E'[Part 2] 주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe taxi driver collected us. (have)',
  'answer',E'I had the taxi driver collect us.',
  'similar_answers',jsonb_build_array(E'I had the taxi driver collect us',E'I had a taxi driver collect us.',E'I had a taxi driver collect us'),
  'explanation',E'have + 목적어 + 동사원형: had the taxi driver collect'),
jsonb_build_object('number',29,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nJohn arrived on time. (get)',
  'answer',E'I got John to arrive on time.',
  'similar_answers',jsonb_build_array(E'I got John to arrive on time'),
  'explanation',E'get + 목적어 + to부정사: got John to arrive'),
jsonb_build_object('number',30,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe mechanic fixed the brakes. (have)',
  'answer',E'I had the mechanic fix the brakes.',
  'similar_answers',jsonb_build_array(E'I had the mechanic fix the brakes',E'I had a mechanic fix the brakes.',E'I had a mechanic fix the brakes'),
  'explanation',E'have + 목적어 + 동사원형: had the mechanic fix'),
jsonb_build_object('number',31,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nMy husband looked after our children. (get)',
  'answer',E'I got my husband to look after our children.',
  'similar_answers',jsonb_build_array(E'I got my husband to look after our children'),
  'explanation',E'get + 목적어 + to부정사: got my husband to look after'),
jsonb_build_object('number',32,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe waiter brought some water. (have)',
  'answer',E'I had the waiter bring some water.',
  'similar_answers',jsonb_build_array(E'I had the waiter bring some water'),
  'explanation',E'have + 목적어 + 동사원형: had the waiter bring'),
jsonb_build_object('number',33,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe nurse took my temperature. (have)',
  'answer',E'I had the nurse take my temperature.',
  'similar_answers',jsonb_build_array(E'I had the nurse take my temperature',E'I had a nurse take my temperature.',E'I had a nurse take my temperature'),
  'explanation',E'have + 목적어 + 동사원형: had the nurse take'),
jsonb_build_object('number',34,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe students stopped sleeping in class. (get)',
  'answer',E'I got the students to stop sleeping in class.',
  'similar_answers',jsonb_build_array(E'I got the students to stop sleeping in class'),
  'explanation',E'get + 목적어 + to부정사: got the students to stop'),
jsonb_build_object('number',35,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe dentist cleaned my teeth. (have)',
  'answer',E'I had the dentist clean my teeth.',
  'similar_answers',jsonb_build_array(E'I had the dentist clean my teeth',E'I had a dentist clean my teeth.',E'I had a dentist clean my teeth'),
  'explanation',E'have + 목적어 + 동사원형: had the dentist clean'),
jsonb_build_object('number',36,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nMy friend took her car. (get)',
  'answer',E'I got my friend to take her car.',
  'similar_answers',jsonb_build_array(E'I got my friend to take her car'),
  'explanation',E'get + 목적어 + to부정사: got my friend to take'),
jsonb_build_object('number',37,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThey washed the windows. (have)',
  'answer',E'I had them wash the windows.',
  'similar_answers',jsonb_build_array(E'I had them wash the windows'),
  'explanation',E'have + 목적어 + 동사원형: had them wash'),
jsonb_build_object('number',38,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe child ate her vegetables. (get)',
  'answer',E'I got the child to eat her vegetables.',
  'similar_answers',jsonb_build_array(E'I got the child to eat her vegetables'),
  'explanation',E'get + 목적어 + to부정사: got the child to eat'),
jsonb_build_object('number',39,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe teacher checked my writing. (get)',
  'answer',E'I got the teacher to check my writing.',
  'similar_answers',jsonb_build_array(E'I got the teacher to check my writing'),
  'explanation',E'get + 목적어 + to부정사: got the teacher to check'),
jsonb_build_object('number',40,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe shop assistant gave me a discount. (get)',
  'answer',E'I got the shop assistant to give me a discount.',
  'similar_answers',jsonb_build_array(E'I got the shop assistant to give me a discount'),
  'explanation',E'get + 목적어 + to부정사: got the shop assistant to give'),
jsonb_build_object('number',41,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nThe shop delivered the food. (have)',
  'answer',E'I had the shop deliver the food.',
  'similar_answers',jsonb_build_array(E'I had the shop deliver the food'),
  'explanation',E'have + 목적어 + 동사원형: had the shop deliver'),
jsonb_build_object('number',42,
  'question',E'주어진 단어를 사용하여 "I"로 시작하는 문장으로 바꾸시오.\nMy brother helped me write the report. (get)',
  'answer',E'I got my brother to help me write the report.',
  'similar_answers',jsonb_build_array(E'I got my brother to help me write the report'),
  'explanation',E'get + 목적어 + to부정사: got my brother to help'),
jsonb_build_object('number',43,
  'question',E'다음 우리말을 영작하시오. (get 활용)\n그녀는 정비공이 엘리베이터를 고치도록 했다.',
  'answer',E'She got a mechanic to repair the elevator.',
  'similar_answers',jsonb_build_array(E'She got a mechanic to repair the elevator',E'She got the mechanic to repair the elevator.',E'She got the mechanic to repair the elevator',E'She got a mechanic to fix the elevator.',E'She got a mechanic to fix the elevator',E'She got the mechanic to fix the elevator.',E'She got the mechanic to fix the elevator'),
  'explanation',E'get + 목적어 + to부정사: got a mechanic to repair/fix'),
jsonb_build_object('number',44,
  'question',E'다음 우리말을 영작하시오. (have 활용)\n엄마는 남동생에게 방을 청소하게 하셨다.',
  'answer',E'Mom had my brother clean his room.',
  'similar_answers',jsonb_build_array(E'Mom had my brother clean his room',E'My mom had my brother clean his room.',E'My mom had my brother clean his room',E'Mom had my brother clean the room.',E'Mom had my brother clean the room',E'My mother had my brother clean his room.',E'My mother had my brother clean his room',E'My mother had my brother clean the room.',E'My mother had my brother clean the room',E'My mom had my brother clean the room.',E'My mom had my brother clean the room'),
  'explanation',E'have + 목적어 + 동사원형: had my brother clean'),
jsonb_build_object('number',45,
  'question',E'다음 우리말을 영작하시오. (get 활용)\n그는 아이들이 규칙을 따르게 했다.',
  'answer',E'He got his children to follow the rules.',
  'similar_answers',jsonb_build_array(E'He got his children to follow the rules',E'He got the children to follow the rules.',E'He got the children to follow the rules',E'He got his kids to follow the rules.',E'He got his kids to follow the rules',E'He got the kids to follow the rules.',E'He got the kids to follow the rules'),
  'explanation',E'get + 목적어 + to부정사: got his children to follow'),
jsonb_build_object('number',46,
  'question',E'다음 우리말을 영작하시오. (make 활용)\n학교는 학생들이 교복을 입게 한다.',
  'answer',E'The school makes all the students wear uniforms.',
  'similar_answers',jsonb_build_array(E'The school makes all the students wear uniforms',E'The school makes the students wear uniforms.',E'The school makes the students wear uniforms',E'The school makes all students wear uniforms.',E'The school makes all students wear uniforms',E'The school makes students wear uniforms.',E'The school makes students wear uniforms',E'School makes the students wear uniforms.',E'School makes the students wear uniforms'),
  'explanation',E'make + 목적어 + 동사원형: makes the students wear'),
jsonb_build_object('number',47,
  'question',E'다음 우리말을 영작하시오. (help 활용)\n개가 그의 길 건너는 것을 돕는다.',
  'answer',E'The dog helps him cross the road.',
  'similar_answers',jsonb_build_array(E'The dog helps him cross the road',E'The dog helps him to cross the road.',E'The dog helps him to cross the road',E'The dog helps him cross the street.',E'The dog helps him cross the street',E'The dog helps him to cross the street.',E'The dog helps him to cross the street',E'A dog helps him cross the road.',E'A dog helps him cross the road',E'A dog helps him to cross the road.',E'A dog helps him to cross the road'),
  'explanation',E'help + 목적어 + (to) 동사원형: helps him (to) cross'),
jsonb_build_object('number',48,
  'question',E'다음 우리말을 영작하시오. (help 활용)\n엄마는 내가 영어 공부하는 것을 도와주셨다.',
  'answer',E'My mother helped me to study English.',
  'similar_answers',jsonb_build_array(E'My mother helped me to study English',E'My mother helped me study English.',E'My mother helped me study English',E'My mom helped me to study English.',E'My mom helped me to study English',E'My mom helped me study English.',E'My mom helped me study English',E'Mom helped me to study English.',E'Mom helped me to study English',E'Mom helped me study English.',E'Mom helped me study English'),
  'explanation',E'help + 목적어 + (to) 동사원형: helped me (to) study'),

    -- ═══════════════════════════════════════════
    -- Part 3: 어법 오류 수정 (Q49~Q65) — 서술형
    -- Part 4: 어순 배열 + 영작 (Q66~Q80) — 서술형
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',49,
  'question',E'[Part 3] 문법적으로 틀린 부분을 찾아 고쳐 쓰시오.\n\nHe made his son to water the plants.',
  'answer',E'water',
  'similar_answers',jsonb_build_array(E'Water'),
  'explanation',E'make + 목적어 + 동사원형. to water → water. 사역동사 make 뒤에는 to 없이 동사원형이 온다.'),
jsonb_build_object('number',50,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nHis father would not let him to go.',
  'answer',E'go',
  'similar_answers',jsonb_build_array(E'Go'),
  'explanation',E'let + 목적어 + 동사원형. to go → go. 사역동사 let 뒤에는 to 없이 동사원형이 온다.'),
jsonb_build_object('number',51,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nMy father didn''t let me going out.',
  'answer',E'go',
  'similar_answers',jsonb_build_array(E'Go'),
  'explanation',E'let + 목적어 + 동사원형. going → go. 사역동사 let 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',52,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nShe made her child is helping the lady.',
  'answer',E'help',
  'similar_answers',jsonb_build_array(E'Help'),
  'explanation',E'make + 목적어 + 동사원형. is helping → help. 사역동사 make 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',53,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nPlease let I know the fact.',
  'answer',E'me',
  'similar_answers',jsonb_build_array(E'Me'),
  'explanation',E'let + 목적격 + 동사원형. 주격 I → 목적격 me. 사역동사의 목적어는 목적격을 써야 한다.'),
jsonb_build_object('number',54,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nJenny had me stays with her baby.',
  'answer',E'stay',
  'similar_answers',jsonb_build_array(E'Stay'),
  'explanation',E'have + 목적어 + 동사원형. stays → stay. 사역동사 have 뒤에는 동사원형이 오므로 3인칭 단수 -s가 불필요하다.'),
jsonb_build_object('number',55,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nShe always makes him to wait.',
  'answer',E'wait',
  'similar_answers',jsonb_build_array(E'Wait'),
  'explanation',E'make + 목적어 + 동사원형. to wait → wait. 사역동사 make 뒤에는 to 없이 동사원형이 온다.'),
jsonb_build_object('number',56,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nThese rules will help you studying well.',
  'answer',E'study',
  'similar_answers',jsonb_build_array(E'to study',E'Study',E'To study'),
  'explanation',E'help + 목적어 + (to) 동사원형. studying → study 또는 to study. help는 to부정사 또는 동사원형을 취한다.'),
jsonb_build_object('number',57,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nThe doctor let her to wash her hands.',
  'answer',E'wash',
  'similar_answers',jsonb_build_array(E'Wash'),
  'explanation',E'let + 목적어 + 동사원형. to wash → wash. 사역동사 let 뒤에는 to 없이 동사원형이 온다.'),
jsonb_build_object('number',58,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nMs. Yun let me to solving a math problem.',
  'answer',E'solve',
  'similar_answers',jsonb_build_array(E'Solve'),
  'explanation',E'let + 목적어 + 동사원형. to solving → solve. 사역동사 let 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',59,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nHe helped me carrying the heavy bag.',
  'answer',E'carry',
  'similar_answers',jsonb_build_array(E'to carry',E'Carry',E'To carry'),
  'explanation',E'help + 목적어 + (to) 동사원형. carrying → carry 또는 to carry. help는 to부정사 또는 동사원형을 취한다.'),
jsonb_build_object('number',60,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nMy mom made me solving the problems.',
  'answer',E'solve',
  'similar_answers',jsonb_build_array(E'Solve'),
  'explanation',E'make + 목적어 + 동사원형. solving → solve. 사역동사 make 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',61,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nI can''t make her stopped crying.',
  'answer',E'stop',
  'similar_answers',jsonb_build_array(E'Stop'),
  'explanation',E'make + 목적어 + 동사원형. stopped → stop. 사역동사 make 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',62,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nThey let their children studies hard.',
  'answer',E'study',
  'similar_answers',jsonb_build_array(E'Study'),
  'explanation',E'let + 목적어 + 동사원형. studies → study. 사역동사 let 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',63,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nI made my sister cleaned her room.',
  'answer',E'clean',
  'similar_answers',jsonb_build_array(E'Clean'),
  'explanation',E'make + 목적어 + 동사원형. cleaned → clean. 사역동사 make 뒤에는 동사원형이 온다.'),
jsonb_build_object('number',64,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nI bought a book to read it.',
  'answer',E'to read',
  'similar_answers',jsonb_build_array(E'To read'),
  'explanation',E'to부정사 형용사적 용법에서 목적어 it 삭제. a book을 수식하는 to read에서 book이 이미 목적어 역할을 하므로 it이 불필요하다. (1과 복습)'),
jsonb_build_object('number',65,
  'question',E'틀린 부분을 찾아 고쳐 쓰시오.\n\nMina would like to have a ball to play.',
  'answer',E'to play with',
  'similar_answers',jsonb_build_array(E'To play with'),
  'explanation',E'to부정사 형용사적 용법에서 전치사 with 필요. a ball to play with (공을 가지고 놀다). 전치사가 빠지면 의미가 불완전하다. (1과 복습)'),


jsonb_build_object('number',66,
  'question',E'[Part 4] 주어진 단어를 올바른 순서로 배열하시오.\n\n(dishes, him, made, I, wash, the)',
  'answer',E'I made him wash the dishes.',
  'similar_answers',jsonb_build_array(E'I made him wash the dishes'),
  'explanation',E'make + 목적어 + 동사원형. I made him wash the dishes. 사역동사 make 구문.'),
jsonb_build_object('number',67,
  'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(go, the, let, the, students, early, teacher, home)',
  'answer',E'The teacher let the students go home early.',
  'similar_answers',jsonb_build_array(E'The teacher let the students go home early'),
  'explanation',E'let + 목적어 + 동사원형. The teacher let the students go home early. 사역동사 let 구문.'),
jsonb_build_object('number',68,
  'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(her homework, had, finish, she, her daughter)',
  'answer',E'She had her daughter finish her homework.',
  'similar_answers',jsonb_build_array(E'She had her daughter finish her homework'),
  'explanation',E'have + 목적어 + 동사원형. She had her daughter finish her homework. 사역동사 have 구문.'),
jsonb_build_object('number',69,
  'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(makes, story, laugh, us, your)',
  'answer',E'Your story makes us laugh.',
  'similar_answers',jsonb_build_array(E'Your story makes us laugh'),
  'explanation',E'make + 목적어 + 동사원형. Your story makes us laugh. 사역동사 make 구문 (3인칭 단수 주어).'),
jsonb_build_object('number',70,
  'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(make, glasses, older, look, him)',
  'answer',E'Glasses make him look older.',
  'similar_answers',jsonb_build_array(E'Glasses make him look older'),
  'explanation',E'make + 목적어 + 동사원형 + 보어. Glasses make him look older. 사역동사 make 구문.'),
jsonb_build_object('number',71,
  'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(wind, made, away, hat, blow, her, the)',
  'answer',E'The wind made her hat blow away.',
  'similar_answers',jsonb_build_array(E'The wind made her hat blow away'),
  'explanation',E'make + 목적어 + 동사원형. The wind made her hat blow away. 사역동사 make 과거형 구문.'),
jsonb_build_object('number',72,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n아빠가 언니에게 설거지를 하게 했다.',
  'answer',E'My dad made my sister do the dishes.',
  'similar_answers',jsonb_build_array(E'My dad made my sister wash the dishes.',E'My father made my sister do the dishes.',E'My father made my sister wash the dishes.',E'My dad made my sister do the dishes',E'My dad made my sister wash the dishes',E'My father made my sister do the dishes',E'My father made my sister wash the dishes',E'Dad made my sister do the dishes.',E'Dad made my sister do the dishes',E'Dad made my sister wash the dishes.',E'Dad made my sister wash the dishes',E'My dad made my older sister do the dishes.',E'My dad made my older sister do the dishes',E'My dad made my older sister wash the dishes.',E'My dad made my older sister wash the dishes',E'My father made my older sister do the dishes.',E'My father made my older sister do the dishes',E'My father made my older sister wash the dishes.',E'My father made my older sister wash the dishes'),
  'explanation',E'make + 목적어 + 동사원형. ~에게 ~을 하게 했다 = made + 사람 + 동사원형. 설거지를 하다 = do/wash the dishes.'),
jsonb_build_object('number',73,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n내가 너에게 마술을 보여줄게.',
  'answer',E'Let me show you a magic trick.',
  'similar_answers',jsonb_build_array(E'Let me show you a magic trick',E'Let me show you magic.',E'Let me show you magic',E'Let me show a magic trick to you.',E'Let me show a magic trick to you',E'Let me show magic to you.',E'Let me show magic to you'),
  'explanation',E'Let me + 동사원형. 내가 ~할게 = Let me ~. 마술을 보여주다 = show you a magic trick.'),
jsonb_build_object('number',74,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n우리 부모님은 내가 일기를 쓰게 시키신다.',
  'answer',E'My parents make me keep a diary.',
  'similar_answers',jsonb_build_array(E'My parents make me write a diary.',E'My parents make me keep a diary',E'My parents make me write a diary',E'My parents make me keep my diary.',E'My parents make me keep my diary',E'My parents make me write my diary.',E'My parents make me write my diary',E'My parents make me write in a diary.',E'My parents make me write in a diary'),
  'explanation',E'make + 목적어 + 동사원형. ~하게 시키다 = make + 사람 + 동사원형. 일기를 쓰다 = keep/write a diary. 현재 습관이므로 make 현재형.'),
jsonb_build_object('number',75,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n그는 늙은 아버지를 걷게 놔두었다.',
  'answer',E'He let his old father walk.',
  'similar_answers',jsonb_build_array(E'He let his elderly father walk.',E'He let his old father walk',E'He let his elderly father walk',E'He let his aged father walk.',E'He let his aged father walk'),
  'explanation',E'let + 목적어 + 동사원형. ~하게 놔두다 = let + 사람 + 동사원형. let의 과거형도 let.'),
jsonb_build_object('number',76,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n나의 아빠는 내가 외출하는 것을 허락하지 않으셨다.',
  'answer',E'My dad didn''t let me go out.',
  'similar_answers',jsonb_build_array(E'My father didn''t let me go out.',E'My dad did not let me go out.',E'My father did not let me go out.',E'My dad didn''t let me go out',E'My father didn''t let me go out',E'My dad did not let me go out',E'My father did not let me go out'),
  'explanation',E'let + 목적어 + 동사원형의 부정. 허락하지 않다 = didn''t let + 사람 + 동사원형. 외출하다 = go out.'),
jsonb_build_object('number',77,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n무엇이 너를 그렇게 생각하게 만드니?',
  'answer',E'What makes you think so?',
  'similar_answers',jsonb_build_array(E'What makes you think so',E'What makes you think that?',E'What makes you think that',E'What makes you think like that?',E'What makes you think like that'),
  'explanation',E'make + 목적어 + 동사원형. 의문사 What이 주어(3인칭 단수)이므로 makes. 그렇게 생각하다 = think so.'),
jsonb_build_object('number',78,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n제 소개를 하겠습니다.',
  'answer',E'Let me introduce myself.',
  'similar_answers',jsonb_build_array(E'Let me introduce myself',E'Allow me to introduce myself.',E'Allow me to introduce myself'),
  'explanation',E'Let me + 동사원형. 제 소개를 하다 = introduce myself. 관용 표현.'),
jsonb_build_object('number',79,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n나는 수리공으로 하여금 나의 차를 수리하도록 하였다.',
  'answer',E'I had the mechanic fix my car.',
  'similar_answers',jsonb_build_array(E'I had a mechanic fix my car.',E'I had the mechanic repair my car.',E'I had a mechanic repair my car.',E'I had the mechanic fix my car',E'I had a mechanic fix my car',E'I had the mechanic repair my car',E'I had a mechanic repair my car'),
  'explanation',E'have + 목적어 + 동사원형. ~로 하여금 ~하도록 하다 = had + 사람 + 동사원형. 수리하다 = fix/repair.'),
jsonb_build_object('number',80,
  'question',E'다음 우리말을 영어로 쓰시오.\n\n내가 너를 사랑하고 있다는 것을 너에게 어떻게 이해시킬 수 있을까?',
  'answer',E'How can I make you understand that I love you?',
  'similar_answers',jsonb_build_array(E'How can I make you understand that I love you',E'How can I make you understand I love you?',E'How can I make you understand I love you'),
  'explanation',E'make + 목적어 + 동사원형. 이해시키다 = make you understand. that절이 understand의 목적어.')
  );

  a := jsonb_build_array(
    '1',
    '2',
    '1',
    '1',
    '1',
    '1',
    '2',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '2',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    '1',
    E'I had the taxi driver collect us.',
    E'I got John to arrive on time.',
    E'I had the mechanic fix the brakes.',
    E'I got my husband to look after our children.',
    E'I had the waiter bring some water.',
    E'I had the nurse take my temperature.',
    E'I got the students to stop sleeping in class.',
    E'I had the dentist clean my teeth.',
    E'I got my friend to take her car.',
    E'I had them wash the windows.',
    E'I got the child to eat her vegetables.',
    E'I got the teacher to check my writing.',
    E'I got the shop assistant to give me a discount.',
    E'I had the shop deliver the food.',
    E'I got my brother to help me write the report.',
    E'She got a mechanic to repair the elevator.',
    E'Mom had my brother clean his room.',
    E'He got his children to follow the rules.',
    E'The school makes all the students wear uniforms.',
    E'The dog helps him cross the road.',
    E'My mother helped me to study English.',
    E'water',
    E'go',
    E'go',
    E'help',
    E'me',
    E'stay',
    E'wait',
    E'study',
    E'wash',
    E'solve',
    E'carry',
    E'solve',
    E'stop',
    E'study',
    E'clean',
    E'to read',
    E'to play with',
    E'I made him wash the dishes.',
    E'The teacher let the students go home early.',
    E'She had her daughter finish her homework.',
    E'Your story makes us laugh.',
    E'Glasses make him look older.',
    E'The wind made her hat blow away.',
    E'My dad made my sister do the dishes.',
    E'Let me show you a magic trick.',
    E'My parents make me keep a diary.',
    E'He let his old father walk.',
    E'My dad didn''t let me go out.',
    E'What makes you think so?',
    E'Let me introduce myself.',
    E'I had the mechanic fix my car.',
    E'How can I make you understand that I love you?'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    '사역동사 Step 1',
    '사역동사',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
