-- ============================================================
-- 명사를 꾸며주는 분사 Step 2 — 객관식 100문항 (복수정답 1문항 포함)
-- template_topic: 명사를 꾸며주는 분사
-- category: problem, mode: interactive
-- Parts: 1(빈칸 Q1-10), 2(AB빈칸 Q11-22), 3(ABC빈칸 Q23-30),
--        4(어법상 옳은 것 Q31-42), 5(어법상 어색한 것 Q43-54),
--        6(쓰임이 다른 것 Q55-66), 7(보기와 같은/다른 것 Q67-76),
--        8(옳은 문장 총 개수 Q77-80), 9(옳은 문장 짝짓기 Q81-90),
--        10(우리말 영작 Q91-100)
-- ============================================================

DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN

DELETE FROM naesin_templates WHERE title = E'명사를 꾸며주는 분사 Step 2';

-- ── q1: Part 1-4 (Q1–Q42) ──
q1 := jsonb_build_array(
jsonb_build_object('number',1,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThe boy __________ next to me on the bus is my classmate.','type','mcq','options',jsonb_build_array(E'sit',E'sat',E'sitting',E'to sit',E'is sitting'),'answer',E'3','explanation',E'소년이 앉아 있는 중(능동/진행) → 현재분사 sitting'),
jsonb_build_object('number',2,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nI received a letter __________ in Chinese.','type','mcq','options',jsonb_build_array(E'write',E'wrote',E'writing',E'written',E'to write'),'answer',E'4','explanation',E'편지가 쓰여진 것(수동) → 과거분사 written'),
jsonb_build_object('number',3,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThe girl __________ the piano on stage is my younger sister.','type','mcq','options',jsonb_build_array(E'play',E'played',E'plays',E'playing',E'to play'),'answer',E'4','explanation',E'소녀가 피아노를 치고 있는 중(능동/진행) → 현재분사 playing'),
jsonb_build_object('number',4,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nLook at the leaves __________ on the ground after the storm.','type','mcq','options',jsonb_build_array(E'fall',E'falling',E'fell',E'fallen',E'to fall'),'answer',E'4','explanation',E'나뭇잎이 이미 떨어진 상태(완료) → 과거분사 fallen'),
jsonb_build_object('number',5,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nShe was __________ to hear that her team had won the championship.','type','mcq','options',jsonb_build_array(E'excite',E'exciting',E'excites',E'to excite',E'excited'),'answer',E'5','explanation',E'그녀가 흥분을 느낌(감정을 느끼는 사람) → 과거분사 excited'),
jsonb_build_object('number',6,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThere is a bridge __________ two small islands.','type','mcq','options',jsonb_build_array(E'connect',E'connected',E'connection',E'connecting',E'to connecting'),'answer',E'4','explanation',E'다리가 두 섬을 연결하고 있는 중(능동) → 현재분사 connecting'),
jsonb_build_object('number',7,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThe documentary was so __________ that I watched it twice.','type','mcq','options',jsonb_build_array(E'touch',E'touched',E'touching',E'to touch',E'touches'),'answer',E'3','explanation',E'다큐가 감동을 유발(감정 유발 → 사물) → 현재분사 touching'),
jsonb_build_object('number',8,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nDo you know the man __________ a speech in front of the crowd?','type','mcq','options',jsonb_build_array(E'make',E'made',E'makes',E'to make',E'making'),'answer',E'5','explanation',E'남자가 연설하고 있는 중(능동/진행) → 현재분사 making'),
jsonb_build_object('number',9,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nMost people found the professor''s lecture __________.','type','mcq','options',jsonb_build_array(E'bore',E'bored',E'bores',E'boring',E'to bore'),'answer',E'4','explanation',E'강의가 지루함을 유발(감정 유발) → 현재분사 boring. find + 목적어 + 분사'),
jsonb_build_object('number',10,'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThe children __________ to the birthday party arrived with big smiles.','type','mcq','options',jsonb_build_array(E'invite',E'inviting',E'invites',E'to invite',E'invited'),'answer',E'5','explanation',E'아이들이 초대받은 것(수동) → 과거분사 invited'),
jsonb_build_object('number',11,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Don''t sit on the (A)_____ chair. It''s dangerous.\n• The girl (B)_____ a red cap is my friend Jisu.','type','mcq','options',jsonb_build_array(E'break — wear',E'broken — wearing',E'breaking — wearing',E'broken — worn',E'breaking — worn'),'answer',E'2','explanation',E'(A) 의자가 부서진 상태(수동) → broken / (B) 소녀가 쓰고 있는 중(능동) → wearing'),
jsonb_build_object('number',12,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• I picked up the leaves (A)_____ on the ground.\n• Tom drew a bird (B)_____ in the sky.','type','mcq','options',jsonb_build_array(E'fall — fly',E'falling — flying',E'fallen — flown',E'fallen — flying',E'falling — flown'),'answer',E'4','explanation',E'(A) 이미 떨어진 나뭇잎(완료) → fallen / (B) 새가 날고 있는 중(능동) → flying'),
jsonb_build_object('number',13,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Yujin likes this novel (A)_____ by Leo Tolstoy.\n• Do you know the man (B)_____ at the lake?','type','mcq','options',jsonb_build_array(E'write — look',E'writing — looked',E'written — looking',E'written — looked',E'to write — to look'),'answer',E'3','explanation',E'(A) 소설이 쓰여진 것(수동) → written / (B) 남자가 보고 있는 중(능동) → looking'),
jsonb_build_object('number',14,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• The most (A)_____ thing about the trip was the food.\n• I was completely (B)_____ by the magician''s performance.','type','mcq','options',jsonb_build_array(E'amazed — amazing',E'amazing — amazing',E'amazed — amazed',E'amazing — amazed',E'amaze — amazed'),'answer',E'4','explanation',E'(A) 사물이 감탄을 유발 → amazing(현재분사) / (B) 사람이 감탄을 느낌 → amazed(과거분사)'),
jsonb_build_object('number',15,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Don''t pick the flowers (A)_____ in the garden.\n• The girl (B)_____ the flowers in the garden is my cousin.','type','mcq','options',jsonb_build_array(E'planting — planted',E'planted — planting',E'planting — planting',E'planted — planted',E'plant — planting'),'answer',E'2','explanation',E'(A) 꽃이 심어진 것(수동) → planted / (B) 소녀가 심고 있는 중(능동) → planting'),
jsonb_build_object('number',16,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• There is a tunnel (A)_____ to the city center.\n• There are two people (B)_____ for the subway.','type','mcq','options',jsonb_build_array(E'connected — waiting',E'connecting — waited',E'connected — waited',E'connecting — waiting',E'connect — wait'),'answer',E'4','explanation',E'(A) 터널이 연결하고 있는(능동) → connecting / (B) 사람들이 기다리고 있는 중(능동) → waiting'),
jsonb_build_object('number',17,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• The news about the accident was very (A)_____.\n• Everyone in the room felt (B)_____ when they heard it.','type','mcq','options',jsonb_build_array(E'shocked — shocking',E'shocking — shocking',E'shocking — shocked',E'shocked — shocked',E'shock — shocked'),'answer',E'3','explanation',E'(A) 뉴스가 충격을 유발(사물) → shocking / (B) 사람들이 충격을 느낌 → shocked'),
jsonb_build_object('number',18,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Justin was (A)_____ to hear about the accident.\n• This book has many (B)_____ stories for young readers.','type','mcq','options',jsonb_build_array(E'surprised — touching',E'surprised — touched',E'surprising — touching',E'surprising — touched',E'surprise — touch'),'answer',E'1','explanation',E'(A) Justin이 놀람을 느낌(사람) → surprised / (B) 이야기가 감동을 유발(사물) → touching'),
jsonb_build_object('number',19,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• The car (A)_____ in the accident last night was mine.\n• There are hundreds of people (B)_____ in this factory.','type','mcq','options',jsonb_build_array(E'breaking — work',E'breaking — working',E'broke — work',E'broken — worked',E'broken — working'),'answer',E'5','explanation',E'(A) 차가 부서진 것(수동) → broken / (B) 사람들이 일하고 있는 중(능동) → working'),
jsonb_build_object('number',20,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• I have an old book (A)_____ in Chinese.\n• My teacher was (B)_____ by my progress.','type','mcq','options',jsonb_build_array(E'writing — impressing',E'writing — impressed',E'written — impressing',E'written — impressed',E'wrote — impress'),'answer',E'4','explanation',E'(A) 책이 쓰여진 것(수동) → written / (B) 선생님이 감명을 받은(사람) → impressed'),
jsonb_build_object('number',21,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Peter walked on the (A)_____ leaves in the forest.\n• I think his performance was really (B)_____.','type','mcq','options',jsonb_build_array(E'falling — surprised',E'falling — surprising',E'fallen — surprised',E'fallen — surprising',E'fall — surprise'),'answer',E'4','explanation',E'(A) 이미 떨어진 낙엽(완료) → fallen / (B) 공연이 놀라움을 유발(사물) → surprising'),
jsonb_build_object('number',22,'question',E'빈칸 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• The students found some (A)_____ treasure in the old box.\n• Look at the cute kids (B)_____ on the stage.','type','mcq','options',jsonb_build_array(E'hiding — danced',E'hiding — dancing',E'hidden — danced',E'hidden — dancing',E'hid — dance'),'answer',E'4','explanation',E'(A) 보물이 숨겨진 것(수동) → hidden / (B) 아이들이 춤추고 있는 중(능동) → dancing'),
jsonb_build_object('number',23,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• I threw away the (A)_____ glasses.\n• The picture (B)_____ in yellow is my daughter''s.\n• Mary told me some (C)_____ news.','type','mcq','options',jsonb_build_array(E'broken — painted — shocking',E'broken — painted — shocked',E'breaking — painted — shocking',E'breaking — painting — shocked',E'broken — painting — shocking'),'answer',E'1','explanation',E'(A) 깨진 안경(수동) → broken / (B) 노란색으로 칠해진(수동) → painted / (C) 충격적인 뉴스(감정 유발) → shocking'),
jsonb_build_object('number',24,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• The Eiffel Tower is a famous structure (A)_____ in 1889.\n• My father is the man (B)_____ a rest under the tree.\n• She watched a ghost (C)_____ people on the street.','type','mcq','options',jsonb_build_array(E'building — taking — attacking',E'building — taking — attacked',E'built — taking — attacking',E'built — taken — attacking',E'built — taking — attacked'),'answer',E'3','explanation',E'(A) 건축된 구조물(수동) → built / (B) 쉬고 있는 중(능동) → taking / (C) 유령이 공격하고 있는 중(능동) → attacking'),
jsonb_build_object('number',25,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Justin was (A)_____ to hear the news.\n• This book has many (B)_____ stories.\n• I bought a (C)_____ car because I didn''t have much money.','type','mcq','options',jsonb_build_array(E'surprised — touching — used',E'surprised — touched — using',E'surprising — touched — used',E'surprising — touching — using',E'surprising — touching — used'),'answer',E'1','explanation',E'(A) Justin이 놀람 느낌(사람) → surprised / (B) 감동적인 이야기(감정 유발) → touching / (C) 중고차(사용된) → used'),
jsonb_build_object('number',26,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• There are many students (A)_____ in science.\n• This is a story (B)_____ by O. Henry.\n• The ceremony was (C)_____ and everyone cried.','type','mcq','options',jsonb_build_array(E'interesting — written — moved',E'interested — written — moving',E'interested — writing — moved',E'interesting — written — moving',E'interested — wrote — moving'),'answer',E'2','explanation',E'(A) 학생들이 흥미를 느낌 → interested / (B) 이야기가 쓰여진(수동) → written / (C) 의식이 감동적(감정 유발) → moving'),
jsonb_build_object('number',27,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• Look at the mountain (A)_____ with snow.\n• The woman (B)_____ a violin on stage is my aunt.\n• All the actors (C)_____ in the play are professional.','type','mcq','options',jsonb_build_array(E'covering — playing — involving',E'covered — played — involved',E'covering — played — involved',E'covered — playing — involving',E'covered — playing — involved'),'answer',E'5','explanation',E'(A) 산이 눈으로 덮인(수동) → covered / (B) 여자가 연주 중(능동) → playing / (C) 배우들이 참여한(수동) → involved'),
jsonb_build_object('number',28,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• She is the actress (A)_____ to everyone in China.\n• Look at this amazing bridge (B)_____ by Leon.\n• Some of the people (C)_____ to the party brought food.','type','mcq','options',jsonb_build_array(E'knowing — designed — inviting',E'known — designing — invited',E'known — designed — invited',E'knowing — designed — invited',E'known — designed — inviting'),'answer',E'3','explanation',E'(A) 여배우가 알려진(수동) → known / (B) 다리가 설계된(수동) → designed / (C) 사람들이 초대받은(수동) → invited'),
jsonb_build_object('number',29,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• He was reading a book (A)_____ by J.K. Rowling.\n• The (B)_____ baby in the corner looks so peaceful.\n• My father sold his old car and bought a (C)_____ one.','type','mcq','options',jsonb_build_array(E'written — sleeping — used',E'writing — sleeping — using',E'written — slept — used',E'writing — slept — using',E'written — sleeping — using'),'answer',E'1','explanation',E'(A) 책이 쓰여진(수동) → written / (B) 잠자고 있는 아기(능동/진행) → sleeping / (C) 중고(사용된) → used'),
jsonb_build_object('number',30,'question',E'빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n• There were pieces of (A)_____ glass on the floor.\n• The two girls (B)_____ to each other are Mira and Sally.\n• I was deeply (C)_____ by his words.','type','mcq','options',jsonb_build_array(E'breaking — talked — moved',E'broken — talking — moving',E'broken — talking — moved',E'breaking — talking — moved',E'broken — talked — moved'),'answer',E'3','explanation',E'(A) 깨진 유리(수동) → broken / (B) 대화 중인 소녀들(능동) → talking / (C) 감동받은(사람) → moved'),
jsonb_build_object('number',31,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'He bought a car making in Korea.',E'The story has a surprised ending.',E'I saw the birds flying in the sky.',E'Who is the man wear a necktie?',E'The man drive the car is my friend.'),'answer',E'3','explanation',E'③ flying 올바른 현재분사 / ① making → made / ② surprised → surprising / ④ wear → wearing / ⑤ drive → driving'),
jsonb_build_object('number',32,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I like excited games.',E'Look at the burned building in the news.',E'This book has a touched story.',E'Who is the man wore a necktie?',E'The man driving the car is my friend.'),'answer',E'5','explanation',E'⑤ driving 올바른 현재분사 / ① excited → exciting / ② burned → burning / ③ touched → touching / ④ wore → wearing'),
jsonb_build_object('number',33,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Tom is happy with the using car he bought.',E'Today is the most exciting day of my life.',E'Amy and Tim are stuck behind a locking door.',E'Jessica collects falling leaves every autumn.',E'I think this book has lots of touched stories.'),'answer',E'2','explanation',E'② exciting 올바른 현재분사 / ① using → used / ③ locking → locked / ④ falling → fallen (이미 떨어진 낙엽을 모으는 것) / ⑤ touched → touching'),
jsonb_build_object('number',34,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Ann found a key hiding under the desk.',E'The baby crying all morning makes me crazy.',E'Mr. Lee''s accident was quite surprised news.',E'I bought a using car because I had no money.',E'There was a very interested article in the paper.'),'answer',E'2','explanation',E'② crying 올바른 현재분사 / ① hiding → hidden / ③ surprised → surprising / ④ using → used / ⑤ interested → interesting'),
jsonb_build_object('number',35,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I went to a meeting holding in Seoul.',E'Let''s pick up these leaves fallen under the tree.',E'I am reading a book writing by George Orwell.',E'There are two people waited for the train.',E'The man talked with Tom is John.'),'answer',E'2','explanation',E'② fallen 올바른 과거분사 / ① holding → held / ③ writing → written / ④ waited → waiting / ⑤ talked → talking'),
jsonb_build_object('number',36,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'She is talking with a boy sitting on the bench.',E'There is a glass filling with orange juice.',E'I want to see the photo taking at the park.',E'My father is reading a newspaper writing in English.',E'I heard my name calling far behind the building.'),'answer',E'1','explanation',E'① sitting 올바른 현재분사 / ② filling → filled / ③ taking → taken / ④ writing → written / ⑤ calling → called'),
jsonb_build_object('number',37,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The road calling "the old road" is now blocked.',E'Look at that girl wore a red skirt.',E'There was a coat hanging on the wall.',E'This is an old picture taking 20 years ago.',E'He lost a book writing by William Shakespeare.'),'answer',E'3','explanation',E'③ hanging 올바른 현재분사 / ① calling → called / ② wore → wearing / ④ taking → taken / ⑤ writing → written'),
jsonb_build_object('number',38,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'All the people inviting to the party are enjoying themselves.',E'I''m reading a play written by Shakespeare.',E'Look at the man painted the house yellow.',E'Jason is eating the spaghetti making by my mom.',E'Who is the pretty woman played the piano?'),'answer',E'2','explanation',E'② written 올바른 과거분사 / ① inviting → invited / ③ painted → painting / ④ making → made / ⑤ played → playing'),
jsonb_build_object('number',39,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'A bear naming Buck is very smart.',E'I read a short story written by O. Henry.',E'This is the scarf making by my grandmother.',E'This is the robot which invented by Dr. Lee.',E'Some of the people inviting to the party didn''t come.'),'answer',E'2','explanation',E'② written 올바른 과거분사 / ① naming → named / ③ making → made / ④ which invented → invented (또는 which was invented) / ⑤ inviting → invited'),
jsonb_build_object('number',40,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The girl waited at the gate is my friend.',E'I want to buy that coat hang on the wall.',E'I know the talking man with the girl.',E'Listen to the birds singing in the woods.',E'The dog barking is my lovely pet.'),'answer',E'4','explanation',E'④ singing 올바른 현재분사 / ① waited → waiting / ② hang → hanging / ③ talking man with → man talking with / ⑤ barking 단독 사용 어색(수식어 필요)'),
jsonb_build_object('number',41,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The taxi taken us to the airport broke down.',E'Somebody naming John called while you were out.',E'There were pieces of breaking glass on the floor.',E'The two girls talking to each other are Mira and Sally.',E'Some of the people inviting to the party couldn''t come.'),'answer',E'4','explanation',E'④ talking 올바른 현재분사 / ① taken → taking / ② naming → named / ③ breaking → broken / ⑤ inviting → invited'),
jsonb_build_object('number',42,'question',E'다음 중 어법상 옳은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I went to the meeting holding in Seoul.',E'She wants the plant watering enough.',E'Look at the mountain covering with snow.',E'The pictures taken at the party last night are funny.',E'My daughter plays with the doll that dressing in red.'),'answer',E'4','explanation',E'④ taken 올바른 과거분사 / ① holding → held / ② watering → watered / ③ covering → covered / ⑤ dressing → dressed (또는 that is dressed)')
);

-- ── q2: Part 5-7 (Q43–Q76) ──
q2 := jsonb_build_array(
jsonb_build_object('number',43,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Look at the bird flying in the sky.',E'I saw the girl dancing on the stage.',E'I like this tree planted by my father.',E'I was deeply impressed by his words.',E'The police found the bag throwing in the woods.'),'answer',E'5','explanation',E'⑤ throwing → thrown (가방이 버려진 것 → 수동/과거분사)'),
jsonb_build_object('number',44,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Do not wake up the sleeping baby.',E'Watches made in Switzerland are very expensive.',E'Their presentation was bored and not impressive.',E'I''m not interested in Korean artworks.',E'What is the language spoken in Egypt?'),'answer',E'3','explanation',E'③ bored → boring (발표가 지루함을 유발 → 현재분사)'),
jsonb_build_object('number',45,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The man standing beside the tree is my uncle.',E'Look at the dog swimming in the sea.',E'Read the book written in English.',E'I bought a mobile phone made in Korea.',E'I found the cat cried on the desk.'),'answer',E'5','explanation',E'⑤ cried → crying (고양이가 울고 있는 중 → 현재분사)'),
jsonb_build_object('number',46,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The girl singing a song is Mary.',E'Can you read a letter writing in English?',E'I saw a pretty woman wearing very long boots.',E'Who is that old man carrying heavy bags?',E'The boy standing outside is my younger brother.'),'answer',E'2','explanation',E'② writing → written (편지가 쓰여진 것 → 수동/과거분사)'),
jsonb_build_object('number',47,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I saw a boy crossing the street.',E'The girl is talking with Tony is Jenny.',E'The cake made by my mother is delicious.',E'The police found the bag thrown in the woods.',E'Do you know the woman talking to him?'),'answer',E'2','explanation',E'② is talking → talking (분사가 명사를 수식할 때 be동사 없이 현재분사만 사용)'),
jsonb_build_object('number',48,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I like clothes made in Korea.',E'He read the card written by my mom.',E'The girl playing the piano is my sister.',E'The robot invented by Dr. Kim was fantastic.',E'The picture painting by Dad is on the wall.'),'answer',E'5','explanation',E'⑤ painting → painted (그림이 그려진 것 → 수동/과거분사)'),
jsonb_build_object('number',49,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'She is the actress known to everybody in China.',E'The bike found in the park is my brother''s.',E'He is reading a book wrote by J.K. Rowling.',E'Look at this amazing bridge designed by Leon.',E'Some of the people invited to the party brought food.'),'answer',E'3','explanation',E'③ wrote → written (책이 쓰여진 것 → 과거분사, wrote는 과거시제)'),
jsonb_build_object('number',50,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'There is a box filling with toys.',E'I found a wooden box containing lots of money.',E'The firefighter rushed into the burning house.',E'Most of the shops found in the mall are large.',E'She is looking at the menu written in English.'),'answer',E'1','explanation',E'① filling → filled (상자가 채워진 것 → 수동/과거분사)'),
jsonb_build_object('number',51,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'She is the writer loved by all Koreans.',E'Look at this picture which took by my brother.',E'Many students holding ID cards were waiting.',E'There were people who were waiting in line.',E'An actor named Minho appeared in the movie.'),'answer',E'2','explanation',E'② which took → which was taken 또는 taken (사진이 찍힌 것 → 수동)'),
jsonb_build_object('number',52,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The barking dog is mine.',E'We brought all tools required to fix the bike.',E'She saw a wounded soldier lying on the grass.',E'Do you know the boy sitting next to Cathy?',E'I think bungee jumping was a terrified experience.'),'answer',E'5','explanation',E'⑤ terrified → terrifying (경험이 공포를 유발 → 현재분사)'),
jsonb_build_object('number',53,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Look at the birds singing in the trees.',E'There was a fancy car parked outside the house.',E'Look at the student satisfied with the exam result.',E'The road connecting two towns was blocked by a truck.',E'The man stood over there is my uncle.'),'answer',E'5','explanation',E'⑤ stood → standing (남자가 서 있는 중 → 현재분사)'),
jsonb_build_object('number',54,'question',E'다음 중 어법상 어색한 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Did you read the letter posted on the blog?',E'There is a woman ironing clothes in the painting.',E'I used to collect fallen leaves every autumn.',E'There is a big tree planting in 1930.',E'They are looking at the menu written in English.'),'answer',E'4','explanation',E'④ planting → planted (나무가 심어진 것 → 수동/과거분사)'),
jsonb_build_object('number',55,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Harry drew a cat <u>eating</u> a fish.',E'Look at that <u>crying</u> baby.',E'He is <u>playing</u> the guitar on stage.',E'<u>Collecting</u> stamps is my hobby.',E'I know many students <u>learning</u> Korean.'),'answer',E'4','explanation',E'④ 동명사(주어 역할) / 나머지는 현재분사(명사 수식 또는 진행형)'),
jsonb_build_object('number',56,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I heard the <u>shocking</u> news from him.',E'She enjoyed <u>playing</u> the violin at the concert.',E'Cover this <u>sleeping</u> child with your coat.',E'They saw a <u>singing</u> bird on the tree.',E'The boy <u>wearing</u> a blue hat is Ji-hun.'),'answer',E'2','explanation',E'② 동명사(목적어 역할) / 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',57,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I''m afraid of dogs <u>barking</u> at people.',E'She wanted a doll <u>wearing</u> a red dress.',E'Look at the <u>smiling</u> baby. She is so cute.',E'The man was <u>cooking</u> dinner for his wife.',E'Yumi''s hobby is <u>taking</u> pictures of people.'),'answer',E'5','explanation',E'⑤ 동명사(보어 역할) / ①②③ 현재분사(명사 수식) / ④ 현재분사(진행형)'),
jsonb_build_object('number',58,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'These are non-<u>smoking</u> seats.',E'Her job is <u>designing</u> baby clothes.',E'Please meet me at the <u>waiting</u> room.',E'I burned my finger with <u>boiling</u> water.',E'Look at the dog <u>running</u> after the cat.'),'answer',E'5','explanation',E'⑤ 현재분사(명사 뒤에서 수식) / ①②③④는 명사 앞 수식 또는 동명사'),
jsonb_build_object('number',59,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'His job is <u>teaching</u> English.',E'I saw the birds <u>flying</u> in the sky.',E'My sister is <u>singing</u> on the stage.',E'She looks like a <u>dancing</u> machine.',E'The <u>sleeping</u> baby on the bed is very cute.'),'answer',E'1','explanation',E'① 동명사(보어 역할) / 나머지는 현재분사'),
jsonb_build_object('number',60,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'<u>Exercising</u> every day is good for your health.',E'The girl <u>holding</u> a book is Mina.',E'The boy <u>wearing</u> glasses is Ann''s brother.',E'There is a dog <u>sleeping</u> by the bench.',E'There is a man <u>lying</u> on the sofa.'),'answer',E'1','explanation',E'① 동명사(주어 역할) / 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',61,'question',E'다음 중 밑줄 친 부분의 쓰임이 같은 것끼리 묶인 것은?\nⓐ The boy <u>crying</u> over there is my brother.\nⓑ We should wait for the train <u>leaving</u> at 8:00.\nⓒ I need to buy a <u>sleeping</u> bag for camping.\nⓓ Students are supposed to be in the <u>waiting</u> room.\nⓔ My uncle <u>living</u> in New York is very busy.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓒ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓔ',E'ⓒ, ⓓ, ⓔ'),'answer',E'4','explanation',E'ⓐⓑⓔ는 현재분사(명사 수식 — 동작 묘사) / ⓒⓓ는 동명사(용도)'),
jsonb_build_object('number',62,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I saw a <u>dancing</u> bear in the zoo.',E'A <u>sleeping</u> baby is like an angel.',E'He tried <u>opening</u> the bottle with a spoon.',E'The girl <u>listening</u> to music is Ann.',E'The man <u>sitting</u> on the bench is my father.'),'answer',E'3','explanation',E'③ 동명사(목적어 역할 — try + V-ing) / 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',63,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'The boy <u>reading</u> a book is my son.',E'<u>Taking</u> a walk is good for your health.',E'There are two girls <u>studying</u> in my class.',E'The girl <u>asking</u> for directions is new here.',E'The man <u>painting</u> a picture wants to be an artist.'),'answer',E'2','explanation',E'② 동명사(주어 역할) / 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',64,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'I saw a <u>running</u> dog in the park.',E'A <u>rolling</u> stone gathers no moss.',E'He was in his room <u>studying</u> math.',E'The <u>sleeping</u> baby is my nephew.',E'There is a <u>smoking</u> room in this building.'),'answer',E'5','explanation',E'⑤ 동명사(용도 — 흡연을 위한 방) / 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',65,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'<u>Swimming</u> every morning keeps me healthy.',E'My dream is <u>becoming</u> a doctor someday.',E'He saw a man <u>lying</u> on the floor.',E'<u>Watching</u> movies is her favorite pastime.',E'I enjoy <u>listening</u> to classical music.'),'answer',E'3','explanation',E'③ 현재분사(명사 수식) / 나머지는 동명사(주어/보어/목적어)'),
jsonb_build_object('number',66,'question',E'다음 중 밑줄 친 부분의 쓰임이 나머지 넷과 다른 것을 고르시오.','type','mcq','options',jsonb_build_array(E'<u>Learning</u> English is very important.',E'His wish is <u>traveling</u> around the world.',E'I hate <u>speaking</u> in front of other people.',E'A police officer is <u>guarding</u> the entrance.',E'What is your secret for <u>winning</u> the contest?'),'answer',E'4','explanation',E'④ 현재분사(진행형 be + V-ing) / 나머지는 동명사(주어/보어/목적어/전치사의 목적어)'),
jsonb_build_object('number',67,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 다른 것을 고르시오.\n\n<보기> Look at the dog <u>running</u> toward him.','type','mcq','options',jsonb_build_array(E'<u>Reading</u> a book is a good hobby.',E'Julia saw a boy <u>walking</u> down the street.',E'Jessica kept her boyfriend <u>waiting</u> for 3 hours.',E'Do you know the <u>shouting</u> man over there?',E'The soccer game was really <u>exciting</u>.'),'answer',E'1','explanation',E'① 동명사(주어 역할) / 보기와 ②③④⑤는 현재분사'),
jsonb_build_object('number',68,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 다른 것을 고르시오.\n\n<보기> All the actors <u>singing</u> and <u>dancing</u> make the movie fun.','type','mcq','options',jsonb_build_array(E'He was in his room <u>studying</u> math.',E'We saw a <u>running</u> dog pass us.',E'A <u>rolling</u> stone gathers no moss.',E'The <u>sleeping</u> baby is my nephew.',E'There is a <u>smoking</u> room in the coffee shop.'),'answer',E'5','explanation',E'⑤ 동명사(용도 — 흡연을 위한 방) / 보기와 나머지는 현재분사(명사 수식)'),
jsonb_build_object('number',69,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 모두 고르시오.\n\n<보기> The boys are <u>making</u> a model airplane.','type','select_all','options',jsonb_build_array(E'<u>Drinking</u> coffee will help you stay awake.',E'I heard someone <u>knocking</u> on the door.',E'His hobby is <u>playing</u> ice hockey.',E'Who is the girl <u>wearing</u> the blue jacket?',E'She enjoys <u>jogging</u> every morning.'),'answer',jsonb_build_array('2','4'),'explanation',E'②④ 현재분사 / ①③⑤ 동명사'),
jsonb_build_object('number',70,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 고르시오.\n\n<보기> We saw a big eagle <u>flying</u> above us.','type','mcq','options',jsonb_build_array(E'<u>Swimming</u> every morning keeps me healthy.',E'My dream is <u>becoming</u> a doctor someday.',E'He saw a man <u>lying</u> on the floor.',E'<u>Watching</u> movies is her favorite pastime.',E'I enjoy <u>listening</u> to classical music.'),'answer',E'3','explanation',E'③ 현재분사(명사 수식 — saw + 목적어 + V-ing) / 나머지는 동명사'),
jsonb_build_object('number',71,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 고르시오.\n\n<보기> Where is your <u>sleeping</u> bag?','type','mcq','options',jsonb_build_array(E'The male fox began <u>pushing</u> hard.',E'The dog was <u>lying</u> on his bed.',E'The cat threw it to the <u>waiting</u> dog.',E'They''ve been <u>preparing</u> for the project.',E'An elephant was <u>freeing</u> himself from a trap.'),'answer',E'3','explanation',E'③ 동명사(용도) / 보기의 sleeping bag과 같은 쓰임'),
jsonb_build_object('number',72,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 고르시오.\n\n<보기> This is a coin <u>found</u> in an ancient tomb.','type','mcq','options',jsonb_build_array(E'She avoided <u>making</u> eye contact.',E'The language <u>spoken</u> here is Swahili.',E'His passion is <u>collecting</u> rare books.',E'<u>Finishing</u> the project took all night.',E'I remember <u>visiting</u> that museum as a child.'),'answer',E'2','explanation',E'② 과거분사(명사 수식) / 나머지는 동명사'),
jsonb_build_object('number',73,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 다른 것을 고르시오.\n\n<보기> She managed to escape from the <u>burning</u> car.','type','mcq','options',jsonb_build_array(E'Who is the <u>crying</u> baby?',E'I saw him <u>crossing</u> the street.',E'John sat <u>reading</u> the magazine.',E'We slept in <u>sleeping</u> bags during the vacation.',E'Jenny was <u>playing</u> the piano when I went to see her.'),'answer',E'4','explanation',E'④ 동명사(용도 — sleeping bag) / 보기와 나머지는 현재분사'),
jsonb_build_object('number',74,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 고르시오.\n\n<보기> <u>Getting</u> a good night''s sleep is important for health.','type','mcq','options',jsonb_build_array(E'I know the boy <u>talking</u> with my teacher.',E'She wanted a doll <u>wearing</u> a red dress.',E'<u>Giving</u> to others makes me happy.',E'My sister is <u>having</u> lunch with her friends.',E'Look at the <u>smiling</u> baby in the stroller.'),'answer',E'3','explanation',E'③ 동명사(주어 역할) / 나머지는 현재분사'),
jsonb_build_object('number',75,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것을 고르시오.\n\n<보기> There is a <u>smoking</u> room on the second floor.','type','mcq','options',jsonb_build_array(E'The bell <u>ringing</u> in the distance told us it was noon.',E'This movie is a comedy about a girl <u>living</u> in Paris.',E'I received a letter <u>offering</u> me the job.',E'A number of suggestions <u>made</u> at the meeting were practical.',E'I need to buy a new pair of <u>running</u> shoes.'),'answer',E'5','explanation',E'⑤ 동명사(용도 — running shoes = 달리기용 신발) / 나머지는 현재분사/과거분사(명사 수식)'),
jsonb_build_object('number',76,'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 다른 것을 고르시오.\n\n<보기> I know the boy <u>talking</u> with my teacher.','type','mcq','options',jsonb_build_array(E'Yunho''s hobby is <u>taking</u> pictures of people.',E'<u>Barking</u> dogs are not always dangerous.',E'Look at the dog <u>playing</u> with a ball.',E'The baby <u>sleeping</u> in the room is my nephew.',E'They are running under the <u>burning</u> sun.'),'answer',E'1','explanation',E'① 동명사(보어 역할) / 보기와 나머지는 현재분사(명사 수식)'));

-- ── q3: Part 8-10 (Q77–Q100) ──
q3 := jsonb_build_array(
jsonb_build_object('number',77,'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Look at the girl dancing with Tim.\n• This is the cell phone making in Korea.\n• These are photos taken from an airplane.\n• Some of the people inviting to the party didn''t come.\n• I read a short story written by O. Henry.\n• The woman driving the car is my mother.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'4','explanation',E'옳은 문장: 1번째(dancing ✓), 3번째(taken ✓), 5번째(written ✓), 6번째(driving ✓) → 4개 / 2번째 making→made(수동), 4번째 inviting→invited(수동)'),
jsonb_build_object('number',78,'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• The barking dog is mine.\n• Do you know the man stood in line?\n• I think bungee jumping was a terrifying experience.\n• We brought all the tools required to fix the bike.\n• She saw a wounded soldier laying on the grass.\n• She is looking at a girl drinking some juice.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'4','explanation',E'옳은 문장: 1번째(barking ✓), 3번째(terrifying ✓), 4번째(required ✓), 6번째(drinking ✓) → 4개 / 2번째 stood→standing(능동), 5번째 laying→lying(자동사)'),
jsonb_build_object('number',79,'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Look at the birds singing in the trees.\n• There''s no one living in the old house.\n• Look at the mountain covering with snow.\n• The man standing over there is my uncle.\n• The police found the money stolen in the robbery.\n• There was a fancy car parked outside the house.','type','mcq','options',jsonb_build_array(E'2개',E'3개',E'4개',E'5개',E'6개'),'answer',E'4','explanation',E'옳은 문장: 1번째(singing ✓), 2번째(living ✓), 4번째(standing ✓), 5번째(stolen ✓), 6번째(parked ✓) → 5개 / 3번째 covering→covered(수동)'),
jsonb_build_object('number',80,'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• These are skates made by his grandfather.\n• This is the picture painting by a famous artist.\n• The boy cried in the room is my brother.\n• They swept the leaves fallen on the ground.\n• She is a famous singer naming Sarah.\n• I want to recommend a book written by Hemingway.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'옳은 문장: 1번째(made ✓), 4번째(fallen ✓), 6번째(written ✓) → 3개 / 2번째 painting→painted(수동), 3번째 cried→crying(능동), 5번째 naming→named(수동)'),
jsonb_build_object('number',81,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The news was surprising to everyone.\nⓑ The man wearing a red cap is my uncle.\nⓒ Mary moved the sleeping cat carefully.\nⓓ Jessica was reading a book written in French.\nⓔ Everything related to his business are based on sports.\nⓕ Many women want to buy bags made in Italy.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓑ, ⓓ, ⓕ',E'ⓑ, ⓓ, ⓔ, ⓕ',E'ⓐ, ⓒ, ⓔ, ⓕ'),'answer',E'3','explanation',E'ⓐⓑⓒⓓⓕ 모두 옳고 ⓔ만 틀림(are→is, Everything은 단수 취급). 선택지 중 옳은 문장으로만 구성된 것은 ③ ⓑ, ⓓ, ⓕ'),
jsonb_build_object('number',82,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The car breaking in the accident was mine.\nⓑ The portrait hanging on the wall was painted in the 1960s.\nⓒ There are some sculptures carved by Donatello.\nⓓ Did you see the town destroyed by bombing?\nⓔ Who is the boy making a speech in front of others?\nⓕ This is a film produced in Japan.','type','mcq','options',jsonb_build_array(E'ⓔ, ⓕ',E'ⓐ, ⓒ, ⓓ, ⓔ',E'ⓑ, ⓓ, ⓔ',E'ⓒ, ⓓ, ⓔ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓔ, ⓕ'),'answer',E'5','explanation',E'ⓑⓒⓓⓔⓕ 모두 옳음 / ⓐ만 breaking→broken(수동)'),
jsonb_build_object('number',83,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The bell ringing in the distance told them it was noon.\nⓑ The first clue was the wide line leading to David''s house.\nⓒ This movie is a comedy about an Indian girl living in Paris.\nⓓ I received a letter offering me the job.\nⓔ A number of suggestions made at the meeting were practical.\nⓕ The waiting room was empty except for a young man sat by the window.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓒ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓔ',E'ⓑ, ⓒ, ⓓ, ⓔ, ⓕ'),'answer',E'2','explanation',E'ⓐⓑⓒⓓⓔ 모두 옳음 / ⓕ만 sat→sitting(능동/진행)'),
jsonb_build_object('number',84,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The taxi taking us to the airport broke down.\nⓑ Somebody named John called while you were out.\nⓒ There were pieces of breaking glass on the floor.\nⓓ The two girls talking to each other are Mira and Sally.\nⓔ Some of the people invited to the party couldn''t come.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓓ, ⓔ',E'ⓑ, ⓒ, ⓓ, ⓔ'),'answer',E'3','explanation',E'ⓑⓓⓔ 옳음 → 선택지 ③ / ⓒ breaking→broken(수동)'),
jsonb_build_object('number',85,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\na. The books ordered online arrived one week later.\nb. Mina likes that man working for a bank.\nc. Don''t pick the flowers planted in the garden.\nd. The people surprising at the noise came outside.','type','mcq','options',jsonb_build_array(E'a',E'a, b',E'a, b, c',E'a, c, d',E'a, b, c, d'),'answer',E'3','explanation',E'a, b, c 옳음 / d surprising→surprised(감정을 느끼는 사람 → 과거분사)'),
jsonb_build_object('number',86,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The man called Dr. K is really good at baseball.\nⓑ The girl likes books written by Edgar Allan Poe.\nⓒ The watches producing in Switzerland are popular.\nⓓ He showed me some photos taken in Turkey.\nⓔ The boy cried in the room is my brother.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓒ',E'ⓑ, ⓔ',E'ⓐ, ⓑ, ⓓ',E'ⓑ, ⓒ, ⓔ',E'ⓒ, ⓓ'),'answer',E'3','explanation',E'ⓐⓑⓓ 옳음 / ⓒ producing→produced(수동), ⓔ cried→crying(능동)'),
jsonb_build_object('number',87,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ Jessica was reading a book written in French.\nⓑ The news were surprising to everyone.\nⓒ Mary moved the sleeping cat carefully.\nⓓ Everything related to his business is based on sports.\nⓔ Many women want to buy bags made in Italy.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓔ',E'ⓑ, ⓒ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓓ, ⓔ'),'answer',E'3','explanation',E'ⓐⓒⓓⓔ 옳음 / ⓑ were→was(news는 불가산 명사, 단수 취급)'),
jsonb_build_object('number',88,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ I picked up the leaves fallen under the tree.\nⓑ I saw a beautiful house covered with snow.\nⓒ Look at that airplane flying in the sky.\nⓓ She memorized a poem wrote by Robert Frost.\nⓔ I had my brother fixed my bike.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓐ, ⓒ',E'ⓐ, ⓑ, ⓒ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓒ, ⓓ'),'answer',E'3','explanation',E'ⓐⓑⓒ 옳음 / ⓓ wrote→written(과거분사), ⓔ fixed→fix(사역동사 have+목적어+동사원형)'),
jsonb_build_object('number',89,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ The people invited to the party are having fun.\nⓑ Have you read short stories wrote by O. Henry?\nⓒ This is a singer who are known to everyone.\nⓓ Look at that bridge which designed by Leon.\nⓔ The picture taking by me won the first prize.','type','mcq','options',jsonb_build_array(E'ⓐ',E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓓ, ⓔ'),'answer',E'1','explanation',E'ⓐ만 옳음 / ⓑ wrote→written, ⓒ are→is(a singer 단수), ⓓ which designed→designed 또는 which was designed, ⓔ taking→taken(수동)'),
jsonb_build_object('number',90,'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ She is a famous swimmer loved by many people.\nⓑ The girl sitting on the bench is reading a book.\nⓒ A number of suggestions made at the meeting are practical.\nⓓ He is a famous designer was born in Sweden.\nⓔ The waiting room was empty except for a man sat by the window.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓒ',E'ⓐ, ⓑ, ⓒ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓒ, ⓓ'),'answer',E'3','explanation',E'ⓐⓑⓒ 옳음 / ⓓ was born→born(분사만 사용), ⓔ sat→sitting(능동/진행)'),
jsonb_build_object('number',91,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n버스를 기다리고 있는 소녀는 나의 친구다.','type','mcq','options',jsonb_build_array(E'The girl wait for the bus is my friend.',E'The girl waited for the bus is my friend.',E'The girl is waiting for the bus is my friend.',E'The girl to wait for the bus is my friend.',E'The girl waiting for the bus is my friend.'),'answer',E'5','explanation',E'현재분사 waiting이 명사 girl을 후치 수식. ①③④ 분사 형태 오류, ② waited는 과거시제로 의미가 다름'),
jsonb_build_object('number',92,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n나는 흰 바지를 입은 소년을 보았다.','type','mcq','options',jsonb_build_array(E'I saw a boy worn white jeans.',E'A boy was wearing white jeans.',E'A boy wearing white jeans saw me.',E'I saw a boy wearing white jeans.',E'I was seeing a boy wear white jeans.'),'answer',E'4','explanation',E'현재분사 wearing이 명사 boy를 후치 수식. ① worn은 수동(소년이 입는 것이므로 능동), ② 주어·의미가 다름, ③ 주어가 바뀜, ⑤ see는 진행형 부적절'),
jsonb_build_object('number',93,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n나는 일본에서 만들어진 카메라를 샀다.','type','mcq','options',jsonb_build_array(E'I bought a camera making in Japan.',E'I bought a camera make in Japan.',E'I bought a camera made in Japan.',E'I bought a camera that makes in Japan.',E'I bought a camera was made in Japan.'),'answer',E'3','explanation',E'과거분사 made — 카메라가 만들어진 것(수동). ① making은 능동, ② 동사원형 불가, ④ that makes는 능동, ⑤ 관계대명사 없이 was 사용 불가'),
jsonb_build_object('number',94,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n피카소가 그린 저 그림들을 보아라.','type','mcq','options',jsonb_build_array(E'Look at those pictures painting by Picasso.',E'Look at those pictures paint by Picasso.',E'Look at those pictures that painting by Picasso.',E'Look at those pictures to paint by Picasso.',E'Look at those pictures painted by Picasso.'),'answer',E'5','explanation',E'과거분사 painted — 그림이 그려진 것(수동). ① painting은 능동, ② 동사원형 불가, ③ that painting 구조 오류, ④ to부정사 부적절'),
jsonb_build_object('number',95,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n바다에서 수영하고 있는 아이들이 많이 있다.','type','mcq','options',jsonb_build_array(E'There are many children swim in the sea.',E'There are many children swam in the sea.',E'There are many children are swimming in the sea.',E'There are many children swimming in the sea.',E'There are many children to swim in the sea.'),'answer',E'4','explanation',E'현재분사 swimming이 children을 후치 수식. ① 동사원형 불가, ② swam은 과거시제, ③ are 중복, ⑤ to부정사 부적절'),
jsonb_build_object('number',96,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n나는 엄마가 요리해 주신 스파게티를 좋아한다.','type','mcq','options',jsonb_build_array(E'I love spaghetti cooking by my mom.',E'I love spaghetti cook by my mom.',E'I love spaghetti cooked by my mom.',E'I love spaghetti that cooking by my mom.',E'I love spaghetti was cooked by my mom.'),'answer',E'3','explanation',E'과거분사 cooked — 스파게티가 요리된 것(수동). ① cooking은 능동, ② 동사원형 불가, ④ that cooking 구조 오류, ⑤ 관계대명사 없이 was 사용 불가'),
jsonb_build_object('number',97,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n바다에서 수영하고 있는 저 여자는 금메달을 땄다.','type','mcq','options',jsonb_build_array(E'That woman swam in the sea won a gold medal.',E'That woman is swimming in the sea won a gold medal.',E'That woman who swimming in the sea won a gold medal.',E'That woman swimming in the sea won a gold medal.',E'That woman swim in the sea won a gold medal.'),'answer',E'4','explanation',E'현재분사 swimming이 woman을 후치 수식. ① swam은 과거동사(동사 중복), ② is swimming은 동사 중복, ③ who swimming 구조 오류(who is swimming 필요), ⑤ 동사원형 불가'),
jsonb_build_object('number',98,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n나는 한국어를 배우는 많은 미국인 학생들을 안다.','type','mcq','options',jsonb_build_array(E'I know many American students learn Korean.',E'I know many American students learned Korean.',E'I know many American students are learning Korean.',E'I know many American students to learn Korean.',E'I know many American students learning Korean.'),'answer',E'5','explanation',E'현재분사 learning이 students를 후치 수식. ①②③은 분사 수식이 아닌 절 구조(that 생략)로 해석 가능하나 분사구문이 적절, ④ to부정사 부적절'),
jsonb_build_object('number',99,'question',E'다음 우리말을 바르게 영작한 것을 고르시오.\n\n야구공으로 인해 깨진 창문을 보아라.','type','mcq','options',jsonb_build_array(E'Look at the window breaking by a baseball.',E'Look at the window break by a baseball.',E'Look at the window broken by a baseball.',E'Look at the window that breaking by a baseball.',E'Look at the window was broken by a baseball.'),'answer',E'3','explanation',E'과거분사 broken — 창문이 깨진 것(수동). ① breaking은 능동, ② 동사원형 불가, ④ that breaking 구조 오류, ⑤ 관계대명사 없이 was 사용 불가'),
jsonb_build_object('number',100,'question',E'다음 두 문장을 한 문장으로 바꿀 때 적절하지 않은 것을 고르시오.','type','mcq','options',jsonb_build_array(E'Harry drew a cat. + It was eating a fish.\n→ Harry drew a cat eating a fish.',E'I know the man. + He is wearing a blue jacket.\n→ I know the man wearing a blue jacket.',E'I don''t know the boy. + He''s coming toward us.\n→ I don''t know the boy coming toward us.',E'She couldn''t avoid the ball. + It was flying toward her.\n→ She couldn''t avoid the ball flying toward her.',E'That woman won a gold medal. + She is swimming in the sea.\n→ That woman won a gold medal swimming in the sea.'),'answer',E'5','explanation',E'⑤ 분사구 swimming in the sea가 gold medal을 수식하는 것처럼 보여 의미가 모호해짐. That woman swimming in the sea won a gold medal.이 올바른 어순')
);

a := jsonb_build_array();

INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
VALUES (
  E'명사를 꾸며주는 분사 Step 2',
  E'명사를 꾸며주는 분사',
  q1 || q2 || q3,
  a,
  'problem',
  'interactive'
);

END $$;
