DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  -- 기존 템플릿 삭제 (중복 방지)
  DELETE FROM naesin_problem_sheets
  WHERE title = '수여동사 Step1' AND is_template = true;

  q := jsonb_build_array(
    -- 유형 A: 목적어 찾기 (1-10)
    jsonb_build_object('number',1,'question','[직접목적어를 찾으시오] Her grandmother made us a birthday cake.','answer','a birthday cake'),
    jsonb_build_object('number',2,'question','[간접목적어를 찾으시오] She lent me her pencil.','answer','me'),
    jsonb_build_object('number',3,'question','[직접목적어를 찾으시오] Can you bring me some fresh fruit?','answer','some fresh fruit'),
    jsonb_build_object('number',4,'question','[간접목적어를 찾으시오] Ms. Kim reads us a story every day.','answer','us'),
    jsonb_build_object('number',5,'question','[직접목적어를 찾으시오] He sold a painting to his neighbor.','answer','a painting'),
    jsonb_build_object('number',6,'question','[간접목적어를 찾으시오] I will offer you kind and honest advice.','answer','you'),
    jsonb_build_object('number',7,'question','[직접목적어를 찾으시오] It brings you and your classmates joy.','answer','joy'),
    jsonb_build_object('number',8,'question','[간접목적어를 찾으시오] My uncle got me a new bike for my birthday.','answer','me'),
    jsonb_build_object('number',9,'question','[직접목적어를 찾으시오] The chef prepared a wonderful meal for the guests.','answer','a wonderful meal'),
    jsonb_build_object('number',10,'question','[간접목적어를 찾으시오] I am going to lend my favorite book to each one of you tomorrow.','answer','each one of you'),
    -- 유형 B: 빈칸 채우기 (11-20)
    jsonb_build_object('number',11,'question','[빈칸 채우기: make / bring / lend] My grandmother ___ us delicious pancakes every Sunday.','answer','makes'),
    jsonb_build_object('number',12,'question','[빈칸 채우기: make / bring / lend] He will ___ me the documents tomorrow.','answer','bring'),
    jsonb_build_object('number',13,'question','[빈칸 채우기: make / bring / lend] She ___ her classmate a pencil yesterday.','answer','lent'),
    jsonb_build_object('number',14,'question','[빈칸 채우기: offer / read / sell] The shop will ___ you a better price.','answer','offer'),
    jsonb_build_object('number',15,'question','[빈칸 채우기: offer / read / sell] My teacher ___ us an interesting story every Friday.','answer','reads'),
    jsonb_build_object('number',16,'question','[빈칸 채우기: offer / read / sell] He ___ his friend an old laptop last week.','answer','sold'),
    jsonb_build_object('number',17,'question','[빈칸 채우기: order / throw / cook / save / find / get] She always ___ us pizza on Friday nights.','answer','orders'),
    jsonb_build_object('number',18,'question','[빈칸 채우기: order / throw / cook / save / find / get] The player will ___ you the ball.','answer','throw'),
    jsonb_build_object('number',19,'question','[빈칸 채우기: order / throw / cook / save / find / get] He ___ his family a big dinner yesterday.','answer','cooked'),
    jsonb_build_object('number',20,'question','[빈칸 채우기: order / throw / cook / save / find / get] I will ___ my friend a nice present for her birthday.','answer','get'),
    -- 유형 C: 구조 바꾸기 (21-33)
    jsonb_build_object('number',21,'question','[문장 구조 바꾸기] Let me cook some pasta for you.','answer','Let me cook you some pasta.'),
    jsonb_build_object('number',22,'question','[문장 구조 바꾸기] Would you bring me a bottle of water?','answer','Would you bring a bottle of water to me?'),
    jsonb_build_object('number',23,'question','[문장 구조 바꾸기] Could you pass the salt to me?','answer','Could you pass me the salt?'),
    jsonb_build_object('number',24,'question','[문장 구조 바꾸기] She asked a favor of me.','answer','She asked me a favor.'),
    jsonb_build_object('number',25,'question','[문장 구조 바꾸기] She teaches children music.','answer','She teaches music to children.'),
    jsonb_build_object('number',26,'question','[문장 구조 바꾸기] I handed the letter to Ms. White.','answer','I handed Ms. White the letter.'),
    jsonb_build_object('number',27,'question','[문장 구조 바꾸기] Dad built me a bookshelf.','answer','Dad built a bookshelf for me.'),
    jsonb_build_object('number',28,'question','[문장 구조 바꾸기] Show your teacher the homework.','answer','Show the homework to your teacher.'),
    jsonb_build_object('number',29,'question','[문장 구조 바꾸기] He asked a difficult question of the students.','answer','He asked the students a difficult question.'),
    jsonb_build_object('number',30,'question','[문장 구조 바꾸기] I lent my friend some money.','answer','I lent some money to my friend.'),
    jsonb_build_object('number',31,'question','[문장 구조 바꾸기] He bought us some snacks.','answer','He bought some snacks for us.'),
    jsonb_build_object('number',32,'question','[문장 구조 바꾸기] My teacher gave a sticker to me.','answer','My teacher gave me a sticker.'),
    jsonb_build_object('number',33,'question','[문장 구조 바꾸기] She found a nice hat for me.','answer','She found me a nice hat.'),
    -- 유형 D: 오류 수정 (34-53)
    jsonb_build_object('number',34,'question','[오류를 고치시오] She told the news us.','answer','She told us the news.'),
    jsonb_build_object('number',35,'question','[오류를 고치시오] He gave a book for his friend.','answer','He gave a book to his friend.'),
    jsonb_build_object('number',36,'question','[오류를 고치시오] My teacher explained the lesson me.','answer','My teacher explained the lesson to me.'),
    jsonb_build_object('number',37,'question','[오류를 고치시오] She passed the ball for her teammate.','answer','She passed the ball to her teammate.'),
    jsonb_build_object('number',38,'question','[오류를 고치시오] I will pack the gifts and bring you them.','answer','I will pack the gifts and bring them to you.'),
    jsonb_build_object('number',39,'question','[오류를 고치시오] Her dad cooked a special dinner to her.','answer','Her dad cooked a special dinner for her.'),
    jsonb_build_object('number',40,'question','[오류를 고치시오] Jenny left her mom to a note.','answer','Jenny left her mom a note.'),
    jsonb_build_object('number',41,'question','[오류를 고치시오] Mike threw his friend to the ball.','answer','Mike threw the ball to his friend.'),
    jsonb_build_object('number',42,'question','[오류를 고치시오] She showed me it.','answer','She showed it to me.'),
    jsonb_build_object('number',43,'question','[오류를 고치시오] She showed her photos us.','answer','She showed us her photos.'),
    jsonb_build_object('number',44,'question','[오류를 고치시오] He bought a nice dress to his daughter.','answer','He bought a nice dress for his daughter.'),
    jsonb_build_object('number',45,'question','[오류를 고치시오] My brother wrote a letter for me.','answer','My brother wrote a letter to me.'),
    jsonb_build_object('number',46,'question','[오류를 고치시오] The waiter brought the menu us.','answer','The waiter brought us the menu.'),
    jsonb_build_object('number',47,'question','[오류를 고치시오] She will find a good seat to you.','answer','She will find a good seat for you.'),
    jsonb_build_object('number',48,'question','[오류를 고치시오] I gave her it.','answer','I gave it to her.'),
    jsonb_build_object('number',49,'question','[오류를 고치시오] He offered his seat for the old lady.','answer','He offered his seat to the old lady.'),
    jsonb_build_object('number',50,'question','[오류를 고치시오] Please hand it me.','answer','Please hand it to me.'),
    jsonb_build_object('number',51,'question','[오류를 고치시오] She saved her brother to some cake.','answer','She saved her brother some cake.'),
    jsonb_build_object('number',52,'question','[오류를 고치시오] He threw the ball for his teammate.','answer','He threw the ball to his teammate.'),
    jsonb_build_object('number',53,'question','[오류를 고치시오] My aunt prepared a birthday party to us.','answer','My aunt prepared a birthday party for us.'),
    -- 유형 E: 배열하시오 (54-68)
    jsonb_build_object('number',54,'question','[배열하시오] 그 소년은 나에게 편지를 보냈다. (a / the / sent / to / boy / letter / me)','answer','The boy sent a letter to me.'),
    jsonb_build_object('number',55,'question','[배열하시오] 나는 그에게 이 책을 사주었다. (this / I / book / for / bought / him)','answer','I bought this book for him.'),
    jsonb_build_object('number',56,'question','[배열하시오] 그녀는 우리에게 그 지도를 보여주었다. (map / she / the / to / us / showed)','answer','She showed the map to us.'),
    jsonb_build_object('number',57,'question','[배열하시오] 그는 그녀에게 그 메시지를 전해주었다. (message / her / told / the / he)','answer','He told her the message.'),
    jsonb_build_object('number',58,'question','[배열하시오] 그 여자는 우리에게 맛있는 케이크를 만들어주었다. (delicious / cake / the / made / woman / a / us)','answer','The woman made us a delicious cake.'),
    jsonb_build_object('number',59,'question','[배열하시오] 톰은 자기의 노트를 나에게 빌려주었다. (notebook / Tom / lent / to / me / his)','answer','Tom lent his notebook to me.'),
    jsonb_build_object('number',60,'question','[배열하시오] 어머니는 나를 위해 점심을 요리해주셨다. (my / lunch / cooked / mother / for / me)','answer','My mother cooked lunch for me.'),
    jsonb_build_object('number',61,'question','[배열하시오] 제인은 그녀의 오빠에게 멋진 선물을 찾아주었다. (her brother / found / Jane / for / a nice gift)','answer','Jane found a nice gift for her brother.'),
    jsonb_build_object('number',62,'question','[배열하시오] 선생님은 우리에게 영어를 가르쳐주신다. (our / English / teaches / teacher / us)','answer','Our teacher teaches us English.'),
    jsonb_build_object('number',63,'question','[배열하시오] 그녀는 나에게 큰 부탁을 했다. (big / a / she / of / asked / me / favor)','answer','She asked a big favor of me.'),
    jsonb_build_object('number',64,'question','[배열하시오] 그는 나에게 어려운 질문을 했다. (difficult / a / he / of / asked / me / question)','answer','He asked a difficult question of me.'),
    jsonb_build_object('number',65,'question','[배열하시오] 아버지는 나에게 자전거를 사주셨다. (my / a / father / bicycle / me / bought)','answer','My father bought me a bicycle.'),
    jsonb_build_object('number',66,'question','[배열하시오] 그녀는 손님들에게 차를 대접했다. (served / the / she / tea / guests)','answer','She served the guests tea.'),
    jsonb_build_object('number',67,'question','[배열하시오] 그 소녀는 나에게 예쁜 카드를 만들어주었다. (pretty / card / the / made / girl / a / me)','answer','The girl made me a pretty card.'),
    jsonb_build_object('number',68,'question','[배열하시오] 존은 그의 여동생에게 인형을 가져다주었다. (his sister / brought / John / for / a doll)','answer','John brought a doll for his sister.')
  );

  a := jsonb_build_array(
    'a birthday cake','me','some fresh fruit','us',
    'a painting','you','joy','me',
    'a wonderful meal','each one of you',
    'makes','bring','lent','offer','reads','sold',
    'orders','throw','cooked','get',
    'Let me cook you some pasta.',
    'Would you bring a bottle of water to me?',
    'Could you pass me the salt?',
    'She asked me a favor.',
    'She teaches music to children.',
    'I handed Ms. White the letter.',
    'Dad built a bookshelf for me.',
    'Show the homework to your teacher.',
    'He asked the students a difficult question.',
    'I lent some money to my friend.',
    'He bought some snacks for us.',
    'My teacher gave me a sticker.',
    'She found me a nice hat.',
    'She told us the news.',
    'He gave a book to his friend.',
    'My teacher explained the lesson to me.',
    'She passed the ball to her teammate.',
    'I will pack the gifts and bring them to you.',
    'Her dad cooked a special dinner for her.',
    'Jenny left her mom a note.',
    'Mike threw the ball to his friend.',
    'She showed it to me.',
    'She showed us her photos.',
    'He bought a nice dress for his daughter.',
    'My brother wrote a letter to me.',
    'The waiter brought us the menu.',
    'She will find a good seat for you.',
    'I gave it to her.',
    'He offered his seat to the old lady.',
    'Please hand it to me.',
    'She saved her brother some cake.',
    'He threw the ball to his teammate.',
    'My aunt prepared a birthday party for us.',
    'The boy sent a letter to me.',
    'I bought this book for him.',
    'She showed the map to us.',
    'He told her the message.',
    'The woman made us a delicious cake.',
    'Tom lent his notebook to me.',
    'My mother cooked lunch for me.',
    'Jane found a nice gift for her brother.',
    'Our teacher teaches us English.',
    'She asked a big favor of me.',
    'He asked a difficult question of me.',
    'My father bought me a bicycle.',
    'She served the guests tea.',
    'The girl made me a pretty card.',
    'John brought a doll for his sister.'
  );

  INSERT INTO naesin_problem_sheets (
    unit_id, title, mode, questions, answer_key,
    category, is_template, template_topic, sort_order
  ) VALUES (
    (SELECT id FROM naesin_units LIMIT 1),
    '수여동사 Step1', 'interactive', q, a,
    'problem', true, '수여동사', 0
  );
END $$;
