DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  -- 기존 템플릿 삭제 (중복 방지)
  DELETE FROM naesin_problem_sheets
  WHERE title = '주격관계대명사 Step1' AND is_template = true;

  q := jsonb_build_array(
    -- 유형 1: who / which / that 고르기 (1-20)
    jsonb_build_object('number',1,'question','[알맞은 것을 고르시오] The man (who / which) lives next door is a doctor.','answer','who'),
    jsonb_build_object('number',2,'question','[알맞은 것을 고르시오] I bought a phone (who / which) has a great camera.','answer','which'),
    jsonb_build_object('number',3,'question','[알맞은 것을 고르시오] She is the teacher (which / who) taught me English.','answer','who'),
    jsonb_build_object('number',4,'question','[알맞은 것을 고르시오] The movie (who / that) won the award was amazing.','answer','that'),
    jsonb_build_object('number',5,'question','[알맞은 것을 고르시오] Do you know the boy (which / who) is standing over there?','answer','who'),
    jsonb_build_object('number',6,'question','[알맞은 것을 고르시오] The cat (who / which) is sleeping on the sofa is mine.','answer','which'),
    jsonb_build_object('number',7,'question','[알맞은 것을 고르시오] I have a friend (which / who) speaks three languages.','answer','who'),
    jsonb_build_object('number',8,'question','[알맞은 것을 고르시오] The tree (who / which) stands in front of our house is very old.','answer','which'),
    jsonb_build_object('number',9,'question','[알맞은 것을 고르시오] She married a man (which / who) works at a hospital.','answer','who'),
    jsonb_build_object('number',10,'question','[알맞은 것을 고르시오] The bus (who / which) goes to the airport leaves at 9.','answer','which'),
    jsonb_build_object('number',11,'question','[알맞은 것을 고르시오] Anyone (which / who) wants to join can sign up here.','answer','who'),
    jsonb_build_object('number',12,'question','[알맞은 것을 고르시오] The computer (who / that) I use every day is very slow.','answer','that'),
    jsonb_build_object('number',13,'question','[알맞은 것을 고르시오] The woman (which / who) is wearing a red dress is my mom.','answer','who'),
    jsonb_build_object('number',14,'question','[알맞은 것을 고르시오] He has a parrot (who / which) can say "hello."','answer','which'),
    jsonb_build_object('number',15,'question','[알맞은 것을 고르시오] The students (which / who) study hard will pass the exam.','answer','who'),
    jsonb_build_object('number',16,'question','[알맞은 것을 고르시오] The building (who / which) is next to the park is a library.','answer','which'),
    jsonb_build_object('number',17,'question','[알맞은 것을 고르시오] I met a girl (which / who) wants to be a singer.','answer','who'),
    jsonb_build_object('number',18,'question','[알맞은 것을 고르시오] The flowers (who / which) bloom in spring are beautiful.','answer','which'),
    jsonb_build_object('number',19,'question','[알맞은 것을 고르시오] People (which / who) exercise regularly live longer.','answer','who'),
    jsonb_build_object('number',20,'question','[알맞은 것을 고르시오] The train (who / which) arrived late was from Busan.','answer','which'),
    -- 유형 2: 두 문장 합치기 (21-40)
    jsonb_build_object('number',21,'question','[관계대명사를 사용하여 문장을 합치시오] I met a woman. She speaks five languages.','answer','I met a woman who speaks five languages.'),
    jsonb_build_object('number',22,'question','[관계대명사를 사용하여 문장을 합치시오] He bought a car. It uses very little gas.','answer','He bought a car which uses very little gas.'),
    jsonb_build_object('number',23,'question','[관계대명사를 사용하여 문장을 합치시오] This is the best book. It was published this year.','answer','This is the best book that was published this year.'),
    jsonb_build_object('number',24,'question','[관계대명사를 사용하여 문장을 합치시오] The boy is my classmate. He is playing the guitar.','answer','The boy who is playing the guitar is my classmate.'),
    jsonb_build_object('number',25,'question','[관계대명사를 사용하여 문장을 합치시오] She has a cat. It loves to sleep all day.','answer','She has a cat which loves to sleep all day.'),
    jsonb_build_object('number',26,'question','[관계대명사를 사용하여 문장을 합치시오] He was the first student. He finished the test.','answer','He was the first student that finished the test.'),
    jsonb_build_object('number',27,'question','[관계대명사를 사용하여 문장을 합치시오] Do you know the girl? She won the singing contest.','answer','Do you know the girl who won the singing contest?'),
    jsonb_build_object('number',28,'question','[관계대명사를 사용하여 문장을 합치시오] I read a book. It was very interesting.','answer','I read a book which was very interesting.'),
    jsonb_build_object('number',29,'question','[관계대명사를 사용하여 문장을 합치시오] The teacher is very kind. She teaches us math.','answer','The teacher who teaches us math is very kind.'),
    jsonb_build_object('number',30,'question','[관계대명사를 사용하여 문장을 합치시오] She is the only person. She knows the answer.','answer','She is the only person that knows the answer.'),
    jsonb_build_object('number',31,'question','[관계대명사를 사용하여 문장을 합치시오] Look at the house. It has a red roof.','answer','Look at the house which has a red roof.'),
    jsonb_build_object('number',32,'question','[관계대명사를 사용하여 문장을 합치시오] The doctor was helpful. He treated my grandmother.','answer','The doctor who treated my grandmother was helpful.'),
    jsonb_build_object('number',33,'question','[관계대명사를 사용하여 문장을 합치시오] I found a bag. It was lying on the bench.','answer','I found a bag which was lying on the bench.'),
    jsonb_build_object('number',34,'question','[관계대명사를 사용하여 문장을 합치시오] Look at the girl and her cat. They are sitting on the bench.','answer','Look at the girl and her cat that are sitting on the bench.'),
    jsonb_build_object('number',35,'question','[관계대명사를 사용하여 문장을 합치시오] The woman is my aunt. She is wearing glasses.','answer','The woman who is wearing glasses is my aunt.'),
    jsonb_build_object('number',36,'question','[관계대명사를 사용하여 문장을 합치시오] He has a robot. It can clean the house.','answer','He has a robot which can clean the house.'),
    jsonb_build_object('number',37,'question','[관계대명사를 사용하여 문장을 합치시오] There is a student. He always arrives early.','answer','There is a student who always arrives early.'),
    jsonb_build_object('number',38,'question','[관계대명사를 사용하여 문장을 합치시오] This is the most exciting game. It has ever been played here.','answer','This is the most exciting game that has ever been played here.'),
    jsonb_build_object('number',39,'question','[관계대명사를 사용하여 문장을 합치시오] The movie was exciting. It came out last week.','answer','The movie which came out last week was exciting.'),
    jsonb_build_object('number',40,'question','[관계대명사를 사용하여 문장을 합치시오] The man is a famous chef. He opened a new restaurant.','answer','The man who opened a new restaurant is a famous chef.'),
    -- 유형 3: 한→영 배열 (41-55)
    jsonb_build_object('number',41,'question','[배열하시오] 그녀는 서울에 사는 의사이다. (Seoul, a doctor, who, she, live, in, is)','answer','She is a doctor who lives in Seoul.'),
    jsonb_build_object('number',42,'question','[배열하시오] 지붕이 빨간 그 집은 우리 것이다. (the house, a red roof, which, have, is, ours)','answer','The house which has a red roof is ours.'),
    jsonb_build_object('number',43,'question','[배열하시오] 세 개의 언어를 말하는 소녀가 내 친구이다. (three languages, the girl, who, speak, is, my friend)','answer','The girl who speaks three languages is my friend.'),
    jsonb_build_object('number',44,'question','[배열하시오] 하늘을 나는 새는 독수리이다. (the bird, in the sky, which, fly, is, an eagle)','answer','The bird which is flying in the sky is an eagle.'),
    jsonb_build_object('number',45,'question','[배열하시오] 나는 피아노를 잘 치는 소년을 안다. (well, the piano, a boy, who, play, I, know)','answer','I know a boy who plays the piano well.'),
    jsonb_build_object('number',46,'question','[배열하시오] 탁자 위에 있는 그 컵은 내 것이다. (on the table, the cup, which, is, is, mine)','answer','The cup which is on the table is mine.'),
    jsonb_build_object('number',47,'question','[배열하시오] 매일 조깅하는 그 남자는 나의 아버지이다. (every day, the man, who, jog, is, my father)','answer','The man who jogs every day is my father.'),
    jsonb_build_object('number',48,'question','[배열하시오] 정원에서 자라는 그 꽃들은 아름답다. (in the garden, the flowers, which, grow, are, beautiful)','answer','The flowers which grow in the garden are beautiful.'),
    jsonb_build_object('number',49,'question','[배열하시오] 안경을 쓴 그 선생님이 우리에게 수학을 가르치신다. (glasses, the teacher, who, wear, teach, us, math)','answer','The teacher who wears glasses teaches us math.'),
    jsonb_build_object('number',50,'question','[배열하시오] 네 옆에 앉아 있는 그 소녀는 누구니? (next to you, the girl, who, is sitting, who, is)','answer','Who is the girl who is sitting next to you?'),
    jsonb_build_object('number',51,'question','[배열하시오] 영어를 가르치는 그 여자는 미국에서 왔다. (English, the woman, who, teach, is, from America)','answer','The woman who teaches English is from America.'),
    jsonb_build_object('number',52,'question','[배열하시오] 큰 귀를 가진 그 동물은 코끼리이다. (big ears, the animal, which, have, is, an elephant)','answer','The animal which has big ears is an elephant.'),
    jsonb_build_object('number',53,'question','[배열하시오] 나는 병원에서 일하는 여자를 만났다. (a hospital, a woman, who, work, in, I, met)','answer','I met a woman who works in a hospital.'),
    jsonb_build_object('number',54,'question','[배열하시오] 옥상에서 짖고 있는 그 개는 이웃의 것이다. (on the rooftop, the dog, which, is barking, is, my neighbor''s)','answer','The dog which is barking on the rooftop is my neighbor''s.'),
    jsonb_build_object('number',55,'question','[배열하시오] 항상 다른 사람을 도와주는 그 소년은 착하다. (always, other people, the boy, who, help, is, kind)','answer','The boy who always helps other people is kind.'),
    -- 유형 4: 영작 (56-70)
    jsonb_build_object('number',56,'question','[영작하시오] 거리에서 춤을 추고 있는 소년을 봐라. (look, dance, on the street)','answer','Look at the boy who is dancing on the street.'),
    jsonb_build_object('number',57,'question','[영작하시오] Eric은 캐나다 출신의 소년이다. (come)','answer','Eric is a boy who comes from Canada.'),
    jsonb_build_object('number',58,'question','[영작하시오] 시청에서 출발하는 버스는 기차역으로 간다. (start, from, City Hall, go)','answer','The bus which starts from City Hall goes to the train station.'),
    jsonb_build_object('number',59,'question','[영작하시오] 그 나무 아래에서 책을 읽고 있는 저 소녀는 나의 여동생이다. (read, under, little)','answer','The little girl who is reading a book under the tree is my sister.'),
    jsonb_build_object('number',60,'question','[영작하시오] 같이 사는 그 아이와 그 개는 좋은 친구이다. (child, the dog, together, friends)','answer','The child and the dog that live together are good friends.'),
    jsonb_build_object('number',61,'question','[영작하시오] 나는 프랑스어를 말하는 선생님이 있다. (speak, French, teacher)','answer','I have a teacher who speaks French.'),
    jsonb_build_object('number',62,'question','[영작하시오] 빨리 달리는 그 차는 위험하다. (fast, run, dangerous)','answer','The car which runs fast is dangerous.'),
    jsonb_build_object('number',63,'question','[영작하시오] 노래를 부르고 있는 그 여자는 유명한 가수이다. (sing, famous, singer)','answer','The woman who is singing is a famous singer.'),
    jsonb_build_object('number',64,'question','[영작하시오] 나는 매일 아침 우유를 배달하는 남자를 안다. (deliver, milk, every morning)','answer','I know the man who delivers milk every morning.'),
    jsonb_build_object('number',65,'question','[영작하시오] 지붕 위에 앉아 있는 그 고양이는 내 것이다. (sit, on the roof, mine)','answer','The cat which is sitting on the roof is mine.'),
    jsonb_build_object('number',66,'question','[영작하시오] 이 마을에 사는 사람들은 친절하다. (live, this town, kind)','answer','The people who live in this town are kind.'),
    jsonb_build_object('number',67,'question','[영작하시오] 정원에 피어 있는 그 꽃들은 아름답다. (bloom, in the garden, beautiful)','answer','The flowers which bloom in the garden are beautiful.'),
    jsonb_build_object('number',68,'question','[영작하시오] 나를 도와준 그 소녀에게 감사했다. (help, thank, girl)','answer','I thanked the girl who helped me.'),
    jsonb_build_object('number',69,'question','[영작하시오] 강 옆에 서 있는 그 건물은 도서관이다. (stand, by the river, library)','answer','The building which stands by the river is a library.'),
    jsonb_build_object('number',70,'question','[영작하시오] 항상 웃는 그 아이는 인기가 많다. (always, smile, popular)','answer','The child who always smiles is popular.')
  );

  a := jsonb_build_array(
    'who','which','who','that','who',
    'which','who','which','who','which',
    'who','that','who','which','who',
    'which','who','which','who','which',
    'I met a woman who speaks five languages.',
    'He bought a car which uses very little gas.',
    'This is the best book that was published this year.',
    'The boy who is playing the guitar is my classmate.',
    'She has a cat which loves to sleep all day.',
    'He was the first student that finished the test.',
    'Do you know the girl who won the singing contest?',
    'I read a book which was very interesting.',
    'The teacher who teaches us math is very kind.',
    'She is the only person that knows the answer.',
    'Look at the house which has a red roof.',
    'The doctor who treated my grandmother was helpful.',
    'I found a bag which was lying on the bench.',
    'Look at the girl and her cat that are sitting on the bench.',
    'The woman who is wearing glasses is my aunt.',
    'He has a robot which can clean the house.',
    'There is a student who always arrives early.',
    'This is the most exciting game that has ever been played here.',
    'The movie which came out last week was exciting.',
    'The man who opened a new restaurant is a famous chef.',
    'She is a doctor who lives in Seoul.',
    'The house which has a red roof is ours.',
    'The girl who speaks three languages is my friend.',
    'The bird which is flying in the sky is an eagle.',
    'I know a boy who plays the piano well.',
    'The cup which is on the table is mine.',
    'The man who jogs every day is my father.',
    'The flowers which grow in the garden are beautiful.',
    'The teacher who wears glasses teaches us math.',
    'Who is the girl who is sitting next to you?',
    'The woman who teaches English is from America.',
    'The animal which has big ears is an elephant.',
    'I met a woman who works in a hospital.',
    'The dog which is barking on the rooftop is my neighbor''s.',
    'The boy who always helps other people is kind.',
    'Look at the boy who is dancing on the street.',
    'Eric is a boy who comes from Canada.',
    'The bus which starts from City Hall goes to the train station.',
    'The little girl who is reading a book under the tree is my sister.',
    'The child and the dog that live together are good friends.',
    'I have a teacher who speaks French.',
    'The car which runs fast is dangerous.',
    'The woman who is singing is a famous singer.',
    'I know the man who delivers milk every morning.',
    'The cat which is sitting on the roof is mine.',
    'The people who live in this town are kind.',
    'The flowers which bloom in the garden are beautiful.',
    'I thanked the girl who helped me.',
    'The building which stands by the river is a library.',
    'The child who always smiles is popular.'
  );

  INSERT INTO naesin_problem_sheets (
    unit_id, title, mode, questions, answer_key,
    category, is_template, template_topic, sort_order
  ) VALUES (
    (SELECT id FROM naesin_units LIMIT 1),
    '주격관계대명사 Step1', 'interactive', q, a,
    'problem', true, '주격관계대명사', 0
  );
END $$;
