-- 최상급 Step1 템플릿 (76문항)
-- Part 1: 객관식 (15) → Part 2: 최상급+전치사 변환 (10) → Part 3: 정보 활용 (7)
-- → Part 4: 원급→비교급/최상급 (18) → Part 5: 보기 선택+최상급 (14) → Part 6: 영작 (12)

INSERT INTO naesin_templates (title, template_topic, questions, answer_key)
VALUES (
  '최상급 Step1',
  '최상급',
  '[
    {"number":1,"question":"[알맞은 것을 고르시오]\n\nI believe autumn is ___ season of the year.","options":["the loveliest","lovelier","very lovely"],"answer":"1"},
    {"number":2,"question":"[알맞은 것을 고르시오]\n\nEmma is ___ piano player in our town.","options":["the best","better"],"answer":"1"},
    {"number":3,"question":"[알맞은 것을 고르시오]\n\nCan you tell me ___ tower in the city?","options":["the tallest","so tall"],"answer":"1"},
    {"number":4,"question":"[알맞은 것을 고르시오]\n\nBasketball is ___ than volleyball.","options":["more thrilling","the most thrilling"],"answer":"1"},
    {"number":5,"question":"[알맞은 것을 고르시오]\n\nVegetables are ___ than candy.","options":["more nutritious","the most nutritious"],"answer":"1"},
    {"number":6,"question":"[알맞은 것을 고르시오]\n\nLast summer was ___ summer in this region.","options":["hotter","the hottest"],"answer":"2"},
    {"number":7,"question":"[알맞은 것을 고르시오]\n\nTrains are ___ than a bus.","options":["the fastest","faster"],"answer":"2"},
    {"number":8,"question":"[알맞은 것을 고르시오]\n\nMy brother is ___ person in our household.","options":["the youngest","younger"],"answer":"1"},
    {"number":9,"question":"[알맞은 것을 고르시오]\n\nScience is ___ subject of all.","options":["the most fascinating","more fascinating than"],"answer":"1"},
    {"number":10,"question":"[알맞은 것을 고르시오]\n\nAn elephant is ___ a deer.","options":["the heaviest","heavier than"],"answer":"2"},
    {"number":11,"question":"[알맞은 것을 고르시오]\n\nIt is generally ___ in autumn than in summer.","options":["cooler","the coolest"],"answer":"1"},
    {"number":12,"question":"[알맞은 것을 고르시오]\n\nSoccer is ___ tennis in our school.","options":["the most popular","more popular than"],"answer":"2"},
    {"number":13,"question":"[알맞은 것을 고르시오]\n\nWho is ___ student you know?","options":["more creative than","the most creative"],"answer":"2"},
    {"number":14,"question":"[알맞은 것을 고르시오]\n\nJenny is ___ girl in our group.","options":["more cheerful than","the most cheerful"],"answer":"2"},
    {"number":15,"question":"[알맞은 것을 고르시오]\n\nClean water is ___ resource for all living things.","options":["the most essential","more essential than"],"answer":"1"},

    {"number":16,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\ne.g.) Judy is a very pretty girl.\nShe is the prettiest girl in our class.\n\nIt''s a very wide road.\nIt''s _______________ our town.","answer":"the widest road in"},
    {"number":17,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nSophie is a very bright student.\nShe is _______________ our school.","answer":"the brightest student in"},
    {"number":18,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nTokyo is a very crowded city.\nIt is _______________ Japan.","answer":"the most crowded city in"},
    {"number":19,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nThis library is very old.\nIt''s _______________ the neighborhood.","answer":"the oldest library in"},
    {"number":20,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nRachel is very kind.\nShe is _______________ all the students in the class.","answer":"the kindest of"},
    {"number":21,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nHe is a very talented actor.\nHe is _______________ our country.","answer":"the most talented actor in"},
    {"number":22,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nIt was a very warm night.\nIt was _______________ the month.","answer":"the warmest night of"},
    {"number":23,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nI have very thick hair.\nMy hair is _______________ my family.","answer":"the thickest in"},
    {"number":24,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nThey are very lazy workers.\nThey are _______________ our office.","answer":"the laziest workers in"},
    {"number":25,"question":"[최상급 + 전치사를 사용하여 문장을 완성하시오]\n\nIt''s a very famous painting.\nIt is _______________ the museum.","answer":"the most famous painting in"},

    {"number":26,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\ne.g.) The blue whale is [bold]heavier[/bold] than any other animal.\nThe blue whale is [bold]the heaviest[/bold] animal on Earth.\n\nThe cheetah can run ___ than any other land animal.\nThe cheetah is ___ land animal on Earth.","answer":"faster, the fastest"},
    {"number":27,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe elephant is ___ than the cheetah.\nThe elephant is ___ animal on land.","answer":"stronger, the strongest"},
    {"number":28,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe giraffe is ___ than all the other animals.\nThe giraffe is ___ animal on Earth.","answer":"taller, the tallest"},
    {"number":29,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe tortoise is ___ than the cheetah.\nThe tortoise is ___ animal in the group.","answer":"slower, the slowest"},
    {"number":30,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe hummingbird is ___ than the elephant.\nThe hummingbird is ___ animal in the group.","answer":"smaller, the smallest"},
    {"number":31,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe Arctic fox lives in ___ places than the elephant.\nThe Arctic fox lives in ___ places of all these animals.","answer":"colder, the coldest"},
    {"number":32,"question":"[다음 정보를 읽고 빈칸을 채우시오]\n\n<Information>\n• The blue whale is very heavy (up to 150 tons).\n• The cheetah is very fast (120 km/h).\n• The elephant is very strong.\n• The giraffe is very tall (up to 6 m).\n• The tortoise is very slow but lives very long.\n• The hummingbird is very small and light.\n• The Arctic fox survives in very cold places.\n\nThe tortoise lives a ___ life than the cheetah.\nThe tortoise lives ___ life of all these animals.","answer":"longer, the longest"},

    {"number":33,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nYou''re not very strong. Your sister is ___ (strong) than you.","answer":"stronger"},
    {"number":34,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nIt is five miles from ___ (near) village.","answer":"the nearest"},
    {"number":35,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nWhat is ___ (deep) ocean in the world?","answer":"the deepest"},
    {"number":36,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\n___ (wild) animals live in the forest.","answer":"The wildest"},
    {"number":37,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nThe journey to Rome was ___ (exciting).","answer":"the most exciting"},
    {"number":38,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nIt''s ___ (cold) tonight than last night.","answer":"colder"},
    {"number":39,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nOur cat is ___ (young) than Tom''s cat.","answer":"younger"},
    {"number":40,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nI think History is ___ (easy) than Science.","answer":"easier"},
    {"number":41,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nWhich mountain is ___ (high), Everest or K2?","answer":"higher"},
    {"number":42,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nThe temperature is ___ (low) in January than in March.","answer":"lower"},
    {"number":43,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nDon''t wake her, she is ___ (tired) of us all!","answer":"the most tired"},
    {"number":44,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nTom is ___ (quiet) boy in our class.","answer":"the quietest"},
    {"number":45,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nMy uncle is ___ (tall) than me, but my grandfather is ___ (tall) in our family.","answer":"taller, the tallest"},
    {"number":46,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nWhich is ___ (dry) month of the year? And ___ (sunny)?","answer":"the driest, the sunniest"},
    {"number":47,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nDad makes ___ (wonderful) pancakes. He''s ___ (good) chef!","answer":"the most wonderful, the best"},
    {"number":48,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nThat spider is ___ (venomous) creature in the lab. Be careful!","answer":"the most venomous"},
    {"number":49,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nWow! This is ___ (nice) gift!","answer":"the nicest"},
    {"number":50,"question":"[주어진 형용사를 알맞은 형태로 바꿔 문장을 완성하시오]\n\nEmily is ___ (fast) than Lisa at swimming, but Sarah is ___ (fast) swimmer in our team.","answer":"faster, the fastest"},

    {"number":51,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nFebruary is ___ month of the year.","answer":"the shortest"},
    {"number":52,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nWhales are ___ animals in the ocean.","answer":"the largest"},
    {"number":53,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nMy grandmother is ___ person in our family.","answer":"the oldest"},
    {"number":54,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nLake Baikal is ___ lake in the world.","answer":"the deepest"},
    {"number":55,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nThe Amazon is ___ river in South America.","answer":"the widest"},
    {"number":56,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nShe is ___ student in the whole school.","answer":"the cleverest"},
    {"number":57,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: short, large, clever, old, wide, loud, deep\n\nThis stadium is ___ place in our city.","answer":"the loudest"},
    {"number":58,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nThe Sahara has ___ climate in the world.","answer":"the driest"},
    {"number":59,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nThis river has ___ water in the region.","answer":"the cleanest"},
    {"number":60,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nHe always buys ___ items at the store.","answer":"the cheapest"},
    {"number":61,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nThe cheetah is ___ animal on land.","answer":"the fastest"},
    {"number":62,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nI think Florence is ___ city in Italy.","answer":"the most beautiful"},
    {"number":63,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nThat firefighter is ___ person in our town.","answer":"the bravest"},
    {"number":64,"question":"[보기에서 알맞은 형용사를 골라 최상급으로 바꿔 빈칸을 채우시오]\n\n보기: kind, brave, fast, beautiful, dry, clean, cheap\n\nShe is ___ girl in our class. She helps everyone.","answer":"the kindest"},

    {"number":65,"question":"[다음 문장을 영작하시오]\n\n세계에서 가장 빠른 동물은 무엇일까?\n\nhint: fast, in the world","answer":"What is the fastest animal in the world?"},
    {"number":66,"question":"[다음 문장을 영작하시오]\n\n어떤 건물이 우리 도시에서 가장 높을까?\n\nhint: tall, building, in our city","answer":"Which building is the tallest in our city?"},
    {"number":67,"question":"[다음 문장을 영작하시오]\n\n나는 이 가게에서 가장 좋은 선물을 고를 것이다.\n\nhint: choose, good, gift, from","answer":"I will choose the best gift from this store."},
    {"number":68,"question":"[다음 문장을 영작하시오]\n\n그것은 나라에서 가장 큰 음악 축제이다.\n\nhint: big, music festival, in","answer":"It is the biggest music festival in the country."},
    {"number":69,"question":"[다음 문장을 영작하시오]\n\n나는 나의 책들을 가장 성실한 학생에게 줄 것이다.\n\nhint: give, books, diligent","answer":"I will give my books to the most diligent student."},
    {"number":70,"question":"[다음 문장을 영작하시오]\n\n그들은 가장 신나는 노래를 연주하기 시작했다.\n\nhint: start, play, exciting, song","answer":"They started to play the most exciting song."},
    {"number":71,"question":"[다음 문장을 영작하시오]\n\n시베리아는 러시아에서 가장 추운 지역이다.\n\nhint: Siberia, cold, region, in Russia","answer":"Siberia is the coldest region in Russia."},
    {"number":72,"question":"[다음 문장을 영작하시오]\n\n티라노사우루스는 가장 크고 무서운 공룡이었다.\n\nhint: the Tyrannosaurus, large, scary, dinosaur","answer":"The Tyrannosaurus was the largest and scariest dinosaur."},
    {"number":73,"question":"[다음 문장을 영작하시오]\n\n그것은 내 인생에서 가장 행복한 순간이었다.\n\nhint: happy, moment, of","answer":"It was the happiest moment of my life."},
    {"number":74,"question":"[다음 문장을 영작하시오]\n\n캐나다가 세계에서 가장 작은 나라는 아니다.\n\nhint: small, country, in","answer":"Canada is not the smallest country in the world."},
    {"number":75,"question":"[다음 문장을 영작하시오]\n\n나우루는 세계에서 가장 작은 섬나라이다.\n\nhint: Nauru, small, island country, in","answer":"Nauru is the smallest island country in the world."},
    {"number":76,"question":"[다음 문장을 영작하시오]\n\n세계에서 가장 높은 산은 에베레스트이다.\n\nhint: the world, high, Mount Everest","answer":"The highest mountain in the world is Mount Everest."}
  ]'::jsonb,
  '[
    "1","1","1","1","1","2","2","1","1","2","1","2","2","2","1",
    "the widest road in","the brightest student in","the most crowded city in","the oldest library in","the kindest of","the most talented actor in","the warmest night of","the thickest in","the laziest workers in","the most famous painting in",
    "faster, the fastest","stronger, the strongest","taller, the tallest","slower, the slowest","smaller, the smallest","colder, the coldest","longer, the longest",
    "stronger","the nearest","the deepest","The wildest","the most exciting","colder","younger","easier","higher","lower","the most tired","the quietest","taller, the tallest","the driest, the sunniest","the most wonderful, the best","the most venomous","the nicest","faster, the fastest",
    "the shortest","the largest","the oldest","the deepest","the widest","the cleverest","the loudest","the driest","the cleanest","the cheapest","the fastest","the most beautiful","the bravest","the kindest",
    "What is the fastest animal in the world?","Which building is the tallest in our city?","I will choose the best gift from this store.","It is the biggest music festival in the country.","I will give my books to the most diligent student.","They started to play the most exciting song.","Siberia is the coldest region in Russia.","The Tyrannosaurus was the largest and scariest dinosaur.","It was the happiest moment of my life.","Canada is not the smallest country in the world.","Nauru is the smallest island country in the world.","The highest mountain in the world is Mount Everest."
  ]'::jsonb
);
