DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = 'so that Step 1';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1: 기본 구조 및 시제 일치 (Q1~Q25) — 2지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
      'question',E'[Part 1] 괄호 안에서 알맞은 표현을 고르시오.\n\nI studied hard so that I (can / could) pass the exam.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(studied)이므로 종속절도 could'),
    jsonb_build_object('number',2,
      'question',E'Speak slowly so that others (can / will) understand you.',
      'options',jsonb_build_array('can','will'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 can'),
    jsonb_build_object('number',3,
      'question',E'We went early in (order / so) that we could get good seats.',
      'options',jsonb_build_array('order','so'),
      'answer','1',
      'explanation',E'in order that = so that (목적)'),
    jsonb_build_object('number',4,
      'question',E'He married her so (as / that) to be with her forever.',
      'options',jsonb_build_array('as','that'),
      'answer','1',
      'explanation',E'so as to + 동사원형 = ~하기 위해'),
    jsonb_build_object('number',5,
      'question',E'I hurried so that I (will / would) not miss the train.',
      'options',jsonb_build_array('will','would'),
      'answer','2',
      'explanation',E'주절이 과거(hurried)이므로 would'),
    jsonb_build_object('number',6,
      'question',E'Turn the music down so that I (can / could) read the book.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 can'),
    jsonb_build_object('number',7,
      'question',E'I will bring the map so that we (can / could) find the way easily.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'주절이 미래(will)이므로 can'),
    jsonb_build_object('number',8,
      'question',E'The Wright brothers invented the airplane so that we (can / could) go to other places quickly.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(invented)이므로 could'),
    jsonb_build_object('number',9,
      'question',E'I go for a walk every morning (so that / because) I can stay healthy.',
      'options',jsonb_build_array('so that','because'),
      'answer','1',
      'explanation',E'건강 유지를 위해(목적) → so that. because는 이유.'),
    jsonb_build_object('number',10,
      'question',E'Gwen goes jogging so that she (can / will) stay in shape.',
      'options',jsonb_build_array('can','will'),
      'answer','1',
      'explanation',E'주절이 현재(goes)이므로 can'),
    jsonb_build_object('number',11,
      'question',E'Rachel bought a swimsuit so that she (can / could) swim in the pool.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(bought)이므로 could'),
    jsonb_build_object('number',12,
      'question',E'Justin studies hard so that he (can / will) be a lawyer.',
      'options',jsonb_build_array('can','will'),
      'answer','1',
      'explanation',E'주절이 현재(studies)이므로 can'),
    jsonb_build_object('number',13,
      'question',E'I called Tiffany so that I (can / could) invite her to my party.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(called)이므로 could'),
    jsonb_build_object('number',14,
      'question',E'He practices running so that he (can / could) finish the marathon.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'주절이 현재(practices)이므로 can'),
    jsonb_build_object('number',15,
      'question',E'Jiho is making a cake so that he (can / could) make his mom happy.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'주절이 현재진행(is making)이므로 can'),
    jsonb_build_object('number',16,
      'question',E'Leave early so that you (don''t / didn''t) miss the bus.',
      'options',jsonb_build_array('don''t','didn''t'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 don''t'),
    jsonb_build_object('number',17,
      'question',E'I went to Canada so that I (can / could) learn English.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(went)이므로 could'),
    jsonb_build_object('number',18,
      'question',E'Step forward so that you (can / could) take a closer look.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 can'),
    jsonb_build_object('number',19,
      'question',E'I''ll leave the door open so that you (can / could) come in.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'주절이 미래(will)이므로 can'),
    jsonb_build_object('number',20,
      'question',E'Please speak louder so that all of us (can / will) hear you.',
      'options',jsonb_build_array('can','will'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 can'),
    jsonb_build_object('number',21,
      'question',E'We climbed higher so that we (can / could) get a better view.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(climbed)이므로 could'),
    jsonb_build_object('number',22,
      'question',E'Switch the light off so that we (can / could) sleep well.',
      'options',jsonb_build_array('can','could'),
      'answer','1',
      'explanation',E'명령문은 현재 시제이므로 can'),
    jsonb_build_object('number',23,
      'question',E'I gave her my phone number so that she (can / could) keep in touch.',
      'options',jsonb_build_array('can','could'),
      'answer','2',
      'explanation',E'주절이 과거(gave)이므로 could'),
    jsonb_build_object('number',24,
      'question',E'I often stop working so that (I / can) can take a rest.',
      'options',jsonb_build_array('I','can'),
      'answer','1',
      'explanation',E'so that 뒤에 주어+조동사 필수. so that I can'),
    jsonb_build_object('number',25,
      'question',E'She made a cake so (that / what) she could give it to her boyfriend.',
      'options',jsonb_build_array('that','what'),
      'answer','1',
      'explanation',E'so that + 주어 + 조동사. what은 불가.'),

    -- ═══════════════════════════════════════════
    -- Part 2: 구문 전환 연습 (Q26~Q50) — 서술형
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',26,
      'question',E'[Part 2] 다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nHe ran to become a champion.',
      'answer',E'He ran so that he might become a champion.',
      'acceptedAnswers',jsonb_build_array(E'He ran so that he might become a champion',E'He ran so that he could become a champion.',E'He ran so that he could become a champion'),
      'explanation',E'to부정사 목적을 so that + 주어 + 조동사로 전환. 과거이므로 might/could 사용.'),
    jsonb_build_object('number',27,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI went to America to speak English well.',
      'answer',E'I went to America so that I could speak English well.',
      'acceptedAnswers',jsonb_build_array(E'I went to America so that I could speak English well',E'I went to America so that I might speak English well.',E'I went to America so that I might speak English well'),
      'explanation',E'to부정사 목적을 so that I could로 전환. 과거 시제이므로 could.'),
    jsonb_build_object('number',28,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nLet''s start early to arrive before dark.',
      'answer',E'Let''s start early so that we may arrive before dark.',
      'acceptedAnswers',jsonb_build_array(E'Let''s start early so that we may arrive before dark',E'Let''s start early so that we can arrive before dark.',E'Let''s start early so that we can arrive before dark'),
      'explanation',E'Let''s 제안문에서 to부정사를 so that we may/can으로 전환.'),
    jsonb_build_object('number',29,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nJane ran out to catch a taxi.',
      'answer',E'Jane ran out so that she could catch a taxi.',
      'acceptedAnswers',jsonb_build_array(E'Jane ran out so that she could catch a taxi'),
      'explanation',E'to부정사 목적을 so that she could로 전환. 과거 시제.'),
    jsonb_build_object('number',30,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI''ll walk fast to get there in time.',
      'answer',E'I''ll walk fast so that I can get there in time.',
      'acceptedAnswers',jsonb_build_array(E'I''ll walk fast so that I can get there in time'),
      'explanation',E'미래 시제이므로 so that I can.'),
    jsonb_build_object('number',31,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nShe exercises every day to lose weight.',
      'answer',E'She exercises every day so that she can lose weight.',
      'acceptedAnswers',jsonb_build_array(E'She exercises every day so that she can lose weight'),
      'explanation',E'현재 시제의 습관이므로 so that she can.'),
    jsonb_build_object('number',32,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nThey went to bed early to get up early.',
      'answer',E'They went to bed early so that they could get up early.',
      'acceptedAnswers',jsonb_build_array(E'They went to bed early so that they could get up early'),
      'explanation',E'과거 시제이므로 so that they could.'),
    jsonb_build_object('number',33,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nHe stepped aside for me to pass by.',
      'answer',E'He stepped aside so that I could pass by.',
      'acceptedAnswers',jsonb_build_array(E'He stepped aside so that I could pass by'),
      'explanation',E'for me to → so that I could. 의미상 주어 me가 절의 주어 I로 변환.'),
    jsonb_build_object('number',34,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nYou must work hard so as not to fail.',
      'answer',E'You must work hard so that you wouldn''t fail.',
      'acceptedAnswers',jsonb_build_array(E'You must work hard so that you wouldn''t fail',E'You must work hard so that you won''t fail.',E'You must work hard so that you won''t fail',E'You must work hard so that you will not fail.',E'You must work hard so that you will not fail',E'You must work hard so that you don''t fail.',E'You must work hard so that you don''t fail'),
      'explanation',E'so as not to → so that + 주어 + 부정 조동사.'),
    jsonb_build_object('number',35,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nThey left home early in order that they can get there on time.',
      'answer',E'They left home early so that they can get there on time.',
      'acceptedAnswers',jsonb_build_array(E'They left home early so that they can get there on time',E'They left home early so that they could get there on time.',E'They left home early so that they could get there on time'),
      'explanation',E'in order that → so that. 나머지 동일.'),
    jsonb_build_object('number',36,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI go for a walk in order to stay healthy.',
      'answer',E'I go for a walk so that I can stay healthy.',
      'acceptedAnswers',jsonb_build_array(E'I go for a walk so that I can stay healthy'),
      'explanation',E'in order to → so that I can. 현재 시제이므로 can.'),
    jsonb_build_object('number',37,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nTurn off the light for the baby to sleep well.',
      'answer',E'Turn off the light so that the baby can sleep well.',
      'acceptedAnswers',jsonb_build_array(E'Turn off the light so that the baby can sleep well'),
      'explanation',E'for + 명사 + to부정사 → so that + 주어 + can. 명령문이므로 can.'),
    jsonb_build_object('number',38,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nHe took a taxi not to be late.',
      'answer',E'He took a taxi so that he wouldn''t be late.',
      'acceptedAnswers',jsonb_build_array(E'He took a taxi so that he wouldn''t be late',E'He took a taxi so that he would not be late.',E'He took a taxi so that he would not be late'),
      'explanation',E'not to → so that + wouldn''t. 부정 목적 표현.'),
    jsonb_build_object('number',39,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI want to sit by the window to see outside.',
      'answer',E'I want to sit by the window so that I can see outside.',
      'acceptedAnswers',jsonb_build_array(E'I want to sit by the window so that I can see outside'),
      'explanation',E'to부정사 목적을 so that I can으로 전환.'),
    jsonb_build_object('number',40,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nShe took my bag for me to walk comfortably.',
      'answer',E'She took my bag so that I could walk comfortably.',
      'acceptedAnswers',jsonb_build_array(E'She took my bag so that I could walk comfortably'),
      'explanation',E'for me to → so that I could. 과거 시제.'),
    jsonb_build_object('number',41,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nThe man broke the door for them to get out.',
      'answer',E'The man broke the door so that they could get out.',
      'acceptedAnswers',jsonb_build_array(E'The man broke the door so that they could get out'),
      'explanation',E'for them to → so that they could. 과거 시제.'),
    jsonb_build_object('number',42,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI prepared breakfast for her to rest.',
      'answer',E'I prepared breakfast so that she could rest.',
      'acceptedAnswers',jsonb_build_array(E'I prepared breakfast so that she could rest'),
      'explanation',E'for her to → so that she could. 과거 시제.'),
    jsonb_build_object('number',43,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nShe cleaned the house for the visitors to feel comfortable.',
      'answer',E'She cleaned the house so that the visitors could feel comfortable.',
      'acceptedAnswers',jsonb_build_array(E'She cleaned the house so that the visitors could feel comfortable'),
      'explanation',E'for the visitors to → so that the visitors could. 과거 시제.'),
    jsonb_build_object('number',44,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI don''t take showers long in order not to waste water.',
      'answer',E'I don''t take showers long so that I may not waste water.',
      'acceptedAnswers',jsonb_build_array(E'I don''t take showers long so that I may not waste water',E'I don''t take showers long so that I won''t waste water.',E'I don''t take showers long so that I won''t waste water',E'I don''t take showers long so that I don''t waste water.',E'I don''t take showers long so that I don''t waste water',E'I don''t take showers long so that I will not waste water.',E'I don''t take showers long so that I will not waste water'),
      'explanation',E'in order not to → so that + may not/won''t. 부정 목적 표현.'),
    jsonb_build_object('number',45,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI studied very hard in order not to fail.',
      'answer',E'I studied very hard so that I wouldn''t fail.',
      'acceptedAnswers',jsonb_build_array(E'I studied very hard so that I wouldn''t fail',E'I studied very hard so that I would not fail.',E'I studied very hard so that I would not fail'),
      'explanation',E'in order not to → so that I wouldn''t. 과거 시제.'),
    jsonb_build_object('number',46,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nShe practiced skating in order to be good at it.',
      'answer',E'She practiced skating so that she could be good at it.',
      'acceptedAnswers',jsonb_build_array(E'She practiced skating so that she could be good at it'),
      'explanation',E'in order to → so that she could. 과거 시제.'),
    jsonb_build_object('number',47,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI took off my shoes in order not to make noise.',
      'answer',E'I took off my shoes so that I wouldn''t make any noise.',
      'acceptedAnswers',jsonb_build_array(E'I took off my shoes so that I wouldn''t make any noise',E'I took off my shoes so that I would not make any noise.',E'I took off my shoes so that I would not make any noise',E'I took off my shoes so that I wouldn''t make noise.',E'I took off my shoes so that I wouldn''t make noise',E'I took off my shoes so that I would not make noise.',E'I took off my shoes so that I would not make noise'),
      'explanation',E'in order not to → so that I wouldn''t. 부정문에서 any 추가 가능.'),
    jsonb_build_object('number',48,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI made vocabulary cards to remember them.',
      'answer',E'I make vocabulary cards so that I can remember them.',
      'acceptedAnswers',jsonb_build_array(E'I make vocabulary cards so that I can remember them',E'I made vocabulary cards so that I could remember them.',E'I made vocabulary cards so that I could remember them'),
      'explanation',E'to부정사 목적을 so that I can으로 전환. 시제가 현재로 바뀌는 점에 주의.'),
    jsonb_build_object('number',49,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nHe cut the bread in half to share it.',
      'answer',E'He cut the bread in half so that he could share it.',
      'acceptedAnswers',jsonb_build_array(E'He cut the bread in half so that he could share it'),
      'explanation',E'to부정사 목적을 so that he could로 전환. 과거 시제.'),
    jsonb_build_object('number',50,
      'question',E'다음 문장을 so that 구문으로 바꿔 쓰시오.\n\nI left my name card for him to contact me.',
      'answer',E'I left my name card so that he could contact me.',
      'acceptedAnswers',jsonb_build_array(E'I left my name card so that he could contact me'),
      'explanation',E'for him to → so that he could. 과거 시제.'),

    -- ═══════════════════════════════════════════
    -- Part 3: 어법 오류 수정 (Q51~Q65) — 서술형
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',51,
      'question',E'[Part 3] 다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nMr. Kim is so kind that his students like.',
      'answer',E'Mr. Kim is so kind that his students like him.',
      'acceptedAnswers',jsonb_build_array(E'Mr. Kim is so kind that his students like him'),
      'explanation',E'목적어 him 누락. like는 타동사이므로 목적어가 필요합니다.'),
    jsonb_build_object('number',52,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nThe place was beautiful so that they wanted to live there.',
      'answer',E'The place was so beautiful that they wanted to live there.',
      'acceptedAnswers',jsonb_build_array(E'The place was so beautiful that they wanted to live there'),
      'explanation',E'so ~ that 결과 구문의 어순: so + 형용사 + that. "so that"(목적)과 "so...that"(결과) 구분.'),
    jsonb_build_object('number',53,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI often stop working so that can take a rest.',
      'answer',E'I often stop working so that I can take a rest.',
      'acceptedAnswers',jsonb_build_array(E'I often stop working so that I can take a rest'),
      'explanation',E'so that 뒤에 주어 I가 누락. so that + 주어 + 조동사 + 동사원형.'),
    jsonb_build_object('number',54,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nThe boy saved money so that he can buy his brother''s present.',
      'answer',E'The boy saved money so that he could buy his brother''s present.',
      'acceptedAnswers',jsonb_build_array(E'The boy saved money so that he could buy his brother''s present'),
      'explanation',E'주절이 과거(saved)이므로 can → could.'),
    jsonb_build_object('number',55,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nShe went to the cafe so that she can meet her dad.',
      'answer',E'She went to the cafe so that she could meet her dad.',
      'acceptedAnswers',jsonb_build_array(E'She went to the cafe so that she could meet her dad',E'She went to the café so that she could meet her dad.',E'She went to the café so that she could meet her dad'),
      'explanation',E'주절이 과거(went)이므로 can → could.'),
    jsonb_build_object('number',56,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nThey will get together so that can they watch a movie.',
      'answer',E'They will get together so that they can watch a movie.',
      'acceptedAnswers',jsonb_build_array(E'They will get together so that they can watch a movie'),
      'explanation',E'so that 뒤 어순: 주어 + 조동사. can they(도치) → they can.'),
    jsonb_build_object('number',57,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI brought an umbrella in order to not get wet.',
      'answer',E'I brought an umbrella in order not to get wet.',
      'acceptedAnswers',jsonb_build_array(E'I brought an umbrella in order not to get wet'),
      'explanation',E'부정 어순: in order not to. "to not"은 틀린 어순.'),
    jsonb_build_object('number',58,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI called the bookstore so that to place an order.',
      'answer',E'I called the bookstore in order to place an order.',
      'acceptedAnswers',jsonb_build_array(E'I called the bookstore in order to place an order',E'I called the bookstore so as to place an order.',E'I called the bookstore so as to place an order',E'I called the bookstore so that I could place an order.',E'I called the bookstore so that I could place an order'),
      'explanation',E'"so that to"는 불가. in order to / so as to + 동사원형 또는 so that + 주어 + 조동사.'),
    jsonb_build_object('number',59,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI was surprised so that I couldn''t say anything.',
      'answer',E'I was so surprised that I couldn''t say anything.',
      'acceptedAnswers',jsonb_build_array(E'I was so surprised that I couldn''t say anything',E'I was so surprised that I could not say anything.',E'I was so surprised that I could not say anything'),
      'explanation',E'so ~ that 결과 구문: so + 형용사 + that. "so that"(목적)이 아님.'),
    jsonb_build_object('number',60,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nGwen reads a lot of books so that she could be a writer.',
      'answer',E'Gwen reads a lot of books so that she can be a writer.',
      'acceptedAnswers',jsonb_build_array(E'Gwen reads a lot of books so that she can be a writer'),
      'explanation',E'주절이 현재(reads)이므로 could → can.'),
    jsonb_build_object('number',61,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI should exercise every day in order to I can be healthy.',
      'answer',E'I should exercise every day so that I can be healthy.',
      'acceptedAnswers',jsonb_build_array(E'I should exercise every day so that I can be healthy',E'I should exercise every day in order to be healthy.',E'I should exercise every day in order to be healthy'),
      'explanation',E'"in order to + 동사원형" 또는 "so that + 주어 + 조동사". "in order to I can"은 두 구문 혼동.'),
    jsonb_build_object('number',62,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nHe came early so that to take a good seat.',
      'answer',E'He came early to take a good seat.',
      'acceptedAnswers',jsonb_build_array(E'He came early to take a good seat',E'He came early in order to take a good seat.',E'He came early in order to take a good seat',E'He came early so that he could take a good seat.',E'He came early so that he could take a good seat'),
      'explanation',E'"so that to"는 불가. to부정사 단독 또는 in order to 사용.'),
    jsonb_build_object('number',63,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nMake a shopping list so that spend your money wisely.',
      'answer',E'Make a shopping list so that you can spend your money wisely.',
      'acceptedAnswers',jsonb_build_array(E'Make a shopping list so that you can spend your money wisely'),
      'explanation',E'so that 뒤에 주어(you) + 조동사(can) 필수.'),
    jsonb_build_object('number',64,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nShe made a cake so what she could give it to her boyfriend.',
      'answer',E'She made a cake so that she could give it to her boyfriend.',
      'acceptedAnswers',jsonb_build_array(E'She made a cake so that she could give it to her boyfriend'),
      'explanation',E'접속사 so that. so what은 틀림.'),
    jsonb_build_object('number',65,
      'question',E'다음 문장에서 틀린 부분을 찾아 올바른 문장 전체를 고쳐 쓰시오.\n\nI left my name card so which he could contact me.',
      'answer',E'I left my name card so that he could contact me.',
      'acceptedAnswers',jsonb_build_array(E'I left my name card so that he could contact me'),
      'explanation',E'접속사 so that. so which는 틀림.'),

    -- ═══════════════════════════════════════════
    -- Part 4: 어순 배열 + 영작 (Q66~Q80) — 서술형
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',66,
      'question',E'[Part 4] 주어진 단어를 올바른 순서로 배열하시오.\n\n(change / can / that / meet / I / will / you / so / the prince / you)',
      'answer',E'I will change you so that you can meet the prince!',
      'acceptedAnswers',jsonb_build_array(E'I will change you so that you can meet the prince!',E'I will change you so that you can meet the prince.',E'I will change you so that you can meet the prince'),
      'explanation',E'so that + 주어 + 조동사 구문.'),
    jsonb_build_object('number',67,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(can / I / light / on / that / the / turn / see / so / you)',
      'answer',E'Turn on the light so that I can see you.',
      'acceptedAnswers',jsonb_build_array(E'Turn on the light so that I can see you',E'Turn the light on so that I can see you.',E'Turn the light on so that I can see you'),
      'explanation',E'Turn on the light so that I can see you. 명령문 + so that.'),
    jsonb_build_object('number',68,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(I / could / rest / prepared / so / Mom / breakfast / that)',
      'answer',E'I prepared breakfast so that Mom could rest.',
      'acceptedAnswers',jsonb_build_array(E'I prepared breakfast so that Mom could rest'),
      'explanation',E'주절이 과거이므로 so that 절에 could.'),
    jsonb_build_object('number',69,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(that / she / Judy / I / email / me / could / so / to / address / my / gave / contact)',
      'answer',E'I gave my email address to Judy so that she could contact me.',
      'acceptedAnswers',jsonb_build_array(E'I gave my email address to Judy so that she could contact me'),
      'explanation',E'4형식/3형식 전환과 so that 구문 결합.'),
    jsonb_build_object('number',70,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(new / I / idioms / so / that / books / can / learn / comic / read / English / I)',
      'answer',E'I read English comic books so that I can learn new idioms.',
      'acceptedAnswers',jsonb_build_array(E'I read English comic books so that I can learn new idioms'),
      'explanation',E'현재 시제이므로 so that I can.'),
    jsonb_build_object('number',71,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(that / on / the fennec fox''s / with / the / fur / covered / can / sand / walk / it / are / hot / feet / so)',
      'answer',E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand.',
      'acceptedAnswers',jsonb_build_array(E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand'),
      'explanation',E'수동태 + so that 구문.'),
    jsonb_build_object('number',72,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(studied / so / I / could / that / hard / I / the exam / pass)',
      'answer',E'I studied hard so that I could pass the exam.',
      'acceptedAnswers',jsonb_build_array(E'I studied hard so that I could pass the exam'),
      'explanation',E'주절이 과거이므로 so that 절에 could.'),
    jsonb_build_object('number',73,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(the / that / we / view / went / floor / so / top / the / could / see / up / to / we)',
      'answer',E'We went up to the top floor so that we could see the view.',
      'acceptedAnswers',jsonb_build_array(E'We went up to the top floor so that we could see the view'),
      'explanation',E'주절이 과거이므로 so that we could.'),
    jsonb_build_object('number',74,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(win / hard / she / Yuna / medal / so / gold / the / could / that / tried)',
      'answer',E'Yuna tried hard so that she could win the gold medal.',
      'acceptedAnswers',jsonb_build_array(E'Yuna tried hard so that she could win the gold medal'),
      'explanation',E'주절이 과거이므로 so that she could.'),
    jsonb_build_object('number',75,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(that / off / can / we / switch / well / light / so / sleep / the)',
      'answer',E'Switch the light off so that we can sleep well.',
      'acceptedAnswers',jsonb_build_array(E'Switch the light off so that we can sleep well',E'Switch off the light so that we can sleep well.',E'Switch off the light so that we can sleep well'),
      'explanation',E'명령문이므로 so that we can. Switch off도 가능.'),
    jsonb_build_object('number',76,
      'question',E'주어진 단어를 올바른 순서로 배열하시오.\n\n(we / ocean / we / currents / here / are / study / that / can / air / so / and)',
      'answer',E'We are here so that we can study air and ocean currents.',
      'acceptedAnswers',jsonb_build_array(E'We are here so that we can study air and ocean currents'),
      'explanation',E'현재 시제이므로 so that we can.'),
    jsonb_build_object('number',77,
      'question',E'다음 우리말을 영어로 쓰시오.\n\n나는 컴퓨터를 켜기 위해서 버튼을 눌렀다.',
      'answer',E'I pressed the button so that I could turn on the computer.',
      'acceptedAnswers',jsonb_build_array(E'I pressed the button so that I could turn on the computer',E'I pushed the button so that I could turn on the computer.',E'I pushed the button so that I could turn on the computer',E'I pressed a button so that I could turn on the computer.',E'I pressed a button so that I could turn on the computer',E'I pushed a button so that I could turn on the computer.',E'I pushed a button so that I could turn on the computer',E'I pressed the button so that I could switch on the computer.',E'I pressed the button so that I could switch on the computer',E'I pressed the button so that I could turn the computer on.',E'I pressed the button so that I could turn the computer on'),
      'explanation',E'"~하기 위해서"는 so that + 주어 + 조동사. 주절이 과거(pressed)이므로 could.'),
    jsonb_build_object('number',78,
      'question',E'다음 우리말을 영어로 쓰시오.\n\n소라는 영어를 열심히 공부하기 위해 책을 샀다.',
      'answer',E'Sora bought the book so that she could study English hard.',
      'acceptedAnswers',jsonb_build_array(E'Sora bought the book so that she could study English hard',E'Sora bought a book so that she could study English hard.',E'Sora bought a book so that she could study English hard',E'Sora bought the book so that she could study English.',E'Sora bought the book so that she could study English',E'Sora bought a book so that she could study English.',E'Sora bought a book so that she could study English',E'Sora bought books so that she could study English hard.',E'Sora bought books so that she could study English hard',E'Sora bought books so that she could study English.',E'Sora bought books so that she could study English'),
      'explanation',E'"~하기 위해"는 so that + 주어 + 조동사. 주절이 과거(bought)이므로 could.'),
    jsonb_build_object('number',79,
      'question',E'다음 우리말을 영어로 쓰시오.\n\n준호는 잘 자기 위해 불을 껐다.',
      'answer',E'Junho turned off the light so that he could sleep well.',
      'acceptedAnswers',jsonb_build_array(E'Junho turned off the light so that he could sleep well',E'Junho turned off the lights so that he could sleep well.',E'Junho turned off the lights so that he could sleep well',E'Junho switched off the light so that he could sleep well.',E'Junho switched off the light so that he could sleep well',E'Junho turned the light off so that he could sleep well.',E'Junho turned the light off so that he could sleep well',E'Junho turned the lights off so that he could sleep well.',E'Junho turned the lights off so that he could sleep well',E'Junho switched off the lights so that he could sleep well.',E'Junho switched off the lights so that he could sleep well'),
      'explanation',E'"~하기 위해"는 so that + 주어 + 조동사. 주절이 과거(turned off)이므로 could.'),
    jsonb_build_object('number',80,
      'question',E'다음 우리말을 영어로 쓰시오.\n\n그는 가난한 사람들을 돕기 위해 인도로 갔다.',
      'answer',E'He went to India so that he could help the poor.',
      'acceptedAnswers',jsonb_build_array(E'He went to India so that he could help the poor',E'He went to India so that he could help poor people.',E'He went to India so that he could help poor people',E'He went to India so that he could help the poor people.',E'He went to India so that he could help the poor people',E'He traveled to India so that he could help the poor.',E'He traveled to India so that he could help the poor',E'He travelled to India so that he could help the poor.',E'He travelled to India so that he could help the poor'),
      'explanation',E'"~하기 위해"는 so that + 주어 + 조동사. "the poor"는 가난한 사람들.')
  );

  a := jsonb_build_array(
    '2','1','1','1','2','1','1','2','1','1','2','1','2','1','1','1','2','1','1','1','2','1','2','1','1',
    E'He ran so that he might become a champion.',
    E'I went to America so that I could speak English well.',
    E'Let''s start early so that we may arrive before dark.',
    E'Jane ran out so that she could catch a taxi.',
    E'I''ll walk fast so that I can get there in time.',
    E'She exercises every day so that she can lose weight.',
    E'They went to bed early so that they could get up early.',
    E'He stepped aside so that I could pass by.',
    E'You must work hard so that you wouldn''t fail.',
    E'They left home early so that they can get there on time.',
    E'I go for a walk so that I can stay healthy.',
    E'Turn off the light so that the baby can sleep well.',
    E'He took a taxi so that he wouldn''t be late.',
    E'I want to sit by the window so that I can see outside.',
    E'She took my bag so that I could walk comfortably.',
    E'The man broke the door so that they could get out.',
    E'I prepared breakfast so that she could rest.',
    E'She cleaned the house so that the visitors could feel comfortable.',
    E'I don''t take showers long so that I may not waste water.',
    E'I studied very hard so that I wouldn''t fail.',
    E'She practiced skating so that she could be good at it.',
    E'I took off my shoes so that I wouldn''t make any noise.',
    E'I make vocabulary cards so that I can remember them.',
    E'He cut the bread in half so that he could share it.',
    E'I left my name card so that he could contact me.',
    E'Mr. Kim is so kind that his students like him.',
    E'The place was so beautiful that they wanted to live there.',
    E'I often stop working so that I can take a rest.',
    E'The boy saved money so that he could buy his brother''s present.',
    E'She went to the cafe so that she could meet her dad.',
    E'They will get together so that they can watch a movie.',
    E'I brought an umbrella in order not to get wet.',
    E'I called the bookstore in order to place an order.',
    E'I was so surprised that I couldn''t say anything.',
    E'Gwen reads a lot of books so that she can be a writer.',
    E'I should exercise every day so that I can be healthy.',
    E'He came early to take a good seat.',
    E'Make a shopping list so that you can spend your money wisely.',
    E'She made a cake so that she could give it to her boyfriend.',
    E'I left my name card so that he could contact me.',
    E'I will change you so that you can meet the prince!',
    E'Turn on the light so that I can see you.',
    E'I prepared breakfast so that Mom could rest.',
    E'I gave my email address to Judy so that she could contact me.',
    E'I read English comic books so that I can learn new idioms.',
    E'The fennec fox''s feet are covered with fur so that it can walk on the hot sand.',
    E'I studied hard so that I could pass the exam.',
    E'We went up to the top floor so that we could see the view.',
    E'Yuna tried hard so that she could win the gold medal.',
    E'Switch the light off so that we can sleep well.',
    E'We are here so that we can study air and ocean currents.',
    E'I pressed the button so that I could turn on the computer.',
    E'Sora bought the book so that she could study English hard.',
    E'Junho turned off the light so that he could sleep well.',
    E'He went to India so that he could help the poor.'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    'so that Step 1',
    'so that',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
