DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'관계대명사의 계속적 용법 Step 2';

  q1 := jsonb_build_array(
    jsonb_build_object('number',1,
      'question',E'My neighbor, ________ has lived here for over 20 years, knows everyone on the street.',
      'type','mcq',
      'options',jsonb_build_array('that','which','whom','who','whose'),
      'answer',E'4',
      'explanation',E'선행사가 사람(neighbor) + 주격 → who. 계속적 용법에 that 불가'),
    jsonb_build_object('number',2,
      'question',E'She won the debate competition, ________ gave her a lot of confidence.',
      'type','mcq',
      'options',jsonb_build_array('who','that','what','whom','which'),
      'answer',E'5',
      'explanation',E'선행사가 앞 문장 전체(대회 우승한 것) → which. 계속적 용법에 that 불가'),
    jsonb_build_object('number',3,
      'question',E'He showed me a photo of the Great Wall, ________ he had visited last summer.',
      'type','mcq',
      'options',jsonb_build_array('who','that','which','what','whose'),
      'answer',E'3',
      'explanation',E'선행사가 사물(the Great Wall) + 목적격 → which'),
    jsonb_build_object('number',4,
      'question',E'There is only one thing I cannot forgive, ________ is dishonesty.',
      'type','mcq',
      'options',jsonb_build_array('who','that','what','which','whom'),
      'answer',E'4',
      'explanation',E'선행사가 사물(one thing) → which'),
    jsonb_build_object('number',5,
      'question',E'I finally met Dr. Ahn, ________ had been my father''s doctor for thirty years.',
      'type','mcq',
      'options',jsonb_build_array('which','that','whom','whose','who'),
      'answer',E'5',
      'explanation',E'선행사가 사람(Dr. Ahn) + 주격 → who'),
    jsonb_build_object('number',6,
      'question',E'다음 두 문장의 의미가 같도록 빈칸에 들어갈 말로 가장 적절한 것은?\n\nShe gave me a warm welcome, and it moved me to tears.\n→ She gave me a warm welcome, ________ moved me to tears.',
      'type','mcq',
      'options',jsonb_build_array('who','that','what','which','and it'),
      'answer',E'4',
      'explanation',E'and it = which (계속적 용법). that은 계속적 용법 불가'),
    jsonb_build_object('number',7,
      'question',E'다음 빈칸 (A), (B)에 들어갈 말로 바르게 짝지어진 것은?\n\n• My uncle, (A)________ spent ten years in Canada, speaks English fluently.\n• She handed me a note, (B)________ had only two words on it.',
      'type','mcq',
      'options',jsonb_build_array('who – which','which – who','that – which','who – that','whose – which'),
      'answer',E'1',
      'explanation',E'(A) uncle=사람 → who / (B) note=사물 → which'),
    jsonb_build_object('number',8,
      'question',E'다음 빈칸 (A), (B)에 들어갈 말로 바르게 짝지어진 것은?\n\n• I admire Sejong the Great, (A)________ created the Korean alphabet.\n• He lost his wallet, (B)________ contained all his credit cards.',
      'type','mcq',
      'options',jsonb_build_array('which – which','who – who','who – which','which – who','that – which'),
      'answer',E'3',
      'explanation',E'(A) Sejong=사람 → who / (B) wallet=사물 → which'),
    jsonb_build_object('number',9,
      'question',E'다음 대화의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?\n\nA: Did you see the news last night?\nB: Yes. I heard about the scientist, (A)________ discovered a new species in the Amazon.\nA: Incredible! She gave an interview, (B)________ was broadcast this morning.',
      'type','mcq',
      'options',jsonb_build_array('who – which','which – who','who – who','which – which','that – which'),
      'answer',E'1',
      'explanation',E'(A) scientist=사람 → who / (B) interview=사물 → which'),
    jsonb_build_object('number',10,
      'question',E'다음 대화의 빈칸 (A), (B), (C)에 들어갈 말로 가장 적절한 것은?\n\nA: How was the school festival?\nB: Amazing! I met Jisoo, (A)________ organized the whole event. She introduced me to her brother, (B)________ plays in a band. They performed three songs, (C)________ got a standing ovation.',
      'type','mcq',
      'options',jsonb_build_array('who – who – which','which – who – which','who – which – who','which – which – who','who – which – that'),
      'answer',E'1',
      'explanation',E'(A)(B) 사람 → who / (C) songs=사물(또는 공연 전체) → which'),
    jsonb_build_object('number',11,
      'question',E'My aunt has four children, ________ are all studying abroad.',
      'type','mcq',
      'options',jsonb_build_array('all of them','all of what','all of which','all of whom','all of whose'),
      'answer',E'4',
      'explanation',E'children=사람 → all of whom (전치사+관계대명사 계속적 용법)'),
    jsonb_build_object('number',12,
      'question',E'다음 중 주어진 문장과 의미가 같은 것을 고르시오.\n\nI ran into my old friend Minji, who was on her way to the library.',
      'type','mcq',
      'options',jsonb_build_array(
        'I ran into my old friend Minji, and she was on her way to the library.',
        'I ran into my old friend Minji because she was on her way to the library.',
        'I ran into my old friend Minji, so she was on her way to the library.',
        'I ran into my old friend Minji though she was on her way to the library.',
        'I ran into my old friend Minji if she was on her way to the library.'),
      'answer',E'1',
      'explanation',E'who = and she (계속적 용법 = 접속사 + 대명사)'),
    jsonb_build_object('number',13,
      'question',E'다음 중 주어진 문장과 의미가 같은 것을 고르시오.\n\nHe skipped breakfast again, which his doctor had warned him not to do.',
      'type','mcq',
      'options',jsonb_build_array(
        'He skipped breakfast again, and his doctor had warned him not to do it.',
        'He skipped breakfast again because his doctor had warned him not to do it.',
        'He skipped breakfast again, but his doctor had warned him not to do so.',
        'He skipped breakfast again though his doctor had warned him not to do it.',
        'He skipped breakfast again so that his doctor had warned him not to do it.'),
      'answer',E'1',
      'explanation',E'which = and it → and his doctor had warned him not to do it'),
    jsonb_build_object('number',14,
      'question',E'다음 중 주어진 문장과 의미가 같은 것을 고르시오.\n\nNobody believed his excuse, which turned out to be completely true.',
      'type','mcq',
      'options',jsonb_build_array(
        'Nobody believed his excuse, but it turned out to be completely true.',
        'Nobody believed his excuse, for it turned out to be completely true.',
        'Nobody believed his excuse, so it turned out to be completely true.',
        'Nobody believed his excuse because it turned out to be completely true.',
        'Nobody believed his excuse though it turned out to be completely true.'),
      'answer',E'1',
      'explanation',E'which = but it — 아무도 믿지 않았지만 사실로 드러남'),
    jsonb_build_object('number',15,
      'question',E'다음 중 짝지어진 두 문장의 의미가 같은 것은?',
      'type','mcq',
      'options',jsonb_build_array(
        E'She has two brothers, who are both teachers.\n= She has two brothers, and they are both teachers.',
        E'He apologized to her, which she didn''t accept.\n= He apologized to her, and she accepted it.',
        E'I don''t like him, who is always complaining.\n= I don''t like him, and he is always complaining.',
        E'We couldn''t go hiking, which was a huge disappointment.\n= We couldn''t go hiking, so it was a huge disappointment.',
        E'She cried all night, which worried her parents.\n= She cried all night, but her parents were worried.'),
      'answer',E'1',
      'explanation',E'① 의미 일치. ② didn''t accept ≠ accepted. ④ which=and it, so는 인과. ⑤ which=and it, but은 역접'),
    jsonb_build_object('number',16,
      'question',E'다음 중 짝지어진 두 문장의 의미가 다른 것은?',
      'type','mcq',
      'options',jsonb_build_array(
        E'I trust her completely, who has never lied to me.\n= I trust her completely, for she has never lied to me.',
        E'They announced a price increase, which angered many customers.\n= They announced a price increase, and it angered many customers.',
        E'He handed in his homework late, which annoyed the teacher.\n= He handed in his homework late, but it annoyed the teacher.',
        E'My sister visited me last weekend, who brought homemade cookies.\n= My sister visited me last weekend, and she brought homemade cookies.',
        E'She saved all her allowance, which allowed her to buy the camera.\n= She saved all her allowance, and it allowed her to buy the camera.'),
      'answer',E'3',
      'explanation',E'which annoyed = and it annoyed가 맞음. but it은 역접으로 의미 상충'),
    jsonb_build_object('number',17,
      'question',E'다음 중 짝지어진 두 문장의 의미가 같은 것은?',
      'type','mcq',
      'options',jsonb_build_array(
        E'Everybody loves Coach Park, who is strict but fair.\n= Everybody loves Coach Park, though he is strict but fair.',
        E'I got a perfect score on the test, which shocked even my teacher.\n= I got a perfect score on the test, and it shocked even my teacher.',
        E'She wore a hat, which covered her whole face.\n= She wore a hat but it covered her whole face.',
        E'He doesn''t like spicy food, who often skips Korean dishes.\n= He doesn''t like spicy food, and she often skips Korean dishes.',
        E'The package arrived damaged, which upset her greatly.\n= The package arrived damaged, but it upset her greatly.'),
      'answer',E'2',
      'explanation',E'② which = and it. ① though는 양보 접속사로 의미 다름. ④ he≠she'),
    jsonb_build_object('number',18,
      'question',E'다음 중 주어진 문장과 의미가 같은 것을 고르시오. (정답 2개)\n\nMy grandfather built this house himself, which he is very proud of.',
      'type','select_all',
      'options',jsonb_build_array(
        'My grandfather built this house himself, and he is very proud of it.',
        'My grandfather built this house himself, but he is very proud of it.',
        'My grandfather built this house himself, so he is very proud of it.',
        'My grandfather built this house himself, for he is very proud of it.',
        'My grandfather built this house himself, and he is very proud of that.'),
      'answer',jsonb_build_array('1','3'),
      'explanation',E'which = and it. ③ so도 인과로 의미 통함'),
    jsonb_build_object('number',19,
      'question',E'다음 중 주어진 문장과 의미가 같은 것을 모두 고르시오. (정답 2개)\n\nI went to the new bookstore, which wasn''t open yet.',
      'type','select_all',
      'options',jsonb_build_array(
        'I went to the new bookstore, but it wasn''t open yet.',
        'I went to the new bookstore, and it wasn''t open yet.',
        'I went to the new bookstore, so it wasn''t open yet.',
        'I went to the new bookstore, for it wasn''t open yet.',
        'I went to the new bookstore, though it wasn''t open yet.'),
      'answer',jsonb_build_array('1','2'),
      'explanation',E'which = and it 또는 but it. ① 대조, ② 순차 서술 둘 다 가능'),
    jsonb_build_object('number',20,
      'question',E'다음 중 밑줄 친 부분과 바꾸어 쓸 수 있는 것은?\n\nWe trust our captain, <u>for he always makes the right decision.</u>',
      'type','mcq',
      'options',jsonb_build_array(
        'which always makes the right decision',
        'who always makes the right decision',
        'that always makes the right decision',
        'whom always makes the right decision',
        'and he always makes the right decision'),
      'answer',E'2',
      'explanation',E'for he = who — 계속적 용법. that은 계속적 용법 불가'),
    jsonb_build_object('number',21,
      'question',E'다음 중 밑줄 친 부분과 바꾸어 쓸 수 있는 것은?\n\nThis is the old market, <u>and it sells the freshest vegetables in town.</u>',
      'type','mcq',
      'options',jsonb_build_array(
        'who sells the freshest vegetables in town',
        'that sells the freshest vegetables in town',
        'which sells the freshest vegetables in town',
        'what sells the freshest vegetables in town',
        'whom sells the freshest vegetables in town'),
      'answer',E'3',
      'explanation',E'and it = which (계속적 용법). market=사물 → which'),
    jsonb_build_object('number',22,
      'question',E'다음 밑줄 친 which가 가리키는 것으로 알맞은 것은?\n\nHe said he had already done his homework, <u>which</u> was a lie.',
      'type','mcq',
      'options',jsonb_build_array(
        'his homework',
        'he',
        'He said he had already done his homework (앞 문장 전체)',
        'the homework assignment',
        'a lie'),
      'answer',E'3',
      'explanation',E'which의 선행사는 앞 문장 전체(그가 숙제를 했다고 말한 것)'),
    jsonb_build_object('number',23,
      'question',E'다음 밑줄 친 which가 가리키는 것으로 알맞은 것은?\n\nI suggested we take a different route, <u>which</u> turned out to be much faster.',
      'type','mcq',
      'options',jsonb_build_array(
        'I',
        'we',
        'a different route',
        'I suggested we take a different route (앞 문장 전체)',
        'the original route'),
      'answer',E'3',
      'explanation',E'which의 선행사는 a different route (다른 길이 더 빨랐다)'),
    jsonb_build_object('number',24,
      'question',E'다음 중 밑줄 친 관계대명사가 가리키는 것으로 알맞지 않은 것은?',
      'type','mcq',
      'options',jsonb_build_array(
        E'I met Jake, <u>who</u> had just returned from a year abroad. (= Jake)',
        E'She bought a new coat, <u>which</u> was on sale. (= a new coat)',
        E'He got a job offer, <u>which</u> made his whole family happy. (= a job offer)',
        E'I helped an old man cross the street, <u>who</u> thanked me kindly. (= an old man)',
        E'She forgot her lines on stage, <u>which</u> made the audience laugh. (= her lines)'),
      'answer',E'5',
      'explanation',E'⑤ which의 선행사는 her lines가 아니라 She forgot her lines on stage 앞 문장 전체'),
    jsonb_build_object('number',25,
      'question',E'다음 중 밑줄 친 관계대명사가 가리키는 것으로 알맞지 않은 것은?',
      'type','mcq',
      'options',jsonb_build_array(
        E'My cat scratched the sofa, <u>which</u> upset my mom. (= 앞 문장 전체)',
        E'We took the subway, <u>which</u> was faster than the bus. (= the subway)',
        E'I saw your sister, <u>who</u> was waiting outside the café. (= your sister)',
        E'He lied to the teacher, <u>which</u> got him into serious trouble. (= 앞 문장 전체)',
        E'She donated her prize money, <u>which</u> was a generous act. (= her prize money)'),
      'answer',E'5',
      'explanation',E'⑤ which의 선행사는 her prize money가 아니라 She donated her prize money 앞 문장 전체'),
    jsonb_build_object('number',26,
      'question',E'다음 중 밑줄 친 which의 선행사가 앞 문장 전체인 것끼리 묶인 것은?\n\nⓐ He finished the race in first place, which was beyond everyone''s expectations.\nⓑ I lost the key, which was on the kitchen table.\nⓒ She refused to apologize, which made the situation worse.\nⓓ My dog chewed my new shoes, which I had just bought yesterday.\nⓔ He stayed silent throughout the meeting, which confused everyone.',
      'type','mcq',
      'options',jsonb_build_array('ⓐ, ⓑ','ⓑ, ⓓ','ⓐ, ⓒ, ⓔ','ⓑ, ⓒ, ⓓ','ⓐ, ⓓ, ⓔ'),
      'answer',E'3',
      'explanation',E'ⓐⓒⓔ = 앞 문장 전체가 선행사. ⓑ key, ⓓ my new shoes가 선행사')
  );

  q2 := jsonb_build_array(
jsonb_build_object('number',27,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n나는 그 경기를 봤는데, 정말 흥미진진했다.','type','mcq','options',jsonb_build_array(E'I watched the game, that was really exciting.',E'I watched the game, what was really exciting.',E'I watched the game, which was really exciting.',E'I watched the game, which it was really exciting.',E'I watched the game, who was really exciting.'),'answer',E'3','explanation',E'사물(the game) 계속적 용법 → which. that/what/who 불가, which it 중복'),
jsonb_build_object('number',28,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n그는 새 아파트로 이사했는데, 그것은 공원 바로 옆에 있다.','type','mcq','options',jsonb_build_array(E'He moved to a new apartment, that is right next to the park.',E'He moved to a new apartment, which right next to the park.',E'He moved to a new apartment, who is right next to the park.',E'He moved to a new apartment, which is right next to the park.',E'He moved to a new apartment, what is right next to the park.'),'answer',E'4','explanation',E'apartment=사물 → which + be동사 is 필요'),
jsonb_build_object('number',29,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n나는 그 소설을 다 읽었는데, 그것은 나를 한참 생각하게 만들었다.','type','mcq','options',jsonb_build_array(E'I finished the novel, that made me think for a long time.',E'I finished the novel, which it made me think for a long time.',E'I finished the novel, which made me think for a long time.',E'I finished the novel, what made me think for a long time.',E'I finished the novel, who made me think for a long time.'),'answer',E'3','explanation',E'the novel=사물 → which'),
jsonb_build_object('number',30,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n모두가 그를 좋아하는데, 그가 항상 친절하고 정직하기 때문이다.','type','mcq','options',jsonb_build_array(E'Everybody likes him, which is always kind and honest.',E'Everybody likes him, that is always kind and honest.',E'Everybody likes him, who is always kind and honest.',E'Everybody likes him, whom is always kind and honest.',E'Everybody likes him, and which is always kind and honest.'),'answer',E'3','explanation',E'him=사람 + 주격 → who. whom은 목적격'),
jsonb_build_object('number',31,'question',E'다음 우리말에 맞는 영어 문장을 모두 고르시오. (정답 2개)\n\n나는 그 영화를 봤는데, 그것은 실제 이야기를 바탕으로 했다.','type','select_all','options',jsonb_build_array(E'I saw the movie, that was based on a true story.',E'I saw the movie, which was based on a true story.',E'I saw the movie, what was based on a true story.',E'I saw the movie, and it was based on a true story.',E'I saw the movie, which it was based on a true story.'),'answer',jsonb_build_array('2','4'),'explanation',E'② which 계속적 용법 옳음. ④ and it = which와 같은 의미'),
jsonb_build_object('number',32,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n그녀에게는 남동생이 하나 있는데, 그는 프로 축구 선수가 되고 싶어 한다.','type','mcq','options',jsonb_build_array(E'She has a brother, that wants to become a professional soccer player.',E'She has a brother, which wants to become a professional soccer player.',E'She has a brother, whom wants to become a professional soccer player.',E'She has a brother, who wants to become a professional soccer player.',E'She has a brother, and which wants to become a professional soccer player.'),'answer',E'4','explanation',E'brother=사람 + 주격 → who'),
jsonb_build_object('number',33,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n우리 아버지는 매일 아침 달리기를 하시는데, 그것이 그를 건강하게 유지시켜 준다.','type','mcq','options',jsonb_build_array(E'My father runs every morning, who keeps him healthy.',E'My father runs every morning, that keeps him healthy.',E'My father runs every morning, what keeps him healthy.',E'My father runs every morning, which it keeps him healthy.',E'My father runs every morning, which keeps him healthy.'),'answer',E'5','explanation',E'앞 문장 전체(달리기 하는 것)가 선행사 → which'),
jsonb_build_object('number',34,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n그녀는 자신의 비밀을 나에게 털어놨는데, 그것은 나를 매우 놀라게 했다.','type','mcq','options',jsonb_build_array(E'She confided her secret to me, whom surprised me greatly.',E'She confided her secret to me, who surprised me greatly.',E'She confided her secret to me, which surprised me greatly.',E'She confided her secret to me, that surprised me greatly.',E'She confided her secret to me, what surprised me greatly.'),'answer',E'3','explanation',E'앞 문장 전체(비밀을 털어놓은 것)가 선행사 → which'),
jsonb_build_object('number',35,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n그는 출판사에서 편집자로 일하는데, 매우 바쁜 사람이다.','type','mcq','options',jsonb_build_array(E'He works as an editor at a publishing house, which is a very busy person.',E'He works as an editor at a publishing house, that is a very busy person.',E'He works as an editor at a publishing house, what is a very busy person.',E'He works as an editor at a publishing house, who is a very busy person.',E'He works as an editor at a publishing house, whom is a very busy person.'),'answer',E'4','explanation',E'He=사람 → who. busy person은 사람을 묘사'),
jsonb_build_object('number',36,'question',E'다음 우리말에 맞는 영어 문장을 고르시오.\n\n우리 팀은 결승전에서 졌는데, 그것은 우리 모두에게 큰 실망이었다.','type','mcq','options',jsonb_build_array(E'Our team lost the final, that was a great disappointment for all of us.',E'Our team lost the final, who was a great disappointment for all of us.',E'Our team lost the final, which was a great disappointment for all of us.',E'Our team lost the final, which it was a great disappointment for all of us.',E'Our team lost the final, what was a great disappointment for all of us.'),'answer',E'3','explanation',E'앞 문장 전체(결승에서 진 것)가 선행사 → which'),
jsonb_build_object('number',37,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① I know the man, that is standing by the gate.\n② She has a sister, which teaches at a university.\n③ They canceled the event, who disappointed many fans.\n④ He visited his grandmother, who lives alone in the mountains.\n⑤ We enjoyed the meal, what was prepared by the chef.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'④ who 옳음. ①that→which ②which→who ③who→which ⑤what→which'),
jsonb_build_object('number',38,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① She broke her promise, which made everyone angry.\n② He has a friend, who have lived in Paris for years.\n③ I bought the jacket, that was on sale last weekend.\n④ We met the director, whom is known worldwide.\n⑤ They attended the seminar, what was very informative.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'①옳음. ②have→has ③that→which ④whom→who ⑤what→which'),
jsonb_build_object('number',39,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① I have two cousins, who is both doctors.\n② She read the letter, that made her cry.\n③ He missed the deadline, which caused a serious problem.\n④ My teacher, whom always encourages us, retired last year.\n⑤ We watched the documentary, what was filmed in Africa.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③옳음. ①is→are ②that→which ④whom→who ⑤what→which'),
jsonb_build_object('number',40,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① She told me a secret, which it shocked me deeply.\n② My brother loves hiking, that keeps him fit.\n③ I met an old professor, who used to teach literature.\n④ They visited the museum, who was under renovation.\n⑤ She lost her glasses, what made reading impossible.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③옳음. ①which it→which ②that→which ④who→which ⑤what→which'),
jsonb_build_object('number',41,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① Everyone admires Ms. Yoon, which is our homeroom teacher.\n② I returned the book, which you lent me last month.\n③ He made a speech, that moved the entire audience.\n④ She called me at midnight, whom woke me up.\n⑤ My parents gave me a surprise party, and which made me very happy.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'②옳음. ①which→who ③that→which ④whom→which ⑤and which→which'),
jsonb_build_object('number',42,'question',E'다음 중 어법상 옳은 문장을 모두 고르시오. (정답 2개)\n\n① She graduated top of her class, which made her parents incredibly proud.\n② He has three daughters, who are all studying medicine.\n③ I ordered a new book, that hasn''t arrived yet.\n④ My dog ran away last night, whom worried us all.\n⑤ We hired a new assistant, which is very hardworking.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','2'),'explanation',E'①②옳음. ③that→which ④whom→which ⑤which→who'),
jsonb_build_object('number',43,'question',E'다음 중 어법상 옳은 문장을 모두 고르시오. (정답 2개)\n\n① I lent him my notes, which he returned the next day.\n② She posted the video online, that went viral immediately.\n③ My grandfather, who is turning 90 next month, still gardens every day.\n④ He cancelled the meeting, which it upset everyone on the team.\n⑤ They opened a new branch, whom is near the train station.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','3'),'explanation',E'①③옳음. ②that→which ④which it→which ⑤whom→which'),
jsonb_build_object('number',44,'question',E'다음 중 어법상 옳은 문장을 모두 고르시오. (정답 2개)\n\n① The singer announced her retirement, which saddened millions of fans.\n② I have a friend, who have studied abroad for two years.\n③ He found a wallet on the street, which contained a large amount of cash.\n④ She ignored my advice, that made me feel unappreciated.\n⑤ My aunt, which is a journalist, won a major award last year.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','3'),'explanation',E'①③옳음. ②have→has ④that→which ⑤which→who'),
jsonb_build_object('number',45,'question',E'다음 중 어법상 <u>어색한</u> 문장은?\n\n① He proposed to her on their first trip together, which she said yes to.\n② My sister, who is a graphic designer, works from home.\n③ They visited the ancient ruins, which had stood for over 2,000 years.\n④ She gave a presentation in English, which impressed the foreign clients.\n⑤ I watched the documentary, that was about ocean pollution.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ that→which — 계속적 용법에 that 불가'),
jsonb_build_object('number',46,'question',E'다음 중 어법상 <u>어색한</u> 문장은?\n\n① My parents moved to Jeju last year, which surprised all of us.\n② I have an older brother, who works at a design firm in Seoul.\n③ She gave me her phone number, which I wrote down immediately.\n④ He told me he was busy, what turned out to be an excuse.\n⑤ We took the mountain trail, which offered a stunning view.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'④ what→which — 계속적 용법에 what 불가'),
jsonb_build_object('number',47,'question',E'다음 중 어법상 옳은 문장을 모두 고르시오. (정답 2개)\n\n① I tried the new café, which opened just last week.\n② She texted me at 3 a.m., that woke me up immediately.\n③ My teacher gave me extra homework, which I found very helpful.\n④ He bought his mom flowers, whom she loved very much.\n⑤ We attended the opening ceremony, and which was quite impressive.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','3'),'explanation',E'①③옳음. ②that→which ④whom→which ⑤and which→which'),
jsonb_build_object('number',48,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① She studied abroad for a year, that broadened her perspective.\n② My best friend moved away, which was hard to accept at first.\n③ I ordered the wrong size, who caused a lot of inconvenience.\n④ He fixed the printer, which it had been broken for two weeks.\n⑤ We planted flowers in the garden, what cheered up the neighborhood.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'②옳음. ①that→which ③who→which ④which it→which ⑤what→which'),
jsonb_build_object('number',49,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① I spoke to the manager, whom dealt with my complaint right away.\n② She spent the whole day cleaning, which exhausted her completely.\n③ He has two older sisters, which are both married.\n④ I left my phone on the bus, that was a real disaster.\n⑤ She smiled at me warmly, what immediately put me at ease.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'②옳음. ①whom→who ③which→who ④that→which ⑤what→which')
  );

  q3 := jsonb_build_array(
jsonb_build_object('number',50,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. I have a dog, which barks at strangers.\nb. She met the director, that she had always admired.\nc. He told me the truth, which surprised me a lot.\nd. My teacher, who have been teaching for 30 years, retired last month.\ne. We visited the village, which was completely destroyed by the flood.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'a, c, e 옳음 (3개). b: that→which, d: have→has'),
jsonb_build_object('number',51,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. She donated her bonus to charity, which was very generous of her.\nb. I met his brother, which is studying medicine in Seoul.\nc. He spoke for two hours, that bored everyone in the room.\nd. My friend Hana, who lives next door, lent me her bicycle.\ne. They launched a new product, which sold out within hours.\nf. She apologized to me, and which made things better between us.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'a, d, e 옳음 (3개). b: which→who, c: that→which, f: and which→which'),
jsonb_build_object('number',52,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. My grandfather, who is 85, still reads the newspaper every morning.\nb. She finished the marathon, which it was her lifelong dream.\nc. He lied to me, that really hurt my feelings.\nd. I moved to a new city, which was both exciting and scary.\ne. She gave a brilliant speech, who impressed the whole audience.\nf. We missed the train, which made us an hour late.','type','mcq','options',jsonb_build_array(E'2개',E'3개',E'4개',E'5개',E'6개'),'answer',E'2','explanation',E'a, d, f 옳음 (3개). b: which it→which, c: that→which, e: who→which'),
jsonb_build_object('number',53,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. She bought a used car, that was surprisingly in great condition.\nb. My coach, who trained me for five years, moved to another city.\nc. He posted a photo online, which went viral overnight.\nd. I introduced her to my parents, whom were delighted to meet her.\ne. They discovered a new planet, what scientists are still studying.\nf. She resigned from her job, which came as a complete shock to everyone.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'b, c, f 옳음 (3개). a: that→which, d: whom→who, e: what→which'),
jsonb_build_object('number',54,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. He has two children, who are both studying abroad.\nb. She told me she was fine, which was clearly not true.\nc. I found a wallet, which contained someone''s ID and cash.\nd. My teacher gave me extra credit, that encouraged me to work harder.\ne. He scored the winning goal, whom made him the hero of the match.\nf. She knitted me a scarf, which I still wear every winter.','type','mcq','options',jsonb_build_array(E'2개',E'3개',E'4개',E'5개',E'6개'),'answer',E'3','explanation',E'a, b, c, f 옳음 (4개). d: that→which, e: whom→which'),
jsonb_build_object('number',55,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. She sang beautifully, who moved everyone to tears.\nb. I read her autobiography, which changed my outlook on life.\nc. He missed the meeting, that upset the whole team.\nd. My sister, who is a pediatrician, volunteers on weekends.\ne. They renovated the old library, which now attracts many visitors.\nf. He sent me a long voice message, what explained everything clearly.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'b, d, e 옳음 (3개). a: who→which, c: that→which, f: what→which'),
jsonb_build_object('number',56,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. I have an older sister, who works as a flight attendant.\nb. She broke the record, which it amazed everyone watching.\nc. He visited his childhood home, which had been turned into a museum.\nd. My friend, whom I trust completely, gave me honest advice.\ne. She decided to study abroad, that was a brave choice.\nf. They got lost in the forest, which led to a hilarious adventure.','type','mcq','options',jsonb_build_array(E'2개',E'3개',E'4개',E'5개',E'6개'),'answer',E'3','explanation',E'a, c, d, f 옳음 (4개). b: which it→which, e: that→which'),
jsonb_build_object('number',57,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\na. He is a well-known architect, which designed our city hall.\nb. She passed the bar exam on her first try, which was remarkable.\nc. I met the author of the book, who signed my copy personally.\nd. They announced the results early, that surprised all the participants.\ne. My mom baked a cake for my birthday, which made my day.\nf. He talked to the crowd for an hour, what kept everyone engaged.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'b, c, e 옳음 (3개). a: which→who, d: that→which, f: what→which'),
jsonb_build_object('number',58,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ I know a girl, who is incredibly talented at drawing.\nⓑ She came home late, that worried her parents terribly.\nⓒ My uncle, which lives in Busan, visits us every summer.\nⓓ He won the scholarship, which will cover his tuition for two years.\nⓔ She kept her promise, and which made me trust her even more.\nⓕ I bought a new phone, who turned out to have a cracked screen.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓓ',E'ⓐ, ⓓ',E'ⓑ, ⓒ, ⓔ',E'ⓓ, ⓔ, ⓕ',E'ⓒ, ⓓ, ⓕ'),'answer',E'2','explanation',E'ⓐⓓ 옳음. ⓑ: that→which, ⓒ: which→who, ⓔ: and which→which, ⓕ: who→which'),
jsonb_build_object('number',59,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ We trust Mr. Choi, who has been our principal for ten years.\nⓑ She finished her thesis early, which allowed her to take a vacation.\nⓒ I met his younger brother, that is studying film in New York.\nⓓ He yelled at us, whom made the whole class feel uncomfortable.\nⓔ She planted roses in the garden, which bloom every spring.\nⓕ My friend called me at dawn, what woke me up instantly.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓔ',E'ⓑ, ⓒ, ⓔ',E'ⓐ, ⓒ, ⓓ',E'ⓓ, ⓔ, ⓕ',E'ⓐ, ⓓ, ⓔ'),'answer',E'1','explanation',E'ⓐⓑⓔ 옳음. ⓒ: that→which, ⓓ: whom→which, ⓕ: what→which'),
jsonb_build_object('number',60,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ She runs a bakery, which is famous for its sourdough bread.\nⓑ I introduced him to my sister, whom is an interior designer.\nⓒ He stayed calm throughout the crisis, that impressed the whole team.\nⓓ My grandmother, who turned 80 last month, still takes yoga classes.\nⓔ They built a new bridge, which connects the two towns.\nⓕ She ignored all his messages, which it made him give up.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓓ',E'ⓑ, ⓒ, ⓔ',E'ⓐ, ⓓ, ⓔ',E'ⓒ, ⓓ, ⓕ',E'ⓐ, ⓔ, ⓕ'),'answer',E'3','explanation',E'ⓐⓓⓔ 옳음. ⓑ: whom→who, ⓒ: that→which, ⓕ: which it→which'),
jsonb_build_object('number',61,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ I have a brother, who is three years older than me.\nⓑ She scored higher than expected, which boosted her confidence.\nⓒ He recommended a café, what serves the best pasta in town.\nⓓ My homeroom teacher, who always believed in me, retired last spring.\nⓔ They canceled the concert, that disappointed thousands of fans.\nⓕ She wrote a poem, which everyone in the class loved.\nⓖ He got a job at a famous company, whom made his parents very proud.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓒ, ⓓ',E'ⓑ, ⓒ, ⓔ, ⓖ',E'ⓐ, ⓑ, ⓓ, ⓕ',E'ⓐ, ⓓ, ⓔ, ⓕ',E'ⓑ, ⓓ, ⓔ, ⓕ'),'answer',E'3','explanation',E'ⓐⓑⓓⓕ 옳음. ⓒ: what→which, ⓔ: that→which, ⓖ: whom→which'),
jsonb_build_object('number',62,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ She adopted a stray cat, which she named Luna.\nⓑ He gave a speech at the ceremony, that lasted over an hour.\nⓒ My neighbor, who has lived here since 1990, knows all the local history.\nⓓ I borrowed her umbrella, which she never asked back for.\nⓔ He said he had returned the money, which was a lie.\nⓕ They hired a new manager, whom is very experienced in marketing.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓔ',E'ⓑ, ⓓ, ⓔ, ⓕ'),'answer',E'4','explanation',E'ⓐⓒⓓⓔ 옳음. ⓑ: that→which, ⓕ: whom→who'),
jsonb_build_object('number',63,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ I visited Paris last year, which is the city of lights.\nⓑ She has three sons, who are all married.\nⓒ He told me a joke, that made everyone laugh.\nⓓ My friend moved to Berlin, which it is a very vibrant city.\nⓔ She quit her job without notice, which angered her employer.\nⓕ I watched a documentary, what was about climate change.\nⓖ He passed the entrance exam, who delighted his whole family.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓔ',E'ⓑ, ⓒ, ⓓ',E'ⓒ, ⓔ, ⓖ',E'ⓐ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓔ'),'answer',E'1','explanation',E'ⓐⓑⓔ 옳음. ⓒ: that→which, ⓓ: which it→which, ⓕ: what→which, ⓖ: who→which'),
jsonb_build_object('number',64,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ She baked cookies for the class, which everyone enjoyed.\nⓑ He forgot his sister''s birthday, that upset her very much.\nⓒ I met the CEO, which founded the company 20 years ago.\nⓓ My father, who is a retired engineer, loves gardening.\nⓔ She confessed her mistake, and which relieved everyone.\nⓕ They watched the game together, which ended in a dramatic draw.\nⓖ He sent me a gift, whom I wasn''t expecting at all.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓓ',E'ⓐ, ⓓ, ⓕ',E'ⓑ, ⓒ, ⓕ',E'ⓒ, ⓓ, ⓖ',E'ⓓ, ⓔ, ⓕ'),'answer',E'2','explanation',E'ⓐⓓⓕ 옳음. ⓑ: that→which, ⓒ: which→who, ⓔ: and which→which, ⓖ: whom→which'),
jsonb_build_object('number',65,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ I have a pen pal in France, who sends me postcards every month.\nⓑ She solved the problem instantly, which amazed all her classmates.\nⓒ He introduced me to his boss, that was very friendly.\nⓓ My team finished the project on time, which impressed the client.\nⓔ She wore a dress, whom her grandmother had sewn.\nⓕ I lent him my laptop, which he promised to return by Friday.\nⓖ They discovered an old painting, what turned out to be priceless.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓑ, ⓓ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓕ',E'ⓐ, ⓑ, ⓔ, ⓕ',E'ⓒ, ⓓ, ⓔ, ⓖ',E'ⓐ, ⓑ, ⓒ, ⓓ'),'answer',E'1','explanation',E'ⓐⓑⓓⓕ 옳음. ⓒ: that→which, ⓔ: whom→which, ⓖ: what→which'),
jsonb_build_object('number',66,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ He was born in a small town, which no longer exists.\nⓑ She got the lead role in the play, that made her extremely happy.\nⓒ My brother, who is a chef, opened his own restaurant last year.\nⓓ I read the article, what was about the new space mission.\nⓔ She cooked dinner for everyone, which they all found delicious.\nⓕ He forgot to lock the door, whom caused a security issue.\nⓖ They held a farewell party, which was attended by over a hundred people.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓒ, ⓔ, ⓖ',E'ⓑ, ⓒ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓔ, ⓖ',E'ⓒ, ⓓ, ⓕ, ⓖ',E'ⓐ, ⓑ, ⓒ, ⓖ'),'answer',E'1','explanation',E'ⓐⓒⓔⓖ 옳음. ⓑ: that→which, ⓓ: what→which, ⓕ: whom→which'),
jsonb_build_object('number',67,'question',E'다음 중 어법상 옳은 것끼리 바르게 짝지어진 것을 고르시오.\n\nⓐ She rescued a puppy from the street, which she named Bomi.\nⓑ He asked for a raise, that was rejected by his manager.\nⓒ My history teacher, who has written several books, is very inspiring.\nⓓ They completed the project ahead of schedule, which delighted the client.\nⓔ I attended the lecture, what was on artificial intelligence.\nⓕ She slipped on the ice, who twisted her ankle badly.\nⓖ He sent me an email, which contained all the details I needed.','type','mcq','options',jsonb_build_array(E'ⓐ, ⓒ, ⓓ, ⓖ',E'ⓑ, ⓒ, ⓓ, ⓖ',E'ⓐ, ⓑ, ⓒ, ⓓ',E'ⓒ, ⓓ, ⓔ, ⓖ',E'ⓐ, ⓓ, ⓔ, ⓕ'),'answer',E'1','explanation',E'ⓐⓒⓓⓖ 옳음. ⓑ: that→which, ⓔ: what→which, ⓕ: who→which'),
jsonb_build_object('number',68,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nLast weekend, I attended my cousin''s wedding, ①<u>that</u> was held at a small chapel in the countryside. The ceremony was beautiful. I sat next to my aunt, ②<u>who</u> flew in all the way from Australia just for the event. After the ceremony, we had dinner at a restaurant, ③<u>which it</u> served amazing traditional food. The newlyweds gave a heartfelt speech, ④<u>what</u> moved everyone to tears. It was truly a memorable day, ⑤<u>which</u> I will never forget.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('2','5'),'explanation',E'②who ⑤which 옳음. ①that→which ③which it→which ④what→which'),
jsonb_build_object('number',69,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nMy grandfather, ①<u>whom</u> turned 85 last month, is still incredibly active. He takes a walk every morning, ②<u>which</u> keeps him healthy and energetic. Last week, he met his old friend Mr. Jang, ③<u>that</u> had moved abroad thirty years ago. They talked for hours, ④<u>which</u> brought back many happy memories. My grandfather later told me about their conversation, ⑤<u>who</u> made him emotional.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('2','4'),'explanation',E'②④ which 옳음. ①whom→who ③that→which ⑤who→which'),
jsonb_build_object('number',70,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nOur school recently hired a new librarian, ①<u>which</u> reorganized the entire library. She installed a digital catalog system, ②<u>that</u> makes it much easier to find books. She also started a reading club, ③<u>which</u> meets every Thursday after school. Last month, she invited a local author, ④<u>who</u> read aloud from her latest novel. The students loved the session, ⑤<u>which</u> inspired many of them to start writing their own stories.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('3','4','5'),'explanation',E'③④⑤ 옳음. ①which→who ②that→which'),
jsonb_build_object('number',71,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nI recently started volunteering at a community center, ①<u>who</u> helps elderly residents in my neighborhood. Last Tuesday, I helped a woman named Mrs. Oh, ②<u>which</u> had difficulty using her new smartphone. I spent two hours with her, ③<u>which</u> she found very helpful. She introduced me to her grandson, ④<u>who</u> also volunteers there on weekends. Working there has been a wonderful experience, ⑤<u>which</u> I would recommend to everyone.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('3','4','5'),'explanation',E'③④⑤ 옳음. ①who→which ②which→who'),
jsonb_build_object('number',72,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nMy family recently adopted a rescue dog, ①<u>that</u> we named Bomi. She was scared at first and stayed under the bed, ②<u>which</u> broke our hearts. My younger sister, ③<u>who</u> is usually afraid of dogs, was the first to earn Bomi''s trust. She spent hours sitting quietly beside her, ④<u>what</u> eventually helped Bomi relax. Now Bomi follows my sister everywhere, ⑤<u>which</u> delights the whole family.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('2','3','5'),'explanation',E'②③⑤ 옳음. ①that→which ④what→which'),
jsonb_build_object('number',73,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nI recently read a biography of Marie Curie, ①<u>which</u> was deeply inspiring. She was a scientist, ②<u>that</u> won the Nobel Prize twice in different fields. She dedicated her life to research, ③<u>which</u> came at a great personal cost to her health. Her daughter Irène, ④<u>who</u> also became a scientist, later won the Nobel Prize as well. Their story is a powerful reminder of the importance of perseverance, ⑤<u>what</u> I think about often.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','3','4'),'explanation',E'①③④ 옳음. ②that→who ⑤what→which'),
jsonb_build_object('number',74,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nMy school organized a cultural exchange program, ①<u>which</u> brought students from five different countries together. I was paired with a student from Brazil named Lucas, ②<u>who</u> could speak three languages. We visited several historical sites, ③<u>that</u> gave us a deeper appreciation of Korean history. Lucas tried Korean food for the first time, ④<u>which</u> he found surprisingly delicious. We exchanged contact information before he left, ⑤<u>whom</u> I hope will lead to a lasting friendship.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('1','2','4'),'explanation',E'①②④ 옳음. ③that→which ⑤whom→which'),
jsonb_build_object('number',75,'question',E'다음 글의 밑줄 친 부분 중 어법상 옳은 것을 모두 고르시오.\n\nLast summer I interned at a publishing company, ①<u>that</u> specializes in children''s books. My supervisor was Ms. Kang, ②<u>who</u> had been in the industry for over twenty years. She gave me a lot of feedback on my work, ③<u>which</u> helped me improve quickly. One day, I accidentally deleted an important file, ④<u>which it</u> caused a major panic in the office. Luckily, a colleague recovered it, ⑤<u>which</u> saved the day.','type','select_all','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',jsonb_build_array('2','3','5'),'explanation',E'②③⑤ 옳음. ①that→which ④which it→which')
  );

  a := jsonb_build_array();

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (E'관계대명사의 계속적 용법 Step 2', E'관계대명사의 계속적 용법', q1 || q2 || q3, a, 'problem', 'interactive');
END $$;
