DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = 'want+목적어+to부정사 Step 1';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1: 동사의 알맞은 형태 고르기 (Q1~Q10) — 2지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
  'question',E'[Part 1] 괄호 안에서 알맞은 형태를 고르시오.\n\nMy dad wants me ______ harder this semester. (study / to study)',
  'options',jsonb_build_array(E'study',E'to study'),
  'answer','2',
  'explanation',E'want+목적어+to부정사: wants me to study'),
jsonb_build_object('number',2,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nShe asked him ______ an umbrella. (to bring / bring)',
  'options',jsonb_build_array(E'to bring',E'bring'),
  'answer','1',
  'explanation',E'ask+목적어+to부정사: asked him to bring'),
jsonb_build_object('number',3,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nThe coach made us ______ ten laps around the track. (to run / run)',
  'options',jsonb_build_array(E'to run',E'run'),
  'answer','2',
  'explanation',E'사역동사 make+목적어+동사원형: made us run'),
jsonb_build_object('number',4,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nI heard someone ______ on the front door. (knock / to knock)',
  'options',jsonb_build_array(E'knock',E'to knock'),
  'answer','1',
  'explanation',E'지각동사 hear+목적어+동사원형: heard someone knock'),
jsonb_build_object('number',5,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nMy teacher encouraged me ______ the debate club. (to join / join)',
  'options',jsonb_build_array(E'to join',E'join'),
  'answer','1',
  'explanation',E'encourage+목적어+to부정사: encouraged me to join'),
jsonb_build_object('number',6,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nShe let her son ______ up late on weekends. (stay / to stay)',
  'options',jsonb_build_array(E'stay',E'to stay'),
  'answer','1',
  'explanation',E'사역동사 let+목적어+동사원형: let her son stay'),
jsonb_build_object('number',7,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nThe dentist advised him ______ too much sugar. (not to eat / not eat)',
  'options',jsonb_build_array(E'not to eat',E'not eat'),
  'answer','1',
  'explanation',E'advise+목적어+not to부정사: advised him not to eat'),
jsonb_build_object('number',8,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nThey expected her ______ the first prize. (to win / winning)',
  'options',jsonb_build_array(E'to win',E'winning'),
  'answer','1',
  'explanation',E'expect+목적어+to부정사: expected her to win'),
jsonb_build_object('number',9,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nI saw the children ______ in the park after school. (play / to play)',
  'options',jsonb_build_array(E'play',E'to play'),
  'answer','1',
  'explanation',E'지각동사 see+목적어+동사원형: saw the children play'),
jsonb_build_object('number',10,
  'question',E'괄호 안에서 알맞은 형태를 고르시오.\n\nHis parents allowed him ______ on the school trip. (go / to go)',
  'options',jsonb_build_array(E'go',E'to go'),
  'answer','2',
  'explanation',E'allow+목적어+to부정사: allowed him to go'),

    -- ═══════════════════════════════════════════
    -- Part 2: 알맞은 형태로 빈칸 채우기 (Q11~Q25) — short_answer
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
  'question',E'[Part 2] 괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n<보기> She asked me to give her some advice. (I / give)\n\nMy mom wants ______ the dishes after dinner. (I / wash)',
  'answer',E'me to wash',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'want+목적어+to부정사 → me to wash'),
jsonb_build_object('number',12,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nCould you ask ______ the report by Friday? (he / finish)',
  'answer',E'him to finish',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'ask+목적어+to부정사 → him to finish'),
jsonb_build_object('number',13,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nShe begged ______ her secret. (he / not / tell)',
  'answer',E'him not to tell',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'beg+목적어+not to부정사 → him not to tell'),
jsonb_build_object('number',14,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nThe teacher told ______ the door. (I / close)',
  'answer',E'me to close',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사 → me to close'),
jsonb_build_object('number',15,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nThey allow ______ in the garden. (people / sit)',
  'answer',E'people to sit',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'allow+목적어+to부정사 → people to sit'),
jsonb_build_object('number',16,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nHe persuaded ______ the team. (she / join)',
  'answer',E'her to join',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'persuade+목적어+to부정사 → her to join'),
jsonb_build_object('number',17,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nMy parents warned ______ out alone at night. (I / not / go)',
  'answer',E'me not to go',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'warn+목적어+not to부정사 → me not to go'),
jsonb_build_object('number',18,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nI invited ______ my birthday party. (all my friends / come)',
  'answer',E'all my friends to come to',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'invite+목적어+to부정사 → all my friends to come to'),
jsonb_build_object('number',19,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nThe coach ordered ______ every morning. (they / practice)',
  'answer',E'them to practice',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'order+목적어+to부정사 → them to practice'),
jsonb_build_object('number',20,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nCan you remind ______ the library books tomorrow? (I / return)',
  'answer',E'me to return',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'remind+목적어+to부정사 → me to return'),
jsonb_build_object('number',21,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nThey warned ______ in the river. (I / not / swim)',
  'answer',E'me not to swim',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'warn+목적어+not to부정사 → me not to swim'),
jsonb_build_object('number',22,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nShe expected ______ the exam easily. (he / pass)',
  'answer',E'him to pass',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'expect+목적어+to부정사 → him to pass'),
jsonb_build_object('number',23,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nThe doctor advised ______ more water every day. (she / drink)',
  'answer',E'her to drink',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'advise+목적어+to부정사 → her to drink'),
jsonb_build_object('number',24,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nHis boss asked ______ overtime this weekend. (he / work)',
  'answer',E'him to work',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'ask+목적어+to부정사 → him to work'),
jsonb_build_object('number',25,
  'question',E'괄호 안의 표현을 알맞은 형태로 바꿔 빈칸을 채우시오.\n\nI encouraged ______ for the school play. (she / audition)',
  'answer',E'her to audition',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'encourage+목적어+to부정사 → her to audition'),

    -- ═══════════════════════════════════════════
    -- Part 3: 대화/인용문 → 문장 전환 (Q26~Q40) — short_answer
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',26,
  'question',E'[Part 3] 괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n<보기> "Mark, please close the window." (ask) → Judy asked Mark to close the window.\n\n"Be quiet, Tom." (tell) → She ______.',
  'answer',E'told Tom to be quiet',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사'),
jsonb_build_object('number',27,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Don''t be late, Mia." (tell) → He ______.',
  'answer',E'told Mia not to be late',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'tell+목적어+not to부정사 (부정)'),
jsonb_build_object('number',28,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Jake, can you help me carry this?" (ask) → She ______.',
  'answer',E'asked Jake to help her carry it',
  'acceptedAnswers',jsonb_build_array(E'asked Jake to help her carry this',E'asked Jake to help her carry that'),
  'explanation',E'ask+목적어+to부정사, me→her (화자 전환)'),
jsonb_build_object('number',29,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"You should get more sleep." (advise) → The doctor ______.',
  'answer',E'advised him to get more sleep',
  'acceptedAnswers',jsonb_build_array(E'advised me to get more sleep',E'advised her to get more sleep',E'advised us to get more sleep'),
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'advise+목적어+to부정사'),
jsonb_build_object('number',30,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"You can use my laptop." (allow) → She ______.',
  'answer',E'allowed him to use her laptop',
  'acceptedAnswers',jsonb_build_array(E'allowed me to use her laptop',E'allowed her to use her laptop',E'allowed us to use her laptop'),
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'allow+목적어+to부정사, my→her (화자 전환)'),
jsonb_build_object('number',31,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Don''t touch the paintings." (tell) → The guard ______.',
  'answer',E'told them not to touch the paintings',
  'acceptedAnswers',jsonb_build_array(E'told us not to touch the paintings',E'told me not to touch the paintings',E'told him not to touch the paintings',E'told her not to touch the paintings',E'told the visitors not to touch the paintings'),
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'tell+목적어+not to부정사 (부정)'),
jsonb_build_object('number',32,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Let''s go shopping," Sue says. → Sue wants ______.',
  'answer',E'to go shopping',
  'acceptedAnswers',jsonb_build_array(E'us to go shopping'),
  'explanation',E'want+to부정사 (주어 자신의 희망)'),
jsonb_build_object('number',33,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Anna, could you please water the plants?" asks her mom. → Anna''s mom wants ______.',
  'answer',E'Anna to water the plants',
  'acceptedAnswers',jsonb_build_array(E'her to water the plants'),
  'explanation',E'want+목적어+to부정사'),
jsonb_build_object('number',34,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"I don''t want to go to the dentist," says Sam. → Sam doesn''t want ______.',
  'answer',E'to go to the dentist',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'want+to부정사 (주어 자신의 희망, 부정문)'),
jsonb_build_object('number',35,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Soldiers, stop right there!" (order) → The officer ______.',
  'answer',E'ordered the soldiers to stop right there',
  'acceptedAnswers',jsonb_build_array(E'ordered them to stop right there'),
  'explanation',E'order+목적어+to부정사'),
jsonb_build_object('number',36,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"You should try the new restaurant." (encourage) → My friend ______.',
  'answer',E'encouraged me to try the new restaurant',
  'acceptedAnswers',jsonb_build_array(E'encouraged us to try the new restaurant'),
  'explanation',E'encourage+목적어+to부정사'),
jsonb_build_object('number',37,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Don''t run in the hallway." (warn) → The teacher ______.',
  'answer',E'warned us not to run in the hallway',
  'acceptedAnswers',jsonb_build_array(E'warned the students not to run in the hallway',E'warned them not to run in the hallway'),
  'explanation',E'warn+목적어+not to부정사 (부정)'),
jsonb_build_object('number',38,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Can I have some more time?" Michael says. → Michael wants ______.',
  'answer',E'to have some more time',
  'acceptedAnswers',jsonb_build_array(E'to have more time'),
  'explanation',E'want+to부정사 (주어 자신의 희망)'),
jsonb_build_object('number',39,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Please don''t tell anyone." (beg) → She ______.',
  'answer',E'begged me not to tell anyone',
  'acceptedAnswers',jsonb_build_array(E'begged him not to tell anyone',E'begged them not to tell anyone'),
  'explanation',E'beg+목적어+not to부정사 (부정)'),
jsonb_build_object('number',40,
  'question',E'괄호 안의 동사를 사용하여 한 문장으로 바꿔 쓰시오.\n\n"Kevin, finish your homework first." (tell) → His mom ______.',
  'answer',E'told Kevin to finish his homework first',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사'),

    -- ═══════════════════════════════════════════
    -- Part 4: 박스에서 동사 골라 빈칸 채우기 (Q41~Q55) — short_answer
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',41,
  'question',E'[Part 4] 박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nShe told him ______ too fast on the highway.',
  'answer',E'not to drive',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'drive를 선택, 과속 금지 → not to drive'),
jsonb_build_object('number',42,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nMom persuaded me ______ to the family dinner.',
  'answer',E'to come',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'come을 선택, persuade+목적어+to부정사'),
jsonb_build_object('number',43,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nI asked her ______ so late at night.',
  'answer',E'not to call',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'call을 선택, 늦은 밤 전화 금지 → not to call'),
jsonb_build_object('number',44,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nThe doctor advised him ______ junk food every day.',
  'answer',E'not to eat',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'eat을 선택, 정크푸드 금지 → not to eat'),
jsonb_build_object('number',45,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nHis teacher told him ______ in bed during class.',
  'answer',E'not to stay',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'stay를 선택, 수업 중 침대에 있지 말라 → not to stay'),
jsonb_build_object('number',46,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nI asked my friend ______ me his bicycle for the weekend.',
  'answer',E'to lend',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'lend를 선택, ask+목적어+to부정사'),
jsonb_build_object('number',47,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nCan you help me ______ this heavy sofa?',
  'answer',E'move',
  'acceptedAnswers',jsonb_build_array(E'to move'),
  'explanation',E'help+목적어+동사원형(또는 to부정사), move를 선택'),
jsonb_build_object('number',48,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nThe manager told all staff ______ the report by Monday.',
  'answer',E'to submit',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'submit을 선택, tell+목적어+to부정사'),
jsonb_build_object('number',49,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nMy parents want me ______ an umbrella when it''s cloudy.',
  'answer',E'to bring',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'bring을 선택, want+목적어+to부정사'),
jsonb_build_object('number',50,
  'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nShe asked him ______ to her after the argument.',
  'answer',E'to apologize',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'apologize를 선택, ask+목적어+to부정사'),
    -- ═══════════════════════════════════════
    -- Part 4 continued: 박스에서 동사 골라 빈칸 채우기 (Q51-Q55) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',51,
      'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nThe rule requires students ___ Korean during English class.',
      'answer',E'not to speak',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'speak을 선택, 영어 수업 중 한국어 사용 금지 → not to speak'),
    jsonb_build_object('number',52,
      'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nHe told me ___ the lights before leaving.',
      'answer',E'to turn off',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'turn off를 선택, tell+목적어+to부정사'),
    jsonb_build_object('number',53,
      'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nThe doctor advised her ___ for at least 30 minutes a day.',
      'answer',E'to exercise',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'exercise를 선택, advise+목적어+to부정사'),
    jsonb_build_object('number',54,
      'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nMy teacher encouraged everyone ___ the science fair.',
      'answer',E'to attend',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'attend를 선택, encourage+목적어+to부정사'),
    jsonb_build_object('number',55,
      'question',E'박스 안에서 알맞은 동사를 골라 빈칸을 채우시오. (필요시 not을 추가할 것)\n[call / come / eat / drive / stay / speak / submit / lend / move / turn off / bring / apologize / open / exercise / attend]\n\nShe told him ___ the window — it was too cold inside.',
      'answer',E'not to open',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'open을 선택, 추워서 창문 열지 말라 → not to open'),

    -- ═══════════════════════════════════════
    -- Part 5: 오류 찾아 고쳐 쓰기 (Q56-Q70) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',56,
      'question',E'[Part 5] 각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nMy brother made me to wash his car.',
      'answer',E'My brother made me wash his car.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'사역동사 make+목적어+동사원형 → to wash를 wash로'),
    jsonb_build_object('number',57,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nShe allowed him go to the concert alone.',
      'answer',E'She allowed him to go to the concert alone.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'allow+목적어+to부정사 → go를 to go로'),
    jsonb_build_object('number',58,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nHe ordered the students to not make noise.',
      'answer',E'He ordered the students not to make noise.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'부정 to부정사의 어순: not to + 동사원형'),
    jsonb_build_object('number',59,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nI asked her sing a song for us.',
      'answer',E'I asked her to sing a song for us.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'ask+목적어+to부정사 → sing을 to sing으로'),
    jsonb_build_object('number',60,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nMy teacher wanted me studying more vocabulary.',
      'answer',E'My teacher wanted me to study more vocabulary.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'want+목적어+to부정사 → studying을 to study로'),
    jsonb_build_object('number',61,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nDad allowed me went to the movies with friends.',
      'answer',E'Dad allowed me to go to the movies with friends.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'allow+목적어+to부정사 → went를 to go로'),
    jsonb_build_object('number',62,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nThey expect her to coming to the ceremony.',
      'answer',E'They expect her to come to the ceremony.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'to+동사원형 → to coming을 to come으로'),
    jsonb_build_object('number',63,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nMy father advised me to not use my phone at dinner.',
      'answer',E'My father advised me not to use my phone at dinner.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'부정 to부정사의 어순: not to + 동사원형'),
    jsonb_build_object('number',64,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nI told you come home before 10 p.m.',
      'answer',E'I told you to come home before 10 p.m.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'tell+목적어+to부정사 → come을 to come으로'),
    jsonb_build_object('number',65,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nMom allowed me playing video games after school.',
      'answer',E'Mom allowed me to play video games after school.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'allow+목적어+to부정사 → playing을 to play로'),
    jsonb_build_object('number',66,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nHe made me to clean the entire classroom.',
      'answer',E'He made me clean the entire classroom.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'사역동사 make+목적어+동사원형 → to clean을 clean으로'),
    jsonb_build_object('number',67,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nMy coach asked me practice every single day.',
      'answer',E'My coach asked me to practice every single day.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'ask+목적어+to부정사 → practice를 to practice로'),
    jsonb_build_object('number',68,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nThe doctor advised me exercise at least three times a week.',
      'answer',E'The doctor advised me to exercise at least three times a week.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'advise+목적어+to부정사 → exercise를 to exercise로'),
    jsonb_build_object('number',69,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nHis wealth enabled him go abroad for his studies.',
      'answer',E'His wealth enabled him to go abroad for his studies.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'enable+목적어+to부정사 → go를 to go로'),
    jsonb_build_object('number',70,
      'question',E'각 문장에서 문법적 오류를 찾아 전체 문장을 올바르게 다시 쓰시오.\n\nHer family expected her went to a top university.',
      'answer',E'Her family expected her to go to a top university.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'expect+목적어+to부정사 → went를 to go로'),

    -- ═══════════════════════════════════════
    -- Part 6: 단어 배열하기 (Q71-Q85) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',71,
      'question',E'[Part 6] 괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nShe asked (to / her / clean / bag / me / her).',
      'answer',E'me to clean her bag',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'ask+목적어+to부정사 → me to clean her bag (her는 소유격)'),
    jsonb_build_object('number',72,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nI want (right / to / now / you / leave).',
      'answer',E'you to leave right now',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'want+목적어+to부정사 → you to leave right now'),
    jsonb_build_object('number',73,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nHe advised (to / me / quit / eating / snacks) late at night.',
      'answer',E'me to quit eating snacks',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'advise+목적어+to부정사 → me to quit eating snacks'),
    jsonb_build_object('number',74,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nMy mom told (to / tidy / me / up / my) desk before bed.',
      'answer',E'me to tidy up my',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'tell+목적어+to부정사 → me to tidy up my (desk는 문장에 이미 포함)'),
    jsonb_build_object('number',75,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nI want to (for / him / make / dinner / have) me tonight.',
      'answer',E'have him make dinner for',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'have(사역)+목적어+동사원형 → have him make dinner for (me는 문장에 이미 포함)'),
    jsonb_build_object('number',76,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nShe told (not / to / talk / him / back) to his parents.',
      'answer',E'him not to talk back',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'tell+목적어+not to부정사 → him not to talk back'),
    jsonb_build_object('number',77,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nThe principal (to / us / asked / be / on) time every day.',
      'answer',E'asked us to be on',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'ask+목적어+to부정사 → asked us to be on (time은 문장에 이미 포함)'),
    jsonb_build_object('number',78,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nThe coach (to / Jim / advised / stretch / before) every game.',
      'answer',E'advised Jim to stretch before',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'advise+목적어+to부정사 → advised Jim to stretch before'),
    jsonb_build_object('number',79,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nThis app (enable / to / us / track / helps) our daily steps.',
      'answer',E'helps enable us to track',
      'acceptedAnswers',jsonb_build_array('helps us to track'),
      'explanation',E'help+동사원형 → helps enable(도움을 줘 가능하게 한다), enable+목적어+to부정사'),
    jsonb_build_object('number',80,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(made / him / I / the / wash) dishes after the party.',
      'answer',E'I made him wash the',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'make(사역)+목적어+동사원형 → I made him wash the (dishes는 문장에 이미 포함)'),
    jsonb_build_object('number',81,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nShe (her / had / daughter / finish) all her vegetables first.',
      'answer',E'had her daughter finish',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'have(사역)+목적어+동사원형 → had her daughter finish'),
    jsonb_build_object('number',82,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(him / James / expects / to / join) the school soccer team.',
      'answer',E'James expects him to join',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'expect+목적어+to부정사 → James expects him to join'),
    jsonb_build_object('number',83,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nMy dad (me / allowed / to / go / on) the camping trip.',
      'answer',E'allowed me to go on',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'allow+목적어+to부정사 → allowed me to go on'),
    jsonb_build_object('number',84,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\n(I / my / told / sister / to / lock) the door before sleeping.',
      'answer',E'I told my sister to lock',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'tell+목적어+to부정사 → I told my sister to lock'),
    jsonb_build_object('number',85,
      'question',E'괄호 안의 단어들을 알맞은 순서로 배열하시오.\n\nThe dentist (me / not / advised / to / eat) hard candy.',
      'answer',E'advised me not to eat',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'advise+목적어+not to부정사 → advised me not to eat'),

    -- ═══════════════════════════════════════
    -- Part 7: 한→영 영작 (Q86-Q100) — short_answer
    -- ═══════════════════════════════════════
    jsonb_build_object('number',86,
      'question',E'[Part 7] 주어진 힌트를 활용하여 문장을 영작하시오.\n\n그녀는 내가 개를 산책시키기를 원했다. (want, walk, the dog)',
      'answer',E'She wanted me to walk the dog.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'want+목적어+to부정사 → wanted me to walk the dog'),
    jsonb_build_object('number',87,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그는 내게 조용히 하라고 요청했다. (ask, be quiet)',
      'answer',E'He asked me to be quiet.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'ask+목적어+to부정사 → asked me to be quiet'),
    jsonb_build_object('number',88,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n나는 그가 의사에게 진찰을 받도록 설득했다. (persuade, see a doctor)',
      'answer',E'I persuaded him to see a doctor.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'persuade+목적어+to부정사 → persuaded him to see a doctor'),
    jsonb_build_object('number',89,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n엄마는 나에게 채소를 더 많이 먹으라고 말씀하셨다. (tell, eat, more vegetables)',
      'answer',E'Mom told me to eat more vegetables.',
      'acceptedAnswers',jsonb_build_array('My mom told me to eat more vegetables.'),
      'explanation',E'tell+목적어+to부정사 → told me to eat more vegetables'),
    jsonb_build_object('number',90,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그 의사는 그녀에게 담배를 피우지 말라고 조언했다. (advise, not, smoke)',
      'answer',E'The doctor advised her not to smoke.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'advise+목적어+not to부정사 → advised her not to smoke'),
    jsonb_build_object('number',91,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n나는 그가 파티에 오기를 원했다. (want, come, the party)',
      'answer',E'I wanted him to come to the party.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'want+목적어+to부정사 → wanted him to come to the party'),
    jsonb_build_object('number',92,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그녀는 그에게 앉아서 기다리라고 말했다. (tell, sit down, wait)',
      'answer',E'She told him to sit down and wait.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'tell+목적어+to부정사+and+동사원형'),
    jsonb_build_object('number',93,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n경찰은 모두에게 실내에 머무르라고 요청했다. (ask, everyone, stay indoors)',
      'answer',E'The police asked everyone to stay indoors.',
      'acceptedAnswers',jsonb_build_array('The police officer asked everyone to stay indoors.'),
      'explanation',E'ask+목적어+to부정사 → asked everyone to stay indoors'),
    jsonb_build_object('number',94,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n우리는 Tom이 늦을 것이라고 예상한다. (expect, be late)',
      'answer',E'We expect Tom to be late.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'expect+목적어+to부정사 → expect Tom to be late'),
    jsonb_build_object('number',95,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그 경찰관은 우리가 그곳을 떠나도 좋다고 허락했다. (allow, leave)',
      'answer',E'The police officer allowed us to leave.',
      'acceptedAnswers',jsonb_build_array('The policeman allowed us to leave.','The officer allowed us to leave.'),
      'explanation',E'allow+목적어+to부정사 → allowed us to leave'),
    jsonb_build_object('number',96,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n엄마는 내가 후식으로 아이스크림 먹는 것을 허락해 주셨다. (allow, eat, ice cream, for dessert)',
      'answer',E'Mom allowed me to eat ice cream for dessert.',
      'acceptedAnswers',jsonb_build_array('My mom allowed me to eat ice cream for dessert.'),
      'explanation',E'allow+목적어+to부정사 → allowed me to eat ice cream for dessert'),
    jsonb_build_object('number',97,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n나는 아무도 그 사실을 모르기를 원한다. (want, anyone, know, the fact)',
      'answer',E'I don''t want anyone to know the fact.',
      'acceptedAnswers',jsonb_build_array('I do not want anyone to know the fact.'),
      'explanation',E'부정문 don''t want+목적어+to부정사 → don''t want anyone to know'),
    jsonb_build_object('number',98,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n그는 그들이 차에 타도록 명령했다. (order, get in the car)',
      'answer',E'He ordered them to get in the car.',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'order+목적어+to부정사 → ordered them to get in the car'),
    jsonb_build_object('number',99,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n선생님은 나에게 수업 시간에 지각하지 말라고 말씀하셨다. (tell, not, be late, class)',
      'answer',E'The teacher told me not to be late for class.',
      'acceptedAnswers',jsonb_build_array('My teacher told me not to be late for class.'),
      'explanation',E'tell+목적어+not to부정사 → told me not to be late for class'),
    jsonb_build_object('number',100,
      'question',E'주어진 힌트를 활용하여 문장을 영작하시오.\n\n자동차가 있으면 어디든 더 쉽게 갈 수 있다. (have a car, enable, get to, easily)',
      'answer',E'Having a car enables you to get anywhere easily.',
      'acceptedAnswers',jsonb_build_array('Having a car enables us to get anywhere easily.','Having a car enables you to get to anywhere easily.','Having a car enables you to get to any place easily.'),
      'explanation',E'enable+목적어+to부정사 → enables you to get anywhere easily')
  );

  a := jsonb_build_array(
    -- Part 1 (Q1-Q10) MCQ answers (1-based index)
    '2','1','2','1','1','1','1','1','1','2',
    -- Part 2 (Q11-Q25)
    E'me to wash',
    E'him to finish',
    E'him not to tell',
    E'me to close',
    E'people to sit',
    E'her to join',
    E'me not to go',
    E'all my friends to come to',
    E'them to practice',
    E'me to return',
    E'me not to swim',
    E'him to pass',
    E'her to drink',
    E'him to work',
    E'her to audition',
    -- Part 3 (Q26-Q40)
    E'told Tom to be quiet',
    E'told Mia not to be late',
    E'asked Jake to help her carry it',
    E'advised him to get more sleep',
    E'allowed him to use her laptop',
    E'told them not to touch the paintings',
    E'to go shopping',
    E'Anna to water the plants',
    E'to go to the dentist',
    E'ordered the soldiers to stop right there',
    E'encouraged me to try the new restaurant',
    E'warned us not to run in the hallway',
    E'to have some more time',
    E'begged me not to tell anyone',
    E'told Kevin to finish his homework first',
    -- Part 4 (Q41-Q55)
    E'not to drive',
    E'to come',
    E'not to call',
    E'not to eat',
    E'not to stay',
    E'to lend',
    E'move',
    E'to submit',
    E'to bring',
    E'to apologize',
    E'not to speak',
    E'to turn off',
    E'to exercise',
    E'to attend',
    E'not to open',
    -- Part 5 (Q56-Q70)
    E'My brother made me wash his car.',
    E'She allowed him to go to the concert alone.',
    E'He ordered the students not to make noise.',
    E'I asked her to sing a song for us.',
    E'My teacher wanted me to study more vocabulary.',
    E'Dad allowed me to go to the movies with friends.',
    E'They expect her to come to the ceremony.',
    E'My father advised me not to use my phone at dinner.',
    E'I told you to come home before 10 p.m.',
    E'Mom allowed me to play video games after school.',
    E'He made me clean the entire classroom.',
    E'My coach asked me to practice every single day.',
    E'The doctor advised me to exercise at least three times a week.',
    E'His wealth enabled him to go abroad for his studies.',
    E'Her family expected her to go to a top university.',
    -- Part 6 (Q71-Q85)
    E'me to clean her bag',
    E'you to leave right now',
    E'me to quit eating snacks',
    E'me to tidy up my',
    E'have him make dinner for',
    E'him not to talk back',
    E'asked us to be on',
    E'advised Jim to stretch before',
    E'helps enable us to track',
    E'I made him wash the',
    E'had her daughter finish',
    E'James expects him to join',
    E'allowed me to go on',
    E'I told my sister to lock',
    E'advised me not to eat',
    -- Part 7 (Q86-Q100)
    E'She wanted me to walk the dog.',
    E'He asked me to be quiet.',
    E'I persuaded him to see a doctor.',
    E'Mom told me to eat more vegetables.',
    E'The doctor advised her not to smoke.',
    E'I wanted him to come to the party.',
    E'She told him to sit down and wait.',
    E'The police asked everyone to stay indoors.',
    E'We expect Tom to be late.',
    E'The police officer allowed us to leave.',
    E'Mom allowed me to eat ice cream for dessert.',
    E'I don''t want anyone to know the fact.',
    E'He ordered them to get in the car.',
    E'The teacher told me not to be late for class.',
    E'Having a car enables you to get anywhere easily.'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    'want+목적어+to부정사 Step 1',
    'want+목적어+to부정사',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
