DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '사역동사 Step 2';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1: 기초 빈칸 채우기 (Q1~Q10) — 5지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
      'question',E'[Part 1] 다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nMy teacher doesn''t let me _______ my cell phone in class.',
      'options',jsonb_build_array('use','to use','using','used','uses'),
      'answer','1',
      'explanation',E'let + 목적어 + 동사원형: let me use가 올바른 형태입니다.'),
    jsonb_build_object('number',2,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nThe funny movie made everyone _______ out loud.',
      'options',jsonb_build_array('laughed','laugh','to laugh','laughing','to laughing'),
      'answer','2',
      'explanation',E'make + 목적어 + 동사원형: made everyone laugh가 올바른 형태입니다.'),
    jsonb_build_object('number',3,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nMom had my little brother _______ his teeth before going to bed.',
      'options',jsonb_build_array('brushes','to brush','brushing','brush','brushed'),
      'answer','4',
      'explanation',E'have + 목적어 + 동사원형: had my little brother brush가 올바른 형태입니다.'),
    jsonb_build_object('number',4,
      'question',E'다음 문장의 빈칸에 들어갈 말로 적절하지 않은 것은?\nThe coach _______ the players run around the field.',
      'options',jsonb_build_array('made','had','let','helped','wanted'),
      'answer','5',
      'explanation',E'wanted는 to부정사를 취하므로 wanted the players to run이 되어야 합니다. make/have/let/help는 모두 목적어 + 동사원형이 가능합니다.'),
    jsonb_build_object('number',5,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nI''ll help you _______ your lost dog.',
      'options',jsonb_build_array('find','finding','found','finds','was found'),
      'answer','1',
      'explanation',E'help + 목적어 + 동사원형: help you find가 올바른 형태입니다.'),
    jsonb_build_object('number',6,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nPlease _______ me know when you are ready to leave.',
      'options',jsonb_build_array('get','tell','ask','let','want'),
      'answer','4',
      'explanation',E'let + 목적어 + 동사원형: let me know는 "알려 주다"라는 의미의 관용 표현입니다.'),
    jsonb_build_object('number',7,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nI got my sister _______ the dishes for me.',
      'options',jsonb_build_array('do','does','to do','doing','did'),
      'answer','3',
      'explanation',E'get + 목적어 + to부정사: got my sister to do가 올바른 형태입니다. get은 사역동사와 달리 to부정사를 취합니다.'),
    jsonb_build_object('number',8,
      'question',E'다음 문장의 빈칸에 들어갈 말로 적절하지 않은 것은?\nThe teacher _______ us to be quiet in the library.',
      'options',jsonb_build_array('asked','told','wanted','allowed','made'),
      'answer','5',
      'explanation',E'make는 목적어 + 동사원형을 취하므로 made us to be는 틀린 표현입니다. ask/tell/want/allow는 모두 목적어 + to부정사가 가능합니다.'),
    jsonb_build_object('number',9,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nThe medicine will help you _______ better soon.',
      'options',jsonb_build_array('feel','felt','feeling','to feeling','feels'),
      'answer','1',
      'explanation',E'help + 목적어 + 동사원형: help you feel이 올바른 형태입니다.'),
    jsonb_build_object('number',10,
      'question',E'다음 문장의 빈칸에 들어갈 말로 적절하지 않은 것은?\nMr. Kim _______ the students finish their homework by Friday.',
      'options',jsonb_build_array('made','had','let','told','helped'),
      'answer','4',
      'explanation',E'told는 to부정사를 취하므로 told the students to finish가 되어야 합니다. make/have/let/help는 모두 목적어 + 동사원형이 가능합니다.'),

    -- ═══════════════════════════════════════════
    -- Part 2: 복합 형태 선택 및 수동 관계 (Q11~Q20) — 5지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
      'question',E'[Part 2] 다음 문장의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?\nShe had him (A) _______ the heavy bags and got him (B) _______ the door.',
      'options',jsonb_build_array('(A) carry - (B) open','(A) to carry - (B) to open','(A) carry - (B) to open','(A) to carry - (B) open','(A) carrying - (B) opened'),
      'answer','3',
      'explanation',E'have + 목적어 + 동사원형: had him carry / get + 목적어 + to부정사: got him to open'),
    jsonb_build_object('number',12,
      'question',E'다음 문장의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?\nI made my son (A) _______ his room and helped him (B) _______ the trash.',
      'options',jsonb_build_array('(A) clean - (B) take out','(A) to clean - (B) to take out','(A) clean - (B) taking out','(A) cleaning - (B) take out','(A) cleaned - (B) taken out'),
      'answer','1',
      'explanation',E'make + 목적어 + 동사원형: made my son clean / help + 목적어 + 동사원형: helped him take out'),
    jsonb_build_object('number',13,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은? (수동 관계에 주의하세요)\nI had my computer _______ by a technician yesterday.',
      'options',jsonb_build_array('repair','to repair','repairing','repaired','repairs'),
      'answer','4',
      'explanation',E'have + 목적어 + 과거분사(p.p.): 목적어(computer)가 수리되는 수동 관계이므로 repaired가 올바릅니다.'),
    jsonb_build_object('number',14,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\nHe had his hair _______ short for the summer.',
      'options',jsonb_build_array('cut','to cut','cutting','cuts','was cut'),
      'answer','1',
      'explanation',E'have + 목적어 + 과거분사(p.p.): 목적어(hair)가 잘리는 수동 관계이며, cut의 과거분사는 cut입니다.'),
    jsonb_build_object('number',15,
      'question',E'다음 문장의 빈칸 (A), (B), (C)에 들어갈 말이 바르게 짝지어진 것은?\n• Let me (A) _______ you.\n• I saw her (B) _______ the street.\n• He expected me (C) _______ the goal.',
      'options',jsonb_build_array('(A) help - (B) cross - (C) score','(A) help - (B) cross - (C) to score','(A) to help - (B) crossing - (C) score','(A) help - (B) crossed - (C) to score','(A) helping - (B) cross - (C) scoring'),
      'answer','2',
      'explanation',E'let + 목적어 + 동사원형: let me help / 지각동사 see + 목적어 + 동사원형: saw her cross / expect + 목적어 + to부정사: expected me to score'),
    jsonb_build_object('number',16,
      'question',E'다음 빈칸에 들어갈 수 없는 동사는?\nI _______ him to solve the math problem.',
      'options',jsonb_build_array('asked','wanted','told','helped','made'),
      'answer','5',
      'explanation',E'make는 목적어 + 동사원형을 취하므로 made him to solve는 틀린 표현입니다. ask/want/tell/help는 모두 목적어 + to부정사가 가능합니다.'),
    jsonb_build_object('number',17,
      'question',E'다음 문장의 빈칸에 공통으로 들어갈 말로 가장 적절한 것은?\n• The news _______ her very happy.\n• My father _______ me a toy robot.\n• The teacher _______ us write a poem.',
      'options',jsonb_build_array('gave','told','made','let','asked'),
      'answer','3',
      'explanation',E'made는 5형식(made her happy), 4형식(made me a robot), 사역동사(made us write) 구문 모두에 쓸 수 있습니다.'),
    jsonb_build_object('number',18,
      'question',E'다음 빈칸에 들어갈 말이 나머지 넷과 다른 하나는?',
      'options',jsonb_build_array('I made him _______ my car.','She let her daughter _______ the piano.','The doctor had the nurse _______ my name.','I got the boy _______ the window.','We helped him _______ the heavy box.'),
      'answer','4',
      'explanation',E'④ got + 목적어 + to부정사(to open)가 와야 합니다. 나머지는 모두 사역동사/help로 동사원형이 들어갑니다.'),
    jsonb_build_object('number',19,
      'question',E'다음 중 밑줄 친 부분의 어형이 바른 것은?',
      'options',jsonb_build_array('Let''s <u>having</u> a party tonight.','He made me <u>to cry</u> yesterday.','I had the waiter <u>brought</u> some water.','She got her husband <u>to buy</u> a gift.','My mom lets me <u>going</u> out now.'),
      'answer','4',
      'explanation',E'④ get + 목적어 + to부정사: got her husband to buy가 올바릅니다.\n① Let''s + 동사원형 → having → have\n② make + 목적어 + 동사원형 → to cry → cry\n③ have + 목적어 + 동사원형 → brought → bring\n⑤ let + 목적어 + 동사원형 → going → go'),
    jsonb_build_object('number',20,
      'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\nI want to _______ my dog to follow my orders.',
      'options',jsonb_build_array('make','have','let','get','help'),
      'answer','4',
      'explanation',E'get + 목적어 + to부정사: get my dog to follow가 올바릅니다. make/have/let은 동사원형을 취하므로 to follow와 어울리지 않습니다.'),

    -- ═══════════════════════════════════════════
    -- Part 3: make 용법 구분 + so that 구문 (Q21~Q40) — 5지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',21,
      'question',E'[Part 3] 다음 밑줄 친 make의 쓰임이 <보기>와 같은 것은?\n\n<보기> Eating healthy food can <u>make</u> you strong.\n\n① I''ll make you some cookies.\n② The sad story makes me cry.\n③ You make me very happy.\n④ My mother is making a dress.\n⑤ He makes a lot of money every month.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'보기와 ③ 모두 make + 목적어 + 형용사 보어 (5형식)입니다. ①은 4형식(make + 간접목적어 + 직접목적어), ②는 사역(make + O + V원형), ④⑤는 3형식(make = 만들다/벌다)입니다.'),
    jsonb_build_object('number',22,
      'question',E'다음 밑줄 친 make의 쓰임이 나머지 넷과 <u>다른</u> 것은?\n\n① She made me do my homework.\n② The teacher made us line up.\n③ My dad made me clean the car.\n④ Mom made me a new suit.\n⑤ The movie made everyone laugh.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'④는 4형식(make + 간접목적어 + 직접목적어: 나에게 새 옷을 만들어 주다)입니다. 나머지는 모두 사역동사(make + O + V원형)입니다.'),
    jsonb_build_object('number',23,
      'question',E'다음 중 밑줄 친 부분의 쓰임이 사역동사인 것은?\n\n① Let''s <u>make</u> a copy of this.\n② He <u>made</u> a nice desk for me.\n③ Don''t <u>make</u> me angry anymore.\n④ What <u>made</u> you change your mind?\n⑤ She <u>made</u> a phone call to her friend.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'④는 make + 목적어(you) + V원형(change)으로 사역동사입니다. ③은 make + O + 형용사(angry)로 5형식이지만 사역이 아닙니다. ①②⑤는 3형식(make = 만들다)입니다.'),
    jsonb_build_object('number',24,
      'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nI study English hard _______ I can travel around the world.',
      'options',jsonb_build_array('so that','because','if','although','but'),
      'answer','1',
      'explanation',E'"세계를 여행할 수 있도록" 목적을 나타내는 접속사 so that이 적절합니다. so that + 주어 + can/could + V원형 구문입니다.'),
    jsonb_build_object('number',25,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nTurn on the light _______ I can see your face.',
      'options',jsonb_build_array('because','so that','when','if','for'),
      'answer','2',
      'explanation',E'"내가 네 얼굴을 볼 수 있도록" 목적을 나타내므로 so that이 적절합니다.'),
    jsonb_build_object('number',26,
      'question',E'다음 중 so that 구문의 시제가 바르게 연결된 것은?\n\nI saved money so that I _______ buy a new bike.',
      'options',jsonb_build_array('can','could','will','am','was'),
      'answer','2',
      'explanation',E'주절이 과거(saved)이므로 so that절의 조동사도 과거형 could를 사용해야 시제가 일치합니다.'),
    jsonb_build_object('number',27,
      'question',E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 것은?\n\nHe ran fast to catch the train.\n= He ran fast _______ he could catch the train.',
      'options',jsonb_build_array('because','if','so that','although','after'),
      'answer','3',
      'explanation',E'to부정사의 부사적 용법(목적)은 so that + 주어 + could로 바꿀 수 있습니다.'),
    jsonb_build_object('number',28,
      'question',E'다음 빈칸에 들어갈 수 있는 말을 <u>모두</u> 고르면?\n\nI went to the library _______ I could study in a quiet place.\n\n① so that\n② in order that\n③ to\n④ so as to\n⑤ because',
      'options',jsonb_build_array('① only','①② only','①②③ only','①②④ only','①②⑤ only'),
      'answer','2',
      'explanation',E'빈칸 뒤에 주어(I) + 조동사(could) + 동사가 있으므로 절을 이끄는 접속사가 필요합니다. so that과 in order that은 + 주어 + 조동사 + V 구조가 가능합니다. to/so as to 뒤에는 V원형만 오므로 불가하고, because는 이유를 나타내므로 적절하지 않습니다.'),
    jsonb_build_object('number',29,
      'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① I study hard so that I can pass the exam.\n② She went to bed early to get up early.\n③ He hurried so that he wouldn''t miss the bus.\n④ I woke up early so that not to be late.\n⑤ Turn off the TV so that I can focus on my work.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'④ "so that not to"는 잘못된 표현입니다. "so as not to be late" 또는 "so that I would not be late"로 써야 합니다. so that 뒤에는 반드시 주어 + 조동사가 와야 합니다.'),
    jsonb_build_object('number',30,
      'question',E'다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: Why do you exercise every day?\nB: I exercise every day _______ I can stay healthy.',
      'options',jsonb_build_array('but','so that','if','because of','or'),
      'answer','2',
      'explanation',E'"건강을 유지할 수 있도록" 목적을 나타내므로 so that이 적절합니다. because of 뒤에는 명사(구)가 오므로 절을 이끌 수 없습니다.'),
    jsonb_build_object('number',31,
      'question',E'다음 중 so that의 쓰임이 ''목적''이 <u>아닌</u> 것은?\n\n① Speak louder so that everyone can hear you.\n② I wear glasses so that I can see better.\n③ He was so tired that he fell asleep immediately.\n④ She saves money so that she can buy a house.\n⑤ I use a map so that I won''t get lost.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'③은 so + 형용사 + that절(결과 구문: 너무 ~해서 …했다)입니다. 나머지는 모두 so that + 주어 + 조동사(목적 구문: ~할 수 있도록)입니다.'),
    jsonb_build_object('number',32,
      'question',E'다음 우리말을 영작한 것으로 가장 적절한 것은?\n\n"다른 사람들이 그를 이해할 수 있도록 그는 천천히 말했다."',
      'options',jsonb_build_array('He spoke slowly because others can understand him.','He spoke slowly so that others could understand him.','He spoke slowly so that others can understand him.','He spoke slowly for others to understand him.','He spoke slowly that others understood him.'),
      'answer','2',
      'explanation',E'주절이 과거(spoke)이므로 so that절에도 과거형 조동사 could를 써야 합니다. ③은 시제 불일치(can), ①은 because(이유), ⑤는 that만으로 목적절을 이끌 수 없습니다.'),
    jsonb_build_object('number',33,
      'question',E'다음 중 의미가 나머지 넷과 <u>다른</u> 것은?\n\n① I went to the market to buy some fruit.\n② I went to the market so that I could buy some fruit.\n③ I went to the market in order to buy some fruit.\n④ I went to the market so as to buy some fruit.\n⑤ I went to the market, and I bought some fruit.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'⑤는 단순히 연속 동작이나 결과를 나타냅니다. 나머지는 모두 "과일을 사기 위해"라는 목적을 나타내는 표현입니다.'),
    jsonb_build_object('number',34,
      'question',E'다음 중 어법상 옳은 문장을 <u>모두</u> 고르면? (정답 2개)\n\n① Sam woke up early so as not to miss the bus.\n② Sam woke up early to not miss the bus.\n③ Sam woke up early so that he would not miss the bus.\n④ Sam woke up early in order to miss the bus.\n⑤ Sam woke up so early that he missed the bus.',
      'options',jsonb_build_array('①③','①④','②③','②⑤','③⑤'),
      'answer','1',
      'explanation',E'① so as not to + V원형은 올바른 부정 목적 표현이고, ③ so that + 주어 + would not도 올바릅니다. ②는 to not(비표준 어순), ④는 의미상 이상(버스를 놓치려고 일찍 일어남), ⑤는 결과 구문으로 의미가 다릅니다.'),
    jsonb_build_object('number',35,
      'question',E'다음 빈칸에 들어갈 말이 순서대로 짝지어진 것은?\n\nHe spoke loudly (A) _______ everyone (B) _______ hear him.',
      'options',jsonb_build_array('(A) so that - (B) could','(A) in order to - (B) could','(A) so that - (B) can','(A) to - (B) can','(A) because - (B) could'),
      'answer','1',
      'explanation',E'주절이 과거(spoke)이므로 so that + 주어 + could가 적절합니다. in order to / to 뒤에는 주어 없이 V원형만 옵니다. can은 현재형이라 시제 불일치입니다.'),
    jsonb_build_object('number',36,
      'question',E'다음 문장의 빈칸에 들어갈 말로 적절하지 <u>않은</u> 것은?\n\nI jog every morning _______ stay in shape.',
      'options',jsonb_build_array('to','so as to','in order to','so that I can','for'),
      'answer','5',
      'explanation',E'for + V원형은 목적을 나타내는 올바른 구조가 아닙니다. to / so as to / in order to + V원형, so that + 주어 + 조동사 + V원형은 모두 목적을 나타낼 수 있습니다.'),
    jsonb_build_object('number',37,
      'question',E'다음 중 문장의 의미가 나머지 넷과 <u>다른</u> 것은?\n\n① He works hard to support his family.\n② He works hard in order to support his family.\n③ He works hard so as to support his family.\n④ He works hard so that he can support his family.\n⑤ He works so hard that he can support his family.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'⑤는 so + 부사 + that절(결과 구문: 너무 열심히 일해서 부양할 수 있다)입니다. 나머지는 모두 "가족을 부양하기 위해"라는 목적을 나타냅니다.'),
    jsonb_build_object('number',38,
      'question',E'다음 빈칸에 들어갈 적절한 조동사를 고르시오.\n\nThe guide walked slowly so that everybody _______ follow him.',
      'options',jsonb_build_array('can','could','will','would','shall'),
      'answer','2',
      'explanation',E'주절이 과거(walked)이므로 so that절의 조동사도 과거형 could를 사용해야 시제가 일치합니다.'),
    jsonb_build_object('number',39,
      'question',E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nHe stepped aside _______ I could pass by.',
      'options',jsonb_build_array('so that','in order to','so as to','because','if'),
      'answer','1',
      'explanation',E'빈칸 뒤에 주어(I) + 조동사(could)가 있으므로 절을 이끄는 접속사 so that이 필요합니다. in order to / so as to 뒤에는 V원형만 옵니다.'),
    jsonb_build_object('number',40,
      'question',E'다음 중 so that 앞에 콤마(,)가 있을 때의 해석으로 가장 적절한 것은?\n\nShe studied hard, so that she passed the test.',
      'options',jsonb_build_array('그녀는 시험에 합격하기 위해 공부했다.','그녀는 공부를 열심히 했고, 그 결과 시험에 합격했다.','그녀는 시험에 합격했음에도 불구하고 공부를 안 했다.','그녀가 시험에 합격한 것은 공부를 했기 때문이다.','그녀는 공부를 너무 열심히 해서 시험에 합격할 수 있었다.'),
      'answer','2',
      'explanation',E'콤마 + so that은 결과(~했고, 그래서 …했다)를 나타냅니다. 콤마가 없는 so that은 목적(~하기 위해)을 나타냅니다.'),

    -- ═══════════════════════════════════════════
    -- Part 4: 통합 실전 어법 (Q41~Q57) — 5지선다 MCQ
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',41,
      'question',E'[Part 4] 다음 중 어법상 옳은 문장은?\n\n① The teacher let us to go home.\n② My dad made me to wash the car.\n③ She had her sister cleaning the room.\n④ I got my brother to help me.\n⑤ Bad movies always make me crying.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'get + 목적어 + to V 구문으로 ④가 올바릅니다. ① let + O + V원형(to go → go), ② make + O + V원형(to wash → wash), ③ have + O + V원형(cleaning → clean), ⑤ make + O + V원형(crying → cry)'),
    jsonb_build_object('number',42,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① I had the mechanic fix my bike.\n② Let me show you my new camera.\n③ The doctor let her to wash her hands.\n④ These rules will help you study well.\n⑤ I made him change his mind.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'let + 목적어 + V원형이므로 "let her to wash"는 틀립니다. "let her wash"가 올바릅니다.'),
    jsonb_build_object('number',43,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① I''ll have her to call you back.\n② They had me repeat the story.\n③ Skipping breakfast made me feeling hungry.\n④ Mom had my sister cleaning her room.\n⑤ Dad will let me to go to the party.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','2',
      'explanation',E'have + 목적어 + V원형이므로 ②가 올바릅니다. ① to call → call, ③ feeling → feel, ④ cleaning → clean, ⑤ to go → go'),
    jsonb_build_object('number',44,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① I can''t make her stop crying.\n② I helped her to do the dishes.\n③ They asked her to come back.\n④ Did you see the baby to smile?\n⑤ We had the man take a picture.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'지각동사 see + 목적어 + V원형이므로 "see the baby to smile"은 틀립니다. "see the baby smile"이 올바릅니다.'),
    jsonb_build_object('number',45,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① My friends got me tell the truth.\n② I had my brother to clean the room.\n③ She helped me wear my new dress.\n④ He can''t make my sister stops crying.\n⑤ Dad got me clean the living room.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'help + 목적어 + V원형이므로 ③이 올바릅니다. ① get + O + to V(tell → to tell), ② have + O + V원형(to clean → clean), ④ make + O + V원형(stops → stop), ⑤ get + O + to V(clean → to clean)'),
    jsonb_build_object('number',46,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① This skirt makes her look fat.\n② Sam made me a happy woman.\n③ This music made me very sadly.\n④ My mom made me do the dishes.\n⑤ Eating too much can make you sick.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'make + 목적어 + 형용사 보어이므로 부사 sadly는 틀립니다. "made me very sad"가 올바릅니다.'),
    jsonb_build_object('number',47,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① The teacher made the boy reads the book.\n② I want to make my dog to carry my bag.\n③ My teacher doesn''t let me be late.\n④ The woman makes the girl picking up the trash.\n⑤ My mother has me doing my homework.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','3',
      'explanation',E'let + 목적어 + V원형(be)이므로 ③이 올바릅니다. ① reads → read, ② to carry → carry, ④ picking → pick, ⑤ doing → do'),
    jsonb_build_object('number',48,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① Mom always makes me to eat vegetables.\n② The teacher had me to clean the floor.\n③ I asked my partner help me.\n④ Mom always lets me play outside.\n⑤ My teacher allowed me use the computer.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'let + 목적어 + V원형(play)이므로 ④가 올바릅니다. ① to eat → eat, ② to clean → clean, ③ help → to help, ⑤ use → to use'),
    jsonb_build_object('number',49,
      'question',E'다음 중 어법상 어색한 문장은? (정답 2개)\n\n① I had my car repair.\n② Let me know your address.\n③ My mom had me wash her car.\n④ He made me to wait for two hours.\n⑤ Mary helped me solve the problem.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','1, 4',
      'explanation',E'① have + 목적어 + p.p.이므로 repair → repaired가 올바릅니다. ④ make + 목적어 + V원형이므로 to wait → wait가 올바릅니다.'),
    jsonb_build_object('number',50,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① I want to make my dog carry my bag.\n② I want my dog to carry my bag.\n③ My mother doesn''t let me read comic books.\n④ The man had me take his picture.\n⑤ The woman wants to let the child to eat candy.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'let + 목적어 + V원형이므로 "let the child to eat"은 틀립니다. "let the child eat"이 올바릅니다.'),
    jsonb_build_object('number',51,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① The boy made the girl falls down.\n② The woman let the child eat candy.\n③ I want to make my dog carries my bag.\n④ My mother let me to read comic books.\n⑤ My teacher has I do my homework.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','2',
      'explanation',E'let + 목적어 + V원형(eat)이므로 ②가 올바릅니다. ① falls → fall, ③ carries → carry, ④ to read → read, ⑤ I → me(목적격)'),
    jsonb_build_object('number',52,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① I woke up early so that I would not be late.\n② He was so wise that he could solve it.\n③ I took a taxi so that I could get there on time.\n④ I studied hard in order to I can pass the test.\n⑤ I left early to avoid the rush hour.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'"in order to + V원형" 또는 "so that + 주어 + V" 구조여야 합니다. "in order to I can"은 구문 혼동입니다.'),
    jsonb_build_object('number',53,
      'question',E'다음 중 어법상 옳은 문장은?\n\n① He tried his best so that he can win the race.\n② She was very careful so that she wouldn''t drop the egg.\n③ Speak too clearly that they can understand you.\n④ We saved lots of money that we could take a vacation.\n⑤ I drove fast so that he can get there in time.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','2',
      'explanation',E'주절이 과거(was)이므로 so that + wouldn''t는 시제 일치가 올바릅니다. ① tried → could, ③ too → so / 구조 오류, ④ so that 누락, ⑤ drove → could'),
    jsonb_build_object('number',54,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① Watch out so as not to fall.\n② I study English so as to travel abroad.\n③ I practiced hard so as to win the game.\n④ I got up early so as not to missing the train.\n⑤ I went to the market so as to buy some food.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','4',
      'explanation',E'so as not to + V원형이므로 "to missing"은 틀립니다. "so as not to miss the train"이 올바릅니다.'),
    jsonb_build_object('number',55,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① She studied hard to get ''A'' in English.\n② They work together for the championship.\n③ I came early so that I could get a better seat.\n④ I did the dishes so that my mom could get rest.\n⑤ He ran to the bus stop in order to he could catch it.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'"in order to + V원형" 구조여야 합니다. "in order to he could"는 구문 혼동입니다.'),
    jsonb_build_object('number',56,
      'question',E'다음 중 밑줄 친 부분의 어법이 어색한 것은?\n\n① The smell of fish makes me <u>feel</u> ill.\n② The teacher made us <u>do</u> a lot of homework.\n③ He yelled at her and made her <u>cry</u>.\n④ My mother made me <u>a sandwich</u>.\n⑤ The falling snow made me <u>feeling</u> happy.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'make + 목적어 + V원형 또는 형용사 보어이므로 "feeling"은 틀립니다. "feel happy" 또는 "happy"가 올바릅니다.'),
    jsonb_build_object('number',57,
      'question',E'다음 중 어법상 어색한 문장은?\n\n① I had my catalog changed from black to color.\n② They made me drink a glass of water.\n③ I watched a man try to get off the train.\n④ She helps me to finish my work.\n⑤ Dad got me wash the car yesterday.',
      'options',jsonb_build_array('①','②','③','④','⑤'),
      'answer','5',
      'explanation',E'get + 목적어 + to V이므로 "got me wash"는 틀립니다. "got me to wash"가 올바릅니다.')
  );

  a := jsonb_build_array(
    '1','2','4','5','1','4','3','5','1','4',
    '3','1','4','1','2','5','3','4','4','4',
    '3','4','4','1','2','2','3','2','4','2',
    '3','2','5','1','1','5','5','2','1','2',
    '4','3','2','4','3','3','3','4','1, 4','5',
    '2','4','2','4','5','5','5'
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    '사역동사 Step 2',
    '사역동사',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
