DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = 'want+목적어+to부정사 Step 3';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1. 괄호 안의 단어를 이용하여 빈칸 완성 (Q1~Q8)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
  'question',E'[Part 1] 다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n엄마는 내가 매일 아침 운동하기를 원하신다. (exercise)\n\nMy mom wants _______________ every morning.',
  'answer',E'me to exercise',
  'similar_answers',jsonb_build_array(),
  'explanation',E'want+목적어+to부정사: wants me to exercise'),
jsonb_build_object('number',2,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n그 선생님은 나에게 더 열심히 공부하라고 말씀하셨다. (study)\n\nThe teacher told _______________ harder.',
  'answer',E'me to study',
  'similar_answers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사: told me to study'),
jsonb_build_object('number',3,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n나는 친구에게 함께 프로젝트를 완성해달라고 요청했다. (finish)\n\nI asked _______________ the project together.',
  'answer',E'my friend to finish',
  'similar_answers',jsonb_build_array(E'him to finish',E'her to finish'),
  'explanation',E'ask+목적어+to부정사: asked my friend to finish'),
jsonb_build_object('number',4,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n의사는 그에게 단 음식을 먹지 말라고 충고했다. (eat)\n\nThe doctor advised _______________ sweet food.',
  'answer',E'him not to eat',
  'similar_answers',jsonb_build_array(),
  'explanation',E'advise+목적어+not to부정사: advised him not to eat'),
jsonb_build_object('number',5,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n우리는 Tom이 늦을 것이라고 예상한다. (be late)\n\nWe expect _______________.',
  'answer',E'Tom to be late',
  'similar_answers',jsonb_build_array(),
  'explanation',E'expect+목적어+to부정사: expect Tom to be late'),
jsonb_build_object('number',6,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n그 경찰관은 우리가 그곳을 떠나도 좋다고 허락했다. (leave)\n\nThe police officer allowed _______________.',
  'answer',E'us to leave there',
  'similar_answers',jsonb_build_array(E'us to leave'),
  'explanation',E'allow+목적어+to부정사: allowed us to leave there'),
jsonb_build_object('number',7,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n그는 나에게 절대 포기하지 말라고 격려했다. (give up)\n\nHe encouraged _______________.',
  'answer',E'me never to give up',
  'similar_answers',jsonb_build_array(E'me not to give up'),
  'explanation',E'encourage+목적어+never to부정사: encouraged me never to give up'),
jsonb_build_object('number',8,
  'question',E'다음 우리말과 일치하도록 괄호 안에 주어진 단어를 이용하여 빈칸에 알맞은 말을 쓰시오.\n\n자동차는 우리가 어디든 더 빠르게 갈 수 있게 해준다. (get to)\n\nCars enable _______________ more quickly.',
  'answer',E'us to get to anywhere',
  'similar_answers',jsonb_build_array(E'us to get anywhere',E'us to get to any place'),
  'explanation',E'enable+목적어+to부정사: enable us to get to anywhere'),

    -- ═══════════════════════════════════════════
    -- Part 2. 괄호 안의 단어를 바르게 배열하여 문장 완성 (Q9~Q16)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',9,
  'question',E'[Part 2] 괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n선생님은 나에게 더 열심히 공부하라고 말씀하셨다.\n(study, the, harder, told, teacher, me, to)',
  'answer',E'The teacher told me to study harder.',
  'similar_answers',jsonb_build_array(E'The teacher told me to study harder'),
  'explanation',E'tell+목적어+to부정사: The teacher told me to study harder.'),
jsonb_build_object('number',10,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n나는 내 친구에게 함께 낚시 가는 것을 요청했다.\n(friend, my, with, to, me, go, I, fishing, asked)',
  'answer',E'I asked my friend to go fishing with me.',
  'similar_answers',jsonb_build_array(E'I asked my friend to go fishing with me'),
  'explanation',E'ask+목적어+to부정사: I asked my friend to go fishing with me.'),
jsonb_build_object('number',11,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n그들은 내가 그 시험에 통과하기를 원했다.\n(want, me, they, pass, exam, the)',
  'answer',E'They wanted me to pass the exam.',
  'similar_answers',jsonb_build_array(E'They wanted me to pass the exam'),
  'explanation',E'want+목적어+to부정사: They wanted me to pass the exam.'),
jsonb_build_object('number',12,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n그는 내게 그것에 대해 걱정하지 말라고 말했다.\n(that, tell, me, not, worry, he, about)',
  'answer',E'He told me not to worry about that.',
  'similar_answers',jsonb_build_array(E'He told me not to worry about that'),
  'explanation',E'tell+목적어+not to부정사: He told me not to worry about that.'),
jsonb_build_object('number',13,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\nMike는 내가 그의 미술 동아리에 가입하도록 설득했다.\n(Mike, me, art, join, persuade, his, club)',
  'answer',E'Mike persuaded me to join his art club.',
  'similar_answers',jsonb_build_array(E'Mike persuaded me to join his art club'),
  'explanation',E'persuade+목적어+to부정사: Mike persuaded me to join his art club.'),
jsonb_build_object('number',14,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n그 의사는 나에게 담배 피는 것을 즉시 그만두라고 충고했다.\n(doctor, advise, stop, smoking, immediately, me, the)',
  'answer',E'The doctor advised me to stop smoking immediately.',
  'similar_answers',jsonb_build_array(E'The doctor advised me to stop smoking immediately'),
  'explanation',E'advise+목적어+to부정사: The doctor advised me to stop smoking immediately.'),
jsonb_build_object('number',15,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n엄마는 내가 새 자전거를 사도록 허락해 주셨다.\n(bike, me, allow, buy, new, Mom, a)',
  'answer',E'Mom allowed me to buy a new bike.',
  'similar_answers',jsonb_build_array(E'Mom allowed me to buy a new bike'),
  'explanation',E'allow+목적어+to부정사: Mom allowed me to buy a new bike.'),
jsonb_build_object('number',16,
  'question',E'괄호 안의 단어를 바르게 배열하여 우리말에 맞는 영어 문장을 완성하시오.\n\n그 남자는 Jenny에게 사진을 찍지 말라고 말했다.\n(Jenny, tell, not, take, the, man, pictures)',
  'answer',E'The man told Jenny not to take pictures.',
  'similar_answers',jsonb_build_array(E'The man told Jenny not to take pictures'),
  'explanation',E'tell+목적어+not to부정사: The man told Jenny not to take pictures.'),

    -- ═══════════════════════════════════════════
    -- Part 3. 대화/인용문 → 문장 전환 (Q17~Q20)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',17,
  'question',E'[Part 3] 괄호 안의 동사를 사용하여 주어진 대화나 인용문을 한 문장으로 바꿔 쓰시오.\n<보기> Alex asked the girl, "Could you open the window?" (tell) → Alex told the girl to open the window.\n\n"Be careful on the road, Jisu." (warn)\n→ Her mom _______________.',
  'answer',E'warned Jisu to be careful on the road',
  'similar_answers',jsonb_build_array(E'warned Jisu to be careful on the road.'),
  'explanation',E'warn+목적어+to부정사: warned Jisu to be careful on the road'),
jsonb_build_object('number',18,
  'question',E'괄호 안의 동사를 사용하여 주어진 대화나 인용문을 한 문장으로 바꿔 쓰시오.\n\n"Don''t forget to bring your ID card, Daniel." (remind)\n→ She _______________.',
  'answer',E'reminded Daniel to bring his ID card',
  'similar_answers',jsonb_build_array(E'reminded Daniel to bring his ID card.',E'reminded Daniel not to forget to bring his ID card'),
  'explanation',E'remind+목적어+to부정사: reminded Daniel to bring his ID card'),
jsonb_build_object('number',19,
  'question',E'괄호 안의 동사를 사용하여 주어진 대화나 인용문을 한 문장으로 바꿔 쓰시오.\n\n"You should give up eating too much sugar." (advise)\n→ The dentist _______________.',
  'answer',E'advised him to give up eating too much sugar',
  'similar_answers',jsonb_build_array(E'advised him to give up eating too much sugar.',E'advised her to give up eating too much sugar'),
  'explanation',E'advise+목적어+to부정사: advised him to give up eating too much sugar'),
jsonb_build_object('number',20,
  'question',E'괄호 안의 동사를 사용하여 주어진 대화나 인용문을 한 문장으로 바꿔 쓰시오.\n\n"Come out with your hands up!" (order)\n→ The police officer _______________.',
  'answer',E'ordered the suspect to come out with his hands up',
  'similar_answers',jsonb_build_array(E'ordered the suspect to come out with his hands up.',E'ordered him to come out with his hands up',E'ordered them to come out with their hands up'),
  'explanation',E'order+목적어+to부정사: ordered the suspect to come out with his hands up')
,
-- Part 3 continued (Q21~Q24): 직접화법 → want/allow 구문 전환
jsonb_build_object('number',21,
  'question',E'다음 직접화법을 간접화법으로 바꾸어 빈칸을 완성하시오.\n"Let''s go to the concert," says Amy.\n→ Amy wants _______________.',
  'answer',E'Amy wants to go to the concert.',
  'similar_answers',jsonb_build_array('to go to the concert','to go to the concert.'),
  'explanation',E'Amy가 자신이 하고 싶은 일을 말하므로 want + to부정사 구문을 사용합니다. "Let''s go"는 Amy wants to go로 전환됩니다.'),
jsonb_build_object('number',22,
  'question',E'다음 직접화법을 간접화법으로 바꾸어 빈칸을 완성하시오.\n"Min, could you please help me with this report?" asks her manager.\n→ Min''s manager wants _______________.',
  'answer',E'Min''s manager wants her to help with the report.',
  'similar_answers',jsonb_build_array('her to help with the report','her to help with the report.','her to help with this report','her to help with this report.','Min''s manager wants her to help with this report.'),
  'explanation',E'매니저가 Min에게 요청하므로 want + 목적어(her) + to부정사 구문을 사용합니다. Min은 여성이므로 목적격 her를 씁니다.'),
jsonb_build_object('number',23,
  'question',E'다음 직접화법을 간접화법으로 바꾸어 빈칸을 완성하시오.\n"I don''t want to wake up early tomorrow," says Kevin.\n→ Kevin doesn''t want _______________.',
  'answer',E'Kevin doesn''t want to wake up early tomorrow.',
  'similar_answers',jsonb_build_array('to wake up early tomorrow','to wake up early tomorrow.'),
  'explanation',E'Kevin이 자신의 의지를 부정하므로 doesn''t want + to부정사 구문을 사용합니다. 주어가 본인이므로 목적어 없이 바로 to부정사가 옵니다.'),
jsonb_build_object('number',24,
  'question',E'다음 직접화법을 간접화법으로 바꾸어 빈칸을 완성하시오.\n"You can stay at my house tonight." (allow)\n→ She _______________.',
  'answer',E'She allowed him to stay at her house that night.',
  'similar_answers',jsonb_build_array('allowed him to stay at her house that night','allowed him to stay at her house that night.','allowed him to stay at her house tonight','allowed him to stay at her house tonight.'),
  'explanation',E'allow + 목적어 + to부정사 구문을 사용합니다. 직접화법의 my house → her house, tonight → that night로 전환합니다.'),

-- Part 4. 오류 찾아 고쳐 쓰기 (Q25~Q32)
jsonb_build_object('number',25,
  'question',E'[Part 4] 다음 문장에서 어법상 어색한 부분을 찾아 전체 문장을 바르게 고쳐 쓰시오.\nMy father made me to clean the garage after school.',
  'answer',E'My father made me clean the garage after school.',
  'similar_answers',jsonb_build_array('My father made me clean the garage after school'),
  'explanation',E'사역동사 make는 목적격보어로 동사원형을 취합니다. to clean → clean으로 고쳐야 합니다. make + 목적어 + 동사원형 패턴입니다.'),
jsonb_build_object('number',26,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 전체 문장을 바르게 고쳐 쓰시오.\nShe allowed him go to the concert without a ticket.',
  'answer',E'She allowed him to go to the concert without a ticket.',
  'similar_answers',jsonb_build_array('She allowed him to go to the concert without a ticket'),
  'explanation',E'allow는 5형식 동사로 목적격보어에 to부정사를 취합니다. go → to go로 고쳐야 합니다. allow + 목적어 + to부정사 패턴입니다.'),
jsonb_build_object('number',27,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 전체 문장을 바르게 고쳐 쓰시오.\nHe ordered the soldiers to not leave the building.',
  'answer',E'He ordered the soldiers not to leave the building.',
  'similar_answers',jsonb_build_array('He ordered the soldiers not to leave the building'),
  'explanation',E'to부정사의 부정은 not을 to 앞에 놓습니다. to not leave → not to leave로 고쳐야 합니다.'),
jsonb_build_object('number',28,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 전체 문장을 바르게 고쳐 쓰시오.\nMy teacher wanted me studying harder for the finals.',
  'answer',E'My teacher wanted me to study harder for the finals.',
  'similar_answers',jsonb_build_array('My teacher wanted me to study harder for the finals'),
  'explanation',E'want는 목적격보어로 to부정사를 취합니다. studying → to study로 고쳐야 합니다. want + 목적어 + to부정사 패턴입니다.'),
jsonb_build_object('number',29,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 전체 문장을 바르게 고쳐 쓰시오.\nHer family expected her went to a top university.',
  'answer',E'Her family expected her to go to a top university.',
  'similar_answers',jsonb_build_array('Her family expected her to go to a top university'),
  'explanation',E'expect는 목적격보어로 to부정사를 취합니다. went → to go로 고쳐야 합니다. expect + 목적어 + to부정사 패턴입니다.'),
jsonb_build_object('number',30,
  'question',E'다음 문장 (1), (2), (3)에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n(1) She allowed we to enter the building.\n(2) I told her goes to the science camp.\n(3) This app enable us contacting family and friends easily.',
  'answer',E'(1) we → us / (2) goes → to go / (3) contacting → to contact',
  'similar_answers',jsonb_build_array('(1) we→us / (2) goes→to go / (3) contacting→to contact','we → us / goes → to go / contacting → to contact','(1) us (2) to go (3) to contact'),
  'explanation',E'(1) allow + 목적어(목적격) + to부정사이므로 we → us. (2) tell + 목적어 + to부정사이므로 goes → to go. (3) enable + 목적어 + to부정사이므로 contacting → to contact.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','us','acceptedAnswers',jsonb_build_array('we → us','we→us')),
    jsonb_build_object('label','(2)','answer','to go','acceptedAnswers',jsonb_build_array('goes → to go','goes→to go')),
    jsonb_build_object('label','(3)','answer','to contact','acceptedAnswers',jsonb_build_array('contacting → to contact','contacting→to contact'))
  )),
jsonb_build_object('number',31,
  'question',E'다음 글에서 어법상 어색한 것을 2개 찾아 그 기호를 쓰고 바르게 고쳐 쓰시오.\nLast weekend, Suji called me and asked (1)if I could go to the bookstore with her. I agreed. Suji wanted to buy pens and books. I couldn''t understand (2)why she needed them all. When I asked her (3)how much did they cost, she said she didn''t care. Also, I was not sure (4)how long she would keep the plants. Anyway, she bought all she wanted. I think (5)she should not bought them at that time.',
  'answer',E'(3) how much did they cost → how much they cost / (5) should not bought → should not have bought',
  'similar_answers',jsonb_build_array('(3) how much they cost / (5) should not have bought','3) how much did they cost → how much they cost / 5) should not bought → should not have bought','(3) how much they cost, (5) should not have bought'),
  'explanation',E'(3) 간접의문문은 「의문사 + 주어 + 동사」 어순이므로 how much did they cost → how much they cost. (5) should + have p.p. 구문이므로 should not bought → should not have bought.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(3)','answer','how much they cost','acceptedAnswers',jsonb_build_array('how much did they cost → how much they cost')),
    jsonb_build_object('label','(5)','answer','should not have bought','acceptedAnswers',jsonb_build_array('should not bought → should not have bought'))
  )),
jsonb_build_object('number',32,
  'question',E'다음 문장에서 어법상 어색한 부분을 각각 찾아 기호를 쓰고 바르게 고쳐 쓰시오.\n(A) He wants her to not leave now.\n(B) My coach asked me practice harder every day.\n(C) The teacher advised us not to run in the hallway.\n(D) Dad allowed me playing computer games after dinner.\n(E) My mother wants that I get up early every morning.',
  'answer',E'(A) to not leave → not to leave / (B) practice → to practice / (D) playing → to play / (E) wants that I get → wants me to get',
  'similar_answers',jsonb_build_array('(A) not to leave / (B) to practice / (D) to play / (E) wants me to get','A) to not leave → not to leave / B) practice → to practice / D) playing → to play / E) wants that I get → wants me to get','(A) not to leave (B) to practice (D) to play (E) wants me to get'),
  'explanation',E'(A) to부정사의 부정은 not + to부정사 → not to leave. (B) ask + 목적어 + to부정사 → to practice. (C)는 올바른 문장. (D) allow + 목적어 + to부정사 → to play. (E) want + 목적어 + to부정사 → wants me to get.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(A)','answer','not to leave','acceptedAnswers',jsonb_build_array('to not leave → not to leave')),
    jsonb_build_object('label','(B)','answer','to practice','acceptedAnswers',jsonb_build_array('practice → to practice')),
    jsonb_build_object('label','(D)','answer','to play','acceptedAnswers',jsonb_build_array('playing → to play')),
    jsonb_build_object('label','(E)','answer','wants me to get','acceptedAnswers',jsonb_build_array('wants that I get → wants me to get'))
  )),

-- Part 5. 두 문장의 의미가 같도록 빈칸 채우기 (Q33~Q38)
jsonb_build_object('number',33,
  'question',E'[Part 5] 두 문장의 의미가 같도록 빈칸을 채우시오.\nThe coach said to us, "Practice harder every day."\n= The coach told us ___ every day.',
  'answer',E'to practice harder',
  'similar_answers',jsonb_build_array('to practice harder every day'),
  'explanation',E'직접화법 "Practice harder"를 간접화법으로 전환할 때 tell + 목적어 + to부정사를 사용합니다. told us to practice harder.'),
jsonb_build_object('number',34,
  'question',E'두 문장의 의미가 같도록 빈칸을 채우시오.\nI ordered that they should keep the door closed.\n= I ordered ___ closed.',
  'answer',E'them to keep the door',
  'similar_answers',jsonb_build_array('them to keep the door closed'),
  'explanation',E'that절을 5형식 구문으로 전환합니다. order + 목적어(them) + to부정사(to keep the door) 패턴입니다.'),
jsonb_build_object('number',35,
  'question',E'두 문장의 의미가 같도록 빈칸을 채우시오.\nI told him that he should wash his hands before eating.\n= I told ___ before eating.',
  'answer',E'him to wash his hands',
  'similar_answers',jsonb_build_array('him to wash his hands before eating'),
  'explanation',E'that절을 to부정사 구문으로 전환합니다. tell + 목적어(him) + to부정사(to wash his hands) 패턴입니다.'),
jsonb_build_object('number',36,
  'question',E'두 문장의 의미가 같도록 빈칸을 채우시오.\nDad allowed me to go to the movies.\n= Dad let me ___.',
  'answer',E'go to the movies',
  'similar_answers',jsonb_build_array('go to the movies.'),
  'explanation',E'allow + 목적어 + to부정사 = let + 목적어 + 동사원형. let은 사역동사이므로 to 없이 동사원형 go를 사용합니다.'),
jsonb_build_object('number',37,
  'question',E'두 문장의 의미가 같도록 빈칸을 채우시오.\nMy mom said to me, "Don''t play computer games after 10."\n= My mom told ___ after 10.',
  'answer',E'me not to play computer games',
  'similar_answers',jsonb_build_array('me not to play computer games after 10'),
  'explanation',E'부정 명령문을 간접화법으로 전환할 때 tell + 목적어 + not to부정사를 사용합니다. told me not to play computer games.'),
jsonb_build_object('number',38,
  'question',E'두 문장의 의미가 같도록 빈칸을 채우시오.\nShe said to him, "You can borrow my laptop."\n= She allowed ___ her laptop.',
  'answer',E'him to borrow',
  'similar_answers',jsonb_build_array('him to borrow her laptop'),
  'explanation',E'"You can borrow"는 허락의 의미이므로 allow + 목적어(him) + to부정사(to borrow)로 전환합니다.'),

-- Part 6. 상황 읽고 빈칸 완성 (Q39~Q40)
jsonb_build_object('number',39,
  'question',E'[Part 6] 다음 상황을 읽고 빈칸을 완성하시오.\nCinderella: Make a dress for me. Please take me to the party.\nMs. Fairy: Come back home by midnight. Wear your glass shoes.\n<보기> Cinderella wanted Ms. Fairy to make a dress for her.\n\n(1) Cinderella wanted Ms. Fairy _______________.\n(2) Ms. Fairy told Cinderella _______________.\n(3) Ms. Fairy told Cinderella _______________.',
  'answer',E'(1) to take her to the party / (2) to come back home by midnight / (3) to wear her glass shoes',
  'similar_answers',jsonb_build_array('to take her to the party / to come back home by midnight / to wear her glass shoes','(1) to take her to the party (2) to come back home by midnight (3) to wear her glass shoes'),
  'explanation',E'(1) want + 목적어 + to부정사: take me → to take her. (2) tell + 목적어 + to부정사: Come back → to come back home by midnight. (3) tell + 목적어 + to부정사: Wear your → to wear her glass shoes.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','to take her to the party','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','to come back home by midnight','acceptedAnswers',jsonb_build_array('to come back by midnight')),
    jsonb_build_object('label','(3)','answer','to wear her glass shoes','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',40,
  'question',E'다음 메모를 읽고 빈칸을 완성하시오.\nBobby,\nWe''ll be home late.\n(1) 개에게 먹이를 줄 것\n(2) 컴퓨터 게임을 하지 말 것\nLove, Mom and Dad\n\n(1) Bobby''s parents want _______________.\n(2) Bobby''s parents want _______________.',
  'answer',E'(1) him to feed the dog / (2) him not to play computer games',
  'similar_answers',jsonb_build_array('him to feed the dog / him not to play computer games','(1) him to feed the dog (2) him not to play computer games'),
  'explanation',E'(1) want + 목적어(him) + to부정사(to feed the dog). (2) 부정은 not + to부정사: want + him + not to play computer games.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','him to feed the dog','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','him not to play computer games','acceptedAnswers',jsonb_build_array())
  ))
,
    -- ═══════════════════════════════════════════
    -- Part 6 continued. 상황 / 메모 기반 완성하기 (Q41~Q44)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',41,
  'question',E'[Part 6] 다음 대화를 읽고 빈칸을 완성하시오.\n\nMom: Hana, turn off the computer.\nDad: Duna, you should clean your room.\nHana: Dad, would you wash the dishes?\nDuna: Mom, will you help me fix the dress?\n\n<보기> Mom wants Hana to turn off the computer.\n\n(1) Dad _______________.\n(2) Hana _______________.\n(3) Duna _______________.',
  'answer',E'wants Duna to clean her room / wants her dad to wash the dishes / wants her mom to help her fix the dress',
  'similar_answers',jsonb_build_array(E'asks Duna to clean her room / asks her dad to wash the dishes / asks her mom to help her fix the dress',E'wants Duna to clean her room / wants Dad to wash the dishes / wants Mom to help her fix the dress',E'asks Duna to clean her room / asks Dad to wash the dishes / asks Mom to help her fix the dress'),
  'explanation',E'want/ask+목적어+to부정사 구문. (1) Dad wants Duna to clean her room (2) Hana wants her dad to wash the dishes (3) Duna wants her mom to help her fix the dress. asks도 정답으로 인정.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','wants Duna to clean her room','acceptedAnswers',jsonb_build_array('asks Duna to clean her room')),
    jsonb_build_object('label','(2)','answer','wants her dad to wash the dishes','acceptedAnswers',jsonb_build_array('asks her dad to wash the dishes','wants Dad to wash the dishes','asks Dad to wash the dishes')),
    jsonb_build_object('label','(3)','answer','wants her mom to help her fix the dress','acceptedAnswers',jsonb_build_array('asks her mom to help her fix the dress','wants Mom to help her fix the dress','asks Mom to help her fix the dress'))
  )),
jsonb_build_object('number',42,
  'question',E'다음 메모들을 읽고 빈칸을 완성하시오.\n\nPlease come home early. - Mom\nWhy don''t you join the drama club? - Somi\nCan you bring some snacks to the party? - Jake\nDon''t be late for soccer practice. - Coach Kim\n\n<보기> Mom told me to come home early.\n\n(1) Jake asked _______________.\n(2) Somi asked _______________.\n(3) Coach Kim told _______________.',
  'answer',E'me to bring some snacks to the party / me to join the drama club / me not to be late for soccer practice',
  'similar_answers',jsonb_build_array(),
  'explanation',E'ask/tell+목적어+to부정사 구문. (1) Jake asked me to bring some snacks to the party. (2) Somi asked me to join the drama club. (3) Coach Kim told me not to be late for soccer practice. 부정 명령은 not to로 전환.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','me to bring some snacks to the party','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','me to join the drama club','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(3)','answer','me not to be late for soccer practice','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',43,
  'question',E'다음 편지를 읽고 빈칸을 완성하시오.\n\nAlice,\nI''m leaving for Jeju-do now. Water the flowers every morning. And walk the dog in the afternoon. Please take care of yourself.\nLove, Mom\n\n→ Alice''s mother wants her _______________ and _______________.',
  'answer',E'to water the flowers every morning / to walk the dog in the afternoon',
  'similar_answers',jsonb_build_array(),
  'explanation',E'want+목적어+to부정사 구문. 편지 내용의 명령문을 to부정사로 전환: wants her to water the flowers every morning and to walk the dog in the afternoon.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','to water the flowers every morning','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','to walk the dog in the afternoon','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',44,
  'question',E'다음 표를 보고 빈칸을 완성하시오.\n\nJudy가 지난주에 한 일\n월요일: 여동생 돌보기\n화요일: 정원에 꽃에 물 주기\n토요일: 친구와 쇼핑 가기\n일요일: 쿠키 만들기\n\n(1) Judy''s mom wanted her _______________ on Monday. (want)\n(2) Judy''s mom made her _______________ on Tuesday. (make)\n(3) Judy''s mom allowed her _______________ on Saturday. (allow)\n(4) Judy''s mom helped her _______________ on Sunday. (help)',
  'answer',E'to take care of her sister / water flowers in the garden / to go shopping with her friend / make some cookies',
  'similar_answers',jsonb_build_array(E'to take care of her sister / water the flowers in the garden / to go shopping with her friend / make some cookies',E'to take care of her sister / water flowers in the garden / to go shopping with her friend / to make some cookies',E'to take care of her younger sister / water flowers in the garden / to go shopping with her friend / make some cookies'),
  'explanation',E'동사별 목적격 보어 형태 구분. (1) want+to부정사: to take care of her sister (2) make(사역)+원형부정사: water flowers in the garden (3) allow+to부정사: to go shopping with her friend (4) help+원형부정사(또는 to부정사): make some cookies. help는 원형/to부정사 모두 가능.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','to take care of her sister','acceptedAnswers',jsonb_build_array('to take care of her younger sister')),
    jsonb_build_object('label','(2)','answer','water flowers in the garden','acceptedAnswers',jsonb_build_array('water the flowers in the garden')),
    jsonb_build_object('label','(3)','answer','to go shopping with her friend','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(4)','answer','make some cookies','acceptedAnswers',jsonb_build_array('to make some cookies'))
  )),

    -- ═══════════════════════════════════════════
    -- Part 7. 조건 영작 (Q45~Q56)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',45,
  'question',E'[Part 7] 다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그의 엄마는 그에게 앉아서 기다리라고 말했다.\n[조건] tell 사용 / sit과 wait 모두 포함',
  'answer',E'His mom told him to sit and wait.',
  'similar_answers',jsonb_build_array(E'His mother told him to sit and wait.',E'His mom told him to sit down and wait.'),
  'explanation',E'tell+목적어+to부정사 구문. sit과 wait를 and로 연결: told him to sit and wait.'),
jsonb_build_object('number',46,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그녀는 내게 자신의 컴퓨터를 쓰지 말라고 말했다.\n[조건] tell과 not 사용',
  'answer',E'She told me not to use her computer.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'tell+목적어+not to부정사 구문. 부정 명령 전달: told me not to use her computer.'),
jsonb_build_object('number',47,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n나는 그가 의사에게 진찰을 받도록 설득했다.\n[조건] persuade와 see 사용',
  'answer',E'I persuaded him to see a doctor.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'persuade+목적어+to부정사 구문. see a doctor = 의사에게 진찰을 받다.'),
jsonb_build_object('number',48,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n우리 부모님은 내가 늦게까지 밖에 있는 것을 허락하지 않는다.\n[조건] allow와 stay, late를 사용할 것',
  'answer',E'My parents don''t allow me to stay out late.',
  'similar_answers',jsonb_build_array(E'My parents do not allow me to stay out late.'),
  'explanation',E'allow+목적어+to부정사 구문의 부정. don''t allow me to stay out late = 늦게까지 밖에 있는 것을 허락하지 않다.'),
jsonb_build_object('number',49,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그 의사는 그에게 담배를 끊으라고 충고했다.\n[조건] advise 사용 / 7단어로 쓸 것',
  'answer',E'The doctor advised him to stop smoking.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'advise+목적어+to부정사 구문. 7단어: The(1) doctor(2) advised(3) him(4) to(5) stop(6) smoking(7).'),
jsonb_build_object('number',50,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그녀는 그녀의 아들에게 그의 방을 청소하라고 말했다.\n[조건] tell 사용 / 8단어로 쓸 것',
  'answer',E'She told her son to clean his room.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사 구문. 8단어: She(1) told(2) her(3) son(4) to(5) clean(6) his(7) room(8).'),
jsonb_build_object('number',51,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n나의 선생님은 나에게 책을 갖고 오라고 말씀하셨다.\n[조건] tell 사용 / (My teacher, to, me, bring, a book) 단어만 사용',
  'answer',E'My teacher told me to bring a book.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'tell+목적어+to부정사 구문. 주어진 단어를 올바른 어순으로 배열: My teacher told me to bring a book.'),
jsonb_build_object('number',52,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n나의 부모님은 내가 나의 친구들을 돕기를 원하신다.\n[조건] want와 help 사용',
  'answer',E'My parents want me to help my friends.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'want+목적어+to부정사 구문. want me to help my friends = 내가 친구들을 돕기를 원하다.'),
jsonb_build_object('number',53,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n인터넷은 내가 정보를 빨리 찾는 것을 가능하게 한다.\n[조건] enable 사용',
  'answer',E'The Internet enables me to find information quickly.',
  'similar_answers',jsonb_build_array(E'The internet enables me to find information quickly.'),
  'explanation',E'enable+목적어+to부정사 구문. enables me to find information quickly = 내가 정보를 빨리 찾는 것을 가능하게 하다.'),
jsonb_build_object('number',54,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n엄마는 내가 공부하는 데 많은 시간을 할애하기를 원하신다.\n[조건] (my mother, spend, a lot of) 포함 / 11단어로 쓸 것',
  'answer',E'My mother wants me to spend a lot of time studying.',
  'similar_answers',jsonb_build_array(),
  'explanation',E'want+목적어+to부정사 구문 + spend+시간+~ing. 11단어: My(1) mother(2) wants(3) me(4) to(5) spend(6) a(7) lot(8) of(9) time(10) studying(11).'),
jsonb_build_object('number',55,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n이 프로젝트는 사람들에게 숲을 보호하고 수백만 그루의 나무를 심도록 요청하고 있다.\n[조건] ask 사용 / protect와 plant 포함',
  'answer',E'This project is asking people to protect the forest and plant millions of trees.',
  'similar_answers',jsonb_build_array(E'This project is asking people to protect forests and plant millions of trees.',E'This project asks people to protect the forest and plant millions of trees.'),
  'explanation',E'ask+목적어+to부정사 구문. 현재진행형 is asking 사용. protect와 plant를 and로 연결.'),
jsonb_build_object('number',56,
  'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n비행기들은 내가 가고 싶은 장소들에 아주 빠르게 도달하는 것을 가능하게 한다.\n[조건] enable 구문 사용 / get과 places, that 포함',
  'answer',E'Airplanes enable me to get to places that I want to go to very fast.',
  'similar_answers',jsonb_build_array(E'Airplanes enable me to get to places that I want to go very fast.',E'Planes enable me to get to places that I want to go to very fast.'),
  'explanation',E'enable+목적어+to부정사 구문. 관계대명사 that을 사용해 places 수식: places that I want to go to.'),

    -- ═══════════════════════════════════════════
    -- Part 8. 지문 / 실전 서술형 (Q57~Q60)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',57,
  'question',E'[Part 8] 다음 두 문장의 의미가 같도록 주어진 단어를 활용하여 다시 쓰시오.\n\n<보기> She said to us "Please come to my house for dinner." (invite)\n→ She invited us to come to her house for dinner.\n\n(1) My mother said to me, "Drink warm milk before you sleep." (want)\n→ My mother ___.\n(2) The teacher said to him, "You can go home and take a rest." (let)\n→ The teacher ___.\n(3) The woman said to me, "You can have some cake." (allow)\n→ The woman ___.',
  'answer',E'wanted me to drink warm milk before I slept / let him go home and take a rest / allowed me to have some cake',
  'similar_answers',jsonb_build_array(E'wanted me to drink warm milk before I slept / let him go home and take a rest / allowed me to have some cake.',E'wants me to drink warm milk before I sleep / let him go home and take a rest / allowed me to have some cake'),
  'explanation',E'동사별 목적격 보어 형태 구분. (1) want+to부정사: wanted me to drink warm milk before I slept (2) let+원형부정사: let him go home and take a rest (3) allow+to부정사: allowed me to have some cake.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','wanted me to drink warm milk before I slept','acceptedAnswers',jsonb_build_array('wants me to drink warm milk before I sleep')),
    jsonb_build_object('label','(2)','answer','let him go home and take a rest','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(3)','answer','allowed me to have some cake','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',58,
  'question',E'다음 대화의 내용에 맞게 빈칸에 알맞은 말을 쓰시오.\n\nCinderella: Take me to the party, please.\nMs. Fairy: Don''t forget to come back home by midnight.\n\n(A) Cinderella tells ___ ___ her to the party.\n(B) Ms. Fairy asks ___ ___ home by midnight.',
  'answer',E'Ms. Fairy / to take / Cinderella / to come back',
  'similar_answers',jsonb_build_array(E'Ms. Fairy to take / Cinderella to come back'),
  'explanation',E'tell/ask+목적어+to부정사 구문. (A) Cinderella tells Ms. Fairy to take her to the party. (B) Ms. Fairy asks Cinderella to come back home by midnight.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(A-1)','answer','Ms. Fairy','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(A-2)','answer','to take','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(B-1)','answer','Cinderella','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(B-2)','answer','to come back','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',59,
  'question',E'다음 런던 여행 안내 책자를 읽고, 주어진 단어를 알맞게 변형하여 빈칸을 완성하시오.\n\nWe don''t want you (1)___(drive) into London during rush hour. If you don''t want to be stuck in traffic, we''d ask you (2)___(travel) by train. We''d expect you (3)___(buy) a saver ticket because it is cheaper. But railway companies don''t allow you (4)___(use) saver tickets before ten o''clock. This is to tell people (5)___(take) a later train.',
  'answer',E'to drive / to travel / to buy / to use / to take',
  'similar_answers',jsonb_build_array(),
  'explanation',E'want/ask/expect/allow/tell 모두 목적어+to부정사 구문을 취하는 동사. 모든 빈칸에 to+동사원형을 넣는다.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','to drive','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','to travel','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(3)','answer','to buy','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(4)','answer','to use','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(5)','answer','to take','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',60,
  'question',E'다음 블로그 글의 내용에 맞게 조건에 맞게 빈칸을 완성하시오.\n\n블로그의 두 가지 장점\n• 우리는 다른 사람들과 정보를 공유할 수 있다.\n• 우리는 우리의 개성을 표현할 수 있다.\n\nI want to tell you about blogs. There are two benefits of blogs.\nOne benefit is that (1)_______________.\nThe other benefit is that (2)_______________.\n[조건] enable 동사를 반드시 사용할 것',
  'answer',E'blogs enable us to share information with others / blogs enable us to express our personality',
  'similar_answers',jsonb_build_array(E'blogs enable us to share information with other people / blogs enable us to express our personalities',E'blogs enable us to share information with others / blogs enable us to express our individuality'),
  'explanation',E'enable+목적어+to부정사 구문. (1) blogs enable us to share information with others (2) blogs enable us to express our personality.',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','blogs enable us to share information with others','acceptedAnswers',jsonb_build_array('blogs enable us to share information with other people')),
    jsonb_build_object('label','(2)','answer','blogs enable us to express our personality','acceptedAnswers',jsonb_build_array('blogs enable us to express our personalities','blogs enable us to express our individuality'))
  ))
  );

  a := jsonb_build_array();

  INSERT INTO naesin_templates (title, template_topic, category, mode, questions, answer_key)
  VALUES ('want+목적어+to부정사 Step 3', 'want+목적어+to부정사', 'problem', 'interactive', q, a);
END;
$$;
