-- 접속사 since/though Step 2 — 100문항 (객관식)
-- template_topic: 접속사 since/though
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'접속사 since/though Step 2';

  q := jsonb_build_array(
    -- ============================================================
    -- Part 1: 빈칸 채우기 (Q1–Q8)
    -- ============================================================
    jsonb_build_object('number',1,
      'question',E'[Part 1] 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ everyone played well, we lost the game.',
      'options',jsonb_build_array(E'As if',E'Because',E'Unless',E'Although',E'Since'),
      'answer',E'4',
      'explanation',E'Although — 양보: ~에도 불구하고. 모두가 잘 했음에도 졌다는 양보의 의미.'),
    jsonb_build_object('number',2,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ it was too dark for him to go back to town, he stayed there.',
      'options',jsonb_build_array(E'Although',E'Since',E'Unless',E'Even if',E'While'),
      'answer',E'2',
      'explanation',E'Since — 이유: ~때문에. 너무 어두워서 마을로 돌아갈 수 없었기 때문에 그곳에 머물렀다.'),
    jsonb_build_object('number',3,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nOur car wouldn''t start, so we were late.\n= __________ our car wouldn''t start, we were late.',
      'options',jsonb_build_array(E'If',E'When',E'Since',E'Before',E'Though'),
      'answer',E'3',
      'explanation',E'Since — 이유: so(그래서)를 사용한 원인-결과 문장을 since(~때문에)로 바꿔 쓸 수 있다.'),
    jsonb_build_object('number',4,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ the wind was blowing hard, it wasn''t very cold.',
      'options',jsonb_build_array(E'As if',E'Because',E'Since',E'Although',E'Unless'),
      'answer',E'4',
      'explanation',E'Although — 양보: 바람이 세게 불었지만 그다지 춥지 않았다. 예상과 반대되는 결과이므로 양보 접속사가 적절하다.'),
    jsonb_build_object('number',5,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nA: Did you go to bed early last night?\nB: I stayed up late __________ I was very exhausted.',
      'options',jsonb_build_array(E'despite',E'unless',E'since',E'because',E'although'),
      'answer',E'5',
      'explanation',E'although — 양보: 매우 지쳤음에도 불구하고 늦게까지 깨어 있었다.'),
    jsonb_build_object('number',6,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nA: What did Rachel do last weekend?\nB: She went hiking __________ it was snowy and chilly.',
      'options',jsonb_build_array(E'because',E'unless',E'since',E'although',E'if'),
      'answer',E'4',
      'explanation',E'although — 양보: 눈이 오고 추웠음에도 불구하고 등산을 갔다.'),
    jsonb_build_object('number',7,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nWe can''t be together, but I will always love you.\n= __________ we can''t be together, I will always love you.',
      'options',jsonb_build_array(E'Even',E'Since',E'Although',E'With',E'Because'),
      'answer',E'3',
      'explanation',E'Although — 양보: but(하지만)을 사용한 대조 문장을 Although(~에도 불구하고)로 바꿔 쓸 수 있다.'),
    jsonb_build_object('number',8,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nWe had a lot of snow last week, so the streets were still slippery.\n= __________ we had a lot of snow last week, the streets were still slippery.',
      'options',jsonb_build_array(E'If',E'When',E'Although',E'Since',E'While'),
      'answer',E'4',
      'explanation',E'Since — 이유: so(그래서)를 사용한 원인-결과 문장을 Since(~때문에)로 바꿔 쓸 수 있다.'),

    -- ============================================================
    -- Part 2: (A)와 (B) 빈칸 + 모두고르기 (Q9–Q24)
    -- ============================================================
    jsonb_build_object('number',9,
      'question',E'[Part 2] (A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A)__________ the weather is so bad, I''m not going out today.\n(B)__________ it was raining, we continued playing soccer.',
      'options',jsonb_build_array(E'(A) Since — (B) While',E'(A) Although — (B) Because',E'(A) Though — (B) Though',E'(A) Since — (B) Even though',E'(A) Because — (B) Although'),
      'answer',E'4',
      'explanation',E'(A) Since — 이유: 날씨가 나쁘기 때문에 나가지 않겠다.\n(B) Even though — 양보: 비가 왔음에도 축구를 계속했다.'),
    jsonb_build_object('number',10,
      'question',E'__________ he had a terrible car accident, he wasn''t hurt at all.\n\n※ 적절하지 않은 것을 모두 고르시오. (정답 2개)',
      'options',jsonb_build_array(E'Since',E'Though',E'Although',E'Even though',E'Until'),
      'answer',E'1,5',
      'explanation',E'Since(이유: ~때문에)와 Until(~까지)은 양보 문맥에 부적절하다. 끔찍한 교통사고를 당했지만 전혀 다치지 않았다는 양보의 의미이므로 Though, Although, Even though가 적절하다.'),
    jsonb_build_object('number',11,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nThough he got up late, __________.',
      'options',jsonb_build_array(E'he couldn''t have breakfast',E'he didn''t do his homework',E'he wasn''t late for class',E'he missed the bus',E'he couldn''t take his lunch box'),
      'answer',E'3',
      'explanation',E'Though(양보) — 늦게 일어났지만 수업에 늦지 않았다. 양보절의 내용과 반대되는 결과가 와야 한다.'),
    jsonb_build_object('number',12,
      'question',E'빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nAlthough the traffic was heavy, __________.',
      'options',jsonb_build_array(E'we arrived on time',E'we were very late',E'we missed the class',E'we were late for school',E'I was too late to be on time'),
      'answer',E'1',
      'explanation',E'Although(양보) — 교통이 막혔지만 제시간에 도착했다. 양보절의 내용과 반대되는 결과가 와야 한다.'),
    jsonb_build_object('number',13,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) Her voice was shaking (A)__________ all her efforts to control it.\n(B) (B)__________ Betty left me 20 years ago, I still miss her.',
      'options',jsonb_build_array(E'(A) despite — (B) Since',E'(A) although — (B) But',E'(A) since — (B) Though',E'(A) although — (B) In spite of',E'(A) despite — (B) Though'),
      'answer',E'5',
      'explanation',E'(A) despite + 명사구: 목소리를 조절하려는 모든 노력에도 불구하고 떨리고 있었다.\n(B) Though + 절: Betty가 20년 전에 떠났지만 여전히 그리워한다.'),
    jsonb_build_object('number',14,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) __________ the wind blew hard, the old man went out to the sea to fish.\n(B) She ran the race (B)__________ an injury.',
      'options',jsonb_build_array(E'(A) Although — (B) despite',E'(A) Since — (B) because of',E'(A) Although — (B) because of',E'(A) Since — (B) despite',E'(A) Though — (B) in spite'),
      'answer',E'1',
      'explanation',E'(A) Although + 절: 바람이 세게 불었지만 낚시하러 바다로 나갔다 (양보).\n(B) despite + 명사: 부상에도 불구하고 경주에 참가했다 (양보). in spite는 단독으로 쓸 수 없고 in spite of가 되어야 한다.'),
    jsonb_build_object('number',15,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) Sarah''s been sick (A)__________ Friday.\n(B) He never gave up his dream (B)__________ his illness.',
      'options',jsonb_build_array(E'(A) since — (B) though',E'(A) since — (B) despite',E'(A) because of — (B) despite',E'(A) because of — (B) though',E'(A) since — (B) because of'),
      'answer',E'2',
      'explanation',E'(A) since + 시점: 금요일부터 아팠다 (시간의 since).\n(B) despite + 명사: 병에도 불구하고 꿈을 포기하지 않았다 (양보).'),
    jsonb_build_object('number',16,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) I''m tired (A)__________ I went to bed late at night.\n(B) (B)__________ his wealth, he is not happy.',
      'options',jsonb_build_array(E'(A) although — (B) Despite',E'(A) since — (B) Although',E'(A) since — (B) In spite of',E'(A) although — (B) In spite of',E'(A) because of — (B) Despite'),
      'answer',E'3',
      'explanation',E'(A) since + 절: 밤에 늦게 잤기 때문에 피곤하다 (이유).\n(B) In spite of + 명사: 그의 부에도 불구하고 행복하지 않다 (양보).'),
    jsonb_build_object('number',17,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) __________ it is small, the apartment is very expensive.\n(B) (B)__________ all our efforts, the event was a failure.',
      'options',jsonb_build_array(E'(A) Since — (B) Although',E'(A) Although — (B) Despite',E'(A) Despite — (B) Even though',E'(A) Because — (B) Despite',E'(A) Although — (B) Since'),
      'answer',E'2',
      'explanation',E'(A) Although + 절: 작지만 아파트가 매우 비싸다 (양보).\n(B) Despite + 명사구: 모든 노력에도 불구하고 행사는 실패였다 (양보).'),
    jsonb_build_object('number',18,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) The situation has changed (A)__________ I left.\n(B) Cathy hasn''t phoned (B)__________ she went to Berlin.',
      'options',jsonb_build_array(E'(A) because — (B) although',E'(A) since — (B) although',E'(A) although — (B) since',E'(A) since — (B) since',E'(A) because — (B) since'),
      'answer',E'4',
      'explanation',E'(A) since + 과거 시점: 내가 떠난 이후로 상황이 변했다 (시간).\n(B) since + 과거 시점: Cathy는 베를린에 간 이후로 전화하지 않았다 (시간).'),
    jsonb_build_object('number',19,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) The baseball match was cancelled (A)__________ the heavy rain.\n(B) (B)__________ her careful spending, Carrie has saved 3,000 dollars.',
      'options',jsonb_build_array(E'(A) since — (B) Despite',E'(A) although — (B) Because of',E'(A) because of — (B) Because of',E'(A) because of — (B) Despite',E'(A) despite — (B) Because of'),
      'answer',E'3',
      'explanation',E'(A) because of + 명사: 폭우 때문에 야구 경기가 취소되었다 (이유).\n(B) Because of + 명사: 신중한 지출 덕분에 Carrie는 3,000달러를 모았다 (이유).'),
    jsonb_build_object('number',20,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) We''re still very good friends (A)__________ we rarely see each other.\n(B) It has been raining (B)__________ last night.',
      'options',jsonb_build_array(E'(A) since — (B) since',E'(A) although — (B) because of',E'(A) although — (B) since',E'(A) since — (B) because of',E'(A) because — (B) since'),
      'answer',E'3',
      'explanation',E'(A) although + 절: 서로 거의 만나지 못하지만 여전히 좋은 친구이다 (양보).\n(B) since + 시점: 어젯밤부터 비가 내리고 있다 (시간).'),
    jsonb_build_object('number',21,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) __________ she had no qualifications, she got the job.\n(B) Everybody likes her (B)__________ the kindness she showed us.',
      'options',jsonb_build_array(E'(A) Since — (B) because of',E'(A) Despite — (B) since',E'(A) Even though — (B) because of',E'(A) Because of — (B) although',E'(A) Although — (B) despite'),
      'answer',E'3',
      'explanation',E'(A) Even though + 절: 자격이 없었음에도 취직했다 (양보).\n(B) because of + 명사구: 그녀가 보여준 친절 때문에 모두 좋아한다 (이유).'),
    jsonb_build_object('number',22,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) __________ he was good at painting, he could easily learn how to draw cartoons.\n(B) (B)__________ the bad weather caused by a terrible storm, the plane changed its course.',
      'options',jsonb_build_array(E'(A) Although — (B) Despite',E'(A) Since — (B) Although',E'(A) Though — (B) Since',E'(A) Since — (B) Because of',E'(A) Although — (B) Because of'),
      'answer',E'4',
      'explanation',E'(A) Since + 절: 그림을 잘 그렸기 때문에 만화 그리기를 쉽게 배울 수 있었다 (이유).\n(B) Because of + 명사구: 폭풍으로 인한 나쁜 날씨 때문에 비행기가 항로를 변경했다 (이유).'),
    jsonb_build_object('number',23,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) He refused to attend the seminar (A)__________ they asked him many times.\n(B) (B)__________ being late for school, she could still take the exam.',
      'options',jsonb_build_array(E'(A) while — (B) For',E'(A) while — (B) Although',E'(A) although — (B) To',E'(A) although — (B) In spite of',E'(A) since — (B) For'),
      'answer',E'4',
      'explanation',E'(A) although + 절: 여러 번 요청했음에도 세미나 참석을 거부했다 (양보).\n(B) In spite of + 동명사: 학교에 늦었음에도 불구하고 시험을 볼 수 있었다 (양보).'),
    jsonb_build_object('number',24,
      'question',E'(A)와 (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A) At first you thought it would be warm because the sun was shining, but when you went outside, it wasn''t warm at all.\n→ (A)__________ the sun was shining, it wasn''t very warm.\n(B) He was in love with her (B)__________ he did not put that name to his feeling.',
      'options',jsonb_build_array(E'(A) Although — (B) although',E'(A) As long as — (B) although',E'(A) Because — (B) as long as',E'(A) Although — (B) because',E'(A) So — (B) as long as'),
      'answer',E'1',
      'explanation',E'(A) Although + 절: 해가 비추었지만 따뜻하지 않았다 (양보).\n(B) although + 절: 그 감정에 이름을 붙이지 않았지만 사랑에 빠져 있었다 (양보).'),

    -- ============================================================
    -- Part 3: since 의미 구별 (Q25–Q34)
    -- ============================================================
    jsonb_build_object('number',25,
      'question',E'[Part 3] 밑줄 친 since의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① <u>Since</u> it was Friday, I stayed up late.\n② I haven''t heard from him <u>since</u> last year.\n③ <u>Since</u> I had a bad cold, I stayed at home all day.\n④ <u>Since</u> I''m very tired, I''m going to go to bed right away.\n⑤ We don''t have to go to school <u>since</u> tomorrow is a holiday.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②의 since는 시간(~이후로): 작년 이후로 연락이 없다. 나머지 ①③④⑤는 모두 이유(~때문에)의 since이다.'),
    jsonb_build_object('number',26,
      'question',E'밑줄 친 since의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① Take your umbrella <u>since</u> it''s raining outside.\n② Mike didn''t come to school <u>since</u> he had a cold.\n③ You should cook dinner <u>since</u> you''re a good cook.\n④ He has been sick <u>since</u> he graduated from university.\n⑤ I couldn''t buy the book <u>since</u> I used up my allowance.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'④의 since는 시간(~이후로): 대학을 졸업한 이후로 아프다. 나머지 ①②③⑤는 모두 이유(~때문에)의 since이다.'),
    jsonb_build_object('number',27,
      'question',E'밑줄 친 since의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① <u>Since</u> Jane came home late, her dad was worried about her.\n② I was waiting inside the café <u>since</u> it was very cold outside.\n③ <u>Since</u> Judy is kind, everyone likes her.\n④ It has been a couple of years <u>since</u> she left me.\n⑤ He couldn''t buy a car <u>since</u> he didn''t have enough money.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'④의 since는 시간(~이후로): 그녀가 떠난 지 몇 년이 되었다. 나머지 ①②③⑤는 모두 이유(~때문에)의 since이다.'),
    jsonb_build_object('number',28,
      'question',E'밑줄 친 since의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① I have known her <u>since</u> I was young.\n② Lisa wants to be a scientist <u>since</u> she''s good at science.\n③ <u>Since</u> he bought her a gift, she was happy.\n④ We have lived in Seoul <u>since</u> we left our hometown.\n⑤ <u>Since</u> I''ve just started learning Chinese, I can''t speak it well.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'1',
      'explanation',E'①의 since는 시간(~이후로): 어렸을 때부터 그녀를 알고 있다 (have known + since). 나머지 ②③⑤는 이유(~때문에)의 since이다.'),
    jsonb_build_object('number',29,
      'question',E'다음 중 밑줄 친 since의 의미가 같은 것끼리 묶인 것은?\n\nⓐ Minho was absent today <u>since</u> he was sick.\nⓑ Sujin will help me <u>since</u> she is my best friend.\nⓒ I have studied English <u>since</u> I was ten years old.\nⓓ He likes this town <u>since</u> people are very polite and kind.\nⓔ She has lived in Seoul <u>since</u> she was nineteen.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓐ, ⓒ',E'ⓑ, ⓓ',E'ⓐ, ⓑ, ⓓ',E'ⓒ, ⓓ, ⓔ'),
      'answer',E'4',
      'explanation',E'ⓐⓑⓓ는 모두 이유(~때문에)의 since이다. ⓒⓔ는 시간(~이후로)의 since이다.'),
    jsonb_build_object('number',30,
      'question',E'<보기> He is excited <u>since</u> his soccer team won the championship.\n\n밑줄 친 since의 의미가 <보기>와 같은 것을 모두 고르시오. (정답 2개)\n\n① <u>Since</u> it was very cold, we wore warm clothes.\n② She has been worried ever <u>since</u> the letter arrived.\n③ It''s been 10 years <u>since</u> we graduated from high school.\n④ The two people have hated each other <u>since</u> they first met.\n⑤ We thought that <u>since</u> we were in the area, we''d stop by.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'1,5',
      'explanation',E'<보기>의 since는 이유(~때문에)이다. ①(추웠기 때문에)과 ⑤(근처에 있었기 때문에)가 이유의 since이다. ②③④는 시간(~이후로)의 since이다.'),
    jsonb_build_object('number',31,
      'question',E'밑줄 친 since의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① <u>Since</u> we have no money, we can''t buy it.\n② I''ll do the dishes tonight <u>since</u> you cooked.\n③ <u>Since</u> then, it has become more and more popular.\n④ I wanted to sleep some more <u>since</u> I was not well.\n⑤ He didn''t attend the meeting <u>since</u> he was sick.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'3',
      'explanation',E'③의 since는 시간(~이후로): 그 이후로 점점 더 인기를 얻었다. 나머지 ①②④⑤는 모두 이유(~때문에)의 since이다.'),
    jsonb_build_object('number',32,
      'question',E'<보기> I enjoy reading books <u>since</u> it helps me to be creative.\n\n밑줄 친 since의 의미가 <보기>와 다른 것을 고르시오.\n\n① He did not go <u>since</u> he was ill.\n② I must stop now <u>since</u> I have to go out.\n③ I''ll buy you popcorn <u>since</u> you paid for the coke.\n④ We have been friends <u>since</u> we were 13 years old.\n⑤ <u>Since</u> I''ve just started learning Chinese, I can''t speak it well.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'<보기>의 since는 이유(~때문에)이다. ④의 since는 시간(~이후로): 13살 때부터 친구였다. 나머지 ①②③⑤는 모두 이유의 since이다.'),
    jsonb_build_object('number',33,
      'question',E'다음 중 밑줄 친 부분의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① The ice cream is melting <u>as</u> the weather is hot.\n② The baby is crying <u>because</u> she is hungry.\n③ <u>As</u> she got up too early, she is sleepy now.\n④ He wears glasses every day <u>since</u> he has bad sight.\n⑤ <u>Since</u> he was at age 6, he has been in Seoul.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'5',
      'explanation',E'⑤의 Since는 시간(~이후로): 6살 때부터 서울에 살고 있다. 나머지 ①②③④는 모두 이유(~때문에)의 접속사이다.'),
    jsonb_build_object('number',34,
      'question',E'다음 중 밑줄 친 부분의 의미가 같은 것끼리 짝지어진 것은?\n\nⓐ The ice cream is melting <u>as</u> the weather is hot.\nⓑ She has been worried ever <u>since</u> the letter arrived.\nⓒ <u>Since</u> I''m good at cooking, I made dinner for everyone.\nⓓ It has been two years <u>since</u> she moved to London.\nⓔ <u>As</u> I had nothing to do, I went for a walk.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓒ, ⓔ'),
      'answer',E'3',
      'explanation',E'ⓐⓒⓔ는 모두 이유(~때문에)의 접속사이다. ⓑⓓ는 시간(~이후로)의 since이다.'),

    -- ============================================================
    -- Part 4: 빈칸에 들어갈 말이 다른 것 (Q35–Q46)
    -- ============================================================
    jsonb_build_object('number',35,
      'question',E'[Part 4] 빈칸에 들어갈 말이 나머지 넷과 다른 것을 고르시오.\n\n① __________ they are poor, they''re happy.\n② I will do my best __________ the problem is very difficult.\n③ __________ it was cold, they played outside.\n④ __________ she is young, she is very brave.\n⑤ __________ I got up late, I was late for school.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'5',
      'explanation',E'⑤는 이유(~때문에)의 접속사(since/because)가 필요하다: 늦게 일어났기 때문에 학교에 늦었다. 나머지 ①②③④는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',36,
      'question',E'빈칸에 들어갈 말이 나머지 넷과 다른 것을 고르시오.\n\n① __________ it rained, they went jogging.\n② I couldn''t sleep __________ I was tired.\n③ __________ the traffic was heavy, I arrived late.\n④ __________ he didn''t study much, he passed the test.\n⑤ It is pretty warm __________ it is a little windy.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 이유(~때문에)의 접속사(since/because)가 필요하다: 피곤했기 때문에 잠을 잘 수 없었다. 나머지 ①③④⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',37,
      'question',E'빈칸에 들어갈 말이 나머지 넷과 다른 것을 고르시오.\n\n① I''m hungry __________ I didn''t eat lunch.\n② I didn''t go out __________ the bad weather.\n③ We like her __________ she is very kind to us.\n④ Jenny couldn''t walk __________ she broke her leg.\n⑤ Hajun got up late __________ he stayed up late last night.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 전치사 because of + 명사(the bad weather)가 필요하다. 나머지 ①③④⑤는 접속사 because/since + 절이 필요하다.'),
    jsonb_build_object('number',38,
      'question',E'빈칸에 들어갈 말이 나머지 넷과 다른 것을 고르시오.\n\n① I can sleep __________ it''s very noisy.\n② I don''t like him __________ he isn''t honest.\n③ __________ it was raining, I didn''t get wet.\n④ __________ she is pretty, she isn''t content with her face.\n⑤ I was late for school __________ I got up early in the morning.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 이유(~때문에)의 접속사(since/because)가 필요하다: 정직하지 않기 때문에 좋아하지 않는다. 나머지 ①③④⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',39,
      'question',E'빈칸에 들어갈 말이 나머지 넷과 다른 것을 고르시오.\n\n① He wore a short T-shirt __________ it was freezing.\n② I had a headache __________ I stayed up all night.\n③ They put on sunglasses __________ it was really dark.\n④ I''ll buy a brand new car __________ it''s so expensive.\n⑤ She always passes her exams __________ she does not study at all.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 이유(~때문에)의 접속사(since/because)가 필요하다: 밤새 깨어 있었기 때문에 두통이 있었다. 나머지 ①③④⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',40,
      'question',E'다음 중 빈칸에 들어갈 말이 나머지 넷과 다른 것은?\n\n① __________ summer is a fun season, I can''t stand the heat!\n② __________ tomatoes are low in calories, they make you feel full.\n③ __________ it explains everything very clearly, it is a useful book.\n④ __________ he was in poor health, he continued to carry out his duties.\n⑤ __________ the house was destroyed, no one was hurt.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'3',
      'explanation',E'③은 이유(~때문에)의 접속사(since)가 필요하다: 모든 것을 명확히 설명하기 때문에 유용한 책이다. 나머지 ①②④⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',41,
      'question',E'다음 중 빈칸에 들어갈 말이 나머지 넷과 다른 것은?\n\n① __________ the field trip was short, I really enjoyed it.\n② I practiced the piano __________ I felt tired.\n③ She could see with her heart __________ she was blind.\n④ I couldn''t phone you __________ I hadn''t got your number.\n⑤ There''s a chance she''ll recover __________ the doctors can''t say for certain.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'④는 이유(~때문에)의 접속사(since/because)가 필요하다: 전화번호가 없었기 때문에 전화할 수 없었다. 나머지 ①②③⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',42,
      'question',E'다음 중 빈칸에 들어갈 말이 나머지 넷과 다른 것은?\n\n① __________ he studied a lot, he didn''t pass the exam.\n② __________ it is hot today, ice cream is melting very fast.\n③ I don''t want your help __________ I''m in need.\n④ __________ he didn''t learn advanced math, he could solve complex problems.\n⑤ We went on a picnic __________ it rained.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 이유(~때문에)의 접속사(since)가 필요하다: 오늘 더우니까 아이스크림이 빨리 녹고 있다. 나머지 ①③④⑤는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다.'),
    jsonb_build_object('number',43,
      'question',E'다음 중 빈칸에 Since가 들어가기에 적절하지 않은 문장은?\n\n① __________ you''re late, you can''t watch the musical.\n② __________ the food is not tasty, you''d better say nice things to the cook.\n③ __________ it is very cold, you''d better not go outside.\n④ __________ you don''t feel well, we''ll take care of your part.\n⑤ __________ I am not good at speech, why don''t you make the presentation?',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 양보(~에도 불구하고)의 접속사(although/though)가 필요하다: 음식이 맛없지만 요리사에게 좋은 말을 해주는 것이 낫다. Since(이유)를 쓰면 "맛없으니까 좋은 말을 해라"가 되어 논리적으로 어색하다.'),
    jsonb_build_object('number',44,
      'question',E'다음 중 빈칸에 though가 들어가기에 어색한 것은?\n\n① __________ he has a good job, he doesn''t complain.\n② __________ they have very little money, they are happy.\n③ __________ she was tired, she tried to study hard.\n④ __________ she caught a bad cold, she had to take the exam.\n⑤ __________ Jessica is rich, she spends little money.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'④는 이유(~때문에)의 접속사가 더 적절하다: 감기에 걸렸기 때문에 시험을 봐야 했다. though를 쓰면 양보의 의미가 되는데, 감기와 시험 응시 사이의 대조가 자연스럽지 않다.'),
    jsonb_build_object('number',45,
      'question',E'다음 중 빈칸에 although가 들어가기에 어색한 것은?\n\n① __________ the traffic was bad, we arrived on time.\n② I went home early __________ I wasn''t feeling well.\n③ __________ he is poor, he always helps other people.\n④ We hardly ever see each other __________ we live on the same street.\n⑤ Brian quickly did his homework __________ he couldn''t concentrate well.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 이유(~때문에)의 접속사(since/because)가 필요하다: 몸이 좋지 않았기 때문에 일찍 집에 갔다. although를 쓰면 "몸이 안 좋았지만 일찍 집에 갔다"가 되어 어색하다.'),
    jsonb_build_object('number',46,
      'question',E'다음 중 밑줄 친 부분의 의미가 나머지 넷과 다른 것을 고르시오.\n\n① We''ve played better <u>since</u> you joined our team.\n② <u>Since</u> the party, she hasn''t spoken to him at all.\n③ <u>Since</u> the Earth is rotating, two tides occur each day.\n④ I felt hungry, <u>so</u> I made myself a sandwich.\n⑤ I left school in 1995, and <u>since</u> then I''ve lived in London.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'4',
      'explanation',E'④의 so는 결과(그래서)의 접속사이다. ①②⑤는 시간(~이후로)의 since이고, ③은 이유(~때문에)의 since이지만, ④만 since가 아닌 so이므로 나머지와 다르다.'),

    -- ============================================================
    -- Part 5: 동의 문장 / 다른 의미 찾기 (Q47–Q56)
    -- ============================================================
    jsonb_build_object('number',47,
      'question',E'[Part 5] 주어진 문장과 의미가 같지 않은 것은?\n\nAlthough it was cold, he stood outside all day long.',
      'options',jsonb_build_array(E'If it was cold, he stood outside all day long.',E'Even though it was cold, he stood outside all day long.',E'In spite of the cold weather, he stood outside all day long.',E'Though it was cold, he stood outside all day long.',E'It was cold, but he stood outside all day long.'),
      'answer',E'1',
      'explanation',E'①의 If는 조건(만약 ~라면)의 접속사로, 양보(~에도 불구하고)의 의미인 원래 문장과 다르다. ②③④⑤는 모두 양보의 의미를 나타낸다.'),
    jsonb_build_object('number',48,
      'question',E'나머지 넷과 의미가 다른 것은?\n\n① We went on a picnic though it rained.\n② We went on a picnic although it rained.\n③ We went on a picnic in spite of the rain.\n④ We went on a picnic despite the rain.\n⑤ We went on a picnic during the rain.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'5',
      'explanation',E'⑤의 during은 시간(~동안)의 전치사로, 양보(~에도 불구하고)의 의미인 나머지와 다르다.'),
    jsonb_build_object('number',49,
      'question',E'나머지 넷과 의미가 다른 것은?\n\n① The baseball game was canceled since it rained.\n② Though it rained, the baseball game wasn''t canceled.\n③ The baseball game wasn''t canceled although it rained.\n④ In spite of the rain, the baseball game wasn''t canceled.\n⑤ The baseball game wasn''t canceled even though it rained.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'1',
      'explanation',E'①은 이유(~때문에): 비가 와서 경기가 취소되었다. 나머지 ②③④⑤는 양보(~에도 불구하고): 비가 왔지만 경기가 취소되지 않았다.'),
    jsonb_build_object('number',50,
      'question',E'나머지 넷과 의미가 다른 것은?\n\n① She tried on several shoes, but she couldn''t find what she liked.\n② She tried on several shoes even though she couldn''t find what she liked.\n③ She couldn''t find what she liked although she tried on several shoes.\n④ She tried on several shoes. Still, she couldn''t find what she liked.\n⑤ Although she tried on several shoes, she couldn''t find what she liked.',
      'options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),
      'answer',E'2',
      'explanation',E'②는 "마음에 드는 것을 찾지 못했음에도 여러 신발을 신어보았다"로, 양보절과 주절의 관계가 나머지와 반대이다. 나머지 ①③④⑤는 모두 "여러 신발을 신어보았지만 마음에 드는 것을 찾지 못했다"의 의미이다.'),
    jsonb_build_object('number',51,
      'question',E'주어진 문장과 의미가 같은 것은?\n\nThe jewel looks real, but it is fake.',
      'options',jsonb_build_array(E'Since the jewel looks real, it is fake.',E'Although the jewel looks real, it is fake.',E'As though the jewel looks real, it is fake.',E'If the jewel looks real, it is fake.',E'When the jewel looks real, it is fake.'),
      'answer',E'2',
      'explanation',E'but(역접)은 although/though(양보)와 같은 의미입니다. "그 보석은 진짜처럼 보이지만 가짜이다."'),
    jsonb_build_object('number',52,
      'question',E'날씨는 나빴지만, 많은 사람들이 콘서트를 보기 위해 왔다.\n다음 중 바르게 영작한 것은?',
      'options',jsonb_build_array(E'Since the weather was bad, many people came to see the concert.',E'Though the weather was bad, many people came to see the concert.',E'While the weather was bad, many people came to see the concert.',E'Thanks to the bad weather, many people came to see the concert.',E'Due to the bad weather, many people came to see the concert.'),
      'answer',E'2',
      'explanation',E'"나빴지만"은 양보의 의미이므로 though가 적절합니다. since/thanks to/due to는 이유를 나타내어 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',53,
      'question',E'비록 대회에서 이기진 못했지만, 난 내가 자랑스러웠다.\n다음 중 바르게 영작한 것은?',
      'options',jsonb_build_array(E'Since I didn''t win the contest, I was proud of myself.',E'I didn''t win the contest since I was proud of myself.',E'Though I didn''t win the contest, I was proud of myself.',E'I didn''t win the contest although I was proud of myself.',E'Until I didn''t win the contest, I was proud of myself.'),
      'answer',E'3',
      'explanation',E'"비록 ~했지만"은 양보를 나타내므로 though가 적절합니다. since는 이유, until은 시간을 나타냅니다.'),
    jsonb_build_object('number',54,
      'question',E'울고 싶었지만, 그녀는 미소를 짓고 있었다.\n다음 중 바르게 영작한 것은? (정답 2개)',
      'options',jsonb_build_array(E'As she felt like crying, she was smiling.',E'She felt like crying, but she was smiling.',E'Even though she felt like crying, she was smiling.',E'Since she felt like crying, she was smiling.',E'She felt like crying although she was smiling.'),
      'answer',E'2,3',
      'explanation',E'"울고 싶었지만"은 역접/양보의 의미입니다. ② but(역접 접속사)과 ③ even though(양보 접속사)가 적절합니다. ⑤는 양보절의 내용이 뒤바뀌어 의미가 어색합니다.'),
    jsonb_build_object('number',55,
      'question',E'Mary는 높은 열 때문에 병원에 입원했다.\n다음 중 알맞게 영작한 것을 모두 고르면?',
      'options',jsonb_build_array(E'Since Mary had a high fever, she went into the hospital.',E'Because a high fever, Mary went into the hospital.',E'Though Mary had a high fever, she went into the hospital.',E'Because of a high fever, Mary went into the hospital.',E'Mary had a high fever because she went into the hospital.'),
      'answer',E'1,4',
      'explanation',E'"~때문에"는 이유를 나타냅니다. ① Since + 주어 + 동사(접속사), ④ Because of + 명사(전치사구) 모두 이유를 올바르게 표현합니다. ② Because 뒤에는 절이 와야 합니다. ③ Though는 양보입니다. ⑤는 인과관계가 뒤바뀌었습니다.'),
    jsonb_build_object('number',56,
      'question',E'다음 글의 밑줄 친 부분과 의미가 가장 가까운 것은?\n\nAlthough Jiwon couldn''t concentrate well, she quickly did her homework.\n<u>Although it rained a lot, Jiwon still went to the music concert</u> after doing her homework.\nAlthough there were too many people in the concert hall, the concert was wonderful.',
      'options',jsonb_build_array(E'It rained too much to go to the music concert.',E'It rained a lot, but Jiwon went to the music concert.',E'After it rained a lot, Jiwon went to the music concert.',E'Jiwon was going to go to the concert when it rained a lot.',E'Jiwon didn''t go to the music concert because it rained a lot.'),
      'answer',E'2',
      'explanation',E'Although(비록 ~이지만)는 양보 접속사로 but(그러나)과 같은 역접 의미를 나타냅니다. "비가 많이 왔지만 콘서트에 갔다" = "비가 많이 왔다, 그러나 콘서트에 갔다"'),

    -- ============================================================
    -- Part 6: 자연스러운/어색한 문장 고르기 (Q57–Q66)
    -- ============================================================
    jsonb_build_object('number',57,
      'question',E'[Part 6] 다음 중 흐름상 가장 자연스러운 문장은?',
      'options',jsonb_build_array(E'Though he is two years old, he can''t read books.',E'Though I was only out for five minutes, I got very wet in the rain.',E'Though I wasn''t feeling well, I went home early.',E'Though we were climbing up the mountain, it started to rain.',E'Though you agree or disagree isn''t important.'),
      'answer',E'2',
      'explanation',E'② "5분밖에 안 나갔는데도 비에 많이 젖었다"는 양보 관계가 자연스럽습니다. ① 2살이면 못 읽는 게 당연(양보 불필요), ③ 아프면 일찍 귀가하는 게 당연, ④ though가 아닌 while이 적절, ⑤ though가 명사절을 이끌 수 없습니다.'),
    jsonb_build_object('number',58,
      'question',E'다음 중 흐름상 어색한 문장은?',
      'options',jsonb_build_array(E'She couldn''t get good grades although she studied very hard.',E'Although he studied hard, he got a good grade on the test.',E'She could see with her heart although she was blind.',E'Although Kevin''s aunt lives in China, she doesn''t speak Chinese.',E'Although coke is not good for our health, the doctor advised me to drink it every day.'),
      'answer',E'2',
      'explanation',E'② "열심히 공부했지만 좋은 점수를 받았다"는 양보 관계가 성립하지 않습니다. 열심히 공부하면 좋은 점수를 받는 것이 자연스럽습니다. although는 예상과 반대되는 결과가 와야 합니다.'),
    jsonb_build_object('number',59,
      'question',E'다음 중 흐름상 어색한 문장은?',
      'options',jsonb_build_array(E'We went on a picnic though it was rainy.',E'She failed the test even though she had studied hard.',E'He is strong and healthy though he is seventy years old.',E'She couldn''t eat the meal though she was very hungry.',E'He didn''t go to school even though he was sick.'),
      'answer',E'5',
      'explanation',E'⑤ "아팠는데도 학교에 가지 않았다"는 양보 관계가 어색합니다. 아프면 학교에 안 가는 것이 자연스럽습니다. "아팠는데도 학교에 갔다"가 올바른 양보 표현입니다.'),
    jsonb_build_object('number',60,
      'question',E'다음 중 흐름상 어색한 문장은? (정답 2개)',
      'options',jsonb_build_array(E'Although Sarah was sick, she wasn''t absent from school.',E'Though Tom studied hard, he got poor grades.',E'Cathy was very hungry although she didn''t have breakfast.',E'Even though I caught a cold, I couldn''t go to school.',E'Though it was cold, we took a walk in the park.'),
      'answer',E'3,4',
      'explanation',E'③ "아침을 안 먹었지만 배가 고팠다"는 양보가 아닙니다(안 먹으면 배고픈 게 당연). ④ "감기에 걸렸는데도 학교에 갈 수 없었다"는 양보가 어색합니다(감기면 못 가는 게 당연). ①②⑤는 예상과 반대되는 결과로 자연스럽습니다.'),
    jsonb_build_object('number',61,
      'question',E'다음 중 밑줄 친 부분의 쓰임이 자연스러운 것은?',
      'options',jsonb_build_array(E'Since I studied hard, I passed the exam.',E'Everybody likes James since he is generous.',E'Although it was cold outside, they wore shorts.',E'Although he is very young, he acts like an old man.',E'They didn''t believe him since he was telling the truth.'),
      'answer',E'5',
      'explanation',E'⑤ "그가 진실을 말하고 있었기 때문에 그를 믿지 않았다"는 역설적이지만 특정 상황(진실이 너무 충격적이어서)에서 자연스러울 수 있습니다.'),
    jsonb_build_object('number',62,
      'question',E'다음 중 밑줄 친 단어가 문맥상 올바른 것은?',
      'options',jsonb_build_array(E'Since I have no money, I cannot buy the snack.',E'My mom cooked dinner although we were hungry.',E'She couldn''t get good grades since she studied very hard.',E'Although I wear glasses, I can read all the letters with them.',E'Since coke is not good for health, the doctor advised me to drink it every day.'),
      'answer',E'1',
      'explanation',E'① "돈이 없으므로 간식을 살 수 없다"는 since(이유)의 올바른 사용입니다. ② 배고프면 요리하는 게 당연(양보 부적절), ③ 열심히 공부했는데 못 받음(이유 부적절), ④ 안경을 쓰면 읽을 수 있는 게 당연(양보 부적절), ⑤ 건강에 안 좋은데 마시라고 권유(이유 부적절).'),
    jsonb_build_object('number',63,
      'question',E'다음 중 흐름상 어색한 문장은?',
      'options',jsonb_build_array(E'Although I caught a cold, I went to school.',E'They didn''t believe him although he was telling the truth.',E'Although it was cold outside, they wore shorts.',E'Although he is very young, he acts like an old man.',E'He was tired although he played soccer the day before.'),
      'answer',E'5',
      'explanation',E'⑤ "전날 축구를 했지만 피곤했다"는 양보 관계가 어색합니다. 축구를 하면 피곤한 것이 자연스럽습니다. "전날 축구를 했지만 피곤하지 않았다"가 올바른 양보 표현입니다.'),
    jsonb_build_object('number',64,
      'question',E'다음 중 흐름상 가장 자연스러운 문장은?',
      'options',jsonb_build_array(E'He is not very active although he''s nearly 80.',E'Though I took a wrong bus, I was late for the meeting.',E'Even though the sun was shining, it was very warm.',E'Despite my illness, I was absent from school.',E'I like my brother though he sometimes makes me angry.'),
      'answer',E'5',
      'explanation',E'⑤ "그가 가끔 화나게 하지만 좋아한다"는 양보 관계가 자연스럽습니다. ① 80세면 활동적이지 않은 게 당연, ② 잘못된 버스를 타면 늦는 게 당연, ③ 해가 비치면 따뜻한 게 당연, ④ 아프면 결석하는 게 당연(양보 불필요).'),
    jsonb_build_object('number',65,
      'question',E'다음 중 빈칸에 접속사 although가 들어갈 수 있는 것은?',
      'options',jsonb_build_array(E'__________ I was tired, I went to bed.',E'__________ he is lazy, he gets up late.',E'__________ I exercised, I gained weight.',E'__________ she was hungry, she had dinner.',E'__________ he studied, he got good grades.'),
      'answer',E'3',
      'explanation',E'③ "운동했지만 살이 쪘다"는 예상과 반대되는 결과로 양보 관계가 성립합니다. ①②④⑤는 원인과 결과가 자연스러워 although(양보)가 아닌 since/because(이유)가 적절합니다.'),
    jsonb_build_object('number',66,
      'question',E'다음 중 밑줄 친 부분의 쓰임이 어색한 것은?',
      'options',jsonb_build_array(E'Because of his disease, he can''t come to school.',E'Despite her strengths, she got the first prize.',E'Since he was ill, he couldn''t come to the party.',E'Thanks to his help, we could finish it with success.',E'Even if he is sick, he does his best all the time.'),
      'answer',E'2',
      'explanation',E'② "그녀의 강점에도 불구하고 1등을 했다"는 양보 관계가 어색합니다. 강점이 있으면 1등하는 게 자연스럽습니다. "약점에도 불구하고" 또는 "강점 덕분에"가 적절합니다.'),

    -- ============================================================
    -- Part 7: 어법 판단 (Q67–Q78)
    -- ============================================================
    jsonb_build_object('number',67,
      'question',E'[Part 7] 다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Despite he was old, he still led an active life.',E'We didn''t stay outside long because of it was too cold.',E'Since my sister lied to me, I was angry at her.',E'He was absent today because his illness.',E'Although the danger signs, we swam there.'),
      'answer',E'3',
      'explanation',E'③ Since + 주어 + 동사(절) 구조가 올바릅니다. ① Despite 뒤에는 명사(구)가 와야 합니다(→ Despite his old age). ② because of 뒤에는 명사가 와야 합니다(→ because it was). ④ because 뒤에는 절이 와야 합니다(→ because of his illness). ⑤ Although 뒤에는 절이 와야 합니다.'),
    jsonb_build_object('number',68,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Since John is our friend, he''ll help us.',E'He went to bed early since he was sick.',E'Since it''s raining outside, I''ll stay at home.',E'She got up late since she missed the school bus.',E'Since tomorrow is Sunday, I don''t have to get up early.'),
      'answer',E'4',
      'explanation',E'④ "늦게 일어났기 때문에 스쿨버스를 놓쳤다"가 올바른 인과관계입니다. "스쿨버스를 놓쳤기 때문에 늦게 일어났다"는 인과관계가 뒤바뀌어 어색합니다.'),
    jsonb_build_object('number',69,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'In spite of he has no money, he is still happy.',E'Although his diligence, he failed the test.',E'Although she studied hard, she gets straight Ds.',E'Even though worked hard, Tom couldn''t finish his report.',E'She couldn''t understand the instructions even though she read them twice.'),
      'answer',E'5',
      'explanation',E'⑤ Even though + 주어 + 동사 구조가 올바릅니다. ① In spite of 뒤에는 명사(구)가 와야 합니다. ② Although 뒤에는 절이 와야 합니다. ③ 시제 불일치(studied → gets). ④ Even though 뒤에 주어가 빠졌습니다.'),
    jsonb_build_object('number',70,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Despite of the storm, the airplane landed safely.',E'I felt sick in spite of the fact that I took medicine.',E'I couldn''t get up despite the alarm rang many times.',E'My dad didn''t eat anything even though the hunger.',E'Even if the fact that I woke up early, I was late for work.'),
      'answer',E'2',
      'explanation',E'② in spite of the fact that + 절 구조가 올바릅니다. ① despite of는 틀린 표현(despite 또는 in spite of). ③ despite 뒤에는 명사(구)가 와야 합니다. ④ even though 뒤에는 절이 와야 합니다. ⑤ even if the fact that는 틀린 표현입니다.'),
    jsonb_build_object('number',71,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Despite it rained heavily, we played soccer.',E'Though it rained heavily, we played soccer.',E'In spite of the heavy rain, we played soccer.',E'Although it rained heavily, we played soccer.',E'Even though it rained heavily, we played soccer.'),
      'answer',E'1',
      'explanation',E'① Despite 뒤에는 명사(구)가 와야 합니다. 절(it rained heavily)이 올 수 없습니다. → Despite the heavy rain 또는 Although it rained heavily가 올바릅니다.'),
    jsonb_build_object('number',72,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'I feel sick in spite of I took some medicine.',E'Although she studied hard, she gets straight Ds.',E'Despite of the storm, the ship arrived safely.',E'Though began last, he finished first.',E'She couldn''t understand the map even though she tried twice.'),
      'answer',E'5',
      'explanation',E'⑤ even though + 주어 + 동사 구조가 올바릅니다. ① in spite of 뒤에는 명사(구)가 와야 합니다. ② 시제 불일치(studied → gets). ③ despite of는 틀린 표현. ④ though 뒤에 주어가 빠졌습니다.'),
    jsonb_build_object('number',73,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'We enjoyed the day at the park though the bad weather.',E'Despite the playground being small, it looked large to the boy.',E'Although the injuries were serious, they did their best to the end.',E'Though he began last, he finished first.',E'Despite our efforts, we failed to win the prize.'),
      'answer',E'1',
      'explanation',E'① though는 접속사이므로 뒤에 절(주어+동사)이 와야 합니다. "though the bad weather"는 동사가 없어 어법상 틀립니다. → though the weather was bad 또는 despite the bad weather가 올바릅니다.'),
    jsonb_build_object('number',74,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Although the injuries, they did their best to the end.',E'Though began last, he finished first.',E'Although our efforts, we failed to win the prize.',E'I couldn''t sleep although I very tired.',E'Although our house is small, it''s big enough for our needs.'),
      'answer',E'5',
      'explanation',E'⑤ Although + 주어 + 동사(절) 구조가 올바릅니다. ① Although 뒤에는 절이 와야 합니다(→ Although the injuries were serious). ② though 뒤에 주어가 빠졌습니다. ③ Although 뒤에는 절이 와야 합니다. ④ be동사(was)가 빠졌습니다.'),
    jsonb_build_object('number',75,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'She bought a car even though she can''t drive.',E'Even though the traffic, I arrived on time.',E'Although he is poor, but he is very happy.',E'Despite I got up early in the morning, I was late for school.',E'Though it was cold, we went swimming.'),
      'answer',E'3',
      'explanation',E'③ although와 but을 함께 쓸 수 없습니다. although가 이미 양보의 의미를 포함하므로 but은 중복입니다. → Although he is poor, he is very happy. 또는 He is poor, but he is very happy.'),
    jsonb_build_object('number',76,
      'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Although the danger signs, we swam there.\n• Despite he was old, he still led an active life.\n• I drink coffee although it makes me nervous.\n• Although it was very muddy, the game went on.\n• We enjoyed the day at the park though the bad weather.\n• Despite she was a great writer, she wasn''t famous at that time.',
      'options',jsonb_build_array(E'0개',E'1개',E'2개',E'3개',E'4개'),
      'answer',E'3',
      'explanation',E'옳은 문장은 2개입니다: "I drink coffee although it makes me nervous."(although + 절 ✓), "Although it was very muddy, the game went on."(although + 절 ✓). 나머지는 although/despite 뒤에 명사(구)/절 구조가 맞지 않습니다.'),
    jsonb_build_object('number',77,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\na. The books ordered online arrived one week later.\nb. I drink coffee although it makes me nervous.\nc. Despite he was old, he still led an active life.\nd. Although it was very muddy, the game went on.\ne. We enjoyed the day at the park though the bad weather.',
      'options',jsonb_build_array(E'a, b',E'a, b, d',E'b, c, d',E'a, c, e',E'b, d, e'),
      'answer',E'2',
      'explanation',E'a. 과거분사의 후치수식 ✓, b. although + 절 ✓, d. although + 절 ✓. c. despite 뒤에 절이 올 수 없음 ✗. e. though 뒤에 명사구만 올 수 없음 ✗.'),
    jsonb_build_object('number',78,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I love the sound of falling rain.',E'When I received the invitation card, I felt very excited.',E'Watch out! There are pieces of broken glass on the floor.',E'New York is one of the biggest cities in America, called ''the Big Apple.''',E'There are various kinds of books included novels, magazines, biography, and so on.'),
      'answer',E'5',
      'explanation',E'⑤ included → including이 되어야 합니다. "소설, 잡지, 전기 등을 포함하는 다양한 종류의 책"에서 including은 현재분사로 능동의 의미를 나타냅니다.'),

    -- ============================================================
    -- Part 8: 어법 옳은 문장 개수/짝짓기 (Q79–Q88)
    -- ============================================================
    jsonb_build_object('number',79,
      'question',E'[Part 8] 다음 중 어법상 옳은 문장의 총 개수는?\n\n• Though Tom studied hard, he got poor grades.\n• Although he studied hard, but he failed the exam.\n• In spite of the rain, we played soccer outside.\n• Despite she was young, she ran the company well.\n• Even though it was snowing, we decided to drive.',
      'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
      'answer',E'3',
      'explanation',E'옳은 문장 3개: "Though Tom studied hard, he got poor grades."(though + 절 ✓), "In spite of the rain, we played soccer outside."(in spite of + 명사 ✓), "Even though it was snowing, we decided to drive."(even though + 절 ✓). although...but 중복 사용 ✗, despite + 절 ✗.'),
    jsonb_build_object('number',80,
      'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Since I have no money, I cannot buy the snack.\n• She got up late since she missed the school bus.\n• He went to bed early since he was sick.\n• Despite of the storm, the airplane landed safely.\n• I couldn''t sleep although I very tired.',
      'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
      'answer',E'2',
      'explanation',E'옳은 문장 2개: "Since I have no money, I cannot buy the snack."(since + 절 ✓), "He went to bed early since he was sick."(since + 절 ✓). "She got up late since she missed the school bus."는 인과관계가 뒤바뀜 ✗. "Despite of"는 틀린 표현 ✗. "although I very tired"는 be동사 누락 ✗.'),
    jsonb_build_object('number',81,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Since John is our friend, he''ll help us.\nⓑ He went to bed early since he was sick.\nⓒ She got up late since she missed the school bus.\nⓓ Since it''s raining outside, I''ll stay at home.\nⓔ Since tomorrow is Sunday, I don''t have to get up early.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓒ',E'ⓐ, ⓑ, ⓓ',E'ⓐ, ⓑ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓓ, ⓔ'),
      'answer',E'4',
      'explanation',E'ⓐⓑⓓⓔ 모두 since(이유) + 절 구조가 올바르고 인과관계가 자연스럽습니다. ⓒ "늦게 일어났기 때문에 스쿨버스를 놓쳤다"가 자연스러운 인과관계이므로, 원인과 결과가 뒤바뀌어 어색합니다.'),
    jsonb_build_object('number',82,
      'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Although the danger signs, we swam there.\n• Despite he was old, he still led an active life.\n• I drink coffee although it makes me nervous.\n• Although it was very muddy, the game went on.\n• We enjoyed the day at the park though the bad weather.\n• Despite she was a great writer, she wasn''t famous at that time.',
      'options',jsonb_build_array(E'0개',E'1개',E'2개',E'3개',E'4개'),
      'answer',E'3',
      'explanation',E'옳은 문장은 2개입니다: "I drink coffee although it makes me nervous."(although + 절 ✓), "Although it was very muddy, the game went on."(although + 절 ✓). although/though 뒤에는 절, despite 뒤에는 명사(구)가 와야 합니다.'),
    jsonb_build_object('number',83,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ In spite of he has no money, he is still happy.\nⓑ Although his diligence, he failed the test.\nⓒ Although she studied hard, she still failed.\nⓓ Even though worked hard, Tom couldn''t finish his report.\nⓔ She couldn''t understand even though she read it twice.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓒ, ⓔ',E'ⓑ, ⓒ',E'ⓐ, ⓓ, ⓔ',E'ⓒ, ⓓ, ⓔ'),
      'answer',E'2',
      'explanation',E'ⓒ Although + 주어 + 동사 ✓, ⓔ even though + 주어 + 동사 ✓. ⓐ In spite of 뒤에 절 ✗, ⓑ Although 뒤에 명사구 ✗, ⓓ Even though 뒤에 주어 누락 ✗.'),
    jsonb_build_object('number',84,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Despite of the storm, the airplane landed safely.\nⓑ I felt sick in spite of the fact that I took medicine.\nⓒ I couldn''t get up despite the alarm rang many times.\nⓓ My dad didn''t eat anything even though the hunger.\nⓔ Even though it is small, the apartment is very expensive.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓔ',E'ⓒ, ⓓ',E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓓ, ⓔ'),
      'answer',E'2',
      'explanation',E'ⓑ in spite of the fact that + 절 ✓, ⓔ even though + 주어 + 동사 ✓. ⓐ despite of 틀린 표현 ✗, ⓒ despite 뒤에 절 ✗, ⓓ even though 뒤에 명사 ✗.'),
    jsonb_build_object('number',85,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Though Tom studied hard, he got poor grades.\nⓑ Although he studied hard, but he failed the exam.\nⓒ In spite of the rain, we played soccer outside.\nⓓ Despite she was young, she ran the company well.\nⓔ Even though it was snowing, we decided to drive.',
      'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓓ',E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓔ'),
      'answer',E'3',
      'explanation',E'ⓐ though + 절 ✓, ⓒ in spite of + 명사 ✓, ⓔ even though + 절 ✓. ⓑ although...but 중복 ✗, ⓓ despite + 절 ✗.'),
    jsonb_build_object('number',86,
      'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• Since I have no money, I cannot buy the snack.\n• She got up late since she missed the school bus.\n• He went to bed early since he was sick.\n• Despite of the storm, the airplane landed safely.\n• I couldn''t sleep although I very tired.',
      'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
      'answer',E'2',
      'explanation',E'옳은 문장 2개: "Since I have no money, I cannot buy the snack."(since + 절 ✓), "He went to bed early since he was sick."(since + 절 ✓). 나머지는 인과관계 오류, despite of 오류, be동사 누락입니다.'),
    jsonb_build_object('number',87,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ I feel sick in spite of I took some medicine.\nⓑ Though it was cold, we went swimming in the river.\nⓒ Despite of the storm, the ship arrived on time.\nⓓ Although he is poor, but he is very happy.\nⓔ Since she had homework to do, she stayed up late.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓔ',E'ⓑ, ⓒ',E'ⓐ, ⓓ, ⓔ',E'ⓒ, ⓓ, ⓔ'),
      'answer',E'2',
      'explanation',E'ⓑ though + 절 ✓, ⓔ since + 절 ✓. ⓐ in spite of 뒤에 절 ✗, ⓒ despite of 틀린 표현 ✗, ⓓ although...but 중복 ✗.'),
    jsonb_build_object('number',88,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Although the bad weather, we went on a picnic.\nⓑ Despite the playground being small, it looked large to the boy.\nⓒ Although the injuries, they did their best to the end.\nⓓ Though he began last, he finished first.\nⓔ Although our efforts, we failed to win the prize.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓓ',E'ⓑ, ⓒ, ⓓ, ⓔ'),
      'answer',E'2',
      'explanation',E'ⓑ Despite + 동명사구 ✓, ⓓ Though + 주어 + 동사 ✓. ⓐⓒⓔ Although 뒤에 명사(구)만 올 수 없음(절이 와야 함) ✗.'),

    -- ============================================================
    -- Part 9: 한영 영작 선택 (Q89–Q100)
    -- ============================================================
    jsonb_build_object('number',89,
      'question',E'[Part 9] 날씨는 나빴지만, 많은 사람들이 콘서트를 보기 위해 왔다.',
      'options',jsonb_build_array(E'Since the weather was bad, many people came to see the concert.',E'Though the weather was bad, many people came to see the concert.',E'While the weather was bad, many people came to see the concert.',E'Thanks to the bad weather, many people came to see the concert.',E'Due to the bad weather, many people came to see the concert.'),
      'answer',E'2',
      'explanation',E'"나빴지만"은 양보의 의미이므로 though(비록 ~이지만)가 적절합니다.'),
    jsonb_build_object('number',90,
      'question',E'비록 대회에서 이기진 못했지만, 난 내가 자랑스러웠다.',
      'options',jsonb_build_array(E'Since I didn''t win the contest, I was proud of myself.',E'I didn''t win the contest since I was proud of myself.',E'Though I didn''t win the contest, I was proud of myself.',E'I didn''t win the contest although I was proud of myself.',E'Until I didn''t win the contest, I was proud of myself.'),
      'answer',E'3',
      'explanation',E'"비록 ~했지만"은 양보의 의미이므로 though가 적절합니다.'),
    jsonb_build_object('number',91,
      'question',E'그는 많이 아팠지만, 일하러 갔다. (정답 2개)',
      'options',jsonb_build_array(E'He was very sick, so he went to work.',E'He was very sick, but he went to work.',E'If he was very sick, he went to work.',E'Since he was very sick, he went to work.',E'Although he was very sick, he went to work.'),
      'answer',E'2,5',
      'explanation',E'"아팠지만"은 역접/양보의 의미입니다. ② but(역접 접속사)과 ⑤ although(양보 접속사)가 적절합니다. ① so(결과), ③ if(조건), ④ since(이유)는 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',92,
      'question',E'비가 내리고 있었지만, 우리는 운동장에서 축구를 했다.',
      'options',jsonb_build_array(E'It played, though the we, soccer on, was raining, playground.',E'Though it was raining, we played soccer on the playground.',E'Since it was raining, we played soccer on the playground.',E'We played soccer on the playground because it was raining.',E'It was raining, so we played soccer on the playground.'),
      'answer',E'2',
      'explanation',E'"비가 내리고 있었지만"은 양보의 의미이므로 though가 적절합니다. ① 단어 나열 오류, ③④ 이유, ⑤ 결과를 나타내어 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',93,
      'question',E'그녀는 열심히 공부하기 때문에, 항상 좋은 점수를 받는다.',
      'options',jsonb_build_array(E'Always good, she since, studies, she, gets, grades, hard.',E'Though she studies hard, she always gets good grades.',E'Since she studies hard, she always gets good grades.',E'She always gets good grades, so she studies hard.',E'She studies hard although she always gets good grades.'),
      'answer',E'3',
      'explanation',E'"~때문에"는 이유를 나타내므로 since가 적절합니다. ② though는 양보, ④ 인과관계 역전, ⑤ although는 양보로 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',94,
      'question',E'비록 나는 돈이 거의 없지만, 정말로 행복하다.',
      'options',jsonb_build_array(E'Since I have little money, I''m really happy.',E'I''m really happy, so I have little money.',E'Because I have little money, I''m really happy.',E'Though I have little money, I''m really happy.',E'I''m really happy because I have little money.'),
      'answer',E'4',
      'explanation',E'"비록 ~이지만"은 양보의 의미이므로 though가 적절합니다.'),
    jsonb_build_object('number',95,
      'question',E'부모님이 주말 동안 집에 안 계셨기 때문에, 나는 남동생을 돌봐야만 했다.',
      'options',jsonb_build_array(E'Though my parents were not home during the weekend, I had to take care of my little brother.',E'Since my parents were not home during the weekend, I had to take care of my little brother.',E'Although my parents were not home during the weekend, I had to take care of my little brother.',E'Even though my parents were not home during the weekend, I had to take care of my little brother.',E'My parents were not home during the weekend, but I had to take care of my little brother.'),
      'answer',E'2',
      'explanation',E'"~때문에"는 이유를 나타내므로 since가 적절합니다. ①③④ 양보, ⑤ 역접은 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',96,
      'question',E'비록 그 집은 붕괴되었지만, 아무도 다치지 않았다.',
      'options',jsonb_build_array(E'Since the house was destroyed, no one was hurt.',E'The house was destroyed, so no one was hurt.',E'Even though the house was destroyed, no one was hurt.',E'Because the house was destroyed, no one was hurt.',E'The house was destroyed although no one was hurt.'),
      'answer',E'3',
      'explanation',E'"비록 ~했지만"은 양보의 의미이므로 even though가 적절합니다. ①④ 이유, ② 결과, ⑤ 양보절의 내용이 뒤바뀌어 어색합니다.'),
    jsonb_build_object('number',97,
      'question',E'그는 그림 그리기를 잘했으므로 만화 그리는 법을 쉽게 배울 수 있었다.',
      'options',jsonb_build_array(E'Though he was good at painting, he could easily learn how to draw cartoons.',E'Since he was good at painting, he could easily learn how to draw cartoons.',E'Although he was good at painting, he could easily learn how to draw cartoons.',E'He was good at painting, but he could easily learn how to draw cartoons.',E'Even though he was good at painting, he could easily learn how to draw cartoons.'),
      'answer',E'2',
      'explanation',E'"~했으므로"는 이유를 나타내므로 since가 적절합니다. ①③⑤ 양보, ④ 역접은 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',98,
      'question',E'비록 이번 여행은 짧았지만, 나는 정말 즐거웠다.',
      'options',jsonb_build_array(E'Since this trip was short, I really enjoyed it.',E'I really enjoyed it, so this trip was short.',E'Because this trip was short, I really enjoyed it.',E'This trip was short, so I really enjoyed it.',E'Although this trip was short, I really enjoyed it.'),
      'answer',E'5',
      'explanation',E'"비록 ~했지만"은 양보의 의미이므로 although가 적절합니다.'),
    jsonb_build_object('number',99,
      'question',E'그는 50년도 더 전에 세상을 떠났지만, 그의 정신은 우리와 함께 영원히 남아 있을 것이다.',
      'options',jsonb_build_array(E'Since he passed away more than 50 years ago, his spirit will remain with us forever.',E'As he passed away more than 50 years ago, his spirit will remain with us forever.',E'Because he passed away more than 50 years ago, his spirit will remain with us forever.',E'Though he passed away more than 50 years ago, his spirit will remain with us forever.',E'If he passed away more than 50 years ago, his spirit will remain with us forever.'),
      'answer',E'4',
      'explanation',E'"떠났지만"은 양보의 의미이므로 though가 적절합니다. ①②③ 이유, ⑤ 조건은 문맥에 맞지 않습니다.'),
    jsonb_build_object('number',100,
      'question',E'나는 쉽게 살이 찌기 때문에 항상 다이어트 중이다.',
      'options',jsonb_build_array(E'Though I gain weight easily, I am always on a diet.',E'I am always on a diet although I gain weight easily.',E'I am always on a diet since I gain weight easily.',E'Even though I gain weight easily, I am always on a diet.',E'I gain weight easily, but I am always on a diet.'),
      'answer',E'3',
      'explanation',E'"~때문에"는 이유를 나타내므로 since가 적절합니다. ①④ 양보, ② although(양보), ⑤ 역접은 문맥에 맞지 않습니다.')
  );

  a := jsonb_build_array();

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (E'접속사 since/though Step 2', E'접속사 since/though', q, a, 'problem', 'interactive');
END $$;
