-- 명사를 꾸며주는 분사 Step 1 — 110문항 (7파트)
-- template_topic: 명사를 꾸며주는 분사
-- category: problem, mode: interactive

DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'명사를 꾸며주는 분사 Step 1';

  -- Part 1~3 (Q1~Q51)
  q1 := jsonb_build_array(

jsonb_build_object('number',1,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nLook at the dog ___ in the river. (swim)',
  'answer',E'swimming',
  'acceptedAnswers',jsonb_build_array('swimming'),
  'explanation',E'개가 강에서 수영하고 있는 중(능동/진행) → 현재분사 swimming'),
jsonb_build_object('number',2,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe ___ baby finally fell asleep. (cry)',
  'answer',E'crying',
  'acceptedAnswers',jsonb_build_array('crying'),
  'explanation',E'아기가 울고 있는 중(능동/진행) → 현재분사 crying'),
jsonb_build_object('number',3,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nShe is reading a book ___ in French. (write)',
  'answer',E'written',
  'acceptedAnswers',jsonb_build_array('written'),
  'explanation',E'책이 프랑스어로 쓰여진 것(수동/완료) → 과거분사 written'),
jsonb_build_object('number',4,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe window ___ by the storm was repaired yesterday. (break)',
  'answer',E'broken',
  'acceptedAnswers',jsonb_build_array('broken'),
  'explanation',E'창문이 폭풍에 의해 깨진 것(수동/완료) → 과거분사 broken'),
jsonb_build_object('number',5,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe man ___ next to the door is my homeroom teacher. (stand)',
  'answer',E'standing',
  'acceptedAnswers',jsonb_build_array('standing'),
  'explanation',E'남자가 문 옆에 서 있는 중(능동/진행) → 현재분사 standing'),
jsonb_build_object('number',6,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nWe watched the leaves ___ slowly from the trees. (fall)',
  'answer',E'falling',
  'acceptedAnswers',jsonb_build_array('falling'),
  'explanation',E'나뭇잎이 천천히 떨어지고 있는 중(능동/진행) → 현재분사 falling'),
jsonb_build_object('number',7,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe girl ___ by the teacher received a prize. (choose)',
  'answer',E'chosen',
  'acceptedAnswers',jsonb_build_array('chosen'),
  'explanation',E'소녀가 선생님에 의해 선택된 것(수동/완료) → 과거분사 chosen'),
jsonb_build_object('number',8,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThere is a car ___ in front of our house. (park)',
  'answer',E'parked',
  'acceptedAnswers',jsonb_build_array('parked'),
  'explanation',E'차가 주차되어 있는 상태(수동/완료) → 과거분사 parked'),
jsonb_build_object('number',9,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe news ___ on TV last night surprised everyone. (report)',
  'answer',E'reported',
  'acceptedAnswers',jsonb_build_array('reported'),
  'explanation',E'뉴스가 TV에서 보도된 것(수동/완료) → 과거분사 reported'),
jsonb_build_object('number',10,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nDo you know the woman ___ a blue scarf around her neck? (wear)',
  'answer',E'wearing',
  'acceptedAnswers',jsonb_build_array('wearing'),
  'explanation',E'여자가 스카프를 두르고 있는 중(능동/진행) → 현재분사 wearing'),
jsonb_build_object('number',11,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nI found some old coins ___ under the floor. (hide)',
  'answer',E'hidden',
  'acceptedAnswers',jsonb_build_array('hidden'),
  'explanation',E'동전이 바닥 아래에 숨겨져 있던 것(수동/완료) → 과거분사 hidden'),
jsonb_build_object('number',12,
  'question',E'괄호 안의 단어를 분사의 알맞은 형태로 바꾸어 빈칸에 쓰시오.\n\nThe students ___ for the contest looked very excited. (prepare)',
  'answer',E'preparing',
  'acceptedAnswers',jsonb_build_array('preparing'),
  'explanation',E'학생들이 대회를 준비하고 있는 중(능동/진행) → 현재분사 preparing'),
jsonb_build_object('number',13,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nLook at the (sleeping / slept) cat on the sofa.',
  'options',jsonb_build_array('sleeping','slept'),
  'answer','1',
  'explanation',E'고양이가 자고 있는 중(능동/진행) → 현재분사 sleeping이 명사 cat을 앞에서 수식'),
jsonb_build_object('number',14,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nDon''t step on the (fallen / falling) leaves on the ground.',
  'options',jsonb_build_array('fallen','falling'),
  'answer','1',
  'explanation',E'나뭇잎이 이미 떨어진 상태(완료) → 과거분사 fallen. 바닥에 있는 잎은 이미 떨어진 결과'),
jsonb_build_object('number',15,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe letter (writing / written) by my grandmother made me cry.',
  'options',jsonb_build_array('writing','written'),
  'answer','2',
  'explanation',E'편지가 할머니에 의해 쓰여진 것(수동/완료) → 과거분사 written. by + 행위자가 단서'),
jsonb_build_object('number',16,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe boy (playing / played) the guitar over there is my cousin.',
  'options',jsonb_build_array('playing','played'),
  'answer','1',
  'explanation',E'소년이 기타를 치고 있는 중(능동/진행) → 현재분사 playing'),
jsonb_build_object('number',17,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nShe wore a dress (designing / designed) by a famous artist.',
  'options',jsonb_build_array('designing','designed'),
  'answer','2',
  'explanation',E'드레스가 유명한 예술가에 의해 디자인된 것(수동/완료) → 과거분사 designed. by + 행위자가 단서'),
jsonb_build_object('number',18,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe road (connecting / connected) the two towns is very narrow.',
  'options',jsonb_build_array('connecting','connected'),
  'answer','1',
  'explanation',E'도로가 두 마을을 연결하고 있는 중(능동/진행) → 현재분사 connecting. 도로가 스스로 연결하는 주체'),
jsonb_build_object('number',19,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nMost children find horror movies (frightening / frightened).',
  'options',jsonb_build_array('frightening','frightened'),
  'answer','1',
  'explanation',E'공포 영화가 무서움을 유발하는 것(감정 유발 → 사물 주어) → 현재분사 frightening. find + 목적어 + 분사(목적격 보어)'),
jsonb_build_object('number',20,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nShe looked (disappointing / disappointed) when she heard the result.',
  'options',jsonb_build_array('disappointing','disappointed'),
  'answer','2',
  'explanation',E'그녀가 실망감을 느끼는 것(감정을 느끼는 사람) → 과거분사 disappointed. look + 형용사(분사)'),
jsonb_build_object('number',21,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThere were many people (waiting / waited) in line at the bakery.',
  'options',jsonb_build_array('waiting','waited'),
  'answer','1',
  'explanation',E'사람들이 줄을 서서 기다리고 있는 중(능동/진행) → 현재분사 waiting'),
jsonb_build_object('number',22,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThis is one of the most (touching / touched) stories I''ve ever read.',
  'options',jsonb_build_array('touching','touched'),
  'answer','1',
  'explanation',E'이야기가 감동을 주는 것(감정 유발 → 사물 주어) → 현재분사 touching'),
jsonb_build_object('number',23,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe police caught the man (stealing / stolen) money from the store.',
  'options',jsonb_build_array('stealing','stolen'),
  'answer','1',
  'explanation',E'남자가 돈을 훔치고 있는 현장(능동/진행) → 현재분사 stealing. catch + 목적어 + 현재분사(~하는 것을 잡다)'),
jsonb_build_object('number',24,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nI was deeply (moving / moved) by his speech.',
  'options',jsonb_build_array('moving','moved'),
  'answer','2',
  'explanation',E'내가 감동을 받은 것(감정을 느끼는 사람) → 과거분사 moved. by + 행위자/원인이 단서'),
jsonb_build_object('number',25,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe documentary was so (boring / bored) that I fell asleep.',
  'options',jsonb_build_array('boring','bored'),
  'answer','1',
  'explanation',E'다큐멘터리가 지루함을 유발하는 것(감정 유발 → 사물 주어) → 현재분사 boring'),
jsonb_build_object('number',26,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nHe always feels (exciting / excited) before a soccer game.',
  'options',jsonb_build_array('exciting','excited'),
  'answer','2',
  'explanation',E'그가 흥분감을 느끼는 것(감정을 느끼는 사람) → 과거분사 excited. feel + 형용사(분사)'),
jsonb_build_object('number',27,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe fence (surrounding / surrounded) the garden was painted white.',
  'options',jsonb_build_array('surrounding','surrounded'),
  'answer','1',
  'explanation',E'울타리가 정원을 둘러싸고 있는 것(능동/진행) → 현재분사 surrounding. 울타리가 둘러싸는 주체'),
jsonb_build_object('number',28,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nMy grandfather has a box (filling / filled) with old photographs.',
  'options',jsonb_build_array('filling','filled'),
  'answer','2',
  'explanation',E'상자가 사진으로 채워져 있는 상태(수동/완료) → 과거분사 filled. be filled with(~로 가득 찬)'),
jsonb_build_object('number',29,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe children were (confusing / confused) by the teacher''s explanation.',
  'options',jsonb_build_array('confusing','confused'),
  'answer','2',
  'explanation',E'아이들이 혼란을 느끼는 것(감정을 느끼는 사람) → 과거분사 confused. by + 원인이 단서'),
jsonb_build_object('number',30,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe laptop (using / used) by my sister broke down this morning.',
  'options',jsonb_build_array('using','used'),
  'answer','2',
  'explanation',E'노트북이 언니/누나에 의해 사용되는 것(수동) → 과거분사 used. by + 행위자가 단서'),
jsonb_build_object('number',31,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nHe showed me a photo (taking / taken) at his graduation ceremony.',
  'options',jsonb_build_array('taking','taken'),
  'answer','2',
  'explanation',E'사진이 졸업식에서 찍힌 것(수동/완료) → 과거분사 taken'),
jsonb_build_object('number',32,
  'question',E'괄호 안에서 알맞은 것을 고르시오.\n\nThe singer (performing / performed) on stage right now is only 16 years old.',
  'options',jsonb_build_array('performing','performed'),
  'answer','1',
  'explanation',E'가수가 지금 무대에서 공연하고 있는 중(능동/진행) → 현재분사 performing. right now가 진행 단서'),
jsonb_build_object('number',33,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The girl is my classmate.\n• She is singing on the stage.',
  'answer',E'The girl singing on the stage is my classmate.',
  'acceptedAnswers',jsonb_build_array('The girl singing on the stage is my classmate.','The girl singing on the stage is my classmate'),
  'explanation',E'She is singing → 능동/진행이므로 현재분사 singing 사용. 주격 관계대명사절(who is singing)을 분사구로 축소'),
jsonb_build_object('number',34,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• I know the man.\n• He is wearing a black hat.',
  'answer',E'I know the man wearing a black hat.',
  'acceptedAnswers',jsonb_build_array('I know the man wearing a black hat.','I know the man wearing a black hat'),
  'explanation',E'He is wearing → 능동/진행이므로 현재분사 wearing 사용. 관계대명사절(who is wearing)을 분사구로 축소'),
jsonb_build_object('number',35,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The building was built in 1980.\n• It is still being used.',
  'answer',E'The building built in 1980 is still being used.',
  'acceptedAnswers',jsonb_build_array('The building built in 1980 is still being used.','The building built in 1980 is still being used'),
  'explanation',E'was built → 수동/완료이므로 과거분사 built 사용. 관계대명사절(which was built)을 분사구로 축소'),
jsonb_build_object('number',36,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• Look at the birds.\n• They are flying over the mountain.',
  'answer',E'Look at the birds flying over the mountain.',
  'acceptedAnswers',jsonb_build_array('Look at the birds flying over the mountain.','Look at the birds flying over the mountain'),
  'explanation',E'They are flying → 능동/진행이므로 현재분사 flying 사용. 관계대명사절(which are flying)을 분사구로 축소'),
jsonb_build_object('number',37,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• I like the music.\n• It is played at this café.',
  'answer',E'I like the music played at this café.',
  'acceptedAnswers',jsonb_build_array('I like the music played at this café.','I like the music played at this café','I like the music played at this cafe.','I like the music played at this cafe'),
  'explanation',E'It is played → 수동이므로 과거분사 played 사용. 관계대명사절(which is played)을 분사구로 축소'),
jsonb_build_object('number',38,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The boy is my neighbor.\n• He is riding a red bicycle.',
  'answer',E'The boy riding a red bicycle is my neighbor.',
  'acceptedAnswers',jsonb_build_array('The boy riding a red bicycle is my neighbor.','The boy riding a red bicycle is my neighbor'),
  'explanation',E'He is riding → 능동/진행이므로 현재분사 riding 사용. 관계대명사절(who is riding)을 분사구로 축소'),
jsonb_build_object('number',39,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• There is a woman over there.\n• She is holding two big bags.',
  'answer',E'There is a woman holding two big bags over there.',
  'acceptedAnswers',jsonb_build_array('There is a woman holding two big bags over there.','There is a woman holding two big bags over there'),
  'explanation',E'She is holding → 능동/진행이므로 현재분사 holding 사용. 분사구가 명사 woman 바로 뒤에 위치하고 over there는 문장 끝으로 이동'),
jsonb_build_object('number',40,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• We ate the pasta.\n• It was cooked by my dad.',
  'answer',E'We ate the pasta cooked by my dad.',
  'acceptedAnswers',jsonb_build_array('We ate the pasta cooked by my dad.','We ate the pasta cooked by my dad'),
  'explanation',E'It was cooked → 수동/완료이므로 과거분사 cooked 사용. 관계대명사절(which was cooked)을 분사구로 축소'),
jsonb_build_object('number',41,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The bridge connects the island to the mainland.\n• It was destroyed by the typhoon.',
  'answer',E'The bridge connecting the island to the mainland was destroyed by the typhoon.',
  'acceptedAnswers',jsonb_build_array('The bridge connecting the island to the mainland was destroyed by the typhoon.','The bridge connecting the island to the mainland was destroyed by the typhoon'),
  'explanation',E'The bridge connects → 능동/진행이므로 현재분사 connecting 사용. 첫 번째 문장의 동사를 분사로 바꿔 주어를 수식'),
jsonb_build_object('number',42,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• Do you see the boy?\n• He is kicking a ball near the tree.',
  'answer',E'Do you see the boy kicking a ball near the tree?',
  'acceptedAnswers',jsonb_build_array('Do you see the boy kicking a ball near the tree?','Do you see the boy kicking a ball near the tree'),
  'explanation',E'He is kicking → 능동/진행이므로 현재분사 kicking 사용. 관계대명사절(who is kicking)을 분사구로 축소'),
jsonb_build_object('number',43,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• I spoke to the woman.\n• She was sitting next to me on the plane.',
  'answer',E'I spoke to the woman sitting next to me on the plane.',
  'acceptedAnswers',jsonb_build_array('I spoke to the woman sitting next to me on the plane.','I spoke to the woman sitting next to me on the plane'),
  'explanation',E'She was sitting → 능동/진행이므로 현재분사 sitting 사용. 관계대명사절(who was sitting)을 분사구로 축소'),
jsonb_build_object('number',44,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• They found a wallet.\n• It was left on the bench.',
  'answer',E'They found a wallet left on the bench.',
  'acceptedAnswers',jsonb_build_array('They found a wallet left on the bench.','They found a wallet left on the bench'),
  'explanation',E'It was left → 수동/완료이므로 과거분사 left 사용. 관계대명사절(which was left)을 분사구로 축소'),
jsonb_build_object('number',45,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The children are my students.\n• They are playing in the playground.',
  'answer',E'The children playing in the playground are my students.',
  'acceptedAnswers',jsonb_build_array('The children playing in the playground are my students.','The children playing in the playground are my students'),
  'explanation',E'They are playing → 능동/진행이므로 현재분사 playing 사용. 관계대명사절(who are playing)을 분사구로 축소'),
jsonb_build_object('number',46,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• She always reads articles.\n• They are published in science magazines.',
  'answer',E'She always reads articles published in science magazines.',
  'acceptedAnswers',jsonb_build_array('She always reads articles published in science magazines.','She always reads articles published in science magazines'),
  'explanation',E'They are published → 수동이므로 과거분사 published 사용. 관계대명사절(which are published)을 분사구로 축소'),
jsonb_build_object('number',47,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The man is a famous chef.\n• He is cooking in the kitchen right now.',
  'answer',E'The man cooking in the kitchen right now is a famous chef.',
  'acceptedAnswers',jsonb_build_array('The man cooking in the kitchen right now is a famous chef.','The man cooking in the kitchen right now is a famous chef'),
  'explanation',E'He is cooking → 능동/진행이므로 현재분사 cooking 사용. 관계대명사절(who is cooking)을 분사구로 축소'),
jsonb_build_object('number',48,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• We visited a museum.\n• It was opened last year.',
  'answer',E'We visited a museum opened last year.',
  'acceptedAnswers',jsonb_build_array('We visited a museum opened last year.','We visited a museum opened last year'),
  'explanation',E'It was opened → 수동/완료이므로 과거분사 opened 사용. 관계대명사절(which was opened)을 분사구로 축소'),
jsonb_build_object('number',49,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The soldier was taken to the hospital.\n• He was injured in the battle.',
  'answer',E'The soldier injured in the battle was taken to the hospital.',
  'acceptedAnswers',jsonb_build_array('The soldier injured in the battle was taken to the hospital.','The soldier injured in the battle was taken to the hospital'),
  'explanation',E'He was injured → 수동/완료이므로 과거분사 injured 사용. 관계대명사절(who was injured)을 분사구로 축소'),
jsonb_build_object('number',50,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• She is one of the scientists.\n• They are working on the climate change project.',
  'answer',E'She is one of the scientists working on the climate change project.',
  'acceptedAnswers',jsonb_build_array('She is one of the scientists working on the climate change project.','She is one of the scientists working on the climate change project'),
  'explanation',E'They are working → 능동/진행이므로 현재분사 working 사용. 관계대명사절(who are working)을 분사구로 축소'),
jsonb_build_object('number',51,
  'question',E'주어진 두 문장을 현재분사 또는 과거분사를 이용하여 한 문장으로 쓰시오.\n\n• The novel became a bestseller.\n• It was translated into 30 languages.',
  'answer',E'The novel translated into 30 languages became a bestseller.',
  'acceptedAnswers',jsonb_build_array('The novel translated into 30 languages became a bestseller.','The novel translated into 30 languages became a bestseller'),
  'explanation',E'It was translated → 수동/완료이므로 과거분사 translated 사용. 관계대명사절(which was translated)을 분사구로 축소')

  );

  -- Part 4~5 (Q52~Q81)
  q2 := jsonb_build_array(

jsonb_build_object('number',52,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nLook at the <u>running</u> horse in the field.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'명사(horse)의 동작을 묘사 → 현재분사'),
jsonb_build_object('number',53,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\n<u>Running</u> every morning is good for your health.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'문장의 주어 역할 → 동명사'),
jsonb_build_object('number',54,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThe <u>swimming</u> pool is closed on Mondays.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'수영장(swimming pool)은 \'수영을 위한 pool\' → 용도를 나타내는 동명사'),
jsonb_build_object('number',55,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nI saw a girl <u>dancing</u> on the rooftop.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'소녀의 동작을 묘사 → 현재분사'),
jsonb_build_object('number',56,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nHer hobby is <u>collecting</u> rare stamps from around the world.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'보어로서 취미의 내용을 설명 → 동명사'),
jsonb_build_object('number',57,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThe woman <u>talking</u> with the principal is Minho\'s mom.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'명사(woman)의 동작을 묘사 → 현재분사'),
jsonb_build_object('number',58,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThis is a <u>sleeping</u> bag for camping in cold weather.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'\'잠을 자기 위한 가방\' → 용도를 나타내는 동명사'),
jsonb_build_object('number',59,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nLook at the baby <u>sleeping</u> in the stroller.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'아기의 동작(자고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',60,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThere is a <u>waiting</u> room on the second floor.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'\'기다리기 위한 방\' → 용도를 나타내는 동명사'),
jsonb_build_object('number',61,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThe students <u>waiting</u> outside the classroom are her fans.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'학생들의 동작(기다리고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',62,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\n<u>Reading</u> comic books helps improve vocabulary.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'문장의 주어 역할 → 동명사'),
jsonb_build_object('number',63,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nI know the boy <u>reading</u> a comic book under the tree.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'소년의 동작(읽고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',64,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThese are non-<u>smoking</u> seats. Please move to the other section.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'\'흡연을 위한/흡연용 좌석\'의 부정 → 용도를 나타내는 동명사'),
jsonb_build_object('number',65,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nI saw an old man <u>smoking</u> a pipe by the window.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'노인의 동작(담배를 피우고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',66,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nMy uncle bought me a pair of <u>running</u> shoes for my birthday.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'\'달리기를 위한 신발\' → 용도를 나타내는 동명사'),
jsonb_build_object('number',67,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThe man <u>fixing</u> the roof is our new neighbor.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'남자의 동작(고치고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',68,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nHis job is <u>designing</u> websites for small businesses.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','2',
  'explanation',E'보어로서 직업의 내용을 설명 → 동명사'),
jsonb_build_object('number',69,
  'question',E'밑줄 친 부분이 현재분사이면 \'현재분사\', 동명사이면 \'동명사\'라고 쓰시오.\n\nThe teacher noticed a girl <u>drawing</u> pictures instead of taking notes.',
  'options',jsonb_build_array('현재분사','동명사'),
  'answer','1',
  'explanation',E'소녀의 동작(그리고 있는)을 묘사 → 현재분사'),
jsonb_build_object('number',70,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n버스 정류장에서 기다리고 있는 그 소녀는 내 여동생이다.\n(the girl / at / wait / the bus stop / is / my sister)',
  'answer',E'The girl waiting at the bus stop is my sister.',
  'acceptedAnswers',jsonb_build_array('The girl waiting at the bus stop is my sister.','The girl waiting at the bus stop is my sister'),
  'explanation',E'wait → waiting (현재분사로 변형): The girl waiting at the bus stop is my sister.'),
jsonb_build_object('number',71,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n나는 영어로 쓰인 편지를 받았다.\n(I / a letter / in / received / English / write)',
  'answer',E'I received a letter written in English.',
  'acceptedAnswers',jsonb_build_array('I received a letter written in English.','I received a letter written in English'),
  'explanation',E'write → written (과거분사로 변형): I received a letter written in English.'),
jsonb_build_object('number',72,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n하늘을 날고 있는 저 비행기를 봐.\n(look / that / in / fly / at / airplane / the sky)',
  'answer',E'Look at that airplane flying in the sky.',
  'acceptedAnswers',jsonb_build_array('Look at that airplane flying in the sky.','Look at that airplane flying in the sky'),
  'explanation',E'fly → flying (현재분사로 변형): Look at that airplane flying in the sky.'),
jsonb_build_object('number',73,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n나무 아래 잠들어 있는 고양이는 내 것이다.\n(the cat / under / sleep / mine / is / the tree)',
  'answer',E'The cat sleeping under the tree is mine.',
  'acceptedAnswers',jsonb_build_array('The cat sleeping under the tree is mine.','The cat sleeping under the tree is mine'),
  'explanation',E'sleep → sleeping (현재분사로 변형): The cat sleeping under the tree is mine.'),
jsonb_build_object('number',74,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n한국에서 만들어진 스마트폰들은 전 세계에서 사용된다.\n(smartphones / in Korea / make / are used / all over the world)',
  'answer',E'Smartphones made in Korea are used all over the world.',
  'acceptedAnswers',jsonb_build_array('Smartphones made in Korea are used all over the world.','Smartphones made in Korea are used all over the world'),
  'explanation',E'make → made (과거분사로 변형): Smartphones made in Korea are used all over the world.'),
jsonb_build_object('number',75,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n그 화재로 피해를 입은 집들은 보험 처리를 받았다.\n(the houses / by the fire / damage / received / insurance)',
  'answer',E'The houses damaged by the fire received insurance.',
  'acceptedAnswers',jsonb_build_array('The houses damaged by the fire received insurance.','The houses damaged by the fire received insurance'),
  'explanation',E'damage → damaged (과거분사로 변형): The houses damaged by the fire received insurance.'),
jsonb_build_object('number',76,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\nTom과 이야기를 나누고 있는 소녀가 누군지 아니?\n(do you know / with Tom / the girl / talk)',
  'answer',E'Do you know the girl talking with Tom?',
  'acceptedAnswers',jsonb_build_array('Do you know the girl talking with Tom?','Do you know the girl talking with Tom'),
  'explanation',E'talk → talking (현재분사로 변형): Do you know the girl talking with Tom?'),
jsonb_build_object('number',77,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n그들은 무대 위에서 춤추고 있는 아이들의 사진을 찍었다.\n(they / of / on stage / took / dance / photos / the children)',
  'answer',E'They took photos of the children dancing on stage.',
  'acceptedAnswers',jsonb_build_array('They took photos of the children dancing on stage.','They took photos of the children dancing on stage'),
  'explanation',E'dance → dancing (현재분사로 변형): They took photos of the children dancing on stage.'),
jsonb_build_object('number',78,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n그는 독일에서 제조된 중고차를 샀다.\n(he / a used car / in Germany / bought / make)',
  'answer',E'He bought a used car made in Germany.',
  'acceptedAnswers',jsonb_build_array('He bought a used car made in Germany.','He bought a used car made in Germany'),
  'explanation',E'make → made (과거분사로 변형): He bought a used car made in Germany.'),
jsonb_build_object('number',79,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n우리 마을에서 발견된 그 고대 유물들은 박물관으로 옮겨졌다.\n(the ancient artifacts / in our town / find / to the museum / were moved)',
  'answer',E'The ancient artifacts found in our town were moved to the museum.',
  'acceptedAnswers',jsonb_build_array('The ancient artifacts found in our town were moved to the museum.','The ancient artifacts found in our town were moved to the museum'),
  'explanation',E'find → found (과거분사로 변형): The ancient artifacts found in our town were moved to the museum.'),
jsonb_build_object('number',80,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n나는 경찰에 의해 쫓기고 있는 남자를 보았다.\n(I / a man / by the police / saw / chase)',
  'answer',E'I saw a man chased by the police.',
  'acceptedAnswers',jsonb_build_array('I saw a man chased by the police.','I saw a man chased by the police'),
  'explanation',E'chase → chased (과거분사로 변형): I saw a man chased by the police.'),
jsonb_build_object('number',81,
  'question',E'주어진 단어들을 올바른 순서로 배열하여 문장을 완성하시오. (필요시 단어의 형태를 변형할 것)\n\n피카소가 그린 그 그림들은 수백만 달러의 가치가 있다.\n(the paintings / by Picasso / paint / are worth / millions of dollars)',
  'answer',E'The paintings painted by Picasso are worth millions of dollars.',
  'acceptedAnswers',jsonb_build_array('The paintings painted by Picasso are worth millions of dollars.','The paintings painted by Picasso are worth millions of dollars'),
  'explanation',E'paint → painted (과거분사로 변형): The paintings painted by Picasso are worth millions of dollars.')
  );

  -- Part 6~7 (Q82~Q110)
  q3 := jsonb_build_array(

jsonb_build_object('number',82,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe man <u>drove</u> the truck is my father.',
  'answer',E'drove → driving',
  'acceptedAnswers',jsonb_build_array(E'drove → driving',E'driving'),
  'explanation',E'남자가 트럭을 운전하고 있는 중(능동/진행) → 현재분사 driving'),
jsonb_build_object('number',83,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nLook at the girl <u>danced</u> in the rain.',
  'answer',E'danced → dancing',
  'acceptedAnswers',jsonb_build_array(E'danced → dancing',E'dancing'),
  'explanation',E'소녀가 춤추고 있는 중(능동/진행) → 현재분사 dancing'),
jsonb_build_object('number',84,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nI read a book <u>writing</u> by a famous Korean author.',
  'answer',E'writing → written',
  'acceptedAnswers',jsonb_build_array(E'writing → written',E'written'),
  'explanation',E'책이 쓰인 것(수동/완료) → 과거분사 written'),
jsonb_build_object('number',85,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nShe found a puppy <u>abandoned</u> on the side of the road and took it home.',
  'answer',E'오류 없음',
  'acceptedAnswers',jsonb_build_array(E'오류 없음',E'오류없음',E'abandoned'),
  'explanation',E'강아지가 버려진 것(수동/완료) → 과거분사 abandoned가 올바름. 오류 없음.'),
jsonb_build_object('number',86,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThere were pieces of <u>break</u> glass on the kitchen floor.',
  'answer',E'break → broken',
  'acceptedAnswers',jsonb_build_array(E'break → broken',E'broken'),
  'explanation',E'유리가 깨진 것(수동/완료) → 과거분사 broken'),
jsonb_build_object('number',87,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nCan you fix this <u>breaking</u> bicycle for me?',
  'answer',E'breaking → broken',
  'acceptedAnswers',jsonb_build_array(E'breaking → broken',E'broken'),
  'explanation',E'자전거가 고장난 상태(수동/완료) → 과거분사 broken'),
jsonb_build_object('number',88,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe people <u>inviting</u> to the party are all close friends.',
  'answer',E'inviting → invited',
  'acceptedAnswers',jsonb_build_array(E'inviting → invited',E'invited'),
  'explanation',E'사람들이 초대받은 것(수동) → 과거분사 invited'),
jsonb_build_object('number',89,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nHe is the most <u>bored</u> speaker I have ever listened to.',
  'answer',E'bored → boring',
  'acceptedAnswers',jsonb_build_array(E'bored → boring',E'boring'),
  'explanation',E'화자가 지루함을 유발하는 주체 → 현재분사 boring'),
jsonb_build_object('number',90,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nLook at the photos <u>taking</u> at the school festival last year.',
  'answer',E'taking → taken',
  'acceptedAnswers',jsonb_build_array(E'taking → taken',E'taken'),
  'explanation',E'사진이 찍힌 것(수동/완료) → 과거분사 taken'),
jsonb_build_object('number',91,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe movie was so <u>excited</u> that we watched it twice.',
  'answer',E'excited → exciting',
  'acceptedAnswers',jsonb_build_array(E'excited → exciting',E'exciting'),
  'explanation',E'영화가 흥미를 유발하는 주체 → 현재분사 exciting'),
jsonb_build_object('number',92,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nI saw a box <u>leaving</u> at the front door this morning.',
  'answer',E'leaving → left',
  'acceptedAnswers',jsonb_build_array(E'leaving → left',E'left'),
  'explanation',E'상자가 놓여진 것(수동/완료) → 과거분사 left'),
jsonb_build_object('number',93,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe girl <u>is calling</u> my name over there is my best friend.',
  'answer',E'is calling → calling',
  'acceptedAnswers',jsonb_build_array(E'is calling → calling',E'calling'),
  'explanation',E'분사가 명사를 수식할 때 be동사 없이 현재분사만 사용 → calling'),
jsonb_build_object('number',94,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nMost of the people <u>surprising</u> by the news left the room immediately.',
  'answer',E'surprising → surprised',
  'acceptedAnswers',jsonb_build_array(E'surprising → surprised',E'surprised'),
  'explanation',E'사람들이 놀란 것(감정을 느끼는 주체) → 과거분사 surprised'),
jsonb_build_object('number',95,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe language <u>speaking</u> in Brazil is Portuguese, not Spanish.',
  'answer',E'speaking → spoken',
  'acceptedAnswers',jsonb_build_array(E'speaking → spoken',E'spoken'),
  'explanation',E'언어가 사용되는 것(수동) → 과거분사 spoken'),
jsonb_build_object('number',96,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nShe bought a coat <u>making</u> of recycled materials.',
  'answer',E'making → made',
  'acceptedAnswers',jsonb_build_array(E'making → made',E'made'),
  'explanation',E'코트가 만들어진 것(수동) → 과거분사 made'),
jsonb_build_object('number',97,
  'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 쓰시오.\n\nThe woman <u>sat</u> by the window is reading a novel.',
  'answer',E'sat → sitting',
  'acceptedAnswers',jsonb_build_array(E'sat → sitting',E'sitting'),
  'explanation',E'여자가 앉아 있는 중(능동/진행) → 현재분사 sitting'),
jsonb_build_object('number',98,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n공원에서 조깅하고 있는 저 남자는 우리 아버지이다.\n【조건】jog, the man 사용 / 8단어',
  'answer',E'The man jogging in the park is my father.',
  'acceptedAnswers',jsonb_build_array(E'The man jogging in the park is my father.',E'The man jogging in the park is my father'),
  'explanation',E'jog → jogging (현재분사): The man jogging in the park is my father.'),
jsonb_build_object('number',99,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n나는 한국에서 만들어진 자동차를 사고 싶다.\n【조건】make, in Korea 사용 / 9단어',
  'answer',E'I want to buy a car made in Korea.',
  'acceptedAnswers',jsonb_build_array(E'I want to buy a car made in Korea.',E'I want to buy a car made in Korea'),
  'explanation',E'make → made (과거분사, 수동): I want to buy a car made in Korea.'),
jsonb_build_object('number',100,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n그 도서관에서 공부하고 있는 학생들은 다음 주에 시험이 있다.\n【조건】study, have an exam 사용 / 12단어',
  'answer',E'The students studying in the library have an exam next week.',
  'acceptedAnswers',jsonb_build_array(E'The students studying in the library have an exam next week.',E'The students studying in the library have an exam next week'),
  'explanation',E'study → studying (현재분사): The students studying in the library have an exam next week.'),
jsonb_build_object('number',101,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n나는 독일어로 쓰인 오래된 편지를 발견했다.\n【조건】find, write 사용 / 9단어',
  'answer',E'I found an old letter written in German.',
  'acceptedAnswers',jsonb_build_array(E'I found an old letter written in German.',E'I found an old letter written in German'),
  'explanation',E'write → written (과거분사, 수동): I found an old letter written in German.'),
jsonb_build_object('number',102,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n나를 향해 달려오고 있는 개가 있다. 무섭다!\n【조건】run toward, there is 사용 / 8단어',
  'answer',E'There is a dog running toward me.',
  'acceptedAnswers',jsonb_build_array(E'There is a dog running toward me.',E'There is a dog running toward me'),
  'explanation',E'run → running (현재분사): There is a dog running toward me.'),
jsonb_build_object('number',103,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n그 회의에 초대된 사람들은 모두 제시간에 도착했다.\n【조건】invite, the people 사용 / 10단어',
  'answer',E'The people invited to the meeting all arrived on time.',
  'acceptedAnswers',jsonb_build_array(E'The people invited to the meeting all arrived on time.',E'The people invited to the meeting all arrived on time'),
  'explanation',E'invite → invited (과거분사, 수동): The people invited to the meeting all arrived on time.'),
jsonb_build_object('number',104,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n나는 그 콘서트에서 찍은 사진들을 SNS에 올렸다.\n【조건】take, post 사용 / 11단어',
  'answer',E'I posted the photos taken at the concert on social media.',
  'acceptedAnswers',jsonb_build_array(E'I posted the photos taken at the concert on social media.',E'I posted the photos taken at the concert on social media'),
  'explanation',E'take → taken (과거분사, 수동): I posted the photos taken at the concert on social media.'),
jsonb_build_object('number',105,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n그가 노래하고 있는 소년이야? 목소리가 정말 아름답다!\n【조건】Is he, sing 사용 / 7단어',
  'answer',E'Is he the boy singing over there?',
  'acceptedAnswers',jsonb_build_array(E'Is he the boy singing over there?',E'Is he the boy singing over there'),
  'explanation',E'sing → singing (현재분사): Is he the boy singing over there?'),
jsonb_build_object('number',106,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n우리 할머니는 지역 예술가가 만든 목걸이를 항상 하신다.\n【조건】make, a local artist 사용 / 11단어',
  'answer',E'My grandmother always wears a necklace made by a local artist.',
  'acceptedAnswers',jsonb_build_array(E'My grandmother always wears a necklace made by a local artist.',E'My grandmother always wears a necklace made by a local artist'),
  'explanation',E'make → made (과거분사, 수동): My grandmother always wears a necklace made by a local artist.'),
jsonb_build_object('number',107,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n야구공에 의해 깨진 창문을 보아라.\n【조건】look, break, by 사용 / 8단어',
  'answer',E'Look at the window broken by a baseball.',
  'acceptedAnswers',jsonb_build_array(E'Look at the window broken by a baseball.',E'Look at the window broken by a baseball'),
  'explanation',E'break → broken (과거분사, 수동): Look at the window broken by a baseball.'),
jsonb_build_object('number',108,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n그 화재로 소실된 그림들의 가치는 수십억 원에 달했다.\n【조건】destroy, the paintings 사용 / 11단어',
  'answer',E'The paintings destroyed in the fire were worth billions of won.',
  'acceptedAnswers',jsonb_build_array(E'The paintings destroyed in the fire were worth billions of won.',E'The paintings destroyed in the fire were worth billions of won'),
  'explanation',E'destroy → destroyed (과거분사, 수동): The paintings destroyed in the fire were worth billions of won.'),
jsonb_build_object('number',109,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n그녀는 전 세계 30개국 언어로 번역된 소설을 쓴 작가이다.\n【조건】translate, the writer 사용 / 14단어',
  'answer',E'She is the writer of a novel translated into 30 languages around the world.',
  'acceptedAnswers',jsonb_build_array(E'She is the writer of a novel translated into 30 languages around the world.',E'She is the writer of a novel translated into 30 languages around the world'),
  'explanation',E'translate → translated (과거분사, 수동): She is the writer of a novel translated into 30 languages around the world.'),
jsonb_build_object('number',110,
  'question',E'주어진 우리말과 조건에 맞게 영작하시오.\n\n무대 위에서 바이올린을 연주하고 있는 소녀가 내 여동생이다. 그녀는 올해 겨우 11살이다.\n【조건】play, the violin, on stage 사용 / 12단어로 쓸 것 (두 번째 문장 제외)',
  'answer',E'The girl playing the violin on stage is my younger sister.',
  'acceptedAnswers',jsonb_build_array(E'The girl playing the violin on stage is my younger sister.',E'The girl playing the violin on stage is my younger sister'),
  'explanation',E'play → playing (현재분사): The girl playing the violin on stage is my younger sister.')
  );

  a := jsonb_build_array(E'swimming', E'crying', E'written', E'broken', E'standing', E'falling', E'chosen', E'parked', E'reported', E'wearing', E'hidden', E'preparing', '1', '1', '2', '1', '2', '1', '1', '2', '1', '1', '1', '2', '1', '2', '1', '2', '2', '2', '2', '1', E'The girl singing on the stage is my classmate.', E'I know the man wearing a black hat.', E'The building built in 1980 is still being used.', E'Look at the birds flying over the mountain.', E'I like the music played at this café.', E'The boy riding a red bicycle is my neighbor.', E'There is a woman holding two big bags over there.', E'We ate the pasta cooked by my dad.', E'The bridge connecting the island to the mainland was destroyed by the typhoon.', E'Do you see the boy kicking a ball near the tree?', E'I spoke to the woman sitting next to me on the plane.', E'They found a wallet left on the bench.', E'The children playing in the playground are my students.', E'She always reads articles published in science magazines.', E'The man cooking in the kitchen right now is a famous chef.', E'We visited a museum opened last year.', E'The soldier injured in the battle was taken to the hospital.', E'She is one of the scientists working on the climate change project.', E'The novel translated into 30 languages became a bestseller.', '1', '2', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', E'The girl waiting at the bus stop is my sister.', E'I received a letter written in English.', E'Look at that airplane flying in the sky.', E'The cat sleeping under the tree is mine.', E'Smartphones made in Korea are used all over the world.', E'The houses damaged by the fire received insurance.', E'Do you know the girl talking with Tom?', E'They took photos of the children dancing on stage.', E'He bought a used car made in Germany.', E'The ancient artifacts found in our town were moved to the museum.', E'I saw a man chased by the police.', E'The paintings painted by Picasso are worth millions of dollars.', E'drove → driving', E'danced → dancing', E'writing → written', E'오류 없음', E'break → broken', E'breaking → broken', E'inviting → invited', E'bored → boring', E'taking → taken', E'excited → exciting', E'leaving → left', E'is calling → calling', E'surprising → surprised', E'speaking → spoken', E'making → made', E'sat → sitting', E'The man jogging in the park is my father.', E'I want to buy a car made in Korea.', E'The students studying in the library have an exam next week.', E'I found an old letter written in German.', E'There is a dog running toward me.', E'The people invited to the meeting all arrived on time.', E'I posted the photos taken at the concert on social media.', E'Is he the boy singing over there?', E'My grandmother always wears a necklace made by a local artist.', E'Look at the window broken by a baseball.', E'The paintings destroyed in the fire were worth billions of won.', E'She is the writer of a novel translated into 30 languages around the world.', E'The girl playing the violin on stage is my younger sister.');

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    E'명사를 꾸며주는 분사 Step 1',
    E'명사를 꾸며주는 분사',
    q1 || q2 || q3,
    a,
    'problem',
    'interactive'
  );
END $$;
