-- 주어동사수일치 Step 1 — 55문항 (60 answer items)
-- template_topic: 주어동사수일치
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'주어동사수일치 Step 1';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Warm-up: 2지선다 MCQ (Q1~Q10)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
      'question',E'[Warm-up] 알맞은 것을 고르시오.\n\nHalf of the water in these bottles ___ for the guests.',
      'options',jsonb_build_array('is','are'),
      'answer','1',
      'explanation',E'water는 불가산명사 → 단수동사 is'),
    jsonb_build_object('number',2,
      'question',E'알맞은 것을 고르시오.\n\nHalf of the students in my class ___ interested in science.',
      'options',jsonb_build_array('is','are'),
      'answer','2',
      'explanation',E'students는 복수명사 → 복수동사 are'),
    jsonb_build_object('number',3,
      'question',E'알맞은 것을 고르시오.\n\nOne of the windows in the building ___ broken during the storm.',
      'options',jsonb_build_array('was','were'),
      'answer','1',
      'explanation',E'one of + 복수명사 → 단수동사 was'),
    jsonb_build_object('number',4,
      'question',E'알맞은 것을 고르시오.\n\nA number of volunteers ___ signed up for the charity event.',
      'options',jsonb_build_array('has','have'),
      'answer','2',
      'explanation',E'a number of + 복수명사 → 복수동사 have'),
    jsonb_build_object('number',5,
      'question',E'알맞은 것을 고르시오.\n\nThe number of electric vehicles on the road ___ increasing rapidly.',
      'options',jsonb_build_array('is','are'),
      'answer','1',
      'explanation',E'the number of + 복수명사 → 단수동사 is'),
    jsonb_build_object('number',6,
      'question',E'알맞은 것을 고르시오.\n\nTwo thirds of the earth''s surface ___ covered with water.',
      'options',jsonb_build_array('is','are'),
      'answer','1',
      'explanation',E'surface는 단수명사 → 단수동사 is'),
    jsonb_build_object('number',7,
      'question',E'알맞은 것을 고르시오.\n\nMost of the children in the neighborhood ___ in the park after school.',
      'options',jsonb_build_array('play','plays'),
      'answer','1',
      'explanation',E'children은 복수명사 → 복수동사 play'),
    jsonb_build_object('number',8,
      'question',E'알맞은 것을 고르시오.\n\nEach of the participants ___ given a certificate at the end of the program.',
      'options',jsonb_build_array('was','were'),
      'answer','1',
      'explanation',E'each of + 복수명사 → 단수동사 was'),
    jsonb_build_object('number',9,
      'question',E'알맞은 것을 고르시오.\n\nEvery student in the advanced class ___ expected to submit a research paper.',
      'options',jsonb_build_array('is','are'),
      'answer','1',
      'explanation',E'every + 단수명사 → 단수동사 is'),
    jsonb_build_object('number',10,
      'question',E'알맞은 것을 고르시오.\n\nAbout 30 percent of the world''s freshwater ___ stored underground.',
      'options',jsonb_build_array('is','are'),
      'answer','1',
      'explanation',E'freshwater는 불가산명사 → 단수동사 is'),

    -- ═══════════════════════════════════════════
    -- Part 1: 빈칸 채우기 서술형 (Q11~Q22)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
      'question',E'[Part 1] 주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nOne fifth of the planet''s land area ___ desert. (be)',
      'answer',E'is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'land area는 단수 → is'),
    jsonb_build_object('number',12,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nThree quarters of the employees ___ the new policy unfair. (find)',
      'answer',E'find',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'employees는 복수 → find'),
    jsonb_build_object('number',13,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nMost of the information on the website ___ updated weekly. (be)',
      'answer',E'is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'information은 불가산 → is'),
    jsonb_build_object('number',14,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nAbout 60 percent of the students ___ to school by bus. (come)',
      'answer',E'come',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'students는 복수 → come'),
    jsonb_build_object('number',15,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nA number of scientists ___ that plastic pollution is a global crisis. (believe)',
      'answer',E'believe',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'a number of + 복수명사 → 복수동사 believe'),
    jsonb_build_object('number',16,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nThe number of wild animals in the forest ___ drastically over the past decade. (decrease)',
      'answer',E'has decreased',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'the number of → 단수동사, 현재완료 has decreased'),
    jsonb_build_object('number',17,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nHalf of the cake ___ before the guests arrived. (eat)',
      'answer',E'was eaten',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'cake는 단수/불가산, 수동태 → was eaten'),
    jsonb_build_object('number',18,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nTwo thirds of the books on that shelf ___ written by Korean authors. (be)',
      'answer',E'were',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'books는 복수 → were (written)'),
    jsonb_build_object('number',19,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nNone of the answers the students gave ___ correct. (be)',
      'answer',E'were',
      'acceptedAnswers',jsonb_build_array('was'),
      'explanation',E'answers는 복수 → were'),
    jsonb_build_object('number',20,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nEach of the team members ___ a different role to play in the project. (have)',
      'answer',E'has',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'each of + 복수명사 → 단수동사 has'),
    jsonb_build_object('number',21,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nForty percent of the world''s food ___ wasted every year. (be)',
      'answer',E'is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'food는 불가산 → is (wasted)'),
    jsonb_build_object('number',22,
      'question',E'주어진 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nSome of the furniture in the new office ___ already damaged when it arrived. (be)',
      'answer',E'was',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'furniture는 불가산 단수 → was'),

    -- ═══════════════════════════════════════════
    -- Part 2: 5지선다 MCQ (Q23~Q32)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',23,
      'question',E'[Part 2] 어법상 틀린 것을 고르시오.',
      'options',jsonb_build_array(
        'Half of the milk has already been used.',
        'Two thirds of the students were absent yesterday.',
        'The number of tourists visiting the island are growing.',
        'Each of the puppies needs special care.',
        'Most of the homework was done before dinner.'
      ),
      'answer','3',
      'explanation',E'the number of + 복수명사 → 단수동사. are → is'),
    jsonb_build_object('number',24,
      'question',E'어법상 틀린 것을 고르시오.',
      'options',jsonb_build_array(
        'A number of reports have been submitted this week.',
        'One of my best friends live in Canada.',
        'About 80 percent of the ocean floor remains unexplored.',
        'Some of the apples in the bag were rotten.',
        'Every child in the classroom has a textbook.'
      ),
      'answer','2',
      'explanation',E'one of + 복수명사 → 단수동사. live → lives'),
    jsonb_build_object('number',25,
      'question',E'어법상 틀린 것을 고르시오.',
      'options',jsonb_build_array(
        'Most of the sugar was used up by noon.',
        'Three fifths of the participants was from Asia.',
        'None of the equipment was damaged in the flood.',
        'Half of the volunteers have already finished.',
        'A number of new cafés have opened downtown.'
      ),
      'answer','2',
      'explanation',E'participants는 복수명사 → 복수동사. was → were'),
    jsonb_build_object('number',26,
      'question',E'어법상 틀린 것을 고르시오.',
      'options',jsonb_build_array(
        'Each student in the group has to give a presentation.',
        'Over half of the world''s coral reefs has been damaged.',
        'The number of homeless animals is a serious concern.',
        'Some of the coffee was spilled on the table.',
        'Two thirds of the budget was spent on marketing.'
      ),
      'answer','2',
      'explanation',E'coral reefs는 복수명사 → 복수동사. has → have'),
    jsonb_build_object('number',27,
      'question',E'어법상 틀린 것을 고르시오.',
      'options',jsonb_build_array(
        'None of the water in the tank was safe to drink.',
        'Most of the cities in the region has strict air quality laws.',
        'About one quarter of the students prefer online classes.',
        'Every rule in this school has a reason behind it.',
        'A number of issues were raised during the meeting.'
      ),
      'answer','2',
      'explanation',E'cities는 복수명사 → 복수동사. has → have'),
    jsonb_build_object('number',28,
      'question',E'어법상 옳은 것을 고르시오.',
      'options',jsonb_build_array(
        'Half of the chairs in the room needs to be replaced.',
        'The number of students who failed the exam were surprising.',
        'Each of the paintings in the gallery have a unique style.',
        'Two thirds of the planet''s freshwater is locked in glaciers.',
        'A number of research has shown that sleep is important.'
      ),
      'answer','4',
      'explanation',E'freshwater는 불가산 단수 → is 올바름'),
    jsonb_build_object('number',29,
      'question',E'어법상 옳은 것을 고르시오.',
      'options',jsonb_build_array(
        'One of the reasons are still unclear to us.',
        'Most of the evidence point to the same conclusion.',
        'About 40 percent of the plastic bottles becomes garbage.',
        'A number of problems has arisen since the policy changed.',
        'Every employee in the company is required to wear a badge.'
      ),
      'answer','5',
      'explanation',E'every + 단수명사 → 단수동사 is 올바름'),
    jsonb_build_object('number',30,
      'question',E'어법상 옳은 것을 고르시오.',
      'options',jsonb_build_array(
        'The number of volunteers at the shelter are growing.',
        'Some of the milk in the fridge were already expired.',
        'Two fifths of the students in our school speaks two languages.',
        'None of the solutions suggested by the team was practical.',
        'Each of the athletes were preparing for the final race.'
      ),
      'answer','4',
      'explanation',E'none of + 복수명사 → 단수동사 was 가능'),
    jsonb_build_object('number',31,
      'question',E'어법상 옳은 것을 고르시오.',
      'options',jsonb_build_array(
        'Half of the audience were clearly bored during the speech.',
        'A number of student has applied for the exchange program.',
        'Most of the money donated to the charity goes to education.',
        'Three quarters of the land in that area are uninhabitable.',
        'One of my cousins are studying medicine at university.'
      ),
      'answer','3',
      'explanation',E'money는 불가산 → goes 올바름'),
    jsonb_build_object('number',32,
      'question',E'어법상 옳은 것을 고르시오.',
      'options',jsonb_build_array(
        'About 70 percent of all emails send daily are spam.',
        'The number of books published each year are increasing.',
        'None of the cookies I baked yesterday were too sweet.',
        'Each of the toys in the store has been carefully tested.',
        'Most of the workers at the factory works the night shift.'
      ),
      'answer','3',
      'explanation',E'cookies는 복수 → were 올바름 (none of + 복수 → 복수동사 가능)'),

    -- ═══════════════════════════════════════════
    -- Part 3: 오류 수정 서술형 (Q33~Q42)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',33,
      'question',E'[Part 3] 문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nTwo thirds of the ocean floor remain unexplored by scientists.',
      'answer',E'No error',
      'acceptedAnswers',jsonb_build_array('no error'),
      'explanation',E'ocean floor는 단수 → remains도 가능하지만, two thirds of the ocean floor + remain도 허용'),
    jsonb_build_object('number',34,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nThe number of endangered species are growing at an alarming rate.',
      'answer',E'The number of endangered species is growing at an alarming rate.',
      'acceptedAnswers',jsonb_build_array(E'are → is','is'),
      'explanation',E'the number of + 복수명사 → 단수동사. are → is'),
    jsonb_build_object('number',35,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nMost of the electricity in this country come from renewable sources.',
      'answer',E'Most of the electricity in this country comes from renewable sources.',
      'acceptedAnswers',jsonb_build_array(E'come → comes','comes'),
      'explanation',E'electricity는 불가산 단수 → 단수동사. come → comes'),
    jsonb_build_object('number',36,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nOne of the most effective ways to reduce stress are regular exercise.',
      'answer',E'One of the most effective ways to reduce stress is regular exercise.',
      'acceptedAnswers',jsonb_build_array(E'are → is','is'),
      'explanation',E'one of + 복수명사 → 단수동사. are → is'),
    jsonb_build_object('number',37,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nAbout half of all food produced globally is lost or wasted each year.',
      'answer',E'No error',
      'acceptedAnswers',jsonb_build_array('no error'),
      'explanation',E'food는 불가산 → is 올바름'),
    jsonb_build_object('number',38,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nEach of the participants in the study were asked to complete a questionnaire.',
      'answer',E'Each of the participants in the study was asked to complete a questionnaire.',
      'acceptedAnswers',jsonb_build_array(E'were → was','was'),
      'explanation',E'each of + 복수명사 → 단수동사. were → was'),
    jsonb_build_object('number',39,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nA number of new policies has been introduced since the new director took office.',
      'answer',E'A number of new policies have been introduced since the new director took office.',
      'acceptedAnswers',jsonb_build_array(E'has → have','have'),
      'explanation',E'a number of + 복수명사 → 복수동사. has → have'),
    jsonb_build_object('number',40,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nSeventy-five percent of the students in our class uses public transportation daily.',
      'answer',E'Seventy-five percent of the students in our class use public transportation daily.',
      'acceptedAnswers',jsonb_build_array(E'uses → use','use'),
      'explanation',E'students는 복수 → 복수동사. uses → use'),
    jsonb_build_object('number',41,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nNone of the furniture in the newly renovated room was damaged during the move.',
      'answer',E'No error',
      'acceptedAnswers',jsonb_build_array('no error'),
      'explanation',E'furniture는 불가산 단수 → was 올바름'),
    jsonb_build_object('number',42,
      'question',E'문법적 오류를 찾아 고치시오. 오류가 없으면 "No error"라고 쓰시오.\n\nEvery employee who works in the building are required to show their ID at the entrance.',
      'answer',E'Every employee who works in the building is required to show their ID at the entrance.',
      'acceptedAnswers',jsonb_build_array(E'are → is','is'),
      'explanation',E'every + 단수명사 → 단수동사. are → is'),

    -- ═══════════════════════════════════════════
    -- Part 4: 단락 빈칸 채우기 + subParts (Q43~Q45)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',43,
      'question',E'[Part 4] 괄호 안의 동사를 알맞은 형태로 빈칸 (A)~(D)에 쓰시오.\n\nA recent survey on teenage eating habits revealed some interesting findings. About 65 percent of teenagers (A)___ (skip) breakfast at least three times a week. Most of the students surveyed (B)___ (say) that they simply do not have enough time in the morning. Interestingly, the number of students who eat a proper lunch (C)___ (be) also decreasing. However, one third of the students (D)___ (report) that they try to eat more vegetables than before.',
      'answer',E'skip / say / is / report',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'(A) teenagers는 복수 → skip. (B) students는 복수 → say. (C) the number of → 단수 is. (D) students는 복수 → report',
      'subParts',jsonb_build_array(
        jsonb_build_object('label','(A)','answer','skip','acceptedAnswers',jsonb_build_array()),
        jsonb_build_object('label','(B)','answer','say','acceptedAnswers',jsonb_build_array('said')),
        jsonb_build_object('label','(C)','answer','is','acceptedAnswers',jsonb_build_array()),
        jsonb_build_object('label','(D)','answer','report','acceptedAnswers',jsonb_build_array('reported'))
      )),
    jsonb_build_object('number',44,
      'question',E'괄호 안의 동사를 알맞은 형태로 빈칸 (A)~(C)에 쓰시오.\n\nWater is one of the most precious resources on Earth. According to scientists, only about three percent of all water on the planet (A)___ (be) fresh water. Furthermore, two thirds of that fresh water (B)___ (be) locked in glaciers and polar ice caps, making it inaccessible. A number of organizations around the world (C)___ (work) to find better solutions to the global water crisis.',
      'answer',E'is / is / are working',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'(A) water는 불가산 단수 → is. (B) fresh water는 불가산 단수 → is. (C) a number of + 복수명사 → 복수동사 are working',
      'subParts',jsonb_build_array(
        jsonb_build_object('label','(A)','answer','is','acceptedAnswers',jsonb_build_array()),
        jsonb_build_object('label','(B)','answer','is','acceptedAnswers',jsonb_build_array()),
        jsonb_build_object('label','(C)','answer','are working','acceptedAnswers',jsonb_build_array('work'))
      )),
    jsonb_build_object('number',45,
      'question',E'대화의 빈칸에 괄호 안의 동사를 알맞은 형태로 쓰시오.\n\nTeacher: Let''s look at the data from our class survey. Half of the class (A)___ (prefer) project-based learning over traditional tests.\nStudent: That''s interesting! And what about homework?\nTeacher: Well, the number of students who complete homework every day (B)___ (be) actually higher than we expected — about 70 percent.',
      'answer',E'prefers / is',
      'acceptedAnswers',jsonb_build_array(),
      'explanation',E'(A) half of the class에서 class는 집합명사(단수 취급) → prefers. (B) the number of → 단수동사 is',
      'subParts',jsonb_build_array(
        jsonb_build_object('label','(A)','answer','prefers','acceptedAnswers',jsonb_build_array('prefer')),
        jsonb_build_object('label','(B)','answer','is','acceptedAnswers',jsonb_build_array())
      )),

    -- ═══════════════════════════════════════════
    -- Part 5: 영작 서술형 (Q46~Q55)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',46,
      'question',E'[Part 5] 주어진 조건에 맞게 영작하시오.\n[조건: half of 사용 / population, city, live abroad]\n\n그 도시 인구의 절반은 해외에서 살았다.',
      'answer',E'Half of the city''s population lived abroad.',
      'acceptedAnswers',jsonb_build_array('Half of the city''s population lived abroad'),
      'explanation',E'population은 단수 → lived(과거). Half of the city''s population lived abroad.'),
    jsonb_build_object('number',47,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: two thirds of 사용 / budget, spend, research]\n\n예산의 3분의 2가 연구에 쓰였다.',
      'answer',E'Two thirds of the budget was spent on research.',
      'acceptedAnswers',jsonb_build_array('Two thirds of the budget was spent on research'),
      'explanation',E'budget은 단수 → was spent. Two thirds of the budget was spent on research.'),
    jsonb_build_object('number',48,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: percent of 사용 / 80, plastic, recycle]\n\n플라스틱의 80퍼센트는 재활용되지 않는다.',
      'answer',E'Eighty percent of plastic is not recycled.',
      'acceptedAnswers',jsonb_build_array('Eighty percent of plastic is not recycled','80 percent of plastic is not recycled.','80 percent of plastic is not recycled'),
      'explanation',E'plastic은 불가산 → is not recycled'),
    jsonb_build_object('number',49,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: a number of 사용 / country, adopt, renewable energy]\n\n많은 나라들이 재생 에너지를 채택해 왔다.',
      'answer',E'A number of countries have adopted renewable energy.',
      'acceptedAnswers',jsonb_build_array('A number of countries have adopted renewable energy'),
      'explanation',E'a number of + 복수명사 → 복수동사 have adopted'),
    jsonb_build_object('number',50,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: the number of 사용 / online learner, grow, rapidly]\n\n온라인 학습자의 수가 빠르게 증가하고 있다.',
      'answer',E'The number of online learners is growing rapidly.',
      'acceptedAnswers',jsonb_build_array('The number of online learners is growing rapidly'),
      'explanation',E'the number of + 복수명사 → 단수동사 is growing'),
    jsonb_build_object('number',51,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: one of 사용 / biggest challenge, face, today]\n\n가장 큰 도전 과제 중 하나는 오늘날 우리가 직면하는 기후 변화이다.',
      'answer',E'One of the biggest challenges we face today is climate change.',
      'acceptedAnswers',jsonb_build_array('One of the biggest challenges we face today is climate change'),
      'explanation',E'one of + 복수명사 → 단수동사 is. One of the biggest challenges'),
    jsonb_build_object('number',52,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: most of 사용 / energy, consume, building]\n\n건물에서 소비되는 에너지의 대부분은 냉난방에 사용된다.',
      'answer',E'Most of the energy consumed in buildings is used for heating and cooling.',
      'acceptedAnswers',jsonb_build_array('Most of the energy consumed in buildings is used for heating and cooling'),
      'explanation',E'energy는 불가산 → 단수동사 is used'),
    jsonb_build_object('number',53,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: three quarters of 사용 / participant, female]\n\n참가자의 4분의 3이 여성이었다.',
      'answer',E'Three quarters of the participants were female.',
      'acceptedAnswers',jsonb_build_array('Three quarters of the participants were female'),
      'explanation',E'participants는 복수 → 복수동사 were'),
    jsonb_build_object('number',54,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건: each of 사용 / member, team, receive, award]\n\n팀의 각 구성원이 상을 받았다.',
      'answer',E'Each of the team members received an award.',
      'acceptedAnswers',jsonb_build_array('Each of the team members received an award','Each of the members of the team received an award.','Each of the members of the team received an award'),
      'explanation',E'each of + 복수명사 → 단수동사 received'),
    jsonb_build_object('number',55,
      'question',E'주어진 조건에 맞게 영작하시오.\n[조건 1: about one fifth of 사용 / 조건 2: 문장 앞에 배치 / atmosphere, oxygen]\n\n대기의 약 5분의 1은 산소이다.',
      'answer',E'About one fifth of the atmosphere is oxygen.',
      'acceptedAnswers',jsonb_build_array('About one fifth of the atmosphere is oxygen'),
      'explanation',E'atmosphere는 단수 → 단수동사 is')
  );

  a := jsonb_build_array();

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    E'주어동사수일치 Step 1',
    E'주어동사수일치',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
