DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '현재완료 Step 3';

  q := jsonb_build_array(
    -- ═══════════════════════════════════════════
    -- Part 1. 괄호 안의 단어를 활용하여 빈칸 완성하기 (Q1~Q10)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',1,
  'question',E'[Part 1] 괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nMy dog _______________ the ball three times today. (catch)',
  'answer',E'has caught',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료: has/have + p.p. catch → caught. 주어 My dog(3인칭 단수) → has caught'),
jsonb_build_object('number',2,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nWe _______________ in this town since 2015. (live)',
  'answer',E'have lived',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: since 2015(시점)와 함께. We(복수) → have lived'),
jsonb_build_object('number',3,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\n_______________ she ever _______________ a camel before? (ride)',
  'answer',E'Has / ridden',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 의문문: Has + 주어 + p.p.? ride → ridden',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','Has','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','ridden','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',4,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nI _______________ anything since breakfast. I''m starving. (not, eat)',
  'answer',E'haven''t eaten',
  'acceptedAnswers',jsonb_build_array(E'have not eaten'),
  'explanation',E'현재완료 부정: have not(haven''t) + p.p. eat → eaten'),
jsonb_build_object('number',5,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nThe team _______________ every match so far this season. (win)',
  'answer',E'has won',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료: The team(3인칭 단수) → has won. win → won'),
jsonb_build_object('number',6,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nHow long _______________ you _______________ each other? (know)',
  'answer',E'have / known',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 의문문: How long have + 주어 + p.p.? know → known',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','have','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','known','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',7,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nSomeone _______________ into my locker. Everything is missing. (break)',
  'answer',E'has broken',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 결과 용법: Someone(3인칭 단수) → has broken. break → broken'),
jsonb_build_object('number',8,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nShe _______________ for this company since she graduated. (work)',
  'answer',E'has worked',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: since she graduated(시점)와 함께. She → has worked'),
jsonb_build_object('number',9,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\n_______________ Tom _______________ his report yet? (finish)',
  'answer',E'Has / finished',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 의문문 + yet: Has + 주어 + p.p. + yet?',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','Has','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','finished','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',10,
  'question',E'괄호 안의 단어를 현재완료 시제에 맞게 활용하여 빈칸을 완성하시오.\n\nIt _______________ for three days. The river might flood. (rain)',
  'answer',E'has rained',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: It(3인칭 단수) → has rained'),

    -- ═══════════════════════════════════════════
    -- Part 2. 두 문장을 현재완료 한 문장으로 연결하기 (Q11~Q22)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',11,
  'question',E'[Part 2] 두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• I lost my wallet. • I don''t have it now.',
  'answer',E'I have lost my wallet.',
  'acceptedAnswers',jsonb_build_array(E'I have lost my wallet',E'I''ve lost my wallet.',E'I''ve lost my wallet'),
  'explanation',E'현재완료 결과 용법: 과거에 잃어버린 결과가 현재까지 영향. have lost'),
jsonb_build_object('number',12,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• She started learning French three years ago. • She still learns it.',
  'answer',E'She has learned French for three years.',
  'acceptedAnswers',jsonb_build_array(E'She has learned French for three years',E'She has studied French for three years.',E'She has studied French for three years'),
  'explanation',E'현재완료 계속 용법: 3년 전부터 지금까지 계속. for three years'),
jsonb_build_object('number',13,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• He went to Australia. • He is not here now.',
  'answer',E'He has gone to Australia.',
  'acceptedAnswers',jsonb_build_array(E'He has gone to Australia',E'He''s gone to Australia.',E'He''s gone to Australia'),
  'explanation',E'have gone to: ~에 가버렸다(아직 거기 있음). 결과 용법'),
jsonb_build_object('number',14,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• I met Jina for the first time in 2018. • We are still friends.',
  'answer',E'I have known Jina since 2018.',
  'acceptedAnswers',jsonb_build_array(E'I have known Jina since 2018',E'I''ve known Jina since 2018.',E'I''ve known Jina since 2018'),
  'explanation',E'현재완료 계속 용법: 2018년(시점)부터 지금까지 알고 지냄. since 2018'),
jsonb_build_object('number',15,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• My brother started playing the guitar two years ago. • He still plays it.',
  'answer',E'My brother has played the guitar for two years.',
  'acceptedAnswers',jsonb_build_array(E'My brother has played the guitar for two years'),
  'explanation',E'현재완료 계속 용법: for two years(기간)'),
jsonb_build_object('number',16,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• She moved to Seoul when she was ten. • She still lives there.',
  'answer',E'She has lived in Seoul since she was ten.',
  'acceptedAnswers',jsonb_build_array(E'She has lived in Seoul since she was ten'),
  'explanation',E'현재완료 계속 용법: since she was ten(시점)'),
jsonb_build_object('number',17,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• Tom broke his arm. • His arm is still broken now.',
  'answer',E'Tom has broken his arm.',
  'acceptedAnswers',jsonb_build_array(E'Tom has broken his arm'),
  'explanation',E'현재완료 결과 용법: 과거에 부러진 결과가 현재까지 지속'),
jsonb_build_object('number',18,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• I bought this bike five years ago. • I still use it.',
  'answer',E'I have had this bike for five years.',
  'acceptedAnswers',jsonb_build_array(E'I have had this bike for five years',E'I have used this bike for five years.',E'I have used this bike for five years',E'I''ve had this bike for five years.',E'I''ve used this bike for five years.'),
  'explanation',E'현재완료 계속 용법: have had = 소유해 왔다. for five years(기간)'),
jsonb_build_object('number',19,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• Amy went to New York. • She is still there.',
  'answer',E'Amy has gone to New York.',
  'acceptedAnswers',jsonb_build_array(E'Amy has gone to New York'),
  'explanation',E'have gone to: ~에 가버렸다(아직 거기 있음). 결과 용법'),
jsonb_build_object('number',20,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• We started studying together in 2020. • We still study together.',
  'answer',E'We have studied together since 2020.',
  'acceptedAnswers',jsonb_build_array(E'We have studied together since 2020',E'We''ve studied together since 2020.',E'We''ve studied together since 2020'),
  'explanation',E'현재완료 계속 용법: since 2020(시점)'),
jsonb_build_object('number',21,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• She began to take piano lessons four years ago. • She still takes them.',
  'answer',E'She has taken piano lessons for four years.',
  'acceptedAnswers',jsonb_build_array(E'She has taken piano lessons for four years'),
  'explanation',E'현재완료 계속 용법: take → taken. for four years(기간)'),
jsonb_build_object('number',22,
  'question',E'두 문장을 현재완료를 사용하여 한 문장으로 만드시오.\n\n• I first read this novel last summer. • I have read it three times total.',
  'answer',E'I have read this novel three times since last summer.',
  'acceptedAnswers',jsonb_build_array(E'I have read this novel three times since last summer',E'I''ve read this novel three times since last summer.',E'I''ve read this novel three times since last summer'),
  'explanation',E'현재완료 경험 용법: three times since last summer. read → read(p.p.)'),

    -- ═══════════════════════════════════════════
    -- Part 3. 대화 빈칸 완성하기 (Q23~Q30)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',23,
  'question',E'[Part 3] 대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Have you ever been to Jeju Island?\nB: Yes, _______________. I went there twice with my family.',
  'answer',E'I have',
  'acceptedAnswers',jsonb_build_array(E'Yes, I have',E'Yes I have'),
  'explanation',E'현재완료 의문문에 대한 긍정 대답: Yes, I have.'),
jsonb_build_object('number',24,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Is Mina in the classroom?\nB: No. She _______________ to the library. She''ll be back after lunch.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'has gone to the library'),
  'explanation',E'have gone to: ~에 가버렸다(아직 거기에 있음). She(3인칭 단수) → has gone'),
jsonb_build_object('number',25,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Where have you been? I''ve been looking for you!\nB: Sorry. I _______________ to the nurse''s office. I had a headache.',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'have been to the nurse''s office',E'''ve been'),
  'explanation',E'have been to: ~에 다녀왔다(갔다가 돌아옴). I → have been'),
jsonb_build_object('number',26,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Have you finished your science project yet?\nB: No, _______________. I still have a lot to do.',
  'answer',E'I haven''t',
  'acceptedAnswers',jsonb_build_array(E'No, I haven''t',E'No I haven''t',E'I have not',E'No, I have not'),
  'explanation',E'현재완료 의문문에 대한 부정 대답: No, I haven''t.'),
jsonb_build_object('number',27,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: How long _______________ you _______________ English?\nB: For about six years. I started in elementary school.',
  'answer',E'have / studied',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법 의문문: How long have you + p.p.?',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','have','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','studied','acceptedAnswers',jsonb_build_array('learned'))
  )),
jsonb_build_object('number',28,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Do you want to watch this drama?\nB: No thanks. I _______________ it already. Let''s watch something else.',
  'answer',E'have seen',
  'acceptedAnswers',jsonb_build_array(E'have watched',E'have already seen',E'have already watched',E'''ve seen',E'''ve watched'),
  'explanation',E'현재완료 완료 용법: already와 함께. I → have seen/watched'),
jsonb_build_object('number',29,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: Is Jake home?\nB: No. He _______________ to the gym. He won''t be back until dinner.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'has gone to the gym'),
  'explanation',E'have gone to: ~에 가버렸다(아직 거기에 있음). He → has gone'),
jsonb_build_object('number',30,
  'question',E'대화의 흐름에 맞게 빈칸을 완성하시오.\n\nA: _______________ you ever _______________ Indian food before?\nB: No, I haven''t. I''d love to try it!',
  'answer',E'Have / tried',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 경험 용법 의문문: Have you ever + p.p.?',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','Have','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','tried','acceptedAnswers',jsonb_build_array('eaten'))
  )),

    -- ═══════════════════════════════════════════
    -- Part 4. 오류 찾아 전체 문장 고쳐 쓰기 (Q31~Q40)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',31,
  'question',E'[Part 4] 밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nShe <u>have</u> finished her homework already.',
  'answer',E'She has finished her homework already.',
  'acceptedAnswers',jsonb_build_array(E'She has finished her homework already'),
  'explanation',E'She(3인칭 단수) → has. have → has'),
jsonb_build_object('number',32,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nI <u>have seen</u> her at the café <u>yesterday</u>.',
  'answer',E'I saw her at the café yesterday.',
  'acceptedAnswers',jsonb_build_array(E'I saw her at the café yesterday',E'I saw her at the cafe yesterday.',E'I saw her at the cafe yesterday'),
  'explanation',E'yesterday는 과거 시점 부사 → 현재완료 불가. 과거 시제 saw로 변경'),
jsonb_build_object('number',33,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nHe has <u>went</u> to Canada. He''s not here.',
  'answer',E'He has gone to Canada. He''s not here.',
  'acceptedAnswers',jsonb_build_array(E'He has gone to Canada. He''s not here'),
  'explanation',E'has + p.p. go의 과거분사는 gone(went는 과거형). went → gone'),
jsonb_build_object('number',34,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nThey have been married <u>for two years ago</u>.',
  'answer',E'They have been married for two years.',
  'acceptedAnswers',jsonb_build_array(E'They have been married for two years'),
  'explanation',E'for + 기간에 ago를 함께 쓸 수 없음. for two years ago → for two years'),
jsonb_build_object('number',35,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nHave you ever <u>rode</u> a horse before?',
  'answer',E'Have you ever ridden a horse before?',
  'acceptedAnswers',jsonb_build_array(E'Have you ever ridden a horse before'),
  'explanation',E'ride의 과거분사는 ridden(rode는 과거형). rode → ridden'),
jsonb_build_object('number',36,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nWe have <u>knew</u> each other since middle school.',
  'answer',E'We have known each other since middle school.',
  'acceptedAnswers',jsonb_build_array(E'We have known each other since middle school'),
  'explanation',E'know의 과거분사는 known(knew는 과거형). knew → known'),
jsonb_build_object('number',37,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nI haven''t seen Minji <u>since three months</u>.',
  'answer',E'I haven''t seen Minji for three months.',
  'acceptedAnswers',jsonb_build_array(E'I haven''t seen Minji for three months',E'I have not seen Minji for three months.',E'I have not seen Minji for three months'),
  'explanation',E'three months는 기간 → since가 아니라 for를 사용. since → for'),
jsonb_build_object('number',38,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\n<u>When have you visited</u> that museum?',
  'answer',E'When did you visit that museum?',
  'acceptedAnswers',jsonb_build_array(E'When did you visit that museum'),
  'explanation',E'When(특정 시점 질문)은 현재완료와 함께 쓸 수 없음. 과거 시제로 변경'),
jsonb_build_object('number',39,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nMy brother <u>didn''t wrote</u> to me since he moved abroad.',
  'answer',E'My brother hasn''t written to me since he moved abroad.',
  'acceptedAnswers',jsonb_build_array(E'My brother hasn''t written to me since he moved abroad',E'My brother has not written to me since he moved abroad.',E'My brother has not written to me since he moved abroad'),
  'explanation',E'since(시점)와 함께 → 현재완료 부정. didn''t wrote → hasn''t written'),
jsonb_build_object('number',40,
  'question',E'밑줄 친 부분에서 오류를 찾아 문장 전체를 바르게 고쳐 쓰시오.\n\nI have <u>gone</u> to Japan twice. It was amazing.',
  'answer',E'I have been to Japan twice. It was amazing.',
  'acceptedAnswers',jsonb_build_array(E'I have been to Japan twice. It was amazing'),
  'explanation',E'have been to: ~에 가본 적이 있다(경험). have gone to: 가버렸다(아직 거기 있음). 경험 표현이므로 gone → been'),

    -- ═══════════════════════════════════════════
    -- Part 5. 두 문장의 의미가 같도록 빈칸 채우기 (Q41~Q48)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',41,
  'question',E'[Part 5] 두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nI lost my key, and I don''t have it now.\n= I _______________ _______________ my key.',
  'answer',E'have lost',
  'acceptedAnswers',jsonb_build_array(E'''ve lost'),
  'explanation',E'현재완료 결과 용법: 잃어버린 결과가 현재까지 지속. have lost'),
jsonb_build_object('number',42,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nJane began to study Chinese four years ago, and she still studies it.\n= Jane _______________ _______________ Chinese _______________ four years.',
  'answer',E'has studied / for',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: has studied + for(기간)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','has studied','acceptedAnswers',jsonb_build_array('has learned')),
    jsonb_build_object('label','(2)','answer','for','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',43,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nHe moved to this city in 2016, and he still lives here.\n= He _______________ _______________ in this city _______________ 2016.',
  'answer',E'has lived / since',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: has lived + since(시점)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','has lived','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','since','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',44,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nShe went to London. She is still there now.\n= She _______________ _______________ to London.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'have gone to: ~에 가버렸다(아직 거기에 있음). She → has gone'),
jsonb_build_object('number',45,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nI started playing soccer when I was eight. I still play it.\n= I _______________ _______________ soccer _______________ I was eight.',
  'answer',E'have played / since',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: have played + since(시점)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','have played','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','since','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',46,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nMy sister bought this laptop two years ago. She still uses it.\n= My sister _______________ _______________ this laptop _______________ two years.',
  'answer',E'has had / for',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: has had(소유) 또는 has used + for(기간)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','has had','acceptedAnswers',jsonb_build_array('has used')),
    jsonb_build_object('label','(2)','answer','for','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',47,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nMark began leading the company ten years ago. He still leads it.\n= Mark _______________ _______________ the company _______________ ten years.',
  'answer',E'has led / for',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: has led(lead → led) + for(기간)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','has led','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','for','acceptedAnswers',jsonb_build_array())
  )),
jsonb_build_object('number',48,
  'question',E'두 문장의 뜻이 같도록 빈칸에 알맞은 말을 쓰시오.\n\nI first met Andrew in 2011. We still know each other.\n= I _______________ _______________ Andrew _______________ 2011.',
  'answer',E'have known / since',
  'acceptedAnswers',jsonb_build_array(),
  'explanation',E'현재완료 계속 용법: have known(know → known) + since(시점)',
  'subParts',jsonb_build_array(
    jsonb_build_object('label','(1)','answer','have known','acceptedAnswers',jsonb_build_array()),
    jsonb_build_object('label','(2)','answer','since','acceptedAnswers',jsonb_build_array())
  )),

    -- ═══════════════════════════════════════════
    -- Part 6. 조건 영작 (Q49~Q60)
    -- ═══════════════════════════════════════════

    jsonb_build_object('number',49,
  'question',E'[Part 6] 주어진 조건에 맞게 우리말을 영작하시오.\n\n나는 캐나다에 가본 적이 없다.\n[조건] be 동사의 현재완료 시제 사용 / 축약형 사용하지 말 것 / 6단어로 쓸 것',
  'answer',E'I have never been to Canada.',
  'acceptedAnswers',jsonb_build_array(E'I have never been to Canada'),
  'explanation',E'have been to: ~에 가본 적이 있다. 부정: have never been to. 축약형 불가 → I have'),
jsonb_build_object('number',50,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n그녀가 한국 음식을 먹어본 적이 있니?\n[조건] eat의 현재완료 시제 사용 / 6단어로 쓸 것',
  'answer',E'Has she ever eaten Korean food?',
  'acceptedAnswers',jsonb_build_array(E'Has she ever eaten Korean food'),
  'explanation',E'현재완료 경험 의문문: Has she ever + p.p.? eat → eaten'),
jsonb_build_object('number',51,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n그는 2019년부터 이 학교에서 가르치고 있다.\n[조건] teach를 사용 / since를 반드시 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'He has taught at this school since 2019.',
  'acceptedAnswers',jsonb_build_array(E'He has taught at this school since 2019',E'He''s taught at this school since 2019.'),
  'explanation',E'현재완료 계속 용법: teach → taught. since 2019(시점)'),
jsonb_build_object('number',52,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n우리는 서로를 2014년 이후로 알고 지내왔다.\n[조건] know를 사용 / since를 반드시 쓸 것 / 7단어로 쓸 것',
  'answer',E'We have known each other since 2014.',
  'acceptedAnswers',jsonb_build_array(E'We have known each other since 2014'),
  'explanation',E'현재완료 계속 용법: know → known. 7단어: We have known each other since 2014.'),
jsonb_build_object('number',53,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n나는 이 자전거를 3년 동안 사용해 오고 있다.\n[조건] use 또는 have를 사용 / for를 반드시 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'I have used this bike for three years.',
  'acceptedAnswers',jsonb_build_array(E'I have used this bike for three years',E'I have had this bike for three years.',E'I have had this bike for three years',E'I''ve used this bike for three years.',E'I''ve had this bike for three years.'),
  'explanation',E'현재완료 계속 용법: have used/have had + for three years(기간)'),
jsonb_build_object('number',54,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\nTom은 그의 반에서 가장 많은 책을 읽어왔다.\n[조건] read를 현재완료로 사용 / most를 반드시 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'Tom has read the most books in his class.',
  'acceptedAnswers',jsonb_build_array(E'Tom has read the most books in his class'),
  'explanation',E'현재완료: has read(read → read). the most books = 가장 많은 책'),
jsonb_build_object('number',55,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n나는 그녀가 어릴 때부터 그녀를 알아왔다.\n[조건] know를 사용 / since와 child를 반드시 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'I have known her since she was a child.',
  'acceptedAnswers',jsonb_build_array(E'I have known her since she was a child',E'I''ve known her since she was a child.',E'I''ve known her since she was a child'),
  'explanation',E'현재완료 계속 용법: have known + since she was a child(시점)'),
jsonb_build_object('number',56,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\nAmy는 초등학생이었을 때부터 Yuna Kim을 좋아해왔다.\n[조건] love와 since를 반드시 사용 / elementary school student를 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'Amy has loved Yuna Kim since she was an elementary school student.',
  'acceptedAnswers',jsonb_build_array(E'Amy has loved Yuna Kim since she was an elementary school student'),
  'explanation',E'현재완료 계속 용법: has loved + since she was an elementary school student'),
jsonb_build_object('number',57,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n너는 얼마나 오래 서울에 살아왔니?\n[조건] live를 사용 / How long으로 시작할 것 / 7단어로 쓸 것',
  'answer',E'How long have you lived in Seoul?',
  'acceptedAnswers',jsonb_build_array(E'How long have you lived in Seoul'),
  'explanation',E'현재완료 계속 용법 의문문: How long have you + p.p.? 7단어'),
jsonb_build_object('number',58,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n우리는 아직 그 문제를 풀지 못했다.\n[조건] solve를 사용 / yet을 반드시 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'We haven''t solved the problem yet.',
  'acceptedAnswers',jsonb_build_array(E'We haven''t solved the problem yet',E'We have not solved the problem yet.',E'We have not solved the problem yet'),
  'explanation',E'현재완료 완료 용법 부정: haven''t + p.p. + yet. solve → solved'),
jsonb_build_object('number',59,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n예술의 역사에서, 예술가들은 서로에게 영향을 끼쳐왔다.\n[조건] influence와 each other를 반드시 사용 / In the history of art로 시작할 것 / 완전한 문장으로 쓸 것',
  'answer',E'In the history of art, artists have influenced each other.',
  'acceptedAnswers',jsonb_build_array(E'In the history of art, artists have influenced each other',E'In the history of art artists have influenced each other.',E'In the history of art artists have influenced each other'),
  'explanation',E'현재완료: have influenced. influence → influenced(규칙 변화)'),
jsonb_build_object('number',60,
  'question',E'주어진 조건에 맞게 우리말을 영작하시오.\n\n나는 내 용돈을 모아서 6년 동안 그를 도왔다.\n[조건] help와 save를 반드시 사용 / for를 쓸 것 / 완전한 문장으로 쓸 것',
  'answer',E'I have helped him for six years by saving my allowance.',
  'acceptedAnswers',jsonb_build_array(E'I have helped him for six years by saving my allowance',E'I have helped him for 6 years by saving my allowance.',E'I have helped him for 6 years by saving my allowance'),
  'explanation',E'현재완료 계속 용법: have helped + for six years. by saving = ~을 모아서')
  );

  a := jsonb_build_array(E'has caught', E'have lived', E'Has / ridden', 'Has', 'ridden', E'haven''t eaten', E'has won', E'have / known', 'have', 'known', E'has broken', E'has worked', E'Has / finished', 'Has', 'finished', E'has rained', E'I have lost my wallet.', E'She has learned French for three years.', E'He has gone to Australia.', E'I have known Jina since 2018.', E'My brother has played the guitar for two years.', E'She has lived in Seoul since she was ten.', E'Tom has broken his arm.', E'I have had this bike for five years.', E'Amy has gone to New York.', E'We have studied together since 2020.', E'She has taken piano lessons for four years.', E'I have read this novel three times since last summer.', E'I have', E'has gone', E'have been', E'I haven''t', E'have / studied', 'have', 'studied', E'have seen', E'has gone', E'Have / tried', 'Have', 'tried', E'She has finished her homework already.', E'I saw her at the café yesterday.', E'He has gone to Canada. He''s not here.', E'They have been married for two years.', E'Have you ever ridden a horse before?', E'We have known each other since middle school.', E'I haven''t seen Minji for three months.', E'When did you visit that museum?', E'My brother hasn''t written to me since he moved abroad.', E'I have been to Japan twice. It was amazing.', E'have lost', E'has studied / for', 'has studied', 'for', E'has lived / since', 'has lived', 'since', E'has gone', E'have played / since', 'have played', 'since', E'has had / for', 'has had', 'for', E'has led / for', 'has led', 'for', E'have known / since', 'have known', 'since', E'I have never been to Canada.', E'Has she ever eaten Korean food?', E'He has taught at this school since 2019.', E'We have known each other since 2014.', E'I have used this bike for three years.', E'Tom has read the most books in his class.', E'I have known her since she was a child.', E'Amy has loved Yuna Kim since she was an elementary school student.', E'How long have you lived in Seoul?', E'We haven''t solved the problem yet.', E'In the history of art, artists have influenced each other.', E'I have helped him for six years by saving my allowance.');

  INSERT INTO naesin_templates (title, template_topic, category, mode, questions, answer_key)
  VALUES ('현재완료 Step 3', '현재완료', 'problem', 'interactive', q, a);
END;
$$;
