DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  -- 기존 템플릿 삭제 (중복 방지)
  DELETE FROM naesin_problem_sheets
  WHERE title = '관계대명사 what Step1' AND is_template = true;

  q := jsonb_build_array(
    -- 유형 1: what절의 역할 구분 (1-20)
    jsonb_build_object('number',1,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What she said made everyone laugh.','answer','주어'),
    jsonb_build_object('number',2,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] I can''t forget what she said to me.','answer','목적어'),
    jsonb_build_object('number',3,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What happened last night is still a mystery.','answer','주어'),
    jsonb_build_object('number',4,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] That is exactly what I meant.','answer','보어'),
    jsonb_build_object('number',5,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] Do you remember what we talked about?','answer','목적어'),
    jsonb_build_object('number',6,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What my father taught me has helped me a lot.','answer','주어'),
    jsonb_build_object('number',7,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] This is not what I ordered.','answer','보어'),
    jsonb_build_object('number',8,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] She is interested in what he is doing.','answer','목적어'),
    jsonb_build_object('number',9,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What you believe shapes your future.','answer','주어'),
    jsonb_build_object('number',10,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] He didn''t understand what the problem was.','answer','목적어'),
    jsonb_build_object('number',11,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What we need right now is teamwork.','answer','주어'),
    jsonb_build_object('number',12,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] Please listen carefully to what I am saying.','answer','목적어'),
    jsonb_build_object('number',13,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] The result was what we had expected.','answer','보어'),
    jsonb_build_object('number',14,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] Nobody knows what will happen tomorrow.','answer','목적어'),
    jsonb_build_object('number',15,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What matters most is not money but love.','answer','주어'),
    jsonb_build_object('number',16,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] I was surprised at what I found in the box.','answer','목적어'),
    jsonb_build_object('number',17,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] Home is what makes you feel safe.','answer','보어'),
    jsonb_build_object('number',18,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] What the boy found in the park was a lost puppy.','answer','주어'),
    jsonb_build_object('number',19,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] They couldn''t decide what to do next.','answer','목적어'),
    jsonb_build_object('number',20,'question',E'[what절의 역할을 고르시오: 주어 / 목적어 / 보어] The real problem is what nobody wants to talk about.','answer','보어'),
    -- 유형 2: 알맞은 것 고르기 (21-40)
    jsonb_build_object('number',21,'question',E'[알맞은 것을 고르시오] He showed me (what / which) he had made for the science project.','answer','what'),
    jsonb_build_object('number',22,'question',E'[알맞은 것을 고르시오] The dress (what / that) she wore to the party was beautiful.','answer','that'),
    jsonb_build_object('number',23,'question',E'[알맞은 것을 고르시오] I don''t understand (what / which) you are talking about.','answer','what'),
    jsonb_build_object('number',24,'question',E'[알맞은 것을 고르시오] The movie (what / which) we watched last weekend was boring.','answer','which'),
    jsonb_build_object('number',25,'question',E'[알맞은 것을 고르시오] (What / That) surprised me was her beautiful voice.','answer','What'),
    jsonb_build_object('number',26,'question',E'[알맞은 것을 고르시오] This is the place (what / that) I''ve always wanted to visit.','answer','that'),
    jsonb_build_object('number',27,'question',E'[알맞은 것을 고르시오] She told me (what / which) she wanted for Christmas.','answer','what'),
    jsonb_build_object('number',28,'question',E'[알맞은 것을 고르시오] The story (what / which) he told us was very funny.','answer','which'),
    jsonb_build_object('number',29,'question',E'[알맞은 것을 고르시오] (What / Which) you see is not always true.','answer','What'),
    jsonb_build_object('number',30,'question',E'[알맞은 것을 고르시오] He lost everything (what / that) he had.','answer','that'),
    jsonb_build_object('number',31,'question',E'[알맞은 것을 고르시오] I will give you (what / which) you need.','answer','what'),
    jsonb_build_object('number',32,'question',E'[알맞은 것을 고르시오] The homework (what / that) the teacher gave us was too difficult.','answer','that'),
    jsonb_build_object('number',33,'question',E'[알맞은 것을 고르시오] Music is (what / which) makes my life better.','answer','what'),
    jsonb_build_object('number',34,'question',E'[알맞은 것을 고르시오] The car (what / which) my dad bought is very fast.','answer','which'),
    jsonb_build_object('number',35,'question',E'[알맞은 것을 고르시오] Do you know (what / that) she is afraid of?','answer','what'),
    jsonb_build_object('number',36,'question',E'[알맞은 것을 고르시오] She didn''t eat anything (what / that) I cooked.','answer','that'),
    jsonb_build_object('number',37,'question',E'[알맞은 것을 고르시오] (What / That) I want to say is very simple.','answer','What'),
    jsonb_build_object('number',38,'question',E'[알맞은 것을 고르시오] The present (what / that) he gave me was a book.','answer','that'),
    jsonb_build_object('number',39,'question',E'[알맞은 것을 고르시오] Reading books is (what / which) I enjoy doing on weekends.','answer','what'),
    jsonb_build_object('number',40,'question',E'[알맞은 것을 고르시오] Is there something (what / that) you want to tell me?','answer','that'),
    -- 유형 3: 괄호 안 단어 배열 (41-55)
    jsonb_build_object('number',41,'question',E'[괄호 안의 단어를 바르게 배열하시오] She gave me (she, what, bought).','answer','what she bought'),
    jsonb_build_object('number',42,'question',E'[괄호 안의 단어를 바르게 배열하시오] I can''t believe (said, he, what).','answer','what he said'),
    jsonb_build_object('number',43,'question',E'[괄호 안의 단어를 바르게 배열하시오] Tell me (what, you, want, really).','answer','what you really want'),
    jsonb_build_object('number',44,'question',E'[괄호 안의 단어를 바르게 배열하시오] (what, surprised, me) was his kind words.','answer','What surprised me'),
    jsonb_build_object('number',45,'question',E'[괄호 안의 단어를 바르게 배열하시오] I will show you (what, found, I, in the park).','answer','what I found in the park'),
    jsonb_build_object('number',46,'question',E'[괄호 안의 단어를 바르게 배열하시오] He didn''t know (what, was, happening).','answer','what was happening'),
    jsonb_build_object('number',47,'question',E'[괄호 안의 단어를 바르게 배열하시오] This is (what, made, for you, I).','answer','what I made for you'),
    jsonb_build_object('number',48,'question',E'[괄호 안의 단어를 바르게 배열하시오] (what, need, we) is more practice.','answer','What we need'),
    jsonb_build_object('number',49,'question',E'[괄호 안의 단어를 바르게 배열하시오] She always remembers (what, told, her, I).','answer','what I told her'),
    jsonb_build_object('number',50,'question',E'[괄호 안의 단어를 바르게 배열하시오] I don''t understand (what, means, this).','answer','what this means'),
    jsonb_build_object('number',51,'question',E'[괄호 안의 단어를 바르게 배열하시오] (me, happy, what, makes) is spending time with family.','answer','What makes me happy'),
    jsonb_build_object('number',52,'question',E'[괄호 안의 단어를 바르게 배열하시오] He will do (what, thinks, he, is right).','answer','what he thinks is right'),
    jsonb_build_object('number',53,'question',E'[괄호 안의 단어를 바르게 배열하시오] Please write down (what, learned, today, you).','answer','what you learned today'),
    jsonb_build_object('number',54,'question',E'[괄호 안의 단어를 바르게 배열하시오] (what, most, matters) is your effort.','answer','What matters most'),
    jsonb_build_object('number',55,'question',E'[괄호 안의 단어를 바르게 배열하시오] I can see (what, drawing, you, are).','answer','what you are drawing'),
    -- 유형 4: 한→영 전체 배열 (56-70)
    jsonb_build_object('number',56,'question',E'[배열하시오] 그가 말한 것은 사실이었다. (said, was, what, true, he)','answer','What he said was true.'),
    jsonb_build_object('number',57,'question',E'[배열하시오] 나는 그녀가 요리한 것을 먹었다. (what, ate, she, I, cooked)','answer','I ate what she cooked.'),
    jsonb_build_object('number',58,'question',E'[배열하시오] 그녀가 가장 좋아하는 것은 음악이다. (most, is, likes, what, music, she)','answer','What she likes most is music.'),
    jsonb_build_object('number',59,'question',E'[배열하시오] 이것이 내가 너에게 말하고 싶은 것이다. (is, what, to, this, tell, want, I, you)','answer','This is what I want to tell you.'),
    jsonb_build_object('number',60,'question',E'[배열하시오] 너는 어제 무슨 일이 있었는지 아니? (do, what, yesterday, you, happened, know, ?)','answer','Do you know what happened yesterday?'),
    jsonb_build_object('number',61,'question',E'[배열하시오] 나를 행복하게 하는 것은 가족이다. (happy, is, makes, what, family, me)','answer','What makes me happy is family.'),
    jsonb_build_object('number',62,'question',E'[배열하시오] 그는 내가 말한 것을 이해하지 못했다. (understand, what, didn''t, said, he, I)','answer','He didn''t understand what I said.'),
    jsonb_build_object('number',63,'question',E'[배열하시오] 중요한 것은 너의 노력이다. (is, effort, what, your, matters)','answer','What matters is your effort.'),
    jsonb_build_object('number',64,'question',E'[배열하시오] 나에게 네가 본 것을 보여줘. (me, what, show, saw, you)','answer','Show me what you saw.'),
    jsonb_build_object('number',65,'question',E'[배열하시오] 그녀는 그가 원하는 것을 알고 있다. (knows, he, she, what, wants)','answer','She knows what he wants.'),
    jsonb_build_object('number',66,'question',E'[배열하시오] 그것은 내가 기대한 것이 아니었다. (not, expected, was, what, that, I)','answer','That was not what I expected.'),
    jsonb_build_object('number',67,'question',E'[배열하시오] 내가 어젯밤에 꿈꾼 것은 이상했다. (dreamed, last night, what, strange, was, I)','answer','What I dreamed last night was strange.'),
    jsonb_build_object('number',68,'question',E'[배열하시오] 선생님은 우리에게 해야 할 것을 말씀하셨다. (us, the teacher, what, told, do, to)','answer','The teacher told us what to do.'),
    jsonb_build_object('number',69,'question',E'[배열하시오] 내가 가장 두려워하는 것은 실패이다. (most, is, fear, what, failure, I)','answer','What I fear most is failure.'),
    jsonb_build_object('number',70,'question',E'[배열하시오] 너는 그녀가 말한 것을 기억하니? (remember, said, you, she, what, do, ?)','answer','Do you remember what she said?'),
    -- 유형 5: 관계대명사 / 의문사 구분 (71-80)
    jsonb_build_object('number',71,'question',E'[관계대명사인지 의문사인지 구분하시오] What she said was true.','answer','관계대명사'),
    jsonb_build_object('number',72,'question',E'[관계대명사인지 의문사인지 구분하시오] She asked me what my name was.','answer','의문사'),
    jsonb_build_object('number',73,'question',E'[관계대명사인지 의문사인지 구분하시오] I will do what I can for you.','answer','관계대명사'),
    jsonb_build_object('number',74,'question',E'[관계대명사인지 의문사인지 구분하시오] This is not what I expected.','answer','관계대명사'),
    jsonb_build_object('number',75,'question',E'[관계대명사인지 의문사인지 구분하시오] What did you eat for lunch?','answer','의문사'),
    jsonb_build_object('number',76,'question',E'[관계대명사인지 의문사인지 구분하시오] What is your favorite subject?','answer','의문사'),
    jsonb_build_object('number',77,'question',E'[관계대명사인지 의문사인지 구분하시오] What surprised me was his kindness.','answer','관계대명사'),
    jsonb_build_object('number',78,'question',E'[관계대명사인지 의문사인지 구분하시오] I wonder what time the train arrives.','answer','의문사'),
    jsonb_build_object('number',79,'question',E'[관계대명사인지 의문사인지 구분하시오] He gave me what I needed.','answer','관계대명사'),
    jsonb_build_object('number',80,'question',E'[관계대명사인지 의문사인지 구분하시오] Can you tell me what day it is today?','answer','의문사'),
    -- 유형 6: 영작 (81-100)
    jsonb_build_object('number',81,'question',E'[영작하시오] 이것이 네가 원했던 것이니? (this, want)','answer','Is this what you wanted?'),
    jsonb_build_object('number',82,'question',E'[영작하시오] 내가 필요한 것은 마실 것이다. (need, something, drink)','answer','What I need is something to drink.'),
    jsonb_build_object('number',83,'question',E'[영작하시오] 나는 그가 말한 것을 이해할 수 없었다. (understand, say)','answer','I couldn''t understand what he said.'),
    jsonb_build_object('number',84,'question',E'[영작하시오] 그들은 우리가 가져온 것을 보고 놀랐다. (surprise, see, bring)','answer','They were surprised at what we brought.'),
    jsonb_build_object('number',85,'question',E'[영작하시오] 이것은 우리가 주문했던 것이 아니다. (this, order)','answer','This is not what we ordered.'),
    jsonb_build_object('number',86,'question',E'[영작하시오] 그녀가 만든 것은 정말 아름다웠다. (make, really, beautiful)','answer','What she made was really beautiful.'),
    jsonb_build_object('number',87,'question',E'[영작하시오] 나에게 네가 배운 것을 말해줘. (tell, learn)','answer','Tell me what you learned.'),
    jsonb_build_object('number',88,'question',E'[영작하시오] 가장 중요한 것은 네 건강이다. (matter, most, health)','answer','What matters most is your health.'),
    jsonb_build_object('number',89,'question',E'[영작하시오] 나는 그가 왜 화났는지 모른다. (know, angry)','answer','I don''t know what made him angry.'),
    jsonb_build_object('number',90,'question',E'[영작하시오] 이것이 내가 너에게 주고 싶은 것이다. (this, give, want)','answer','This is what I want to give you.'),
    jsonb_build_object('number',91,'question',E'[영작하시오] 그녀는 내가 한 것에 대해 감사했다. (thankful, do)','answer','She was thankful for what I did.'),
    jsonb_build_object('number',92,'question',E'[영작하시오] 내가 기억하는 것은 그의 미소이다. (remember, smile)','answer','What I remember is his smile.'),
    jsonb_build_object('number',93,'question',E'[영작하시오] 너는 선생님이 말씀하신 것을 들었니? (hear, teacher, say)','answer','Did you hear what the teacher said?'),
    jsonb_build_object('number',94,'question',E'[영작하시오] 나를 놀라게 한 것은 그의 정직함이었다. (surprise, honesty)','answer','What surprised me was his honesty.'),
    jsonb_build_object('number',95,'question',E'[영작하시오] 이것은 내가 항상 꿈꿔왔던 것이다. (this, always, dream)','answer','This is what I have always dreamed of.'),
    jsonb_build_object('number',96,'question',E'[영작하시오] 그는 자기가 원하는 것을 알고 있다. (know, want)','answer','He knows what he wants.'),
    jsonb_build_object('number',97,'question',E'[영작하시오] 내가 가장 좋아하는 것은 독서이다. (like, most, reading)','answer','What I like most is reading.'),
    jsonb_build_object('number',98,'question',E'[영작하시오] 너는 그녀가 숨긴 것을 찾았니? (find, hide)','answer','Did you find what she hid?'),
    jsonb_build_object('number',99,'question',E'[영작하시오] 우리가 본 것은 믿을 수 없었다. (see, unbelievable)','answer','What we saw was unbelievable.'),
    jsonb_build_object('number',100,'question',E'[영작하시오] 그것이 내가 말하려던 것이다. (that, try, say)','answer','That is what I was trying to say.')
  );

  a := jsonb_build_array(
    '주어','목적어','주어','보어','목적어',
    '주어','보어','목적어','주어','목적어',
    '주어','목적어','보어','목적어','주어',
    '목적어','보어','주어','목적어','보어',
    'what','that','what','which','What',
    'that','what','which','What','that',
    'what','that','what','which','what',
    'that','What','that','what','that',
    'what she bought',
    'what he said',
    'what you really want',
    'What surprised me',
    'what I found in the park',
    'what was happening',
    'what I made for you',
    'What we need',
    'what I told her',
    'what this means',
    'What makes me happy',
    'what he thinks is right',
    'what you learned today',
    'What matters most',
    'what you are drawing',
    'What he said was true.',
    'I ate what she cooked.',
    'What she likes most is music.',
    'This is what I want to tell you.',
    'Do you know what happened yesterday?',
    'What makes me happy is family.',
    'He didn''t understand what I said.',
    'What matters is your effort.',
    'Show me what you saw.',
    'She knows what he wants.',
    'That was not what I expected.',
    'What I dreamed last night was strange.',
    'The teacher told us what to do.',
    'What I fear most is failure.',
    'Do you remember what she said?',
    '관계대명사','의문사','관계대명사','관계대명사','의문사',
    '의문사','관계대명사','의문사','관계대명사','의문사',
    'Is this what you wanted?',
    'What I need is something to drink.',
    'I couldn''t understand what he said.',
    'They were surprised at what we brought.',
    'This is not what we ordered.',
    'What she made was really beautiful.',
    'Tell me what you learned.',
    'What matters most is your health.',
    'I don''t know what made him angry.',
    'This is what I want to give you.',
    'She was thankful for what I did.',
    'What I remember is his smile.',
    'Did you hear what the teacher said?',
    'What surprised me was his honesty.',
    'This is what I have always dreamed of.',
    'He knows what he wants.',
    'What I like most is reading.',
    'Did you find what she hid?',
    'What we saw was unbelievable.',
    'That is what I was trying to say.'
  );

  INSERT INTO naesin_problem_sheets (
    unit_id, title, mode, questions, answer_key,
    category, is_template, template_topic, sort_order
  ) VALUES (
    (SELECT id FROM naesin_units LIMIT 1),
    '관계대명사 what Step1', 'interactive', q, a,
    'problem', true, '관계대명사', 0
  );
END $$;
