-- 간접의문문 Step 2 — 객관식 90문항
-- template_topic: 간접의문문
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '간접의문문 Step 2';

  q := jsonb_build_array(
jsonb_build_object('number',1,
  'question',E'[Part 1] 다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nCan you tell me __________ the next train leaves?',
  'options',jsonb_build_array('that','when','because','so','then'),
  'answer','2',
  'explanation',E'간접의문문에서 시간을 묻는 의문사 when이 적절'),
jsonb_build_object('number',2,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nDo you know __________?',
  'options',jsonb_build_array('where she works','how old her brother is','when does the store close','if he passed the exam','what her favorite food is'),
  'answer','3',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → when does the store close는 직접의문문 어순'),
jsonb_build_object('number',3,
  'question',E'다음 빈칸에 들어갈 수 있는 말을 모두 고르면?\n\nI''m not sure __________ she will attend the meeting.\nⓐ if  ⓑ that  ⓒ because  ⓓ whether  ⓔ when',
  'options',jsonb_build_array('ⓐ, ⓑ','ⓐ, ⓒ','ⓑ, ⓓ','ⓐ, ⓓ','ⓓ, ⓔ'),
  'answer','4',
  'explanation',E'yes/no 의문문의 간접의문문에는 if 또는 whether를 사용'),
jsonb_build_object('number',4,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nHow do you __________ she became so successful?',
  'options',jsonb_build_array('think','suppose','know','believe','imagine'),
  'answer','3',
  'explanation',E'의문사가 문두에 나오려면 think류 동사(think, suppose, believe, imagine)가 필요하다. know는 해당되지 않는다.'),
jsonb_build_object('number',5,
  'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nI wonder __________ he missed the bus this morning.',
  'options',jsonb_build_array('where','what','why','who','when'),
  'answer','3',
  'explanation',E'버스를 놓친 이유를 궁금해하므로 why가 적절'),
jsonb_build_object('number',6,
  'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nPlease tell me __________ I can find the nearest pharmacy.',
  'options',jsonb_build_array('where','that','so','which','then'),
  'answer','1',
  'explanation',E'장소를 묻는 간접의문문이므로 where가 적절'),
jsonb_build_object('number',7,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nCan you tell me __________?',
  'options',jsonb_build_array('how long it takes to get there','what kind of music she likes','where the bus stop is','why does he always come late','if the restaurant is open on Sundays'),
  'answer','4',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → why does he는 직접의문문 어순'),
jsonb_build_object('number',8,
  'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nDo you know __________?',
  'options',jsonb_build_array('what time the concert starts','where is the nearest hospital','how much should I pay','when does the library open','who is that woman'),
  'answer','1',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → what time the concert starts만 올바른 어순'),
jsonb_build_object('number',9,
  'question',E'다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: I need to submit my assignment but I don''t know __________.\nB: The deadline is this Friday at noon.',
  'options',jsonb_build_array('when is the deadline','when the deadline is','what is the deadline','that the deadline is','when did the deadline pass'),
  'answer','2',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → when the deadline is'),
jsonb_build_object('number',10,
  'question',E'다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: I''m curious about __________.\nB: It''s the Eiffel Tower in Paris.',
  'options',jsonb_build_array('where this famous tower is','what''s the tower name','who built this','when was it painted','how tall does it stand'),
  'answer','1',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → where this famous tower is만 올바른 어순'),
jsonb_build_object('number',11,
  'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것은?\n\nI wonder __________ last weekend.',
  'options',jsonb_build_array('where Kevin goes','where Kevin went','where will Kevin go','where did Kevin go','where does Kevin go'),
  'answer','2',
  'explanation',E'last weekend(과거)이므로 과거시제 + 간접의문문 어순 → where Kevin went'),
jsonb_build_object('number',12,
  'question',E'다음 빈칸에 들어갈 수 있는 말을 모두 고르면?\n\nDo you know __________?\nⓐ who is the new science teacher\nⓑ how many people live in this city\nⓒ when does he finish work\nⓓ where she studied abroad\nⓔ what is the girl''s hobby',
  'options',jsonb_build_array('ⓐ, ⓒ','ⓑ, ⓓ','ⓒ, ⓔ','ⓐ, ⓑ','ⓓ, ⓔ'),
  'answer','2',
  'explanation',E'간접의문문 어순(의문사+주어+동사)에 맞는 것은 ⓑ와 ⓓ'),
jsonb_build_object('number',13,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nDo you know __________?',
  'options',jsonb_build_array('how many hours she sleeps a day','why did he change his mind','who her favorite teacher is','what she does after school','if he likes playing sports'),
  'answer','2',
  'explanation',E'간접의문문은 의문사+주어+동사 어순 → why did he는 직접의문문 어순'),
jsonb_build_object('number',14,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nI don''t remember __________.',
  'options',jsonb_build_array('sending an email to her last night','what she was wearing at the event','how I got to the hotel','the man wearing a blue jacket','where did I put my passport'),
  'answer','5',
  'explanation',E'간접의문문 어순 → where did I는 직접의문문 어순'),
jsonb_build_object('number',15,
  'question',E'다음 빈칸에 들어갈 말로 적절하지 않은 것을 모두 고르면?\n\nCould you tell me __________?\nⓐ what the problem is\nⓑ who owns this building\nⓒ if the story is true\nⓓ what does she look like\nⓔ how long have you been here',
  'options',jsonb_build_array('ⓐ, ⓓ','ⓑ, ⓔ','ⓒ, ⓓ','ⓓ, ⓔ','ⓐ, ⓔ'),
  'answer','4',
  'explanation',E'ⓓ와 ⓔ는 직접의문문 어순 → 간접의문문에 부적절'),
jsonb_build_object('number',16,
  'question',E'[Part 2] 다음 우리말을 바르게 영작한 것은?\n\n저녁 식사가 언제 준비될지 모르겠어요.',
  'options',jsonb_build_array('I''m not sure when will dinner be ready.','I''m not sure if dinner will be ready.','I''m not sure where dinner will be ready.','I''m not sure if will dinner be ready.','I''m not sure when dinner will be ready.'),
  'answer','5',
  'explanation',E'간접의문문 어순(의문사+주어+동사): when dinner will be ready'),
jsonb_build_object('number',17,
  'question',E'다음 우리말을 바르게 영작한 것은?\n\n우리가 몇 시에 출발할 예정인지 궁금해.',
  'options',jsonb_build_array('I wonder what time are we going to leave.','I wonder we are going to leave what time.','I wonder what time we are going to leave.','I wonder what we are going to leave time.','I wonder are we going to leave what time.'),
  'answer','3',
  'explanation',E'간접의문문 어순: what time we are going to leave'),
jsonb_build_object('number',18,
  'question',E'다음 우리말을 바르게 영작한 것은?\n\n너는 누가 그 사진을 찍었는지 아니?',
  'options',jsonb_build_array('Do you know who take the picture?','Do you know who took the picture?','Who took the picture do you know?','Do you know who was taking the picture?','Who do you know took the picture?'),
  'answer','2',
  'explanation',E'who가 주어인 간접의문문 → 어순 변화 없음, 과거시제 took'),
jsonb_build_object('number',19,
  'question',E'다음 우리말을 바르게 영작한 것은?\n\n너는 그녀의 남동생이 몇 살인지 아니?',
  'options',jsonb_build_array('How old do you know her brother is?','How old do you know is her brother?','Do you know how old her brother is?','Do you know how old is her brother?','Do you know is her brother how old?'),
  'answer','3',
  'explanation',E'know는 think류가 아니므로 의문사가 절 안에 남음: how old her brother is'),
jsonb_build_object('number',20,
  'question',E'다음 우리말을 바르게 영작한 것은?\n\n이 근처에 지하철역이 있는지 모르겠어.',
  'options',jsonb_build_array('I don''t know if is there a subway station nearby.','I don''t know if there is a subway station nearby.','I don''t know there a is subway station nearby.','I don''t know is there a subway station nearby.','I don''t know how there is a subway station nearby.'),
  'answer','2',
  'explanation',E'yes/no 의문문의 간접의문문: if + 주어 + 동사 어순'),
jsonb_build_object('number',21,
  'question',E'다음 우리말을 영작할 때 4번째로 오는 단어는?\n\n그녀가 왜 그 경기를 포기했다고 생각하니?\n→ Why do you think she gave up the game?',
  'options',jsonb_build_array('why','think','she','do','gave'),
  'answer','3',
  'explanation',E'think류 동사 → 의문사(Why)가 문두로 이동하여 Why do you think she gave up the game?'),
jsonb_build_object('number',22,
  'question',E'다음 우리말과 일치하도록 괄호 안의 단어들을 바르게 배열할 때, 세 번째로 오는 단어는?\n\n그들이 그 프로젝트를 좋아하는지 너는 알고 있니?\n→ Do you (know / if / like / they / the) project?',
  'options',jsonb_build_array('know','if','like','they','the'),
  'answer','4',
  'explanation',E'Do you know if they like the project? → 괄호 안 배열: know(1) if(2) they(3) like(4) the(5) → 세 번째 they'),
jsonb_build_object('number',23,
  'question',E'다음 밑줄 친 우리말을 바르게 영작한 것은?\n\nWe may have different opinions about <u>무엇이 진정한 행복을 만드는지</u>.',
  'options',jsonb_build_array('what are happy things','a happy life makes what','what make true happiness','what makes true happiness','what true happiness makes'),
  'answer','4',
  'explanation',E'what이 주어 → 어순 변화 없이 what makes true happiness (3인칭 단수 -s)'),
jsonb_build_object('number',24,
  'question',E'다음 빈칸에 들어갈 수 있는 질문 중 어법상 어색한 것은?\n\nQ: __________?\nA: You can reduce waste by using reusable bags when you go shopping.',
  'options',jsonb_build_array('Do you know how can we reduce waste?','Do you know how we can reduce waste?','Do you know the way we can reduce waste?','Do you know the way that we can reduce waste?','Do you know the way in which we can reduce waste?'),
  'answer','1',
  'explanation',E'간접의문문 어순 → how can we는 직접의문문 어순, how we can이 올바름'),
jsonb_build_object('number',25,
  'question',E'다음 문장에서 어법상 오류를 찾아 고친 것으로 옳은 것은?\n\nDo you think why these changes are happening so fast?',
  'options',jsonb_build_array('Do you think why these changes are happening so fast?','Do you think why are happening these changes so fast?','Do you think why are these changes happening so fast?','Why do you think these changes are happening so fast?','Why do you think are these changes happening so fast?'),
  'answer','4',
  'explanation',E'think류 동사 → 의문사(Why)가 문두로 이동'),
jsonb_build_object('number',26,
  'question',E'[Part 3] 다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· I''d like to know.\n· When did she arrive at the airport?',
  'options',jsonb_build_array('I''d like to know when she arrives at the airport.','I''d like to know when she arrived at the airport.','I''d like to know when arrived she at the airport.','I''d like to know when she has arrived at the airport.','I''d like to know when did she arrive at the airport.'),
  'answer','2',
  'explanation',E'did arrive → arrived로 변환하고 간접의문문 어순 적용'),
jsonb_build_object('number',27,
  'question',E'다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· Can you tell me?\n· What did he order for dinner?',
  'options',jsonb_build_array('What can you tell me he ordered?','What can you tell me he orders?','Can you tell me what he orders?','Can you tell me what he ordered?','Can you tell me what did he order?'),
  'answer','4',
  'explanation',E'did order → ordered로 변환하고 간접의문문 어순 적용'),
jsonb_build_object('number',28,
  'question',E'다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· Can you tell me?\n· Did she enjoy the trip?',
  'options',jsonb_build_array('Can you tell me she enjoyed the trip?','Can you tell me did she enjoy the trip?','Can you tell me if did she enjoy the trip?','Can you tell me if she enjoyed the trip?','Can you tell me if she enjoys the trip?'),
  'answer','4',
  'explanation',E'yes/no 의문문 → if를 사용, did enjoy → enjoyed로 변환'),
jsonb_build_object('number',29,
  'question',E'다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· Do you think?\n· What should we do to solve this problem?',
  'options',jsonb_build_array('Do you think what we should do to solve this problem?','Do you think what should we do to solve this problem?','What do you think we should do to solve this problem?','What do you think should we do to solve this problem?','What do you think did we do to solve this problem?'),
  'answer','3',
  'explanation',E'think류 동사 → 의문사(What)가 문두로 이동'),
jsonb_build_object('number',30,
  'question',E'다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· Do you think?\n· Why did she leave the company?',
  'options',jsonb_build_array('Do you think why she left the company?','Do you think why did she leave the company?','Why do you think she left the company?','Why do you think why she leave the company?','Why do you think why did she leave the company?'),
  'answer','3',
  'explanation',E'think류 동사 → 의문사(Why)가 문두로 이동, did leave → left'),
jsonb_build_object('number',31,
  'question',E'다음 두 문장을 한 문장으로 만들 때 가장 적절한 것은?\n\n· I wonder.\n· Is the new café open on weekends?',
  'options',jsonb_build_array('I wonder if the new café is open on weekends.','I wonder whether is the new café open on weekends.','I wonder if is the new café open on weekends.','I wonder that the new café is open on weekends.','I wonder the new café is open on weekends.'),
  'answer','1',
  'explanation',E'yes/no 의문문 → if를 사용하고 주어+동사 어순'),
jsonb_build_object('number',32,
  'question',E'다음 중 두 문장을 한 문장으로 바르게 바꾼 것은?',
  'options',jsonb_build_array('I want to know. + How did she win? → I want to know how she wins.','Can you tell me? + When did he leave? → Can you tell me when he left?','Do you know? + Which subject does she like? → Which subject do you know she likes?','Ask him. + What made him change his mind? → What asks him change his mind?','I''d like to know. + What song is she singing? → I''d like to know what is she singing to song.'),
  'answer','2',
  'explanation',E'did leave → left로 변환하고 간접의문문 어순 적용. ①은 시제 불일치, ③은 know는 think류 아님, ④⑤ 구조 오류'),
jsonb_build_object('number',33,
  'question',E'다음 직접의문문을 간접의문문으로 바꿀 때, 어법상 어색한 것은?',
  'options',jsonb_build_array('Where will he stay? → Let me know where he''ll stay.','What did she buy? → Tell me what she bought.','How long does it take? → Can I ask you how long it takes?','Who is she? → I asked them who she was.','Who spilled the juice? → I wonder did who spill the juice.'),
  'answer','5',
  'explanation',E'who가 주어일 때 어순 변화 없음 → I wonder who spilled the juice가 올바름'),
jsonb_build_object('number',34,
  'question',E'다음 두 문장을 한 문장으로 연결할 때 어색한 것은?',
  'options',jsonb_build_array('What is she reading? + Do you know? → Do you know what she is reading?','Where is the bus stop? + Do you know? → Do you know where the bus stop is?','Where can I charge my phone? + Tell me. → Tell me where can I charge my phone.','Who is he? + Do you know? → Do you know who he is?','How tall is she? + I want to know. → I want to know how tall she is.'),
  'answer','3',
  'explanation',E'간접의문문 어순 → Tell me where I can charge my phone이 올바름'),
jsonb_build_object('number',35,
  'question',E'다음 문장을 간접의문문으로 바꿀 때 빈칸에 들어갈 말로 가장 적절한 것은?\n\nHe said to me, "Did you enjoy the party?"\n→ He asked me __________.',
  'options',jsonb_build_array('if I had enjoyed the party','if you enjoyed the party','if I enjoyed the party','whether I enjoy the party','whether you enjoyed the party'),
  'answer','3',
  'explanation',E'직접 인용 → 간접 인용: you→I 전환, 시제는 과거 유지'),
jsonb_build_object('number',36,
  'question',E'[Part 4] 다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: I have to return this book to Ms. Park, but I don''t know __________.\nB: She''s in the staff room on the second floor.',
  'options',jsonb_build_array('where is she','where she is','where she went','where she did go','where did she go'),
  'answer','2',
  'explanation',E'간접의문문 어순(의문사+주어+동사): where she is'),
jsonb_build_object('number',37,
  'question',E'다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: What are you searching for online?\nB: I''m trying to find out __________.\nA: Oh, it''s on the 3rd floor of the city hall building.',
  'options',jsonb_build_array('where the immigration office is','what''s the immigration office','who runs the immigration office','what the immigration office does','when the immigration office opens it'),
  'answer','1',
  'explanation',E'장소를 묻는 간접의문문 + 대답이 위치 정보'),
jsonb_build_object('number',38,
  'question',E'다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nA: A package arrived for you. It had your name but no sender''s info.\nB: Really? I don''t know what''s in it. And I also don''t know __________.',
  'options',jsonb_build_array('who sent the package','who did send the package','who the package is','who the package sent','who you sent the package'),
  'answer','1',
  'explanation',E'who가 주어인 간접의문문 → 어순 변화 없이 who sent the package'),
jsonb_build_object('number',39,
  'question',E'다음 인터뷰 질문 중 어법상 적절하지 않은 것은?\n\nInterview with a young chef',
  'options',jsonb_build_array('Could you briefly introduce yourself?','Can you tell us what your specialty dish is?','Please let us know what inspired you to become a chef.','Can you tell us your advice for beginner cooks?','What do you want to cook most if you open your own restaurant?'),
  'answer','4',
  'explanation',E'tell+간접의문문 또는 tell+목적어+to부정사 구조 필요. "tell us your advice"는 give us your advice가 적절'),
jsonb_build_object('number',40,
  'question',E'다음 빈칸 (A), (B), (C)에 들어갈 알맞은 말로 바르게 짝지어진 것은?\n\n· I have no idea how (A)[they found / did they find] the treasure.\n· I want to know who (B)[wrote the letter / did the letter write] yesterday.\n· Do you know where (C)[she is / is she] from?',
  'options',jsonb_build_array('they found — wrote the letter — she is','they found — wrote the letter — is she','did they find — did the letter write — she is','did they find — did the letter write — is she','did they find — wrote the letter — is she'),
  'answer','1',
  'explanation',E'간접의문문은 모두 주어+동사 어순'),
jsonb_build_object('number',41,
  'question',E'[Part 5] 다음 밑줄 친 부분 중 어법상 어색한 것은?',
  'options',jsonb_build_array('I know who you really are.','Can you tell me how she solved it?','I don''t know what did she say.','He wants to know where she lives.','Do you know when he came back?'),
  'answer','3',
  'explanation',E'간접의문문 어순 → what did she say를 what she said로'),
jsonb_build_object('number',42,
  'question',E'다음 밑줄 친 부분 중 어법상 옳은 것은?',
  'options',jsonb_build_array('Tell me if did anyone call you.','Do you know how Gyeongbokgung old is?','I don''t know who broke the window.','Please explain what does that sign mean.','Can you tell me what are you looking for?'),
  'answer','3',
  'explanation',E'who가 주어인 간접의문문 → 어순 변화 없이 올바름'),
jsonb_build_object('number',43,
  'question',E'다음 밑줄 친 부분 중 어법상 어색한 것은?',
  'options',jsonb_build_array('I don''t know who ate the last piece of cake.','He asked me how much the jacket was.','Do you know what did she have for lunch?','Can you tell me where the restroom is?','Can you tell me what kind of sport he likes?'),
  'answer','3',
  'explanation',E'간접의문문 어순 → what did she have를 what she had로'),
jsonb_build_object('number',44,
  'question',E'다음 밑줄 친 부분 중 어법상 어색한 것은?',
  'options',jsonb_build_array('Please tell me where he lives.','I want to know where are you going.','I want to know who your favorite actor is.','He asked me when the flight would depart.','To find out what the problem is, we need more data.'),
  'answer','2',
  'explanation',E'간접의문문 어순 → where are you going을 where you are going으로'),
jsonb_build_object('number',45,
  'question',E'다음 중 어법상 옳은 문장은?',
  'options',jsonb_build_array('I don''t know how old is he?','Do you know where is she from?','I don''t know why did she become a nurse.','Do you have any idea how long did it take?','I was wondering why we didn''t take the bus; it would have been faster.'),
  'answer','5',
  'explanation',E'①②③④는 모두 간접의문문 어순 오류. ⑤만 올바른 어순')
,
    jsonb_build_object('number',46,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Do you know what time it is?',E'I don''t understand why they are upset.',E'No one knows where he went.',E'I don''t know what she bought.',E'I don''t care who are you.'),
      'answer','5',
      'explanation',E'간접의문문 어순 → who are you를 who you are로'),
    jsonb_build_object('number',47,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'I wondered what his job.',E'The woman wants to know how help the child.',E'The teacher wonders who the best student is.',E'The boy is curious about where is the dog.',E'She wonders when will she meet her idol.'),
      'answer','3',
      'explanation',E'③만 간접의문문 어순(의문사+주어+동사) 정확'),
    jsonb_build_object('number',48,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Can you tell me if he will come tomorrow?',E'I don''t know why she is so quiet today.',E'Do you think where we should meet?',E'We wanted to know what he did yesterday.',E'Do you know how we get to the museum?'),
      'answer','3',
      'explanation',E'think류 동사 → 의문사가 문두로: Where do you think we should meet?'),
    jsonb_build_object('number',49,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Do you know how far the hotel is from here?',E'Can you tell me where is the man?',E'Do you think where Jane met Mr. Kim?',E'Can you tell me when will the shop open?',E'Would you tell me whether she lives in Busan?'),
      'answer','5',
      'explanation',E'⑤만 간접의문문 어순(whether+주어+동사) 올바름'),
    jsonb_build_object('number',50,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Can you tell me where the department store is?',E'Do you know what the countryside is like?',E'Do you know how much is it?',E'No one knows when he left for school.',E'I don''t care who she is.'),
      'answer','3',
      'explanation',E'간접의문문 어순 → how much is it를 how much it is로'),
    jsonb_build_object('number',51,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Can you tell me where is the bank?',E'Let me know how long I should wait.',E'I need to know what did you do last night.',E'I asked her how does she get to school.',E'Please tell me what time does the store open?'),
      'answer','2',
      'explanation',E'②만 간접의문문 어순 정확'),
    jsonb_build_object('number',52,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Can you tell me when your graduation is?',E'I don''t understand why they are nervous.',E'I don''t care where you are from.',E'She asked me how I was tall.',E'I don''t know who he is.'),
      'answer','4',
      'explanation',E'how I was tall → how tall I was (의문사+형용사가 한 덩어리)'),
    jsonb_build_object('number',53,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Which do you think is more useful?',E'I wonder how much will it cost.',E'Where do you know Tom has gone?',E'Can you tell me what time begins the show?',E'I don''t understand why did she leave so suddenly.'),
      'answer','1',
      'explanation',E'think류 동사 → 의문사(Which)가 문두로, Which가 주어 역할'),
    jsonb_build_object('number',54,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I wonder if he will go hiking this weekend.',E'Do you know where she is right now?',E'I don''t know how long I should stay here.',E'I am not sure what is the answer.',E'She asked me when Chris would be back.'),
      'answer','4',
      'explanation',E'간접의문문 어순 → what is the answer를 what the answer is로'),
    jsonb_build_object('number',55,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'I''m not sure where is Anne.',E'Do you think when he will return?',E'Will you tell me what "vibe" mean?',E'Jack asked me when our school festival was.',E'Could you tell me how can I get to the library?'),
      'answer','4',
      'explanation',E'④만 간접의문문 어순 정확. ②는 think류→의문사 문두, ③ mean→means, ⑤ 어순 오류'),
    jsonb_build_object('number',56,
      'question',E'[Part 6] 다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'She asked me why I didn''t show up.',E'He didn''t know where his glasses were.',E'Please tell me why animals migrate.',E'I''m not sure when we last spoke.',E'I wonder how could she finish so quickly.'),
      'answer','5',
      'explanation',E'간접의문문 어순 → how could she를 how she could로'),
    jsonb_build_object('number',57,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Do you know who your neighbors'' are best friends?',E'Where do you think penguins find food?',E'We didn''t know who designed this building.',E'Do you remember how much this bag was?',E'Do you know how many hours your parents rest every day?'),
      'answer','1',
      'explanation',E'어순 오류 → who your neighbors'' best friends are가 올바름'),
    jsonb_build_object('number',58,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I don''t know where Lisa is going to work.',E'I wonder how gets he so much pocket money.',E'Tell me what makes a good leader.',E'I should have brought a jacket.',E'We shouldn''t have skipped breakfast.'),
      'answer','2',
      'explanation',E'간접의문문 어순 → how gets he를 how he gets로'),
    jsonb_build_object('number',59,
      'question',E'다음 중 어법상 어색한 문장을 모두 고르면?\nⓐ Where do you think does she keep her diary?\nⓑ Why do you suppose she can''t make it today?\nⓒ When do you know the office closes?\nⓓ I don''t know where this path leads to.\nⓔ Why do you think he wants to travel alone?',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓐ, ⓒ',E'ⓑ, ⓒ',E'ⓒ, ⓓ',E'ⓐ, ⓔ'),
      'answer','2',
      'explanation',E'ⓐ think류인데 does 불필요(does she keep → she keeps), ⓒ know는 think류 아님(의문사 문두 불가)'),
    jsonb_build_object('number',60,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'Do you think what the answer is?',E'He has no idea how it is far from here.',E'She asked me if Linda have a dictionary.',E'Can you tell me how the prices are high?',E'Do you know when they are going to announce it?'),
      'answer','5',
      'explanation',E'⑤만 간접의문문 어순 정확'),
    jsonb_build_object('number',61,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I want to know where the city hall is.',E'I asked him what time it was.',E'Let me know about the girl who I saw yesterday.',E'We need to understand why this rule is necessary.',E'She doesn''t wonder when he will come.'),
      'answer','3',
      'explanation',E'who I saw → whom I saw 또는 관계대명사 목적격 오류'),
    jsonb_build_object('number',62,
      'question',E'다음 밑줄 친 부분 중 어법상 옳은 것은?',
      'options',jsonb_build_array(E'No one knows who made it.',E'I asked him what is his name?',E'I wonder if he will comes.',E'I don''t know how old is he.',E'Do you know if he has dog?'),
      'answer','1',
      'explanation',E'who가 주어인 간접의문문 → 어순 변화 없이 올바름'),
    jsonb_build_object('number',63,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'I''m not sure if is the answer correct.',E'Do you think where the hospital is?',E'She wonders if his schedule is okay.',E'I''d like to know whether can she drive.',E'Do you think who will win the match?'),
      'answer','3',
      'explanation',E'③만 if+주어+동사 어순 정확'),
    jsonb_build_object('number',64,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Do you know what color is it?',E'Can you tell me why he is so quiet?',E'I don''t know what you ordered yesterday.',E'I wonder if she will join our study group.',E'I want to know where my homeroom teacher lives.'),
      'answer','1',
      'explanation',E'간접의문문 어순 → what color is it를 what color it is로'),
    jsonb_build_object('number',65,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'She asks me that the rumor is true or not.',E'Do you know where the event will hold?',E'I want to know if he will join our club.',E'Everyone wonders that she likes spicy food.',E'I haven''t decided yet what should I wear.'),
      'answer','3',
      'explanation',E'③만 if+주어+동사 어순 정확'),
    jsonb_build_object('number',66,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I wonder if he will go on the trip.',E'Do you know where she is?',E'I don''t know how long I should stay here.',E'I am not sure what is the schedule.',E'She asked me when the results would be out.'),
      'answer','4',
      'explanation',E'간접의문문 어순 → what is the schedule를 what the schedule is로'),
    jsonb_build_object('number',67,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'She asked me why I didn''t come to practice.',E'He didn''t know where his keys were.',E'Please tell me why people recycle.',E'I''m not sure when we met for the first time.',E'I wonder how could she solve it so fast.'),
      'answer','5',
      'explanation',E'간접의문문 어순 → how could she를 how she could로'),
    jsonb_build_object('number',68,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'Do you know who your classmates'' are favorite singers?',E'Where do you think eagles hunt for food?',E'We didn''t know who painted this mural.',E'Do you remember how much this watch was?',E'Do you know how many books your friend reads a month?'),
      'answer','1',
      'explanation',E'어순 오류 → who your classmates'' favorite singers are가 올바름'),
    jsonb_build_object('number',69,
      'question',E'다음 중 어법상 옳은 문장은?',
      'options',jsonb_build_array(E'I''m not sure where is the manager.',E'Do you think when she will call back?',E'Will you tell me what "K-drama" mean?',E'He asked me when our school trip would be.',E'Could you tell me how can I fix this error?'),
      'answer','4',
      'explanation',E'④만 간접의문문 어순 정확'),
    jsonb_build_object('number',70,
      'question',E'다음 중 어법상 어색한 문장은?',
      'options',jsonb_build_array(E'I wonder if he will go camping this summer.',E'Do you know where she is hiding?',E'I don''t know how long I should wait in line.',E'I am not sure what is the right direction.',E'She asked me when the package would arrive.'),
      'answer','4',
      'explanation',E'간접의문문 어순 → what is the right direction를 what the right direction is로'),
    jsonb_build_object('number',71,
      'question',E'[Part 7] 다음 중 어법상 어색한 문장을 모두 고르면?\nⓐ Who do you think he spent the weekend with?\nⓑ Do you think what we should do to help them?\nⓒ I don''t know when she can meet me.\nⓓ Do you believe who broke my tablet?\nⓔ I wonder if she can finish her project by tomorrow.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓒ, ⓔ',E'ⓐ, ⓓ',E'ⓑ, ⓔ'),
      'answer','2',
      'explanation',E'ⓑ think류→의문사 문두 필요, ⓓ believe는 think류→의문사 문두 필요'),
    jsonb_build_object('number',72,
      'question',E'다음 중 어법상 옳은 문장을 모두 고르면?\nⓐ Tell me where were you last night.\nⓑ Do you know who did draw this portrait?\nⓒ Let me know how much the entrance fee is.\nⓓ I wonder why is she always so stressed.\nⓔ She asked me when the performance started.',
      'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓔ',E'ⓒ, ⓔ',E'ⓐ, ⓓ',E'ⓑ, ⓒ'),
      'answer','3',
      'explanation',E'ⓒ와 ⓔ만 간접의문문 어순 정확'),
    jsonb_build_object('number',73,
      'question',E'다음 중 어법상 어색한 문장을 모두 고르면?\nⓐ I want to know why she doesn''t reply to me.\nⓑ Do you have any idea how much it will cost?\nⓒ Do you know who designed these shoes?\nⓓ Do you think when she will come back?\nⓔ Could you tell me when did he arrive home?',
      'options',jsonb_build_array(E'ⓐ, ⓓ',E'ⓑ, ⓔ',E'ⓒ, ⓓ',E'ⓓ, ⓔ',E'ⓐ, ⓔ'),
      'answer','4',
      'explanation',E'ⓓ think류→의문사 문두 필요, ⓔ 간접의문문 어순 오류'),
    jsonb_build_object('number',74,
      'question',E'다음 중 어법상 옳은 문장을 모두 고르면?\nⓐ Do you know how that boy is old?\nⓑ Can you believe what did you hear?\nⓒ Let''s see which route is faster.\nⓓ Do you know when did Jimin return home?\nⓔ I want to know which color she likes better.',
      'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓔ',E'ⓒ, ⓔ',E'ⓐ, ⓓ',E'ⓑ, ⓒ'),
      'answer','3',
      'explanation',E'ⓒ와 ⓔ만 어법 정확'),
    jsonb_build_object('number',75,
      'question',E'다음 중 어법상 어색한 문장을 모두 고르면?\nⓐ Do you know what happens to the main character?\nⓑ I don''t know if she can use the equipment.\nⓒ Do you think what is his nickname?\nⓓ I''m not sure whether he is coming today.\nⓔ Do you know where does she come from?',
      'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓔ',E'ⓒ, ⓔ',E'ⓐ, ⓓ',E'ⓑ, ⓒ'),
      'answer','3',
      'explanation',E'ⓒ think류→의문사 문두 필요, ⓔ 간접의문문 어순 오류'),
    jsonb_build_object('number',76,
      'question',E'다음 중 어법상 옳은 문장을 모두 고르면?\nⓐ I want to know who broke the vase.\nⓑ Do you think who will be her new partner?\nⓒ I''m wondering whether is he at school now.\nⓓ What do you believe happened to him yesterday?\nⓔ I''m curious about what did she do last summer.',
      'options',jsonb_build_array(E'ⓐ, ⓓ',E'ⓑ, ⓔ',E'ⓒ, ⓔ',E'ⓐ, ⓒ',E'ⓑ, ⓓ'),
      'answer','1',
      'explanation',E'ⓐ who가 주어→어순 변화 없음, ⓓ believe는 think류→의문사 문두'),
    jsonb_build_object('number',77,
      'question',E'다음 중 어법상 어색한 문장의 총 개수는?\n\nⓐ I wonder whether Mia loves traveling.\nⓑ Do you remember what time was it?\nⓒ How far do you suppose he can run?\nⓓ Jessica doesn''t know if there is a café nearby.\nⓔ Please tell me what should I do next.\nⓕ I wonder if I might borrow your pen.',
      'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
      'answer','2',
      'explanation',E'ⓑ what time was it→what time it was, ⓔ what should I→what I should → 2개'),
    jsonb_build_object('number',78,
      'question',E'다음 중 어법상 어색한 문장의 총 개수는?\n\nⓐ Do you know where she traveled last summer?\nⓑ Let me know how much is one cup of coffee.\nⓒ Do you think who will win the award?\nⓓ Do you know how whales survive so long?\nⓔ Do you remember when did you meet her first?\nⓕ He''s exciting to tell her what really happened.',
      'options',jsonb_build_array(E'one',E'two',E'three',E'four',E'five'),
      'answer','5',
      'explanation',E'ⓑ 어순 오류, ⓒ think류→의문사 문두, ⓓ how long으로 묶어야 함, ⓔ 어순 오류, ⓕ exciting→excited → 5개(ⓐ만 올바름)'),
    jsonb_build_object('number',79,
      'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\n(A) Do you believe where did you lose it?\n(B) What do you think is she doing now?\n(C) I don''t know who broke the window.\n(D) Tell me who your teammates'' are best friends.\n(E) Do you know what your parents do for a living?\n(F) I wonder if Kate was dating Mike yesterday.\n(G) Do you know how many hours did your parents sleep?',
      'options',jsonb_build_array(E'0개',E'2개',E'3개',E'4개',E'5개'),
      'answer','2',
      'explanation',E'(C)와 (E)만 올바른 어순. 나머지는 모두 어법 오류'),
    jsonb_build_object('number',80,
      'question',E'다음 중 어법상 어색한 문장끼리 바르게 짝지어진 것은?\n\n(a) I don''t know that she will come to the party or not.\n(b) Can you tell me when your exam is?\n(c) She asks me when we will meet.\n(d) Do you know who did drew this picture?\n(e) I don''t know who is telling the truth.\n(f) Do you think why she cried?',
      'options',jsonb_build_array(E'(a), (d), (f)',E'(a), (c), (e)',E'(b), (d), (e)',E'(c), (e), (f)',E'(b), (e), (f)'),
      'answer','1',
      'explanation',E'(a) that→whether/if (or not 필요), (d) did drew→drew, (f) think류→의문사 문두'),
    jsonb_build_object('number',81,
      'question',E'[Part 8] 다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Do you know who is she?\nⓑ Can you tell me what brought you here?\nⓒ Do you know who ate the most pizza?\nⓓ She didn''t even tell me what her score was.\nⓔ Do you know if Andy can play the violin?',
      'options',jsonb_build_array(E'ⓐ, ⓒ, ⓓ',E'ⓑ, ⓒ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓔ',E'ⓐ, ⓓ, ⓔ'),
      'answer','3',
      'explanation',E'ⓑ(what이 주어), ⓓ(간접의문문 어순), ⓔ(if+주어+동사)가 올바름'),
    jsonb_build_object('number',82,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ Please tell me how is Tom doing.\nⓑ Do you think what he should do?\nⓒ Does he know where his sister lives?\nⓓ Can you tell me who the trophy belongs to?\nⓔ I wonder if you will come to my farewell party.',
      'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓑ, ⓓ',E'ⓒ, ⓔ',E'ⓑ, ⓒ, ⓔ',E'ⓒ, ⓓ, ⓔ'),
      'answer','3',
      'explanation',E'ⓒ(간접의문문 어순 정확), ⓔ(if+주어+동사 어순 정확)가 올바름'),
    jsonb_build_object('number',83,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ I can''t remember what did Sora do then.\nⓑ I want to know whether I can use your charger.\nⓒ I wonder how long you will be staying here.\nⓓ Do you know what time the game start?\nⓔ Do you think who can solve the puzzle?',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓒ',E'ⓑ, ⓒ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓔ'),
      'answer','2',
      'explanation',E'ⓑ(whether+주어+동사), ⓒ(의문사+주어+동사)가 올바름'),
    jsonb_build_object('number',84,
      'question',E'다음 중 어법상 어색한 문장끼리 바르게 짝지어진 것은?\n\n(A) Do you think why she is so nervous?\n(B) Can you tell me where did you go?\n(C) I don''t know how I should handle this.\n(D) What do you know the price of this jacket is?\n(E) I don''t know how did the fire start.\n(F) I wonder why you decided to move abroad.',
      'options',jsonb_build_array(E'(A), (C), (F)',E'(B), (D), (E)',E'(A), (B), (D), (E)',E'(C), (D), (E), (F)',E'(B), (C), (D), (F)'),
      'answer','3',
      'explanation',E'(A) think류→의문사 문두, (B) 어순 오류, (D) know는 think류 아님, (E) 어순 오류'),
    jsonb_build_object('number',85,
      'question',E'다음 중 어법상 옳은 문장을 모두 고르면?\n\nⓐ I want to know where you study.\nⓑ Do you know what song she want to sing?\nⓒ What kind of career do I want to have?\nⓓ Do you think I should exercise more?\nⓔ Do you think what I can do for you?\nⓕ What do you think you want to eat?\nⓖ The man wants to know how much is it.',
      'options',jsonb_build_array(E'ⓐ, ⓓ, ⓕ',E'ⓑ, ⓔ, ⓖ',E'ⓒ, ⓓ, ⓕ',E'ⓐ, ⓒ, ⓓ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓕ'),
      'answer','1',
      'explanation',E'ⓐ(간접의문문 어순), ⓓ(if절 생략형 간접의문문), ⓕ(think류→의문사 문두)'),
    jsonb_build_object('number',86,
      'question',E'다음 중 어법상 어색한 문장을 모두 고르면?\n\nⓐ Can you guess why they do this?\nⓑ Do you suppose what made her come here?\nⓒ I don''t really know when is the class over.\nⓓ He asked me how often she helped him.\nⓔ Let''s ask her who the man in the photo is.\nⓕ I''m not sure when he arrived at the station.\nⓖ I didn''t know how I dealt with it.\nⓗ Do you think why he''s so surprised?',
      'options',jsonb_build_array(E'ⓐ, ⓓ, ⓖ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓗ',E'ⓒ, ⓓ, ⓔ, ⓖ',E'ⓑ, ⓔ, ⓖ, ⓗ',E'ⓐ, ⓒ, ⓔ, ⓕ'),
      'answer','2',
      'explanation',E'ⓑ suppose는 think류→의문사 문두, ⓒ 어순 오류, ⓓ 시제 불일치, ⓗ think류→의문사 문두'),
    jsonb_build_object('number',87,
      'question',E'다음 중 어법상 어색한 문장을 모두 고르면?\n\nⓐ How can you believe she painted this herself?\nⓑ Why do you think he will arrive on time?\nⓒ I don''t know when she can help me with this.\nⓓ Do you imagine what the sky looks like from there?\nⓔ Can you tell me where he went yesterday?\nⓕ Why do you think she would rather stay home?\nⓖ Do you suppose what time she will get there?\nⓗ Where do you know the bus station is?',
      'options',jsonb_build_array(E'ⓐ, ⓓ, ⓖ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓗ',E'ⓐ, ⓒ, ⓔ, ⓗ',E'ⓓ, ⓔ, ⓖ, ⓗ',E'ⓑ, ⓒ, ⓔ, ⓕ'),
      'answer','4',
      'explanation',E'ⓓ imagine은 think류→의문사 문두 필요, ⓖ suppose는 think류→의문사 문두 필요, ⓗ know는 think류 아님→의문사가 절 안에 남아야 함'),
    jsonb_build_object('number',88,
      'question',E'다음 괄호 (A), (B), (C) 안에서 어법에 맞는 표현으로 가장 적절한 것은?\n\n· I have no idea how (A)[they solved / did they solve] it.\n· I want to know who (B)[got the award / did the award get] yesterday.\n· Do you know where (C)[he is / is he] from?',
      'options',jsonb_build_array(E'they solved — got the award — he is',E'they solved — got the award — is he',E'did they solve — did the award get — he is',E'did they solve — did the award get — is he',E'did they solve — got the award — is he'),
      'answer','1',
      'explanation',E'간접의문문은 모두 주어+동사 어순'),
    jsonb_build_object('number',89,
      'question',E'다음 중 어법상 옳은 문장끼리 바르게 짝지어진 것은?\n\nⓐ I want to know where he is going.\nⓑ Do you think what she should say?\nⓒ Does she know where her friend lives?\nⓓ Can you tell me who the package is from?\nⓔ I wonder if you will come to my concert.',
      'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓑ, ⓓ',E'ⓒ, ⓔ',E'ⓑ, ⓒ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓔ'),
      'answer','5',
      'explanation',E'ⓐⓒⓓⓔ 모두 간접의문문 어순 정확. ⓑ만 think류→의문사 문두 필요'),
    jsonb_build_object('number',90,
      'question',E'다음 중 어법상 어색한 문장끼리 바르게 짝지어진 것은?\n\nⓐ Can you guess why they act this way?\nⓑ Do you suppose what made him stay?\nⓒ I don''t really know when is the show over.\nⓓ He asked me how often she called him.\nⓔ Let''s ask her who the woman in the photo is.\nⓕ I''m not sure when she arrived at school.\nⓖ I didn''t know how I handled it.\nⓗ Do you think why he looks so tired?',
      'options',jsonb_build_array(E'ⓐ, ⓓ, ⓖ, ⓕ',E'ⓑ, ⓒ, ⓗ',E'ⓒ, ⓓ, ⓔ, ⓖ',E'ⓑ, ⓔ, ⓖ, ⓗ',E'ⓐ, ⓒ, ⓔ, ⓕ'),
      'answer','2',
      'explanation',E'ⓑ suppose는 think류→의문사 문두, ⓒ 어순 오류, ⓗ think류→의문사 문두')
  );

  a := jsonb_build_array(
    jsonb_build_object('number',1,'answer','2'),
    jsonb_build_object('number',2,'answer','3'),
    jsonb_build_object('number',3,'answer','4'),
    jsonb_build_object('number',4,'answer','3'),
    jsonb_build_object('number',5,'answer','3'),
    jsonb_build_object('number',6,'answer','1'),
    jsonb_build_object('number',7,'answer','4'),
    jsonb_build_object('number',8,'answer','1'),
    jsonb_build_object('number',9,'answer','2'),
    jsonb_build_object('number',10,'answer','1'),
    jsonb_build_object('number',11,'answer','2'),
    jsonb_build_object('number',12,'answer','2'),
    jsonb_build_object('number',13,'answer','2'),
    jsonb_build_object('number',14,'answer','5'),
    jsonb_build_object('number',15,'answer','4'),
    jsonb_build_object('number',16,'answer','5'),
    jsonb_build_object('number',17,'answer','3'),
    jsonb_build_object('number',18,'answer','2'),
    jsonb_build_object('number',19,'answer','3'),
    jsonb_build_object('number',20,'answer','2'),
    jsonb_build_object('number',21,'answer','3'),
    jsonb_build_object('number',22,'answer','4'),
    jsonb_build_object('number',23,'answer','4'),
    jsonb_build_object('number',24,'answer','1'),
    jsonb_build_object('number',25,'answer','4'),
    jsonb_build_object('number',26,'answer','2'),
    jsonb_build_object('number',27,'answer','4'),
    jsonb_build_object('number',28,'answer','4'),
    jsonb_build_object('number',29,'answer','3'),
    jsonb_build_object('number',30,'answer','3'),
    jsonb_build_object('number',31,'answer','1'),
    jsonb_build_object('number',32,'answer','2'),
    jsonb_build_object('number',33,'answer','5'),
    jsonb_build_object('number',34,'answer','3'),
    jsonb_build_object('number',35,'answer','3'),
    jsonb_build_object('number',36,'answer','2'),
    jsonb_build_object('number',37,'answer','1'),
    jsonb_build_object('number',38,'answer','1'),
    jsonb_build_object('number',39,'answer','4'),
    jsonb_build_object('number',40,'answer','1'),
    jsonb_build_object('number',41,'answer','3'),
    jsonb_build_object('number',42,'answer','3'),
    jsonb_build_object('number',43,'answer','3'),
    jsonb_build_object('number',44,'answer','2'),
    jsonb_build_object('number',45,'answer','5'),
    jsonb_build_object('number',46,'answer','5'),
    jsonb_build_object('number',47,'answer','3'),
    jsonb_build_object('number',48,'answer','3'),
    jsonb_build_object('number',49,'answer','5'),
    jsonb_build_object('number',50,'answer','3'),
    jsonb_build_object('number',51,'answer','2'),
    jsonb_build_object('number',52,'answer','4'),
    jsonb_build_object('number',53,'answer','1'),
    jsonb_build_object('number',54,'answer','4'),
    jsonb_build_object('number',55,'answer','4'),
    jsonb_build_object('number',56,'answer','5'),
    jsonb_build_object('number',57,'answer','1'),
    jsonb_build_object('number',58,'answer','2'),
    jsonb_build_object('number',59,'answer','2'),
    jsonb_build_object('number',60,'answer','5'),
    jsonb_build_object('number',61,'answer','3'),
    jsonb_build_object('number',62,'answer','1'),
    jsonb_build_object('number',63,'answer','3'),
    jsonb_build_object('number',64,'answer','1'),
    jsonb_build_object('number',65,'answer','3'),
    jsonb_build_object('number',66,'answer','4'),
    jsonb_build_object('number',67,'answer','5'),
    jsonb_build_object('number',68,'answer','1'),
    jsonb_build_object('number',69,'answer','4'),
    jsonb_build_object('number',70,'answer','4'),
    jsonb_build_object('number',71,'answer','2'),
    jsonb_build_object('number',72,'answer','3'),
    jsonb_build_object('number',73,'answer','4'),
    jsonb_build_object('number',74,'answer','3'),
    jsonb_build_object('number',75,'answer','3'),
    jsonb_build_object('number',76,'answer','1'),
    jsonb_build_object('number',77,'answer','2'),
    jsonb_build_object('number',78,'answer','5'),
    jsonb_build_object('number',79,'answer','2'),
    jsonb_build_object('number',80,'answer','1'),
    jsonb_build_object('number',81,'answer','3'),
    jsonb_build_object('number',82,'answer','3'),
    jsonb_build_object('number',83,'answer','2'),
    jsonb_build_object('number',84,'answer','3'),
    jsonb_build_object('number',85,'answer','1'),
    jsonb_build_object('number',86,'answer','2'),
    jsonb_build_object('number',87,'answer','4'),
    jsonb_build_object('number',88,'answer','1'),
    jsonb_build_object('number',89,'answer','5'),
    jsonb_build_object('number',90,'answer','2')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('간접의문문 Step 2', '간접의문문', q, a, 'problem', 'interactive');
END $$;
