DO $$
DECLARE
  v_questions jsonb;
  v_answer_key jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '지각동사 Step1';

  v_questions := jsonb_build_array(
    jsonb_build_object('number', 1, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI saw the boy (sells / selling / sell) lemonade on the corner.', 'answer', E'selling', 'acceptedAnswers', jsonb_build_array(E'selling', E'sell')),
    jsonb_build_object('number', 2, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nWe felt the ground (shakes / shake / to shake) beneath our feet.', 'answer', E'shake', 'acceptedAnswers', jsonb_build_array(E'shake')),
    jsonb_build_object('number', 3, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nCan you hear the birds (to sing / singing) in the trees?', 'answer', E'singing', 'acceptedAnswers', jsonb_build_array(E'singing')),
    jsonb_build_object('number', 4, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nJisu saw a woman (to paint / painting) a picture in the park.', 'answer', E'painting', 'acceptedAnswers', jsonb_build_array(E'painting')),
    jsonb_build_object('number', 5, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI feel something (crawling / to crawl) up my back.', 'answer', E'crawling', 'acceptedAnswers', jsonb_build_array(E'crawling')),
    jsonb_build_object('number', 6, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nMinho heard his name (called / calling / call) from across the street.', 'answer', E'calling', 'acceptedAnswers', jsonb_build_array(E'calling', E'call')),
    jsonb_build_object('number', 7, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI heard the audience (clap / to clap) after the performance.', 'answer', E'clap', 'acceptedAnswers', jsonb_build_array(E'clap')),
    jsonb_build_object('number', 8, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nTom watched his sister (cross / crosses) the finish line.', 'answer', E'cross', 'acceptedAnswers', jsonb_build_array(E'cross')),
    jsonb_build_object('number', 9, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI noticed my neighbor (standing / to stand) at the gate.', 'answer', E'standing', 'acceptedAnswers', jsonb_build_array(E'standing')),
    jsonb_build_object('number', 10, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nThe crowd watched hundreds of balloons (floating / to float) into the sky.', 'answer', E'floating', 'acceptedAnswers', jsonb_build_array(E'floating')),
    jsonb_build_object('number', 11, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nA reporter watched workers (to live / living) in temporary shelters.', 'answer', E'living', 'acceptedAnswers', jsonb_build_array(E'living')),
    jsonb_build_object('number', 12, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nWalking at night is risky because you can''t hear cars (came / coming).', 'answer', E'coming', 'acceptedAnswers', jsonb_build_array(E'coming')),
    jsonb_build_object('number', 13, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nWhen you see a magician (flying / to fly) on stage, he isn''t actually flying.', 'answer', E'flying', 'acceptedAnswers', jsonb_build_array(E'flying')),
    jsonb_build_object('number', 14, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nSora hears her parents (to argue / arguing) downstairs late at night.', 'answer', E'arguing', 'acceptedAnswers', jsonb_build_array(E'arguing')),
    jsonb_build_object('number', 15, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nJimin saw the magician (to disappear / disappearing) behind the curtain.', 'answer', E'disappearing', 'acceptedAnswers', jsonb_build_array(E'disappearing')),
    jsonb_build_object('number', 16, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nCan you see the goalkeeper (to catch / catching) the ball with one hand?', 'answer', E'catching', 'acceptedAnswers', jsonb_build_array(E'catching')),
    jsonb_build_object('number', 17, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nShe heard her cat (to meow / meowing) outside the door all night.', 'answer', E'meowing', 'acceptedAnswers', jsonb_build_array(E'meowing')),
    jsonb_build_object('number', 18, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nMake the audience want to see them (to perform / perform) again.', 'answer', E'perform', 'acceptedAnswers', jsonb_build_array(E'perform')),
    jsonb_build_object('number', 19, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nYou can see many volunteers (will help / help / to help) at the event.', 'answer', E'help', 'acceptedAnswers', jsonb_build_array(E'help', E'helping')),
    jsonb_build_object('number', 20, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nIf you stay positive, you would feel your confidence (to grow / growing) stronger.', 'answer', E'growing', 'acceptedAnswers', jsonb_build_array(E'growing')),
    jsonb_build_object('number', 21, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nI can feel my heart. It''s beating fast.', 'answer', E'I can feel my heart beating fast.', 'acceptedAnswers', jsonb_build_array(E'I can feel my heart beating fast.', E'I can feel my heart beating fast')),
    jsonb_build_object('number', 22, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nWe heard them. They were laughing all night.', 'answer', E'We heard them laughing all night.', 'acceptedAnswers', jsonb_build_array(E'We heard them laughing all night.', E'We heard them laughing all night')),
    jsonb_build_object('number', 23, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nDid you notice me? I was waving at you.', 'answer', E'Did you notice me waving at you?', 'acceptedAnswers', jsonb_build_array(E'Did you notice me waving at you?', E'Did you notice me waving at you')),
    jsonb_build_object('number', 24, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nSomething''s cooking. I can smell it.', 'answer', E'I can smell something cooking.', 'acceptedAnswers', jsonb_build_array(E'I can smell something cooking.', E'I can smell something cooking')),
    jsonb_build_object('number', 25, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nThe fireworks exploded. Did you see them?', 'answer', E'Did you see the fireworks explode?', 'acceptedAnswers', jsonb_build_array(E'Did you see the fireworks explode?', E'Did you see the fireworks explode')),
    jsonb_build_object('number', 26, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nI saw you the other day. You were jogging in the park.', 'answer', E'I saw you jogging in the park the other day.', 'acceptedAnswers', jsonb_build_array(E'I saw you jogging in the park the other day.', E'I saw you jogging in the park the other day')),
    jsonb_build_object('number', 27, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nMany people cheered loudly. I heard this.', 'answer', E'I heard many people cheering loudly.', 'acceptedAnswers', jsonb_build_array(E'I heard many people cheering loudly.', E'I heard many people cheering loudly', E'I heard many people cheer loudly.', E'I heard many people cheer loudly')),
    jsonb_build_object('number', 28, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nShe was singing on the balcony. I heard her.', 'answer', E'I heard her singing on the balcony.', 'acceptedAnswers', jsonb_build_array(E'I heard her singing on the balcony.', E'I heard her singing on the balcony')),
    jsonb_build_object('number', 29, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nShe was running across the field. I noticed her.', 'answer', E'I noticed her running across the field.', 'acceptedAnswers', jsonb_build_array(E'I noticed her running across the field.', E'I noticed her running across the field')),
    jsonb_build_object('number', 30, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nI heard him early this morning. He was leaving the building.', 'answer', E'I heard him leaving the building early this morning.', 'acceptedAnswers', jsonb_build_array(E'I heard him leaving the building early this morning.', E'I heard him leaving the building early this morning')),
    jsonb_build_object('number', 31, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nThey performed a dance. I listened to them.', 'answer', E'I listened to them performing a dance.', 'acceptedAnswers', jsonb_build_array(E'I listened to them performing a dance.', E'I listened to them performing a dance', E'I listened to them perform a dance.', E'I listened to them perform a dance')),
    jsonb_build_object('number', 32, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nShe stood there and watched him. He drove away.', 'answer', E'She stood there and watched him drive away.', 'acceptedAnswers', jsonb_build_array(E'She stood there and watched him drive away.', E'She stood there and watched him drive away')),
    jsonb_build_object('number', 33, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nWe saw the cat. And it was climbing up the fence.', 'answer', E'We saw the cat climbing up the fence.', 'acceptedAnswers', jsonb_build_array(E'We saw the cat climbing up the fence.', E'We saw the cat climbing up the fence')),
    jsonb_build_object('number', 34, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nHave you ever heard her? She tells amazing stories.', 'answer', E'Have you ever heard her tell amazing stories?', 'acceptedAnswers', jsonb_build_array(E'Have you ever heard her tell amazing stories?', E'Have you ever heard her tell amazing stories')),
    jsonb_build_object('number', 35, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 만드시오.\n\n<보기> She plays the guitar every evening. He watches her.\n→ He watches her play the guitar every evening.\n\nI''ve often seen you. You were skateboarding near the school.', 'answer', E'I''ve often seen you skateboarding near the school.', 'acceptedAnswers', jsonb_build_array(E'I''ve often seen you skateboarding near the school.', E'I''ve often seen you skateboarding near the school', E'I have often seen you skateboarding near the school.', E'I have often seen you skateboarding near the school')),
    jsonb_build_object('number', 36, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nCan you smell something ___ in the kitchen?', 'answer', E'burning', 'acceptedAnswers', jsonb_build_array(E'burning')),
    jsonb_build_object('number', 37, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI could hear two people ___ with each other in the next room.', 'answer', E'arguing', 'acceptedAnswers', jsonb_build_array(E'arguing')),
    jsonb_build_object('number', 38, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI''m sure I saw you ___ his hand at the farewell party.', 'answer', E'holding', 'acceptedAnswers', jsonb_build_array(E'holding', E'hold')),
    jsonb_build_object('number', 39, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nCan you hear the choir ___? It''s beautiful.', 'answer', E'singing', 'acceptedAnswers', jsonb_build_array(E'singing')),
    jsonb_build_object('number', 40, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI could feel something ___ my shoulder, but I couldn''t see anything.', 'answer', E'touching', 'acceptedAnswers', jsonb_build_array(E'touching')),
    jsonb_build_object('number', 41, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI couldn''t see anything ___ in the dark room.', 'answer', E'moving', 'acceptedAnswers', jsonb_build_array(E'moving')),
    jsonb_build_object('number', 42, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI''m sure I heard him ___ to someone on the phone.', 'answer', E'talking', 'acceptedAnswers', jsonb_build_array(E'talking', E'talk')),
    jsonb_build_object('number', 43, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI watched Tom ___ a scooter around the neighborhood.', 'answer', E'riding', 'acceptedAnswers', jsonb_build_array(E'riding', E'ride')),
    jsonb_build_object('number', 44, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI heard the phone ___ but I was too busy to answer.', 'answer', E'ringing', 'acceptedAnswers', jsonb_build_array(E'ringing', E'ring')),
    jsonb_build_object('number', 45, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI heard someone ___ for help from outside.', 'answer', E'screaming', 'acceptedAnswers', jsonb_build_array(E'screaming', E'scream')),
    jsonb_build_object('number', 46, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI was so frightened. I could feel myself ___ with fear.', 'answer', E'shaking', 'acceptedAnswers', jsonb_build_array(E'shaking')),
    jsonb_build_object('number', 47, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 알맞은 형태로 빈칸을 채우시오.\n\n<보기> argue / burn / hold / sing / touch / talk / scream / dance / ring / ride / move / shake\n\nI saw a performer ___ gracefully on the stage.', 'answer', E'dancing', 'acceptedAnswers', jsonb_build_array(E'dancing', E'dance')),
    jsonb_build_object('number', 48, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI didn''t hear (calling, you, my, name).\n→ I didn''t hear ___', 'answer', E'you calling my name.', 'acceptedAnswers', jsonb_build_array(E'you calling my name.', E'you calling my name')),
    jsonb_build_object('number', 49, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nDid you (cleaning, see, her, bedroom)?\n→ Did you ___?', 'answer', E'see her cleaning her bedroom?', 'acceptedAnswers', jsonb_build_array(E'see her cleaning her bedroom?', E'see her cleaning her bedroom')),
    jsonb_build_object('number', 50, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI (Jiho, with, his, friend, talking, heard).\n→ I ___', 'answer', E'heard Jiho talking with his friend.', 'acceptedAnswers', jsonb_build_array(E'heard Jiho talking with his friend.', E'heard Jiho talking with his friend')),
    jsonb_build_object('number', 51, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI''ll (her, have, my, desk, tidy).\n→ I''ll ___', 'answer', E'have her tidy my desk.', 'acceptedAnswers', jsonb_build_array(E'have her tidy my desk.', E'have her tidy my desk')),
    jsonb_build_object('number', 52, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI want to (her, help, dinner, make, for, us).\n→ I want to ___', 'answer', E'help her make dinner for us.', 'acceptedAnswers', jsonb_build_array(E'help her make dinner for us.', E'help her make dinner for us')),
    jsonb_build_object('number', 53, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI''ll (let, with, me, play, him, tennis).\n→ I''ll ___', 'answer', E'let him play tennis with me.', 'acceptedAnswers', jsonb_build_array(E'let him play tennis with me.', E'let him play tennis with me')),
    jsonb_build_object('number', 54, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nThe coach (players, the, warm, made, up).\n→ The coach ___', 'answer', E'made the players warm up.', 'acceptedAnswers', jsonb_build_array(E'made the players warm up.', E'made the players warm up')),
    jsonb_build_object('number', 55, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI (a, saw, song, Sora, singing) on the stage.\n→ I ___', 'answer', E'saw Sora singing a song on the stage.', 'acceptedAnswers', jsonb_build_array(E'saw Sora singing a song on the stage.', E'saw Sora singing a song on the stage')),
    jsonb_build_object('number', 56, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nI (Minho, waiting, bus, for, saw, a) at the stop.\n→ I ___', 'answer', E'saw Minho waiting for a bus at the stop.', 'acceptedAnswers', jsonb_build_array(E'saw Minho waiting for a bus at the stop.', E'saw Minho waiting for a bus at the stop')),
    jsonb_build_object('number', 57, 'type', 'subjective', 'question', E'다음 괄호 안의 단어를 바르게 배열하여 문장을 완성하시오.\n\nShe (play, sat, watched, and, the children).\n→ She ___', 'answer', E'sat and watched the children play.', 'acceptedAnswers', jsonb_build_array(E'sat and watched the children play.', E'sat and watched the children play')),
    jsonb_build_object('number', 58, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nDid you see anyone came into this room?', 'answer', E'come / coming', 'acceptedAnswers', jsonb_build_array(E'come', E'coming', E'come / coming', E'came → come', E'came → coming')),
    jsonb_build_object('number', 59, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nHe saw a girl to run very fast on the track.', 'answer', E'run / running', 'acceptedAnswers', jsonb_build_array(E'run', E'running', E'run / running', E'to run → run', E'to run → running')),
    jsonb_build_object('number', 60, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI felt my legs to tremble when I stood on stage.', 'answer', E'tremble / trembling', 'acceptedAnswers', jsonb_build_array(E'tremble', E'trembling', E'tremble / trembling', E'to tremble → tremble', E'to tremble → trembling')),
    jsonb_build_object('number', 61, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI felt the door shaken behind me.', 'answer', E'shake / shaking', 'acceptedAnswers', jsonb_build_array(E'shake', E'shaking', E'shake / shaking', E'shaken → shake', E'shaken → shaking')),
    jsonb_build_object('number', 62, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI heard Jina to speak French fluently.', 'answer', E'speak / speaking', 'acceptedAnswers', jsonb_build_array(E'speak', E'speaking', E'speak / speaking', E'to speak → speak', E'to speak → speaking')),
    jsonb_build_object('number', 63, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI saw a cat ran after a bird in the garden.', 'answer', E'run / running', 'acceptedAnswers', jsonb_build_array(E'run', E'running', E'run / running', E'ran → run', E'ran → running')),
    jsonb_build_object('number', 64, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI heard my neighbor laughed outside my window.', 'answer', E'laugh / laughing', 'acceptedAnswers', jsonb_build_array(E'laugh', E'laughing', E'laugh / laughing', E'laughed → laugh', E'laughed → laughing')),
    jsonb_build_object('number', 65, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI saw Mina to enter the library.', 'answer', E'enter / entering', 'acceptedAnswers', jsonb_build_array(E'enter', E'entering', E'enter / entering', E'to enter → enter', E'to enter → entering')),
    jsonb_build_object('number', 66, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nListen to the birds to sing every morning.', 'answer', E'sing / singing', 'acceptedAnswers', jsonb_build_array(E'sing', E'singing', E'sing / singing', E'to sing → sing', E'to sing → singing')),
    jsonb_build_object('number', 67, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nJisu saw a stranger to enter the building.', 'answer', E'enter / entering', 'acceptedAnswers', jsonb_build_array(E'enter', E'entering', E'enter / entering', E'to enter → enter', E'to enter → entering')),
    jsonb_build_object('number', 68, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nJunho felt somebody touches his shoulder.', 'answer', E'touch / touching', 'acceptedAnswers', jsonb_build_array(E'touch', E'touching', E'touch / touching', E'touches → touch', E'touches → touching')),
    jsonb_build_object('number', 69, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nCan you smell something to burn in the kitchen?', 'answer', E'burning', 'acceptedAnswers', jsonb_build_array(E'burning', E'burn', E'burn / burning', E'to burn → burning', E'to burn → burn')),
    jsonb_build_object('number', 70, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nWe listened to him says to himself quietly.', 'answer', E'say / saying', 'acceptedAnswers', jsonb_build_array(E'say', E'saying', E'say / saying', E'says → say', E'says → saying')),
    jsonb_build_object('number', 71, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI watched Tom painted his bicycle in the driveway.', 'answer', E'paint / painting', 'acceptedAnswers', jsonb_build_array(E'paint', E'painting', E'paint / painting', E'painted \u2192 paint', E'painted \u2192 painting')),
    jsonb_build_object('number', 72, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nPeople were cheering loudly. I heard them. The stadium was electric.', 'answer', E'I heard people cheering loudly.', 'acceptedAnswers', jsonb_build_array(E'I heard people cheering loudly.', E'I heard people cheering loudly')),
    jsonb_build_object('number', 73, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nA fire alarm was ringing. I could hear it. It went on and on.', 'answer', E'I could hear a fire alarm ringing.', 'acceptedAnswers', jsonb_build_array(E'I could hear a fire alarm ringing.', E'I could hear a fire alarm ringing')),
    jsonb_build_object('number', 74, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nThe delivery arrived. We saw it. It was right at the door.', 'answer', E'We saw the delivery arrive right at the door.', 'acceptedAnswers', jsonb_build_array(E'We saw the delivery arrive right at the door.', E'We saw the delivery arrive right at the door', E'We saw the delivery arrive.')),
    jsonb_build_object('number', 75, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nI saw a child. She was crying. She was sitting alone on a bench.', 'answer', E'I saw a child crying alone on a bench.', 'acceptedAnswers', jsonb_build_array(E'I saw a child crying alone on a bench.', E'I saw a child crying alone on a bench')),
    jsonb_build_object('number', 76, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nThe thunder roared. I heard it. It was terrifying.', 'answer', E'I heard the thunder roar.', 'acceptedAnswers', jsonb_build_array(E'I heard the thunder roar.', E'I heard the thunder roar')),
    jsonb_build_object('number', 77, 'type', 'subjective', 'question', E'다음 상황을 읽고 <보기>와 같이 한 문장으로 쓰시오.\n\n<보기> The window rattled. She felt it. She was surprised.\n\u2192 She felt the window rattle.\n\nA man was sleeping on the bench. I saw him. He was just lying there.', 'answer', E'I saw a man sleeping on the bench.', 'acceptedAnswers', jsonb_build_array(E'I saw a man sleeping on the bench.', E'I saw a man sleeping on the bench')),
    jsonb_build_object('number', 78, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n그녀는 무언가가 손에 닿는 것을 느꼈다. (feel, touch)', 'answer', E'She felt something touching her hand.', 'acceptedAnswers', jsonb_build_array(E'She felt something touching her hand.', E'She felt something touching her hand', E'She felt something touch her hand.', E'She felt something touch her hand')),
    jsonb_build_object('number', 79, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n그들은 한 남자가 그림을 그리고 있는 것을 보았다. (a man, paint)', 'answer', E'They saw a man painting a picture.', 'acceptedAnswers', jsonb_build_array(E'They saw a man painting a picture.', E'They saw a man painting a picture')),
    jsonb_build_object('number', 80, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n당신이 그 차를 닦는 것을 누가 보았나요? (anyone, see, wash)', 'answer', E'Did anyone see you washing the car?', 'acceptedAnswers', jsonb_build_array(E'Did anyone see you washing the car?', E'Did anyone see you washing the car', E'Did anyone see you wash the car?', E'Did anyone see you wash the car')),
    jsonb_build_object('number', 81, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\nMina가 자전거를 타는 것을 보았니? (see, a bike)', 'answer', E'Did you see Mina riding a bike?', 'acceptedAnswers', jsonb_build_array(E'Did you see Mina riding a bike?', E'Did you see Mina riding a bike', E'Did you see Mina ride a bike?', E'Did you see Mina ride a bike')),
    jsonb_build_object('number', 82, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n나는 책상이 흔들리고 있는 것을 느꼈다. (feel, shake)', 'answer', E'I felt the desk shaking.', 'acceptedAnswers', jsonb_build_array(E'I felt the desk shaking.', E'I felt the desk shaking', E'I felt the desk shake.', E'I felt the desk shake')),
    jsonb_build_object('number', 83, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n한 왕자가 지나가다가 라푼젤이 노래하고 있는 것을 들었다. (a prince, pass by, hear, Rapunzel)', 'answer', E'A prince passed by and heard Rapunzel singing.', 'acceptedAnswers', jsonb_build_array(E'A prince passed by and heard Rapunzel singing.', E'A prince passed by and heard Rapunzel singing')),
    jsonb_build_object('number', 84, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n그는 그의 새가 자유롭게 날고 있는 것을 보았다. (fly free)', 'answer', E'He saw his bird flying free.', 'acceptedAnswers', jsonb_build_array(E'He saw his bird flying free.', E'He saw his bird flying free', E'He saw his bird fly free.', E'He saw his bird fly free')),
    jsonb_build_object('number', 85, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n그는 한 소년이 불가사리를 바다로 던지고 있는 모습을 봤어. (throw, the starfish)\n→ ___ back into the sea.', 'answer', E'He saw a boy throwing the starfish back into the sea.', 'acceptedAnswers', jsonb_build_array(E'He saw a boy throwing the starfish back into the sea.', E'He saw a boy throwing the starfish back into the sea')),
    jsonb_build_object('number', 86, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n나는 육중한 트럭이 지나가는 소리를 들었다. (hear, heavy, go by)', 'answer', E'I heard a heavy truck go by.', 'acceptedAnswers', jsonb_build_array(E'I heard a heavy truck go by.', E'I heard a heavy truck go by', E'I heard a heavy truck going by.', E'I heard a heavy truck going by')),
    jsonb_build_object('number', 87, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n너는 집이 지금 막 흔들린 것을 느꼈니? (feel, shake)\n→ ___ just now?', 'answer', E'Did you feel the house shake just now?', 'acceptedAnswers', jsonb_build_array(E'Did you feel the house shake just now?', E'Did you feel the house shake just now', E'Did you feel the house shaking just now?', E'Did you feel the house shaking just now')),
    jsonb_build_object('number', 88, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n나는 Kate가 그녀의 방에서 우는 소리를 들었다. (hear, cry out, in)', 'answer', E'I heard Kate crying out in her room.', 'acceptedAnswers', jsonb_build_array(E'I heard Kate crying out in her room.', E'I heard Kate crying out in her room', E'I heard Kate cry out in her room.', E'I heard Kate cry out in her room')),
    jsonb_build_object('number', 89, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n우리는 해가 산 위로 떠오르는 것을 보았다. (watch, rise, over)', 'answer', E'We watched the sun rise over the mountain.', 'acceptedAnswers', jsonb_build_array(E'We watched the sun rise over the mountain.', E'We watched the sun rise over the mountain', E'We watched the sun rising over the mountain.', E'We watched the sun rising over the mountain')),
    jsonb_build_object('number', 90, 'type', 'subjective', 'question', E'다음 우리말을 주어진 힌트 단어를 활용하여 영작하시오.\n\n그는 스케이트를 타고 있었는데 귀가 어는 것 같았다. (ice-skating, feel, freeze)', 'answer', E'He was ice-skating and felt his ears freezing.', 'acceptedAnswers', jsonb_build_array(E'He was ice-skating and felt his ears freezing.', E'He was ice-skating and felt his ears freezing', E'He was ice-skating and felt his ears freeze.'))
  );

  v_answer_key := jsonb_build_array(
    jsonb_build_object('number',1, 'answer',E'selling'),
    jsonb_build_object('number',2, 'answer',E'shake'),
    jsonb_build_object('number',3, 'answer',E'singing'),
    jsonb_build_object('number',4, 'answer',E'painting'),
    jsonb_build_object('number',5, 'answer',E'crawling'),
    jsonb_build_object('number',6, 'answer',E'calling'),
    jsonb_build_object('number',7, 'answer',E'clap'),
    jsonb_build_object('number',8, 'answer',E'cross'),
    jsonb_build_object('number',9, 'answer',E'standing'),
    jsonb_build_object('number',10, 'answer',E'floating'),
    jsonb_build_object('number',11, 'answer',E'living'),
    jsonb_build_object('number',12, 'answer',E'coming'),
    jsonb_build_object('number',13, 'answer',E'flying'),
    jsonb_build_object('number',14, 'answer',E'arguing'),
    jsonb_build_object('number',15, 'answer',E'disappearing'),
    jsonb_build_object('number',16, 'answer',E'catching'),
    jsonb_build_object('number',17, 'answer',E'meowing'),
    jsonb_build_object('number',18, 'answer',E'perform'),
    jsonb_build_object('number',19, 'answer',E'help'),
    jsonb_build_object('number',20, 'answer',E'growing'),
    jsonb_build_object('number',21, 'answer',E'I can feel my heart beating fast.'),
    jsonb_build_object('number',22, 'answer',E'We heard them laughing all night.'),
    jsonb_build_object('number',23, 'answer',E'Did you notice me waving at you?'),
    jsonb_build_object('number',24, 'answer',E'I can smell something cooking.'),
    jsonb_build_object('number',25, 'answer',E'Did you see the fireworks explode?'),
    jsonb_build_object('number',26, 'answer',E'I saw you jogging in the park the other day.'),
    jsonb_build_object('number',27, 'answer',E'I heard many people cheering loudly.'),
    jsonb_build_object('number',28, 'answer',E'I heard her singing on the balcony.'),
    jsonb_build_object('number',29, 'answer',E'I noticed her running across the field.'),
    jsonb_build_object('number',30, 'answer',E'I heard him leaving the building early this morning.'),
    jsonb_build_object('number',31, 'answer',E'I listened to them performing a dance.'),
    jsonb_build_object('number',32, 'answer',E'She stood there and watched him drive away.'),
    jsonb_build_object('number',33, 'answer',E'We saw the cat climbing up the fence.'),
    jsonb_build_object('number',34, 'answer',E'Have you ever heard her tell amazing stories?'),
    jsonb_build_object('number',35, 'answer',E'I''ve often seen you skateboarding near the school.'),
    jsonb_build_object('number',36, 'answer',E'burning'),
    jsonb_build_object('number',37, 'answer',E'arguing'),
    jsonb_build_object('number',38, 'answer',E'holding'),
    jsonb_build_object('number',39, 'answer',E'singing'),
    jsonb_build_object('number',40, 'answer',E'touching'),
    jsonb_build_object('number',41, 'answer',E'moving'),
    jsonb_build_object('number',42, 'answer',E'talking'),
    jsonb_build_object('number',43, 'answer',E'riding'),
    jsonb_build_object('number',44, 'answer',E'ringing'),
    jsonb_build_object('number',45, 'answer',E'screaming'),
    jsonb_build_object('number',46, 'answer',E'shaking'),
    jsonb_build_object('number',47, 'answer',E'dancing'),
    jsonb_build_object('number',48, 'answer',E'you calling my name.'),
    jsonb_build_object('number',49, 'answer',E'see her cleaning her bedroom?'),
    jsonb_build_object('number',50, 'answer',E'heard Jiho talking with his friend.'),
    jsonb_build_object('number',51, 'answer',E'have her tidy my desk.'),
    jsonb_build_object('number',52, 'answer',E'help her make dinner for us.'),
    jsonb_build_object('number',53, 'answer',E'let him play tennis with me.'),
    jsonb_build_object('number',54, 'answer',E'made the players warm up.'),
    jsonb_build_object('number',55, 'answer',E'saw Sora singing a song on the stage.'),
    jsonb_build_object('number',56, 'answer',E'saw Minho waiting for a bus at the stop.'),
    jsonb_build_object('number',57, 'answer',E'sat and watched the children play.'),
    jsonb_build_object('number',58, 'answer',E'come / coming'),
    jsonb_build_object('number',59, 'answer',E'run / running'),
    jsonb_build_object('number',60, 'answer',E'tremble / trembling'),
    jsonb_build_object('number',61, 'answer',E'shake / shaking'),
    jsonb_build_object('number',62, 'answer',E'speak / speaking'),
    jsonb_build_object('number',63, 'answer',E'run / running'),
    jsonb_build_object('number',64, 'answer',E'laugh / laughing'),
    jsonb_build_object('number',65, 'answer',E'enter / entering'),
    jsonb_build_object('number',66, 'answer',E'sing / singing'),
    jsonb_build_object('number',67, 'answer',E'enter / entering'),
    jsonb_build_object('number',68, 'answer',E'touch / touching'),
    jsonb_build_object('number',69, 'answer',E'burning'),
    jsonb_build_object('number',70, 'answer',E'say / saying'),
    jsonb_build_object('number',71, 'answer',E'paint / painting'),
    jsonb_build_object('number',72, 'answer',E'I heard people cheering loudly.'),
    jsonb_build_object('number',73, 'answer',E'I could hear a fire alarm ringing.'),
    jsonb_build_object('number',74, 'answer',E'We saw the delivery arrive right at the door.'),
    jsonb_build_object('number',75, 'answer',E'I saw a child crying alone on a bench.'),
    jsonb_build_object('number',76, 'answer',E'I heard the thunder roar.'),
    jsonb_build_object('number',77, 'answer',E'I saw a man sleeping on the bench.'),
    jsonb_build_object('number',78, 'answer',E'She felt something touching her hand.'),
    jsonb_build_object('number',79, 'answer',E'They saw a man painting a picture.'),
    jsonb_build_object('number',80, 'answer',E'Did anyone see you washing the car?'),
    jsonb_build_object('number',81, 'answer',E'Did you see Mina riding a bike?'),
    jsonb_build_object('number',82, 'answer',E'I felt the desk shaking.'),
    jsonb_build_object('number',83, 'answer',E'A prince passed by and heard Rapunzel singing.'),
    jsonb_build_object('number',84, 'answer',E'He saw his bird flying free.'),
    jsonb_build_object('number',85, 'answer',E'He saw a boy throwing the starfish back into the sea.'),
    jsonb_build_object('number',86, 'answer',E'I heard a heavy truck go by.'),
    jsonb_build_object('number',87, 'answer',E'Did you feel the house shake just now?'),
    jsonb_build_object('number',88, 'answer',E'I heard Kate crying out in her room.'),
    jsonb_build_object('number',89, 'answer',E'We watched the sun rise over the mountain.'),
    jsonb_build_object('number',90, 'answer',E'He was ice-skating and felt his ears freezing.')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('지각동사 Step1', '지각동사', v_questions, v_answer_key, 'problem', 'interactive');
END;
$$;
