-- 현재완료 Step 2 — 객관식 70문항
-- template_topic: 현재완료
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '현재완료 Step 2';

  q := jsonb_build_array(
jsonb_build_object('number',1,
  'question',E'[Part 1] \ube48\uce78\uc5d0 \uc54c\ub9de\uc740 \uac83\uc744 \uace0\ub974\uc2dc\uc624.\n\nI have __________ my homework. I can relax now.',
  'options',jsonb_build_array(E'finish',E'finishing',E'finished',E'to finish',E'been finish'),
  'answer','3',
  'explanation',E'have + p.p. \u2192 finished'),
jsonb_build_object('number',2,
  'question',E'She __________ never eaten Thai food before.',
  'options',jsonb_build_array(E'do',E'does',E'did',E'has',E'have'),
  'answer','4',
  'explanation',E'She \u2192 3\uc778\uce6d \ub2e8\uc218 has'),
jsonb_build_object('number',3,
  'question',E'My brother __________ to Canada. He\u2019s not here now.',
  'options',jsonb_build_array(E'goes',E'has been',E'has gone',E'have gone',E'went'),
  'answer','3',
  'explanation',E'\uc5ec\uae30 \uc5c6\uc74c \u2192 has gone'),
jsonb_build_object('number',4,
  'question',E'We have known each other __________ we were in elementary school.',
  'options',jsonb_build_array(E'for',E'during',E'since',E'until',E'before'),
  'answer','3',
  'explanation',E'\ud2b9\uc815 \uc2dc\uc810(we were~) \u2192 since'),
jsonb_build_object('number',5,
  'question',E'__________ you ever tried riding a horse before?',
  'options',jsonb_build_array(E'Do',E'Did',E'Are',E'Were',E'Have'),
  'answer','5',
  'explanation',E'\ud604\uc7ac\uc644\ub8cc \uc758\ubb38\ubb38 Have + p.p.'),
jsonb_build_object('number',6,
  'question',E'How long __________ she lived in this city?',
  'options',jsonb_build_array(E'do',E'did',E'is',E'was',E'has'),
  'answer','5',
  'explanation',E'How long + has + p.p.'),
jsonb_build_object('number',7,
  'question',E'I started working here in 2020. I __________ here for four years.',
  'options',jsonb_build_array(E'work',E'worked',E'am working',E'have worked',E'was working'),
  'answer','4',
  'explanation',E'for four years + \ud604\uc7ac\uae4c\uc9c0 \u2192 \ud604\uc7ac\uc644\ub8cc'),
jsonb_build_object('number',8,
  'question',E'Tom can\u2019t find his wallet. He __________ it somewhere.',
  'options',jsonb_build_array(E'loses',E'lost',E'has lost',E'have lost',E'was losing'),
  'answer','3',
  'explanation',E'\ud604\uc7ac \uacb0\uacfc(\ubabb \ucc3e\uc74c) \u2192 has lost'),
jsonb_build_object('number',9,
  'question',E'My family has lived in Busan __________ ten years.',
  'options',jsonb_build_array(E'since',E'during',E'before',E'until',E'for'),
  'answer','5',
  'explanation',E'ten years(\uae30\uac04) \u2192 for'),
jsonb_build_object('number',10,
  'question',E'__________ the postman come yet?',
  'options',jsonb_build_array(E'Does',E'Did',E'Is',E'Was',E'Has'),
  'answer','5',
  'explanation',E'yet \u2192 \ud604\uc7ac\uc644\ub8cc Has + p.p.'),
jsonb_build_object('number',11,
  'question',E'I haven\u2019t seen my cousin __________ last summer.',
  'options',jsonb_build_array(E'for',E'during',E'since',E'after',E'until'),
  'answer','3',
  'explanation',E'last summer(\ud2b9\uc815 \uc2dc\uc810) \u2192 since'),
jsonb_build_object('number',12,
  'question',E'She has __________ finished her report. She looks relieved.',
  'options',jsonb_build_array(E'yet',E'never',E'ago',E'just',E'before'),
  'answer','4',
  'explanation',E'\ubc29\uae08 \uc644\ub8cc \u2192 just'),
jsonb_build_object('number',13,
  'question',E'[Part 2] \ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740/\uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc744 \uace0\ub974\uc2dc\uc624.\n\n\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'He has went to the library.',E'She have studied English for five years.',E'I have never been to Europe before.',E'They has lived here since 2010.',E'When have you met her?'),
  'answer','3',
  'explanation',E'\u2460 went\u2192gone \u2461 have\u2192has \u2463 has\u2192have \u2464 When\u2192\uacfc\uac70\uc2dc\uc81c'),
jsonb_build_object('number',14,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have been to Jeju Island twice.',E'She has just finished her lunch.',E'Have you ever seen a shooting star?',E'He has visited his uncle last weekend.',E'We haven\u2019t solved the problem yet.'),
  'answer','4',
  'explanation',E'last weekend \u2192 \uacfc\uac70\uc2dc\uc81c'),
jsonb_build_object('number',15,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have lost my key yesterday.',E'She has been to Paris last year.',E'When have you bought that coat?',E'They have known each other for ten years.',E'We have studied together two days ago.'),
  'answer','4',
  'explanation',E'for ten years \u2192 \ud604\uc7ac\uc644\ub8cc \uacc4\uc18d \uc6a9\ubc95'),
jsonb_build_object('number',16,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'Kate has not bought the book yet.',E'I have never made such a big mistake.',E'He has gone to Japan. He\u2019ll be back soon.',E'She has worked as a nurse since last year.',E'I haven\u2019t seen Minho since three months.'),
  'answer','5',
  'explanation',E'since three months \u2192 for three months'),
jsonb_build_object('number',17,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have lived in Seoul since 2005.',E'He has finished his homework last night.',E'When have you started learning piano?',E'She has met her old friend two weeks ago.',E'They have studied math together yesterday.'),
  'answer','1',
  'explanation',E'since 2005 \u2192 \ud604\uc7ac\uc644\ub8cc \uacc4\uc18d'),
jsonb_build_object('number',18,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have been here for three hours.',E'Have you ever ridden a camel?',E'She has just arrived at the airport.',E'They have gave him a surprise party.',E'My dog has been sick since Monday.'),
  'answer','4',
  'explanation',E'gave \u2192 given'),
jsonb_build_object('number',19,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'She has visit her grandparents last Sunday.',E'How long does she has lived here?',E'I haven\u2019t finished reading the book yet.',E'He have never eaten Indian food before.',E'We have went to the cinema last Friday.'),
  'answer','3',
  'explanation',E'haven\u2019t + p.p. + yet \uc62c\ubc14\ub984'),
jsonb_build_object('number',20,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'Have you ever tried kimchi jjigae?',E'I have already sent the email.',E'She hasn\u2019t called me since her birthday.',E'Tom has gone to Australia twice.',E'My parents have just come back from their trip.'),
  'answer','4',
  'explanation',E'\uacbd\ud5d8(twice) \u2192 has been to, has gone\uc740 \uac00\uace0 \uc5c6\uc744 \ub54c'),
jsonb_build_object('number',21,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have saw that movie three times.',E'She have been to London before.',E'They haven\u2019t eaten anything since this morning.',E'He has wrote a letter to his teacher yesterday.',E'We have visit the museum last week.'),
  'answer','3',
  'explanation',E'since this morning \u2192 \ud604\uc7ac\uc644\ub8cc \uc62c\ubc14\ub984'),
jsonb_build_object('number',22,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have read that novel twice.',E'She has never tried bungee jumping.',E'Have you already finished your homework?',E'He has lost his glasses. He can\u2019t see well.',E'They have moved to Busan three days ago.'),
  'answer','5',
  'explanation',E'three days ago \u2192 \uacfc\uac70\uc2dc\uc81c'),
jsonb_build_object('number',23,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'She has never rode a horse before.',E'I have been to London. I just came back.',E'They have studied English since five years.',E'He has called me one hour ago.',E'We have saw the movie last weekend.'),
  'answer','2',
  'explanation',E'have been to = \uac14\ub2e4 \uc634, rode\u2192ridden'),
jsonb_build_object('number',24,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'I have known her since we were children.',E'She has just woken up. She looks tired.',E'How long have you studied Korean?',E'He has not drunk any water since this morning.',E'I have never meet a famous singer before.'),
  'answer','5',
  'explanation',E'meet \u2192 met'),
jsonb_build_object('number',25,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'It has rained since last week.',E'When have they arrived at the hotel?',E'She has cooked dinner two hours ago.',E'He have just finished his project.',E'We have been friends since long time.'),
  'answer','1',
  'explanation',E'since last week \u2192 \ud604\uc7ac\uc644\ub8cc \uc62c\ubc14\ub984'),
jsonb_build_object('number',26,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'She has been in Seoul for a month.',E'I have never seen such a beautiful sunset.',E'Have you ever eaten Turkish food before?',E'He has just leave the building.',E'They have lived here since they got married.'),
  'answer','4',
  'explanation',E'leave \u2192 left'),
jsonb_build_object('number',27,
  'question',E'\ub2e4\uc74c \uc911 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \ubb38\uc7a5\uc740?',
  'options',jsonb_build_array(E'She has went to the store. She\u2019ll be back soon.',E'I have finished the report last night.',E'How long have you been in Korea?',E'They have not eaten anything two days ago.',E'He have known her for many years.'),
  'answer','3',
  'explanation',E'How long + have + p.p. \uc62c\ubc14\ub984'),
jsonb_build_object('number',28,
  'question',E'[Part 3] \ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740/\uc5b4\uc0c9\ud55c \uac83\uc744 \uace0\ub974\uc2dc\uc624.\n\n\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \uac83\uc740?',
  'options',jsonb_build_array(E'She has <u>lost</u> her umbrella.',E'I have <u>read</u> this book twice.',E'They have <u>gave</u> him a birthday present.',E'We haven\u2019t <u>finished</u> our project yet.',E'He has <u>lived</u> in Incheon for five years.'),
  'answer','3',
  'explanation',E'gave \u2192 given'),
jsonb_build_object('number',29,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \uac83\uc740?',
  'options',jsonb_build_array(E'When <u>have you seen</u> that movie?',E'I <u>have been</u> to Dokdo three times.',E'She <u>has met</u> her boyfriend last night.',E'We have studied English <u>since five years</u>.',E'I <u>have finished</u> my homework 2 hours ago.'),
  'answer','2',
  'explanation',E'have been to + \uc7a5\uc18c = \uacbd\ud5d8'),
jsonb_build_object('number',30,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \uac83\uc740?',
  'options',jsonb_build_array(E'I have been here <u>for</u> two years.',E'Have you <u>done</u> your homework yet?',E'Kate <u>has just arrived</u> at the station.',E'I have learned Chinese <u>for</u> three months.',E'He <u>has gone</u> to the library yesterday.'),
  'answer','5',
  'explanation',E'yesterday \u2192 \uacfc\uac70\uc2dc\uc81c'),
jsonb_build_object('number',31,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \uac83\uc740?',
  'options',jsonb_build_array(E'She has been there <u>since yesterday</u>.',E'I <u>have met</u> my friend last night.',E'He has <u>wrote</u> five books so far.',E'We <u>have studied</u> together two days ago.',E'She <u>have</u> never eaten Mexican food before.'),
  'answer','1',
  'explanation',E'since yesterday \u2192 \ud604\uc7ac\uc644\ub8cc \uacc4\uc18d'),
jsonb_build_object('number',32,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \uac83\uc740?',
  'options',jsonb_build_array(E'He has <u>lost</u> his cell phone.',E'I have <u>seen</u> this film before.',E'They have <u>spreaded</u> the news widely.',E'We haven\u2019t <u>cleaned</u> our room yet.',E'She has <u>lived</u> in Seoul for four years.'),
  'answer','3',
  'explanation',E'spread-spread-spread, spreaded\ub294 \ud2c0\ub9bc'),
jsonb_build_object('number',33,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \uac83\uc740?',
  'options',jsonb_build_array(E'I <u>have read</u> a book yesterday.',E'I <u>have lived</u> in Daegu for ten years.',E'When <u>have you visited</u> that museum?',E'She <u>have</u> already finished cooking.',E'We <u>have studied</u> together yesterday.'),
  'answer','2',
  'explanation',E'for ten years \u2192 \ud604\uc7ac\uc644\ub8cc \uacc4\uc18d'),
jsonb_build_object('number',34,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \uac83\uc740?',
  'options',jsonb_build_array(E'She has been there <u>since last Tuesday</u>.',E'Have you ever <u>seen</u> that movie before?',E'I have <u>known</u> Jake for many years.',E'She has <u>written</u> three books for ten years.',E'Tom <u>has arrived</u> here three days ago.'),
  'answer','5',
  'explanation',E'three days ago \u2192 \uacfc\uac70\uc2dc\uc81c'),
jsonb_build_object('number',35,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \uac83\uc740?',
  'options',jsonb_build_array(E'I have <u>saw</u> him twice this week.',E'She <u>have</u> not done her homework yet.',E'How long <u>have you been</u> together?',E'He <u>has called</u> me two hours ago.',E'We have <u>went</u> to the park last Sunday.'),
  'answer','3',
  'explanation',E'How long + have + p.p. \uc62c\ubc14\ub984'),
jsonb_build_object('number',36,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc5b4\uc0c9\ud55c \uac83\uc740?',
  'options',jsonb_build_array(E'I have <u>been</u> to Hong Kong before.',E'She has never <u>made</u> so much money.',E'He has <u>went</u> to South Africa for work.',E'They have <u>lived</u> here since 2015.',E'I haven\u2019t <u>seen</u> him for three months.'),
  'answer','3',
  'explanation',E'went \u2192 gone'),
jsonb_build_object('number',37,
  'question',E'\ub2e4\uc74c \uc911 \ubc11\uc904 \uce5c \ubd80\ubd84\uc774 \uc5b4\ubc95\uc0c1 \uc62c\uc740 \uac83\uc740?',
  'options',jsonb_build_array(E'She <u>has visit</u> Paris two years ago.',E'<u>Have you ever been</u> to New Zealand?',E'He <u>have</u> not finished his lunch yet.',E'I <u>have lost</u> my key two days ago.',E'She has <u>knew</u> him since childhood.'),
  'answer','2',
  'explanation',E'Have you ever been to = \uacbd\ud5d8 \ud604\uc7ac\uc644\ub8cc'),
jsonb_build_object('number',38,
  'question',E'[Part 4] 다음 중 어법상 어색한 문장을 2개 고르면?\n\n① I have never been to Africa.\n② She has just finish cooking dinner.\n③ They have lived here since 2018.\n④ He has went to the gym. He''ll be back soon.\n⑤ Have you ever tried surfing before?',
  'options',jsonb_build_array(E'①, ③',E'②, ⑤',E'②, ④',E'③, ④',E'④, ⑤'),
  'answer','3',
  'explanation',E'② finish→finished, ④ went→gone'),
jsonb_build_object('number',39,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① Have you already packed your bag?\n② When has the accident happened?\n③ She has studied French for three years.\n④ I have seen her at the party last night.\n⑤ He hasn''t called me since last Monday.',
  'options',jsonb_build_array(E'①, ④',E'②, ③',E'③, ⑤',E'②, ④',E'①, ②'),
  'answer','4',
  'explanation',E'② When→과거시제, ④ last night→과거시제'),
jsonb_build_object('number',40,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① I have been here for two hours.\n② They have been married for two years ago.\n③ She has never eaten octopus before.\n④ Mike has went to London. He''s not here.\n⑤ How long have you known her?',
  'options',jsonb_build_array(E'②, ④',E'①, ②',E'②, ③',E'③, ④',E'④, ⑤'),
  'answer','1',
  'explanation',E'② for...ago 모순, ④ went→gone'),
jsonb_build_object('number',41,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① She has lived in this house since she was born.\n② I have lost my wallet. I can''t find it anywhere.\n③ When have you started learning Chinese?\n④ They have visited their uncle last weekend.\n⑤ He hasn''t finished his project yet.',
  'options',jsonb_build_array(E'①, ③',E'②, ④',E'②, ③',E'④, ⑤',E'③, ④'),
  'answer','5',
  'explanation',E'③ When→과거시제, ④ last weekend→과거시제'),
jsonb_build_object('number',42,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① I haven''t finished my homework yet.\n② She has just arrived at the station.\n③ He have known her since they were young.\n④ We have studied English since 2019.\n⑤ Tom has called me two hours ago.',
  'options',jsonb_build_array(E'②, ③',E'③, ⑤',E'①, ⑤',E'③, ④',E'④, ⑤'),
  'answer','2',
  'explanation',E'③ have→has, ⑤ ago→과거시제'),
jsonb_build_object('number',43,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① How long have you lived in this city?\n② She hasn''t seen her best friend since summer.\n③ I have never rode a motorcycle before.\n④ They has known each other for many years.\n⑤ He has already sent the invitation cards.',
  'options',jsonb_build_array(E'②, ③',E'①, ④',E'②, ⑤',E'③, ④',E'④, ⑤'),
  'answer','4',
  'explanation',E'③ rode→ridden, ④ has→have'),
jsonb_build_object('number',44,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① We have enjoyed our holiday so far.\n② She has been a teacher since she was 25.\n③ I have saw that film at least five times.\n④ They haven''t eaten anything since morning.\n⑤ He has visited his parents last Sunday.',
  'options',jsonb_build_array(E'③, ⑤',E'①, ③',E'②, ④',E'③, ④',E'④, ⑤'),
  'answer','1',
  'explanation',E'③ saw→seen, ⑤ last Sunday→과거시제'),
jsonb_build_object('number',45,
  'question',E'다음 중 어법상 어색한 문장을 2개 고르면?\n\n① Have you ever met anyone famous?\n② I have not seen Minji since three months.\n③ She has worked here for a long time.\n④ They have went on a trip last week.\n⑤ He hasn''t replied to my message yet.',
  'options',jsonb_build_array(E'①, ②',E'②, ③',E'②, ④',E'④, ⑤',E'②, ⑤'),
  'answer','3',
  'explanation',E'② since three months→for three months, ④ went+last week→과거시제'),
jsonb_build_object('number',46,
  'question',E'[Part 5] 다음 중 어법상 옳은 문장의 총 개수는?\n\nⓐ She has never been to America.\nⓑ I have met her at the café yesterday.\nⓒ He has just finished his breakfast.\nⓓ They have studied together two days ago.\nⓔ We have known each other since 2016.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','3',
  'explanation',E'ⓐⓒⓔ 올바름 (ⓑ yesterday, ⓓ ago → 과거시제)'),
jsonb_build_object('number',47,
  'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\nⓐ I have lived here for ten years.\nⓑ She has went to the store. She''ll be back.\nⓒ Have you ever eaten Vietnamese food?\nⓓ When has he called you?\nⓔ I haven''t seen him since last Christmas.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','3',
  'explanation',E'ⓐⓒⓔ 올바름'),
jsonb_build_object('number',48,
  'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\nⓐ I have just arrived at the airport.\nⓑ She has studied piano since five years.\nⓒ They have been friends since middle school.\nⓓ He has sent the email two days ago.\nⓔ Have you already finished the test?',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','3',
  'explanation',E'ⓐⓒⓔ 올바름'),
jsonb_build_object('number',49,
  'question',E'다음 중 어법상 어색한 문장의 총 개수는?\n\nⓐ She helped him last year.\nⓑ In 2002, the World Cup have been held in Korea.\nⓒ We have known each other since we were kids.\nⓓ He has got a call from Jenny two weeks ago.\nⓔ They haven''t finished the meal yet.\nⓕ I have talked to her yesterday.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','3',
  'explanation',E'ⓑⓓⓕ 어색 (ⓑ have→was, ⓓ ago→과거, ⓕ yesterday→과거)'),
jsonb_build_object('number',50,
  'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\nⓐ Tony has not woken up yet.\nⓑ How long have you been together?\nⓒ Isaac has been in the hospital then.\nⓓ She has studied in this school since 2020.\nⓔ Logan has broken this window yesterday.\nⓕ Jane has already finished the project.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','4',
  'explanation',E'ⓐⓑⓓⓕ 올바름 (ⓒ then→과거, ⓔ yesterday→과거)'),
jsonb_build_object('number',51,
  'question',E'다음 중 어법상 어색한 문장의 총 개수는?\n\nⓐ I have just finished lunch.\nⓑ She has not done her homework yet.\nⓒ They have been married for five years.\nⓓ Mr. Kim has stopped smoking 3 years ago.\nⓔ We have known each other since 2017.\nⓕ My parents have went to Doha. They''re not here.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','2',
  'explanation',E'ⓓ ago→과거시제, ⓕ went→gone'),
jsonb_build_object('number',52,
  'question',E'다음 중 어법상 옳은 문장의 총 개수는?\n\nⓐ He has seen Boa once.\nⓑ Suji has just finished cleaning the room.\nⓒ She have never eaten Mexican food.\nⓓ I haven''t eaten anything since this morning.\nⓔ When has he called her?\nⓕ Sera has been to Europe before.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','4',
  'explanation',E'ⓐⓑⓓⓕ 올바름 (ⓒ have→has, ⓔ When→과거시제)'),
jsonb_build_object('number',53,
  'question',E'다음 중 어법상 어색한 문장의 총 개수는?\n\nⓐ Hanjin looks angrier than usual today.\nⓑ She has never been to overseas before.\nⓒ He is the luckiest man I have ever met.\nⓓ I have lost my phone. I can''t find it.\nⓔ Jaeseok has called me two days ago.\nⓕ It is the most delicious food I''ve ever had.',
  'options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),
  'answer','2',
  'explanation',E'ⓑ to overseas→overseas (overseas는 부사), ⓔ ago→과거시제'),
jsonb_build_object('number',54,
  'question',E'[Part 6] 다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\n㉠ He has gone to France.\n㉡ I have been to Canada twice.\n㉢ Have you finish your homework?\n㉣ She have never eaten Mexican food.\n㉤ I''ve been to the restaurant last week.',
  'options',jsonb_build_array(E'㉠, ㉡',E'㉠, ㉢',E'㉡, ㉣',E'㉢, ㉤',E'㉣, ㉤'),
  'answer','1',
  'explanation',E'㉠㉡ 올바름 (㉢ finish→finished, ㉣ have→has, ㉤ last week→과거)'),
jsonb_build_object('number',55,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\nⓐ I have just finished lunch.\nⓑ When have you visited Turkey?\nⓒ She has not done her homework yet.\nⓓ They have been married for five years.\nⓔ Mr. Kim has stopped smoking 5 years ago.\nⓕ I have already explained this to you twice.',
  'options',jsonb_build_array(E'ⓐ, ⓑ, ⓒ',E'ⓐ, ⓒ, ⓓ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓓ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓔ'),
  'answer','4',
  'explanation',E'ⓐⓒⓓⓕ 올바름'),
jsonb_build_object('number',56,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\nⓐ It has rained since last week.\nⓑ I read the book last night.\nⓒ Jane has known him for six years.\nⓓ We have studied math together yesterday.\nⓔ I have saved my allowance since January.',
  'options',jsonb_build_array(E'ⓐ, ⓑ',E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓒ, ⓓ',E'ⓐ, ⓑ, ⓒ, ⓔ',E'ⓐ, ⓑ, ⓒ, ⓓ, ⓔ'),
  'answer','4',
  'explanation',E'ⓐⓑⓒⓔ 올바름 (ⓓ yesterday→과거)'),
jsonb_build_object('number',57,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\n㉠ She has been there since yesterday.\n㉡ Have you ever seen that movie before?\n㉢ I have known Greg for many years.\n㉣ She has arrived here three days ago.\n㉤ He hasn''t replied to my message yet.',
  'options',jsonb_build_array(E'㉠, ㉡, ㉢',E'㉠, ㉢, ㉣',E'㉡, ㉢, ㉤',E'㉠, ㉡, ㉢, ㉤',E'㉡, ㉢, ㉣, ㉤'),
  'answer','4',
  'explanation',E'㉠㉡㉢㉤ 올바름 (㉣ ago→과거)'),
jsonb_build_object('number',58,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\nⓐ I have never tried skydiving.\nⓑ She has went to Paris for a week.\nⓒ Have you ever seen the Northern Lights?\nⓓ They have lived here since they got married.\nⓔ He has called me one hour ago.',
  'options',jsonb_build_array(E'ⓐ, ⓒ',E'ⓐ, ⓑ, ⓒ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓒ, ⓓ',E'ⓐ, ⓒ, ⓓ, ⓔ'),
  'answer','4',
  'explanation',E'ⓐⓒⓓ 올바름'),
jsonb_build_object('number',59,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\nⓐ I have just arrived at the airport.\nⓑ She has studied piano since five years.\nⓒ They have been close friends since middle school.\nⓓ He has sent the email two days ago.\nⓔ We haven''t eaten anything since this morning.\nⓕ How long has your brother lived with you?',
  'options',jsonb_build_array(E'ⓐ, ⓒ, ⓔ',E'ⓐ, ⓑ, ⓒ',E'ⓑ, ⓓ, ⓕ',E'ⓐ, ⓒ, ⓔ, ⓕ',E'ⓑ, ⓓ, ⓔ, ⓕ'),
  'answer','4',
  'explanation',E'ⓐⓒⓔⓕ 올바름'),
jsonb_build_object('number',60,
  'question',E'다음 중 어법상 옳은 것끼리 바르게 묶인 것은?\n\nⓐ She has never ridden a horse before.\nⓑ I have met my friend at the mall yesterday.\nⓒ He has just finished his project.\nⓓ They hasn''t eaten dinner yet.\nⓔ We have known each other since 2014.\nⓕ How long has she been in this school?',
  'options',jsonb_build_array(E'ⓐ, ⓒ, ⓔ',E'ⓑ, ⓓ, ⓔ',E'ⓐ, ⓑ, ⓒ',E'ⓐ, ⓒ, ⓔ, ⓕ',E'ⓑ, ⓒ, ⓓ, ⓔ'),
  'answer','4',
  'explanation',E'ⓐⓒⓔⓕ 올바름'),
jsonb_build_object('number',61,
  'question',E'[Part 7] 다음 대화의 빈칸에 가장 알맞은 것은?\n\nA: Where is Sujin?\nB: She __________ to the convenience store. She''ll be back soon.',
  'options',jsonb_build_array(E'goes',E'went',E'has been',E'has gone',E'have gone'),
  'answer','4',
  'explanation',E'여기 없음 + 곧 돌아옴 → has gone'),
jsonb_build_object('number',62,
  'question',E'다음 대화의 빈칸에 가장 알맞은 것은?\n\nA: Do you want to watch this movie?\nB: No thanks. I __________ it already. Let''s watch something else.',
  'options',jsonb_build_array(E'see',E'saw',E'have seen',E'have saw',E'am seeing'),
  'answer','3',
  'explanation',E'already → 현재완료(완료)'),
jsonb_build_object('number',63,
  'question',E'다음 대화의 빈칸에 가장 알맞은 것은?\n\nA: Is your mom home?\nB: No. She __________ to the supermarket. She bought some vegetables for us.',
  'options',jsonb_build_array(E'has gone',E'has been',E'went',E'goes',E'is going'),
  'answer','2',
  'explanation',E'야채를 사왔음 → 갔다 돌아옴 → has been'),
jsonb_build_object('number',64,
  'question',E'다음 대화의 빈칸에 가장 알맞은 것은?\n\nA: You look tired. What happened?\nB: I __________ all night to finish my assignment.',
  'options',jsonb_build_array(E'work',E'worked',E'have worked',E'am working',E'was working'),
  'answer','3',
  'explanation',E'결과(피곤해 보임) → 현재완료'),
jsonb_build_object('number',65,
  'question',E'다음 대화의 빈칸에 가장 알맞은 것은?\n\nA: Can I speak to Jake, please?\nB: I''m sorry, but he __________ out. He''ll be back after dinner.',
  'options',jsonb_build_array(E'goes',E'went',E'has been',E'have gone',E'has gone'),
  'answer','5',
  'explanation',E'여기 없음(외출 중) → has gone'),
jsonb_build_object('number',66,
  'question',E'[Part 8] 다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것은?\n\n<보기> I <u>have just finished</u> my homework. (완료)',
  'options',jsonb_build_array(E'She has been to New York twice.',E'He has lost his wallet. He can''t pay.',E'They have lived here since 2010.',E'Have you already packed your bag?',E'I have never tried rock climbing before.'),
  'answer','4',
  'explanation',E'보기=완료(just), ④=완료(already)'),
jsonb_build_object('number',67,
  'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것은?\n\n<보기> <u>Have you ever ridden</u> a horse? (경험)',
  'options',jsonb_build_array(E'She has just arrived at the station.',E'I have studied Japanese for 5 years.',E'I have seen a rainbow before.',E'I have lived here since 1995.',E'How long have you stayed here?'),
  'answer','3',
  'explanation',E'보기=경험(ever), ③=경험(before)'),
jsonb_build_object('number',68,
  'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것은?\n\n<보기> She <u>has lost</u> her passport. She can''t travel. (결과)',
  'options',jsonb_build_array(E'Have you ever tried Thai food?',E'I have worked here since March.',E'He has already finished his homework.',E'My friend has gone to Canada. He''s not here.',E'She has read "Harry Potter" three times.'),
  'answer','4',
  'explanation',E'보기=결과, ④=결과(가고 없음)'),
jsonb_build_object('number',69,
  'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 같은 것은?\n\n<보기> I <u>have known</u> him for ten years. (계속)',
  'options',jsonb_build_array(E'I have once lived in London.',E'I have never met any movie stars.',E'Have you ever been to Sydney?',E'I have read the novel twice.',E'She has lived in Seoul since she was eight.'),
  'answer','5',
  'explanation',E'보기=계속(for), ⑤=계속(since)'),
jsonb_build_object('number',70,
  'question',E'다음 중 밑줄 친 부분의 쓰임이 <보기>와 다른 것은?\n\n<보기> She <u>has met</u> him twice. (경험)',
  'options',jsonb_build_array(E'Have you heard about the new café?',E'She has been to Jejudo three times.',E'She hasn''t seen a koala before.',E'She has ridden a horse once.',E'She has gone to Fiji with her family.'),
  'answer','5',
  'explanation',E'①②③④=경험, ⑤=결과(가고 없음)')
  );

  a := jsonb_build_array(
    jsonb_build_object('number',1,'answer','3'),
    jsonb_build_object('number',2,'answer','4'),
    jsonb_build_object('number',3,'answer','3'),
    jsonb_build_object('number',4,'answer','3'),
    jsonb_build_object('number',5,'answer','5'),
    jsonb_build_object('number',6,'answer','5'),
    jsonb_build_object('number',7,'answer','4'),
    jsonb_build_object('number',8,'answer','3'),
    jsonb_build_object('number',9,'answer','5'),
    jsonb_build_object('number',10,'answer','5'),
    jsonb_build_object('number',11,'answer','3'),
    jsonb_build_object('number',12,'answer','4'),
    jsonb_build_object('number',13,'answer','3'),
    jsonb_build_object('number',14,'answer','4'),
    jsonb_build_object('number',15,'answer','4'),
    jsonb_build_object('number',16,'answer','5'),
    jsonb_build_object('number',17,'answer','1'),
    jsonb_build_object('number',18,'answer','4'),
    jsonb_build_object('number',19,'answer','3'),
    jsonb_build_object('number',20,'answer','4'),
    jsonb_build_object('number',21,'answer','3'),
    jsonb_build_object('number',22,'answer','5'),
    jsonb_build_object('number',23,'answer','2'),
    jsonb_build_object('number',24,'answer','5'),
    jsonb_build_object('number',25,'answer','1'),
    jsonb_build_object('number',26,'answer','4'),
    jsonb_build_object('number',27,'answer','3'),
    jsonb_build_object('number',28,'answer','3'),
    jsonb_build_object('number',29,'answer','2'),
    jsonb_build_object('number',30,'answer','5'),
    jsonb_build_object('number',31,'answer','1'),
    jsonb_build_object('number',32,'answer','3'),
    jsonb_build_object('number',33,'answer','2'),
    jsonb_build_object('number',34,'answer','5'),
    jsonb_build_object('number',35,'answer','3'),
    jsonb_build_object('number',36,'answer','3'),
    jsonb_build_object('number',37,'answer','2'),
    jsonb_build_object('number',38,'answer','3'),
    jsonb_build_object('number',39,'answer','4'),
    jsonb_build_object('number',40,'answer','1'),
    jsonb_build_object('number',41,'answer','5'),
    jsonb_build_object('number',42,'answer','2'),
    jsonb_build_object('number',43,'answer','4'),
    jsonb_build_object('number',44,'answer','1'),
    jsonb_build_object('number',45,'answer','3'),
    jsonb_build_object('number',46,'answer','3'),
    jsonb_build_object('number',47,'answer','3'),
    jsonb_build_object('number',48,'answer','3'),
    jsonb_build_object('number',49,'answer','3'),
    jsonb_build_object('number',50,'answer','4'),
    jsonb_build_object('number',51,'answer','2'),
    jsonb_build_object('number',52,'answer','4'),
    jsonb_build_object('number',53,'answer','2'),
    jsonb_build_object('number',54,'answer','1'),
    jsonb_build_object('number',55,'answer','4'),
    jsonb_build_object('number',56,'answer','4'),
    jsonb_build_object('number',57,'answer','4'),
    jsonb_build_object('number',58,'answer','4'),
    jsonb_build_object('number',59,'answer','4'),
    jsonb_build_object('number',60,'answer','4'),
    jsonb_build_object('number',61,'answer','4'),
    jsonb_build_object('number',62,'answer','3'),
    jsonb_build_object('number',63,'answer','2'),
    jsonb_build_object('number',64,'answer','3'),
    jsonb_build_object('number',65,'answer','5'),
    jsonb_build_object('number',66,'answer','4'),
    jsonb_build_object('number',67,'answer','3'),
    jsonb_build_object('number',68,'answer','4'),
    jsonb_build_object('number',69,'answer','5'),
    jsonb_build_object('number',70,'answer','5')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('현재완료 Step 2', '현재완료', q, a, 'problem', 'interactive');
END $$;
