DO $$
DECLARE
  v_questions jsonb;
  v_answer_key jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = 'something+형용사 Step3';

  v_questions := jsonb_build_array(
    jsonb_build_object('number',1, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n시장에서 재미있는 것 좀 찾았니?\n→ Did you find ___ at the market?', 'answer',E'anything interesting', 'acceptedAnswers',jsonb_build_array(E'anything interesting')),
    jsonb_build_object('number',2, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n나 심심해, 신나는 것 좀 하자.\n→ I''m bored. Let''s do ___.', 'answer',E'something exciting', 'acceptedAnswers',jsonb_build_array(E'something exciting')),
    jsonb_build_object('number',3, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\nSara는 주말마다 특별하게 할 일이 없다.\n→ Sara has ___ to do every weekend.', 'answer',E'nothing special', 'acceptedAnswers',jsonb_build_array(E'nothing special')),
    jsonb_build_object('number',4, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n나는 엄마를 위해 좋은 것을 샀다.\n→ I bought ___ for my mother.', 'answer',E'something special', 'acceptedAnswers',jsonb_build_array(E'something special', E'something delicious')),
    jsonb_build_object('number',5, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n환자에게서 특이한 것이 발견되지 않았다.\n→ There was ___ in the patient.', 'answer',E'nothing wrong', 'acceptedAnswers',jsonb_build_array(E'nothing wrong', E'nothing unusual')),
    jsonb_build_object('number',6, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\nTV에 뭔가 잘못되었다.\n→ There''s ___ on the TV.', 'answer',E'something wrong', 'acceptedAnswers',jsonb_build_array(E'something wrong')),
    jsonb_build_object('number',7, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n나는 목마르다. 차가운 것을 마시고 싶다.\n→ I am thirsty. I want to drink ___.', 'answer',E'something cold', 'acceptedAnswers',jsonb_build_array(E'something cold')),
    jsonb_build_object('number',8, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 빈칸에 쓰시오.\n\n<보기> something / anything / nothing / interesting / exciting / special / wrong / delicious\n\n선생님이 학생들에게 새로운 누군가를 소개하고 있다.\n→ The teacher is introducing ___ to his students.', 'answer',E'someone new', 'acceptedAnswers',jsonb_build_array(E'someone new', E'somebody new')),
    jsonb_build_object('number',9, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: Did you find ___ at the bookstore? (anything, interesting)\nB: No, there was ___ there. (special, nothing)\nA: You always go to the same bookstore.\nB: I know. I should find ___ next time. (good, something)', 'answer',E'anything interesting / nothing special / something good', 'acceptedAnswers',jsonb_build_array(E'anything interesting / nothing special / something good')),
    jsonb_build_object('number',10, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: Tomorrow is Jinho''s birthday. Let''s get (1) ___ for him. (nice)\nB: Sure. Did you find (2) ___? (good)\nA: No, there is (3) ___ here. (special) Let''s go to another shop.', 'answer',E'(1) something nice (2) anything good (3) nothing special', 'acceptedAnswers',jsonb_build_array(E'(1) something nice (2) anything good (3) nothing special', E'something nice / anything good / nothing special')),
    jsonb_build_object('number',11, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: Do you have any good ideas?\nB: No, ___. (nothing, special)', 'answer',E'nothing special', 'acceptedAnswers',jsonb_build_array(E'nothing special')),
    jsonb_build_object('number',12, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: What''s wrong with you?\nB: I''m so thirsty. I need ___ to drink. (something, cold)', 'answer',E'something cold', 'acceptedAnswers',jsonb_build_array(E'something cold')),
    jsonb_build_object('number',13, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: Would you like some hot tea?\nB: It''s very hot today. I don''t want to have ___. (anything, hot) I want something cold.', 'answer',E'anything hot', 'acceptedAnswers',jsonb_build_array(E'anything hot')),
    jsonb_build_object('number',14, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: I''m bored. Let''s do ___. (exciting, something)\nB: OK. How about going to a rock concert?', 'answer',E'something exciting', 'acceptedAnswers',jsonb_build_array(E'something exciting')),
    jsonb_build_object('number',15, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nKevin: Sumi, thank you for coming by. Would you like ___ to drink? (something, cold)\nSumi: Sure, I want some cold water.', 'answer',E'something cold', 'acceptedAnswers',jsonb_build_array(E'something cold')),
    jsonb_build_object('number',16, 'type','subjective', 'question',E'다음 대화의 빈칸에 괄호 안의 단어를 사용하여 알맞은 말을 쓰시오.\n\nA: What would you like to drink?\nB: I am hot. I would like to drink ___. (something, cold)', 'answer',E'something cold', 'acceptedAnswers',jsonb_build_array(E'something cold')),
    jsonb_build_object('number',17, 'type','subjective', 'question',E'다음 <예시>를 참고하여 괄호 안의 어구를 <보기>의 단어를 사용하여 다시 쓰시오.\n\n<예시> I haven''t done a wrong thing since then.\n→ I haven''t done anything wrong since then.\n\n<보기> someone / something / nothing / somewhere / anything\n\nI once met (a famous person) at the café.\n→ I once met ___ at the café.', 'answer',E'someone famous', 'acceptedAnswers',jsonb_build_array(E'someone famous', E'somebody famous')),
    jsonb_build_object('number',18, 'type','subjective', 'question',E'다음 <예시>를 참고하여 괄호 안의 어구를 <보기>의 단어를 사용하여 다시 쓰시오.\n\n<예시> I haven''t done a wrong thing since then.\n→ I haven''t done anything wrong since then.\n\n<보기> someone / something / nothing / somewhere / anything\n\nI''ve got (a different thing) to tell you about the trip.\n→ I''ve got ___ to tell you about the trip.', 'answer',E'something different', 'acceptedAnswers',jsonb_build_array(E'something different')),
    jsonb_build_object('number',19, 'type','subjective', 'question',E'다음 <예시>를 참고하여 괄호 안의 어구를 <보기>의 단어를 사용하여 다시 쓰시오.\n\n<예시> I haven''t done a wrong thing since then.\n→ I haven''t done anything wrong since then.\n\n<보기> someone / something / nothing / somewhere / anything\n\n(No exciting things) ever happen in this small town.\n→ ___ ever happens in this small town.', 'answer',E'Nothing exciting', 'acceptedAnswers',jsonb_build_array(E'Nothing exciting', E'nothing exciting')),
    jsonb_build_object('number',20, 'type','subjective', 'question',E'다음 <예시>를 참고하여 괄호 안의 어구를 <보기>의 단어를 사용하여 다시 쓰시오.\n\n<예시> I haven''t done a wrong thing since then.\n→ I haven''t done anything wrong since then.\n\n<보기> someone / something / nothing / somewhere / anything\n\nI''d like to buy (a nice thing) for my sister''s graduation.\n→ I''d like to buy ___ for my sister''s graduation.', 'answer',E'something nice', 'acceptedAnswers',jsonb_build_array(E'something nice')),
    jsonb_build_object('number',21, 'type','subjective', 'question',E'다음 <예시>를 참고하여 괄호 안의 어구를 <보기>의 단어를 사용하여 다시 쓰시오.\n\n<예시> I haven''t done a wrong thing since then.\n→ I haven''t done anything wrong since then.\n\n<보기> someone / something / nothing / somewhere / anything\n\nLet''s go (to another place) more peaceful, shall we?\n→ Let''s go ___ more peaceful, shall we?', 'answer',E'somewhere', 'acceptedAnswers',jsonb_build_array(E'somewhere', E'somewhere more peaceful')),
    jsonb_build_object('number',22, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\n나는 흥미진진하게 읽을거리가 필요하다.\n→ I need ___.', 'answer',E'something exciting to read', 'acceptedAnswers',jsonb_build_array(E'something exciting to read', E'something exciting to read.')),
    jsonb_build_object('number',23, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\n나는 모든 사람들에게 중요한 무엇인가를 말할 것이 있다.\n→ I have ___.', 'answer',E'something important to tell everyone', 'acceptedAnswers',jsonb_build_array(E'something important to tell everyone', E'something important to tell everyone.')),
    jsonb_build_object('number',24, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\nJessica는 비싼 것을 살 수 없었다.', 'answer',E'Jessica couldn''t buy anything expensive.', 'acceptedAnswers',jsonb_build_array(E'Jessica couldn''t buy anything expensive.', E'Jessica couldn''t buy anything expensive', E'Jessica could not buy anything expensive.', E'Jessica could not buy anything expensive')),
    jsonb_build_object('number',25, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\nSmith 씨가 너에게 중요한 것을 말할 것이다.', 'answer',E'Mr. Smith will tell you something important.', 'acceptedAnswers',jsonb_build_array(E'Mr. Smith will tell you something important.', E'Mr. Smith will tell you something important')),
    jsonb_build_object('number',26, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\nTV에 재미있는 것이 아무것도 없네요.', 'answer',E'There is nothing interesting on TV.', 'acceptedAnswers',jsonb_build_array(E'There is nothing interesting on TV.', E'There is nothing interesting on TV')),
    jsonb_build_object('number',27, 'type','subjective', 'question',E'다음 우리말과 일치하도록 <보기>에서 알맞은 단어를 골라 바르게 배열하시오. (단, 중복 사용 가능)\n\n<보기> for / important / tell / read / exciting / everyone / to / something / anything / nothing / interesting / on\n\n그녀는 항상 새로운 무언가를 배우려고 노력한다.', 'answer',E'She always tries to learn something new.', 'acceptedAnswers',jsonb_build_array(E'She always tries to learn something new.', E'She always tries to learn something new')),
    jsonb_build_object('number',28, 'type','subjective', 'question',E'다음 우리말과 일치하도록 괄호 안의 단어를 바르게 배열하시오.\n\n우리는 특별한 것을 해보고 싶다.\ndo, special, we, something, to, want', 'answer',E'We want to do something special.', 'acceptedAnswers',jsonb_build_array(E'We want to do something special.', E'We want to do something special')),
    jsonb_build_object('number',29, 'type','subjective', 'question',E'다음 우리말과 일치하도록 괄호 안의 단어를 바르게 배열하시오.\n\n창의력을 개발하기 위해 새로운 어떤 것을 배우세요.\ncreativity, learn, new, to, develop, something', 'answer',E'Learn something new to develop creativity.', 'acceptedAnswers',jsonb_build_array(E'Learn something new to develop creativity.', E'Learn something new to develop creativity')),
    jsonb_build_object('number',30, 'type','subjective', 'question',E'다음 우리말과 일치하도록 괄호 안의 단어를 바르게 배열하시오.\n\n나는 그녀의 생일에 특별한 무엇인가를 하고 싶다.\nwant, special, something, do, I, to\n→ ___ for her birthday.', 'answer',E'I want to do something special for her birthday.', 'acceptedAnswers',jsonb_build_array(E'I want to do something special for her birthday.', E'I want to do something special for her birthday', E'I want to do something special')),
    jsonb_build_object('number',31, 'type','subjective', 'question',E'다음 우리말과 일치하도록 괄호 안의 단어를 바르게 배열하시오.\n\n그의 제안에는 새로운 어떤 것도 없다.\nproposal, nothing, there, about, new, is, his', 'answer',E'There is nothing new about his proposal.', 'acceptedAnswers',jsonb_build_array(E'There is nothing new about his proposal.', E'There is nothing new about his proposal')),
    jsonb_build_object('number',32, 'type','subjective', 'question',E'다음 우리말과 일치하도록 괄호 안의 단어를 바르게 배열하시오.\n\nEdgar Degas는 항상 움직이는 것을 그리기를 원했다.\ndraw, want, something, to, move\n→ Edgar Degas always ___.', 'answer',E'wanted to draw something moving.', 'acceptedAnswers',jsonb_build_array(E'wanted to draw something moving.', E'wanted to draw something moving')),
    jsonb_build_object('number',33, 'type','subjective', 'question',E'다음 문장에서 어법상 어색한 부분을 찾아 고치고 완전한 문장으로 다시 쓰시오.\n\nThere is special nothing about the new menu.', 'answer',E'There is nothing special about the new menu.', 'acceptedAnswers',jsonb_build_array(E'There is nothing special about the new menu.', E'There is nothing special about the new menu')),
    jsonb_build_object('number',34, 'type','subjective', 'question',E'다음 문장에서 어법상 어색한 부분을 찾아 고치고 완전한 문장으로 다시 쓰시오.\n\nThere is wrong something with my laptop.', 'answer',E'There is something wrong with my laptop.', 'acceptedAnswers',jsonb_build_array(E'There is something wrong with my laptop.', E'There is something wrong with my laptop')),
    jsonb_build_object('number',35, 'type','subjective', 'question',E'다음 문장에서 어법상 어색한 부분을 찾아 고치고 완전한 문장으로 다시 쓰시오.\n\nStrange nothing happened to me on my way home.', 'answer',E'Nothing strange happened to me on my way home.', 'acceptedAnswers',jsonb_build_array(E'Nothing strange happened to me on my way home.', E'Nothing strange happened to me on my way home')),
    jsonb_build_object('number',36, 'type','subjective', 'question',E'다음 문장에서 어법상 어색한 부분을 찾아 고치고 완전한 문장으로 다시 쓰시오.\n\nHe enjoys doing exciting something after school every day.', 'answer',E'He enjoys doing something exciting after school every day.', 'acceptedAnswers',jsonb_build_array(E'He enjoys doing something exciting after school every day.', E'He enjoys doing something exciting after school every day')),
    jsonb_build_object('number',37, 'type','subjective', 'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. <보기>의 단어를 모두 한 번씩 사용할 것\n2. 총 7단어로 쓸 것\n<보기> would / like / something / cold / to / drink / you\n\n너 마실만한 찬 것 좀 줄까?', 'answer',E'Would you like something cold to drink?', 'acceptedAnswers',jsonb_build_array(E'Would you like something cold to drink?', E'Would you like something cold to drink')),
    jsonb_build_object('number',38, 'type','subjective', 'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. <보기>의 단어를 모두 사용할 것 (중복 사용 불가, 형태 변형 가능)\n2. 5~6단어로 쓸 것\n<보기> special / about / nothing / there / is\n\n그에게는 남다른 점이 없어.', 'answer',E'There is nothing special about him.', 'acceptedAnswers',jsonb_build_array(E'There is nothing special about him.', E'There is nothing special about him')),
    jsonb_build_object('number',39, 'type','subjective', 'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. something을 반드시 사용할 것\n2. 주어진 <Rule>에 맞게 영작할 것\n<Rule> Adjectives come immediately after nouns ending with -body, -thing, or -where.\n\n(1) 나는 무언가 마실 뜨거운 것이 필요하다.\n\n(2) 그들은 한국에 머무는 동안 붐비는 어떤 곳을 방문하고 싶어 한다.\n→ ___ while they stay in Korea.', 'answer',E'(1) I need something hot to drink. (2) They want to visit somewhere crowded', 'acceptedAnswers',jsonb_build_array(E'(1) I need something hot to drink. (2) They want to visit somewhere crowded', E'(1) I need something hot to drink. (2) They want to visit somewhere crowded while they stay in Korea.', E'(1) I need something hot to drink. (2) They want to visit somewhere crowded.')),
    jsonb_build_object('number',40, 'type','subjective', 'question',E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. 주어진 해석에 맞는 시제로 영작할 것\n2. <보기>의 단어를 모두 한 번씩 사용할 것\n3. 필요시 단어를 변형할 것, 추가단어 없음\n<보기> draw / want / something / to / move\n\n나는 항상 움직이는 무언가를 그리고 싶었다.\n→ I always ___.', 'answer',E'wanted to draw something moving.', 'acceptedAnswers',jsonb_build_array(E'wanted to draw something moving.', E'wanted to draw something moving'))
  );

  v_answer_key := jsonb_build_array(
    jsonb_build_object('number',1, 'answer',E'anything interesting'),
    jsonb_build_object('number',2, 'answer',E'something exciting'),
    jsonb_build_object('number',3, 'answer',E'nothing special'),
    jsonb_build_object('number',4, 'answer',E'something special'),
    jsonb_build_object('number',5, 'answer',E'nothing wrong'),
    jsonb_build_object('number',6, 'answer',E'something wrong'),
    jsonb_build_object('number',7, 'answer',E'something cold'),
    jsonb_build_object('number',8, 'answer',E'someone new'),
    jsonb_build_object('number',9, 'answer',E'anything interesting / nothing special / something good'),
    jsonb_build_object('number',10, 'answer',E'(1) something nice (2) anything good (3) nothing special'),
    jsonb_build_object('number',11, 'answer',E'nothing special'),
    jsonb_build_object('number',12, 'answer',E'something cold'),
    jsonb_build_object('number',13, 'answer',E'anything hot'),
    jsonb_build_object('number',14, 'answer',E'something exciting'),
    jsonb_build_object('number',15, 'answer',E'something cold'),
    jsonb_build_object('number',16, 'answer',E'something cold'),
    jsonb_build_object('number',17, 'answer',E'someone famous'),
    jsonb_build_object('number',18, 'answer',E'something different'),
    jsonb_build_object('number',19, 'answer',E'Nothing exciting'),
    jsonb_build_object('number',20, 'answer',E'something nice'),
    jsonb_build_object('number',21, 'answer',E'somewhere'),
    jsonb_build_object('number',22, 'answer',E'something exciting to read'),
    jsonb_build_object('number',23, 'answer',E'something important to tell everyone'),
    jsonb_build_object('number',24, 'answer',E'Jessica couldn''t buy anything expensive.'),
    jsonb_build_object('number',25, 'answer',E'Mr. Smith will tell you something important.'),
    jsonb_build_object('number',26, 'answer',E'There is nothing interesting on TV.'),
    jsonb_build_object('number',27, 'answer',E'She always tries to learn something new.'),
    jsonb_build_object('number',28, 'answer',E'We want to do something special.'),
    jsonb_build_object('number',29, 'answer',E'Learn something new to develop creativity.'),
    jsonb_build_object('number',30, 'answer',E'I want to do something special for her birthday.'),
    jsonb_build_object('number',31, 'answer',E'There is nothing new about his proposal.'),
    jsonb_build_object('number',32, 'answer',E'wanted to draw something moving.'),
    jsonb_build_object('number',33, 'answer',E'There is nothing special about the new menu.'),
    jsonb_build_object('number',34, 'answer',E'There is something wrong with my laptop.'),
    jsonb_build_object('number',35, 'answer',E'Nothing strange happened to me on my way home.'),
    jsonb_build_object('number',36, 'answer',E'He enjoys doing something exciting after school every day.'),
    jsonb_build_object('number',37, 'answer',E'Would you like something cold to drink?'),
    jsonb_build_object('number',38, 'answer',E'There is nothing special about him.'),
    jsonb_build_object('number',39, 'answer',E'(1) I need something hot to drink. (2) They want to visit somewhere crowded'),
    jsonb_build_object('number',40, 'answer',E'wanted to draw something moving.')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('something+형용사 Step3', 'something+형용사', v_questions, v_answer_key, 'problem', 'interactive');
END;
$$;
