DO $$
DECLARE
  v_questions jsonb;
  v_answer_key jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '현재완료진행 Step1';

  v_questions := jsonb_build_array(
    jsonb_build_object('number', 1, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nI ___ (practice) the piano for two hours.', 'answer', E'have been practicing', 'similar_answers', jsonb_build_array(E'have been practicing', E'have been practising')),
    jsonb_build_object('number', 2, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nHe ___ (review) vocabulary for the exam since this morning.', 'answer', E'has been reviewing', 'similar_answers', jsonb_build_array(E'has been reviewing')),
    jsonb_build_object('number', 3, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nIt ___ (rain) since yesterday afternoon.', 'answer', E'has been raining', 'similar_answers', jsonb_build_array(E'has been raining')),
    jsonb_build_object('number', 4, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nShe ___ (not, sleep) well since she started the new job.', 'answer', E'has not been sleeping', 'similar_answers', jsonb_build_array(E'has not been sleeping', E'hasn''t been sleeping')),
    jsonb_build_object('number', 5, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nThe children ___ (argue) about what to watch for an hour.', 'answer', E'have been arguing', 'similar_answers', jsonb_build_array(E'have been arguing')),
    jsonb_build_object('number', 6, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nMy dad ___ (fix) the roof since early morning.', 'answer', E'has been fixing', 'similar_answers', jsonb_build_array(E'has been fixing')),
    jsonb_build_object('number', 7, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nWe ___ (try) to reach the customer service team for two days.', 'answer', E'have been trying', 'similar_answers', jsonb_build_array(E'have been trying')),
    jsonb_build_object('number', 8, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nHallyu ___ (spread) to other continents in recent years.', 'answer', E'has been spreading', 'similar_answers', jsonb_build_array(E'has been spreading')),
    jsonb_build_object('number', 9, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nSome scientists ___ (ask) themselves this question for decades.', 'answer', E'have been asking', 'similar_answers', jsonb_build_array(E'have been asking')),
    jsonb_build_object('number', 10, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행 시제로 바꾸어 빈칸을 완성하시오.\n\nI ___ (use) reusable bags to reduce plastic waste since last year.', 'answer', E'have been using', 'similar_answers', jsonb_build_array(E'have been using')),
    jsonb_build_object('number', 11, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nI ___ to school every day to save energy since last year.', 'answer', E'have been walking', 'similar_answers', jsonb_build_array(E'have been walking')),
    jsonb_build_object('number', 12, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nShe ___ stamps from different countries for three years.', 'answer', E'has been collecting', 'similar_answers', jsonb_build_array(E'has been collecting')),
    jsonb_build_object('number', 13, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nThey ___ around Southeast Asia for the past two months.', 'answer', E'have been traveling', 'similar_answers', jsonb_build_array(E'have been traveling', E'have been travelling')),
    jsonb_build_object('number', 14, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nMy uncle ___ his old motorcycle since last weekend.', 'answer', E'has been repairing', 'similar_answers', jsonb_build_array(E'has been repairing')),
    jsonb_build_object('number', 15, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nAlice and I ___ a surprise party for Jisu since last week.', 'answer', E'have been planning', 'similar_answers', jsonb_build_array(E'have been planning')),
    jsonb_build_object('number', 16, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nMy mom ___ at the community center since 2018.', 'answer', E'has been working', 'similar_answers', jsonb_build_array(E'has been working')),
    jsonb_build_object('number', 17, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nJunho ___ for the science olympiad since the beginning of the semester.', 'answer', E'has been studying', 'similar_answers', jsonb_build_array(E'has been studying')),
    jsonb_build_object('number', 18, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nIt ___ heavily since yesterday morning and the streets are flooded.', 'answer', E'has been raining', 'similar_answers', jsonb_build_array(E'has been raining')),
    jsonb_build_object('number', 19, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nOur school ___ its founding anniversary for over fifty years.', 'answer', E'has been celebrating', 'similar_answers', jsonb_build_array(E'has been celebrating')),
    jsonb_build_object('number', 20, 'type', 'subjective', 'question', E'다음 <보기>에서 알맞은 동사를 골라 현재완료진행형으로 바꾸어 빈칸을 채우시오.\n\n<보기> walk / collect / travel / repair / plan / work / study / rain / celebrate / talk\n\nHe ___ on the phone for two hours and still hasn''t finished.', 'answer', E'has been talking', 'similar_answers', jsonb_build_array(E'has been talking')),
    jsonb_build_object('number', 21, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nI ___ (learn) Spanish ___ three years.', 'answer', E'have been learning / for', 'similar_answers', jsonb_build_array(E'have been learning / for', E'have been learning, for')),
    jsonb_build_object('number', 22, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nShe ___ (live) in this town ___ she was born.', 'answer', E'has been living / since', 'similar_answers', jsonb_build_array(E'has been living / since', E'has been living, since')),
    jsonb_build_object('number', 23, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nMinho ___ (wait) for the bus ___ half an hour.', 'answer', E'has been waiting / for', 'similar_answers', jsonb_build_array(E'has been waiting / for', E'has been waiting, for')),
    jsonb_build_object('number', 24, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nI ___ (do) my homework ___ 4 o''clock this afternoon.', 'answer', E'have been doing / since', 'similar_answers', jsonb_build_array(E'have been doing / since', E'have been doing, since')),
    jsonb_build_object('number', 25, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nThey ___ (build) the new library ___ last spring.', 'answer', E'have been building / since', 'similar_answers', jsonb_build_array(E'have been building / since', E'have been building, since')),
    jsonb_build_object('number', 26, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nMy little sister ___ (watch) cartoons ___ three hours.', 'answer', E'has been watching / for', 'similar_answers', jsonb_build_array(E'has been watching / for', E'has been watching, for')),
    jsonb_build_object('number', 27, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nShe ___ (collect) vintage postcards ___ she was in middle school.', 'answer', E'has been collecting / since', 'similar_answers', jsonb_build_array(E'has been collecting / since', E'has been collecting, since')),
    jsonb_build_object('number', 28, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nThe players ___ (run) ___ one hour without a break.', 'answer', E'have been running / for', 'similar_answers', jsonb_build_array(E'have been running / for', E'have been running, for')),
    jsonb_build_object('number', 29, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nWomen ___ (wear) makeup ___ ancient times.', 'answer', E'have been wearing / since', 'similar_answers', jsonb_build_array(E'have been wearing / since', E'have been wearing, since')),
    jsonb_build_object('number', 30, 'type', 'subjective', 'question', E'다음 괄호 안의 동사를 현재완료진행형으로 바꾸고, for 또는 since를 골라 빈칸을 완성하시오.\n\n<보기> They have been reading the book for two hours.\n\nJack ___ (wear) glasses ___ he was in fifth grade.', 'answer', E'has been wearing / since', 'similar_answers', jsonb_build_array(E'has been wearing / since', E'has been wearing, since')),
    jsonb_build_object('number', 31, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nMy sister has been practicing taekwondo (for / since) she was six years old.', 'answer', E'since', 'similar_answers', jsonb_build_array(E'since')),
    jsonb_build_object('number', 32, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nIt has been snowing (for / since) about four hours now.', 'answer', E'for', 'similar_answers', jsonb_build_array(E'for')),
    jsonb_build_object('number', 33, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nHer grandparents have been living in this village (for / since) forty years.', 'answer', E'for', 'similar_answers', jsonb_build_array(E'for')),
    jsonb_build_object('number', 34, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nWhat have you been doing (for / since) breakfast?', 'answer', E'since', 'similar_answers', jsonb_build_array(E'since')),
    jsonb_build_object('number', 35, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nHe has been explaining the same concept (for / since) the last class.', 'answer', E'since', 'similar_answers', jsonb_build_array(E'since')),
    jsonb_build_object('number', 36, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI have been taking swimming lessons (for / since) six months.', 'answer', E'for', 'similar_answers', jsonb_build_array(E'for')),
    jsonb_build_object('number', 37, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nTom has not been eating junk food (for / since) he turned 15.', 'answer', E'since', 'similar_answers', jsonb_build_array(E'since')),
    jsonb_build_object('number', 38, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nShe has been cooking dinner (for / since) she arrived home from work.', 'answer', E'since', 'similar_answers', jsonb_build_array(E'since')),
    jsonb_build_object('number', 39, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nThe researchers have been studying this issue (for / since) many years.', 'answer', E'for', 'similar_answers', jsonb_build_array(E'for')),
    jsonb_build_object('number', 40, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nHave you been waiting here (for / since) two hours?', 'answer', E'for', 'similar_answers', jsonb_build_array(E'for')),
    jsonb_build_object('number', 41, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI (have wanted / have been wanting) to visit Japan since I was little.', 'answer', E'have wanted', 'similar_answers', jsonb_build_array(E'have wanted')),
    jsonb_build_object('number', 42, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nShe (has known / has been knowing) the truth since that day.', 'answer', E'has known', 'similar_answers', jsonb_build_array(E'has known')),
    jsonb_build_object('number', 43, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nThe children (have been playing / have played) in the backyard since eight o''clock.', 'answer', E'have been playing', 'similar_answers', jsonb_build_array(E'have been playing')),
    jsonb_build_object('number', 44, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI (have seen / have been seeing) that movie three times already.', 'answer', E'have seen', 'similar_answers', jsonb_build_array(E'have seen')),
    jsonb_build_object('number', 45, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nHe (has had / has been having) the same bicycle for five years.', 'answer', E'has had', 'similar_answers', jsonb_build_array(E'has had')),
    jsonb_build_object('number', 46, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI (have planted / have been planting) only three trees so far.', 'answer', E'have planted', 'similar_answers', jsonb_build_array(E'have planted')),
    jsonb_build_object('number', 47, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nThey (have been celebrating / have celebrated) this tradition for over 200 years.', 'answer', E'have been celebrating', 'similar_answers', jsonb_build_array(E'have been celebrating')),
    jsonb_build_object('number', 48, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nI (have known / have been knowing) him since he was a child.', 'answer', E'have known', 'similar_answers', jsonb_build_array(E'have known')),
    jsonb_build_object('number', 49, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nJudy (has had / has been having) the same piano for twenty years.', 'answer', E'has had', 'similar_answers', jsonb_build_array(E'has had')),
    jsonb_build_object('number', 50, 'type', 'subjective', 'question', E'다음 문장의 괄호 안에서 알맞은 것을 고르시오.\nShe (has been reading / has read) the same novel since Monday and hasn''t finished yet.', 'answer', E'has been reading', 'similar_answers', jsonb_build_array(E'has been reading')),
    jsonb_build_object('number', 51, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• Sora began to exercise at noon.\n• She is still exercising.\n→ ___ since noon.', 'answer', E'Sora has been exercising since noon.', 'similar_answers', jsonb_build_array(E'Sora has been exercising since noon.', E'Sora has been exercising since noon')),
    jsonb_build_object('number', 52, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• Jinho began sleeping 8 hours ago.\n• He is still sleeping now.\n→ ___ for 8 hours.', 'answer', E'Jinho has been sleeping for 8 hours.', 'similar_answers', jsonb_build_array(E'Jinho has been sleeping for 8 hours.', E'Jinho has been sleeping for 8 hours', E'Jinho has been sleeping for eight hours.', E'Jinho has been sleeping for eight hours')),
    jsonb_build_object('number', 53, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• He began to write a report two hours ago.\n• He is still writing it now.\n→ He ___ for two hours.', 'answer', E'has been writing a report for two hours.', 'similar_answers', jsonb_build_array(E'has been writing a report for two hours.', E'has been writing a report for two hours')),
    jsonb_build_object('number', 54, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• My brother started using the tablet two hours ago.\n• He is still using it.\n→ My brother ___ for two hours.', 'answer', E'has been using the tablet for two hours.', 'similar_answers', jsonb_build_array(E'has been using the tablet for two hours.', E'has been using the tablet for two hours')),
    jsonb_build_object('number', 55, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• It began to snow this morning.\n• It is still snowing.', 'answer', E'It has been snowing since this morning.', 'similar_answers', jsonb_build_array(E'It has been snowing since this morning.', E'It has been snowing since this morning')),
    jsonb_build_object('number', 56, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• Kevin started to play basketball two hours ago.\n• He is still playing basketball.', 'answer', E'Kevin has been playing basketball for two hours.', 'similar_answers', jsonb_build_array(E'Kevin has been playing basketball for two hours.', E'Kevin has been playing basketball for two hours')),
    jsonb_build_object('number', 57, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• I started working at this café last month.\n• I am still working there.', 'answer', E'I have been working at this café since last month.', 'similar_answers', jsonb_build_array(E'I have been working at this café since last month.', E'I have been working at this cafe since last month.', E'I have been working at this café since last month', E'I have been working at this cafe since last month')),
    jsonb_build_object('number', 58, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• Jisu uses the cell phone.\n• She got it in 2020.', 'answer', E'Jisu has been using the cell phone since 2020.', 'similar_answers', jsonb_build_array(E'Jisu has been using the cell phone since 2020.', E'Jisu has been using the cell phone since 2020')),
    jsonb_build_object('number', 59, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• She started to read your book yesterday.\n• She''s still reading it.', 'answer', E'She has been reading your book since yesterday.', 'similar_answers', jsonb_build_array(E'She has been reading your book since yesterday.', E'She has been reading your book since yesterday')),
    jsonb_build_object('number', 60, 'type', 'subjective', 'question', E'다음 두 문장이 같은 의미가 되도록 현재완료진행형을 사용하여 한 문장으로 쓰시오.\n\n<보기>\n• Mia started playing tennis two hours ago.\n• She is still playing tennis.\n→ Mia has been playing tennis for two hours.\n\n• My father started repairing his bike at 5 p.m.\n• He is still repairing it now.', 'answer', E'My father has been repairing his bike since 5 p.m.', 'similar_answers', jsonb_build_array(E'My father has been repairing his bike since 5 p.m.', E'My father has been repairing his bike since 5 p.m')),
    jsonb_build_object('number', 61, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\n나는 요즘 일을 열심히 해왔어요.\n[I, working, have, been, hard, recently]', 'answer', E'I have been working hard recently.', 'similar_answers', jsonb_build_array(E'I have been working hard recently.', E'I have been working hard recently')),
    jsonb_build_object('number', 62, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\n나는 오전 내내 달리고 있었어.\n[have, been, morning, I, running, all]', 'answer', E'I have been running all morning.', 'similar_answers', jsonb_build_array(E'I have been running all morning.', E'I have been running all morning')),
    jsonb_build_object('number', 63, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\nTom은 2시간 동안 TV를 보고 있다.\n[been, watching, Tom, hours, two, for, has, TV]', 'answer', E'Tom has been watching TV for two hours.', 'similar_answers', jsonb_build_array(E'Tom has been watching TV for two hours.', E'Tom has been watching TV for two hours')),
    jsonb_build_object('number', 64, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\nSusan은 7월부터 운동을 해 오고 있다.\n[exercising, July, since, has, Susan, been]', 'answer', E'Susan has been exercising since July.', 'similar_answers', jsonb_build_array(E'Susan has been exercising since July.', E'Susan has been exercising since July')),
    jsonb_build_object('number', 65, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\nJones 씨는 1998년부터 이곳에서 계속 가르치고 계신다.\n[Mr. Jones, here, teaching, has, been, 1998, since]', 'answer', E'Mr. Jones has been teaching here since 1998.', 'similar_answers', jsonb_build_array(E'Mr. Jones has been teaching here since 1998.', E'Mr. Jones has been teaching here since 1998')),
    jsonb_build_object('number', 66, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\nJake는 일 년 동안 자전거를 타 왔다.\n[for, has, year, his, been, riding, a, Jake, bicycle]', 'answer', E'Jake has been riding his bicycle for a year.', 'similar_answers', jsonb_build_array(E'Jake has been riding his bicycle for a year.', E'Jake has been riding his bicycle for a year')),
    jsonb_build_object('number', 67, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\nEric과 Amy는 2시간째 계속 전화 통화를 하고 있다.\n[the, phone, and, been, for, talking, have, on, hours, Amy, Eric, two]', 'answer', E'Eric and Amy have been talking on the phone for two hours.', 'similar_answers', jsonb_build_array(E'Eric and Amy have been talking on the phone for two hours.', E'Eric and Amy have been talking on the phone for two hours')),
    jsonb_build_object('number', 68, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\n저는 한국의 고등학교에서 2년 동안 영어를 가르쳐 오고 있습니다.\n[English, at, for, high, teaching, have, years, a Korean, been, school, I, two]', 'answer', E'I have been teaching English at a Korean high school for two years.', 'similar_answers', jsonb_build_array(E'I have been teaching English at a Korean high school for two years.', E'I have been teaching English at a Korean high school for two years')),
    jsonb_build_object('number', 69, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\n너의 가족이 얼마나 오래 너의 집에서 살고 있는 중이니?\n[has, house, been, your, family, living, how, your, in, long]', 'answer', E'How long has your family been living in your house?', 'similar_answers', jsonb_build_array(E'How long has your family been living in your house?', E'How long has your family been living in your house')),
    jsonb_build_object('number', 70, 'type', 'subjective', 'question', E'다음 우리말과 같은 뜻이 되도록 주어진 단어를 바르게 배열하시오.\n\n너는 얼마나 오랫동안 숙제를 하고 있니?\n[have, homework, doing, been, long, you, how]', 'answer', E'How long have you been doing homework?', 'similar_answers', jsonb_build_array(E'How long have you been doing homework?', E'How long have you been doing homework')),
    jsonb_build_object('number', 71, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nMy brother has been playing the computer game since hours.', 'answer', E'since hours → for hours', 'similar_answers', jsonb_build_array(E'since hours → for hours', E'since → for', E'for hours')),
    jsonb_build_object('number', 72, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nI have been read this novel since yesterday.', 'answer', E'have been read → have been reading', 'similar_answers', jsonb_build_array(E'have been read → have been reading', E'read → reading', E'have been reading')),
    jsonb_build_object('number', 73, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nMary has being cooking in the kitchen for 50 minutes.', 'answer', E'has being → has been', 'similar_answers', jsonb_build_array(E'has being → has been', E'being → been', E'has been')),
    jsonb_build_object('number', 74, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nRon and Emma have been knowing each other for 5 years.', 'answer', E'have been knowing → have known', 'similar_answers', jsonb_build_array(E'have been knowing → have known', E'been knowing → known', E'have known')),
    jsonb_build_object('number', 75, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\n\nJane and Kate has been dancing for hours.', 'answer', E'has been → have been', 'similar_answers', jsonb_build_array(E'has been → have been', E'has → have', E'have been')),
    jsonb_build_object('number', 76, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\nHow long have you living in this neighborhood?', 'answer', E'have you living → have you been living', 'similar_answers', jsonb_build_array(E'have you living → have you been living', E'living → been living', E'have you been living')),
    jsonb_build_object('number', 77, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\nNora has been worked on the project since this morning.', 'answer', E'has been worked → has been working', 'similar_answers', jsonb_build_array(E'has been worked → has been working', E'worked → working', E'has been working')),
    jsonb_build_object('number', 78, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\nSora has been using the cell phone in 2019.', 'answer', E'in 2019 → since 2019', 'similar_answers', jsonb_build_array(E'in 2019 → since 2019', E'in → since', E'since 2019')),
    jsonb_build_object('number', 79, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\nI have been wanting to visit the art museum for a long time.', 'answer', E'have been wanting → have wanted', 'similar_answers', jsonb_build_array(E'have been wanting → have wanted', E'been wanting → wanted', E'have wanted')),
    jsonb_build_object('number', 80, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고치시오.\nJenny is preparing for the final exam for 6 months.', 'answer', E'is preparing → has been preparing', 'similar_answers', jsonb_build_array(E'is preparing → has been preparing', E'is → has been', E'has been preparing'))
  );

  v_answer_key := jsonb_build_array(
    jsonb_build_object('number',1, 'answer',E'have been practicing'),
    jsonb_build_object('number',2, 'answer',E'has been reviewing'),
    jsonb_build_object('number',3, 'answer',E'has been raining'),
    jsonb_build_object('number',4, 'answer',E'has not been sleeping'),
    jsonb_build_object('number',5, 'answer',E'have been arguing'),
    jsonb_build_object('number',6, 'answer',E'has been fixing'),
    jsonb_build_object('number',7, 'answer',E'have been trying'),
    jsonb_build_object('number',8, 'answer',E'has been spreading'),
    jsonb_build_object('number',9, 'answer',E'have been asking'),
    jsonb_build_object('number',10, 'answer',E'have been using'),
    jsonb_build_object('number',11, 'answer',E'have been walking'),
    jsonb_build_object('number',12, 'answer',E'has been collecting'),
    jsonb_build_object('number',13, 'answer',E'have been traveling'),
    jsonb_build_object('number',14, 'answer',E'has been repairing'),
    jsonb_build_object('number',15, 'answer',E'have been planning'),
    jsonb_build_object('number',16, 'answer',E'has been working'),
    jsonb_build_object('number',17, 'answer',E'has been studying'),
    jsonb_build_object('number',18, 'answer',E'has been raining'),
    jsonb_build_object('number',19, 'answer',E'has been celebrating'),
    jsonb_build_object('number',20, 'answer',E'has been talking'),
    jsonb_build_object('number',21, 'answer',E'have been learning / for'),
    jsonb_build_object('number',22, 'answer',E'has been living / since'),
    jsonb_build_object('number',23, 'answer',E'has been waiting / for'),
    jsonb_build_object('number',24, 'answer',E'have been doing / since'),
    jsonb_build_object('number',25, 'answer',E'have been building / since'),
    jsonb_build_object('number',26, 'answer',E'has been watching / for'),
    jsonb_build_object('number',27, 'answer',E'has been collecting / since'),
    jsonb_build_object('number',28, 'answer',E'have been running / for'),
    jsonb_build_object('number',29, 'answer',E'have been wearing / since'),
    jsonb_build_object('number',30, 'answer',E'has been wearing / since'),
    jsonb_build_object('number',31, 'answer',E'since'),
    jsonb_build_object('number',32, 'answer',E'for'),
    jsonb_build_object('number',33, 'answer',E'for'),
    jsonb_build_object('number',34, 'answer',E'since'),
    jsonb_build_object('number',35, 'answer',E'since'),
    jsonb_build_object('number',36, 'answer',E'for'),
    jsonb_build_object('number',37, 'answer',E'since'),
    jsonb_build_object('number',38, 'answer',E'since'),
    jsonb_build_object('number',39, 'answer',E'for'),
    jsonb_build_object('number',40, 'answer',E'for'),
    jsonb_build_object('number',41, 'answer',E'have wanted'),
    jsonb_build_object('number',42, 'answer',E'has known'),
    jsonb_build_object('number',43, 'answer',E'have been playing'),
    jsonb_build_object('number',44, 'answer',E'have seen'),
    jsonb_build_object('number',45, 'answer',E'has had'),
    jsonb_build_object('number',46, 'answer',E'have planted'),
    jsonb_build_object('number',47, 'answer',E'have been celebrating'),
    jsonb_build_object('number',48, 'answer',E'have known'),
    jsonb_build_object('number',49, 'answer',E'has had'),
    jsonb_build_object('number',50, 'answer',E'has been reading'),
    jsonb_build_object('number',51, 'answer',E'Sora has been exercising since noon.'),
    jsonb_build_object('number',52, 'answer',E'Jinho has been sleeping for 8 hours.'),
    jsonb_build_object('number',53, 'answer',E'has been writing a report for two hours.'),
    jsonb_build_object('number',54, 'answer',E'has been using the tablet for two hours.'),
    jsonb_build_object('number',55, 'answer',E'It has been snowing since this morning.'),
    jsonb_build_object('number',56, 'answer',E'Kevin has been playing basketball for two hours.'),
    jsonb_build_object('number',57, 'answer',E'I have been working at this café since last month.'),
    jsonb_build_object('number',58, 'answer',E'Jisu has been using the cell phone since 2020.'),
    jsonb_build_object('number',59, 'answer',E'She has been reading your book since yesterday.'),
    jsonb_build_object('number',60, 'answer',E'My father has been repairing his bike since 5 p.m.'),
    jsonb_build_object('number',61, 'answer',E'I have been working hard recently.'),
    jsonb_build_object('number',62, 'answer',E'I have been running all morning.'),
    jsonb_build_object('number',63, 'answer',E'Tom has been watching TV for two hours.'),
    jsonb_build_object('number',64, 'answer',E'Susan has been exercising since July.'),
    jsonb_build_object('number',65, 'answer',E'Mr. Jones has been teaching here since 1998.'),
    jsonb_build_object('number',66, 'answer',E'Jake has been riding his bicycle for a year.'),
    jsonb_build_object('number',67, 'answer',E'Eric and Amy have been talking on the phone for two hours.'),
    jsonb_build_object('number',68, 'answer',E'I have been teaching English at a Korean high school for two years.'),
    jsonb_build_object('number',69, 'answer',E'How long has your family been living in your house?'),
    jsonb_build_object('number',70, 'answer',E'How long have you been doing homework?'),
    jsonb_build_object('number',71, 'answer',E'since hours → for hours'),
    jsonb_build_object('number',72, 'answer',E'have been read → have been reading'),
    jsonb_build_object('number',73, 'answer',E'has being → has been'),
    jsonb_build_object('number',74, 'answer',E'have been knowing → have known'),
    jsonb_build_object('number',75, 'answer',E'has been → have been'),
    jsonb_build_object('number',76, 'answer',E'have you living → have you been living'),
    jsonb_build_object('number',77, 'answer',E'has been worked → has been working'),
    jsonb_build_object('number',78, 'answer',E'in 2019 → since 2019'),
    jsonb_build_object('number',79, 'answer',E'have been wanting → have wanted'),
    jsonb_build_object('number',80, 'answer',E'is preparing → has been preparing')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('현재완료진행 Step1', '현재완료진행', v_questions, v_answer_key, 'problem', 'interactive');
END;
$$;
