DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'조건문 if Step 2';

  q1 := jsonb_build_array(
jsonb_build_object('number',1,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ you eat more vegetables, you will be healthier.','type','mcq','options',jsonb_build_array(E'If',E'So',E'Until',E'Although',E'Because'),'answer',E'1','explanation',E'조건절 if + 현재시제, 주절 will — 조건의 부사절'),
jsonb_build_object('number',2,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf you do your best, __________ is possible.','type','mcq','options',jsonb_build_array(E'nothing',E'anything',E'everything',E'something',E'nowhere'),'answer',E'2','explanation',E'if 조건문 + 긍정 맥락에서 anything(무엇이든) 적절'),
jsonb_build_object('number',3,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nI''ll stay home __________ it rains tomorrow.','type','mcq','options',jsonb_build_array(E'so',E'although',E'if',E'because',E'when'),'answer',E'3','explanation',E'조건의 접속사 if'),
jsonb_build_object('number',4,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ you practice hard, you can win the contest.','type','mcq','options',jsonb_build_array(E'If',E'Unless',E'Although',E'However',E'Because'),'answer',E'1','explanation',E'조건절 if'),
jsonb_build_object('number',5,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nShe won''t pass the exam __________ she studies harder.','type','mcq','options',jsonb_build_array(E'if',E'so',E'unless',E'when',E'before'),'answer',E'3','explanation',E'unless = if ~ not, 더 열심히 공부하지 않으면'),
jsonb_build_object('number',6,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nHe will lose his job __________ he works harder.','type','mcq','options',jsonb_build_array(E'although',E'when',E'if',E'because',E'unless'),'answer',E'5','explanation',E'unless = if ~ not, 더 열심히 일하지 않으면'),
jsonb_build_object('number',7,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nYou will get a good grade __________ you do your best.','type','mcq','options',jsonb_build_array(E'if',E'as',E'before',E'because',E'although'),'answer',E'1','explanation',E'조건절 if'),
jsonb_build_object('number',8,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n__________ you don''t hurry up, we''ll miss the train.','type','mcq','options',jsonb_build_array(E'Unless',E'Although',E'If',E'Before',E'Because'),'answer',E'3','explanation',E'If you don''t hurry = 서두르지 않으면'),
jsonb_build_object('number',9,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nDo you know __________ he''s coming to the party?','type','mcq','options',jsonb_build_array(E'that',E'what',E'how',E'if',E'when'),'answer',E'4','explanation',E'if = ~인지 아닌지 (명사절 접속사)'),
jsonb_build_object('number',10,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\nI''m not sure __________ the store is open on Sundays.','type','mcq','options',jsonb_build_array(E'that',E'which',E'if',E'what',E'how'),'answer',E'3','explanation',E'if = ~인지 아닌지 (명사절), sure의 보어'),
jsonb_build_object('number',11,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf it (A)__________ tomorrow, they (B)__________ TV at home.','type','mcq','options',jsonb_build_array(E'rains — watch',E'rains — will watch',E'will rain — watch',E'will rain — will watch',E'rained — watched'),'answer',E'2','explanation',E'if절 현재시제(rains) + 주절 will(will watch)'),
jsonb_build_object('number',12,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf she (A)__________ early today, I (B)__________ to the concert with her.','type','mcq','options',jsonb_build_array(E'finish — will go',E'finishes — go',E'will finish — go',E'will finish — will go',E'finishes — will go'),'answer',E'5','explanation',E'if절 3인칭 단수 현재(finishes) + 주절 will(will go)'),
jsonb_build_object('number',13,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf you (A)__________ carefully, you (B)__________ the report well.','type','mcq','options',jsonb_build_array(E'will listen — will understand',E'listen — will understand',E'will listen — understand',E'listen — understand',E'listened — understand'),'answer',E'2','explanation',E'if절 현재(listen) + 주절 will(will understand)'),
jsonb_build_object('number',14,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A)__________ you exercise regularly, you (B)__________ healthy.','type','mcq','options',jsonb_build_array(E'If — won''t',E'Unless — will be',E'If — will not be',E'Unless — won''t be',E'Although — won''t be'),'answer',E'4','explanation',E'Unless = If not, 운동 안 하면 건강하지 않을 것'),
jsonb_build_object('number',15,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf I (A)__________ your purse, I (B)__________ let you know.','type','mcq','options',jsonb_build_array(E'will find — will',E'find — can',E'find — will',E'found — will',E'will find — can'),'answer',E'3','explanation',E'if절 현재(find) + 주절 will'),
jsonb_build_object('number',16,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf he (A)__________ here tomorrow, we (B)__________ together.','type','mcq','options',jsonb_build_array(E'will come — study',E'come — study',E'will come — will study',E'comes — studies',E'comes — will study'),'answer',E'5','explanation',E'if절 3인칭 단수 현재(comes) + 주절 will(will study)'),
jsonb_build_object('number',17,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf school (A)__________ early today, I (B)__________ to the movies.','type','mcq','options',jsonb_build_array(E'finish — will go',E'finishes — go',E'will finish — will go',E'finishes — will go',E'will finish — go'),'answer',E'4','explanation',E'if절 3인칭 단수 현재(finishes) + 주절 will(will go)'),
jsonb_build_object('number',18,'question',E'다음 빈칸에 들어갈 말로 가장 적절한 것을 고르시오.\n\n______ the weather (A)______ fine tomorrow, I (B)______ hiking with friends.','type','mcq','options',jsonb_build_array(E'If — is — will go',E'If — will be — go',E'If — is — go',E'Unless — is — won''t go',E'If — was — will go'),'answer',E'1','explanation',E'If + 현재시제(is) + 주절 will(will go)'),
jsonb_build_object('number',19,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\n(A)__________ you don''t save money, you (B)__________ buy the new phone.','type','mcq','options',jsonb_build_array(E'Unless — can',E'Although — can''t',E'Unless — can''t',E'If — can',E'If — can''t'),'answer',E'5','explanation',E'If you don''t save → can''t buy'),
jsonb_build_object('number',20,'question',E'다음 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오.\n\nIf you (A)__________ now, you (B)__________ the bus.','type','mcq','options',jsonb_build_array(E'will leave — catch',E'leave — catch',E'leave — will catch',E'leaving — will catch',E'will leave — will catch'),'answer',E'3','explanation',E'if절 현재(leave) + 주절 will(will catch)'),
jsonb_build_object('number',21,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If it will rain tomorrow, I will stay home.\n② If she won''t get up now, she''ll miss the bus.\n③ I will go to the park if it is sunny.\n④ If he will study harder, he''ll get good grades.\n⑤ If I will run, I am on time.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③ if절 현재시제(is) + 주절 will 올바름. 나머지는 if절에 will 사용 오류'),
jsonb_build_object('number',22,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If you sleep well, you felt better.\n② They will see you if they will see me.\n③ We go outside if it was sunny later.\n④ If I will see her, I''ll tell her to call you.\n⑤ I''ll tell you the news if I see you.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ if절 현재(see) + 주절 will 올바름'),
jsonb_build_object('number',23,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① Unless he is so wise, he can solve problems.\n② If you don''t start now, you will be late.\n③ If it will rain tomorrow, the event won''t be held.\n④ Unless it work properly, you should fix it.\n⑤ Unless you will exercise, you''re not healthy.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② if + 현재부정(don''t start) + will 올바름'),
jsonb_build_object('number',24,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① Water boils if the temperature reaches 100℃.\n② I will stay home if it will rain tomorrow.\n③ If you will need money, I''ll lend you some.\n④ If Minjun leave now, she won''t be late.\n⑤ I always get hungry if I will skip breakfast.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'① 일반적 사실/과학적 진리 — 현재시제+현재시제 올바름'),
jsonb_build_object('number',25,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① I can''t tell if it rains tomorrow.\n② I''ll go to the beach if I have some free time.\n③ Do you know if he comes tomorrow?\n④ We don''t know if he comes to the party or not.\n⑤ I''ll play soccer if it will be sunny.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② 조건절 if + 현재시제(have) + 주절 will 올바름. ①③④ 명사절 if에서 미래는 will 필요, ⑤ if절에 will 불가')
  );

  q2 := jsonb_build_array(
jsonb_build_object('number',26,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① Don''t judge me if you won''t know me.\n② If it be sunny tomorrow, we''ll go on a picnic.\n③ If you study hard, you passed the test.\n④ If I will get a good grade, my parents will be pleased.\n⑤ They will come to the party if the class ends early.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ if절 현재(ends) + 주절 will 올바름. ① won''t→don''t ② be→is ③ passed→will pass ④ will get→get'),
jsonb_build_object('number',27,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If it will be hot tomorrow, I usually go swimming.\n② If it snows a lot, I usually go out to make a snowman.\n③ If I will do not let her go, I will be happier.\n④ If you will stop crying, I''ll buy you ice cream.\n⑤ If the fact will be false, he will be scolded.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② 습관적 조건 — if 현재(snows)+현재(go) 올바름'),
jsonb_build_object('number',28,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If I don''t run, I will be late.\n② If he is late, he won''t played baseball.\n③ If we will take the bus, it''ll be cheaper.\n④ If it will rain tomorrow, I will stay home.\n⑤ If you save money, you buys a new computer.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'① if절 현재부정(don''t run)+주절 will 올바름. ② won''t played→won''t play ③④ if절에 will 불가 ⑤ buys→can buy'),
jsonb_build_object('number',29,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If she will want to go there, I will go, too.\n② If she wants to go there, I will go, too.\n③ We went on a picnic if it doesn''t rain tomorrow.\n④ If you go to bed late tonight, you will tired tomorrow.\n⑤ Why don''t you show her your heart if you will love her?','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② if절 현재(wants)+주절 will 올바름. ① will want→wants ③ went→will go ④ will tired→will be tired ⑤ will love→love'),
jsonb_build_object('number',30,'question',E'다음 중 어법상 옳은 문장을 고르시오.\n\n① If you will finish the homework, what do you do?\n② If you miss a class, Ms. Green will call your parents.\n③ I will tell him if he will comes back.\n④ If I will become President, I''ll work for the poor.\n⑤ If they will hear the truth, they will be amazed.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② if절 현재(miss)+주절 will 올바름. ① will finish→finish ③ will comes→comes ④ will become→become ⑤ will hear→hear'),
jsonb_build_object('number',31,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If it is fine tomorrow, we will go camping.\n② If you arrive early, you can get a good seat.\n③ He will lose his job unless he will come right now.\n④ If she takes a subway, she will be there on time.\n⑤ Unless you take some water, you will feel very thirsty.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③ unless절에 will 사용 불가 → unless he comes'),
jsonb_build_object('number',32,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If it rains tomorrow, I will stay in your castle.\n② If I see Martin, I''ll tell him.\n③ You''ll miss the train unless you walk more quickly.\n④ If he will arrive early, we''ll eat lunch together.\n⑤ Do you know if she will come?','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'④ if절에 will 불가 → arrives'),
jsonb_build_object('number',33,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① You can stay for the weekend if you like.\n② If it will be hot and sunny tomorrow, I go swimming.\n③ If it snows a lot, I go out to make a snowman.\n④ If I sell some milk, I''ll buy a chicken.\n⑤ If school finishes early, I play basketball with my friends.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② if절에 will 불가 → is'),
jsonb_build_object('number',34,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If you eat tomatoes every day, you will become healthy.\n② If she will ride a bike, it will take 15 minutes.\n③ If I finish the homework, I''ll play baseball.\n④ If you think that way, you won''t have to worry.\n⑤ If the weather is nice on Saturday, I''ll go on a picnic.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② if절에 will 불가 → rides'),
jsonb_build_object('number',35,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If it snows a lot, I usually go skiing.\n② If there is no water, I will drink juice.\n③ If we will leave now, we can catch the next train.\n④ If you don''t have lunch, you''ll feel hungry.\n⑤ If school finishes early, Jane will go to the movies.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③ if절에 will 불가 → leave'),
jsonb_build_object('number',36,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If you feel tired, take a rest.\n② Exercise if you want to be healthy.\n③ If it''s snowy outside, let''s go out and play.\n④ If you will go with us, we''ll be very happy.\n⑤ I''ll buy you a phone if you do well on the exam.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'④ if절에 will 불가 → go'),
jsonb_build_object('number',37,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If it rains tomorrow, I will stay at home.\n② Kevin will catch the train if he leaves now.\n③ If you run every day, you will become healthy.\n④ If Susan does not get up now, she will miss the bus.\n⑤ Yujin will read a book if her school will finish early today.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ if절에 will 불가 → finishes'),
jsonb_build_object('number',38,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If I don''t run, I will be late.\n② If he is late, he won''t play baseball.\n③ We go on a picnic if it doesn''t rain tomorrow.\n④ If you go to bed late tonight, you will be tired tomorrow.\n⑤ If you save money, you can buy a new computer.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'③ tomorrow가 있으므로 주절에 will 필요 → will go'),
jsonb_build_object('number',39,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If you eat tomatoes every day, you will become healthy.\n② If I finish the homework, I''ll play baseball.\n③ If you think that way, you won''t have to worry.\n④ If the weather is nice on Saturday, I''ll go on a picnic.\n⑤ Yujin will read a book at home if her school will finish early today.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ if절에 will 불가 → finishes'),
jsonb_build_object('number',40,'question',E'다음 중 어법상 <u>어색한</u> 문장을 고르시오.\n\n① If it will rain tomorrow, I will stay home.\n② If he is late, he won''t play baseball.\n③ If we take the bus, it will be cheaper.\n④ If you save money, you can buy a new computer.\n⑤ Unless you take some water, you will feel very thirsty.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'① if절에 will 불가 → rains'),
jsonb_build_object('number',41,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 내가 그 책을 다 읽으면 너에게 빌려줄게.\n\n① If I finish the book, I''ll lend it to you.\n② If I will finish the book, I''ll lend it to you.\n③ If I finish the book, I lend it to you.\n④ Unless I finish the book, I''ll lend it to you.\n⑤ If I finished the book, I''ll lend it to you.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'if절 현재(finish)+주절 will(I''ll lend) 올바름'),
jsonb_build_object('number',42,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 네가 지금 떠나지 않는다면 너는 늦을 것이다.\n\n① If you won''t leave now, you''ll be late.\n② If you will not leave now, you''ll be late.\n③ If you don''t leave now, you''ll be late.\n④ Unless you leave now, you will not be late.\n⑤ If you not leave now, you''ll be late.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'if절 현재부정(don''t leave) 올바름. ①② if절에 will 불가 ④ 의미 다름 ⑤ 문법 오류'),
jsonb_build_object('number',43,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 내일 눈이 내린다면, 나는 집에 머무를 것이다.\n\n① If it snow tomorrow, I''ll stay at home.\n② If it will snow tomorrow, I''ll stay at home.\n③ If it snows tomorrow, I''ll stay at home.\n④ Unless it snows tomorrow, I''ll stay at home.\n⑤ If it snowed tomorrow, I''ll stay at home.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'if절 3인칭 단수 현재(snows) 올바름'),
jsonb_build_object('number',44,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n네가 원하면 나는 너를 도울 수 있어.\n\n① I help you if you want.\n② I can help you if you will want.\n③ I will help you if you can want.\n④ I can help you if you want.\n⑤ I will help you if you will want.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'조건절 현재(want)+주절 can 올바름'),
jsonb_build_object('number',45,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 더 빨리 걷지 않는다면, 너는 늦을 것이다.\n\n① If you walk faster, you will be late.\n② Unless you walk faster, you will be late.\n③ Unless you walk faster, you won''t be late.\n④ If you don''t walk faster, you won''t be late.\n⑤ Unless you will walk faster, you will be late.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'Unless = If not, 더 빨리 걷지 않으면 늦을 것'),
jsonb_build_object('number',46,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 내일 비가 오지 않는다면, 우리는 소풍을 갈 것이다.\n\n① If it do not rain tomorrow, we will go on a picnic.\n② If it will not rain tomorrow, we will go on a picnic.\n③ If it does not rain tomorrow, we will go on a picnic.\n④ We go on a picnic if it do not rain tomorrow.\n⑤ We go on a picnic if it will not rain tomorrow.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'3인칭 단수 부정 does not rain 올바름'),
jsonb_build_object('number',47,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n만약 그가 아침을 먹지 않는다면, 그는 수업 중에 배가 고플 것이다.\n\n① He is hungry if he doesn''t eat breakfast.\n② He will hungry if he doesn''t eat breakfast.\n③ He will be hungry if he will not eat breakfast.\n④ He will be hungry if he doesn''t eat breakfast.\n⑤ He will be hungry unless he eats breakfast.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'4','explanation',E'if절 현재부정(doesn''t eat)+주절 will be 올바름. ⑤도 의미상 맞지만 우리말이 "먹지 않는다면"이므로 if + 부정이 직역에 더 적합'),
jsonb_build_object('number',48,'question',E'다음 우리말을 영어로 바르게 옮긴 것을 고르시오.\n\n나에게 5달러를 빌려주면, 내일 너에게 갚을게.\n\n① If you lend me five dollars, I will pay you back tomorrow.\n② If you will lend me five dollars, I will pay you back tomorrow.\n③ Unless you lend me five dollars, I will pay you back tomorrow.\n④ If you lend me five dollars, I pay you back tomorrow.\n⑤ If you lended me five dollars, I will pay you back tomorrow.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'if절 현재(lend)+주절 will 올바름. ② will lend 불가 ③ 의미 다름 ④ 주절 will 필요 ⑤ lended→lent(과거형 오류)')
  );

  q3 := jsonb_build_array(
jsonb_build_object('number',49,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① I will bring some books <u>if</u> I visit my parents.\n② <u>If</u> you don''t run, you''ll be late for school.\n③ I''d like to go with you <u>if</u> you don''t mind.\n④ <u>If</u> I pay for the ticket, will you go with me?\n⑤ I don''t know <u>if</u> he wants to go to the zoo.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ 명사절 (~인지 아닌지, know의 목적어) / 나머지 조건 부사절'),
jsonb_build_object('number',50,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① <u>If</u> you visit Paris, you can see the Eiffel Tower.\n② They want to know <u>if</u> she will finish the project.\n③ What will happen <u>if</u> I fail the test?\n④ What do I say <u>if</u> I want different tiles?\n⑤ <u>If</u> it snows tomorrow, I will stay here.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② 명사절 (~인지 아닌지, know의 목적어) / 나머지 조건 부사절'),
jsonb_build_object('number',51,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① <u>If</u> you take a taxi, you won''t be late.\n② I will go swimming <u>if</u> it is fine tomorrow.\n③ <u>If</u> you fly higher, you can see more.\n④ <u>If</u> you start now, you''ll be in time.\n⑤ I don''t know <u>if</u> she''ll come back here.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ 명사절 (~인지 아닌지) / 나머지 조건 부사절'),
jsonb_build_object('number',52,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① <u>If</u> I go shopping, I''ll buy some fruit.\n② She asked me <u>if</u> she could use my car.\n③ They will go to the sea <u>if</u> it is sunny tomorrow.\n④ You will become unhealthy <u>if</u> you don''t exercise.\n⑤ <u>If</u> you kill the dragon, you will get the dragon''s tear.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② 명사절 (~인지 아닌지, asked의 목적어) / 나머지 조건 부사절'),
jsonb_build_object('number',53,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① I''m not sure <u>if</u> it will rain tomorrow.\n② Can you tell me <u>if</u> the test is on Friday?\n③ He wanted to know <u>if</u> she had a broken bone.\n④ Do you know <u>if</u> he will have dinner with us?\n⑤ I will go out <u>if</u> it is fine tomorrow.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ 조건 부사절 (만약 ~한다면) / 나머지 명사절 (~인지 아닌지)'),
jsonb_build_object('number',54,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① <u>If</u> it''s warm tomorrow, we''ll drive in the country.\n② I shall tell him <u>if</u> he comes.\n③ I''ll go <u>if</u> you do.\n④ Do you mind <u>if</u> I open the window?\n⑤ I asked her <u>if</u> she knew French.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'5','explanation',E'⑤ 명사절 (~인지 아닌지, asked의 목적어) / 나머지 조건 부사절'),
jsonb_build_object('number',55,'question',E'다음 <보기>의 if와 쓰임이 같은 것을 고르시오.\n\n<보기> If you read many books, you''ll be wiser.\n\n① I will be happier <u>if</u> you join the party.\n② No one knows <u>if</u> she will break the record.\n③ She asked me <u>if</u> I liked spicy food.\n④ Do you know <u>if</u> he is coming?\n⑤ I''m not sure <u>if</u> it will snow tomorrow.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'1','explanation',E'<보기>는 조건 부사절. ① 조건 부사절 (같음) / ②③④⑤ 명사절'),
jsonb_build_object('number',56,'question',E'다음 중 밑줄 친 if의 쓰임이 나머지 넷과 다른 하나를 고르시오.\n\n① I don''t know <u>if</u> he will come soon.\n② <u>If</u> it rains tomorrow, we will not go on a picnic.\n③ I don''t know <u>if</u> he will come.\n④ Do you know <u>if</u> he will have dinner with us?\n⑤ I''m not sure <u>if</u> the store is open on Sunday.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'② 조건 부사절 (만약 ~한다면) / 나머지 명사절 (~인지 아닌지)'),
jsonb_build_object('number',57,'question',E'다음 두 문장의 의미가 같으면 ○, 다르면 ✕를 쓰시오.\n\nIf you don''t hurry, you will be late. = Unless you hurry, you will be late.','type','short_answer','answer',E'○','similar_answers',jsonb_build_array(E'O',E'o'),'explanation',E'If ~ not = Unless, 의미 동일'),
jsonb_build_object('number',58,'question',E'다음 두 문장의 의미가 같으면 ○, 다르면 ✕를 쓰시오.\n\nUnless it rains, we will go camping. = If it doesn''t rain, we will go camping.','type','short_answer','answer',E'○','similar_answers',jsonb_build_array(E'O',E'o'),'explanation',E'Unless = If ~ not, 의미 동일'),
jsonb_build_object('number',59,'question',E'다음 두 문장의 의미가 같으면 ○, 다르면 ✕를 쓰시오.\n\nIf you don''t exercise, you will get fat. = Unless you exercise, you won''t get fat.','type','short_answer','answer',E'✕','similar_answers',jsonb_build_array(E'X',E'x'),'explanation',E'원문은 "운동 안 하면 살찐다". Unless you exercise, you will get fat이 맞음 (won''t→will)'),
jsonb_build_object('number',60,'question',E'다음 두 문장의 의미가 같으면 ○, 다르면 ✕를 쓰시오.\n\nUnless she comes with me, I won''t go to Jane''s party. = If she doesn''t come with me, I won''t go to Jane''s party.','type','short_answer','answer',E'○','similar_answers',jsonb_build_array(E'O',E'o'),'explanation',E'Unless = If ~ not, 의미 동일'),
jsonb_build_object('number',61,'question',E'다음 문장과 의미가 같은 것을 고르시오.\n\nIf you don''t start now, you will be late.\n\n① If you start now, you will be late.\n② Unless you start now, you will be late.\n③ Unless you start now, you won''t be late.\n④ If you start now, you won''t be late.\n⑤ Although you start now, you will be late.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'If ~ not = Unless, 시작하지 않으면 늦을 것'),
jsonb_build_object('number',62,'question',E'다음 문장과 의미가 같은 것을 고르시오.\n\nUnless she buys the tickets, she won''t go to the concert.\n\n① If she buys the tickets, she won''t go to the concert.\n② If she doesn''t buy the tickets, she will go to the concert.\n③ If she doesn''t buy the tickets, she won''t go to the concert.\n④ Unless she doesn''t buy the tickets, she won''t go to the concert.\n⑤ If she buys the tickets, she will go to the concert.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'Unless = If ~ not, 티켓을 사지 않으면 콘서트에 안 갈 것'),
jsonb_build_object('number',63,'question',E'다음 문장과 의미가 같은 것을 고르시오.\n\nTake the subway, and you''ll get there faster.\n\n① Unless you take the subway, you''ll get there faster.\n② If you take the subway, you''ll get there faster.\n③ If you will take the subway, you''ll get there faster.\n④ If you don''t take the subway, you''ll get there faster.\n⑤ Although you take the subway, you''ll get there faster.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'2','explanation',E'명령문 + and = If ~, 지하철을 타면 더 빨리 도착할 것'),
jsonb_build_object('number',64,'question',E'다음 문장과 의미가 같은 것을 고르시오.\n\nStudy hard, or you will fail the exam.\n\n① If you study hard, you will fail the exam.\n② Unless you study hard, you won''t fail the exam.\n③ If you don''t study hard, you will fail the exam.\n④ Unless you study hard, you will pass the exam.\n⑤ If you study hard, you won''t pass the exam.','type','mcq','options',jsonb_build_array(E'①',E'②',E'③',E'④',E'⑤'),'answer',E'3','explanation',E'명령문 + or = If ~ not, 열심히 공부하지 않으면 시험에 떨어질 것'),
jsonb_build_object('number',65,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If it will rain tomorrow, we won''t go hiking.\nⓑ She will be late if she doesn''t hurry.\nⓒ If he comes back, I''ll cook special food.\nⓓ Unless you will exercise, you won''t be healthy.\nⓔ I''ll go to the beach if I have free time.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'ⓑ, ⓒ, ⓔ 옳음 (3개). ⓐ will rain→rains ⓓ will exercise→exercise'),
jsonb_build_object('number',66,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If you study hard, you passed the test.\nⓑ Unless she comes, I will be sad.\nⓒ If it snows tomorrow, school will be cancelled.\nⓓ I will call you if I will arrive.\nⓔ If you are tired, take a rest.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'ⓑ, ⓒ, ⓔ 옳음 (3개). ⓐ passed→will pass ⓓ will arrive→arrive'),
jsonb_build_object('number',67,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If you will eat too much, you''ll gain weight.\nⓑ I won''t go unless it stops raining.\nⓒ What will you do if she refuses to help?\nⓓ Unless you hurry, you won''t arrive on time.\nⓔ If I will see her tomorrow, I''ll tell her.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'ⓑ, ⓒ, ⓓ 옳음 (3개). ⓐ will eat→eat ⓔ will see→see'),
jsonb_build_object('number',68,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If she wants to go, I will go, too.\nⓑ He will be late if he doesn''t run.\nⓒ If we will take a taxi, we won''t be late.\nⓓ I don''t know if he will come or not.\nⓔ Unless you save money, you can''t buy it.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'4','explanation',E'ⓐ, ⓑ, ⓓ, ⓔ 옳음 (4개). ⓒ will take→take'),
jsonb_build_object('number',69,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If it be sunny tomorrow, we''ll go on a picnic.\nⓑ If you don''t start now, you are late.\nⓒ You''ll miss the bus if you don''t walk faster.\nⓓ If you will eat more vegetables, you''ll be healthy.\nⓔ The flea market will be held unless it rains tomorrow.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'2','explanation',E'ⓒ, ⓔ 옳음 (2개). ⓐ be→is ⓑ are→will be ⓓ will eat→eat'),
jsonb_build_object('number',70,'question',E'다음 중 어법상 옳은 문장의 총 개수를 고르시오.\n\nⓐ If I don''t run, I will be late.\nⓑ Unless you study harder, you will fail.\nⓒ If it will rain, I will stay at home.\nⓓ She''ll be angry if someone eats her pizza.\nⓔ Unless he will come right now, he''ll lose his job.','type','mcq','options',jsonb_build_array(E'1개',E'2개',E'3개',E'4개',E'5개'),'answer',E'3','explanation',E'ⓐ, ⓑ, ⓓ 옳음 (3개). ⓒ will rain→rains ⓔ will come→comes')
  );

  a := jsonb_build_array(E'1', E'2', E'3', E'1', E'3', E'5', E'1', E'3', E'4', E'3', E'2', E'5', E'2', E'4', E'3', E'5', E'4', E'1', E'5', E'3', E'3', E'5', E'2', E'1', E'2', E'5', E'2', E'1', E'2', E'2', E'3', E'4', E'2', E'2', E'3', E'4', E'5', E'3', E'5', E'1', E'1', E'3', E'3', E'4', E'2', E'3', E'4', E'1', E'5', E'2', E'5', E'2', E'5', E'5', E'1', E'2', E'○', E'○', E'✕', E'○', E'2', E'3', E'2', E'3', E'3', E'3', E'3', E'4', E'2', E'3');

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (E'조건문 if Step 2', E'조건문 if', q1 || q2 || q3, a, 'problem', 'interactive');
END $$;
