DO $$
DECLARE
  q1 jsonb;
  q2 jsonb;
  q3 jsonb;
  a  jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = E'조건문 if Step 1';

  q1 := jsonb_build_array(
jsonb_build_object('number',1,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf she ______ (study) harder, she will pass the test.','type','short_answer','answer',E'studies','similar_answers',jsonb_build_array(E'Studies',E'STUDIES'),'explanation',E'if절(조건절)에서는 현재시제를 사용합니다. 주어가 3인칭 단수(she)이므로 study → studies로 변환합니다.'),
jsonb_build_object('number',2,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nI ______ (call) you if I finish early.','type','short_answer','answer',E'will call','similar_answers',jsonb_build_array(E'Will call',E'will Call'),'explanation',E'주절(결과절)에서는 미래시제(will + 동사원형)를 사용합니다. call → will call이 됩니다.'),
jsonb_build_object('number',3,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf it ______ (rain) tomorrow, we will stay home.','type','short_answer','answer',E'rains','similar_answers',jsonb_build_array(E'Rains',E'RAINS'),'explanation',E'if절에서는 미래의 일이라도 현재시제를 씁니다. 주어가 3인칭 단수(it)이므로 rain → rains가 됩니다.'),
jsonb_build_object('number',4,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nHe ______ (be) late if he doesn''t hurry.','type','short_answer','answer',E'will be','similar_answers',jsonb_build_array(E'Will be',E'will Be'),'explanation',E'주절에서는 will + 동사원형을 사용합니다. be → will be가 됩니다.'),
jsonb_build_object('number',5,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf you ______ (not eat) breakfast, you''ll feel hungry.','type','short_answer','answer',E'don''t eat','similar_answers',jsonb_build_array(E'do not eat',E'Don''t eat',E'Do not eat'),'explanation',E'if절의 부정문은 don''t/doesn''t + 동사원형으로 씁니다. 주어가 you이므로 don''t eat이 됩니다.'),
jsonb_build_object('number',6,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf the baby ______ (cry), I will pick her up.','type','short_answer','answer',E'cries','similar_answers',jsonb_build_array(E'Cries',E'CRIES'),'explanation',E'if절에서는 현재시제를 사용합니다. 주어가 3인칭 단수(the baby)이므로 cry → cries(y를 i로 바꾸고 -es)가 됩니다.'),
jsonb_build_object('number',7,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nWe ______ (go) on a picnic if the weather is nice.','type','short_answer','answer',E'will go','similar_answers',jsonb_build_array(E'Will go',E'will Go'),'explanation',E'주절에서는 will + 동사원형을 사용합니다. go → will go가 됩니다.'),
jsonb_build_object('number',8,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf you ______ (press) this button, the machine starts.','type','short_answer','answer',E'press','similar_answers',jsonb_build_array(E'Press',E'PRESS'),'explanation',E'일반적 사실이나 습관을 나타내는 조건문(zero conditional)에서는 if절과 주절 모두 현재시제를 사용합니다. 주어가 you이므로 press 그대로 씁니다.'),
jsonb_build_object('number',9,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nIf she ______ (not leave) now, she will miss the train.','type','short_answer','answer',E'doesn''t leave','similar_answers',jsonb_build_array(E'does not leave',E'Doesn''t leave',E'Does not leave'),'explanation',E'if절의 부정문에서 주어가 3인칭 단수(she)이므로 doesn''t + 동사원형(leave)을 사용합니다.'),
jsonb_build_object('number',10,'question',E'다음 괄호 안의 동사를 알맞은 형태로 빈칸에 쓰시오.\n\nPlants ______ (die) if you don''t water them.','type','short_answer','answer',E'die','similar_answers',jsonb_build_array(E'Die',E'DIE'),'explanation',E'일반적 사실을 나타내는 조건문(zero conditional)에서는 주절도 현재시제를 씁니다. 주어가 복수(Plants)이므로 die 그대로 씁니다.'),
jsonb_build_object('number',11,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf it (A)______ (snow) tomorrow, school (B)______ (cancel).','type','short_answer','answer',E'(A) snows (B) will be cancelled','similar_answers',jsonb_build_array(E'(A) snows (B) will be canceled',E'snows, will be cancelled',E'snows, will be canceled',E'snows / will be cancelled',E'snows / will be canceled'),'explanation',E'if절은 현재시제(snows), 주절은 미래 수동태(will be cancelled)입니다. cancelled와 canceled 모두 맞는 철자입니다.'),
jsonb_build_object('number',12,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf you (A)______ (help) me, I (B)______ (finish) sooner.','type','short_answer','answer',E'(A) help (B) will finish','similar_answers',jsonb_build_array(E'help, will finish',E'help / will finish'),'explanation',E'if절은 현재시제(help), 주절은 미래시제(will finish)입니다. 주어가 you이므로 help은 원형 그대로 씁니다.'),
jsonb_build_object('number',13,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nShe (A)______ (be) happy if you (B)______ (come) to the party.','type','short_answer','answer',E'(A) will be (B) come','similar_answers',jsonb_build_array(E'will be, come',E'will be / come'),'explanation',E'주절(She ...)에서는 will be(미래시제), if절(you ...)에서는 현재시제 come을 씁니다.'),
jsonb_build_object('number',14,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf he (A)______ (arrive) early, we (B)______ (eat) together.','type','short_answer','answer',E'(A) arrives (B) will eat','similar_answers',jsonb_build_array(E'arrives, will eat',E'arrives / will eat'),'explanation',E'if절은 현재시제(arrives, 3인칭 단수), 주절은 미래시제(will eat)입니다.'),
jsonb_build_object('number',15,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf you (A)______ (touch) the stove, you (B)______ (burn) yourself.','type','short_answer','answer',E'(A) touch (B) will burn','similar_answers',jsonb_build_array(E'touch, will burn',E'touch / will burn'),'explanation',E'if절은 현재시제(touch), 주절은 미래시제(will burn)입니다.'),
jsonb_build_object('number',16,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf they (A)______ (not hurry), they (B)______ (miss) the bus.','type','short_answer','answer',E'(A) don''t hurry (B) will miss','similar_answers',jsonb_build_array(E'(A) do not hurry (B) will miss',E'don''t hurry, will miss',E'do not hurry, will miss',E'don''t hurry / will miss'),'explanation',E'if절의 부정은 don''t + 동사원형(hurry), 주절은 will miss(미래시제)입니다.'),
jsonb_build_object('number',17,'question',E'다음 (A), (B)에 들어갈 동사의 알맞은 형태를 짝지어 쓰시오.\n\nIf you (A)______ (be) quiet, the baby (B)______ (sleep).','type','short_answer','answer',E'(A) are (B) will sleep','similar_answers',jsonb_build_array(E'are, will sleep',E'are / will sleep'),'explanation',E'if절에서 be동사는 주어에 맞춰 현재형(are)으로, 주절은 will sleep(미래시제)으로 씁니다.'),
jsonb_build_object('number',18,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\n(you / if / hard / practice), you can win the contest.','type','short_answer','answer',E'If you practice hard, you can win the contest.','similar_answers',jsonb_build_array(E'If you practice hard, you can win the contest'),'explanation',E'if절: If + 주어(you) + 동사(practice) + 부사(hard) 순서로 배열합니다.'),
jsonb_build_object('number',19,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\n(hungry / feel / I / if), I will make a sandwich.','type','short_answer','answer',E'If I feel hungry, I will make a sandwich.','similar_answers',jsonb_build_array(E'If I feel hungry, I will make a sandwich'),'explanation',E'if절: If + 주어(I) + 동사(feel) + 형용사(hungry) 순서로 배열합니다.'),
jsonb_build_object('number',20,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\nWe will be late (take / don''t / if / the subway / we).','type','short_answer','answer',E'We will be late if we don''t take the subway.','similar_answers',jsonb_build_array(E'We will be late if we don''t take the subway',E'We will be late if we do not take the subway.',E'We will be late if we do not take the subway'),'explanation',E'if절이 뒤에 올 때는 쉼표 없이 연결합니다: if + 주어(we) + don''t take + 목적어(the subway).'),
jsonb_build_object('number',21,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\n(the door / open / if / you), the cat will run out.','type','short_answer','answer',E'If you open the door, the cat will run out.','similar_answers',jsonb_build_array(E'If you open the door, the cat will run out'),'explanation',E'if절: If + 주어(you) + 동사(open) + 목적어(the door) 순서로 배열합니다.'),
jsonb_build_object('number',22,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\nShe will be angry (eat / if / her pizza / someone).','type','short_answer','answer',E'She will be angry if someone eats her pizza.','similar_answers',jsonb_build_array(E'She will be angry if someone eats her pizza'),'explanation',E'if절이 뒤에 올 때 쉼표 없이 연결합니다. someone은 3인칭 단수이므로 eat → eats가 됩니다.'),
jsonb_build_object('number',23,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\n(get up / if / early / you), you will see the sunrise.','type','short_answer','answer',E'If you get up early, you will see the sunrise.','similar_answers',jsonb_build_array(E'If you get up early, you will see the sunrise'),'explanation',E'if절: If + 주어(you) + 동사구(get up) + 부사(early) 순서로 배열합니다.'),
jsonb_build_object('number',24,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\n(forget / if / your umbrella / you), you will get wet.','type','short_answer','answer',E'If you forget your umbrella, you will get wet.','similar_answers',jsonb_build_array(E'If you forget your umbrella, you will get wet'),'explanation',E'if절: If + 주어(you) + 동사(forget) + 목적어(your umbrella) 순서로 배열합니다.'),
jsonb_build_object('number',25,'question',E'주어진 단어를 바르게 배열하여 조건문을 완성하시오.\n\nI (bring / will / the drinks) if you bring the food.','type','short_answer','answer',E'I will bring the drinks if you bring the food.','similar_answers',jsonb_build_array(E'I will bring the drinks if you bring the food'),'explanation',E'주절: 주어(I) + will + 동사원형(bring) + 목적어(the drinks) 순서로 배열합니다. if절이 뒤에 오면 쉼표가 필요 없습니다.')
  );

  q2 := jsonb_build_array(
jsonb_build_object('number',26,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf it will rain tomorrow, I will stay home.','type','short_answer','answer',E'If it rains tomorrow, I will stay home.','similar_answers',jsonb_build_array(E'If it rains tomorrow, I will stay home',E'if it rains tomorrow, I will stay home.',E'if it rains tomorrow, I will stay home'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will rain → rains'),
jsonb_build_object('number',27,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf she will finish early, we can have lunch together.','type','short_answer','answer',E'If she finishes early, we can have lunch together.','similar_answers',jsonb_build_array(E'If she finishes early, we can have lunch together',E'if she finishes early, we can have lunch together.',E'if she finishes early, we can have lunch together'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will finish → finishes'),
jsonb_build_object('number',28,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nI will be happy if he will come to the party.','type','short_answer','answer',E'I will be happy if he comes to the party.','similar_answers',jsonb_build_array(E'I will be happy if he comes to the party',E'i will be happy if he comes to the party.',E'i will be happy if he comes to the party'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will come → comes'),
jsonb_build_object('number',29,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf you will not hurry, you will miss the bus.','type','short_answer','answer',E'If you don''t hurry, you will miss the bus.','similar_answers',jsonb_build_array(E'If you don''t hurry, you will miss the bus',E'If you do not hurry, you will miss the bus.',E'If you do not hurry, you will miss the bus',E'if you don''t hurry, you will miss the bus.',E'if you don''t hurry, you will miss the bus'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will not hurry → don''t hurry'),
jsonb_build_object('number',30,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf he doesn''t run, he will missed the train.','type','short_answer','answer',E'If he doesn''t run, he will miss the train.','similar_answers',jsonb_build_array(E'If he doesn''t run, he will miss the train',E'If he does not run, he will miss the train.',E'If he does not run, he will miss the train',E'if he doesn''t run, he will miss the train.',E'if he doesn''t run, he will miss the train'),'explanation',E'will 뒤에는 동사원형이 와야 한다. will missed → will miss'),
jsonb_build_object('number',31,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nWe will go camping if it won''t rain this weekend.','type','short_answer','answer',E'We will go camping if it doesn''t rain this weekend.','similar_answers',jsonb_build_array(E'We will go camping if it doesn''t rain this weekend',E'We will go camping if it does not rain this weekend.',E'We will go camping if it does not rain this weekend',E'we will go camping if it doesn''t rain this weekend.',E'we will go camping if it doesn''t rain this weekend'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. won''t rain → doesn''t rain'),
jsonb_build_object('number',32,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf Minjun will leave now, he can catch the last bus.','type','short_answer','answer',E'If Minjun leaves now, he can catch the last bus.','similar_answers',jsonb_build_array(E'If Minjun leaves now, he can catch the last bus',E'if Minjun leaves now, he can catch the last bus.',E'if Minjun leaves now, he can catch the last bus'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will leave → leaves'),
jsonb_build_object('number',33,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf you will eat too much fast food, you will gain weight.','type','short_answer','answer',E'If you eat too much fast food, you will gain weight.','similar_answers',jsonb_build_array(E'If you eat too much fast food, you will gain weight',E'if you eat too much fast food, you will gain weight.',E'if you eat too much fast food, you will gain weight'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will eat → eat'),
jsonb_build_object('number',34,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf I see her tomorrow, I will told her the news.','type','short_answer','answer',E'If I see her tomorrow, I will tell her the news.','similar_answers',jsonb_build_array(E'If I see her tomorrow, I will tell her the news',E'if I see her tomorrow, I will tell her the news.',E'if I see her tomorrow, I will tell her the news'),'explanation',E'will 뒤에는 동사원형이 와야 한다. will told → will tell'),
jsonb_build_object('number',35,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nShe won''t pass the exam if she won''t study harder.','type','short_answer','answer',E'She won''t pass the exam if she doesn''t study harder.','similar_answers',jsonb_build_array(E'She won''t pass the exam if she doesn''t study harder',E'She won''t pass the exam if she does not study harder.',E'She won''t pass the exam if she does not study harder',E'she won''t pass the exam if she doesn''t study harder.',E'she won''t pass the exam if she doesn''t study harder'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. won''t study → doesn''t study'),
jsonb_build_object('number',36,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nIf you will be thirsty, there is water in the fridge.','type','short_answer','answer',E'If you are thirsty, there is water in the fridge.','similar_answers',jsonb_build_array(E'If you are thirsty, there is water in the fridge',E'if you are thirsty, there is water in the fridge.',E'if you are thirsty, there is water in the fridge'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will be → are'),
jsonb_build_object('number',37,'question',E'다음 문장에서 어법상 어색한 부분을 찾아 바르게 고쳐 전체 문장을 다시 쓰시오.\n\nHe will water the garden if he will come home early.','type','short_answer','answer',E'He will water the garden if he comes home early.','similar_answers',jsonb_build_array(E'He will water the garden if he comes home early',E'he will water the garden if he comes home early.',E'he will water the garden if he comes home early'),'explanation',E'if절에서는 미래를 나타낼 때 will을 쓰지 않고 현재시제를 사용한다. will come → comes'),
jsonb_build_object('number',38,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nIf you don''t hurry, you will be late.\n= ______ you hurry, you will be late.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. \"만약 서두르지 않으면\"을 unless로 바꾸면 부정이 빠지고 \"Unless you hurry\"가 된다.'),
jsonb_build_object('number',39,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nUnless it rains, we will go on a field trip.\n= If it ______, we will go on a field trip.','type','short_answer','answer',E'doesn''t rain','similar_answers',jsonb_build_array(E'does not rain',E'Doesn''t rain',E'Does not rain'),'explanation',E'Unless = If ~ not. unless it rains → if it doesn''t rain으로 전환한다.'),
jsonb_build_object('number',40,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nIf you don''t wear a coat, you will catch a cold.\n= ______ you wear a coat, you will catch a cold.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. \"만약 코트를 입지 않으면\"을 unless로 바꾸면 부정이 빠지고 \"Unless you wear\"가 된다.'),
jsonb_build_object('number',41,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nUnless she apologizes, he won''t forgive her.\n= If she ______, he won''t forgive her.','type','short_answer','answer',E'doesn''t apologize','similar_answers',jsonb_build_array(E'does not apologize',E'Doesn''t apologize',E'Does not apologize'),'explanation',E'Unless = If ~ not. unless she apologizes → if she doesn''t apologize로 전환한다.'),
jsonb_build_object('number',42,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nIf you don''t exercise regularly, you won''t stay healthy.\n= ______ you exercise regularly, you won''t stay healthy.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. \"만약 규칙적으로 운동하지 않으면\"을 unless로 바꾸면 부정이 빠지고 \"Unless you exercise\"가 된다.'),
jsonb_build_object('number',43,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nUnless you save enough money, you can''t buy the laptop.\n= If you ______ enough money, you can''t buy the laptop.','type','short_answer','answer',E'don''t save','similar_answers',jsonb_build_array(E'do not save',E'Don''t save',E'Do not save'),'explanation',E'Unless = If ~ not. unless you save → if you don''t save로 전환한다.'),
jsonb_build_object('number',44,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nIf he doesn''t stop playing games, he will fail the test.\n= ______ he stops playing games, he will fail the test.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. \"만약 게임을 그만두지 않으면\"을 unless로 바꾸면 부정이 빠지고 \"Unless he stops\"가 된다.'),
jsonb_build_object('number',45,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nUnless you get up early, you will miss the school bus.\n= If you ______ early, you will miss the school bus.','type','short_answer','answer',E'don''t get up','similar_answers',jsonb_build_array(E'do not get up',E'Don''t get up',E'Do not get up'),'explanation',E'Unless = If ~ not. unless you get up → if you don''t get up으로 전환한다.'),
jsonb_build_object('number',46,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nIf you don''t return the book, I will report you to the teacher.\n= ______ you return the book, I will report you to the teacher.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. \"만약 책을 돌려주지 않으면\"을 unless로 바꾸면 부정이 빠지고 \"Unless you return\"이 된다.'),
jsonb_build_object('number',47,'question',E'다음 두 문장이 같은 뜻이 되도록 빈칸을 채우시오.\n\nUnless they leave now, they will miss the first show.\n= If they ______ now, they will miss the first show.','type','short_answer','answer',E'don''t leave','similar_answers',jsonb_build_array(E'do not leave',E'Don''t leave',E'Do not leave'),'explanation',E'Unless = If ~ not. unless they leave → if they don''t leave로 전환한다.'),
jsonb_build_object('number',48,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\n(If / Unless) you eat your vegetables, you won''t grow tall.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'Unless = If ~ not. 야채를 먹지 않으면 키가 안 큰다는 의미이므로 Unless가 적절'),
jsonb_build_object('number',49,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\nI won''t go out (if / unless) it stops raining.','type','short_answer','answer',E'unless','similar_answers',jsonb_build_array(E'Unless',E'UNLESS'),'explanation',E'비가 그치지 않으면 나가지 않겠다는 의미이므로 unless가 적절'),
jsonb_build_object('number',50,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\n(If / Unless) she studies hard, she will fail the exam.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'열심히 공부하지 않으면 시험에 떨어질 것이라는 의미이므로 Unless가 적절'),
jsonb_build_object('number',51,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\nCall me (if / unless) you need any help.','type','short_answer','answer',E'if','similar_answers',jsonb_build_array(E'If',E'IF'),'explanation',E'도움이 필요하면 전화하라는 조건이므로 if가 적절'),
jsonb_build_object('number',52,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\n(If / Unless) you don''t hurry up, we''ll be late.','type','short_answer','answer',E'If','similar_answers',jsonb_build_array(E'if',E'IF'),'explanation',E'이미 don''t가 있으므로 부정 조건은 if를 사용한다. unless는 이중 부정이 되어 부적절'),
jsonb_build_object('number',53,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\nHe will lose his job (if / unless) he works harder.','type','short_answer','answer',E'unless','similar_answers',jsonb_build_array(E'Unless',E'UNLESS'),'explanation',E'더 열심히 일하지 않으면 직장을 잃을 것이라는 의미이므로 unless가 적절'),
jsonb_build_object('number',54,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\n(If / Unless) global warming gets worse, the ice caps will melt.','type','short_answer','answer',E'If','similar_answers',jsonb_build_array(E'if',E'IF'),'explanation',E'지구 온난화가 심해지면 빙하가 녹을 것이라는 조건이므로 If가 적절'),
jsonb_build_object('number',55,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\nYou can watch TV (if / unless) you finish your homework first.','type','short_answer','answer',E'if','similar_answers',jsonb_build_array(E'If',E'IF'),'explanation',E'숙제를 끝내면 TV를 볼 수 있다는 조건이므로 if가 적절'),
jsonb_build_object('number',56,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\n(If / Unless) you take an umbrella, you will get soaked.','type','short_answer','answer',E'Unless','similar_answers',jsonb_build_array(E'unless',E'UNLESS'),'explanation',E'우산을 가져가지 않으면 흠뻑 젖을 것이라는 의미이므로 Unless가 적절'),
jsonb_build_object('number',57,'question',E'괄호 안에서 알맞은 것을 골라 쓰시오.\n\nClimate change will continue (if / unless) we take action now.','type','short_answer','answer',E'unless','similar_answers',jsonb_build_array(E'Unless',E'UNLESS'),'explanation',E'지금 행동하지 않으면 기후 변화가 계속될 것이라는 의미이므로 unless가 적절')
  );

  q3 := jsonb_build_array(
jsonb_build_object('number',58,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nStudy hard. Then you will get a good grade.','type','short_answer','answer',E'If you study hard, you will get a good grade.','similar_answers',jsonb_build_array(E'If you study hard, you will get a good grade'),'explanation',E'명령문 + Then 주어 will ~은 If you + 현재시제, 주어 will ~로 바꿉니다. Study hard → If you study hard로 변환합니다.'),
jsonb_build_object('number',59,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nTake the subway. Then you will get there faster.','type','short_answer','answer',E'If you take the subway, you will get there faster.','similar_answers',jsonb_build_array(E'If you take the subway, you will get there faster'),'explanation',E'명령문 Take the subway를 If you take the subway로 바꾸고, 주절 you will get there faster를 연결합니다.'),
jsonb_build_object('number',60,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nEat breakfast every day. Then you won''t feel tired in class.','type','short_answer','answer',E'If you eat breakfast every day, you won''t feel tired in class.','similar_answers',jsonb_build_array(E'If you eat breakfast every day, you won''t feel tired in class',E'If you eat breakfast every day, you will not feel tired in class.',E'If you eat breakfast every day, you will not feel tired in class'),'explanation',E'명령문을 If you + 현재시제로 바꿉니다. won''t = will not(부정)은 그대로 주절에 씁니다.'),
jsonb_build_object('number',61,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nPractice every day. Then you can play the violin well.','type','short_answer','answer',E'If you practice every day, you can play the violin well.','similar_answers',jsonb_build_array(E'If you practice every day, you can play the violin well'),'explanation',E'명령문을 If you practice every day로 바꾸고, 주절의 조동사 can은 그대로 유지합니다.'),
jsonb_build_object('number',62,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nShe doesn''t eat. Then we will see the doctor.','type','short_answer','answer',E'If she doesn''t eat, we will see the doctor.','similar_answers',jsonb_build_array(E'If she doesn''t eat, we will see the doctor',E'If she does not eat, we will see the doctor.',E'If she does not eat, we will see the doctor'),'explanation',E'She doesn''t eat을 If she doesn''t eat으로 바꿉니다. 부정문은 doesn''t + 동사원형을 그대로 유지합니다.'),
jsonb_build_object('number',63,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nBe careful. Then you won''t spoil the machine.','type','short_answer','answer',E'If you are careful, you won''t spoil the machine.','similar_answers',jsonb_build_array(E'If you are careful, you won''t spoil the machine',E'If you are careful, you will not spoil the machine.',E'If you are careful, you will not spoil the machine'),'explanation',E'명령문 Be careful은 If you are careful로 바꿉니다. be동사 명령문은 If + 주어 + are/is로 변환합니다.'),
jsonb_build_object('number',64,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nDon''t drink too much coffee. Then you can sleep well.','type','short_answer','answer',E'If you don''t drink too much coffee, you can sleep well.','similar_answers',jsonb_build_array(E'If you don''t drink too much coffee, you can sleep well',E'If you do not drink too much coffee, you can sleep well.',E'If you do not drink too much coffee, you can sleep well'),'explanation',E'부정 명령문 Don''t ~는 If you don''t + 동사원형으로 바꿉니다.'),
jsonb_build_object('number',65,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nExercise regularly. And you will feel much healthier.','type','short_answer','answer',E'If you exercise regularly, you will feel much healthier.','similar_answers',jsonb_build_array(E'If you exercise regularly, you will feel much healthier'),'explanation',E'명령문 + And 주어 will ~은 If you + 현재시제, 주어 will ~로 바꿉니다. And와 Then은 같은 패턴입니다.'),
jsonb_build_object('number',66,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nYou don''t protect rainforests. Then many animal species won''t survive.','type','short_answer','answer',E'If you don''t protect rainforests, many animal species won''t survive.','similar_answers',jsonb_build_array(E'If you don''t protect rainforests, many animal species won''t survive',E'If you do not protect rainforests, many animal species won''t survive.',E'If you do not protect rainforests, many animal species won''t survive',E'If you do not protect rainforests, many animal species will not survive.',E'If you do not protect rainforests, many animal species will not survive'),'explanation',E'You don''t protect를 If you don''t protect로 바꿉니다. 부정문은 don''t + 동사원형을 그대로 유지합니다.'),
jsonb_build_object('number',67,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nTalk to him. Then he will understand your decision.','type','short_answer','answer',E'If you talk to him, he will understand your decision.','similar_answers',jsonb_build_array(E'If you talk to him, he will understand your decision'),'explanation',E'명령문 Talk to him을 If you talk to him으로 바꾸고, 주절 he will understand your decision을 연결합니다.'),
jsonb_build_object('number',68,'question',E'다음 두 문장을 if를 사용하여 한 문장으로 쓰시오.\n\nDon''t brush your teeth. Then you will get a cavity.','type','short_answer','answer',E'If you don''t brush your teeth, you will get a cavity.','similar_answers',jsonb_build_array(E'If you don''t brush your teeth, you will get a cavity',E'If you do not brush your teeth, you will get a cavity.',E'If you do not brush your teeth, you will get a cavity'),'explanation',E'부정 명령문 Don''t brush를 If you don''t brush로 바꿉니다. 주어 you를 추가하고 don''t + 동사원형을 유지합니다.'),
jsonb_build_object('number',69,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\nI don''t know <u>if</u> he will come tomorrow.','type','short_answer','answer',E'ⓑ','similar_answers',jsonb_build_array(E'b',E'B'),'explanation',E'명사절 (~인지 아닌지), know의 목적어 역할을 합니다. "그가 내일 올지 아닌지 모른다"로 해석됩니다.'),
jsonb_build_object('number',70,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\n<u>If</u> it is cold tomorrow, I will wear a heavy coat.','type','short_answer','answer',E'ⓐ','similar_answers',jsonb_build_array(E'a',E'A'),'explanation',E'조건의 부사절 (만약 ~한다면)입니다. "만약 내일 춥다면 두꺼운 외투를 입을 것이다"로 해석됩니다.'),
jsonb_build_object('number',71,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\nDo you know <u>if</u> she bought a new phone?','type','short_answer','answer',E'ⓑ','similar_answers',jsonb_build_array(E'b',E'B'),'explanation',E'명사절 (~인지 아닌지), know의 목적어 역할을 합니다. "그녀가 새 전화기를 샀는지 아니?"로 해석됩니다.'),
jsonb_build_object('number',72,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\n<u>If</u> you leave now, you will catch the train.','type','short_answer','answer',E'ⓐ','similar_answers',jsonb_build_array(E'a',E'A'),'explanation',E'조건의 부사절 (만약 ~한다면)입니다. "만약 지금 떠나면 기차를 탈 수 있을 것이다"로 해석됩니다.'),
jsonb_build_object('number',73,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\nTell me <u>if</u> you need any help.','type','short_answer','answer',E'ⓐ','similar_answers',jsonb_build_array(E'a',E'A'),'explanation',E'조건의 부사절 (만약 ~한다면)입니다. 명령문과 함께 쓰여 "만약 도움이 필요하면 말해 줘"로 해석됩니다.'),
jsonb_build_object('number',74,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\nShe asked me <u>if</u> I wanted to join the club.','type','short_answer','answer',E'ⓑ','similar_answers',jsonb_build_array(E'b',E'B'),'explanation',E'명사절 (~인지 아닌지), asked의 목적어 역할을 합니다. "그녀는 내가 클럽에 가입하고 싶은지 물어봤다"로 해석됩니다.'),
jsonb_build_object('number',75,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\n<u>If</u> you don''t hurry, you will miss the last bus.','type','short_answer','answer',E'ⓐ','similar_answers',jsonb_build_array(E'a',E'A'),'explanation',E'조건의 부사절 (만약 ~한다면)입니다. "만약 서두르지 않으면 마지막 버스를 놓칠 것이다"로 해석됩니다.'),
jsonb_build_object('number',76,'question',E'다음 밑줄 친 if의 쓰임이 <보기>와 같으면 ⓐ, 다르면 ⓑ를 쓰시오.\n\n<보기> If you study hard, you will pass the exam. → ⓐ 조건의 부사절 (만약 ~한다면)\n\nI''m not sure <u>if</u> the store is open on Sunday.','type','short_answer','answer',E'ⓑ','similar_answers',jsonb_build_array(E'b',E'B'),'explanation',E'명사절 (~인지 아닌지), sure의 보어 역할을 합니다. "그 가게가 일요일에 여는지 확실하지 않다"로 해석됩니다.'),
jsonb_build_object('number',77,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n만약 내일 날씨가 좋다면, 우리는 자전거를 탈 것이다.','type','short_answer','answer',E'If the weather is nice tomorrow, we will ride bikes.','similar_answers',jsonb_build_array(E'If the weather is nice tomorrow, we will ride bikes',E'If the weather is good tomorrow, we will ride bikes.',E'If the weather is good tomorrow, we will ride bikes',E'If the weather is fine tomorrow, we will ride bikes.',E'If the weather is fine tomorrow, we will ride bikes'),'explanation',E'조건절: If the weather is nice/good tomorrow (현재시제), 주절: we will ride bikes (미래시제)로 씁니다.'),
jsonb_build_object('number',78,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n네가 지금 출발하지 않으면, 너는 늦을 것이다.','type','short_answer','answer',E'Unless you leave now, you will be late.','similar_answers',jsonb_build_array(E'Unless you leave now, you will be late',E'If you don''t leave now, you will be late.',E'If you don''t leave now, you will be late',E'If you do not leave now, you will be late.',E'If you do not leave now, you will be late'),'explanation',E'~하지 않으면은 unless 또는 if ~ not으로 표현합니다. Unless you leave now = If you don''t leave now입니다.'),
jsonb_build_object('number',79,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n만약 그녀가 열심히 연습한다면, 그녀는 대회에서 이길 수 있다.','type','short_answer','answer',E'If she practices hard, she can win the contest.','similar_answers',jsonb_build_array(E'If she practices hard, she can win the contest',E'If she practices hard, she can win the competition.',E'If she practices hard, she can win the competition'),'explanation',E'조건절: If she practices hard (3인칭 단수 현재시제), 주절: she can win the contest (조동사 can)으로 씁니다.'),
jsonb_build_object('number',80,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n네가 건강해지고 싶다면, 규칙적으로 운동해라.','type','short_answer','answer',E'If you want to be healthy, exercise regularly.','similar_answers',jsonb_build_array(E'If you want to be healthy, exercise regularly',E'If you want to become healthy, exercise regularly.',E'If you want to become healthy, exercise regularly'),'explanation',E'조건절: If you want to be healthy (현재시제), 주절: exercise regularly (명령문)로 씁니다.'),
jsonb_build_object('number',81,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n만약 그가 공부를 열심히 하지 않는다면, 그는 시험에 떨어질 것이다.','type','short_answer','answer',E'If he doesn''t study hard, he will fail the exam.','similar_answers',jsonb_build_array(E'If he doesn''t study hard, he will fail the exam',E'If he does not study hard, he will fail the exam.',E'If he does not study hard, he will fail the exam',E'Unless he studies hard, he will fail the exam.',E'Unless he studies hard, he will fail the exam'),'explanation',E'~하지 않는다면은 if ~ not 또는 unless로 표현합니다. If he doesn''t study hard = Unless he studies hard입니다.'),
jsonb_build_object('number',82,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n만약 내가 너를 만나면 그 소식을 전해줄게.','type','short_answer','answer',E'If I meet you, I will tell you the news.','similar_answers',jsonb_build_array(E'If I meet you, I will tell you the news',E'If I meet you, I''ll tell you the news.',E'If I meet you, I''ll tell you the news'),'explanation',E'조건절: If I meet you (현재시제), 주절: I will tell you the news (미래시제)로 씁니다.'),
jsonb_build_object('number',83,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n서두르지 않으면, 우리는 마지막 열차를 놓칠 것이다.','type','short_answer','answer',E'Unless we hurry, we will miss the last train.','similar_answers',jsonb_build_array(E'Unless we hurry, we will miss the last train',E'If we don''t hurry, we will miss the last train.',E'If we don''t hurry, we will miss the last train',E'If we do not hurry, we will miss the last train.',E'If we do not hurry, we will miss the last train'),'explanation',E'~하지 않으면은 unless 또는 if ~ not으로 표현합니다. Unless we hurry = If we don''t hurry입니다.'),
jsonb_build_object('number',84,'question',E'다음 우리말과 일치하도록 if 또는 unless를 사용하여 영작하시오.\n\n만약 네가 나에게 5달러를 빌려준다면, 내일 갚을게.','type','short_answer','answer',E'If you lend me five dollars, I will pay you back tomorrow.','similar_answers',jsonb_build_array(E'If you lend me five dollars, I will pay you back tomorrow',E'If you lend me 5 dollars, I will pay you back tomorrow.',E'If you lend me 5 dollars, I will pay you back tomorrow',E'If you lend me five dollars, I''ll pay you back tomorrow.',E'If you lend me five dollars, I''ll pay you back tomorrow'),'explanation',E'조건절: If you lend me five dollars (현재시제), 주절: I will pay you back tomorrow (미래시제)로 씁니다. five dollars와 5 dollars 모두 허용됩니다.')
  );

  a := jsonb_build_array(E'studies', E'will call', E'rains', E'will be', E'don''t eat', E'cries', E'will go', E'press', E'doesn''t leave', E'die', E'(A) snows (B) will be cancelled', E'(A) help (B) will finish', E'(A) will be (B) come', E'(A) arrives (B) will eat', E'(A) touch (B) will burn', E'(A) don''t hurry (B) will miss', E'(A) are (B) will sleep', E'If you practice hard, you can win the contest.', E'If I feel hungry, I will make a sandwich.', E'We will be late if we don''t take the subway.', E'If you open the door, the cat will run out.', E'She will be angry if someone eats her pizza.', E'If you get up early, you will see the sunrise.', E'If you forget your umbrella, you will get wet.', E'I will bring the drinks if you bring the food.', E'If it rains tomorrow, I will stay home.', E'If she finishes early, we can have lunch together.', E'I will be happy if he comes to the party.', E'If you don''t hurry, you will miss the bus.', E'If he doesn''t run, he will miss the train.', E'We will go camping if it doesn''t rain this weekend.', E'If Minjun leaves now, he can catch the last bus.', E'If you eat too much fast food, you will gain weight.', E'If I see her tomorrow, I will tell her the news.', E'She won''t pass the exam if she doesn''t study harder.', E'If you are thirsty, there is water in the fridge.', E'He will water the garden if he comes home early.', E'Unless', E'doesn''t rain', E'Unless', E'doesn''t apologize', E'Unless', E'don''t save', E'Unless', E'don''t get up', E'Unless', E'don''t leave', E'Unless', E'unless', E'Unless', E'if', E'If', E'unless', E'If', E'if', E'Unless', E'unless', E'If you study hard, you will get a good grade.', E'If you take the subway, you will get there faster.', E'If you eat breakfast every day, you won''t feel tired in class.', E'If you practice every day, you can play the violin well.', E'If she doesn''t eat, we will see the doctor.', E'If you are careful, you won''t spoil the machine.', E'If you don''t drink too much coffee, you can sleep well.', E'If you exercise regularly, you will feel much healthier.', E'If you don''t protect rainforests, many animal species won''t survive.', E'If you talk to him, he will understand your decision.', E'If you don''t brush your teeth, you will get a cavity.', E'ⓑ', E'ⓐ', E'ⓑ', E'ⓐ', E'ⓐ', E'ⓑ', E'ⓐ', E'ⓑ', E'If the weather is nice tomorrow, we will ride bikes.', E'Unless you leave now, you will be late.', E'If she practices hard, she can win the contest.', E'If you want to be healthy, exercise regularly.', E'If he doesn''t study hard, he will fail the exam.', E'If I meet you, I will tell you the news.', E'Unless we hurry, we will miss the last train.', E'If you lend me five dollars, I will pay you back tomorrow.');

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (E'조건문 if Step 1', E'조건문 if', q1 || q2 || q3, a, 'problem', 'interactive');
END $$;
