DO $$
DECLARE
  v_questions jsonb;
  v_answer_key jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '지각동사 Step3';

  v_questions := jsonb_build_array(
    jsonb_build_object('number', 1, 'type', 'subjective', 'question', E'다음 두 문장의 의미가 일치하도록 빈칸에 알맞은 말을 쓰시오.\n\nI heard that you won the award.\n= I heard ___ the award.', 'answer', E'you win', 'similar_answers', jsonb_build_array(E'you win', E'you winning')),
    jsonb_build_object('number', 2, 'type', 'subjective', 'question', E'다음 두 문장의 의미가 일치하도록 빈칸에 알맞은 말을 쓰시오.\n\nI didn''t notice that she was crying.\n= I didn''t notice ___.', 'answer', E'her crying', 'similar_answers', jsonb_build_array(E'her cry', E'her crying')),
    jsonb_build_object('number', 3, 'type', 'subjective', 'question', E'다음 두 문장의 의미가 일치하도록 빈칸에 알맞은 말을 쓰시오.\n\nI heard that they cheered for the team.\n= I heard ___ for the team.', 'answer', E'them cheer', 'similar_answers', jsonb_build_array(E'them cheer', E'them cheering')),
    jsonb_build_object('number', 4, 'type', 'subjective', 'question', E'다음 두 문장의 의미가 일치하도록 빈칸에 알맞은 말을 쓰시오.\n\nShe heard that the pianist played beautifully.\n= She heard ___ beautifully.', 'answer', E'the pianist play', 'similar_answers', jsonb_build_array(E'the pianist play', E'the pianist playing')),
    jsonb_build_object('number', 5, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nI heard my cat. It was purring on the bed.', 'answer', E'I heard my cat purring on the bed.', 'similar_answers', jsonb_build_array(E'I heard my cat purring on the bed.', E'I heard my cat purr on the bed.', E'I heard my cat purring on the bed', E'I heard my cat purr on the bed')),
    jsonb_build_object('number', 6, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nShe saw her teammate. He was sprinting toward the goal.', 'answer', E'She saw her teammate sprinting toward the goal.', 'similar_answers', jsonb_build_array(E'She saw her teammate sprinting toward the goal.', E'She saw her teammate sprint toward the goal.', E'She saw her teammate sprinting toward the goal', E'She saw her teammate sprint toward the goal')),
    jsonb_build_object('number', 7, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nJimin watched his little sister. She was drawing at the table.', 'answer', E'Jimin watched his little sister drawing at the table.', 'similar_answers', jsonb_build_array(E'Jimin watched his little sister drawing at the table.', E'Jimin watched his little sister draw at the table.', E'Jimin watched his little sister drawing at the table', E'Jimin watched his little sister draw at the table')),
    jsonb_build_object('number', 8, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nHe saw his puppy. The puppy was chasing its tail.', 'answer', E'He saw his puppy chasing its tail.', 'similar_answers', jsonb_build_array(E'He saw his puppy chasing its tail.', E'He saw his puppy chase its tail.', E'He saw his puppy chasing its tail', E'He saw his puppy chase its tail')),
    jsonb_build_object('number', 9, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nI saw some kids. They were splashing in the puddles.', 'answer', E'I saw some kids splashing in the puddles.', 'similar_answers', jsonb_build_array(E'I saw some kids splashing in the puddles.', E'I saw some kids splash in the puddles.', E'I saw some kids splashing in the puddles', E'I saw some kids splash in the puddles')),
    jsonb_build_object('number', 10, 'type', 'subjective', 'question', E'다음 두 문장을 <보기>와 같이 한 문장으로 바꾸어 쓰시오.\n\n<보기> I saw some geese. They were flying away.\n→ I saw some geese flying away.\n\nShe noticed the old clock. It was ticking on the wall.', 'answer', E'She noticed the old clock ticking on the wall.', 'similar_answers', jsonb_build_array(E'She noticed the old clock ticking on the wall.', E'She noticed the old clock tick on the wall.', E'She noticed the old clock ticking on the wall', E'She noticed the old clock tick on the wall')),
    jsonb_build_object('number', 11, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 고쳐 올바른 문장으로 바꿔 쓰시오.\n\nI saw a pretty girl to smile at me.', 'answer', E'I saw a pretty girl smile at me.', 'similar_answers', jsonb_build_array(E'I saw a pretty girl smile at me.', E'I saw a pretty girl smiling at me.', E'I saw a pretty girl smile at me', E'I saw a pretty girl smiling at me')),
    jsonb_build_object('number', 12, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 고쳐 올바른 문장으로 바꿔 쓰시오.\n\nThe boy watched his mother ran down the street.', 'answer', E'The boy watched his mother run down the street.', 'similar_answers', jsonb_build_array(E'The boy watched his mother run down the street.', E'The boy watched his mother running down the street.', E'The boy watched his mother run down the street', E'The boy watched his mother running down the street')),
    jsonb_build_object('number', 13, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 고쳐 올바른 문장으로 바꿔 쓰시오.\n\nI saw Ann got on the bus.', 'answer', E'I saw Ann get on the bus.', 'similar_answers', jsonb_build_array(E'I saw Ann get on the bus.', E'I saw Ann getting on the bus.', E'I saw Ann get on the bus', E'I saw Ann getting on the bus')),
    jsonb_build_object('number', 14, 'type', 'subjective', 'question', E'다음 문장에서 어법상 어색한 부분을 고쳐 올바른 문장으로 바꿔 쓰시오.\n\nHe listened to his friends to sing at the concert.', 'answer', E'He listened to his friends sing at the concert.', 'similar_answers', jsonb_build_array(E'He listened to his friends sing at the concert.', E'He listened to his friends singing at the concert.', E'He listened to his friends sing at the concert', E'He listened to his friends singing at the concert')),
    jsonb_build_object('number', 15, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 주어진 단어를 바르게 배열하여 문장을 완성하시오.\n\n나는 Kate가 그림을 그리는 것을 보았다.\n[Kate / a / picture / I / saw / painting]', 'answer', E'I saw Kate painting a picture.', 'similar_answers', jsonb_build_array(E'I saw Kate painting a picture.', E'I saw Kate painting a picture')),
    jsonb_build_object('number', 16, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 주어진 단어를 바르게 배열하여 문장을 완성하시오.\n\n너는 어제 그녀가 노래를 부르는 것을 들었니?\n[you / sing / did / yesterday / hear / songs / her]', 'answer', E'Did you hear her sing songs yesterday?', 'similar_answers', jsonb_build_array(E'Did you hear her sing songs yesterday?', E'Did you hear her sing songs yesterday')),
    jsonb_build_object('number', 17, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 주어진 단어를 바르게 배열하여 문장을 완성하시오.\n\n준호는 누군가가 그의 이름을 부르는 것을 들었다.\n[someone / his name / heard / calling]\n→ Junho ___', 'answer', E'heard someone calling his name.', 'similar_answers', jsonb_build_array(E'heard someone calling his name.', E'heard someone calling his name')),
    jsonb_build_object('number', 18, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 주어진 단어를 바르게 배열하여 문장을 완성하시오.\n\nSori는 한 노인이 기차에서 내리는 것을 보았다.\n[get off / an old man / the train]\n→ Sori saw ___', 'answer', E'an old man get off the train.', 'similar_answers', jsonb_build_array(E'an old man get off the train.', E'an old man getting off the train.', E'an old man get off the train', E'an old man getting off the train')),
    jsonb_build_object('number', 19, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\n나는 그들이 새로운 소프트웨어를 배우는 것을 지켜보았다.\n[watch / new software]', 'answer', E'I watched them learn new software.', 'similar_answers', jsonb_build_array(E'I watched them learn new software.', E'I watched them learning new software.', E'I watched them learn new software', E'I watched them learning new software')),
    jsonb_build_object('number', 20, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\n나는 방안에서 전화가 울리는 것을 들었다.\n[ring / heard / the phone / in the room]', 'answer', E'I heard the phone ring in the room.', 'similar_answers', jsonb_build_array(E'I heard the phone ring in the room.', E'I heard the phone ringing in the room.', E'I heard the phone ring in the room', E'I heard the phone ringing in the room')),
    jsonb_build_object('number', 21, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\nDavid는 파도가 그의 발에 닿는 것을 느꼈다.\n[the waves, touch, feet]\n→ David felt ___', 'answer', E'the waves touch his feet.', 'similar_answers', jsonb_build_array(E'the waves touch his feet.', E'the waves touching his feet.', E'the waves touch his feet', E'the waves touching his feet')),
    jsonb_build_object('number', 22, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\nSue는 새들이 나무에서 노래하는 것을 들었다.\n[birds, sing]\n→ Sue heard ___', 'answer', E'the birds sing in the tree.', 'similar_answers', jsonb_build_array(E'the birds sing in the tree.', E'the birds singing in the tree.', E'the birds sing in the tree', E'the birds singing in the tree')),
    jsonb_build_object('number', 23, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\n나는 많은 학생들이 점심시간에 음식의 거의 절반을 버리는 것을 본다.\n[I / many / throw / half / lunch / almost / time / of / food / away / students / at / see / their]', 'answer', E'I see many students throw away almost half of their food at lunchtime.', 'similar_answers', jsonb_build_array(E'I see many students throw away almost half of their food at lunchtime.', E'I see many students throwing away almost half of their food at lunchtime.', E'I see many students throw away almost half of their food at lunchtime', E'I see many students throwing away almost half of their food at lunchtime')),
    jsonb_build_object('number', 24, 'type', 'subjective', 'question', E'다음 우리말과 일치하도록 괄호 안의 단어를 사용하여 영작하시오.\n\n내가 통화 중에 말하는 걸 들었니?\n[talk / listen / the / hear / phone / on]', 'answer', E'Did you hear me talk on the phone?', 'similar_answers', jsonb_build_array(E'Did you hear me talk on the phone?', E'Did you hear me talking on the phone?', E'Did you hear me talk on the phone', E'Did you hear me talking on the phone')),
    jsonb_build_object('number', 25, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. 지각동사를 어법에 맞게 사용할 것\n2. 완전한 문장으로 쓸 것\n\n나는 내 친구가 내 이름을 부르는 것을 들었다.', 'answer', E'I heard my friend call my name.', 'similar_answers', jsonb_build_array(E'I heard my friend call my name.', E'I heard my friend calling my name.', E'I heard my friend call my name', E'I heard my friend calling my name')),
    jsonb_build_object('number', 26, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. watch를 사용할 것\n2. 5단어로 쓸 것\n\n그녀는 그들이 축구하고 있는 것을 지켜보았다.', 'answer', E'She watched them play soccer.', 'similar_answers', jsonb_build_array(E'She watched them play soccer.', E'She watched them play soccer')),
    jsonb_build_object('number', 27, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. 지각동사를 사용할 것\n2. 우리말에 맞는 시제로 영작할 것\n\n(1) 새들이 하늘 위로 날아오르는 것을 그녀는 보았다.\n(2) 집 전체가 흔들리는 것을 그는 느꼈다.', 'answer', E'(1) She saw birds fly up into the sky. (2) He felt the whole house shake.', 'similar_answers', jsonb_build_array(E'(1) She saw birds fly up into the sky. (2) He felt the whole house shake.', E'(1) She saw birds flying up into the sky. (2) He felt the whole house shaking.', E'(1) She saw birds fly up into the sky. (2) He felt the whole house shaking.', E'(1) She saw birds flying up into the sky. (2) He felt the whole house shake.')),
    jsonb_build_object('number', 28, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n<조건>\n1. <보기>의 단어를 모두 활용할 것 (형태 변형 가능)\n2. 완전한 문장으로 쓸 것\n<보기> We / Ms. Wilson / hear / sing / "Yesterday"\n\n우리는 Ms. Wilson이 "Yesterday"를 부르는 것을 들었다.', 'answer', E'We heard Ms. Wilson sing "Yesterday".', 'similar_answers', jsonb_build_array(E'We heard Ms. Wilson sing "Yesterday".', E'We heard Ms. Wilson singing "Yesterday".', E'We heard Ms. Wilson sing "Yesterday"', E'We heard Ms. Wilson singing "Yesterday"')),
    jsonb_build_object('number', 29, 'type', 'subjective', 'question', E'다음 이야기의 빈칸에 <보기>의 동사를 알맞은 형태로 넣어 완성하시오.\n\n<보기> breathe / follow / move / run / watch\n\nOne night I was walking home alone and started to feel uneasy. I found myself on a quiet street and could sense I wasn''t alone. I could feel someone (1)___ me and I was sure I could hear their footsteps (2)___ behind me. I stopped and listened carefully. Yes! There it was. I could hear someone (3)___ loudly. I turned quickly and saw something (4)___ out of the corner of my eye. Then ... BANG! The last thing I remember is that I heard the sound of feet (5)___ away and then I woke up in the hospital.\n\n위 빈칸 (1)에 알맞은 단어를 쓰시오.', 'answer', E'following', 'similar_answers', jsonb_build_array(E'following', E'follow')),
    jsonb_build_object('number', 30, 'type', 'subjective', 'question', E'다음 이야기의 빈칸에 <보기>의 동사를 알맞은 형태로 넣어 완성하시오.\n\n<보기> breathe / follow / move / run / watch\n\nOne night I was walking home alone and started to feel uneasy. I found myself on a quiet street and could sense I wasn''t alone. I could feel someone (1)___ me and I was sure I could hear their footsteps (2)___ behind me. I stopped and listened carefully. Yes! There it was. I could hear someone (3)___ loudly. I turned quickly and saw something (4)___ out of the corner of my eye. Then ... BANG! The last thing I remember is that I heard the sound of feet (5)___ away and then I woke up in the hospital.\n\n위 빈칸 (2)에 알맞은 단어를 쓰시오.', 'answer', E'moving', 'similar_answers', jsonb_build_array(E'moving', E'move')),
    jsonb_build_object('number', 31, 'type', 'subjective', 'question', E'다음 이야기의 빈칸에 <보기>의 동사를 알맞은 형태로 넣어 완성하시오.\n\n<보기> breathe / follow / move / run / watch\n\nOne night I was walking home alone and started to feel uneasy. I found myself on a quiet street and could sense I wasn''t alone. I could feel someone (1)___ me and I was sure I could hear their footsteps (2)___ behind me. I stopped and listened carefully. Yes! There it was. I could hear someone (3)___ loudly. I turned quickly and saw something (4)___ out of the corner of my eye. Then ... BANG! The last thing I remember is that I heard the sound of feet (5)___ away and then I woke up in the hospital.\n\n위 빈칸 (3)에 알맞은 단어를 쓰시오.', 'answer', E'breathing', 'similar_answers', jsonb_build_array(E'breathing', E'breathe')),
    jsonb_build_object('number', 32, 'type', 'subjective', 'question', E'다음 이야기의 빈칸에 <보기>의 동사를 알맞은 형태로 넣어 완성하시오.\n\n<보기> breathe / follow / move / run / watch\n\nOne night I was walking home alone and started to feel uneasy. I found myself on a quiet street and could sense I wasn''t alone. I could feel someone (1)___ me and I was sure I could hear their footsteps (2)___ behind me. I stopped and listened carefully. Yes! There it was. I could hear someone (3)___ loudly. I turned quickly and saw something (4)___ out of the corner of my eye. Then ... BANG! The last thing I remember is that I heard the sound of feet (5)___ away and then I woke up in the hospital.\n\n위 빈칸 (4)에 알맞은 단어를 쓰시오.', 'answer', E'moving', 'similar_answers', jsonb_build_array(E'moving', E'watching')),
    jsonb_build_object('number', 33, 'type', 'subjective', 'question', E'다음 이야기의 빈칸에 <보기>의 동사를 알맞은 형태로 넣어 완성하시오.\n\n<보기> breathe / follow / move / run / watch\n\nOne night I was walking home alone and started to feel uneasy. I found myself on a quiet street and could sense I wasn''t alone. I could feel someone (1)___ me and I was sure I could hear their footsteps (2)___ behind me. I stopped and listened carefully. Yes! There it was. I could hear someone (3)___ loudly. I turned quickly and saw something (4)___ out of the corner of my eye. Then ... BANG! The last thing I remember is that I heard the sound of feet (5)___ away and then I woke up in the hospital.\n\n위 빈칸 (5)에 알맞은 단어를 쓰시오.', 'answer', E'running', 'similar_answers', jsonb_build_array(E'running', E'run')),
    jsonb_build_object('number', 34, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 완전한 영어 문장으로 쓰시오.\n\n<조건>\n1. <보기>의 단어를 모두 한 번씩 사용할 것\n2. 필요시 형태 변형 가능, 추가 단어 없음\n<보기> I / many / throw / half / lunch / almost / time / of / food / away / students / at / see / their\n\n나는 많은 학생들이 점심시간에 음식의 거의 절반을 버리는 것을 본다.', 'answer', E'I see many students throw away almost half of their food at lunchtime.', 'similar_answers', jsonb_build_array(E'I see many students throw away almost half of their food at lunchtime.', E'I see many students throwing away almost half of their food at lunchtime.', E'I see many students throw away almost half of their food at lunchtime', E'I see many students throwing away almost half of their food at lunchtime')),
    jsonb_build_object('number', 35, 'type', 'subjective', 'question', E'다음 우리말을 주어진 조건에 맞게 완전한 영어 문장으로 쓰시오.\n\n<조건>\n1. [주어+동사+목적어+목적격보어] 형식의 완전한 문장으로 쓸 것\n2. 지각동사를 3가지 사용하여 각각 한 문장씩 쓸 것\n3. 주방 상황을 묘사할 것 (냄새, 소리, 시각 각각)\n\n상황: 나는 주방에서 음식이 타는 냄새를 맡았고, 물이 끓는 소리를 들었으며, 연기가 피어오르는 것을 보았다.\n\n(1) →\n(2) →\n(3) →', 'answer', E'(1) I smelled something burning in the kitchen. (2) I heard the water boiling on the stove. (3) I saw smoke rising from the pot.', 'similar_answers', jsonb_build_array(E'(1) I smelled something burning in the kitchen. (2) I heard the water boiling on the stove. (3) I saw smoke rising from the pot.', E'(1) I smelled something burn in the kitchen. (2) I heard the water boil on the stove. (3) I saw smoke rise from the pot.'))  );

  v_answer_key := jsonb_build_array(
    jsonb_build_object('number',1, 'answer',E'you win'),
    jsonb_build_object('number',2, 'answer',E'her crying'),
    jsonb_build_object('number',3, 'answer',E'them cheer'),
    jsonb_build_object('number',4, 'answer',E'the pianist play'),
    jsonb_build_object('number',5, 'answer',E'I heard my cat purring on the bed.'),
    jsonb_build_object('number',6, 'answer',E'She saw her teammate sprinting toward the goal.'),
    jsonb_build_object('number',7, 'answer',E'Jimin watched his little sister drawing at the table.'),
    jsonb_build_object('number',8, 'answer',E'He saw his puppy chasing its tail.'),
    jsonb_build_object('number',9, 'answer',E'I saw some kids splashing in the puddles.'),
    jsonb_build_object('number',10, 'answer',E'She noticed the old clock ticking on the wall.'),
    jsonb_build_object('number',11, 'answer',E'I saw a pretty girl smile at me.'),
    jsonb_build_object('number',12, 'answer',E'The boy watched his mother run down the street.'),
    jsonb_build_object('number',13, 'answer',E'I saw Ann get on the bus.'),
    jsonb_build_object('number',14, 'answer',E'He listened to his friends sing at the concert.'),
    jsonb_build_object('number',15, 'answer',E'I saw Kate painting a picture.'),
    jsonb_build_object('number',16, 'answer',E'Did you hear her sing songs yesterday?'),
    jsonb_build_object('number',17, 'answer',E'heard someone calling his name.'),
    jsonb_build_object('number',18, 'answer',E'an old man get off the train.'),
    jsonb_build_object('number',19, 'answer',E'I watched them learn new software.'),
    jsonb_build_object('number',20, 'answer',E'I heard the phone ring in the room.'),
    jsonb_build_object('number',21, 'answer',E'the waves touch his feet.'),
    jsonb_build_object('number',22, 'answer',E'the birds sing in the tree.'),
    jsonb_build_object('number',23, 'answer',E'I see many students throw away almost half of their food at lunchtime.'),
    jsonb_build_object('number',24, 'answer',E'Did you hear me talk on the phone?'),
    jsonb_build_object('number',25, 'answer',E'I heard my friend call my name.'),
    jsonb_build_object('number',26, 'answer',E'She watched them play soccer.'),
    jsonb_build_object('number',27, 'answer',E'(1) She saw birds fly up into the sky. (2) He felt the whole house shake.'),
    jsonb_build_object('number',28, 'answer',E'We heard Ms. Wilson sing "Yesterday".'),
    jsonb_build_object('number',29, 'answer',E'following'),
    jsonb_build_object('number',30, 'answer',E'moving'),
    jsonb_build_object('number',31, 'answer',E'breathing'),
    jsonb_build_object('number',32, 'answer',E'moving'),
    jsonb_build_object('number',33, 'answer',E'running'),
    jsonb_build_object('number',34, 'answer',E'I see many students throw away almost half of their food at lunchtime.'),
    jsonb_build_object('number',35, 'answer',E'(1) I smelled something burning in the kitchen. (2) I heard the water boiling on the stove. (3) I saw smoke rising from the pot.')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('지각동사 Step3', '지각동사', v_questions, v_answer_key, 'problem', 'interactive');
END;
$$;
