DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates
  WHERE template_topic = '관계대명사의 계속적 용법'
    AND title LIKE '%Step 3%';

  q := jsonb_build_array(
    jsonb_build_object('number', 1,
  'question', E'[Part 1] 다음 우리말을 영어로 쓸 때, 빈칸에 알맞은 관계대명사를 쓰시오.\n\n(1) 나는 강아지를 한 마리 키우는데, 그것은 아침마다 나를 깨운다.\n→ I have a puppy, __________ wakes me up every morning.\n\n(2) 그는 유명한 소설가인데, 그의 책은 20개국에서 팔렸다.\n→ He is a famous novelist, __________ books have been sold in 20 countries.\n\n(3) 나는 그에게 솔직하게 말했는데, 그것이 결국 우리 관계를 더 좋게 만들었다.\n→ I spoke to him honestly, __________ eventually made our relationship better.\n\n(4) 우리 반에는 친구가 하나 있는데, 그는 다섯 개의 언어를 할 수 있다.\n→ I have a friend in my class, __________ can speak five languages.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'which', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(2)', 'answer', E'whose', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(3)', 'answer', E'which', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(4)', 'answer', E'who', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'which / whose / which / who',
  'explanation', E'(1) puppy(사물) 주격 → which (2) 소유격 → whose (3) 앞 문장 전체 → which (4) friend(사람) 주격 → who'),

jsonb_build_object('number', 2,
  'question', E'다음 주어진 정보를 이용하여 보기와 같이 문장을 완성하시오.\n\n[보기] Mona Lisa — It was painted by Leonardo da Vinci.\n→ This is the Mona Lisa, which was painted by Leonardo da Vinci.\n\n• Bulguksa Temple — It was built during the Silla Dynasty.\n• Albert Einstein — He developed the theory of relativity.\n• The Amazon River — It is the longest river in South America.\n\n(1) This is Bulguksa Temple, _________________________________________.\n(2) This is Albert Einstein, __________________________________________.\n(3) This is the Amazon River, _________________________________________.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'which was built during the Silla Dynasty', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(2)', 'answer', E'who developed the theory of relativity', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(3)', 'answer', E'which is the longest river in South America', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'which was built during the Silla Dynasty / who developed the theory of relativity / which is the longest river in South America',
  'explanation', E'(1) Bulguksa Temple(사물) → which (2) Albert Einstein(사람) → who (3) The Amazon River(사물) → which'),

jsonb_build_object('number', 3,
  'question', E'다음 사람들의 계획을 보고 보기와 같이 문장을 완성하시오.\n\n[보기] Junho — going to see his dentist / She is very gentle and skillful.\n→ Junho is going to see his dentist, who is very gentle and skillful.\n\nSoyeon — planning to read Demian / It is her favorite novel of all time.\nTaeyang — going to visit his grandfather / He lives alone in a small village.\nNaeun — planning to join a cooking class / It opened just last week.\n\n(1) Soyeon → ___________________________________________________\n(2) Taeyang → __________________________________________________\n(3) Naeun → ____________________________________________________',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'Soyeon is planning to read Demian, which is her favorite novel of all time.', 'acceptedAnswers', jsonb_build_array(E'Soyeon is planning to read Demian, which is her favorite novel of all time')),
    jsonb_build_object('label', E'(2)', 'answer', E'Taeyang is going to visit his grandfather, who lives alone in a small village.', 'acceptedAnswers', jsonb_build_array(E'Taeyang is going to visit his grandfather, who lives alone in a small village')),
    jsonb_build_object('label', E'(3)', 'answer', E'Naeun is planning to join a cooking class, which opened just last week.', 'acceptedAnswers', jsonb_build_array(E'Naeun is planning to join a cooking class, which opened just last week'))
  ),
  'answer', E'Soyeon is planning to read Demian, which is her favorite novel of all time. / Taeyang is going to visit his grandfather, who lives alone in a small village. / Naeun is planning to join a cooking class, which opened just last week.',
  'explanation', E'(1) Demian(사물) → which (2) grandfather(사람) → who (3) cooking class(사물) → which'),

jsonb_build_object('number', 4,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 관계대명사를 쓰시오.\n\n(1) She returned all the money she owed, and it impressed everyone.\n→ She returned all the money she owed, __________ impressed everyone.\n\n(2) We all like Coach Bae, for he always puts the team first.\n→ We all like Coach Bae, __________ always puts the team first.\n\n(3) I went to the new gallery, but it was closed for a private event.\n→ I went to the new gallery, __________ was closed for a private event.\n\n(4) She has two daughters, and they are both studying architecture.\n→ She has two daughters, __________ are both studying architecture.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'which', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(2)', 'answer', E'who', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(3)', 'answer', E'which', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(4)', 'answer', E'who', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'which / who / which / who',
  'explanation', E'(1) and it → which (2) for he → who (3) but it → which (4) and they → who'),

jsonb_build_object('number', 5,
  'question', E'다음 분실물 보관소의 물건들을 보고, 관계대명사를 사용하여 문장을 완성하시오.\n\n[보기] bag — left on the train on April 3rd\n→ I lost my bag, which I left on the train on April 3rd.\n\n• water bottle — found near the school entrance\n• gray hoodie — covered in paint stains\n• laptop — made in Germany\n\n(1) I''m looking for my water bottle, ___________________________________.\n(2) I lost my gray hoodie, ____________________________________________.\n(3) I''m trying to find my laptop, _______________________________________.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'which was found near the school entrance', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'(2)', 'answer', E'which was covered in paint stains', 'acceptedAnswers', jsonb_build_array(E'which is covered in paint stains')),
    jsonb_build_object('label', E'(3)', 'answer', E'which was made in Germany', 'acceptedAnswers', jsonb_build_array(E'which is made in Germany'))
  ),
  'answer', E'which was found near the school entrance / which was covered in paint stains / which was made in Germany',
  'explanation', E'모두 사물 선행사 → which'),

jsonb_build_object('number', 6,
  'question', E'다음 which의 선행사를 각각 쓰시오.\n\n(1) She forgot to set her alarm, which made her miss the first class.\n→ 선행사: ___________________________\n\n(2) I visited the old library, which had recently been restored.\n→ 선행사: ___________________________\n\n(3) He said he had finished the report, which was not true at all.\n→ 선행사: ___________________________',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'(1)', 'answer', E'She forgot to set her alarm', 'acceptedAnswers', jsonb_build_array(E'앞 문장 전체', E'she forgot to set her alarm(앞 문장 전체)')),
    jsonb_build_object('label', E'(2)', 'answer', E'the old library', 'acceptedAnswers', jsonb_build_array(E'old library', E'the library')),
    jsonb_build_object('label', E'(3)', 'answer', E'He said he had finished the report', 'acceptedAnswers', jsonb_build_array(E'앞 문장 전체', E'he said he had finished the report(앞 문장 전체)'))
  ),
  'answer', E'She forgot to set her alarm / the old library / He said he had finished the report',
  'explanation', E'(1),(3) 앞 문장 전체가 선행사 (2) 특정 명사가 선행사'),

jsonb_build_object('number', 7,
  'question', E'다음 두 문장의 의미 차이를 우리말로 설명하시오.\n\na. I have a brother who works at a hospital.\nb. I have a brother, who works at a hospital.\n\na의 의미:\nb의 의미:\n차이점:',
  'answer', E'a — 나는 (여러 형제 중) 병원에서 일하는 형제가 있다. (형제가 더 있을 수 있음) / b — 나는 형제가 한 명 있는데, 그는 병원에서 일한다. (형제가 한 명뿐) / 차이점: 콤마(,)의 유무에 따라 a는 한정적 용법(범위를 제한), b는 계속적 용법(부가 정보 제공)으로 쓰임.',
  'acceptedAnswers', jsonb_build_array(E'a: 여러 형제 중 병원에서 일하는 형제가 있다 / b: 형제가 한 명뿐이며 그가 병원에서 일한다'),
  'explanation', E'a(한정적 용법): 범위 제한, b(계속적 용법): 부가 정보'),

jsonb_build_object('number', 8,
  'question', E'다음 두 문장의 의미 차이를 우리말로 설명하시오.\n\na. She has friends who support her through everything.\nb. She has friends, who support her through everything.\n\na의 의미:\nb의 의미:',
  'answer', E'a — 그녀에게는 (여러 친구들 중에서) 어떤 상황에서도 그녀를 지지해주는 친구들이 있다. / b — 그녀에게는 친구들이 있는데, 그들은 어떤 상황에서도 그녀를 지지해준다.',
  'acceptedAnswers', jsonb_build_array(E'a: 모든 친구가 아닌 일부 친구만 지지 / b: 친구들 전부가 그녀를 지지한다는 부연 설명'),
  'explanation', E'a(한정적): 일부 친구, b(계속적): 친구 전부에 대한 부연'),

jsonb_build_object('number', 9,
  'question', E'[Part 2] 다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nI finally met the author of my favorite book. + She signed my copy and chatted with me for ten minutes.',
  'answer', E'I finally met the author of my favorite book, who signed my copy and chatted with me for ten minutes.',
  'acceptedAnswers', jsonb_build_array(E'I finally met the author of my favorite book, who signed my copy and chatted with me for 10 minutes.'),
  'explanation', E'the author(사람) → who, 부가 설명을 계속적 용법으로 연결'),

jsonb_build_object('number', 10,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nWe took the scenic coastal road to Busan. + It added an extra hour to our journey but was absolutely worth it.',
  'answer', E'We took the scenic coastal road to Busan, which added an extra hour to our journey but was absolutely worth it.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'the scenic coastal road(사물) → which, 부가 설명을 계속적 용법으로 연결'),

jsonb_build_object('number', 11,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nShe said nothing during the entire meeting. + It made everyone feel uncomfortable.',
  'answer', E'She said nothing during the entire meeting, which made everyone feel uncomfortable.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'앞 문장 전체가 선행사 → which'),

jsonb_build_object('number', 12,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nMy grandfather made this wooden chair himself. + He is now 75 years old and lives in the countryside.',
  'answer', E'My grandfather, who is now 75 years old and lives in the countryside, made this wooden chair himself.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'My grandfather(사람) → who, 문장 중간에 삽입하여 부가 설명'),

jsonb_build_object('number', 13,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nThey announced that school would be canceled due to the snowstorm. + This news delighted every single student.',
  'answer', E'They announced that school would be canceled due to the snowstorm, which delighted every single student.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'앞 문장 전체가 선행사 → which'),

jsonb_build_object('number', 14,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nI bumped into my elementary school teacher at the supermarket. + She still remembered my name after all these years.',
  'answer', E'I bumped into my elementary school teacher at the supermarket, who still remembered my name after all these years.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'my elementary school teacher(사람) → who, 부가 설명을 계속적 용법으로 연결'),

jsonb_build_object('number', 15,
  'question', E'다음 세 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\n• I have one older sister.\n• She is a pediatric nurse.\n• She has worked at Seoul Children''s Hospital for seven years.',
  'answer', E'I have one older sister, who is a pediatric nurse and has worked at Seoul Children''s Hospital for seven years.',
  'acceptedAnswers', jsonb_build_array(E'I have one older sister, who is a pediatric nurse and has worked at Seoul Children''s Hospital for 7 years.'),
  'explanation', E'one older sister(사람, 한 명뿐) → who, 두 가지 정보를 and로 연결'),

jsonb_build_object('number', 16,
  'question', E'다음 세 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\n• The new community center will open in March.\n• It can hold up to 500 people.\n• It was built with donations from local residents.',
  'answer', E'The new community center, which can hold up to 500 people and was built with donations from local residents, will open in March.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'The new community center(사물) → which, 문장 중간에 삽입하여 두 가지 부가 설명을 and로 연결'),

jsonb_build_object('number', 17,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nHe practiced his speech over a hundred times. + This level of dedication eventually paid off on the big day.',
  'answer', E'He practiced his speech over a hundred times, which eventually paid off on the big day.',
  'acceptedAnswers', jsonb_build_array(E'He practiced his speech over a hundred times, which eventually paid off on the big day'),
  'explanation', E'앞 문장 전체가 선행사 → which'),

jsonb_build_object('number', 18,
  'question', E'다음 두 문장을 관계대명사의 계속적 용법을 이용하여 한 문장으로 쓰시오.\n\nMy best friend moved to a different city for university. + She calls me every single day without fail.',
  'answer', E'My best friend, who calls me every single day without fail, moved to a different city for university.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'My best friend(사람) → who, 문장 중간에 삽입하여 부가 설명'),

jsonb_build_object('number', 19,
  'question', E'[Part 3] 다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nShe won the gold medal, and it brought tears to her eyes.\n→ She won the gold medal, __________ brought tears to her eyes.',
  'answer', E'which',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'and it → which (앞 내용을 받는 계속적 용법)'),

jsonb_build_object('number', 20,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nHe has three sons, who are all working in the tech industry.\n→ He has three sons, __________ __________ are all working in the tech industry.',
  'answer', E'and they',
  'acceptedAnswers', jsonb_build_array(E'and they'),
  'explanation', E', who → and they (계속적 용법을 접속사+대명사로 전환)'),

jsonb_build_object('number', 21,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nI don''t like my new boss, for she micromanages everything we do.\n→ I don''t like my new boss, __________ micromanages everything we do.',
  'answer', E'who',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'for she → who (계속적 용법으로 전환, 사람 주격)'),

jsonb_build_object('number', 22,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nShe forgot to mention the most important detail, which confused the entire audience.\n→ She forgot to mention the most important detail, __________ __________ confused the entire audience.',
  'answer', E'and it',
  'acceptedAnswers', jsonb_build_array(E'and this', E'and that'),
  'explanation', E', which → and it (계속적 용법을 접속사+대명사로 전환)'),

jsonb_build_object('number', 23,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nI tried to fix the leaking pipe myself, but it only made things worse.\n→ I tried to fix the leaking pipe myself, __________ only made things worse.',
  'answer', E'which',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'but it → which (앞 문장 전체가 선행사, 계속적 용법)'),

jsonb_build_object('number', 24,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nThe Dark Knight is one of my all-time favorite films, and I have watched it six times.\n→ The Dark Knight, __________ __________ __________ __________ __________, is one of my all-time favorite films.',
  'answer', E'which I have watched six times',
  'acceptedAnswers', jsonb_build_array(E'which i have watched six times', E'which I have watched 6 times'),
  'explanation', E'and I have watched it six times → which I have watched six times (계속적 용법, 문장 중간 삽입)'),

jsonb_build_object('number', 25,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nShe is a gifted musician, who doesn''t practice nearly as much as she should.\n→ She is a gifted musician, __________ __________ __________ __________ __________ __________ __________ __________.',
  'answer', E'but she doesn''t practice nearly as much as she should',
  'acceptedAnswers', jsonb_build_array(E'but she does not practice nearly as much as she should'),
  'explanation', E', who doesn''t → but she doesn''t (계속적 용법을 접속사+대명사로 전환)'),

jsonb_build_object('number', 26,
  'question', E'다음 두 문장이 같은 의미가 되도록 빈칸에 알맞은 말을 쓰시오.\n\nHe claimed he had never met her before, which turned out to be completely false.\n→ He claimed he had never met her before, __________ __________ __________ __________ __________ __________.',
  'answer', E'but it turned out to be completely false',
  'acceptedAnswers', jsonb_build_array(E'but that turned out to be completely false', E'but this turned out to be completely false'),
  'explanation', E', which turned out → but it turned out (계속적 용법을 접속사+대명사로 전환)'),

jsonb_build_object('number', 27,
  'question', E'[Part 4] 주어진 상황에 맞는 문장을 고르고, 두 문장의 의미 차이를 우리말로 설명하시오.\n\n[상황] Mira has only one cat. It knocks things off the table constantly.\n\na. Mira''s cat which knocks things off the table is very naughty.\nb. Mira''s cat, which knocks things off the table, is very naughty.\n\n정답:\n이유:\n두 문장의 의미 차이:',
  'answer', E'b / 이유: 고양이가 한 마리뿐이므로 계속적 용법(콤마+which)을 씀. / 차이: a는 여러 고양이 중 물건을 떨어뜨리는 특정 고양이를 가리킴. b는 고양이가 한 마리뿐이며 그에 대한 부가 설명을 제공함.',
  'acceptedAnswers', jsonb_build_array(E'b'),
  'explanation', E'고양이가 한 마리뿐 → 한정할 필요 없음 → 계속적 용법(b)이 적절'),

jsonb_build_object('number', 28,
  'question', E'다음 상황에서 적절한 문장을 고르고, 그 이유를 우리말로 설명하시오.\n\n[상황] Jaeho has four cousins. Only one of them is a doctor.\n\na. Jaeho''s cousin who is a doctor works at a university hospital.\nb. Jaeho''s cousin, who is a doctor, works at a university hospital.\n\n적절한 문장:\n이유:',
  'answer', E'a / 이유: 사촌이 여럿이므로 의사인 사촌을 한정하는 한정적 용법이 적절.',
  'acceptedAnswers', jsonb_build_array(E'a'),
  'explanation', E'사촌이 4명 → 특정 사촌을 한정 → 한정적 용법(a)이 적절'),

jsonb_build_object('number', 29,
  'question', E'다음 두 문장을 각각 우리말로 해석하시오.\n\na. Students who submit their assignments late will lose points.\nb. Students, who submit their assignments late, will lose points.\n\na의 의미:\nb의 의미:',
  'answer', E'a — 과제를 늦게 내는 학생들(만)은 점수를 잃을 것이다. / b — 학생들은 과제를 늦게 내는데, 그들은 점수를 잃을 것이다. (모든 학생들이 과제를 늦게 낸다는 뜻이 되어 어색한 문장)',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'a(한정적): 늦게 내는 학생만 해당, b(계속적): 모든 학생이 늦게 낸다는 의미가 되어 부자연스러움'),

jsonb_build_object('number', 30,
  'question', E'다음 두 문장을 각각 우리말로 해석하고, 친구가 한 명뿐인 상황에서 더 자연스러운 문장을 고르시오.\n\na. I have a friend who always tells me the truth.\nb. I have a friend, who always tells me the truth.\n\na의 의미:\nb의 의미:\n더 자연스러운 문장:',
  'answer', E'a — 나는 (여러 친구 중) 항상 솔직하게 말해주는 친구가 있다. / b — 나는 친구가 한 명 있는데, 그는 항상 나에게 솔직하게 말해준다. / b',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'친구가 한 명뿐 → 한정할 필요 없음 → 계속적 용법(b)이 더 자연스러움'),

jsonb_build_object('number', 31,
  'question', E'다음 두 문장 중 상황에 더 적절한 문장을 고르고, 그 이유를 우리말로 설명하시오.\n\na. The players who gave their best effort deserve a reward.\nb. Our team, who gave their best effort, deserves a reward.\n\n적절한 문장:\n이유:',
  'answer', E'b / 이유: Our team은 특정한 하나의 팀이므로 추가 설명을 제공하는 계속적 용법이 자연스럽고, 한정할 필요가 없음.',
  'acceptedAnswers', jsonb_build_array(E'b'),
  'explanation', E'Our team은 이미 특정된 대상 → 계속적 용법(b)이 적절'),

jsonb_build_object('number', 32,
  'question', E'다음 우리말을 영어로 옮길 때, 적절한 문장을 고르고, 그 이유를 우리말로 설명하시오.\n\n[우리말] 나에게는 남동생이 한 명 있는데, 그는 요즘 수능 준비를 하고 있다.\n\na. I have a brother who is preparing for the college entrance exam these days.\nb. I have a brother, who is preparing for the college entrance exam these days.\n\n적절한 문장:\n이유:',
  'answer', E'b / 이유: 남동생이 한 명뿐임을 나타내므로 계속적 용법(콤마+who)이 적절.',
  'acceptedAnswers', jsonb_build_array(E'b'),
  'explanation', E'남동생 한 명뿐 → 한정 불필요 → 계속적 용법(b)이 적절'),
    jsonb_build_object('number', 33,
  'question', E'[Part 5] 다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nMy science teacher, that has won several research awards, is retiring next semester.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'that', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'who', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'that / who',
  'explanation', E'계속적 용법(콤마 뒤)에서는 that을 관계대명사로 쓸 수 없으며, 선행사가 사람(My science teacher)이므로 who를 써야 한다.'),
jsonb_build_object('number', 34,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nShe confessed to cheating on the exam, what shocked the entire class.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'what', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'what / which',
  'explanation', E'계속적 용법에서는 what을 사용할 수 없다. 앞 문장 전체를 선행사로 받으므로 which를 써야 한다.'),
jsonb_build_object('number', 35,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nHe returned the wallet he had found, which it earned him great praise from everyone.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'which it', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'which it / which',
  'explanation', E'관계대명사 which가 주어 역할을 하므로 대명사 it을 함께 쓰면 주어가 중복된다. it을 삭제해야 한다.'),
jsonb_build_object('number', 36,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nMy parents, who has been married for 35 years, still hold hands when they walk.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'has', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'have', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'has / have',
  'explanation', E'선행사 My parents가 복수이므로, 관계대명사절의 동사도 복수형 have를 써야 한다.'),
jsonb_build_object('number', 37,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nShe decided to quit social media completely, who was the best decision she ever made.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'who', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'who / which',
  'explanation', E'선행사가 앞 문장 전체(소셜 미디어를 완전히 끊기로 한 것)이므로 사물을 받는 which를 써야 한다. who는 사람에게만 쓴다.'),
jsonb_build_object('number', 38,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nI finally found my lost journal, whom I had been searching for all week.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'whom', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'whom / which',
  'explanation', E'선행사 my lost journal은 사물이므로 whom(사람 목적격) 대신 which를 써야 한다.'),
jsonb_build_object('number', 39,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nHe introduced me to his colleague Dr. Min, which is an expert in renewable energy.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'which', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'who', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'which / who',
  'explanation', E'선행사 Dr. Min은 사람이므로 which 대신 who를 써야 한다.'),
jsonb_build_object('number', 40,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nShe stayed calm throughout the entire crisis, and which impressed her team greatly.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'and which', 'acceptedAnswers', jsonb_build_array(E', and which')),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array(E', which'))
  ),
  'answer', E'and which / which',
  'explanation', E'계속적 용법에서 접속사 and와 관계대명사 which를 동시에 쓸 수 없다. and를 삭제해야 한다.'),
jsonb_build_object('number', 41,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nI have two older brothers, who is both studying abroad right now.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'is', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'are', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'is / are',
  'explanation', E'선행사 two older brothers가 복수이므로, 관계대명사절의 동사도 복수형 are를 써야 한다.'),
jsonb_build_object('number', 42,
  'question', E'다음 문장에서 어법상 어색한 부분을 찾아 고치시오.\n\nShe told me her address, that I wrote down carefully in my notebook.',
  'subParts', jsonb_build_array(
    jsonb_build_object('label', E'틀린 부분', 'answer', E'that', 'acceptedAnswers', jsonb_build_array()),
    jsonb_build_object('label', E'고친 표현', 'answer', E'which', 'acceptedAnswers', jsonb_build_array())
  ),
  'answer', E'that / which',
  'explanation', E'계속적 용법(콤마 뒤)에서는 that을 관계대명사로 쓸 수 없다. 선행사 her address는 사물이므로 which를 써야 한다.'),
jsonb_build_object('number', 43,
  'question', E'[Part 6] 다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ Last week, I met my childhood friend Sujin at a café downtown.\nⓑ She had just returned from a year in Canada, that had changed her a lot.\nⓒ We talked for hours, and which made both of us feel like no time had passed.\nⓓ She told me about her host family in Vancouver, who were incredibly warm and welcoming.\nⓔ She also brought me a small gift, what I found very thoughtful.',
  'answer', E'ⓑ, ⓒ, ⓔ\nⓑ → She had just returned from a year in Canada, which had changed her a lot.\nⓒ → We talked for hours, which made both of us feel like no time had passed.\nⓔ → She also brought me a small gift, which I found very thoughtful.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓑ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓒ 접속사 and와 관계대명사 which를 동시에 쓸 수 없으므로 and를 삭제한다. ⓔ 계속적 용법에서는 what을 쓸 수 없으므로 which로 고쳐야 한다.'),
jsonb_build_object('number', 44,
  'question', E'다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ My uncle, who have worked as a marine biologist for over twenty years, is truly inspiring.\nⓑ He studies deep-sea creatures, that are rarely seen by humans.\nⓒ Last month, he discovered a new species of jellyfish, which he named after his daughter.\nⓓ The news was covered by major media outlets, what brought him worldwide attention.\nⓔ His dedication to science, which I deeply admire, motivates me every day.',
  'answer', E'ⓐ, ⓑ, ⓓ\nⓐ → My uncle, who has worked as a marine biologist for over twenty years, is truly inspiring.\nⓑ → He studies deep-sea creatures, which are rarely seen by humans.\nⓓ → The news was covered by major media outlets, which brought him worldwide attention.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓐ 선행사 My uncle이 단수이므로 have를 has로 고쳐야 한다. ⓑ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓓ 계속적 용법에서는 what을 쓸 수 없으므로 which로 고쳐야 한다.'),
jsonb_build_object('number', 45,
  'question', E'다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ This is my homeroom teacher, Ms. Park, which has taught English for fifteen years.\nⓑ She is known for her creative lessons, who always keep students engaged.\nⓒ Last semester, she organized a school debate competition, which was a great success.\nⓓ She also recommended several novels to me, that I found extremely helpful for my writing.\nⓔ I am grateful to have her as my teacher, which has shaped who I am today.',
  'answer', E'ⓐ, ⓑ, ⓓ\nⓐ → This is my homeroom teacher, Ms. Park, who has taught English for fifteen years.\nⓑ → She is known for her creative lessons, which always keep students engaged.\nⓓ → She also recommended several novels to me, which I found extremely helpful for my writing.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓐ 선행사 Ms. Park은 사람이므로 which를 who로 고쳐야 한다. ⓑ 선행사 her creative lessons는 사물이므로 who를 which로 고쳐야 한다. ⓓ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓔ는 선행사가 앞 문장 전체이므로 which가 올바르다.'),
jsonb_build_object('number', 46,
  'question', E'다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ A few years ago, a typhoon hit our town, who caused serious damage to many buildings.\nⓑ My family, which had lived in the area for decades, had to evacuate immediately.\nⓒ We stayed at a community shelter, that provided food and basic supplies.\nⓓ Volunteers came from all over the country, which moved us deeply.\nⓔ One volunteer, which became a close friend of mine, still keeps in touch with our family.',
  'answer', E'ⓐ, ⓑ, ⓒ, ⓔ\nⓐ → A few years ago, a typhoon hit our town, which caused serious damage to many buildings.\nⓑ → My family, who had lived in the area for decades, had to evacuate immediately.\nⓒ → We stayed at a community shelter, which provided food and basic supplies.\nⓔ → One volunteer, who became a close friend of mine, still keeps in touch with our family.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓐ 선행사 a typhoon은 사물이므로 who를 which로 고쳐야 한다. ⓑ 선행사 My family는 사람이므로 which를 who로 고쳐야 한다. ⓒ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓔ 선행사 One volunteer는 사람이므로 which를 who로 고쳐야 한다.'),
jsonb_build_object('number', 47,
  'question', E'다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ I recently started volunteering at a local animal shelter, which rescues abandoned pets.\nⓑ Last Saturday, I met a puppy, that had been left on the street in the rain.\nⓒ One of the staff members, who name is Jiyeon, took special care of it.\nⓓ She said the puppy would be ready for adoption in two weeks, what gave me hope.\nⓔ I am seriously considering adopting it, which would be my first ever pet.',
  'answer', E'ⓑ, ⓒ, ⓓ\nⓑ → Last Saturday, I met a puppy, which had been left on the street in the rain.\nⓒ → One of the staff members, whose name is Jiyeon, took special care of it.\nⓓ → She said the puppy would be ready for adoption in two weeks, which gave me hope.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓑ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓒ 이름의 소유를 나타내므로 who를 소유격 whose로 고쳐야 한다. ⓓ 계속적 용법에서는 what을 쓸 수 없으므로 which로 고쳐야 한다.'),
jsonb_build_object('number', 48,
  'question', E'다음 글에서 어법상 어색한 문장을 모두 찾아 기호를 쓰고, 바르게 고쳐 쓰시오.\n\nⓐ My grandmother, who turned 80 this year, is one of the most remarkable people I know.\nⓑ She grew up during a very difficult time in Korean history, that shaped her strong character.\nⓒ She raised five children on her own, which was an incredible achievement.\nⓓ All of her children became successful professionals, and which makes her extremely proud.\nⓔ She often tells me her life story, whom I find deeply inspiring and moving.',
  'answer', E'ⓑ, ⓓ, ⓔ\nⓑ → She grew up during a very difficult time in Korean history, which shaped her strong character.\nⓓ → All of her children became successful professionals, which makes her extremely proud.\nⓔ → She often tells me her life story, which I find deeply inspiring and moving.',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'ⓑ 계속적 용법에서는 that을 쓸 수 없으므로 which로 고쳐야 한다. ⓓ 접속사 and와 관계대명사 which를 동시에 쓸 수 없으므로 and를 삭제한다. ⓔ 선행사 her life story는 사물이므로 whom(사람 목적격) 대신 which를 써야 한다.'),
jsonb_build_object('number', 49,
  'question', E'[Part 7] 다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n나는 새 이어폰을 샀는데, 그것은 사흘 만에 고장났다.\n[조건] buy, break down을 활용할 것 / 계속적 용법의 관계대명사를 사용할 것',
  'answer', E'I bought new earphones, which broke down after three days.',
  'acceptedAnswers', jsonb_build_array(E'I bought new earphones, which broke down in three days.', E'I bought new earphones, which broke down after 3 days.'),
  'explanation', E'\"새 이어폰을 샀다\"는 I bought new earphones, \"그것은 사흘 만에 고장났다\"는 계속적 용법 which broke down after three days로 연결한다.'),
jsonb_build_object('number', 50,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그녀는 장학금을 받았는데, 그것이 그녀의 대학 생활을 바꿔놓았다.\n[조건] receive, change를 활용할 것 / 9단어로 쓸 것',
  'answer', E'She received a scholarship, which changed her university life.',
  'acceptedAnswers', jsonb_build_array(E'She received a scholarship, which changed her college life.'),
  'explanation', E'\"장학금을 받았다\"는 She received a scholarship, \"그것이 대학 생활을 바꿨다\"는 계속적 용법 which changed her university life로 연결한다. 총 9단어.'),
jsonb_build_object('number', 51,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n우리 오빠는 서울에 있는 IT 회사에서 일하는데, 매우 바쁜 사람이다.\n[조건] work, IT company, busy를 활용할 것 / who를 사용할 것',
  'answer', E'My older brother, who works at an IT company in Seoul, is a very busy person.',
  'acceptedAnswers', jsonb_build_array(E'My brother, who works at an IT company in Seoul, is a very busy person.'),
  'explanation', E'선행사 My older brother(사람)를 계속적 용법의 who로 받아 부가 정보를 삽입하고, 주절에서 is a very busy person으로 마무리한다.'),
jsonb_build_object('number', 52,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그는 아무 설명도 하지 않고 자리를 떠났는데, 그것이 모두를 혼란스럽게 했다.\n[조건] leave, explanation, confuse를 활용할 것 / which를 사용할 것',
  'answer', E'He left without any explanation, which confused everyone.',
  'acceptedAnswers', jsonb_build_array(E'He left without explanation, which confused everyone.'),
  'explanation', E'\"아무 설명 없이 떠났다\"는 He left without any explanation, \"그것이 모두를 혼란스럽게 했다\"는 계속적 용법 which confused everyone으로 연결한다.'),
jsonb_build_object('number', 53,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n그들은 새로운 환경 정책을 발표했는데, 그것은 많은 시민들의 지지를 받았다.\n[조건] announce, environmental policy, support를 활용할 것 / 계속적 용법의 관계대명사를 사용할 것',
  'answer', E'They announced a new environmental policy, which received support from many citizens.',
  'acceptedAnswers', jsonb_build_array(E'They announced a new environmental policy, which was supported by many citizens.'),
  'explanation', E'\"새로운 환경 정책을 발표했다\"는 They announced a new environmental policy, \"많은 시민들의 지지를 받았다\"는 계속적 용법 which received support from many citizens로 연결한다.'),
jsonb_build_object('number', 54,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n우리 학교에는 음악 선생님이 한 분 계신데, 그분은 세계적인 피아니스트 출신이다.\n[조건] music teacher, world-famous pianist를 활용할 것 / who를 사용할 것 / 12단어 이내로 쓸 것',
  'answer', E'Our school has a music teacher, who is a world-famous pianist.',
  'acceptedAnswers', jsonb_build_array(E'We have a music teacher, who is a world-famous pianist.'),
  'explanation', E'\"학교에 음악 선생님이 계시다\"는 Our school has a music teacher, \"그분은 세계적인 피아니스트 출신\"은 계속적 용법 who is a world-famous pianist로 연결한다.'),
jsonb_build_object('number', 55,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n나는 자전거를 타고 가다가 낯선 사람에게 길을 알려줬는데, 그것이 내 하루를 행복하게 만들었다.\n[조건] give directions, stranger, make를 활용할 것 / which를 사용할 것',
  'answer', E'I gave directions to a stranger while riding my bike, which made my day happy.',
  'acceptedAnswers', jsonb_build_array(E'I was riding my bike and gave directions to a stranger, which made my whole day.', E'I gave directions to a stranger while riding my bicycle, which made my day happy.'),
  'explanation', E'\"자전거를 타다가 길을 알려줬다\"는 I gave directions to a stranger while riding my bike, \"그것이 하루를 행복하게 만들었다\"는 계속적 용법 which made my day happy로 연결한다.'),
jsonb_build_object('number', 56,
  'question', E'다음 우리말을 주어진 조건에 맞게 영작하시오.\n\n이것은 우리 할아버지께서 직접 지으신 집인데, 60년이 지난 지금도 튼튼하게 서 있다.\n[조건] grandfather, build, still standing을 활용할 것 / which를 사용할 것 / 15단어 이내로 쓸 것',
  'answer', E'This is the house my grandfather built, which is still standing after 60 years.',
  'acceptedAnswers', jsonb_build_array(E'This is the house my grandfather built, which is still standing after sixty years.'),
  'explanation', E'\"할아버지가 지은 집\"은 the house my grandfather built, \"60년이 지난 지금도 서 있다\"는 계속적 용법 which is still standing after 60 years로 연결한다.'),
jsonb_build_object('number', 57,
  'question', E'[Part 8] 다음 문장이 어법상 옳으면 O, 어색하면 X를 쓰고, X인 경우 이유와 바른 문장을 쓰시오.\n\nShe introduced me to her roommate, that is studying art in Paris.',
  'answer', E'X / 계속적 용법에서는 that을 관계대명사로 쓸 수 없음. / She introduced me to her roommate, who is studying art in Paris.',
  'acceptedAnswers', jsonb_build_array(E'X'),
  'explanation', E'콤마 뒤 계속적 용법에서는 that을 관계대명사로 사용할 수 없다. 선행사 her roommate는 사람이므로 who를 써야 한다.'),
jsonb_build_object('number', 58,
  'question', E'다음 문장이 어법상 옳으면 O, 어색하면 X를 쓰고, X인 경우 이유와 바른 문장을 쓰시오.\n\nMy team finished the presentation early, which gave us extra time to practice.',
  'answer', E'O',
  'acceptedAnswers', jsonb_build_array(),
  'explanation', E'계속적 용법의 관계대명사 which가 앞 문장 전체(발표를 일찍 끝낸 것)를 선행사로 받아 올바르게 사용되었다.'),
jsonb_build_object('number', 59,
  'question', E'다음 문장이 어법상 옳으면 O, 어색하면 X를 쓰고, X인 경우 이유와 바른 문장을 쓰시오.\n\nHe has two cats, who are both named after soccer players.',
  'answer', E'X / 고양이는 사람이 아닌 동물(사물)이므로 who 대신 which를 써야 함. / He has two cats, which are both named after soccer players.',
  'acceptedAnswers', jsonb_build_array(E'X'),
  'explanation', E'선행사 two cats는 동물(사물)이므로 사람에게 쓰는 who 대신 which를 사용해야 한다.'),
jsonb_build_object('number', 60,
  'question', E'다음 문장이 어법상 옳으면 O, 어색하면 X를 쓰고, X인 경우 이유와 바른 문장을 쓰시오.\n\nI read his autobiography twice, which it changed my perspective on life completely.',
  'answer', E'X / 계속적 용법의 관계대명사 which 뒤에 대명사 it을 중복해서 쓸 수 없음. / I read his autobiography twice, which changed my perspective on life completely.',
  'acceptedAnswers', jsonb_build_array(E'X'),
  'explanation', E'관계대명사 which가 주어 역할을 하므로 대명사 it을 함께 쓰면 주어가 중복된다. it을 삭제해야 한다.'),
jsonb_build_object('number', 61,
  'question', E'[Part 9] 계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n우리 어머니는 지역 병원에서 간호사로 일하시는데, 항상 환자들에게 친절하게 대하신다.',
  'answer', E'My mother, who works as a nurse at a local hospital, is always kind to her patients.',
  'acceptedAnswers', jsonb_build_array(E'My mom, who works as a nurse at a local hospital, is always kind to her patients.', E'My mother, who works as a nurse at a local hospital, always treats her patients kindly.'),
  'explanation', E'선행사 My mother(사람)를 계속적 용법의 who로 받아 직업 정보를 삽입하고, 주절에서 is always kind to her patients로 마무리한다.'),
jsonb_build_object('number', 62,
  'question', E'계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n그 학생들은 홍수 피해 지역에서 봉사 활동을 했는데, 그것이 많은 사람들에게 큰 감동을 주었다.\n[힌트] volunteer, move',
  'answer', E'The students did volunteer work in the flood-damaged area, which moved many people deeply.',
  'acceptedAnswers', jsonb_build_array(E'The students volunteered in the flood-damaged area, which deeply moved many people.'),
  'explanation', E'\"봉사 활동을 했다\"는 The students did volunteer work in the flood-damaged area, \"큰 감동을 주었다\"는 계속적 용법 which moved many people deeply로 연결한다.'),
jsonb_build_object('number', 63,
  'question', E'계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n그들은 콘서트가 취소되었다고 발표했는데, 그것은 수천 명의 팬들을 실망시켰다.\n[힌트] announce, disappoint',
  'answer', E'They announced that the concert was canceled, which disappointed thousands of fans.',
  'acceptedAnswers', jsonb_build_array(E'They announced that the concert had been canceled, which disappointed thousands of fans.', E'They announced the cancellation of the concert, which disappointed thousands of fans.'),
  'explanation', E'\"콘서트 취소를 발표했다\"는 They announced that the concert was canceled, \"수천 명의 팬들을 실망시켰다\"는 계속적 용법 which disappointed thousands of fans로 연결한다.'),
jsonb_build_object('number', 64,
  'question', E'계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n이것은 세종대왕인데, 그분은 한글을 창제하여 한국의 문맹률을 크게 낮추셨다.',
  'answer', E'This is King Sejong, who created Hangeul and greatly reduced the illiteracy rate in Korea.',
  'acceptedAnswers', jsonb_build_array(E'This is King Sejong, who invented Hangeul and greatly reduced illiteracy in Korea.'),
  'explanation', E'선행사 King Sejong(사람)을 계속적 용법의 who로 받아 한글 창제와 문맹률 감소라는 부가 정보를 전달한다.'),
jsonb_build_object('number', 65,
  'question', E'계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n그녀는 전액 장학금을 받았는데, 그것은 4년간의 학비를 모두 해결해주었다.\n[힌트] scholarship, cover',
  'answer', E'She received a full scholarship, which covered all her tuition fees for four years.',
  'acceptedAnswers', jsonb_build_array(E'She received a full scholarship, which covered all of her tuition for four years.'),
  'explanation', E'\"전액 장학금을 받았다\"는 She received a full scholarship, \"4년간 학비를 해결했다\"는 계속적 용법 which covered all her tuition fees for four years로 연결한다.'),
jsonb_build_object('number', 66,
  'question', E'계속적 용법의 관계대명사를 반드시 사용하여 다음 우리말을 영어로 완전히 영작하시오.\n\n나는 외할머니댁 근처에 있는 서점을 자주 방문했는데, 그곳은 항상 따뜻하고 조용해서 좋았다.',
  'answer', E'I often visited a bookstore near my grandmother''s house, which was always warm and quiet.',
  'acceptedAnswers', jsonb_build_array(E'I often visited the bookstore near my grandmother''s house, which was always warm and quiet.', E'I frequently visited a bookstore near my grandmother''s house, which was always warm and quiet.'),
  'explanation', E'\"외할머니댁 근처 서점을 자주 방문했다\"는 I often visited a bookstore near my grandmother''s house, \"항상 따뜻하고 조용했다\"는 계속적 용법 which was always warm and quiet로 연결한다.')
  );

  a := jsonb_build_array(E'which', E'which was built during the Silla Dynasty', E'Soyeon is planning to read Demian, which is her favorite novel of all time.', E'which', E'which was found near the school entrance', E'She forgot to set her alarm', E'a — 나는 (여러 형제 중) 병원에서 일하는 형제가 있다. (형제가 더 있을 수 있음) / b — 나는 형제가 한 명 있는데, 그는 병원에서 일한다. (형제가 한 명뿐) / 차이점: 콤마(,)의 유무에 따라 a는 한정적 용법(범위를 제한), b는 계속적 용법(부가 정보 제공)으로 쓰임.', E'a — 그녀에게는 (여러 친구들 중에서) 어떤 상황에서도 그녀를 지지해주는 친구들이 있다. / b — 그녀에게는 친구들이 있는데, 그들은 어떤 상황에서도 그녀를 지지해준다.', E'I finally met the author of my favorite book, who signed my copy and chatted with me for ten minutes.', E'We took the scenic coastal road to Busan, which added an extra hour to our journey but was absolutely worth it.', E'She said nothing during the entire meeting, which made everyone feel uncomfortable.', E'My grandfather, who is now 75 years old and lives in the countryside, made this wooden chair himself.', E'They announced that school would be canceled due to the snowstorm, which delighted every single student.', E'I bumped into my elementary school teacher at the supermarket, who still remembered my name after all these years.', E'I have one older sister, who is a pediatric nurse and has worked at Seoul Children''s Hospital for seven years.', E'The new community center, which can hold up to 500 people and was built with donations from local residents, will open in March.', E'He practiced his speech over a hundred times, which eventually paid off on the big day.', E'My best friend, who calls me every single day without fail, moved to a different city for university.', E'which', E'and they', E'who', E'and it', E'which', E'which I have watched six times', E'but she doesn''t practice nearly as much as she should', E'but it turned out to be completely false', E'b / 이유: 고양이가 한 마리뿐이므로 계속적 용법(콤마+which)을 씀. / 차이: a는 여러 고양이 중 물건을 떨어뜨리는 특정 고양이를 가리킴. b는 고양이가 한 마리뿐이며 그에 대한 부가 설명을 제공함.', E'a / 이유: 사촌이 여럿이므로 의사인 사촌을 한정하는 한정적 용법이 적절.', E'a — 과제를 늦게 내는 학생들(만)은 점수를 잃을 것이다. / b — 학생들은 과제를 늦게 내는데, 그들은 점수를 잃을 것이다. (모든 학생들이 과제를 늦게 낸다는 뜻이 되어 어색한 문장)', E'a — 나는 (여러 친구 중) 항상 솔직하게 말해주는 친구가 있다. / b — 나는 친구가 한 명 있는데, 그는 항상 나에게 솔직하게 말해준다. / b', E'b / 이유: Our team은 특정한 하나의 팀이므로 추가 설명을 제공하는 계속적 용법이 자연스럽고, 한정할 필요가 없음.', E'b / 이유: 남동생이 한 명뿐임을 나타내므로 계속적 용법(콤마+who)이 적절.', E'that', E'what', E'which it', E'has', E'who', E'whom', E'which', E'and which', E'is', E'that', E'ⓑ, ⓒ, ⓔ\nⓑ → She had just returned from a year in Canada, which had changed her a lot.\nⓒ → We talked for hours, which made both of us feel like no time had passed.\nⓔ → She also brought me a small gift, which I found very thoughtful.', E'ⓐ, ⓑ, ⓓ\nⓐ → My uncle, who has worked as a marine biologist for over twenty years, is truly inspiring.\nⓑ → He studies deep-sea creatures, which are rarely seen by humans.\nⓓ → The news was covered by major media outlets, which brought him worldwide attention.', E'ⓐ, ⓑ, ⓓ\nⓐ → This is my homeroom teacher, Ms. Park, who has taught English for fifteen years.\nⓑ → She is known for her creative lessons, which always keep students engaged.\nⓓ → She also recommended several novels to me, which I found extremely helpful for my writing.', E'ⓐ, ⓑ, ⓒ, ⓔ\nⓐ → A few years ago, a typhoon hit our town, which caused serious damage to many buildings.\nⓑ → My family, who had lived in the area for decades, had to evacuate immediately.\nⓒ → We stayed at a community shelter, which provided food and basic supplies.\nⓔ → One volunteer, who became a close friend of mine, still keeps in touch with our family.', E'ⓑ, ⓒ, ⓓ\nⓑ → Last Saturday, I met a puppy, which had been left on the street in the rain.\nⓒ → One of the staff members, whose name is Jiyeon, took special care of it.\nⓓ → She said the puppy would be ready for adoption in two weeks, which gave me hope.', E'ⓑ, ⓓ, ⓔ\nⓑ → She grew up during a very difficult time in Korean history, which shaped her strong character.\nⓓ → All of her children became successful professionals, which makes her extremely proud.\nⓔ → She often tells me her life story, which I find deeply inspiring and moving.', E'I bought new earphones, which broke down after three days.', E'She received a scholarship, which changed her university life.', E'My older brother, who works at an IT company in Seoul, is a very busy person.', E'He left without any explanation, which confused everyone.', E'They announced a new environmental policy, which received support from many citizens.', E'Our school has a music teacher, who is a world-famous pianist.', E'I gave directions to a stranger while riding my bike, which made my day happy.', E'This is the house my grandfather built, which is still standing after 60 years.', E'X / 계속적 용법에서는 that을 관계대명사로 쓸 수 없음. / She introduced me to her roommate, who is studying art in Paris.', E'O', E'X / 고양이는 사람이 아닌 동물(사물)이므로 who 대신 which를 써야 함. / He has two cats, which are both named after soccer players.', E'X / 계속적 용법의 관계대명사 which 뒤에 대명사 it을 중복해서 쓸 수 없음. / I read his autobiography twice, which changed my perspective on life completely.', E'My mother, who works as a nurse at a local hospital, is always kind to her patients.', E'The students did volunteer work in the flood-damaged area, which moved many people deeply.', E'They announced that the concert was canceled, which disappointed thousands of fans.', E'This is King Sejong, who created Hangeul and greatly reduced the illiteracy rate in Korea.', E'She received a full scholarship, which covered all her tuition fees for four years.', E'I often visited a bookstore near my grandmother''s house, which was always warm and quiet.');

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES (
    '관계대명사의 계속적 용법 Step 3 (서술형 66문항)',
    '관계대명사의 계속적 용법',
    q,
    a,
    'problem',
    'interactive'
  );
END $$;
