-- 현재완료 Step 1 — 110문항 (서술형 + 객관식)
-- template_topic: 현재완료
-- category: problem, mode: interactive

DO $$
DECLARE
  q jsonb;
  a jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '현재완료 Step 1';

  q := jsonb_build_array(
jsonb_build_object('number',1,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nMy dog ___ the ball. (just, catch)',
  'answer',E'has just caught',
  'acceptedAnswers',jsonb_build_array(E'Has just caught'),
  'explanation',E'catch-caught-caught, 3인칭 단수 has'),
jsonb_build_object('number',2,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nWe ___ this song before. (never, hear)',
  'answer',E'have never heard',
  'acceptedAnswers',jsonb_build_array(E'Have never heard'),
  'explanation',E'hear-heard-heard'),
jsonb_build_object('number',3,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\n___ she ___ her keys? (lose)',
  'answer',E'Has / lost',
  'acceptedAnswers',jsonb_build_array(E'Has/lost',E'has / lost',E'has/lost',E'Has lost',E'has lost'),
  'explanation',E'의문문 Has + S + p.p., lose-lost-lost'),
jsonb_build_object('number',4,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nThey ___ their project yet. (not, finish)',
  'answer',E'haven''t finished',
  'acceptedAnswers',jsonb_build_array(E'have not finished',E'Haven''t finished',E'Have not finished'),
  'explanation',E'haven''t + p.p.'),
jsonb_build_object('number',5,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nI ___ this movie twice. (already, see)',
  'answer',E'have already seen',
  'acceptedAnswers',jsonb_build_array(E'Have already seen'),
  'explanation',E'see-saw-seen'),
jsonb_build_object('number',6,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nBen ___ for three hours. (study)',
  'answer',E'has studied',
  'acceptedAnswers',jsonb_build_array(E'Has studied'),
  'explanation',E'3인칭 단수 has + p.p.'),
jsonb_build_object('number',7,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nThe bus ___. (just, leave)',
  'answer',E'has just left',
  'acceptedAnswers',jsonb_build_array(E'Has just left'),
  'explanation',E'leave-left-left'),
jsonb_build_object('number',8,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\n___ you ___ your room yet? (clean)',
  'answer',E'Have / cleaned',
  'acceptedAnswers',jsonb_build_array(E'Have/cleaned',E'have / cleaned',E'have/cleaned',E'Have cleaned',E'have cleaned'),
  'explanation',E'의문문 Have + S + p.p.'),
jsonb_build_object('number',9,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nLisa ___ a lot lately. (grow)',
  'answer',E'has grown',
  'acceptedAnswers',jsonb_build_array(E'Has grown'),
  'explanation',E'grow-grew-grown'),
jsonb_build_object('number',10,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nWe ___ dinner yet. (not, have)',
  'answer',E'haven''t had',
  'acceptedAnswers',jsonb_build_array(E'have not had',E'Haven''t had',E'Have not had'),
  'explanation',E'have-had-had'),
jsonb_build_object('number',11,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nTom ___ in Paris before. (never, be)',
  'answer',E'has never been',
  'acceptedAnswers',jsonb_build_array(E'Has never been'),
  'explanation',E'be-was/were-been'),
jsonb_build_object('number',12,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nShe ___ her essay already. (send)',
  'answer',E'has sent',
  'acceptedAnswers',jsonb_build_array(E'Has sent',E'has already sent',E'Has already sent'),
  'explanation',E'send-sent-sent'),
jsonb_build_object('number',13,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nHow many books ___ he ___ this year? (read)',
  'answer',E'has / read',
  'acceptedAnswers',jsonb_build_array(E'has/read',E'Has / read',E'Has/read',E'has read',E'Has read'),
  'explanation',E'read-read-read (과거분사 동형)'),
jsonb_build_object('number',14,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nMy parents ___ the dishes. (not, wash)',
  'answer',E'haven''t washed',
  'acceptedAnswers',jsonb_build_array(E'have not washed',E'Haven''t washed',E'Have not washed'),
  'explanation',E'wash-washed-washed'),
jsonb_build_object('number',15,
  'question',E'[Part 1] 괄호 안의 단어를 활용하여 현재완료 시제로 문장을 완성하시오.\n\nThe team ___ every game so far. (win)',
  'answer',E'has won',
  'acceptedAnswers',jsonb_build_array(E'Has won'),
  'explanation',E'win-won-won'),
jsonb_build_object('number',16,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nI (lost / have lost) my umbrella. I can''t find it anywhere.',
  'answer',E'have lost',
  'acceptedAnswers',jsonb_build_array(E'Have lost'),
  'explanation',E'현재 결과(못 찾음) → 현재완료'),
jsonb_build_object('number',17,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nShe (visited / has visited) her grandma last Sunday.',
  'answer',E'visited',
  'acceptedAnswers',jsonb_build_array(E'Visited'),
  'explanation',E'last Sunday → 과거시제'),
jsonb_build_object('number',18,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\n(Did you finish / Have you finished) your homework yet?',
  'answer',E'Have you finished',
  'acceptedAnswers',jsonb_build_array(E'have you finished'),
  'explanation',E'yet → 현재완료'),
jsonb_build_object('number',19,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nWe (moved / have moved) to this town in 2019.',
  'answer',E'moved',
  'acceptedAnswers',jsonb_build_array(E'Moved'),
  'explanation',E'in 2019 → 과거시제'),
jsonb_build_object('number',20,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nHe (has never eaten / never ate) sushi before.',
  'answer',E'has never eaten',
  'acceptedAnswers',jsonb_build_array(E'Has never eaten'),
  'explanation',E'never...before → 현재완료(경험)'),
jsonb_build_object('number',21,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nWhen (did you buy / have you bought) that jacket?',
  'answer',E'did you buy',
  'acceptedAnswers',jsonb_build_array(E'Did you buy'),
  'explanation',E'When(특정 시점) → 과거시제'),
jsonb_build_object('number',22,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nThey (have just arrived / just arrived) at the station.',
  'answer',E'have just arrived',
  'acceptedAnswers',jsonb_build_array(E'Have just arrived'),
  'explanation',E'just → 현재완료(완료)'),
jsonb_build_object('number',23,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nIt (didn''t rain / hasn''t rained) since last week.',
  'answer',E'hasn''t rained',
  'acceptedAnswers',jsonb_build_array(E'has not rained',E'Hasn''t rained',E'Has not rained'),
  'explanation',E'since → 현재완료(계속)'),
jsonb_build_object('number',24,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nI (saw / have seen) that actor at the mall yesterday.',
  'answer',E'saw',
  'acceptedAnswers',jsonb_build_array(E'Saw'),
  'explanation',E'yesterday → 과거시제'),
jsonb_build_object('number',25,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\n(Have you ever been / Were you ever) to Jeju Island?',
  'answer',E'Have you ever been',
  'acceptedAnswers',jsonb_build_array(E'have you ever been'),
  'explanation',E'ever → 현재완료(경험)'),
jsonb_build_object('number',26,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nMy brother (broke / has broken) his arm last winter.',
  'answer',E'broke',
  'acceptedAnswers',jsonb_build_array(E'Broke'),
  'explanation',E'last winter → 과거시제'),
jsonb_build_object('number',27,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nShe (has taught / taught) piano for ten years and still teaches now.',
  'answer',E'has taught',
  'acceptedAnswers',jsonb_build_array(E'Has taught'),
  'explanation',E'for ten years + still → 현재완료(계속)'),
jsonb_build_object('number',28,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nSam (has lost / lost) his wallet, so he can''t pay now.',
  'answer',E'has lost',
  'acceptedAnswers',jsonb_build_array(E'Has lost'),
  'explanation',E'현재 결과(지금 못 냄) → 현재완료'),
jsonb_build_object('number',29,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nI (received / have received) a gift from my uncle two days ago.',
  'answer',E'received',
  'acceptedAnswers',jsonb_build_array(E'Received'),
  'explanation',E'two days ago → 과거시제'),
jsonb_build_object('number',30,
  'question',E'[Part 2] 괄호 안에서 알맞은 시제를 고르시오.\n\nThis is the best meal I (had / have ever had).',
  'answer',E'have ever had',
  'acceptedAnswers',jsonb_build_array(E'Have ever had'),
  'explanation',E'최상급 + 현재완료(경험)'),
jsonb_build_object('number',31,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nMy sister ___ two novels so far. (write)',
  'answer',E'has written',
  'acceptedAnswers',jsonb_build_array(E'Has written'),
  'explanation',E'so far → 현재완료'),
jsonb_build_object('number',32,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nWe ___ a new house last month. (buy)',
  'answer',E'bought',
  'acceptedAnswers',jsonb_build_array(E'Bought'),
  'explanation',E'last month → 과거시제'),
jsonb_build_object('number',33,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nI ___ my phone. I can''t find it! (lose)',
  'answer',E'have lost',
  'acceptedAnswers',jsonb_build_array(E'Have lost'),
  'explanation',E'현재 결과 → 현재완료'),
jsonb_build_object('number',34,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nJake ___ to the library yesterday. (go)',
  'answer',E'went',
  'acceptedAnswers',jsonb_build_array(E'Went'),
  'explanation',E'yesterday → 과거시제'),
jsonb_build_object('number',35,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nShe ___ here for five years. (live)',
  'answer',E'has lived',
  'acceptedAnswers',jsonb_build_array(E'Has lived'),
  'explanation',E'for five years → 현재완료(계속)'),
jsonb_build_object('number',36,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nThe game ___ already. They''re playing now. (already, start)',
  'answer',E'has already started',
  'acceptedAnswers',jsonb_build_array(E'Has already started'),
  'explanation',E'already → 현재완료(완료)'),
jsonb_build_object('number',37,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nI ___ Korean food for the first time last year. (try)',
  'answer',E'tried',
  'acceptedAnswers',jsonb_build_array(E'Tried'),
  'explanation',E'last year → 과거시제'),
jsonb_build_object('number',38,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nHe ___ his finger. It''s bleeding. (cut)',
  'answer',E'has cut',
  'acceptedAnswers',jsonb_build_array(E'Has cut'),
  'explanation',E'현재 결과(피가 남) → 현재완료, cut-cut-cut'),
jsonb_build_object('number',39,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nHow many times ___ you ___ to London? (be)',
  'answer',E'have / been',
  'acceptedAnswers',jsonb_build_array(E'have/been',E'Have / been',E'Have/been',E'have been',E'Have been'),
  'explanation',E'How many times → 현재완료(경험)'),
jsonb_build_object('number',40,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nMy uncle ___ to Canada last summer. (move)',
  'answer',E'moved',
  'acceptedAnswers',jsonb_build_array(E'Moved'),
  'explanation',E'last summer → 과거시제'),
jsonb_build_object('number',41,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nSomeone ___ my bike! I can''t find it anywhere. (steal)',
  'answer',E'has stolen',
  'acceptedAnswers',jsonb_build_array(E'Has stolen'),
  'explanation',E'현재 결과 → 현재완료, steal-stole-stolen'),
jsonb_build_object('number',42,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nShe ___ from high school in 2021. (graduate)',
  'answer',E'graduated',
  'acceptedAnswers',jsonb_build_array(E'Graduated'),
  'explanation',E'in 2021 → 과거시제'),
jsonb_build_object('number',43,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nI''m hungry. I ___ anything since morning. (not, eat)',
  'answer',E'haven''t eaten',
  'acceptedAnswers',jsonb_build_array(E'have not eaten',E'Haven''t eaten',E'Have not eaten'),
  'explanation',E'since morning → 현재완료'),
jsonb_build_object('number',44,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nThe choir ___ that song fifty times. (sing)',
  'answer',E'has sung',
  'acceptedAnswers',jsonb_build_array(E'Has sung'),
  'explanation',E'fifty times → 현재완료(경험), sing-sang-sung'),
jsonb_build_object('number',45,
  'question',E'[Part 3] 괄호 안의 동사를 현재완료 또는 과거시제 중 알맞은 형태로 쓰시오.\n\nWe ___ into our new apartment last week. (move)',
  'answer',E'moved',
  'acceptedAnswers',jsonb_build_array(E'Moved'),
  'explanation',E'last week → 과거시제'),
jsonb_build_object('number',46,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nShe ___ ill ___ Monday. (be)',
  'answer',E'has been / since',
  'acceptedAnswers',jsonb_build_array(E'has been/since',E'Has been / since',E'Has been/since'),
  'explanation',E'Monday(특정 시점) → since'),
jsonb_build_object('number',47,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nThey ___ in the same school ___ three years. (study)',
  'answer',E'have studied / for',
  'acceptedAnswers',jsonb_build_array(E'have studied/for',E'Have studied / for',E'Have studied/for'),
  'explanation',E'three years(기간) → for'),
jsonb_build_object('number',48,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nHe ___ for the bus ___ twenty minutes. (wait)',
  'answer',E'has waited / for',
  'acceptedAnswers',jsonb_build_array(E'has waited/for',E'Has waited / for',E'Has waited/for'),
  'explanation',E'twenty minutes(기간) → for'),
jsonb_build_object('number',49,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nI ___ awake ___ 5 a.m. (be)',
  'answer',E'have been / since',
  'acceptedAnswers',jsonb_build_array(E'have been/since',E'Have been / since',E'Have been/since'),
  'explanation',E'5 a.m.(특정 시점) → since'),
jsonb_build_object('number',50,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nJudy ___ in the same office ___ 2015. (work)',
  'answer',E'has worked / since',
  'acceptedAnswers',jsonb_build_array(E'has worked/since',E'Has worked / since',E'Has worked/since'),
  'explanation',E'2015(특정 시점) → since'),
jsonb_build_object('number',51,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nMy parents ___ here ___ a week. (be)',
  'answer',E'have been / for',
  'acceptedAnswers',jsonb_build_array(E'have been/for',E'Have been / for',E'Have been/for'),
  'explanation',E'a week(기간) → for'),
jsonb_build_object('number',52,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nShe ___ her friends ___ her birthday. (not, see)',
  'answer',E'hasn''t seen / since',
  'acceptedAnswers',jsonb_build_array(E'hasn''t seen/since',E'has not seen / since',E'Hasn''t seen / since',E'Has not seen / since'),
  'explanation',E'her birthday(특정 시점) → since'),
jsonb_build_object('number',53,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nIt ___ cold and rainy ___ two weeks. (be)',
  'answer',E'has been / for',
  'acceptedAnswers',jsonb_build_array(E'has been/for',E'Has been / for',E'Has been/for'),
  'explanation',E'two weeks(기간) → for'),
jsonb_build_object('number',54,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nTom ___ any water ___ this morning. (not, drink)',
  'answer',E'hasn''t drunk / since',
  'acceptedAnswers',jsonb_build_array(E'hasn''t drunk/since',E'has not drunk / since',E'Hasn''t drunk / since',E'Has not drunk / since'),
  'explanation',E'drink-drank-drunk, this morning(특정 시점) → since'),
jsonb_build_object('number',55,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nI ___ to call you ___ an hour. (try)',
  'answer',E'have tried / for',
  'acceptedAnswers',jsonb_build_array(E'have tried/for',E'Have tried / for',E'Have tried/for'),
  'explanation',E'an hour(기간) → for'),
jsonb_build_object('number',56,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nKorea ___ an independent nation ___ 1945. (be)',
  'answer',E'has been / since',
  'acceptedAnswers',jsonb_build_array(E'has been/since',E'Has been / since',E'Has been/since'),
  'explanation',E'1945(특정 시점) → since'),
jsonb_build_object('number',57,
  'question',E'[Part 4] 괄호 안의 동사를 현재완료형으로 쓰고, for 또는 since를 빈칸에 쓰시오.\n\nThere ___ no rain ___ several months. (be)',
  'answer',E'has been / for',
  'acceptedAnswers',jsonb_build_array(E'has been/for',E'Has been / for',E'Has been/for'),
  'explanation',E'several months(기간) → for')
  );
  q := q || jsonb_build_array(
jsonb_build_object('number',58,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nI''ve (already / yet) packed my bag. I''m ready to go.',
  'answer',E'already',
  'acceptedAnswers',jsonb_build_array(E'Already'),
  'explanation',E'긍정문에서 이미 완료 → already'),
jsonb_build_object('number',59,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nHave you called your mom (yet / already)?',
  'answer',E'yet',
  'acceptedAnswers',jsonb_build_array(E'Yet'),
  'explanation',E'의문문 끝 → yet'),
jsonb_build_object('number',60,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nHe''s (never / ever) been late for class before.',
  'answer',E'never',
  'acceptedAnswers',jsonb_build_array(E'Never'),
  'explanation',E'부정적 의미(한 번도 ~않음) → never'),
jsonb_build_object('number',61,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nHave you (ever / never) tried riding a horse?',
  'answer',E'ever',
  'acceptedAnswers',jsonb_build_array(E'Ever'),
  'explanation',E'의문문에서 경험 → ever'),
jsonb_build_object('number',62,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nShe hasn''t replied to my message (still / yet).',
  'answer',E'yet',
  'acceptedAnswers',jsonb_build_array(E'Yet'),
  'explanation',E'부정문 끝 → yet'),
jsonb_build_object('number',63,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nThey''ve (just / already) left. They walked out a minute ago.',
  'answer',E'just',
  'acceptedAnswers',jsonb_build_array(E'Just'),
  'explanation',E'a minute ago → 방금 → just'),
jsonb_build_object('number',64,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nIt''s amazing — I''ve (ever / never) seen such a big rainbow!',
  'answer',E'never',
  'acceptedAnswers',jsonb_build_array(E'Never'),
  'explanation',E'한 번도 ~않음(놀라움) → never'),
jsonb_build_object('number',65,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nThey (still / yet) haven''t announced the winner.',
  'answer',E'still',
  'acceptedAnswers',jsonb_build_array(E'Still'),
  'explanation',E'still + haven''t → 아직도 ~않음'),
jsonb_build_object('number',66,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nI''ve (already / yet) seen this film. Let''s watch something else.',
  'answer',E'already',
  'acceptedAnswers',jsonb_build_array(E'Already'),
  'explanation',E'긍정문에서 이미 → already'),
jsonb_build_object('number',67,
  'question',E'[Part 5] 괄호 안에서 알맞은 것을 고르시오.\n\nHas he (ever / just) won a prize? Who did he beat?',
  'answer',E'ever',
  'acceptedAnswers',jsonb_build_array(E'Ever'),
  'explanation',E'의문문에서 경험 → ever'),
jsonb_build_object('number',68,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nA: Where''s Min? B: She ___ to the library.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'Has gone'),
  'explanation',E'Min이 여기 없음 → has gone(가서 아직 안 돌아옴)'),
jsonb_build_object('number',69,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nI ___ to the market. I bought some fruit for you.',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'Have been'),
  'explanation',E'과일을 사왔음 → have been(갔다 옴)'),
jsonb_build_object('number',70,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nDad ___ to Japan twice. He loves it there.',
  'answer',E'has been',
  'acceptedAnswers',jsonb_build_array(E'Has been'),
  'explanation',E'경험(두 번 가봄) → has been'),
jsonb_build_object('number',71,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nWhere is Chris? He ___ to the gym. He''ll be back later.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'Has gone'),
  'explanation',E'Chris가 여기 없음 → has gone'),
jsonb_build_object('number',72,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nMy parents ___ on holiday. The house is empty.',
  'answer',E'have gone',
  'acceptedAnswers',jsonb_build_array(E'Have gone'),
  'explanation',E'집이 비어 있음 → have gone(가서 안 돌아옴)'),
jsonb_build_object('number',73,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nThey''re having a great time in Busan. They ___ there for a week.',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'Have been'),
  'explanation',E'거기서 일주일째 있음 → have been(머물고 있음)'),
jsonb_build_object('number',74,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nA: Where have you been? B: Sorry, I ___ to the dentist.',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'Have been'),
  'explanation',E'갔다 돌아옴 → have been'),
jsonb_build_object('number',75,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nLucy isn''t here. She ___ to the café with her friends.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'Has gone'),
  'explanation',E'Lucy가 여기 없음 → has gone'),
jsonb_build_object('number',76,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nI ___ to that restaurant before. The food is great!',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'Have been'),
  'explanation',E'경험(가본 적 있음) → have been'),
jsonb_build_object('number',77,
  'question',E'[Part 6] have[has] been 또는 have[has] gone을 이용하여 빈칸을 완성하시오.\n\nMy brother ___ to Australia for a month. He won''t be back until June.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'Has gone'),
  'explanation',E'6월까지 안 돌아옴 → has gone'),
jsonb_build_object('number',78,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nThe train <u>has just left</u>. We missed it.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','3',
  'explanation',E'just left → 막 완료된 동작'),
jsonb_build_object('number',79,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\n<u>Have</u> you <u>ever tried</u> bungee jumping?',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','1',
  'explanation',E'ever tried → 경험 여부'),
jsonb_build_object('number',80,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nShe <u>has lived</u> in Seoul for ten years.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','2',
  'explanation',E'for ten years → 계속 거주 중'),
jsonb_build_object('number',81,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nHe <u>has broken</u> his leg. He''s in hospital now.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','4',
  'explanation',E'다리가 부러진 결과 → 지금 입원 중'),
jsonb_build_object('number',82,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nI <u>have already finished</u> my homework.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','3',
  'explanation',E'already finished → 이미 완료'),
jsonb_build_object('number',83,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nThey <u>have been</u> close friends since middle school.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','2',
  'explanation',E'since middle school → 계속 친구'),
jsonb_build_object('number',84,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nI <u>have never heard</u> of such a strange story.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','1',
  'explanation',E'never heard → 경험 없음'),
jsonb_build_object('number',85,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nMia <u>has lost</u> her passport. She can''t travel.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','4',
  'explanation',E'여권 분실 결과 → 여행 불가'),
jsonb_build_object('number',86,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nHow many times <u>have</u> you <u>seen</u> that movie?',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','1',
  'explanation',E'how many times → 경험 횟수'),
jsonb_build_object('number',87,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nThe factory <u>has been</u> here since the 1990s.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','2',
  'explanation',E'since the 1990s → 계속 존재'),
jsonb_build_object('number',88,
  'question',E'[Part 7] 밑줄 친 부분의 현재완료 용법을 고르시오.\n\nShe <u>has just graduated</u> from university.',
  'options',jsonb_build_array(E'경험',E'계속',E'완료',E'결과'),
  'answer','3',
  'explanation',E'just graduated → 방금 졸업'),
jsonb_build_object('number',89,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nShe <u>have finished</u> her report already.',
  'answer',E'has finished',
  'acceptedAnswers',jsonb_build_array(E'Has finished'),
  'explanation',E'She → 3인칭 단수 has'),
jsonb_build_object('number',90,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nI <u>have seen</u> her at the store yesterday.',
  'answer',E'saw',
  'acceptedAnswers',jsonb_build_array(E'Saw'),
  'explanation',E'yesterday → 과거시제'),
jsonb_build_object('number',91,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nThey <u>have been</u> to the party last night.',
  'answer',E'were',
  'acceptedAnswers',jsonb_build_array(E'Were',E'went'),
  'explanation',E'last night → 과거시제'),
jsonb_build_object('number',92,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nHas Kyle ever <u>rided</u> a horse?',
  'answer',E'ridden',
  'acceptedAnswers',jsonb_build_array(E'Ridden'),
  'explanation',E'ride-rode-ridden'),
jsonb_build_object('number',93,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nWe have <u>knew</u> each other since 2018.',
  'answer',E'have known',
  'acceptedAnswers',jsonb_build_array(E'Have known'),
  'explanation',E'know-knew-known'),
jsonb_build_object('number',94,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nHe has <u>went</u> to Paris. He''ll be back next week.',
  'answer',E'has gone',
  'acceptedAnswers',jsonb_build_array(E'Has gone'),
  'explanation',E'go-went-gone'),
jsonb_build_object('number',95,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nI <u>have lost</u> my keys three days ago.',
  'answer',E'lost',
  'acceptedAnswers',jsonb_build_array(E'Lost'),
  'explanation',E'three days ago → 과거시제'),
jsonb_build_object('number',96,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nThe meeting <u>began has</u> at 9 a.m. this morning.',
  'answer',E'began',
  'acceptedAnswers',jsonb_build_array(E'Began'),
  'explanation',E'this morning(특정 과거) → 과거시제, has 제거'),
jsonb_build_object('number',97,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nMy brother <u>didn''t wrote</u> to me since he moved.',
  'answer',E'hasn''t written',
  'acceptedAnswers',jsonb_build_array(E'has not written',E'Hasn''t written',E'Has not written'),
  'explanation',E'since → 현재완료, write-wrote-written'),
jsonb_build_object('number',98,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nShe <u>has visited</u> her grandparents in 2022.',
  'answer',E'visited',
  'acceptedAnswers',jsonb_build_array(E'Visited'),
  'explanation',E'in 2022 → 과거시제'),
jsonb_build_object('number',99,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nI <u>have gone</u> to Japan twice. It was amazing.',
  'answer',E'have been',
  'acceptedAnswers',jsonb_build_array(E'Have been'),
  'explanation',E'경험(갔다 옴) → have been'),
jsonb_build_object('number',100,
  'question',E'[Part 8] 밑줄 친 부분에서 오류를 찾아 올바르게 고쳐 쓰시오.\n\nThere <u>have been</u> a big storm here last weekend.',
  'answer',E'was',
  'acceptedAnswers',jsonb_build_array(E'Was'),
  'explanation',E'last weekend → 과거시제, There was'),
jsonb_build_object('number',101,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nnever / she / her / broken / arm / has',
  'answer',E'She has never broken her arm.',
  'acceptedAnswers',jsonb_build_array(E'she has never broken her arm.',E'She has never broken her arm'),
  'explanation',E'She has never broken her arm.'),
jsonb_build_object('number',102,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nHave / ever / you / abroad / travelled / ?',
  'answer',E'Have you ever travelled abroad?',
  'acceptedAnswers',jsonb_build_array(E'have you ever travelled abroad?',E'Have you ever travelled abroad',E'Have you ever traveled abroad?',E'have you ever traveled abroad?'),
  'explanation',E'Have you ever travelled abroad?'),
jsonb_build_object('number',103,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nalready / my / met / friend / has / him',
  'answer',E'My friend has already met him.',
  'acceptedAnswers',jsonb_build_array(E'my friend has already met him.',E'My friend has already met him'),
  'explanation',E'My friend has already met him.'),
jsonb_build_object('number',104,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nhaven''t / I / since / seen / a / football match / last year',
  'answer',E'I haven''t seen a football match since last year.',
  'acceptedAnswers',jsonb_build_array(E'I haven''t seen a football match since last year',E'I have not seen a football match since last year.',E'I have not seen a football match since last year'),
  'explanation',E'I haven''t seen a football match since last year.'),
jsonb_build_object('number',105,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\njust / has / Emma / won / a / prize',
  'answer',E'Emma has just won a prize.',
  'acceptedAnswers',jsonb_build_array(E'emma has just won a prize.',E'Emma has just won a prize'),
  'explanation',E'Emma has just won a prize.'),
jsonb_build_object('number',106,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nhave / for / years / I / known / her',
  'answer',E'I have known her for years.',
  'acceptedAnswers',jsonb_build_array(E'i have known her for years.',E'I have known her for years'),
  'explanation',E'I have known her for years.'),
jsonb_build_object('number',107,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nknown / have / since / we / each other / 2012',
  'answer',E'We have known each other since 2012.',
  'acceptedAnswers',jsonb_build_array(E'we have known each other since 2012.',E'We have known each other since 2012'),
  'explanation',E'We have known each other since 2012.'),
jsonb_build_object('number',108,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nhas / long / how / lived / she / here / ?',
  'answer',E'How long has she lived here?',
  'acceptedAnswers',jsonb_build_array(E'how long has she lived here?',E'How long has she lived here'),
  'explanation',E'How long has she lived here?'),
jsonb_build_object('number',109,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\ntickets / yet / you / booked / have / ?',
  'answer',E'Have you booked tickets yet?',
  'acceptedAnswers',jsonb_build_array(E'have you booked tickets yet?',E'Have you booked tickets yet'),
  'explanation',E'Have you booked tickets yet?'),
jsonb_build_object('number',110,
  'question',E'[Part 9] 주어진 단어를 올바른 순서로 배열하여 문장을 완성하시오.\n\nhave / worked / I / with / famous people / for years',
  'answer',E'I have worked with famous people for years.',
  'acceptedAnswers',jsonb_build_array(E'i have worked with famous people for years.',E'I have worked with famous people for years'),
  'explanation',E'I have worked with famous people for years.')
  );

  a := jsonb_build_array(
    jsonb_build_object('number',1,'answer',E'has just caught'),
    jsonb_build_object('number',2,'answer',E'have never heard'),
    jsonb_build_object('number',3,'answer',E'Has / lost'),
    jsonb_build_object('number',4,'answer',E'haven''t finished'),
    jsonb_build_object('number',5,'answer',E'have already seen'),
    jsonb_build_object('number',6,'answer',E'has studied'),
    jsonb_build_object('number',7,'answer',E'has just left'),
    jsonb_build_object('number',8,'answer',E'Have / cleaned'),
    jsonb_build_object('number',9,'answer',E'has grown'),
    jsonb_build_object('number',10,'answer',E'haven''t had'),
    jsonb_build_object('number',11,'answer',E'has never been'),
    jsonb_build_object('number',12,'answer',E'has sent'),
    jsonb_build_object('number',13,'answer',E'has / read'),
    jsonb_build_object('number',14,'answer',E'haven''t washed'),
    jsonb_build_object('number',15,'answer',E'has won'),
    jsonb_build_object('number',16,'answer',E'have lost'),
    jsonb_build_object('number',17,'answer',E'visited'),
    jsonb_build_object('number',18,'answer',E'Have you finished'),
    jsonb_build_object('number',19,'answer',E'moved'),
    jsonb_build_object('number',20,'answer',E'has never eaten'),
    jsonb_build_object('number',21,'answer',E'did you buy'),
    jsonb_build_object('number',22,'answer',E'have just arrived'),
    jsonb_build_object('number',23,'answer',E'hasn''t rained'),
    jsonb_build_object('number',24,'answer',E'saw'),
    jsonb_build_object('number',25,'answer',E'Have you ever been'),
    jsonb_build_object('number',26,'answer',E'broke'),
    jsonb_build_object('number',27,'answer',E'has taught'),
    jsonb_build_object('number',28,'answer',E'has lost'),
    jsonb_build_object('number',29,'answer',E'received'),
    jsonb_build_object('number',30,'answer',E'have ever had'),
    jsonb_build_object('number',31,'answer',E'has written'),
    jsonb_build_object('number',32,'answer',E'bought'),
    jsonb_build_object('number',33,'answer',E'have lost'),
    jsonb_build_object('number',34,'answer',E'went'),
    jsonb_build_object('number',35,'answer',E'has lived'),
    jsonb_build_object('number',36,'answer',E'has already started'),
    jsonb_build_object('number',37,'answer',E'tried'),
    jsonb_build_object('number',38,'answer',E'has cut'),
    jsonb_build_object('number',39,'answer',E'have / been'),
    jsonb_build_object('number',40,'answer',E'moved'),
    jsonb_build_object('number',41,'answer',E'has stolen'),
    jsonb_build_object('number',42,'answer',E'graduated'),
    jsonb_build_object('number',43,'answer',E'haven''t eaten'),
    jsonb_build_object('number',44,'answer',E'has sung'),
    jsonb_build_object('number',45,'answer',E'moved'),
    jsonb_build_object('number',46,'answer',E'has been / since'),
    jsonb_build_object('number',47,'answer',E'have studied / for'),
    jsonb_build_object('number',48,'answer',E'has waited / for'),
    jsonb_build_object('number',49,'answer',E'have been / since'),
    jsonb_build_object('number',50,'answer',E'has worked / since'),
    jsonb_build_object('number',51,'answer',E'have been / for'),
    jsonb_build_object('number',52,'answer',E'hasn''t seen / since'),
    jsonb_build_object('number',53,'answer',E'has been / for'),
    jsonb_build_object('number',54,'answer',E'hasn''t drunk / since'),
    jsonb_build_object('number',55,'answer',E'have tried / for'),
    jsonb_build_object('number',56,'answer',E'has been / since'),
    jsonb_build_object('number',57,'answer',E'has been / for')
  );
  a := a || jsonb_build_array(
    jsonb_build_object('number',58,'answer',E'already'),
    jsonb_build_object('number',59,'answer',E'yet'),
    jsonb_build_object('number',60,'answer',E'never'),
    jsonb_build_object('number',61,'answer',E'ever'),
    jsonb_build_object('number',62,'answer',E'yet'),
    jsonb_build_object('number',63,'answer',E'just'),
    jsonb_build_object('number',64,'answer',E'never'),
    jsonb_build_object('number',65,'answer',E'still'),
    jsonb_build_object('number',66,'answer',E'already'),
    jsonb_build_object('number',67,'answer',E'ever'),
    jsonb_build_object('number',68,'answer',E'has gone'),
    jsonb_build_object('number',69,'answer',E'have been'),
    jsonb_build_object('number',70,'answer',E'has been'),
    jsonb_build_object('number',71,'answer',E'has gone'),
    jsonb_build_object('number',72,'answer',E'have gone'),
    jsonb_build_object('number',73,'answer',E'have been'),
    jsonb_build_object('number',74,'answer',E'have been'),
    jsonb_build_object('number',75,'answer',E'has gone'),
    jsonb_build_object('number',76,'answer',E'have been'),
    jsonb_build_object('number',77,'answer',E'has gone'),
    jsonb_build_object('number',78,'answer','3'),
    jsonb_build_object('number',79,'answer','1'),
    jsonb_build_object('number',80,'answer','2'),
    jsonb_build_object('number',81,'answer','4'),
    jsonb_build_object('number',82,'answer','3'),
    jsonb_build_object('number',83,'answer','2'),
    jsonb_build_object('number',84,'answer','1'),
    jsonb_build_object('number',85,'answer','4'),
    jsonb_build_object('number',86,'answer','1'),
    jsonb_build_object('number',87,'answer','2'),
    jsonb_build_object('number',88,'answer','3'),
    jsonb_build_object('number',89,'answer',E'has finished'),
    jsonb_build_object('number',90,'answer',E'saw'),
    jsonb_build_object('number',91,'answer',E'were'),
    jsonb_build_object('number',92,'answer',E'ridden'),
    jsonb_build_object('number',93,'answer',E'have known'),
    jsonb_build_object('number',94,'answer',E'has gone'),
    jsonb_build_object('number',95,'answer',E'lost'),
    jsonb_build_object('number',96,'answer',E'began'),
    jsonb_build_object('number',97,'answer',E'hasn''t written'),
    jsonb_build_object('number',98,'answer',E'visited'),
    jsonb_build_object('number',99,'answer',E'have been'),
    jsonb_build_object('number',100,'answer',E'was'),
    jsonb_build_object('number',101,'answer',E'She has never broken her arm.'),
    jsonb_build_object('number',102,'answer',E'Have you ever travelled abroad?'),
    jsonb_build_object('number',103,'answer',E'My friend has already met him.'),
    jsonb_build_object('number',104,'answer',E'I haven''t seen a football match since last year.'),
    jsonb_build_object('number',105,'answer',E'Emma has just won a prize.'),
    jsonb_build_object('number',106,'answer',E'I have known her for years.'),
    jsonb_build_object('number',107,'answer',E'We have known each other since 2012.'),
    jsonb_build_object('number',108,'answer',E'How long has she lived here?'),
    jsonb_build_object('number',109,'answer',E'Have you booked tickets yet?'),
    jsonb_build_object('number',110,'answer',E'I have worked with famous people for years.')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('현재완료 Step 1', '현재완료', q, a, 'problem', 'interactive');
END $$;
