DO $$
DECLARE
  v_questions jsonb;
  v_answer_key jsonb;
BEGIN
  DELETE FROM naesin_templates WHERE title = '지각동사 Step2';

  v_questions := jsonb_build_array(
    jsonb_build_object('number', 1, 'question', E'다음 문장의 빈칸에 들어갈 말로 가장 적절한 것은?\n\nI felt something ___ under my foot.', 'options', jsonb_build_array(E'crunch', E'crunched', E'crunching', E'to crunch', E'to crunching'), 'answer', '1,3'),
    jsonb_build_object('number', 2, 'question', E'다음 문장의 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nSora ___ someone knocking on the door.', 'options', jsonb_build_array(E'heard', E'felt', E'watched', E'told', E'noticed'), 'answer', '4'),
    jsonb_build_object('number', 3, 'question', E'다음 빈칸에 들어갈 말로 바르게 짝지어진 것은?\n\n• I heard someone ⓐ ___ about the test results.\n• I saw the children ⓑ ___ in the rain.', 'options', jsonb_build_array(E'talking - played', E'to talk - playing', E'talked - played', E'talking - playing', E'talk - to play'), 'answer', '4'),
    jsonb_build_object('number', 4, 'question', E'다음 문장의 빈칸에 들어갈 말로 적절한 것을 모두 고르면?\n\nShe watched him ___.', 'options', jsonb_build_array(E'leave', E'left', E'to leave', E'leaving', E'have left'), 'answer', '1,4'),
    jsonb_build_object('number', 5, 'question', E'다음 빈칸에 들어갈 말로 알맞은 것을 모두 고르면?\n\nI heard my name ___ from across the hall.', 'options', jsonb_build_array(E'call', E'called', E'calling', E'to call', E'was called'), 'answer', '2,3'),
    jsonb_build_object('number', 6, 'question', E'다음 빈칸에 들어갈 말로 적절하지 않은 것은?\n\nMy dad ___ me take out the trash.', 'options', jsonb_build_array(E'watched', E'saw', E'made', E'asked', E'helped'), 'answer', '4'),
    jsonb_build_object('number', 7, 'question', E'다음 빈칸에 들어갈 수 있는 것을 모두 고르면?\n\nI ___ Junho performing a magic trick on the stage.', 'options', jsonb_build_array(E'saw', E'made', E'helped', E'watched', E'noticed'), 'answer', '1,4,5'),
    jsonb_build_object('number', 8, 'question', E'다음 빈칸에 들어갈 말로 알맞은 것을 모두 고르면?\n\nShe felt her wallet ___ from her bag.', 'options', jsonb_build_array(E'take', E'takes', E'taking', E'taken', E'to take'), 'answer', '3,4'),
    jsonb_build_object('number', 9, 'question', E'다음 문장의 빈칸에 공통으로 들어갈 말로 적절하지 않은 것은?\n\n• I ___ something fall from the shelf.\n• I ___ the door slam shut.', 'options', jsonb_build_array(E'got', E'heard', E'felt', E'noticed', E'watched'), 'answer', '1'),
    jsonb_build_object('number', 10, 'question', E'다음 문장의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?\n\n• I heard my phone (A) ___ in my bag.\n• She watched the flag (B) ___ in the wind.', 'options', jsonb_build_array(E'ringing - wave', E'to ring - waving', E'rang - waved', E'ringing - waving', E'ring - to wave'), 'answer', '4'),
    jsonb_build_object('number', 11, 'question', E'다음 문장의 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?\n\n• I saw a window (A) ___ by the strong wind.\n• I heard my dog (B) ___ outside all night.', 'options', jsonb_build_array(E'breaking - barking', E'broken - barking', E'broke - barked', E'broken - to bark', E'break - barked'), 'answer', '2'),
    jsonb_build_object('number', 12, 'question', E'다음 두 문장을 한 문장으로 바르게 연결한 것은?\n\n• I see my brother.\n• He is jogging along the river.', 'options', jsonb_build_array(E'I see my brother jogs along the river.', E'I see my brother jogged along the river.', E'I see my brother to jog along the river.', E'I see my brother jogging along the river.', E'I see my brother to be jogging along the river.'), 'answer', '4'),
    jsonb_build_object('number', 13, 'question', E'다음 빈칸에 들어갈 알맞은 것은?\n\nShe heard the news. Minjun had been chosen as the captain.\n= She heard ___.', 'options', jsonb_build_array(E'the news Minjun chosen as the captain', E'Minjun chosen as the captain', E'Minjun being chosen as the captain', E'the news Minjun being chosen as the captain', E'Minjun to be chosen as the captain'), 'answer', '3'),
    jsonb_build_object('number', 14, 'question', E'다음 빈칸 ⓐ, ⓑ, ⓒ에 들어갈 말로 바르게 짝지어진 것은?\n\n• Sora heard her father ⓐ ___ the violin.\n• He felt the floor ⓑ ___ beneath him.\n• I watched them ⓒ ___ about the plan.', 'options', jsonb_build_array(E'playing - to shake - talking', E'to play - shake - talked', E'was playing - to shake - talking', E'playing - shaking - talking', E'play - to shake - talked'), 'answer', '4'),
    jsonb_build_object('number', 15, 'question', E'다음 ⓐ~ⓓ 빈칸에 알맞은 말로 바르게 짝지어진 것은?\n\nLast weekend I visited my grandparents. I saw grandma ⓐ[cook / cooking] in the kitchen. I heard grandpa ⓑ[to sing / singing] his favorite song. I also noticed the cat ⓒ[sleeping / to sleep] on the sofa. They all looked ⓓ[relaxed / relaxing]!', 'options', jsonb_build_array(E'cooking - to sing - sleeping - relaxed', E'cooking - singing - sleeping - relaxed', E'cook - to sing - to sleep - relaxing', E'cooking - singing - to sleep - relaxed', E'cook - singing - sleeping - relaxing'), 'answer', '2'),
    jsonb_build_object('number', 16, 'question', E'다음 우리말과 일치하도록 주어진 단어를 바르게 배열한 것은?\n\n나는 내 가방이 누군가에 의해 옮겨지는 것을 느꼈다.\n(carried / felt / my bag / I / by someone)', 'options', jsonb_build_array(E'I felt my bag carrying by someone.', E'I felt my bag carried by someone.', E'I felt my bag carry by someone.', E'I felt carried my bag by someone.', E'Carried by someone I felt my bag.'), 'answer', '2'),
    jsonb_build_object('number', 17, 'question', E'다음 우리말을 바르게 영작한 것은?\n\n나는 고양이 한 마리가 지붕 위에서 달리는 것을 보았다.', 'options', jsonb_build_array(E'I saw a cat running on the roof.', E'I saw a cat to run on the roof.', E'I saw a cat ran on the roof.', E'I saw a cat runs on the roof.', E'I saw a cat to running on the roof.'), 'answer', '1'),
    jsonb_build_object('number', 18, 'question', E'다음 우리말을 바르게 영작한 것은?\n\n나는 내 자전거가 누군가에 의해 도둑맞는 것을 보았다.', 'options', jsonb_build_array(E'I saw my bike stealing by someone.', E'I saw my bike to steal by someone.', E'I saw my bike stolen by someone.', E'I saw someone steal my bike.', E'I watched my bike was stolen by someone.'), 'answer', '3,4'),
    jsonb_build_object('number', 19, 'question', E'다음 우리말을 바르게 영작한 것은? (정답 2개)\n\n우리는 누군가가 창문을 깨는 소리를 들었다.', 'options', jsonb_build_array(E'We heard someone breaking the window.', E'We heard someone broke the window.', E'We heard the window broken by someone.', E'We heard to break the window someone.', E'We heard someone break the window.'), 'answer', '1,5'),
    jsonb_build_object('number', 20, 'question', E'다음 중 어법상 옳은 문장은?\n\n① I saw my friend to read a book in the library.\n② Jinho heard Sujin talked on the phone.\n③ She felt someone touched her arm gently.\n④ Kevin saw his sister dancing in her room.\n⑤ I heard the news announced on TV this morning.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '4,5'),
    jsonb_build_object('number', 21, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I listened to his coach talk to the team.\n② I watched the whole class clean up together.\n③ I heard you sing at the school festival.\n④ I saw the puppy smiling at its owner.\n⑤ Did you see Minji to plant those flowers?', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '5'),
    jsonb_build_object('number', 22, 'question', E'다음 중 어법상 옳은 문장은?\n\n① Jisu saw him crossed the finish line.\n② Mr. Kim watched a student to dance on stage.\n③ Sora felt someone to tap her shoulder.\n④ I saw the door left open all night.\n⑤ She heard the train arrived at the station.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '4'),
    jsonb_build_object('number', 23, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I felt something crawling on my neck.\n② I saw two men carry heavy boxes.\n③ I heard him humming in the shower.\n④ I saw a wall painted by local artists.\n⑤ I watched my sister to dance at the concert.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '5'),
    jsonb_build_object('number', 24, 'question', E'다음 중 어법상 옳은 문장은?\n\n① Nobody saw him took the bag.\n② Did you hear the singer sang a ballad?\n③ I saw the car repaired at the garage.\n④ She felt someone came over behind her.\n⑤ The little boy heard his mom to call his name.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '3'),
    jsonb_build_object('number', 25, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I saw my friend to study hard in the library.\n② Nobody saw him take the bag.\n③ He felt someone touch his shoulder.\n④ Did anyone see you wash the car?\n⑤ I watched the package being delivered to my door.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '1'),
    jsonb_build_object('number', 26, 'question', E'다음 중 어법상 옳은 문장은?\n\n① I didn''t hear her came in last night.\n② I saw Joe to read my diary secretly.\n③ I felt someone to touch my shoulder.\n④ I watched the boy running across the street.\n⑤ I heard a famous singer to perform at the concert.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '4'),
    jsonb_build_object('number', 27, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I saw Hyunwoo run down the hallway.\n② I saw Jiyeon going home after school.\n③ I heard Minsu sang a solo at the concert.\n④ I heard her calling my name from outside.\n⑤ I felt my room shake during the earthquake.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '3'),
    jsonb_build_object('number', 28, 'question', E'다음 중 어법상 옳은 문장은?\n\n① They felt the bridge shook.\n② I heard someone call my name just now.\n③ I looked at Sally crossed the street.\n④ We listened to someone playing the piano beautifully.\n⑤ My mom is watching a cat runs after a bird.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '2,4'),
    jsonb_build_object('number', 29, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I can smell something burning in the oven.\n② Have you ever seen him smiling like that?\n③ She watched her son swim across the pool.\n④ We heard her singing a beautiful song.\n⑤ He saw Rachel to stand on the bench.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '5'),
    jsonb_build_object('number', 30, 'question', E'다음 중 어법상 옳은 문장은?\n\n① I heard Jimin calling me from downstairs.\n② I saw people to shake hands at the ceremony.\n③ She heard him shouts at the top of his lungs.\n④ Jason hears the birds sang in the garden.\n⑤ He felt his mother touches his forehead gently.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '1'),
    jsonb_build_object('number', 31, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I felt the ground to move under me slowly.\n② Did anyone see you wash the dishes?\n③ Jisu saw her cleaning the window after school.\n④ She heard him talk on the phone in the hallway.\n⑤ Where did you notice him running away to?', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '1'),
    jsonb_build_object('number', 32, 'question', E'다음 중 어법상 옳은 문장은? (정답 2개)\n\n① He watched people living in tents on the news.\n② Can you smell something burning on the stove?\n③ She felt something touches her arm suddenly.\n④ I saw your sister takes the subway every morning.\n⑤ I could hear her singing her favorite song.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '1,2,5'),
    jsonb_build_object('number', 33, 'question', E'다음 중 어법상 어색한 문장은?\n\n① I watched her playing the piano at the recital.\n② Have you ever seen him sleeping on the bus?\n③ Did you see the people crossed the street?\n④ I felt the chair moving back little by little.\n⑤ We watched the full moon rising over the sea.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '3'),
    jsonb_build_object('number', 34, 'question', E'다음 중 어법상 올바른 문장을 모두 고르면?\n\n① I saw you to enter the room.\n② She felt something coming toward her.\n③ I watched my son play with his friend.\n④ She heard her sister was locking the door.\n⑤ I saw the window broken by the storm.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '2,3,5'),
    jsonb_build_object('number', 35, 'question', E'다음 중 어법상 어색한 문장은?\n\n① They felt the bridge shake violently.\n② We heard him playing the guitar last night.\n③ They saw the kite flown by the little girl.\n④ She told me sing on the stage.\n⑤ I watched the boy wait for the bus patiently.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '4'),
    jsonb_build_object('number', 36, 'question', E'다음 중 어법상 옳은 문장은? (정답 2개)\n\n① I heard someone calling my name from behind.\n② You can''t hear the car to come close.\n③ I saw my sister clean the room herself.\n④ I heard the train to arrive at the station.\n⑤ Sora saw the old man helped across the road.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', '1,3'),
    jsonb_build_object('number', 37, 'question', E'다음 밑줄 친 부분 중 어법상 어색한 것은?\n\n① Minho heard his little sister <u>crying</u> in her room.\n② She felt the ground <u>shake</u> under her feet.\n③ We heard our names <u>to call</u> by the teacher.\n④ I saw an old man <u>cross</u> the busy street alone.\n⑤ They saw the teacher <u>coming</u> into the classroom.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', E'3'),
    jsonb_build_object('number', 38, 'question', E'다음 밑줄 친 부분 중 어법상 어색한 것은?\n\n① I can smell something <u>to burn</u> in the kitchen.\n② I saw Jiyeon <u>walking</u> along the riverside.\n③ Did you see him <u>cleaning</u> his room?\n④ Did you hear the bird <u>sing</u> on the tree?\n⑤ She heard her brother <u>playing</u> the piano.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', E'1'),
    jsonb_build_object('number', 39, 'question', E'다음 밑줄 친 부분 중 어법상 어색한 것은?\n\n① She saw her brother <u>play</u> baseball after school.\n② We heard you <u>singing</u> in front of people.\n③ My teacher told me <u>to clean</u> my room.\n④ I made my brother <u>to finish</u> his homework early.\n⑤ I heard the song <u>played</u> on the radio.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', E'4'),
    jsonb_build_object('number', 40, 'question', E'다음 밑줄 친 부분 중 어법상 어색한 것은?\n\n① I saw Yumi <u>do</u> her homework at the library.\n② He felt a breeze <u>blowing</u> through the window.\n③ My mother made me <u>clean</u> my room every weekend.\n④ Mina had her wallet <u>stolen</u> on the bus.\n⑤ She heard the children <u>to sing</u> together.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', E'5'),
    jsonb_build_object('number', 41, 'question', E'다음 밑줄 친 부분 중 어법상 어색한 것은? (정답 2개)\n\n① I saw her <u>to stand</u> at the entrance.\n② Let''s watch Minjun <u>swimming</u> in the pool.\n③ She heard someone <u>call</u> her nickname.\n④ Junho felt the waves <u>touched</u> his feet.\n⑤ They got up when he smelled the food <u>burning</u>.', 'options', jsonb_build_array(E'①', E'②', E'③', E'④', E'⑤'), 'answer', E'1,4'),
    jsonb_build_object('number', 42, 'question', E'다음 중 어법상 옳은 문장의 총 개수는?\n\n• They felt the building shake last night.\n• I heard them to playing violins and flutes.\n• Did you hear someone walking in the room?\n• She saw the letter written in red ink.\n• James watched the boys playing tennis in the gym.', 'options', jsonb_build_array(E'1개', E'2개', E'3개', E'4개', E'5개'), 'answer', E'4'),
    jsonb_build_object('number', 43, 'question', E'다음 중 어법상 옳은 문장을 모두 골라 짝지은 것은?\n\nⓐ I can hear the bell ring.\nⓑ I feel my confidence getting stronger.\nⓒ She heard the child cries.\nⓓ He hears the students laughing.\nⓔ They saw him wearing that hat.', 'options', jsonb_build_array(E'ⓐ, ⓑ, ⓓ', E'ⓑ, ⓒ, ⓓ', E'ⓒ, ⓓ, ⓔ', E'ⓐ, ⓑ, ⓒ, ⓔ', E'ⓐ, ⓑ, ⓓ, ⓔ'), 'answer', E'5'),
    jsonb_build_object('number', 44, 'question', E'다음 중 어법상 옳은 문장을 모두 골라 짝지은 것은?\n\nⓐ I felt the ground shook suddenly.\nⓑ I couldn''t hear a car coming toward me.\nⓒ I didn''t hear the phone ringing.\nⓓ I saw my jacket taken by a stranger.\nⓔ I saw my sister dance on the stage.', 'options', jsonb_build_array(E'ⓐ, ⓔ', E'ⓑ, ⓓ', E'ⓒ, ⓔ', E'ⓐ, ⓒ, ⓔ', E'ⓑ, ⓒ, ⓓ, ⓔ'), 'answer', E'5'),
    jsonb_build_object('number', 45, 'question', E'다음 중 어법상 옳은 문장을 모두 골라 짝지은 것은?\n\nⓐ I felt somebody to see me.\nⓑ I heard her open the window carefully.\nⓒ She is listening to the bird singing.\nⓓ I saw Jisu waiting for her friend.\nⓔ He will not listen to his daughter to say.\nⓕ I watched the boy running across the street.', 'options', jsonb_build_array(E'ⓐ, ⓒ', E'ⓑ, ⓕ', E'ⓒ, ⓔ', E'ⓐ, ⓓ, ⓕ', E'ⓑ, ⓓ, ⓔ'), 'answer', E'2')
  );

  v_answer_key := jsonb_build_array(
    jsonb_build_object('number',1, 'answer','1,3'),
    jsonb_build_object('number',2, 'answer','4'),
    jsonb_build_object('number',3, 'answer','4'),
    jsonb_build_object('number',4, 'answer','1,4'),
    jsonb_build_object('number',5, 'answer','2,3'),
    jsonb_build_object('number',6, 'answer','4'),
    jsonb_build_object('number',7, 'answer','1,4,5'),
    jsonb_build_object('number',8, 'answer','3,4'),
    jsonb_build_object('number',9, 'answer','1'),
    jsonb_build_object('number',10, 'answer','4'),
    jsonb_build_object('number',11, 'answer','2'),
    jsonb_build_object('number',12, 'answer','4'),
    jsonb_build_object('number',13, 'answer','3'),
    jsonb_build_object('number',14, 'answer','4'),
    jsonb_build_object('number',15, 'answer','2'),
    jsonb_build_object('number',16, 'answer','2'),
    jsonb_build_object('number',17, 'answer','1'),
    jsonb_build_object('number',18, 'answer','3,4'),
    jsonb_build_object('number',19, 'answer','1,5'),
    jsonb_build_object('number',20, 'answer','4,5'),
    jsonb_build_object('number',21, 'answer','5'),
    jsonb_build_object('number',22, 'answer','4'),
    jsonb_build_object('number',23, 'answer','5'),
    jsonb_build_object('number',24, 'answer','3'),
    jsonb_build_object('number',25, 'answer','1'),
    jsonb_build_object('number',26, 'answer','4'),
    jsonb_build_object('number',27, 'answer','3'),
    jsonb_build_object('number',28, 'answer','2,4'),
    jsonb_build_object('number',29, 'answer','5'),
    jsonb_build_object('number',30, 'answer','1'),
    jsonb_build_object('number',31, 'answer','1'),
    jsonb_build_object('number',32, 'answer','1,2,5'),
    jsonb_build_object('number',33, 'answer','3'),
    jsonb_build_object('number',34, 'answer','2,3,5'),
    jsonb_build_object('number',35, 'answer','4'),
    jsonb_build_object('number',36, 'answer','1,3'),
    jsonb_build_object('number',37, 'answer','3'),
    jsonb_build_object('number',38, 'answer','1'),
    jsonb_build_object('number',39, 'answer','4'),
    jsonb_build_object('number',40, 'answer','5'),
    jsonb_build_object('number',41, 'answer','1,4'),
    jsonb_build_object('number',42, 'answer','4'),
    jsonb_build_object('number',43, 'answer','5'),
    jsonb_build_object('number',44, 'answer','5'),
    jsonb_build_object('number',45, 'answer','2')
  );

  INSERT INTO naesin_templates (title, template_topic, questions, answer_key, category, mode)
  VALUES ('지각동사 Step2', '지각동사', v_questions, v_answer_key, 'problem', 'interactive');
END;
$$;
